### ISSUE TITLE
Syntax error when create table by schema tool.

### ISSUE THREAD

**Issue by sliver** [doctrine/dbal#2]
Syntax error when create table by schema tool.
Connection driver is pdo_sqlite.

  [PDOException]
  SQLSTATE[HY000]: General error: 1 near "AUTOINCREMENT": syntax error

**Comment by chrisguitarguy** [comment]
Fairly sure this can be closed. The change mentioned was added in 2.X. If it was breaking, it was part of a major version and okay by semver.

All the issues mentioned here seem to be random stack traces and things.
