### ISSUE TITLE
Fulltext index on unique column ignored 

### ISSUE THREAD

**Issue by csasarak** [doctrine/dbal#2248]
I'm working on a MariaDB database with a table with a name which is set to be unique on the table. I also want a fulltext index which is supported with the flags variable in Doctrine annotations as described [here](http://www.doctrine-project.org/jira/browse/DDC-3014). The problem is that when I try to generate a migration (or even create the schema) Doctrine ignores the fact that the fulltext index is different than the index it would create for the unique constraint and doesn't bother making the fulltext index. 

The main reason I want to use fulltext rather than a normal index is because MariaDB can return a [relevance](https://mariadb.com/kb/en/mariadb/fulltext-index-overview/#relevance) score for any matches, unlike using SQL's "LIKE". This can be worked around by adding a 'where' clause to the options parameter to the effect of "where id is not null", which is always true but convinces Doctrine that this index is different than the uniqueness index. 

An example entity of what I'm describing might look like this:
```php
/**
 * 
 *
 * @ORM\Table("fieldname", 
    uniqueConstraints={@ORM\UniqueConstraint(name="name", columns={"name"})},  
    indexes={@ORM\Index(name="fulltext_index", 
                        columns={"name"},
                        flags={"fulltext"})})
 * @ORM\Entity
 */
class ExampleEntity {
    /**
     * @ORM\Id
     * @ORM\Column(name="id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;
}
```

I'm willing to dive in and try to make Doctrine aware of the fact that if there's a flags variable on such an index annotation, then it should still create the index. I'm aware my use case is probably pretty idiosyncratic. First I wanted to make sure that this wasn't purposeful and that it makes sense to consider this a bug that's worth fixing.

**Comment by Ocramius** [comment]
@csasarak ouch: we actually specifically added logic to get rid of duplicate indexes where possible.

Maybe we should change the logic so that indexes with different (incompatible) properties are still considered as separate?

**Comment by csasarak** [comment]
I figured that you had, and that behavior was so in line with the principle of least surprise that I was able to find out what was wrong in my application pretty quickly. I mostly wanted some feedback because I'm not sure how often this would really come up, and I have mixed feelings about having made a separate index on that column anyhow. 

I'm going to have a look at the code and see if I can find stuff that would break if we did that.

**Comment by deeky666** [comment]
@Ocramius I think that is not entirely true, because lately this is exactly what we tried to change (having Doctrine drop "duplicate" index definitions implicitly). You remember we had a discussion about this and came to the conclusion that responsibility for those kind of things should be moved to the user.
@csasarak this is most likely an issue with ORM mappings and its schema tool. Which ORM version are you using? Because there have been some changes about this in the last few months...

**Comment by deeky666** [comment]
I think I got it. Schema tool is dropping the fulltext index silently [here](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Tools/SchemaTool.php#L294-L297). This looks kinda wrong to me... /cc @Ocramius

**Comment by deeky666** [comment]
Commit https://github.com/doctrine/doctrine2/commit/699a6e1783f4443a3bb6bc129f6cc7130db1b5ff has changed that behaviour. Looking at the test model, the mapping looks wrong anyways as it explicitly defines the semantically same index twice (one time via `unique` column attribute, second time via `UniqueConstraint` table index).
I think the use case of that change is plain wrong and a misuse of the mappings. IMO you should EITHER have `unqiue` defined on a column OR have a more advanced unqiue constraint at table level but not both. So IMO that particular changes needs to be reverted. Am I wrong here?

**Comment by csasarak** [comment]
@deeky666 I am using this as part of a Symfony2 project. Composer says that I am using doctrine/orm v2.5.2

**Comment by paquitodev** [comment]
I am running this same issue with Symfony 2.8 and:

    # composer show -i
    ...
    doctrine/common                          v2.5.2             Common Library for Doctrine projects
    doctrine/dbal                            v2.5.2             Database Abstraction Layer
    doctrine/doctrine-bundle                 1.6.1              Symfony DoctrineBundle
    doctrine/doctrine-cache-bundle           1.2.2              Symfony Bundle for Doctrine Cache
    doctrine/inflector                       v1.1.0             Common String Manipulations with regard to casing and singular/plural rules.
    doctrine/instantiator                    1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
    doctrine/lexer                           v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
    doctrine/orm                             v2.5.2             Object-Relational-Mapper for PHP
    ...

**Comment by deeky666** [comment]
@csasarak as this is clearly an ORM issue with the schema tool, I will close this issue here. Could you please open up a new one in the ORM issue tracker and link this issue? Thanks!
