### ISSUE TITLE
Compatibility mis-match? PGSQL_ATTR_DISABLE_PREPARES in v2.5.2 (in a PHP 5.6.16 envt)

### ISSUE THREAD

**Issue by c5creative** [doctrine/dbal#2249]
Greetings,

I'm coming up empty on the following observation. I'm not sure if it's an issue or not, and perhaps someone here could advise.

I went ahead and installed doctrine/dbal 2.5.2 (via composer) into a project running atop of PHP 5.6.16, and I'm using pgsql as my backend database. I was previously running 2.5.1 on a PHP 5.3.* without issue. 

In connecting via dbal to the database, I am seeing this now:
` Fatal error: Undefined class constant 'PGSQL_ATTR_DISABLE_PREPARES' in /path-to-files/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php on line 49`

That block is shown:
```php
if (PHP_VERSION_ID >= 50600
                && (! isset($driverOptions[PDO::PGSQL_ATTR_DISABLE_PREPARES])
                    || true === $driverOptions[PDO::PGSQL_ATTR_DISABLE_PREPARES]
                )
            ) {
                $pdo->setAttribute(PDO::PGSQL_ATTR_DISABLE_PREPARES, true);
            }
```

If I comment out this entire block, the fatal error goes away and things *seem* to work normally. I'm not comfortable just commenting this out, since I don't know the full ramifications of such an action.

Any advice is much appreciated and I hope I'm not breaking any conventions by reporting this here. Thanks!

JP

**Comment by Ocramius** [comment]
This is bizarre... What version of the PGSQL driver is currently installed? That constant *should* be defined...

**Comment by deeky666** [comment]
Weird indeed. When compiling with `pdo_pgsql` the class constant [should always be registered](https://github.com/php/php-src/blob/php-5.6.16/ext/pdo_pgsql/pdo_pgsql.c#L89).
Maybe there is something wrong with your `pdo_pgsql` setup?

**Comment by c5creative** [comment]
Thank you both - let me gather up some more info.

**Comment by garcher** [comment]
I also have this issue. And my PDO class has alot of constants, but none of them is PGSQL_ATTR_DISABLE_PREPARES. At which version this block of code was added?

**Comment by deeky666** [comment]
@c5creative that version is from 2006 oO. How did you intall the extension? Looks like you installed via the deprecated PECL package maybe? The extension is part of the PHP core for a long time now and should be installed / built from there. Wondering how such an old version can even be compatible with PHP 5.6...

**Comment by deeky666** [comment]
okay tried to make the check more robust so that DBAL doesn't crash if the constant is not available.
