### ISSUE TITLE
Oracle platform errors in PHP 7

### ISSUE THREAD

**Issue by arcostasi** [doctrine/dbal#2256]
I'm having the following error with doctrine-orm-module 0.9.2 in PHP 7:

ORA-01862: the numeric value does not match the length of the format item in vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractOracleDriver.php:76

Any Solution? Thanks.

**Comment by avlima** [comment]
I am having the same problem. :(

**Comment by DeepDiver1975** [comment]
PHP7, Oracle and dbal seem to have somre more issues - I'm currently trying to setup an php7 oracle ci system ....

https://ci.owncloud.org/job/doctrine-dbal-oracle/PHP=7.0.0,label=SLAVE/

But there are some issues we need to get sorted out before we see the whole picture ...

https://github.com/doctrine/dbal/pull/2251

**Comment by Ocramius** [comment]
Can anyone dig up the list of changes in the oracle driver for PHP7? There may have been breakages there...

**Comment by DeepDiver1975** [comment]
http://php.net/ChangeLog-7.php lists only 3 items

OCI8:

    Fixed memory leak with LOBs.
    Fixed bug #68298 (OCI int overflow).
    Corrected oci8 hash destructors to prevent segfaults, and a few other fixes.

**Comment by Ocramius** [comment]
That's not the entire list of fixes since 5.6.x.

For instance, RC8 included some LOB fixes - https://github.com/php/php-src/blob/php-7.0.0RC8/NEWS

I can't seem to do a [decent search](https://bugs.php.net/search.php?search_for=&boolean=0&limit=All&order_by=&direction=DESC&cmd=display&status=Open&bug_type=All&project=All&package_name[]=PDO+OCI&package_name[]=OCI8+related&package_name[]=Oracle+related&php_os=&phpver=&cve_id=&assign=&author_email=&bug_age=0&bug_updated=0) on OCI8/PDO OCI on the php-src issue tracker:

**Comment by arcostasi** [comment]
I had problem with the official oci8 2.0.8, and I got a new oci8 2.1.0 changed in a remi repository of the CentOS and this worked with php 7, but with doctrine the problem still happens.

It's the oci8 2.1.0: http://arcostasi.com/download/oci8.so

**Comment by amaroRafael** [comment]
I'm getting the same error when try persist object.

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO log_auth (id, username, type, ip, user_agent, DATA_CRIACAO, id_usuario) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [9776, "user", 4, "201.86.94.44", "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/47.0.2526.80 Safari\/537.36", "2015-12-11 11:56:00", "122"]: ORA-01862: the numeric value does not match the length of the format item
```

**Comment by arcostasi** [comment]
I did a new test and found something, I set the last field to null and get error in the first field that is required, but the first parameter was set! What I can deduce, the doctrine overwriting all fields with the last param!

ORA-01400: cannot insert NULL into ("LOG_AUTH"."ID")

An exception occurred while executing 'INSERT INTO log_auth (id, username, type, ip, user_agent, created, user_id) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [9794, "test", 4, "201.86.94.44", "cURL", "2015-12-11 15:55:55", null]:

**Comment by Ocramius** [comment]
Any previous exceptions that we could look at?

**Comment by arcostasi** [comment]
http://pastebin.com/jTgBZbC8

**Comment by Ocramius** [comment]
Could you show the state of that `OCI8Statement`, as well as what is passed to `fromErrorInfo`?

**Comment by arcostasi** [comment]
Hi Ocramius, this is the log of method execute on Statement, I removed only connection params.

error_log('PARAMS: ' . print_r($params, true) . PHP_EOL . print_r($this, true), 3, statement-dump.log);

http://arcostasi.com/statement-dump.log

**Comment by Ocramius** [comment]
Cleaned it up and this is what is relevant:

```
PARAMS: 
Doctrine\DBAL\Statement Object
(
    [sql:protected] => INSERT INTO log_auth (id, username, type, ip, user_agent, DATA_CRIACAO, id_usuario) VALUES (?, ?, ?, ?, ?, ?, ?)
    [params:protected] => Array
        (
            [1] => 9807
            [2] => arcostasi
            [3] => 4
            [4] => 201.86.94.44
            [5] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36
            [6] => Base\Util\DateTimeBr Object
                (
                    [date] => 2015-12-11 16:55:26.000000
                    [timezone_type] => 3
                    [timezone] => America/Sao_Paulo
                )

            [7] => 
        )

    [types:protected] => Array
        (
            [1] => bigint
            [2] => string
            [3] => integer
            [4] => string
            [5] => string
            [6] => datetime
            [7] => bigint
        )

    [stmt:protected] => Doctrine\DBAL\Driver\OCI8\OCI8Statement Object
        (
            [_dbh:protected] => Resource id #424
            [_sth:protected] => Resource id #490
            [_conn:protected] => Doctrine\DBAL\Driver\OCI8\OCI8Connection Object
                (
                    [dbh:protected] => Resource id #424
                    [executeMode:protected] => 0
                )

            [_defaultFetchMode:protected] => 2
            [_paramMap:protected] => Array
                (
                    [1] => :param1
                    [2] => :param2
                    [3] => :param3
                    [4] => :param4
                    [5] => :param5
                    [6] => :param6
                    [7] => :param7
                )

        )

    [platform:protected] => Doctrine\DBAL\Platforms\OraclePlatform Object
        (        )

    [conn:protected] => Doctrine\DBAL\Connection Object
        (
        )

)
```

**Comment by Ocramius** [comment]
I'm closing this - it is evident that the problem lies inside the implementation of `oci_execute`, which is outside our scope.

**Comment by cjbj** [comment]
It's quite possible that Doctrine needs to make sure that zvals used at bind time are still available at execute time - as always has been recommended.  The core zval ref counting optimizations in PHP 7's VM can cause different behavior to PHP 5.6 and this is known to have affected OCI8 apps.

**Comment by arcostasi** [comment]
I think the doctrine support for Oracle is not good! 
We have already shown one way to solve, and it was not taken seriously! They do not listen and do nothing about it!

**Comment by Ocramius** [comment]
There is an open PR about it (which needs work), see #2386. Moderate your tone, @arcostasi.

Also, we do stuff when we have time, since we're not paid to do [any of the free stuff you are using](https://github.com/doctrine/dbal/blob/7dd848b7afdf065966daebcac3c134f90ba2bcdd/LICENSE)

**Comment by arcostasi** [comment]
Ok, just my opinion @Ocramius! I think it's not as free as you talk, many things in my work had to refactor!

**Comment by Ocramius** [comment]
@arcostasi yeah, but that's your work, not your free time ;-)

**Comment by arcostasi** [comment]
many things I had to do in my free time!

**Comment by Ocramius** [comment]
> @Ocramius many things I had to do in my free time!

"had to" + free time => collision.

I'm not here to tell you how to fix your work environment issues, tho.

**Comment by arcostasi** [comment]
I know @Ocramius, my work is not the problem! We also provide a free fix to solve temporarily some problem that other developer may have. https://github.com/doctrine/dbal/issues/2261

**Comment by soyuka** [comment]
@arcostasi the #2261 adds an issue with Oci-Lob that I'm trying to solve in #2386, I'll work on it asap (we're almost there)
