### ISSUE TITLE
(mssql) Problem with method addColumn when i need to set default in existing table with data

### ISSUE THREAD

**Issue by tjura** [doctrine/dbal#2265]
When i use code $schema->getTable('users')->addColumn('sex' , 'integer')->setDefault(0)
Doctrine built two Queries: 
1. Alter table...
and second
2. Add constraint

Migrations throws errow on first query.

Error shows up only when i have data in table users.

I found solution, adding custom SQLServer2012Platform but there is a lot of private method that i need to copy.

A simillar problem happend when a try drop column with constraint.

**Comment by deeky666** [comment]
@inferno1992 can you please provide exact details on how to reproduce this issue? I'm afraid the information you provided is insufficient for a decent investigation.

**Comment by kalinowcyk** [comment]
I've got the same problem. 
This is how to reproduce: 
1) I have a table filled with data, database is MSSQL Server,
2) I've made a migration like this:
```
<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160906134946 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
		$schema->getTable('my_table')->addColumn('my_column', 'integer')->setNotnull(false)->setDefault(0);

    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
```
3) When I run this migration, I've got an error:
```
Migration 20160906134946 failed during Execution. Error An exception occurred while executing 'ALTER TABLE my_table ADD my_column INT NOT NULL':

SQLSTATE[42000]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]ALTER TABLE only allows columns to be added that can contain nulls, or have a DEFAULT definition specified, or the column being added is an identity or timestamp column, or alternatively if none of the previous conditions are satisfied the table must be empty to allow addition of this column. Column 'my_column' cannot be added to non-empty table 'my_table' because it does not satisfy these conditions.
```

**Comment by morozov** [comment]
Closing as fixed by https://github.com/doctrine/dbal/pull/4447. Please reopen if it's not.
