### ISSUE TITLE
PHP compatibility broken

### ISSUE THREAD

**Issue by NVasse** [doctrine/dbal#2269]
Since this commit 90b2f0c6725380abad92ced7f8a1346705d3c901, I have the following error : 
``FatalErrorException in ProxyGenerator.php line 62:
Parse Error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING)``

Here is the code :
```PHP 
protected $placeholders = [
        'baseProxyInterface'   => Proxy::class,
        'additionalProperties' => '',
    ];
```

I guess this is because of the PHP requirement which has not been increased to PHP > 5.4

**Comment by Ocramius** [comment]
`doctrine/common` 2.6.1 requires PHP 5.5+. What version of `doctrine/common` do you have installed?

**Comment by NVasse** [comment]
``  - Updating doctrine/common (2.5.x-dev 11b994b => 2.6.x-dev 99b55ad)``
``  - Updating doctrine/cache dev-master (bc23e0f => 619c3d4)``
``  - Updating doctrine/dbal 2.5.x-dev (e4a9c02 => 8f7e5c5)``

**Comment by Ocramius** [comment]
Hah, typical case of "I ran `composer update` on a system that doesn't resemble production".

Closing, sorry :-)
