### ISSUE TITLE
Removed Unsigned Integer Support in SQL Server (and unsupported platforms)

### ISSUE THREAD

**Issue by scalp** [doctrine/dbal#2283]
Hi,

In my opinion [PR-207](https://github.com/doctrine/dbal/pull/207) didn't remove full support in SQL Server of **UNSIGNED integer**.

Like [ISSUE-1695](https://github.com/doctrine/dbal/issues/1695) for SQLite, _Schema\Comparator_ return differences for each column with "unsigned => true" attribute.

As i see, **UNSIGNED integer** is not available from neither SQL Server, PostgreSQL, SQLite, DB2, ...

I tried to see in which way it would be possible to fix it :
1. i think the best way would be to remove "unsigned" from defaults attributes and switch it to _Schema\Column\PlatformOptions_ or a newer property like **PlatformAttributes**. The problem is that it is a lot of work and will cause BC breaks.
2. another way, would be to add a method **supportsUnsignedInteger** in _Platforms\AbstractPlatform_ and test it in _Schema\SchemaDiff_toSql_ method to don't add SQL lines if unsupported. But i've an unresolved problem with this option, if (int) type change (small int to int for example) or nullable property.
3. last way was to inject **Platform** in _Schema\Comparator_ and test support (like previous point with **$platform->supportsUnsignedInteger**) in _Schema\Comparator\diffColumn_ method.

What do you think about theses solutions ? I can make a PR for solution 2 or 3. First way is too complicated for me and maybe a little bit unreasonable.

**Comment by deeky666** [comment]
@scalp I'm not sure if I get the issue here. Where is SQL Server platform even using `unsigned`? Please provide us some information on how to reproduce the actual issue. Thanks!

**Comment by scalp** [comment]
Hi @deeky666, it's the same issue as [ISSUE-1695](https://github.com/doctrine/dbal/issues/1695) but for SQLServer.

Requests are finely generated without ``UNSIGNED`` attribute by DBAL but *Schema\Comparator* method always detect differences on syncing methods.

It's because *Schema\SQLServerSchemaManager->createSchema* return a *Schema\Schema* without ``UNSIGNED`` attribute for concerned columns (as SQLServer doesn't support it) whereas *Tool\SchemaTool->getSchemaFromMetadata* return a *Schema\Schema* with ``UNSIGNED`` attribute. So when [*Schema\Comparator->diffColumn*](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/Comparator.php#L428-L432) check differences, it returns an ``unsigned`` changed properties for each concerned column.

Impact is schema and database are never consider as sync for exemple by command like "doctrine:schema:update" whereas they are. For instance, it's a problem when you use third libraries which defines ``unsigned => true`` in schema.

**Comment by deeky666** [comment]
@scalp got it now. Thanks for reporting. Unfortunately the comparator isn't platform aware so vendor specific comparator issues have to be dealt with (and is already done) in the platform's `getAlTerTableSQL()` method when generating SQL for the column diffs. The issue should be fixed there.

**Comment by scalp** [comment]
I understand comparator isn't platform aware.

But why in your opinion this should be fixed in 
*Platforms\SQLServerPlatform->getAlterTableSQL* instead of modify these lines of [*Schema\SchemaDiff->_toSql*](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/SchemaDiff.php#L198-L200). For instance with a new platform method like ``$platform->supportsUnsignedInteger`` and a check on each ``changedColumns`` if ``ColumnDiff->changedProperties`` contains only ``unsigned`` then don't execute ``getAlterTableSQL`` ?

**Comment by deeky666** [comment]
@scalp the problem with that approach is, that it doesn't fix `getAlterTableSQL()` it self which can be used directly without `SchemaDiff`. Also the root problem is not solved by adding additional `supports*()` method to the platform as there are many other different vendor specific semantics for table alteration that cannot be abstracted easily. For example some platform disallow altering from specific column types to others (each vendor having their own constraints).
Those vendor specific constraints are already dealt with in `getAlterTableSQL()` methods as it is the only place where to fix these things properly. For 2.x we won't do any big changes to that approach.

**Comment by bartfeenstra** [comment]
We ran into this problem last week, as we started migrating a project from MariaDB to SQL Server. I agree with @deeky666 that `Comparator` is platform-unaware and that's not where we should address this. However, while is the platform that builds the SQL, for schema validation it's `SchemaTool` building the schema that includes unsigned definitions in the first place.

**Comment by morozov** [comment]
As of https://github.com/doctrine/dbal/pull/4746, schema comparison is schema-aware. Could somebody verify if this issue is still relevant?

**Comment by bartfeenstra** [comment]
I changed jobs a few weeks ago, and I am no longer able to test this. Sorry for the inconvenience!

**Comment by morozov** [comment]
Then I'll close it given that the issue doesn't contain reproduction steps.
