### ISSUE TITLE
Implement exception conversion for retryable exceptions in Oracle drivers

### ISSUE THREAD

**Issue by deeky666** [doctrine/dbal#2289]
As of https://github.com/doctrine/dbal/pull/718 `2.6` will receive new exceptions for retryable transactions. However the implementation for Oracle based drivers is still missing and must be implemented before `2.6` to avoid having a partially supported feature over all vendors.

**Comment by Ocramius** [comment]
@deeky666 can you check this one if you have time? If this doesn't get fixed, I'm fine with simply dropping it from the `2.6` milestone and have somebody with more oracledb knowledge look at it instead.

**Comment by Ocramius** [comment]
Removing milestone for now - this is not really a blocker, as all you get on OracleDB with this is non-retriable exceptions then.

**Comment by morozov** [comment]
This is unlikely to be implemented in the foreseeable future. We can reopen the issue once somebody decides to address it.
