### ISSUE TITLE
The QueryBuilder::getSQLForSelect() always appends a FROM clause for select queries

### ISSUE THREAD

**Issue by kabirbaidhya** [doctrine/dbal#2291]
Running queries without `FROM` clause is not possible currently with the `Doctrine\DBAL\Query\QueryBuilder`.

For instance we have these queries: 

`SELECT EXISTS(...)`
`SELECT some_function(1, 1)`

We would probably write something like this: 
`$qb->select('EXISTS (...)')`
And, `$qb->select('my_function(1, 1)')`

But, when we do `$qb->execute()` it would fail because, internally the `FROM` clause is being appended to the SQL every time we use `QueryBuilder::select()`. 

Here's, the part of `QueryBuilder::getSQLForSelect()` that's responsible for this. 
```php
    /**
     * @return string
     *
     * @throws \Doctrine\DBAL\Query\QueryException
     */
    private function getSQLForSelect()
    {
        $query = 'SELECT ' . implode(', ', $this->sqlParts['select']) . ' FROM ';

        $query .= implode(', ', $this->getFromClauses())
```
https://github.com/doctrine/dbal/blob/a3a86aa50ebfe180ac5943cce90a40262041bbdf/lib/Doctrine/DBAL/Query/QueryBuilder.php#L1108-L1111

I have come across a lot of scenarios, where we need to run `SELECT` without `FROM`. But, it's not possible right now. 

Eg: If I want to check if the user exists in the database, I would want to do: 
`SELECT EXISTS(SELECT 1 FROM user WHERE id = :userId)` as this is the fastest way

But, I have been using this type of query as a work around
`SELECT COUNT(id) FROM user WHERE id = :userId` which is comparatively slower than the first one. 
http://stackoverflow.com/questions/7471625/fastest-check-if-row-exists-in-postgresql#answer-16467634

**Comment by Ocramius** [comment]
@kabirbaidhya does this need to be implemented/supported by the query builder? Is there any particular reason why a query like `SELECT EXISTS(SELECT 1 FROM user WHERE id = :userId)` can't simply be thrown at a DB connection? It is very specific, and some engines don't support it in the `SELECT` clause anyway.

**Comment by deeky666** [comment]
@kabirbaidhya We used to keep `QueryBuilder` in DBAL as simple as possible and it should not be thought of a complete complex query builder that covers everything. It is not an AST and platform agnostic so we won't be able to do complex things safely. We surely will rework the Query component in `3.0`, maybe we can consider it there.
For if you really want to use the query builder for subqueries you have 2 options (not tested though):

1. Put the raw subquery SQL into `$qb->select()` or `$qb->addSelect()`
2. Create another `QueryBuilder` instance for the subquery and add it to the main query via `$qb->select($subQb)` or `$qb->addSelect($subQb)`. However you will have to take care of bound parameters from the sub query builder yourself I suppose.

**Comment by kabirbaidhya** [comment]
In case of `SELECT EXISTS(SELECT 1 FROM user WHERE id = :userId)` yes we can say it is not supported by the all the engines. But, there are many other cases like `SELECT some_function(..) AS val`, which is common across all the engines.

So, in my opinion although it's not a must have thing, I think its a good to have feature to support `SELECT`s without `FROM` as currently we can't have them. This would add some more flexibility.

**Comment by deeky666** [comment]
@kabirbaidhya okay seems I totally misunderstood the actual issue. Now I do. This seems to be an easy fix. Also I'd even consider this a bug as we should not generate `FROM` clause if no table were specified. Will do a PR.

**Comment by deeky666** [comment]
Patch created in #2292

**Comment by kabirbaidhya** [comment]
:+1:

**Comment by mesaugat** [comment]
:+1:
