### ISSUE TITLE
SQLParserUtils treats brackets in Postgres like quoting characters

### ISSUE THREAD

**Issue by maryo** [doctrine/dbal#2295]
After this commit (https://github.com/doctrine/dbal/commit/646f479a6a816044e2116e17416113b33de380e3#diff-e7dd540cfb86c74ce7361e2bd00053cf
  added because of SQL Server) SQLParserUtils::getUnquotedStatementFragments() treats brackets like quoting character. This is OFC fine in case of SQL Server. But Postgres does not use brackets for strings or escaping but for example as an array constructor like `ARRAY[20000, 25000, 25000, 25000]`.

Let's say I have an SQL like this: `SELECT * FROM a WHERE jsonb_exists_any(a.b, ARRAY[:parameter]) = false` and i want to set an array parameter. Then SQLParserUtils treats `[?]` as a quoted statement and does not expand the array parameter like it does in other cases,.

This class cannot be universal as the behavior should depend on the platform. So maybe the platform should be the place where this is set.

Another, quick way is to change the regular expression to not treat `[...]` like `ARRAY[...]`... That would still be probably better than it's now.

**Comment by deeky666** [comment]
@maryo I was expecting some issue like this to come sooner or later. You pointed out the reasons already, so no need to explain further. I'll see what we can do about it in 2.x.

**Comment by deeky666** [comment]
@maryo patch created in https://github.com/doctrine/dbal/issues/2296
