### ISSUE TITLE
Sequence in _getPortableTableColumnDefinition PostgreSqlSchemaManager

### ISSUE THREAD

**Issue by agrazian** [doctrine/dbal#2298]
Hi,
I'm using PostgreSQL 9.3 and i have to retrieve the lastInsertId after an insert.
I use the connection method

```
$connection->lastInsertId($sequenceName)
```

But i need to know the Sequence name associated with the specific table (the table already exists in the database), and to do that i use the SchemaManager. 
I use the listTableColumns method 

```
$schemaManager->listTableColumns($tableName);
```

and cycle to all columns till i find the sequence name associated with the primary key column.

In Line 249 of _getPortableTableColumnDefinition method
https://github.com/doctrine/dbal/blob/2.4/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php#L249
a sequence entry for the tableColumn array  is been created

```
$tableColumn['sequence'] = $matches[1];
```

but is never used in the rest of the method, and i was wondering why of this, because i need to retrieve the sequence name associated with the Column.

One solution could be having this code

```
if (isset($tableColumn['sequence']) && !empty($tableColumn['sequence'])) {
    $column->setPlatformOption('sequence', $tableColumn['sequence']);
}
```

on the bottom of the _getPortableTableColumnDefinition method.

So that i can retrieve, having a column instance, the sequence name with this code 

```
$options = $column->getPlatformOptions();
if (!empty($options) && isset($options['sequence'])) {
    return $options['sequence'];
}
```

any hints?

**Comment by deeky666** [comment]
@agrazian DBAL doesn't provide direct relations between sequences and columns. Setting the `sequence` attribute as platform option will cause trouble with the schema comparator and lead to unwanted diffs when comparing online and offline schemas. Also platform options is not really the right place for this. How was the sequence in question created? If it was created via a `SERIAL` column type, you can simply build the sequence name own your own I think. According to [this](http://www.postgresql.org/message-id/1098938001.7477.3.camel@vacant) the sequence is always named like `<table_name>_<column_name>_seq`.
