### ISSUE TITLE
Doctrine (DBAL) Error Handling while Executing Multiple Queries

### ISSUE THREAD

**Issue by feridmovsumov** [doctrine/dbal#2299]
I have an schema sql file (with syntax error) including multiple queries for settings database

example.sql

``` sql
CREATE TABLE IF NOT EXISTS `example` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;


CREATExxxxxxxxxx TABLE IF NOT EXISTS `example2` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` text COLLATE utf8_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;
```

example.php

``` php
$sqlContent = file_get_contents("example.sql");
$stmt = $conn->prepare($sqlContent);
$result = $stmt->execute();
```

execute method doesn't throw any exception even that my sql is incorrect. it documentation says it returns false on failure but it returns true.

How should I do exception hanling here? How can I check if my query has an error?

**Comment by deeky666** [comment]
@feridmovsumov this is an interesting edge case. PHP database drivers do not handle multi queries very well. Tested this on `pdo_mysql` and it indeed doesn't error if the second query fails. But it does fail with `SyntaxErrorException` if the first one is invalid. `mysqli` does error regardless, whether the first or the second one is invalid. Unfortunately PDO seems to execute one by one, so if the first is valid and the second not, the first one will still have been executed (resulting in the table being created). `mysqli` seems to validate syntax of all queries first before actually executing anything (resulting in no table being created at all).
This is a tricky one and I am not sure how DBAL should behave here (or if we even can make behaviour consistent between drivers).

**Comment by ovcharenkovv** [comment]
and what if you wrap both qery in transaction ?

**Comment by geekwright** [comment]
MySQL does an Implicit Commit on each CREATE. That stops the transaction after the first statement.
http://dev.mysql.com/doc/refman/5.7/en/implicit-commit.html

**Comment by tomasfejfar** [comment]
We hit this after 4 years from the original issue in Doctrine migrations:

```
$this->addSql("
CREATE TABLE test (id INT);
ALTER TABLE test DROP COLUMN myName;
");
```

Super hard to debug! 

It would be best if multiple queries in one go would result in error or at least warning.

**Comment by tomasfejfar** [comment]
Also https://stackoverflow.com/questions/39395262/why-does-doctrine-2-migration-silently-fail-in-symfony-project

**Comment by morozov** [comment]
The DBAL (almost) doesn't do any parsing of the queries before passing them to the underlying driver. Introducing an additional parsing phase to address the issue of the PHP's drivers is unjustified.

**Comment by tomasfejfar** [comment]
Couldn't it at least check number of resultsets of the query afterwards?

**Comment by morozov** [comment]
Does PHP even support the execution of multiple semicolon-separated SQL statements? UPD: see the [source](https://github.com/php/php-src/blob/f23164584ec145895e3f086c8c23c5e443fb1472/ext/mysqli/mysqli_nonapi.c#L659).

Here's an example in PHP:
```php
<?php

$conn = mysqli_connect('127.0.0.1', 'root', '', 'tmp');

if (!$conn) {
    exit(1);
}

$statement = 'CREATE TABLE t1(id INT); CREATE TABLE t2(id INT);';

try {
    mysqli_query($conn, $statement);
} catch (mysqli_sql_exception $e) {
    echo $e->getMessage(), PHP_EOL;
    exit(1);
}
```
It produces the following error:

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE t2(id INT)' at line 1

The same statement works in the command-line client:
```
mysql> CREATE TABLE t1(id INT); CREATE TABLE t2(id INT);
Query OK, 0 rows affected (0.04 sec)

Query OK, 0 rows affected (0.03 sec)

mysql> show tables;
+---------------+
| Tables_in_tmp |
+---------------+
| t1            |
| t2            |
+---------------+
2 rows in set (0.00 sec)
```
