### ISSUE TITLE
Composer not updating. Man in the middle attack?

### ISSUE THREAD

**Issue by antonioribeiro** [doctrine/dbal#2311]
Composer is not updating nor installing packages because of this error:

![error](https://i.imgur.com/Ju9EN1V.png)

I'm able to download that [file](http://packagist.org/p/provider-2015%2488e82faf543cdeb3bb4bd6f9d7abc172bd75eeb176125ee9e24fa113fa60742a.json) via wget and browser, so I'm not sure what to do with this.

Is there a way to manually check the file signature?

**Comment by Ocramius** [comment]
This can happen when github changes the zip package checksum (package is re-generated). We can't do much about it, as we don't generate those zip files ourselves.

Closing as `Can't fix`.
