### ISSUE TITLE
QueryBuilder::getSQLForInsert function maybe much better?

### ISSUE THREAD

**Issue by mvatansever** [doctrine/dbal#2312]
In file : **Doctrine/DBAL/Query/QueryBuilder.php**

```
private function getSQLForInsert()
{
        return 'INSERT INTO ' . $this->sqlParts['from']['table'] .
        ' (' . implode(', ', array_keys($this->sqlParts['values'])) . ')' .
        ' VALUES(' . implode(', ', $this->sqlParts['values']) . ')';
}
```

If i set a value with **setValue** function which type of string value the **getSQLForInsert()** function produce invalid insert string because didn't put the **'** character start of value and end of value. So return to wrong insert sql string. 

Example:

`INSERT INTO contents (content, user_id) VALUES(Something like a lorem ipsum, 157);`

This content does not add because string **content** value not wrapped with **'** character. Necessarily I use raw SQL string with parameters?

**Comment by beyazkurt** [comment]
So I now found "values" function but this function maybe much better then this, thanks :)

**Comment by beyazkurt** [comment]
Or I use "values" function after the insert() same thing is happening:

```
        $qb->insert("summary")
           ->values(array(
               "content" => $value['content'],
               "user_id" => $value['user_id']
           ))
           ->execute();
```

Return of this function is same:

`INSERT INTO contents (content, user_id) VALUES(Something like a lorem ipsum, 157);`

**Comment by morozov** [comment]
The inputs that the query builder accepts are SQL expressions, not values. The current behavior is by design.
