### ISSUE TITLE
DateIntervalType supports conversion of invalid values

### ISSUE THREAD

**Issue by MisatoTremor** [doctrine/dbal#2314]
The current implementation allows to convert a DateInterval to DB values that can not be converted back to PHP values. As a side node the DB field length of the type of 20 could not hold these values.

Intervals with values that overflow their moduli like `P53W` or `P100M` will yield these DB values:  `P0000-00-371T00:00:00` or `P0000-100-00T00:00:00`.
While these exceed the declared 20 character field length they are also invalid as per ISO 8601 and the PHP manual. If they were tried to be converted back to a DateInterval an exception would be thrown (e.g. 'DateInterval::__construct(): Unknown or bad format (P0000-00-371T00:00:00)')

Maybe DateIntervals should be saved in the `PnYnMnDTnHnMnS` format which allows overflowing.

Ping @vbartusevicius

**Comment by vbartusevicius** [comment]
Initially `PnYnMnDTnHnMnS` was in my original implementation, but later @zeroedin-bill suggested to use datetime format (https://github.com/doctrine/dbal/pull/854#issuecomment-112848030) as it's sortable in db.
So if @zeroedin-bill would suggest to use `PnYnMnDTnHnMnS` - I will refactor current implementation

**Comment by zeroedin-bill** [comment]
@MisatoTremor @vbartusevicius It's a very good point, but I'm not sure how to satisfy both conditions that the database representation be sortable and the format is comprehensive.

**Comment by Ocramius** [comment]
Note that changing a format that landed in a stable version is not possible

**Comment by MisatoTremor** [comment]
@vbartusevicius @zeroedin-bill When saving it normalized like ``PnnYnnMnnDTnnHnnMnnS`` with ``'P'.$value->format('%YY%MM%DDT%HH%IM%SS')`` it would be almost as sortable as it is now. Only exception is that the year will have 2 instead of 4 digits

@Ocramius Afaik there is no stable release with the DateIntervalType in it, yet.

**Comment by vbartusevicius** [comment]
@MisatoTremor - you're right, there is no `DateIntervalType` in https://github.com/doctrine/dbal/tree/v2.5.4/lib/Doctrine/DBAL/Types

So if @zeroedin-bill will agree, I could quickly make some changes to `DateIntervalType` to internally store in @MisatoTremor's suggested format `'P' . $value->format('%YY%MM%DDT%HH%IM%SS')`

**Comment by vbartusevicius** [comment]
Created a PR: https://github.com/doctrine/dbal/pull/2316

**Comment by Ocramius** [comment]
Handled in #2316
