### ISSUE TITLE
Better output for RunSqlCommand

### ISSUE THREAD

**Issue by trompette** [doctrine/dbal#2319]
On tag `v2.5.4`, the dumper used is quite simple: 

https://github.com/doctrine/dbal/blob/v2.5.4/lib/Doctrine/DBAL/Tools/Console/Command/RunSqlCommand.php#L83

It would be nice to use a dumper supporting highlighting like:

https://github.com/symfony/var-dumper/blob/3c2f3b6d45a3098450bd1a10376d1d50918006b5/Dumper/CliDumper.php

What do you think?

**Comment by Ocramius** [comment]
@trompette I think that's a decent improvement, but I don't see any handling for maximum depth?

**Comment by trompette** [comment]
@Ocramius This dumper is used in Symfony, and Doctrine related objects can be dumped without error. I am not sure where this behaviour is implemented though.

**Comment by Ocramius** [comment]
@trompette I see high chances of chaos whenever something with a circular reference is dumped

**Comment by trompette** [comment]
@Ocramius AFAIK, this use case is handled by the VarDumper component.
