### ISSUE TITLE
 Doctrine DBAL type boolean for SQLite

### ISSUE THREAD

**Issue by SebTM** [doctrine/dbal#2338]
I'm a new developer of the open-source project called Poweradmin. (Also hosted here on Github)

We want to move away from some old and outdated libraries which got copied through our code. As our software provides a management webinterface for PowerDNS we need to have the sql-schema provided by PowerDNS installed. It will not proved by our software!

If I want to connect to a SQLite database containing the default-schema of PowerDNS for SQLite, I get the following error:

> Fatal error: Uncaught exception 'Doctrine\DBAL\DBALException' with message 'Unknown database type bool requested, Doctrine\DBAL\Platforms\SqlitePlatform may not support it.'

Until now I can't find a solution how to solve this? You can find the sql-schema for SQLite with PowerDNS here: https://doc.powerdns.com/md/authoritative/backend-generic-sqlite/

**Comment by Ocramius** [comment]
@SebTM we use [`BOOLEAN`](https://github.com/doctrine/dbal/blob/61e1f860a304c3fb6961ecbec36927b5f20b71c6/lib/Doctrine/DBAL/Platforms/SqlitePlatform.php#L201) to map fields. Do you have the DDL of the table that is being loaded by the schema tools?

**Comment by SebTM** [comment]
@Ocramius What do you mean with DDL?

In my first Post above you find a link to the Powerdns Doku, this sql-schema is installed to SQLite database. The error occurred on connecting to database. 

Later on I want to create the sql-schema specified here https://github.com/poweradmin/poweradmin/blob/installer-v2/install/includes/database_structure.php

**Comment by Ocramius** [comment]
Ah yes, so the fields are mapped (for example) as `auth                  BOOL DEFAULT 1,`.

The simplest way to fix this, for now, is mapping the `bool` type to `boolean` via [`AbstractPlatform#registerDoctrineTypeMapping()`](https://github.com/doctrine/dbal/blob/61e1f860a304c3fb6961ecbec36927b5f20b71c6/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L391)

**Comment by morozov** [comment]
I don't see `BOOL` mentioned in the SQLite [documentation](https://www.sqlite.org/datatype3.html), so I assume it's supported for backward compatibility or something like this.

I believe the issue should be fixed on the consumer side by using `BOOLEAN` which is documented in SQLite and is supported by the DBAL.
