### ISSUE TITLE
Bug when changing column from NOT NULL to NULL

### ISSUE THREAD

**Issue by svlcomyoo** [doctrine/dbal#2345]
When changing a column to be nullable when the generated query will not reflect this.

I have only been able to test this with a non 5.7 mysql.

A fix that i tried local (and works) is to change line 2225 in Platforms/AbstractPlatform@getColumnDeclarationSQL from
$notnull = (isset($field['notnull']) && $field['notnull']) ? ' NOT NULL' : '';
to
$notnull = (isset($field['notnull']) && $field['notnull']) ? ' NOT NULL' : ' NULL';

I was trying to make a pull request for this, but failed (havent been working with github for that long)

**Comment by morozov** [comment]
I cannot reproduce this on `3.2.x` with MySQL 5.7:
```php
$table = new Table('test');
$table->addColumn('id', 'integer', ['notnull' => true]);

$sm = $connection->createSchemaManager();
$sm->createTable($table);

$table->getColumn('id')
    ->setNotnull(false);

$comparator = $sm->createComparator();
$diff = $comparator->diffTable($sm->listTableDetails('test'), $table);
$sm->alterTable($diff);
```
The above produces:
```sql
CREATE TABLE test (id INT NOT NULL)
ALTER TABLE test CHANGE id id INT DEFAULT NULL
```
The resulting table looks like this:
```sql
CREATE TABLE test (id INT NULL)
```
