### ISSUE TITLE
Table Options not documented in  Annotation reference

### ISSUE THREAD

**Issue by rijnhard** [doctrine/dbal#2352]
In the annotations reference the table options are not documented.

http://docs.doctrine-project.org/en/latest/reference/annotations-reference.html#annref-table

``` php
**
 * @Entity
 * @Table(name="user",
 *      uniqueConstraints={@UniqueConstraint(name="user_unique",columns={"username"})},
 *      indexes={@Index(name="user_idx", columns={"email"})}
 *      schema="schema_name"
 *      options={
 *           "collate"="utf8mb4_unicode_ci",
 *           "charset"="utf8mb4",
 *           "engine"="InnoDB",
 *           "auto_increment"="",
 *           "comment"="",
  *          "row_format"=""
 *      }
 * )
 */
class User { }
```

I just pulled these from the MySqlPlatform, I'm sure there are more. 

Whether this should or not be documented is up for debate. 

**collate:**
https://github.com/doctrine/dbal/issues/2351

**Comment by morozov** [comment]
This doesn't look like a DBAL issue.
