### ISSUE TITLE
PostgreSqlPlatform tstzrange unknown database type

### ISSUE THREAD

**Issue by EspadaV8** [doctrine/dbal#2353]
Trying to alter a postgresql table that has a `tstzrange` which is causing an exception to be thrown

```
[Doctrine\DBAL\DBALException]
Unknown database type tstzrange requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it.
```

Ranges were added in PostgreSQL 9.2 (http://www.postgresql.org/docs/9.2/static/release-9-2.html) and I couldn't see anything listed in `PostgreSQL92Platform` for it either.

**Comment by morozov** [comment]
This type doesn't look portable across supported databases.
