### ISSUE TITLE
sqlite url configuration not working as expected

### ISSUE THREAD

**Issue by nebulousGirl** [doctrine/dbal#2354]
connecting to sqlite using an URL is not working as per the docs:
http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html

The sqlite driver class is looking for a path, but parsing the URL from driver manager does not result in a path param.

**Comment by laoneo** [comment]
This is a duplicate of #1106. You have to wait till 2.5.5 is released or apply the patch from #2267 manually.

**Comment by fabpot** [comment]
2.5.5 is out now, so this one can probably be closed.

**Comment by nebulousGirl** [comment]
This is working now.
