### ISSUE TITLE
Support 5-digits years or do not throws exception on invalid date

### ISSUE THREAD

**Issue by coolmic** [doctrine/dbal#2355]
Postgresql date field support year with more than 5-digits.
It's possible to have 20515-02-01 as value for a date type.

see http://www.postgresql.org/message-id/E1VWUoI-0006WM-8o@gemulon.postgresql.org
http://michael.otacoo.com/postgresql-2/postgres-9-4-feature-highlight-dates-with-more-than-5-digit-years/

I did a frontend which connect to an external postgresql database (used by an intranet), which I have not control.
I want to access a member field, but the birthdate field have values like 19987-01-02 or 20007-11-10.

When I try to query the database, I have this exception  : 

```
Doctrine\DBAL\Types\ConversionException
 Could not convert database value "19987-01-02" to Doctrine Type date. Expected format: Y-m-d
----------------------------------------------------------------------
/private/var/www/xxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/ConversionException.php:63
#0 /private/var/www/xxx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Types/DateType.php(67): Doctrine\DBAL\Types\ConversionException::conversionFailedFormat('19987-01-02', 'date', 'Y-m-d')
#1 /private/var/www/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(297): Doctrine\DBAL\Types\DateType->convertToPHPValue('19987-01-02', Object(Doctrine\DBAL\Platforms\PostgreSQL92Platform))
#2 /private/var/www/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(333): Doctrine\ORM\Internal\Hydration\AbstractHydrator->gatherRowData(Array, Array, Array)
#3 /private/var/www/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/ObjectHydrator.php(165): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateRowData(Array, Array)
#4 /private/var/www/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php(147): Doctrine\ORM\Internal\Hydration\ObjectHydrator->hydrateAllData()
#5 /private/var/www/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(946): Doctrine\ORM\Internal\Hydration\AbstractHydrator->hydrateAll(Object(Doctrine\DBAL\Driver\PDOStatement), Object(Doctrine\ORM\Query\ResultSetMapping), Array)
#6 /private/var/www/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(1749): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadCollectionFromStatement(Array, Object(Doctrine\DBAL\Driver\PDOStatement), Object(Doctrine\ORM\PersistentCollection))
#7 /private/var/www/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(2823): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->loadOneToManyCollection(Array, Object(OrmIntranet\Entity\Famille), Object(Doctrine\ORM\PersistentCollection))
#8 /private/var/www/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php(697): Doctrine\ORM\UnitOfWork->loadCollection(Object(Doctrine\ORM\PersistentCollection))
#9 /private/var/www/xxx/vendor/doctrine/orm/lib/Doctrine/ORM/PersistentCollection.php(214): Doctrine\ORM\PersistentCollection->doInitialize()
#10 /private/var/www/xxx/vendor/doctrine/collections/lib/Doctrine/Common/Collections/AbstractLazyCollection.php(274): Doctrine\ORM\PersistentCollection->initialize()
#11 /private/var/www/xxx/module/Intranet/src/Intranet/Service/IntranetImportService.php(298): Doctrine\Common\Collections\AbstractLazyCollection->getIterator()
```

It seems `DateTime::createFromFormat` failed to parse year with 5 digits.
But `$date->setDate(19987, 1, 2)` works.

As is it now, there is nothing I can do to fetch them, and fix it.
Is it possible to change the code to allow 5-digit years? Or at least return null or a datetime with a default value?

**Comment by Ocramius** [comment]
Doesn't seem to work out of the box: https://3v4l.org/vna1F

`Y` seems to support only 4 digits: `Y 	A full numeric representation of a year, 4 digits 	Examples: 1999 or 2003` (see http://php.net/manual/en/function.date.php )

**Comment by coolmic** [comment]
The method format() support it
https://3v4l.org/p4p7e

We just have to change the parsing code.
Or return 1970-01-01 as fallback. But an exception is too expeditious.
Even others hydration fail.

**Comment by coolmic** [comment]
Is it possible to use a customized type to override the current behaviour?

**Comment by Ocramius** [comment]
Splitting the string in userland seems unfeasible, as the [`DateTimeType`](https://github.com/doctrine/dbal/blob/3df22ccdf20a68fafe34cb1ae452aee7cde7d442/lib/Doctrine/DBAL/Types/DateTimeType.php#L57) varies from platform to platform.

 > Is it possible to use a customized type to override the current behaviour?

Override the `DateTimeType` yourself in your app then (via [`Type::overrideType()`](https://github.com/doctrine/dbal/blob/3df22ccdf20a68fafe34cb1ae452aee7cde7d442/lib/Doctrine/DBAL/Types/Type.php#L223))

**Comment by coolmic** [comment]
Is it possible to override only in the connection context?

I have 2 connections, one with postgresql, and one with mysql. 
I only want to override the date type for postgresql, not for mysql.

**Comment by Ocramius** [comment]
Sadly not: this is one of the pitfalls of DBAL and ORM 2.x, as the type system uses a flyweight static registry.

**Comment by coolmic** [comment]
Ok thanks. I override the DateType with my own

```php

namespace OrmIntranet\Types;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\ConversionException;
use Doctrine\DBAL\Types\Type;

class DateType extends \Doctrine\DBAL\Types\DateType
{
    /**
     * {@inheritdoc}
     */
    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        try {
            return parent::convertToPHPValue($value, $platform);
        } catch (ConversionException $e) {
            $date = new \DateTime();
            if (preg_match('/(\d{4,})-(\d{2})-(\d{2})/', $value, $matches)) {
                $date->setDate($matches[1], $matches[2], $matches[3]);
            }
            return $date;
        }
    }
}
```

I will use instanceof on $platform to determine which connection is used.
