### ISSUE TITLE
MySQL: Create indexes with columns length

### ISSUE THREAD

**Issue by DeepDiver1975** [doctrine/dbal#2368]
With MySQL (and other DBMS as well :question:) is is possible to define the column length to be used within an index

``` sql
CREATE INDEX part_of_name ON customer (name(10));
```

Is there a way to respect this with the schema classes when generating the sql statements?

**Comment by Jean85** [comment]
Documentation refers an `option` array for the `@Index` annotation, but I don't know if `lenght` is supported...

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#annref-index

**Comment by morozov** [comment]
Fixed by #2412.
