### ISSUE TITLE
SQLSrvStatement doesn't respect PDO::PARAM_STR when binding parameters

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#2369]
``` php
$conn = Doctrine\DBAL\DriverManager::getConnection(array(
    'driver' => 'sqlsrv',
    'host' => 'localhost',
    'user' => 'user',
    'password' => 'passw0rd',
    'dbname' => 'test',
));

$conn->executeStatement('CREATE TABLE test(
    id varchar(36) NOT NULL,
    name nvarchar(60) NULL
)');
$conn->executeStatement('INSERT INTO test (id, name) VALUES(\'xxx\', \'Test\')');
$query = 'SELECT name FROM test WHERE id = ?';
$stmt = $conn->prepare($query);
$stmt->bindValue(1, 1, \Doctrine\DBAL\ParameterType::STRING);

try {
    var_dump($stmt->execute()->fetchOne());
} catch (Exception $e) {
    echo $e->getMessage(), PHP_EOL;
}

$conn->executeStatement('DROP TABLE test');

// Outputs: An exception occurred while executing 'SELECT name FROM test WHERE id = ?' with params [1]:
//
// SQLSTATE [22018, 245]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Conversion failed when converting the varchar value 'xxx' to data type int.
```

According to the [implementation of `SQLSrvStatement::bindParam()`](https://github.com/doctrine/dbal/blob/v2.5.4/lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php#L141-L145), it only considers `PDO::PARAM_LOB` if it is specified as `$type` but ignores other types.

The expected behavior is to have SQL Server informed that the parameter is of a string type, not int.

**Comment by slucas-nwx** [comment]
I'm wondering if the problem i'm encountering is the same. I'm trying to send a comma delimited string to my stored procedure but it fails. If i execute the procedure from Mssql directly it works, but if i execute it through doctrine, I get no results back.

`        $statement = $this->em
            ->getConnection()
            ->getWrappedConnection()
            ->prepare('EXEC [dbo].[GetCatalogItems]
                @CultureId = ?,
                @OrderTypeCountryId = ?,
                @TargetDateTime = ?,
                @strSKU = ?'
            );


        $statement->bindValue(1, $cultureId, ParameterType::INTEGER);
        $statement->bindValue(2, $orderTypeCountryId, ParameterType::INTEGER);
        $statement->bindValue(3, $startDateTime, ParameterType::STRING);
        $statement->bindValue(4, $skus, ParameterType::STRING );
        $statement->execute();`

and my test

`    public function test_execute_with_multiple_sku()
    {
        $skus = array('skus'=> array("1000","300203"));
        $skuStr = implode(",", $skus['skus']);
        $result = $this->container->get('nova.stored_procedure.get_catalog_items')->execute(
            1, 50, new \DateTime(), $skuStr
        );

        $this->assertInstanceOf(ArrayCollection::class, $result);
        $this->assertContainsOnlyInstancesOf(GetProductDetail::class, $result);
        $this->assertFalse($result->isEmpty());
    }`

**Comment by morozov** [comment]
> If i execute the procedure from Mssql directly it works

Could you provide the example which works for you? Are you sure the problem is with the comma-separated string, not with the date?

**Comment by slucas-nwx** [comment]
> > If i execute the procedure from Mssql directly it works
> 
> @slucas-nwx, could you provide the example which works for you? Are you sure the problem is with the comma-separated string, not with the date?

This is my proc command.

EXEC [dbo].[GetCatalogItems] 1, 50, '2018-10-15 03:10:50', '1000, 300203'

The date isn't giving me issues, because if i run it like this from symfony it works fine.

EXEC [dbo].[GetCatalogItems] 1, 50, '2018-10-15 03:10:50'

**Comment by morozov** [comment]
@slucas-nwx at a glance, it looks unrelated. Please file a new issue with the steps to reproduce. You may want to strip down your existing procedure to something simple which doesn't contain your business logic but is still prone to the same error.

**Comment by slucas-nwx** [comment]
Ok, if we can't figure it out I will. Thank you

**Comment by morozov** [comment]
Closing as the issue doesn't seem to be fixable at the driver level:
```php
$conn = sqlsrv_connect('127.0.0.1', array(
    'UID' => 'sa',
    'PWD' => 'Passw0rd',
    'Database' => 'master',
));

$stmt = sqlsrv_prepare($conn, 'SELECT IIF(? = \'foo\', 1, 0)', [
    [
        1,
        SQLSRV_PARAM_IN,
        SQLSRV_PHPTYPE_STRING(SQLSRV_ENC_CHAR),
    ]
]);

var_dump(sqlsrv_execute($stmt));
var_dump(sqlsrv_errors());

/*
bool(false)
array(1) {
  [0] =>
  array(3) {
    'SQLSTATE' =>
    string(5) "22018"
    'code' =>
    int(245)
    'message' =>
    string(129) "[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting the varchar value \'foo\' to data type int."
  }
}
*/
```
Even if an integer is bound as a string, it remains to be an integer when it comes to comparison. We cannot cast the value at the DBAL level since the variable may be passed by reference.
