### ISSUE TITLE
Table named user erroneously quoted

### ISSUE THREAD

**Issue by dohpaz42** [doctrine/dbal#2370]
First of all, if this is the wrong part of Doctrine to post this to, forgive me. I'm still a bit wet behind the doctrine ears. I am currently using v2.5.4 of DBAL. 

I have a user table in my database, and when I go to run the following two commands, the output quotes the word user in every possible circumstance it can; this includes file names and class names. See attached screenshot.
![screen shot 2016-04-20 at 4 25 07 pm](https://cloud.githubusercontent.com/assets/2528463/14689264/95db42da-0714-11e6-8bce-4d7cb2045dff.png)

**Comment by Ocramius** [comment]
@dohpaz42 seems like an entity generator bug. Can you re-open this against doctrine/doctrine2 please?

**Comment by dohpaz42** [comment]
@Ocramius Thank you!
