### ISSUE TITLE
getShardManager function not defined

### ISSUE THREAD

**Issue by duhruh** [doctrine/dbal#2371]
The comments for [doctrine/dbal:PoolingShardConnection](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Sharding/PoolingShardConnection.php#L59) indicate that we are able to run the function `getShardManager` on the returned connection. However this will not work since for whatever reason the function `PoolingShardConnection::getShardManager` wasn't carried over from [doctrine/shards:PoolingShardConnection](https://github.com/doctrine/shards/blob/master/lib/Doctrine/Shards/DBAL/PoolingShardConnection.php#L131). Was this intended, or are we responsible for bringing in the sharding library. If we are responsible then i'm not sure why a copy of this exists in it's own repository and in this one.

Edit: okay it looks like `getShardManager` was intentionally removed in this commit https://github.com/doctrine/dbal/commit/b6f48e1ac069d213e040db6170d8df7e0a508ee2 so can the documentation be updated as to the recommend way to get the shard manager and select a shard.

Edit: Okay i didn't feel like waiting 😝  I'm assuming this is the recommended way to handle this now

``` php
        $chooser = new MultiTenantShardChoser();
        $conn = DriverManager::getConnection([
                'wrapperClass' => 'Doctrine\DBAL\Sharding\PoolingShardConnection', 'driver' => 'pdo_mysql',
                'global' =>['user' => '', 'password' => '', 'host' => '', 'dbname' => ''],
                'shards' => [
                    ['id' => 1, 'user' => 'slave1', 'password', 'host' => '', 'dbname' => ''],
                    ['id' => 2, 'user' => 'slave2', 'password', 'host' => '', 'dbname' => ''],
                ],
                'shardChoser' => $chooser,
            ]);

        $shardManager = new PoolingShardManager($conn, $chooser);
        $shardManager->selectGlobal();
        $shardManager->selectShard(1);
```

if so can you update the docs for other poor helpless souls out there struggling with this like me 😄  

last thing if you do update these docs can you guys please update the word `shardChoser` in the code, chooser is spelt with 2 O's i.e. `shardChooser` 

last last thing i also just noticed that there's no reason for `shardChoser` to even be passed into `PoolingShardConnection` as it doesn't reference this at all, unless there's something i'm missing. Since you guys took out `getShardManager` i think that was the only reference to the shard choser, so since you removed one of them, shouldn't you remove both?

**Comment by lorenzleutgeb** [comment]
I just came across the same issue(s). I am happy to provide a PR that fixes documentation and stays backward compatible with 2.5.

@Ocramius would you be willing to receive such a PR?

**Comment by Ocramius** [comment]
Patch ahead 👍

**Comment by morozov** [comment]
Closing as no longer supported (https://github.com/doctrine/dbal/pull/3602).
