### ISSUE TITLE
Some negative float numbers are returned incorrectly

### ISSUE THREAD

**Issue by SoboLAN** [doctrine/dbal#2373]
I use **Doctrine/DBAL 2.5.2** for accessing an **Oracle** database containing latitudes and longitudes.

The values are stored as floats in columns of type `NUMBER`.

Most values are being returned correctly but some are retrieved in a "corrupted form" e.g.:
- If the column contains `-0.123`, then I get the value as `-.123`
- If the column contains `-0.987`, then I get the value as `-.987`.

This happens only for numbers of the form `-0.xxx`.

I'm not 100% sure that the issue is generated by `doctrine/dbal` since we use a custom implementations of the `Doctrine\DBAL\Driver` and `Doctrine\DBAL\Driver\Statement` interfaces and I'm not very familiar with that code. I scanned it from top to bottom and it doesn't seem to contain any pieces of code that change the data after retrieval.

Since those custom implementations are needed in our codebase, it is kind of hard for me to reproduce the issue by using a "naked" instance of `doctrine/dbal`.

If there's any additional information needed, I will do my best to provide it :) .

**Comment by SoboLAN** [comment]
Can someone reproduce this ?

In the next few days I will also try to upgrade to **2.5.4** and see if the problem persists.

**Comment by Ocramius** [comment]
Can't reproduce this with `Doctrine\DBAL\Types\*`. Please try writing a failing test case.

**Comment by SoboLAN** [comment]
@Ocramius I also tried it with a connection that uses OCI8 driver and it behaves exactly the same.

I will try to do some debugging sometime in next few days, maybe I'll narrow it down to only a few statements/types/etc.

**Comment by SoboLAN** [comment]
@Ocramius I closed it because I don't have an Oracle database available with which I can try to to reproduce it.

Given the monstruosity of typical Oracle stuff (because #corporate-bs ), I doubt I'll be able to install something like that.

**Comment by Ocramius** [comment]
@SoboLAN fully understand, but if this is happening, and can be isolated to a unit test (without a running OracleDB instance), then please try to do so.

Marking this as `incomplete`.

**Comment by morozov** [comment]
@SoboLAN why do you consider a value formatted like `-.987` corrupted? It looks valid in PHP:
```php
var_dump((float) '-.987');
// double(-0.987)
```

**Comment by morozov** [comment]
> […] fully understand, but if this is happening, and can be isolated to a unit test (without a running OracleDB instance), then please try to do so.

@Ocramius, it's not a DBAL issue. The `oci` driver formats floats this way:
```php
$stmt = oci_parse($conn, 'SELECT TEST_NUMBER FROM TEST_TABLE');
oci_execute($stmt);
var_dump(oci_fetch_array($stmt));

// array(2) {
//   [0] =>
//   string(5) "-.123"
//   'TEST_NUMBER' =>
//   string(5) "-.123"
}
```
