### ISSUE TITLE
New release coming anytime soon?

### ISSUE THREAD

**Issue by NinoFloris** [doctrine/dbal#2375]
Sorry to be a bit harsh but we have had a dev-master alias like:
```       
"doctrine/dbal": "dev-master as 2.5.x-dev",
````
for months in our project because we need PostgreSQL94Platform for jsonb support.

I would really love to tie this dependency back to a specific version

**Comment by Ocramius** [comment]
2.6 release not coming yet. It will be done when we can do it :-)

Closing here meanwhile.
