### ISSUE TITLE
Explicitly cast old type's value from new type's value when altering a column's type with PostgreSQL

### ISSUE THREAD

**Issue by devantoine** [doctrine/dbal#2376]
When you change a column's type with PostgreSQL, for example from boolean to integer, using the annotation and then run a schema update, you end up with the following error:

> ERROR: column "type" cannot be cast automatically to type integer
> SQL state: 42804
> Hint: You might need to specify "USING type::integer".

I guess the queries generated in `PostgreSqlPlatform::getAlterTableSQL()` have to cast the value with the `USING` statement?

I'm willing to do a PR if it's the right way to proceed but I need some guidelines.

**Comment by shemgp** [comment]
There are times when this can't be done automatically (eg. converting boolean to numeric), so would adding a `using` parameter be feasible?

**Comment by morozov** [comment]
This doesn't look like something that the DBAL should take care of. If Postgres doesn't provide a safe default for this type of conversion, it probably means that the user should make some choice. Similar issues: https://github.com/doctrine/dbal/issues/2783, https://github.com/doctrine/dbal/issues/4748.
