### ISSUE TITLE
AbstractSchemaManager failing on column name "enabled"

### ISSUE THREAD

**Issue by baskettcase** [doctrine/dbal#2377]
I have a column in one of my tables called "enabled" and when 

abstract protected function _getPortableTableColumnDefinition($tableColumn);

is called on that column, from this function _getPortableTableColumnList  then everything fails.

**Comment by Ocramius** [comment]
@baskettcase what's the failure alike?

**Comment by baskettcase** [comment]
No return, it just stops processing. I can't find an error, etc.. now it's actually failing at a different table.. the table right before the table it was failing at previously so Im trying to figure that one out. I have error reporting on, and error logging, but nothing.. it just stops processing.

**Comment by Ocramius** [comment]
@baskettcase able to reproduce the problem in isolation, like in a test?

**Comment by baskettcase** [comment]
At this point now. Im new to doctrine which Im using through pagekit since pagekit uses it.. so Im trying to figure out why the installer is not working in pagekit and have been tracing back the problem to doctrine and my database so far. The error I was getting was a connection error which wasn't helpful and now Im seeing that it is connecting just fine, but there is a problem with the looping of the schema creation.. Ill see if I can force some type of display of errors.. or if you have a script that would test this, that would be helpful also :)

**Comment by baskettcase** [comment]
It's definitely failing on line 849:

abstract protected function _getPortableTableColumnDefinition($tableColumn);

It's just a one line method.. never seen something like that before, so I have no idea what it's doing and how it is doing it without anything in the function...

$tableColumn is equal to 

Array
(
    [Field] => enabled
    [Type] => enum('0','1')
    [Null] => NO
    [Key] => 
    [Default] => 0
    [Extra] => 
    [Comment] => 
    [CharacterSet] => utf8
    [Collation] => utf8_general_ci
)

I don't know if that's enough for you to go on?

**Comment by Ocramius** [comment]
@baskettcase what DB adapter? The [`AbstractSchemaManager` has no such line](https://github.com/doctrine/dbal/blob/3df22ccdf20a68fafe34cb1ae452aee7cde7d442/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php#L839)

**Comment by baskettcase** [comment]
vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php line 839

and I just found the problem.. /DBAL/Platforms/MySqlPlatform.php initializeDoctrineTypeMappings() doesn't have enum.. and the "enabled" field is an enum field type.

and then in the MySqlSchemaManager.php the method _getPortableTableColumnDefinition() has $dbtype and none of those are enum types also.

Have enums been deprecated? or just an oversight in these mappings?

**Comment by Ocramius** [comment]
ENUMs are not supported by doctrine by default (see [this stackoverflow question](http://stackoverflow.com/questions/8750724/what-do-you-use-instead-of-enum-in-doctrine2/9057352#9057352)).

Still that should raise an exception, and not fatal, and it should eventually still show an error message or log the error somewhere.

Please link the code inside the repository, if you find corresponding broken bits, as you may have an installed version that doesn't match up with the current version in the project sources at the moment.

**Comment by baskettcase** [comment]
Im not exactly sure how to do that type of linking.. sounds like a great feature though! Well Im very happy to have finally figured out this problem. I've been working on this for the last couple of days, for hours on end :(

**Comment by Ocramius** [comment]
@baskettcase did you manage to verify if an exception is thrown though? It should definitely not fatal.

As for linking, just browse this repo's source and get the lines at the side of the code:
<img width="169" alt="b82da9" src="https://cloud.githubusercontent.com/assets/154256/14908045/89a59092-0dd1-11e6-936b-9166875f81c7.png">

Then press "Y" to make sure the URL is absolute (points at a specific commit - branches keep moving, commits stay forever).

Then you got a URL to give to us :-)

**Comment by baskettcase** [comment]
Im not seeing any kind of exception being thrown.. but Im also not sure how to test for that either. Just testing... The mapping is found here:

https://github.com/doctrine/dbal/blob/3df22ccdf20a68fafe34cb1ae452aee7cde7d442/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L975

and the AbstractSchemaManager.php that it fails on:
https://github.com/doctrine/dbal/blob/3df22ccdf20a68fafe34cb1ae452aee7cde7d442/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php#L839

Where it is called is here:
https://github.com/doctrine/dbal/blob/3df22ccdf20a68fafe34cb1ae452aee7cde7d442/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php#L820

So Im not sure why it would throw an exception.. do you see a way it would throw an exception instead of a fatal error?

**Comment by Ocramius** [comment]
I can only think of the context (framework/library) that uses DBAL catching or handling exceptions globally, making them impossible for you to track, for some reason.

Anyway, https://github.com/doctrine/dbal/blob/3df22ccdf20a68fafe34cb1ae452aee7cde7d442/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php#L839 leads further down to more code that you should probably step through with a debugger.

**Comment by baskettcase** [comment]
Yeah that piece of code was what led me to enums not being supported. First I had to read up on abstract protected functions since I had no clue what was going on there since there was no code being run, from what I could see.

Ill let PageKit know about this thread and that the problem was found.. maybe they can code in some exceptions. and at least they will know about the enum "problem" and maybe put something in their docs about it.. it would have saved me a massive amount of work.
