### ISSUE TITLE
PHP7 Oracle BLOB/CLOB behavior

### ISSUE THREAD

**Issue by soyuka** [doctrine/dbal#2387]
At the moment, every `\PDO::PARAM_LOB` is considered as a BLOB by the [OCI8Statement](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php#L151):

```php
if ($type == \PDO::PARAM_LOB) {
        $lob = oci_new_descriptor($this->_dbh, OCI_D_LOB);
        //note the type here is OCI_B_BLOB not OCI_B_CLOB             
        $lob->writeTemporary($variable, OCI_TEMP_BLOB);
        return oci_bind_by_name($this->_sth, $column, $lob, -1, OCI_B_BLOB);
}
```

Why is there no different use case when a CLOB is binded?

----

Using php7 (oci >= 1.1.0) and oracle 12 when you create a table from an entity that specifies a `text` property, the database column does end up with a CLOB. Then, try to insert data and you'll get:

```
  ORA-00932: inconsistent datatypes: expected CLOB got BLOB
```

Quick fix above, changing `OCI_B_BLOB` to `OCI_B_CLOB` seems to perform better, but, if a field is binded after the one, you'll get:

```
  ORA-24816: Expanded non LONG bind data supplied after actual LONG or LOB column
```

I think that this is related to the latest oci8 patch but I haven't found any information that could help me fix this.

**Comment by soyuka** [comment]
After digging a bit more, here's the explanation of how the current OCI8Statement works:

- When type is something related to oracle `CLOB` (eg `text`, `json_array`) the PDO type is `\PDO::PARAM_STR`. `OCI8Statement::bindValue`, doesn't create any descriptor. I don't know how this was supposed to work, but it did until now.
- When type is related to oracle `BLOB`, the type is `\PDO::PARAM_LOB` and everything is smooth

Now, to fix oci-related issues with php7, we need to specify that we want either a `CLOB` or a `BLOB` when writing the descriptor. 

See https://github.com/doctrine/dbal/pull/2386#issuecomment-218722069

**Comment by deeky666** [comment]
@soyuka is this still a valid issue?

**Comment by soyuka** [comment]
Yes I think that finally it is #2433 feel free to close if the PR is enough

**Comment by deeky666** [comment]
Hmm I don't think that this issue relates to this. 

This error comes from a misuse of the driver API. For `CLOB` you have to bind the value to `PDO::PARAM_STR`, not `PARAM_LOB`:

```
  ORA-00932: inconsistent datatypes: expected CLOB got BLOB
```

The second error is unrelated because it IS POSSIBLE to insert `CLOB` type column data with `PDO::PARAM_STR` (for example if you just have one VARCHAR2/CLOB column) so it is not caused by wrong binding types. The issue comes up when having mixed type columns in one INSERT and specific ordering in the INSERT column list which is another story IMO. See the PHP bug report I filed today.

**Comment by soyuka** [comment]
Yes I understand totally, but at the time of this issue I hadn't the
knowledge that leads to the php bug ;). Anyway I remember that it lead me
to the PR.
Le jeu. 30 juin 2016 à 20:11, Steve Müller <notifications@github.com> a
écrit :

**Comment by soyuka** [comment]
Closing in favor of the PR adding a test-case for this issue (#2433), which is related to the php bug https://bugs.php.net/bug.php?id=72524.

**Comment by Jabolcnik** [comment]
Hi, I'm watching this #72524 bug very closely as we need this fix. So Im wondering when OCI8 2.1.2 will be released? 

In case this is not in reasonable time ... I need a suggestion how to install a version ov OCI8 with this hotfix included.

**Comment by soyuka** [comment]
It has been fixed a couple days ago just update the oci8 php module.

**Comment by Jabolcnik** [comment]
Thank you for quick answering :) - I had troubles with finding the source code with latest fixes.
I can confirm that lost functionality on php7 with updating records with CLOB is now restored


If anybody else is having same issue with compiling:

The complete procedure for getting all the fixes is:
1) Download soucre from here
http://git.php.net/?p=php-src.git;a=tree;f=ext/oci8;hb=refs/heads/master
By clicking on tar.gz link

2) Extract files
3) Copy all *.h files from oracle client
For example
cp /usr/include/oracle/12.1/client64/*.h /var/tmp/php-src-e6daf03/
4) Compile and install
# phpize
# ./configure
# make
# make install

5) Check php.ini if oci8 is enabled
And viola your freshly compiled oci8.so is installed.
