### ISSUE TITLE
Doubt about async support

### ISSUE THREAD

**Issue by castarco** [doctrine/dbal#2404]
Hello,

I've been searching information about how to work with MySQL in PHP with async queries, and I discovered that mysqli allows doing it, but there's a lot of work to integrate something like that in a clean way.

I know that DBAL works with other databases (not only with MySQL) and does not require a particular driver to run. But I'm wondering if there are plans, or ideas floating in the air about adding async support, in DBAL or in a related project.

Thank you in advance for your time and your responses.

**Comment by Ocramius** [comment]
Nothing like that, at the moment. DB adapters (lower level) are also far
from supporting async operations, so we can't really afford to rewrite the
lower layers ourselves either.
