### ISSUE TITLE
Postgresql BIGSERIAL breaks nullable foreign keys.

### ISSUE THREAD

**Issue by jhogendorn** [doctrine/dbal#2417]
if you specify a primary key as such:

    /**
     * @ORM\Column(name="id", type="bigint", options={ "autoincrement"=true })
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

It correctly defines the id as `BIGSERIAL`, however, all the foreign keys become `BIGSERIAL`'s also. I believe this is incorrect because foreign keys, in some cases can be nullable and default to null, which is incompatible with a `BIGSERIAL` definition. 

I'm no expert for sure, but in this instance `BIGSERIAL` is just shorthand for `BIGINT` with a specific default value for autogenerating the next in sequence, which isnt appropriate for a foreign key at all, and it should just use `BIGINT` for the foreign key type?

**Comment by Ocramius** [comment]
> It correctly defines the id as `BIGSERIAL`, however, all the foreign keys become `BIGSERIAL`'s also. I believe this is incorrect because foreign keys, in some cases can be nullable and default to null, which is incompatible with a `BIGSERIAL` definition. 

Foreign keys must have the same type of the referenced type. If `BIGSERIAL` doesn't support nullability, then this is simply an incompatibility with how foreign keys work, and therefore it is an issue of PostgreSQL.

**Comment by jhogendorn** [comment]
In postgresql bigserial is the same as bigint except it encapsulates the autoincrement behaviour.

https://www.postgresql.org/docs/9.5/static/datatype-numeric.html

`The data types smallserial, serial and bigserial are not true types, but merely a notational convenience for creating unique identifier columns (similar to the AUTO_INCREMENT property supported by some other databases).`

So, under the hood, serial/bigserial are just int/bigint plus sugar, which means their foreign key should be the simpler datatype.

I would not consider this a postgresql issue, but an issue with doctrines postgresql driver.

**Comment by jhogendorn** [comment]
To further clarify, either just use BIGINT and manually specify the correct sequence configuration, and never go near BIGSERIAL, or support bigserial correctly.

**Comment by Ocramius** [comment]
> So, under the hood, serial/bigserial are just int/bigint plus sugar, which means their foreign key should be the simpler datatype.

The DBAL would have to pretty much map all these quirks (allowing `BIGINT` on the FK side), and that's not gonna happen, as that requires architectural changes in the schema tools. A very quick workaround is to map the join column as `BIGINT` on the referencing side.

**Comment by jhogendorn** [comment]
Sure, if its a big change thats fine, just remove doctrine support for *SERIAL columns and put some lines in the docs saying how doctrine handles it instead.

**Comment by Ocramius** [comment]
Dropping support for `SERIAL` is not gonna happen either - it just works, but the referencing column will just need custom mapping definition.

It's a lose-lose situation, as it stands. It will have to stay as-is until we have better platform customization support.

**Comment by jhogendorn** [comment]
Fair enough.
