### ISSUE TITLE
Problem with PHP 7.x with strict types & nullable relations

### ISSUE THREAD

**Issue by mikemirten** [doctrine/dbal#2420]
We using PHP 7.0.7 with declared strict types.
Custom GUID type which serves as an ID of entities.

If **nullable** related property of an entity referenced to a target entity with custom primary ID type contains no referenced object, it causes an exception due to ```convertToDatabaseValue()``` with strictly should return a string: _"Return value of ...\GuidType::convertToDatabaseValue() must be of the type string, null returned"_.

Possible solution: do not convert null-values or to add something like ```convertNullValues(): bool``` method into abstract Type class to be able choose behaviour.

Thank you.

**Comment by Ocramius** [comment]
DBAL has no return type hints at the moment, so what is this issue about? I already closed https://github.com/doctrine/doctrine2/issues/5881#issuecomment-227138287 as invalid due to pretty much the same question (does not have anything to do with repos under the `doctrine` organization)

**Comment by mikemirten** [comment]
Sure, DBAL has no return hints, but doesn't forbids to use ones for extensions. And the described issue prevents to write a strict typed doctrine types.

I think we can call it "A PHP7 compatibility issue" in some degree. It is certainly not a critical bug but would be good to do something with that in future because PHP7 getting popular and more developers will stumble on that.

Thank you.

**Comment by Ocramius** [comment]
Alright, then let me repeat that this is a non-issue. DBAL types change depending on single type, and nullability is just as it is.

I suggest you to try PHP 7.1-alpha, which allows nullable types.

Closing as `invalid`
