### ISSUE TITLE
Unknown database type jsonb requested. 

### ISSUE THREAD

**Issue by Kilgaloon** [doctrine/dbal#2423]
Like title says, here it is full error.
`Unknown database type jsonb requested, Doctrine\DBAL\Platforms\PostgreSqlPlatform may not support it. `

What i want is to ALTER table and to change its type from varchar to jsonb. Im using laravel migration and following command throws error when migration is attempted.

`$table->jsonb("tags")->change();`

dbal is version is 2.5.4

**Comment by VolCh** [comment]
Try use `json_array` Doctrine type and `jsonb=true` in `platformOptions`. [doc](http://doctrine-orm.readthedocs.io/projects/doctrine-dbal/en/latest/reference/types.html#mapping-matrixl)

**Comment by Kilgaloon** [comment]
Also this error appears when i do following. 
`$table->string('video')->nullable()->change();`

This have nothing with jsonb and this message pops, i guess this is some sort of bugg.

**Comment by deeky666** [comment]
Please provide a failing test case using the DBAL API. We are not responsible for third party code using DBAL.

**Comment by mzur** [comment]
@Kilgaloon Do you get this error with Laravel?

**Comment by Kilgaloon** [comment]
@mzur Yes!

**Comment by mzur** [comment]
I'll soon create a PR for laravel/framework which (I believe) will fix this issue.

**Comment by Kilgaloon** [comment]
I didn't had time to test this further. and find cause of problem, is it laravel or dbal, but glad to hear that. GL

**Comment by mzur** [comment]
[Here](https://github.com/laravel/framework/pull/14359) is the PR. I guess this issue can be closed once the PR is approved and merged.

**Comment by deeky666** [comment]
@Kilgaloon `jsonb` was introduced in PostgtreSQL `9.4`. The related `PostgreSQL94Platform` was introduced in DBAL `2.6` (which is not yet released). You will have to use DBAL `master` + `PostgreSQL94Platform` and `jsonb` platform option (as stated in the docs) to get jsonb working. Closing as invalid.

**Comment by nisevi** [comment]
Hi @deeky666, do you know if the DBAL `master` branch is gonna be compatible with php ^7.0 ?

**Comment by morozov** [comment]
@nisevi, no. See #2750.
