### ISSUE TITLE
Commands out of sync

### ISSUE THREAD

**Issue by lemartin** [doctrine/dbal#2430]
Hello,

when running the following code I get this error. 

```
PHP Fatal error:  Uncaught exception 'Doctrine\DBAL\Driver\Mysqli\MysqliException' with message 'Commands out of sync; you can't run this command now'
```

``` php
$stmt1 = $connection->prepare("SELECT * FROM information_schema.TABLES");
$stmt1->execute();
$stmt1->closeCursor();

$stmt1->execute();

$stmt2 = $connection->prepare("SELECT * FROM information_schema.VIEWS");
$stmt2->execute();
```

If `$stmt1` is only executed once, the error does not occur. My guess is, that is is related to `$this->_stmt->store_result()`, which is only called the first time when `MysqliStatement::execute` is executed, because the second time `$this->_columnNames` is initialised (see. Doctrine\DBAL\Driver\Mysqli\MysqliStatement).

In commits 10a96cc and d00511c it was changed when `store_result()` is called. Before these commits, it was called when `$this->_columnNames` was initialised, now it is only called when `$this->_columnNames` is being initialised. 

The main question is, was this intentionally and, is there a way to circumvent the problem? 

No, closing the `$stmt1` after the second execute is not really an option.

We are using doctrine/dbal 2.5.4 on PHP 5.4.45 with MySQL 5.5.

**Comment by deeky666** [comment]
I don't quite get what your example is trying to achieve? Why the second `execute()`? What is it supposed to do? AFAIK we do not support executing a prepared statement more than once. I am not even sure all drivers support this.

**Comment by kimhemsoe** [comment]
PDO supports it seems http://php.net/manual/en/pdostatement.closecursor.php

I haven't looked if would be possible for mysqli driver to support. How close do we follow PDO in these cases?

**Comment by deeky666** [comment]
@kimhemsoe we (should) support what it is defined in our interface contracts (as much as possible). Looks like we adopted the contract from PDO here, so basically it means we should support it where possible. I would suggest adding a failing test case for this is DBAL first and then start to fix the implementations.

**Comment by kimhemsoe** [comment]
👍

**Comment by morozov** [comment]
> I would suggest adding a failing test case for this is DBAL first and then start to fix the implementations.

@deeky666 please see https://github.com/doctrine/dbal/pull/2487.

**Comment by morozov** [comment]
Must have been fixed by https://github.com/doctrine/dbal/pull/2546.
