### ISSUE TITLE
SqlServer: type mismatch with blob and binary

### ISSUE THREAD

**Issue by MichaelMure** [doctrine/dbal#2445]
I'm using a doctrine's blob type in a symfony project. Once the column created in the database by doctrine, it keeps detecting type mismatch and refuse to validate the schema / generate migration.

After some debugging, the problem is how blob and binary type are mapped to sqlserver's type:

| Doctrine | SqlServer |
| --- | --- |
| blob | varbinary(max) |
| binary(500), fixed=true | binary(500) |
| binary(500), fixed=false | varbinary(500) |
| binary(0), fixed=true | binary(255) |
| binary(0), fixed=false | varbinary(255) |

This come from `SQLServerPlatform::getBlobTypeDeclarationSQL()` and `SQLServerPlatform::getBinaryTypeDeclarationSQLSnippet()`.

As far as I can tell, when reading the database, all of those sqlserver's type are mapped to doctrine's binary (`SQLServerPlatform::initializeDoctrineTypeMappings()`). As it doesn't match the previous mapping, a type mismatch is then detected.

Not sure how it should be done thought.

**Comment by DerDu** [comment]
Same for me
- Symfony 5.1.3
- Doctrine DBAL from symfony/orm-pack 1.1.0
- MSSQL-Server

Using:
```
    /**
     * @ORM\Column(type="blob")
     */
    private $imageData;
```

Is correctly mapped to `varbinary(max)` in Database (schema create)

BUT doctrine migration or schema update always keeps creating this one

`ALTER TABLE tblEilaImage ALTER COLUMN image_data VARBINARY(MAX) NOT NULL`

So schema is always invalid :-(

**Comment by morozov** [comment]
Should have been fixed by https://github.com/doctrine/dbal/pull/4765.
