### ISSUE TITLE
Portable stored procedure calls?

### ISSUE THREAD

**Issue by DerManoMann** [doctrine/dbal#2449]
Hi there,

I am looking for a portable way to call stored procedures, but haven't found anything in DBAL so far. 

Seeing that there are different keywords like 'EXEC' vs. 'CALL' and use of '()' vs no brackets around arguments a method to format an SP call is something I would have expected to find somewhere in DBAL?

**Comment by Ocramius** [comment]
DBAL does not support stored procedures, routines, etc.

**Comment by DerManoMann** [comment]
Hmm, thanks.
