### ISSUE TITLE
DBAL QueryBuilder::update not valid syntax in SQLite with table alias

### ISSUE THREAD

**Issue by robertodormepoco** [doctrine/dbal#2451]
Building update statements using table aliases can give you headache when you deal with SQLite

```
$conn->createQueryBuilder()
->update('table', 't')
->set('foo', ':bar')
->where('t.who = :me')
->setParam('bar', 'drunk');
->setParam('me', 'robertodormepoco');
```

gives a syntax like "UPDATE table t SET t.foo = ? WHERE t.me = ?"
which has no valid "qualified-table-name" as stated in the [sqlite update syntax](https://www.sqlite.org/lang_update.html)

**Comment by morozov** [comment]
Query builder is just a string builder on steroids. It is not aware of the limitations of the target database platform. If any of the platforms supported by the application doesn't support certain features, the table should not use them.
