### ISSUE TITLE
Documentation for test suite runner references non-existing files

### ISSUE THREAD

**Issue by miholeus** [doctrine/dbal#2453]
Here on this page https://github.com/doctrine/dbal/blob/master/docs/en/reference/supporting-other-databases.rst there is typo in sentence
```
You can run the testsuite of your new database driver by calling "cd tests/ && phpunit -c myconfig.xml Doctrine/Tess/AllTests.php"
```
Please fix it with correct path

**Comment by Ocramius** [comment]
@miholeus what would the correct syntax be? You can edit https://github.com/doctrine/dbal/blob/master/docs/en/reference/supporting-other-databases.rst directly from the web-ui.

**Comment by miholeus** [comment]
I can't find
```Doctrine/Tess/AllTests.php``` file.
What is the correct path? tests/Doctrine/Tests?

**Comment by Ocramius** [comment]
@miholeus I think we entirely drop it: no file needs to be provided...

**Comment by miholeus** [comment]
@Ocramius will you update the doc then please?

**Comment by Ocramius** [comment]
Edit it, try it, then I'll merge:

![8ff131](https://cloud.githubusercontent.com/assets/154256/16949346/95930bcc-4dba-11e6-8f6f-6f7f629320e3.png)

**Comment by miholeus** [comment]
Done here https://github.com/doctrine/dbal/pull/2454

**Comment by Ocramius** [comment]
Thanks, merged!
