### ISSUE TITLE
SchemaDiff - _toSql should return not null SQL's

### ISSUE THREAD

**Issue by poolerMF** [doctrine/dbal#2456]
I need to make custom updates while creating DB schema ...
function _toSql is returning SQL's .. but, my array sometimes contains NULL

can you update function _toSql in Schema diff ?
return value should be:

```
 return array_filter($sql, function($value) { return $value; });
```

**Comment by stof** [comment]
the question is why the array contains null. This seems to be the actual bug

**Comment by poolerMF** [comment]
it's not a bug .. I made custom doctrine filter that somatimes return null (I do not want to execute some sql queries when creating/updating schema)

**Comment by Ocramius** [comment]
What filter? What does it look like? Why is it replacing strings with `null` instead of just filtering the values (which is what it should do)?

**Comment by poolerMF** [comment]
I implement federated tables ... in some databases where are those tables I dont want to execute SQL for creating foreign keys ... It is impossible to make this in actual doctrine in good way

so in DBAL I created custom listener in extended MySqlPlatform ...function getCreateForeignKeySQL return NULL when required ... In my program - returning NULL mean that command should be empty and should not be executed ... so I dont want "empty sql commands"

**Comment by stof** [comment]
Well, the contract of the method is `@return string`.
your own implementation changes this contract to `@return string|null`, which breaks OOP rules (a child class is not allowed to make the return value more generic, as it would mean that a code expecting an AbstractPlatform may not handle your return value).
You cannot expect the SchemaDiff tool to support `null` values there when the contract of the class says the value cannot be null.
