### ISSUE TITLE
new Release

### ISSUE THREAD

**Issue by mathroc** [doctrine/dbal#2465]
Hello,

it's been quite some time since the last release and a lot of work has been put into DBAL since january, is it possible to tag a new release ? 
I can see there is a 2.5.5 milestone but are all of those issue really necessary ?
maybe they can be separated into 2 categories (N being the last bugfix number):

* 2.5.N+1: issues that are BC since 2.5.N
* 2.5.X: issues that already existed in 2.5.N

a bugfix release can then be made, for example every 3 or 6 months if the 2.5.N+1 milestone is empty. 

thoughts ?

**Comment by Ocramius** [comment]
> it's been quite some time since the last release and a lot of work has been put into DBAL since january, is it possible to tag a new release ? 

@mathroc we just never got around doing a release.

 > I can see there is a 2.5.5 milestone but are all of those issue really necessary ?

When we release, we just kick unfinished work into a different milestone.

What you described is already what's going on (we know semver), we just didn't work on it at all.

Closing here. Release will be done when they will be done.

**Comment by mathroc** [comment]
great, thank you for quick answer @Ocramius
