### ISSUE TITLE
Doctrine\Tests\DBAL\Functional\WriteTest::testLastInsertIdSequence fails for SQLSRV on master branch

### ISSUE THREAD

**Issue by xalopp** [doctrine/dbal#2467]
When I run `./vendor/bin/phpunit --configuration tests/travis/sqlsrv.travis.xml`,  I get following failure:

```
There was 1 failure:

1) Doctrine\Tests\DBAL\Functional\WriteTest::testLastInsertIdSequence
Failed asserting that false is true.

/home/ubuntu/dbal/tests/Doctrine/Tests/DBAL/Functional/WriteTest.php:172
```

I set up my test environment based on Ubuntu 16.04 with https://github.com/xalopp/vagrant-php7sqlsrv

PHP Version: `PHP 7.0.9-1+deb.sury.org~xenial+1 (cli) ( NTS )PHP 7.0.9-1+deb.sury.org~xenial+1 (cli) ( NTS )`
SQLSRV driver Version: `4.0.2.0`
MS SQL Server Version: `Microsoft SQL Server 2016 (RTM) - 13.0.1601.5 (X64) Microsoft SQL Server 2016 (RTM) - 13.0.1601.5 (X64)`

**Comment by xalopp** [comment]
The function `lastInsertId` in `lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvConnection.phplib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvConnection.php`
tries to get the  `lastInsertId` by doing
```php
$sql = "SELECT IDENT_CURRENT(".$this->quote($name).") AS LastInsertId";
```
I guess, the code is borrowed  from [pdo_sqlsrv/pdo_dbh.cpp](https://github.com/Azure/msphpsql/blob/7cb7c799164e4e699fea6d09ba4de869b9689204/pdo_sqlsrv/pdo_dbh.cpp#L37)

According to https://msdn.microsoft.com/en-us/library/ms175098.aspx `IDENT_CURRENT` takes a table name as parameter, but a sequence name is used [Doctrine\Tests\DBAL\Functional\WriteTest::testLastInsertIdSequence](https://github.com/doctrine/dbal/blob/master/tests/Doctrine/Tests/DBAL/Functional/WriteTest.php#L170).

MS SQLServer stores the information about sequences in the table `sys.sequences`.
I guess it would be consistent  to use this system table, so the behavior is similar to
[Doctrine\DBAL\Driver\OCI8\OCI8Connection::lastInsertId](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php#L148)

A PR is in progress

**Comment by morozov** [comment]
Closing as not reproducible:
```
$ git log -1
commit 2aec3f8da5f601462162d9b90d013554b240292b (HEAD -> 3.2.x, upstream/3.2.x)
Merge: 141daa53e b0404da1b
Author: Sergei Morozov <morozov@tut.by>
Date:   Mon Dec 6 10:58:49 2021 -0800

    Merge branch '2.13.x' into 3.2.x

$ phpunit -c sqlsrv.phpunit.xml --filter testLastInsertIdSequence tests/Functional/WriteTest.php
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

.                                                                                                                               1 / 1 (100%)

Time: 00:00.599, Memory: 12.00 MB

OK (1 test, 3 assertions)
```
Must have been fixed by https://github.com/doctrine/dbal/pull/2634.
