### ISSUE TITLE
Test are failing with Oracle for branch 2.5

### ISSUE THREAD

**Issue by xalopp** [doctrine/dbal#2468]
The PHPUnit tests are running fine with Oracle on master branch, unfortunately they fail on 2.5 branch 😨 

By cherry-picking to `branch 2.5` fallowing commits 
- cb83758aee4fef9fc1c4f13913144e7a7e3d302c  #2252 ModifyLimitQueryTest::testModifyLimitQuerySubSelect() fails on Oracle
- 26ddca2e8fde4ba0b2e6d73e605d05bc6e301fbd #2255 Use shorter table names - Oracle allows max 30 characters
- 3fa94ec7f88211da0510cebab327b2f85bdb6609  #2253 SchemaManagerFunctionalTestCase::testDropsDatabaseWithActiveConnections() fails on Oracle
- 0ee664598b8615813d07dabce61a03c2908493ea #2250 Unit tests failing on Oracle

the test suite is running fine.

Hope this helps to get closer to a release, as mentioned in https://github.com/doctrine/dbal/pull/2434#issuecomment-231189893

**Comment by xalopp** [comment]
Does it help to make a PR with the cherry-picked commits?

**Comment by DeepDiver1975** [comment]
ci status on 2.5 - https://jenkins.owncloud.org/job/doctrine-dbal-oracle-2.5/

ci status on master - https://jenkins.owncloud.org/job/doctrine-dbal-oracle/

**Comment by xalopp** [comment]
@DeepDiver1975 do you have the possibility to add MS SQL Server to the OwnCloud CI to make the progress on SQLSRV / PDO_SQLSRV support more transparent? In my case this would help for the issues #2469 and #2467, but there quiet more MS SQL Server issues open.

In general, wouldn't it be great to integrate Jenkins for non Open Source Databases to the GitHub build services for Doctrine DBAL?

**Comment by DeepDiver1975** [comment]
We are running Jenkins on pure Linux infrastructure - sorry :crying_cat_face:

**Comment by DeepDiver1975** [comment]
> In general, wouldn't it be great to integrate Jenkins for non Open Source Databases to the GitHub build services for Doctrine DBAL?

I'm happy to provide deeper integration for doctrine.

**Comment by DeepDiver1975** [comment]
@deeky666 @Ocramius - what is the plan?
- [ ] backport oracle fixes to 2.5 branch? - I'm happy to provide PRs
- [ ] don't backport - when do we get 2.6 released?

THX

**Comment by Majkl578** [comment]
Hi, I am closing this as there are already 2.6 and 2.7 releases and we test Oracle on Continuous PHP.
Should any issues still persist, please open new issue based on 2.7 branch.
