### ISSUE TITLE
MySQL Storage Engine

### ISSUE THREAD

**Issue by manseuk** [doctrine/dbal#2471]
Hi,

I am using Doctrine as part of Symfony

We would like to use the NDBCLUSTER storage engine for MySQL - we know that we can add @Table(enigine="ndbcluster") on all of the entities - but we only what this storage engine in production environment not in all environments.

Had a look through the documentation and cannot see any way to change the default storage engine

I have also looked at the platform code and cant see how to access params from the configuration to be able to even set a default storage engine.

Is this something that could be easily implemented ? or complex ?

Happy to look at coding it up if someone could point me in the right direction - i think being able to configure a default storage engine per environment would be a good thing ?

**Comment by kimhemsoe** [comment]
To me personal it sounds like a scary thing todo. If i remember correct
there is HUGE differences between NDBCLUSTER and INNODB.

It may be possible with events far from sure though, but i would vote
against native support in dbal.

**Comment by manseuk** [comment]
From a client point of view the difference is minimal - im not asking for the project to add support - just add support for a different engine based on environment. Or at least how i would add it

**Comment by kimhemsoe** [comment]
As i mentioned. My best guess is events.

**Comment by kimhemsoe** [comment]
Look at loadClassMetadata event
