### ISSUE TITLE
Cannot mix positional parameters and named paramters in SQL

### ISSUE THREAD

**Issue by zjsxwc** [doctrine/dbal#2472]
In function expandListParameters, 
https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/SQLParserUtils.php#L89

I have lot of query sqls that mixed  positional parameters (?) and named paramters(:namedparam) in a project, 

  say:

  " SELECT \* FROM user WHERE user.name IN (?) AND user.id IN (:ppmid1, :ppmid2) "， with QueryBuilder's params [ 0 =>['zjsxwc'], 'ppmid1' => 1, 'ppmid2' => 2 ].

The problem is that when QueryBuilder do execute the sql, then in expandListParameters will only regard the sql as positional, and not handle the named parameters part, then only return the positional part params to https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php#L816.

how can i solve the problem?

**Comment by frogeyedpeas** [comment]
was this ever fixed?

**Comment by zjsxwc** [comment]
@frogeyedpeas
> was this ever fixed?

it fixed.
see the source code in v2.10.1:
https://github.com/doctrine/dbal/blob/v2.10.1/lib/Doctrine/DBAL/SQLParserUtils.php#L127
