### ISSUE TITLE
Is anything gained by the following lines of code?

### ISSUE THREAD

**Issue by zippy1981** [doctrine/dbal#2474]
https://github.com/doctrine/dbal/blob/45939c61df532608c67a92733b7cd1e64455abc1/lib/Doctrine/DBAL/Driver/PDOConnection.php#L110-L124

two methods overwriting pdo methings and just calling themselves.

**Comment by Ocramius** [comment]
Possibly due to reflection and HHVM compliance, but not 100% sure.

Try checking if the test suite relies on it by removing them? Maybe check also `git blame`

**Comment by chrisguitarguy** [comment]
Looks like it was HHVM compliance https://github.com/doctrine/dbal/commit/7aa02d0a91479b972240681071f876d127c580d3

**Comment by zippy1981** [comment]
Yes
