### ISSUE TITLE
The build is broken on master

### ISSUE THREAD

**Issue by greg0ire** [doctrine/dbal#2475]
In #2473 , I noticed many errors in the build that seem unrelated to my changes.

I fixed similar problems with Sonata recently : 

- https://github.com/sonata-project/SonataMediaBundle/pull/1106/files
- https://github.com/sonata-project/SonataAdminBundle/pull/4079/files

It looks the mock system is a bit more strict now.

[Example error message](https://travis-ci.org/doctrine/dbal/jobs/154096041#L384) : 

> Doctrine\Tests\DBAL\ConnectionTest::testConnectDispatchEvent
>
> Undefined index: postConnect

The same message appears many times, with different method names.

Related : https://github.com/sebastianbergmann/phpunit-mock-objects/issues/321

**Comment by greg0ire** [comment]
@Ocramius : should this be contributed on master or on 2.5 (or on both? I don't see 2.5 being merged in master or vice versa in the git graph).

**Comment by Ocramius** [comment]
@greg0ire send patches to `master`, backporting is up to us.
