### ISSUE TITLE
Sharding Database by Schemas

### ISSUE THREAD

**Issue by mdhheydari** [doctrine/dbal#2478]
Hi,

I want to shard my current database. Doing so, Instead of sharding schemas by ID, I'm going to move some of the schemas to another MySQL instance (my current database is also MySQL). I don't have any join queries within the shards though I need transactions. How can I do it with Doctrine DBAL?

**Comment by Ocramius** [comment]
@mdhheydari this is not something that the DBAL abstract for you. My personal suggestion is to use different DBAL connections for different schemas, rather than selecting DB connection inside the DBAL (messy/buggy).

Closing, since this is not an issue, but a question.
