### ISSUE TITLE
Inserting boolean "false" throws Exception with PDO_OCI

### ISSUE THREAD

**Issue by matthias-z** [doctrine/dbal#2481]
I actually encountered this problem with doctrine/orm and I'm actually a little unsure whether this is the correct place for the report but personally I think it's more related to the DBAL, so I'll create the issue here.
## Environment
- PHP 5.6
- Oracle 11g2 database
- PDO_OCI driver
- doctrine/dbal 2.5.4
- doctrine/orm 2.5.4
## PDO error

The root cause of the problem can be reproduced with the native PDO_OCI driver using the parameter type `PDO::PARAM_BOOL`:

```
/* @var PDO $pdo */
$pdo = $db->getConnection();
$stmt = $pdo->prepare("INSERT INTO ba_customer (id, name, has_one_record_per_efa) VALUES (?, ?, ?)");
$stmt->bindValue(1, 1, PDO::PARAM_INT);
$stmt->bindValue(2, "Testcustomer", PDO::PARAM_STR);
$stmt->bindValue(3, false, PDO::PARAM_BOOL);
$stmt->execute();
```

which results in:

```
Fatal Error: SQLSTATE[HY000]: General error: 1400 OCIStmtExecute: ORA-01400: cannot insert NULL into ("INTRANET_DEV_BRANCH"."BA_CUSTOMER"."HAS_ONE_RECORD_PER_EFA") (/tmp/php-5.6.16/ext/pdo_oci/oci_statement.c:148)
```

Oracle does not support boolean columns, so the actual column type of `has_one_record_per_efa` is `NUMBER(1,0)`.
Interesting enough, it works if I try to insert boolean "true".
If I use `PDO::PARAM_INT` instead it works for both "true" and "false".
## Problem with doctrine ORM/DBAL

As I mentioned before, I've first encountered this problem with doctrine/orm with the following mapping in my entity class:

```
/**
 * @ORM\Column(type="boolean", name="has_one_record_per_efa")
 */
protected $hasOneRecordPerEfa;
```

Doctrine ORM uses the DBAL internally and passes the type name (as a string) when preparing the statement / bind parameters.
Here's the example above modified to use doctrine DBAL:

```
$conn = $entityManager->getConnection();
$stmt = $conn->prepare("INSERT INTO ba_customer (id, name, has_one_record_per_efa) VALUES (?, ?, ?)");
$stmt->bindValue(1, 1, "integer");
$stmt->bindValue(2, "Testcustomer", "string");
$stmt->bindValue(3, false, "boolean");
$stmt->execute();
```

which results in the same error.
The string parameter "boolean" is converted to `Doctrine\DBAL\Types\BooleanType`  and `BooleanType::getBindingType()` returns `PDO::PARAM_BOOL`.
## Workaround
- When just working with the DBAL, you can simply use `PDO::PARAM_INT` or "integer" as the bind type.
- When working with the ORM, you have to change the column mapping to "integer" and implement type casting in the getter/setter methods
## Desired behaviour

The DBAL should use `PDO::PARAM_INT` instead of `PDO::PARAM_BOOL` for the `BooleanType` on the Oracle platform.

**Comment by Ocramius** [comment]
I'd rather say that PDO is broken here, since this means that `PDO::PARAM_BOOL` is basically useless when dealing with PDO.

Is there an issue for this on http://bugs.php.net/ ?

**Comment by morozov** [comment]
Closing as this is not a DBAL issue ([bug #81586](https://bugs.php.net/bug.php?id=81586)):
```php
$conn = new PDO('oci:dbname=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521))(CONNECT_DATA=(SID=XE)))', 'system', 'oracle');
$stmt = $conn->prepare('SELECT ? FROM DUAL');
$stmt->bindValue(1, false, PDO::PARAM_BOOL);
$stmt->execute();
var_dump($stmt->fetch(PDO::FETCH_COLUMN));
// NULL
```
