### ISSUE TITLE
Wrong migration diff with trait

### ISSUE THREAD

**Issue by andreas4all** [doctrine/dbal#2492]
Hi,

I have an entity with this property:

```
    /**
     * @var string
     *
     * @ORM\Column(name="model_name", type="string", length=64, nullable=true)
     * @Assert\Length(max = 64)
     */
    protected $modelName;
```

Generated diff is clear - no `up` and `down` migrations. But when I create a new trait (and remove from entity) with this same code I got this diff:

UP:
```
$this->addSql('ALTER TABLE service_device ALTER model_name TYPE VARCHAR(64)');
$this->addSql('ALTER TABLE service_device ALTER model_name DROP DEFAULT');
```

DOWN:
```
$this->addSql('CREATE SCHEMA public');
$this->addSql('ALTER TABLE service_device ALTER model_name TYPE TEXT');
$this->addSql('ALTER TABLE service_device ALTER model_name DROP DEFAULT');
$this->addSql('ALTER TABLE service_device ALTER model_name TYPE TEXT');
```

When I copy this property to entity (in trait is same) and get new diff - this diff is empty. Then I remove property from entity (in trait is still same) and get another new diff - this diff is empty.

```
php -v
PHP 7.0.10 (cli) (built: Aug 22 2016 08:57:26) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10, Copyright (c) 1999-2016, by Zend Technologies
```

```
"name": "doctrine/dbal",
"version": "v2.5.4",

"name": "doctrine/doctrine-bundle",
"version": "1.6.4",
```

**Comment by Ocramius** [comment]
This seems like an ORM issue. We don't really have extensive trait support testing, but please report the issue in the ORM, and compare metadata of the entity with/without the trait (`$entityManager->getClassMetadataFor(YourEntity::class)`)
