### ISSUE TITLE
ResultStatement::fetch() returns null instead of false with mysqli

### ISSUE THREAD

**Issue by PatrickLouys** [doctrine/dbal#2497]
ResultStatement::fetch() returns null with mysqli, false with sqlsrv. Documented is that it always returns false http://www.doctrine-project.org/api/dbal/2.0/class-Doctrine.DBAL.Driver.ResultStatement.html

http://www.doctrine-project.org/api/dbal/2.3/source-class-Doctrine.DBAL.Driver.Mysqli.MysqliStatement.html#243

I guess the code here should return false instead of null?

**Comment by PatrickLouys** [comment]
If this is confirmed as a bug I can make a quick PR.

**Comment by kimhemsoe** [comment]
This seems indeed to be a bug.

Confirmed.

**Comment by Ocramius** [comment]
Fixed via #2500
