### ISSUE TITLE
Migration diff command always add migration for default values of custom type fields

### ISSUE THREAD

**Issue by josecelano** [doctrine/dbal#2506]
Hi. I have the problem described here:

http://stackoverflow.com/a/27557785/3012842

Basically when I use a custom DBAL type like [CarbonDateTimeType](https://github.com/beberlei/DoctrineExtensions/blob/5e4eeb632b18da7a848b9b470ff1e688200c0d4e/src/Types/CarbonDateTimeType.php) doctrine always creates a migration for changing the default value of that field.

The migration looks like:

```
$this->addSql('ALTER TABLE table_name CHANGE field_with_carbon_date_time_type field_with_carbon_date_time_type DATETIME NOT NULL');
```

In stackoverflow @vbence says it's a bug but the link is to the old jira bug tracker. And I do not know if th bug is fixed or how can I fix it. The solution in stackoverflow is not valid in this case because that type already contains the method `requiresSQLCommentHint`

Thanks.

**Comment by josecelano** [comment]
I have found the solution in this blog post from @ricbra:

https://blog.vandenbrand.org/2015/06/25/creating-a-custom-doctrine-dbal-type-the-right-way/

You have to add this comment: `(DC2Type:CarbonDateTime)` to the field in the table which is mapped to the custom type. Where **CarbonDateTime** is the custom type.

This is the sample SQL to add that comment:

```
ALTER TABLE `table_name`
	CHANGE COLUMN `table_field` `table_field` DATETIME NOT NULL COMMENT '(DC2Type:CarbonDateTime);
```

Then, I suppose this is not a bug in this package and I should open an issue in [beberlei/DoctrineExtensions](https://github.com/beberlei/DoctrineExtensions).

Maybe they should add this code:

```
    /**
     * @param array            $fieldDeclaration
     * @param AbstractPlatform $platform
     * @return string
     */
    public function getSqlDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        return sprintf('BINARY(%d) COMMENT \'(DC2Type:uuid)\'', $fieldDeclaration['length']);
    }
````

into their [CarbonDateTimeType](https://github.com/beberlei/DoctrineExtensions/blob/5e4eeb632b18da7a848b9b470ff1e688200c0d4e/src/Types/CarbonDateTimeType.php) class.

Is that correct?

**Comment by vbence** [comment]
Hi, the issue imported form Jira can be found here:
https://github.com/doctrine/dbal/issues/1137

**Comment by deeky666** [comment]
@josecelano maybe realted to https://github.com/doctrine/dbal/issues/2594
Please try again with current `master` and report back. Thanks.

**Comment by morozov** [comment]
Closing due to the lack of feedback. Likely, irrelevant as of https://github.com/doctrine/dbal/pull/5512.
