### ISSUE TITLE
Renaming index does not rename the index, but creates new one

### ISSUE THREAD

**Issue by mishal** [doctrine/dbal#2508]
When I try to rename the index using the API, the old options are not passed to the new index, which causes that the index is not renamed, but _different_ index is created.

```
$table = Table();
$table->addIndex(['name'], 'idx_name', [], [            
    'where' => 'name IS NOT NULL'
]);
$table->renameIndex('idx_name', 'idy_foo');
```

The method renameIndex() does not pass the options from the old index.

**Comment by deeky666** [comment]
@mishal which platform are you using? Partial Indexes are currently only supported on PostgreSQL and SQLite.

**Comment by mishal** [comment]
PostgreSQL is platform of my choice :)

**Comment by mishal** [comment]
But this issue is not about partial indexes, the options array could contain anything else...

**Comment by deeky666** [comment]
@mishal patch created: #2611

**Comment by Ocramius** [comment]
Handled via #2611
