### ISSUE TITLE
PHP Warning when listing table columns in Oracle

### ISSUE THREAD

**Issue by nitso** [doctrine/dbal#2515]
```
PHP Warning:  oci_fetch_all(): ORA-01427: single-row subquery returns more than one row in /opt/kvk/WB/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php on line 290
```

Synopsis: 
1. Create two databases accessible by current user
2. Add identical tables with same name in both databases
3. Try to get database schema (in my case I was running a migration)

**Comment by Marius2805** [comment]
This bug is already fixed (including test) in pull reqeust:
https://github.com/doctrine/dbal/pull/2518

**Comment by deeky666** [comment]
Duplicate of #2517
