### ISSUE TITLE
The documentation, Prepared statements and Triggers

### ISSUE THREAD

**Issue by mikeSimonson** [doctrine/dbal#2520]
The documentation implies that [the query method does not use the prepared statements](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/data-retrieval-and-manipulation.html#data-retrieval).

But in the Mysqli it's the exec method that seems the only one not to use prepared statements.
In Mysqli case it's thus the exec method that is the only one suitable to create Triggers as they are not supported in prepared statements.

Here is a table of those 2 methods in all the supported driver of the DBAL. 

| DRIVER | method | prepared stmts |
| --- | --- | --- |
| mysqli | exec | no |
| mysqli | query | yes |
| pdo (Mysql, Oracle, PgSql, Sqlite, SqlSrv) | exec | no |
| pdo (Mysql, Oracle, PgSql, Sqlite, SqlSrv) | query | no |
| IBMDB2 | exec | yes |
| IBMDB2 | query | yes |
| OCI8 | exec | yes |
| OCI8 | query | yes |
| SQLAnywhere | exec | x |
| SQLAnywhere | query | yes |
| SqlSrv | exec | yes |
| SqlSrv | query | yes |

As I don't know if some db other than mysqli support trigger creation in a prepared statement.
I don't know if that means that the documentation needs to be modified or if some Connection needs to be fixed.

OCI8, SqlAnywhere and SqlSrv don't seems to provide anyway to query without prepared statement, does that means that they can't support Trigger or that They support trigger trough prepared statement.

I don't have any of those so I can't answer the question properly.

**Comment by Ocramius** [comment]
> the query method does not use the prepared statements.

It may state so, but it doesn't really matter if it uses them internally.

**Comment by mikeSimonson** [comment]
@Ocramius Maybe a little more context.
I needed to add a trigger in a db. The connection to that db use mysqli. Mysqli does not support create Trigger in a prepared statement. In the doc it says that quey doesn't use prepared statement but for the Mysqli driver it does and adding the trigger fails.

**Comment by kimhemsoe** [comment]
I dont understand why you are using query() for creating a trigger. The
docs clearly states it will return a statement object.

Maybe the docs is a bit wage on this subject, but i dont read it as there
will not be used a prepare statement in its implementation.

Anyway exec() is very clearly made for creating triggers as it will not
return a result.

**Comment by Ocramius** [comment]
Regardless of that, I don't see why adapters shouldn't be able to use prepared statements with triggers. Sounds like a bug at adapter level, rather than a DBAL issue.

**Comment by kimhemsoe** [comment]
@Ocramius We are not writing about using triggers, only creating them. Apparently the mysqli c driver does support creating triggers with prepared statements, which the mysqli dbal driver use for returning a result.

**Comment by Ocramius** [comment]
@kimhemsoe yes, but generally ANY SQL should just be OK with a prepared statement. It's still a piece of SQL sent down to a server with some (eventual) parameters and an open session.

I'd say that it is a SEP (someone else's problem).

**Comment by kimhemsoe** [comment]
Agree. It is possible to fix in the mysqli dbal driver. But it very much not fun and i would need to duplicate quite a but of code and make sure it works with all the different drivers (mysqlnd and mysqli) and their variants.

**Comment by Ocramius** [comment]
> But it very much not fun and i would need to duplicate quite a bit of code and make sure it works with all the different drivers (mysqlnd and mysqli) and their variants. 

Or... use working drivers, and report the issue about non-working one to the respective "SEP authority"

**Comment by kimhemsoe** [comment]
what.. mysql (mysqli) and php (mysqlnd) fixing.. bugs..? :D So unheard of. That will never happen. It is properly a thing in the mysql server protocol.

**Comment by Ocramius** [comment]
Then why the heck do people use those things in first place? I know I sound harsh, but we're not here to fix everyone's problems.

**Comment by mikeSimonson** [comment]
@kimhemsoe The documentation says 

>     Databases optimize SQL queries before they are executed.
>     Using the query method you will trigger the optimization process over 
>     and over again, although it could re-use this information 
>     easily using a technique called prepared statements.

That's the sentence that induced me to think that the dbal query implementation does not use prepared statement, but if you look at the [php code](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php#L130), it does.
And has shown in the table in the first post, the fact that the query or exec method uses a prepared statement or not is not consistent across drivers.

So the questions now are:  
  * Is it a problem that the use of prepared statement for a given method of the dbal interface is not consistent across divers ?
  * Should it be documented ?
  * Should I replace the sentence above that seems to state that the query method does not use prepared statement ?

Also exec is not in the documentation so I should probably add it to it.

**Comment by kimhemsoe** [comment]
@kimhemsoe The documentation says 



> That's the sentence that induced me to think that the dbal query implementation does not use  prepared statement, but if you look at the [php code](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php#L130), it does.
> And has shown in the table in the first post, the fact that the query or exec method uses a prepared statement or not is not consistent across drivers.

I dont read like it does not use prepared statements, only that the user dont get the possible benefits from a prepared statement. 
Also i think we try to say "use prepared statements" for the wrong reasons with that paragraph. We should only mention security. 

> So the questions now are:  
>  * Is it a problem that the use of prepared statement for a given method of the dbal interface is not consistent across divers ?
>  * Should it be documented ?
>  * Should I replace the sentence above that seems to state that the query method does not use prepared statement ?

Nope

 Document exec() and make it clear what each method is for.

Yes rewrite it in a way that states that is better that the user to use prepared statements and what the user gain from this. It does not make sense to write anything about "optimization" since this is can be very different between vendors.

**Comment by morozov** [comment]
Closing due to the lack of interest in addressing the issue.
