### ISSUE TITLE
Allow UPDATE FROM clause

### ISSUE THREAD

**Issue by zippy1981** [doctrine/dbal#2526]
Some RDBMSes. specifically postgres and Microsoft SQL Server support a FROM clause in an update like so

```
UPDATE people 
    SET last_name = 'Smith'
    FROM address
    WHERE
        people.address_id - address.address_id 
        AND address.postal_code = '10001';
```

However, if I add a FROM to a DBAL update() call, it seems to be silently ignored.

**Comment by zippy1981** [comment]
It seems to be a matter of updating [QueryBuilder::getSQLForSelect()](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Query/QueryBuilder.php#L1196). Since UPDATE syntax is not universal across platforms, then perhaps QueryBuilder needs to have a child class per driver that wants to implement this.

DB2 will be weird since you join on correlated subqueries inside the SET clause. However, for postgres and Microsoft SQL server the FROM sytanx is straightforward, although slightly different.

**Comment by Ocramius** [comment]
We'll only support cross-platform compliant syntax. If you are really building SQL strings that are supported only on some platforms, then you don't need an SQL builder anyway - just use SQL.
