### ISSUE TITLE
Doctrine\DBAL\Driver\PDOException - SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC1\xAA\xCF\xB5</...' for column 'html' at row 1

### ISSUE THREAD

**Issue by bizmate** [doctrine/dbal#2533]
While inserting html I get error  `General error: 1366 Incorrect string value: '\xC1\xAA\xCF\xB5</...' for column 'html' at row 1` despite using `charset:  utf8mb4`.

Sample text includes characters like

`վṩ鼦Ѷ鼦ַ鼦ٷվݡ`

https://github.com/voku/portable-utf8/files/520607/textDebug.txt.tar.gz

I have enabled the doctrine logger and after grabbing the statement and running it against the db directly I see no error.

[Insert_works.sql.txt](https://github.com/doctrine/dbal/files/523176/Insert_works.sql.txt)

Any idea what might be gone wrong?

**Comment by Ocramius** [comment]
This usually happens when trying to insert non-utf8 chars. Did you filter them, and validate if it's utf8? I can clearly see a broken character there, although I didn't dig further:
![1712c1](https://cloud.githubusercontent.com/assets/154256/19296436/be9a38b0-903b-11e6-89c7-6fba9af5bf9f.png)

**Comment by bizmate** [comment]
Although I tried 
https://github.com/voku/portable-utf8/issues/47
I am not 100% sure, despite the tests in the library passing. But also my question is how come is the insert (taken directly from the logger) working when run manually in the db (so outside PDO/Doctrine). I was expecting that statement to fail consistently. 

I ll need to try and find those characters you posted in your image as opening this file with some editors parses/garbles them. textmate seems to work. Could you please repost it with some of its surrounding html?
