### ISSUE TITLE
Minimum PHP Version should be 5.6.x in case of varidic operators

### ISSUE THREAD

**Issue by mbunge** [doctrine/dbal#2540]
https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Connection.php#L926

Doctrine requires PHP Version 5.3.2, but varidic operatos requires PHP version >=5.6.x.  The required Version need to be changed to 5.6 or remove varidic support.

**Comment by kimhemsoe** [comment]
Minimum php version for the unreleased version on master is php 5.6 as specified in composer.json.

Current stable release of dbal only require php 5.3.2 or higher.

**Comment by Ocramius** [comment]
Closing - indeed, we bumped version requirements.
