### ISSUE TITLE
Doctrine Schema Update with large number of columns

### ISSUE THREAD

**Issue by fabgg** [doctrine/dbal#2544]
For one project with Symfony 2.8.* and Mysql 5.7.10 and PHP 5.6.25.
I have one table with 257 columns.
The command doctrine:schema:update does an alter table each time even table is ok.
ALTER TABLE myTable ADD field256 INT DEFAULT NULL, ADD field257 INT DEFAULT NULL, DROP field256, DROP field257;
Problem I loose part of data;
It seems the limit to 255 columns per row.
Question : Is it normal ?

**Comment by Ocramius** [comment]
> It seems the limit to 255 columns per row.

Depends on the DBMS, not on doctrine.

Closing, since this is not a doctrine issue.

**Comment by Ocramius** [comment]
FYI: https://dev.mysql.com/doc/refman/5.7/en/column-count-limit.html

**Comment by fabgg** [comment]
Ok but, i don't have any issue with this table on mysql server. My table count 257 columns and every thing works well except Doctrine schema update
