### ISSUE TITLE
DBAL [AbstractPlatform]: quoteStringLiteral introduces syntax error (with MySql)

### ISSUE THREAD

**Issue by DerDu** [doctrine/dbal#2548]
**BUG in `public function quoteStringLiteral`**

If i use the MySQL Platform the `getStringLiteralQuoteCharacter` is a `'`

    /**
     * Quotes a literal string.
     * This method is NOT meant to fix SQL injections!
     * It is only meant to escape this platform's string literal
     * quote character inside the given literal string.
     *
     * @param string $str The literal string to be quoted.
     *
     * @return string The quoted literal string.
     */
    public function quoteStringLiteral($str)
    {

        $c = $this->getStringLiteralQuoteCharacter();

        return $c.str_replace($c, $c.$c, $str).$c;
    }

With MySql this should quote every `'` to `''` .. and it does:

---

Let's say we have:

`abc'd`  turns into `'abc''d'` > This is OK

**BUT**

Let's have:

`abc\'d`  this turns into `'abc\''d'` > This is WRONG

Because this would be parsed as:

`'` > BEGIN string
`abc` > string
`\'`  > `'` in string (YES this escape is also valid)
`'` > END string
`d'` > **??? > Syntax Error**

**Comment by deeky666** [comment]
@DerDu I cannot reproduce the issue. Quoting of the backslash character is implemented. The following test case works for me:

```php
$expected = "'abc\\\''d'"; // 'abc\\''d'
$literal = "abc\\'d"; // abc\'d
$this->assertSame("'abc\\\''d'", $this->_platform->quoteStringLiteral("abc\\'d")); // ok
```

Maybe you did not escape the backslash in your PHP code? Like:

```php
$literal = "abc\'d"; // wrong
$literal = "abc\\'d"; // correct
```
