### ISSUE TITLE
DateTimeType seems to be broken when default PHP timezone is not UTC

### ISSUE THREAD

**Issue by NoiseByNorthwest** [doctrine/dbal#2554]
The way DateTimeType convertions are handled seems to be broken when PHP default timezone is not UTC.
I'm using ORM with PostgreSQL.
With datetime mapping, a DateTime object is converted to/from DB value with a simple format()/createFromFormat() with 'Y-m-d H:i:s' format.
Thus, the given date is wrongly interpreted by PHP as a date within its default timezone, and, in the other side, is wrongly interpreted by PostgreSQL as an UTC date.

E.G. If a date field has the '2016-11-16 15:28:47' (UTC) value in PostgreSQL, on PHP side, with 'Europe/Berlin' as default timezone, it will be converted to a DateTime representing '2016-11-16 15:28:47' in 'Europe/Berlin'. That means '2016-11-16 14:28:47' in UTC (since 'Europe/Berlin' is currently UTC+1 offset).

**Comment by Ocramius** [comment]
This is correct behavior by DBAL, although indeed annoying for systems where the system clock of the DB and the application are configured differently. The conversion can be done with a custom UTC-based time or custom timezone-capable adapter: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/working-with-datetime.html

We may eventually ship something like that (although we'd need someone with more date/time handling experience) for 3.x.

Closing here.
