### ISSUE TITLE
schema generation maps oracle DATE fields to datetime

### ISSUE THREAD

**Issue by brettmc** [doctrine/dbal#2555]
I am using the schema generation tool to generate create/update scripts for my database from yaml entities.
Using http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#datetime as a guide, I have a date column of type 'date', which correctly generates an oracle column with type DATE.
However, when I try to generate update scripts, OraclePlatform::doctrineTypeMappings maps the oracle DATE to a doctrine DateTimeType. The columns are seen as different because DateType != DateTimeType.
If I change the mapping date->datetime to date->date, it correctly sees that the database column matches the entity definition.

I think this is a bug, although minor since the update sql is generated from the entity definition and ends up being a no-op.

**Comment by Ocramius** [comment]
Can you try reproducing this as a test case against DBAL? An example script
could also suffice.

**Comment by brettmc** [comment]
Sure. I'll try it as a test case first (I started on one yesterday), give me a couple of days.

**Comment by brettmc** [comment]
I have submitted a pull request  #2561 to demonstrate the issue (which I think can be applied to other databases, and I've written it so that it could be)... I think it illustrates an inconsistency with how the Oracle platform treats the 'date' and 'time' doctrine types.
NB I needed to modify AbstractPlatform::getColumnDeclarationSQL(), but I'll look at whether this is necessary...

**Comment by deeky666** [comment]
Confirmed. PR is coming.

**Comment by deeky666** [comment]
Patch provided via #2612

**Comment by Ocramius** [comment]
Handled in #2612
