### ISSUE TITLE
Add the ability to use custom JSON options for json_encode in `json` field type

### ISSUE THREAD

**Issue by sivolobov** [doctrine/dbal#2556]
For now when we use DBAL type `json` or `json_array` our value is always encoded without any JSON options (defined for convenient use of `json_encode` function in PHP). But it is very convenient to make it more flexible.
Example: I think that many developers have databases with utf8 encoding and so they don't need escaping UTF8 characters. So they would be happy if there were ability to add `JSON_UNESCAPED_UNICODE` in `convertToDatabase` implementation:

        $encoded = json_encode($value, JSON_UNESCAPED_UNICODE);

But for other cases developers will need another options. And the most convenient way to make it more flexible: extract these options to some configuration point. And use it like:

        $encoded = json_encode($value, $optionsFromConfig);

**Comment by Ocramius** [comment]
Functionally, this doesn't introduce anything, so I think that the added complexity is actually not even worth investigating.

A custom DBAL type is sufficient, and DB engines that actually understand JSON will actually compress the information correctly anyway (Postgres, usually).

While the idea is valid, I'll put `won't fix` on it, preventively.
