### ISSUE TITLE
Unknown column type "timestamp" requested

### ISSUE THREAD

**Issue by marktopper** [doctrine/dbal#2558]
Are you gonna add support for the `timestamp` type?

Cause now I get the following exception when trying to modify a column of the `timestamp` type.
Else, how to work around it?

### Exception:
```
[Doctrine\DBAL\DBALException]
  Unknown column type "timestamp" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DB
  AL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrine
  TypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.
```

**Comment by Ocramius** [comment]
`TIMESTAMP` is a MySQL-specific type that we're not going to support. You will most probably need a custom type, or just use a `DATETIME` instead.

**Comment by marktopper** [comment]
Just saw this now, however already made the [pull request](2559) for MySQL support of the Timestamp type.

Might just make it into a custom type instead which people using MySQL might wanna add.

**Comment by Ocramius** [comment]
Closing that PR - please re-submit to https://github.com/beberlei/doctrineextensions if interested (that repo contains MySQL-specific stuff)

**Comment by Jujunol** [comment]
As far as I'm aware, `timestamp` isn't _"MySQL-Specific"_ It's used in MariaDB, PostgreSQL, Transact-SQL, and Oracle as well.

**Comment by Ocramius** [comment]
It has custom formats on all these platforms, and specifically the MySQL one should never really be used.

**Comment by Bmsandoval** [comment]
Can we rediscuss "should never really be used"? In Mysql, the only way to pull the time and date out in the mysql server's current time zone is to use the timestamp or timestamps. The problem is I don't need to add a create and an updated stamp.

**Comment by Ocramius** [comment]
> the only way to pull the time and date out in the mysql server's current time zone is to use the timestamp or timestamps

Please save date and time by *providing* the timezone, if required: using the storage server's defaults is just a recipe for more confusion between application and storage.

See https://github.com/doctrine/doctrine2/issues/6661

**Comment by Majkl578** [comment]
Note that Postgres also has timestamptz type which you can transparently (except schema introspection) use with datetimetz_immutable.
