### ISSUE TITLE
Integrating asynchronous driver with DBAL

### ISSUE THREAD

**Issue by mwsv** [doctrine/dbal#2562]
I'm working on a project with event driven architecture, using technologies like Ratchet, Redis Pub/Sub etc., where I also need to use Doctrine. As far as I know, Doctrine execute SQL queries in a blocking way, therefore I was wondering is it possible to write some extension for DBAL, which would use one of database drivers with support for asynchronous usage, like e.g.:

https://pecl.php.net/package/pq
https://mdref.m6w6.name/pq

...or there are some limitations in terms of integrating such kind of libraries with DBAL. Thank you for any feedbacks.

**Comment by Ocramius** [comment]
Building an adapter is possible, but not beneficial. At the end of the day, what you want is asynchronous code, while the DBAL provides a synchronous API, defeating the advantages before we even start.

A new asynchronous API would be required, but we first need something from async-interop to work with, which is necessary to design an asynch DBAL API.

**Comment by morozov** [comment]
Closing as it hasn't gotten any traction.
