### ISSUE TITLE
unit test uses variadic params, HHVM does not currently support variadic params

### ISSUE THREAD

**Issue by photodude** [doctrine/dbal#2567]
DBAL unit tests uses variadic params, [HHVM does not currently support variadic params in php files](https://github.com/facebook/hhvm/issues/6954) and the DBAL unit tests errors as follows

```php
Fatal error: Parameter $argv is variadic and has a type constraint (array);
variadic params with type constraints are not supported in non-Hack files in
/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator.php(345)(99903a0f89bff37673bd5a019eb1a617) : eval()'d code on line 255
```

If possible the specific unit tests should be rewritten to eliminate the use of variadic params

**Comment by Ocramius** [comment]
Not an issue of doctrine: to be reported towards HHVM or PHPUnit mock objects.
