### ISSUE TITLE
Incorrect sequence name generated with postgresql

### ISSUE THREAD

**Issue by lazaro3487** [doctrine/dbal#2574]
There is an strange behavior when a primary key is generated using the identity strategy with postgreSQL because doctrine generate a name for the secuence with a length that postgresql does not support. The sequence name in PostgreSQL are limited to 63 characters. In this entity class:

```php
/**
 * CompanyConfigBankAccount
 *
 * @ORM\Table(name="tbl_company_config_bank_account")
 * @ORM\Entity() 
 */
class CompanyConfigBankAccount
{
    /**
     * @var integer
     * 
     * @ORM\Column(name="pk_company_config_bank_account", type="smallint")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;
}
```

The sequence name generated by doctrine is tbl_company_config_bank_account_pk_company_config_bank_account_seq but PostgreSQL truncate this name to tbl_company_config_bank_account_pk_company_config_bank_account_

I think this is a bug. Regards. #

**Comment by Ocramius** [comment]
> By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes. If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h . Meaning, the only way to change it is to hack the source code and recompile PostgreSQL.

https://stackoverflow.com/questions/8213127/maximum-characters-in-labels-table-names-columns-etc

Closing as `can't fix`, since we can't do anything about it on our side, and changing expected names would be worse.

It would probably nice by postgres to cause an error, rather than a silent truncation.
