### ISSUE TITLE
Missing ping method in 2.4 branch ... 

### ISSUE THREAD

**Issue by arlaneenalra** [doctrine/dbal#2575]
The documentation states  that the Doctrine\DBAL\Connection has a ping method:

See:

http://www.doctrine-project.org/api/dbal/2.4/source-class-Doctrine.DBAL.Connection.html#1554-1590

http://www.doctrine-project.org/api/dbal/2.4/class-Doctrine.DBAL.Connection.html

Strangely, I've been unable to find the method in the actual release. I checked versions 2.4.5-2.4.3 via their release tags on github ...

It does look like the method is back in 2.5, any particular reason it's gone in 2.4?

**Comment by Ocramius** [comment]
@arlaneenalra it was only merged into 2.5, as a new feature. We only merge bugfixes into stable branches.

Ref: https://github.com/doctrine/dbal/pull/414

**Comment by arlaneenalra** [comment]
@Ocramius Where's the appropriate place to file bugs against the documentation then?  Since that is clearly what's wrong here...

**Comment by Ocramius** [comment]
@arlaneenalra I think the 2.4 docs are compiled against the wrong branch. Check https://github.com/doctrine/doctrine-website-sphinx
