### ISSUE TITLE
Impossible to save null to nullable boolean field

### ISSUE THREAD

**Issue by aivus** [doctrine/dbal#2580]
It's impossible to save null to nullable boolean field.
`PDO::PARAM_BOOL` converts any values to `true/false`.
`PDO::PARAM_NULL` could be used for this purpose

But I don't see a good approach for this.
It would be great to have `value` in `Type::getBindingType()` in [BooleanType](https://github.com/doctrine/dbal/blob/b551fcb26a81e230085c0dca88174573b6c36609/lib/Doctrine/DBAL/Types/BooleanType.php#L68) or any other approach.

I can prepare PR if we find solution for this.

It was discussed in https://github.com/doctrine/dbal/pull/632 but solution wasn't found.

**Comment by deeky666** [comment]
This requires a use-case that reveals the issue, at best a test case.

**Comment by aivus** [comment]
@deeky666 test exists, but it has incorrect value:
https://github.com/doctrine/dbal/blob/292a65169120d01b5d83067577c784e2f088339d/tests/Doctrine/Tests/DBAL/Functional/Ticket/DBAL630Test.php#L163

And some discuss here:
https://github.com/doctrine/dbal/pull/632/files#r15512990

**Comment by deeky666** [comment]
@aivus I remember the issue. I don't see what we can do about it as it seems to be a bug in the PDO driver with emulated prepares. IMO it has to be fixed in PHP. I don't have a solution for this other than disabling emulated prepares.

**Comment by morozov** [comment]
Closing as stale and likely unrelated to the DBAL.
