### ISSUE TITLE
Single quotes on mysql reserved keywords in schema creation

### ISSUE THREAD

**Issue by joubertredrat** [doctrine/dbal#2582]
Hi guys,

I'm testing Schema from DBAL and I discovered this problem below:

```php
<?php
require(__DIR__.'/vendor/autoload.php');

$schema = new \Doctrine\DBAL\Schema\Schema();
$products = $schema->createTable('products');
$products->addColumn(
    'date_insert',
    'datetime',
    [
        'default' => 'CURRENT_TIMESTAMP',
        'comment' => 'Insert date'
    ]
);
$products->addColumn(
    'date_update',
    'datetime',
    [
        'notnull' => false,
        'default' => "NULL ON UPDATE CURRENT_TIMESTAMP",
        'comment' => 'Last change date'
    ]
);
$queries = $schema->toSql(new Doctrine\DBAL\Platforms\MySQL57Platform());
echo $queries[0];

$queries = $schema->toSql(new Doctrine\DBAL\Platforms\MySqlPlatform());
echo $queries[0];
```

This code above, the expected result is
```sql
CREATE TABLE products (
  date_insert DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT 'Insert date', 
  date_update DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'Last change date'
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
```

But schema is putting single quotes on `NULL ON UPDATE CURRENT_TIMESTAMP`, causing a SQL syntax error.
```sql
CREATE TABLE products (
  date_insert DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT 'Insert date', 
  date_update DATETIME DEFAULT 'NULL ON UPDATE CURRENT_TIMESTAMP' COMMENT 'Last change date'
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
```

On debug here, we saw that single quotes is removed only if default is `CURRENT_TIMESTAMP` and not if is user another keywords, as  `NOW()`, `NULL`, `CURRENT_TIME`, `CURRENT_DATE` and others.
https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L2278

I was able to fix this in my test with this class

```php
<?php
/**
 * Class with default bugfix for tests
 *
 * @author Joubert <eu@redrat.com.br>
 */

namespace Doctrine\DBAL\Platforms;

class MySQL57PlatformWithFix extends MySQL57Platform
{
    /**
     * Get reserved keywords for default
     *
     * @return array
     */
    public static function getReservedDefaultKeywords()
    {
        return [
            'NULL',
            'CURRENT_DATE',
            'CURRENT_TIME',
            'CURRENT_TIMESTAMP',
            'NULL ON UPDATE CURRENT_DATE',
            'NULL ON UPDATE CURRENT_TIME',
            'NULL ON UPDATE CURRENT_TIMESTAMP',
        ];
    }

    /**
     * @see Doctrine\DBAL\Platforms\MySqlPlatform::getDefaultValueDeclarationSQL()
     */
    public function getDefaultValueDeclarationSQL($field)
    {
        if (in_array($field['default'], self::getReservedDefaultKeywords())) {
            return " DEFAULT ".$field['default'];
        }

        return parent::getDefaultValueDeclarationSQL($field);
    }
}
```

Now is time to talk guys, this is a good question.

**Comment by Ocramius** [comment]
@joubertredrat hmm, I don't think that `ON UPDATE` semantics are supported by DBAL at all. Any other references to `ON UPDATE` in the codebase?

**Comment by joubertredrat** [comment]
Hi @Ocramius 

On DBAL have reference to `ON UPDATE` only for foreign key in schema, as below: 

https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L2468
https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php#L139

You can view information about `ON UPDATE` for fields in http://dev.mysql.com/doc/refman/5.7/en/timestamp-initialization.html

**Comment by Ocramius** [comment]
Yeah, what I'm thinking here is that `ON UPDATE` is not an default value, but an additional clause (which isn't really a value).

I can't even find it in the EBNF (sigh): https://dev.mysql.com/doc/refman/5.7/en/create-table.html

I'm inclined to say that this is simply out of scope here, since `ON UPDATE` semantics vary wildly depending on RDBMS, but maybe @deeky666 has a better idea of how to handle this.

**Comment by joubertredrat** [comment]
> Yeah, what I'm thinking here is that ON UPDATE is not an default value, but an additional clause (which isn't really a value).

Ah, now I understood, really isn't a default value and on various tools here is different notation. Phpmyadmin display "Extra", Mysql workbench display "Default" or "Expression", Adminer don't display anything.

![phpmyadmin](https://cloud.githubusercontent.com/assets/1520407/21454740/00b63cf4-c902-11e6-887a-7c0080d50e2d.png)
![workbench](https://cloud.githubusercontent.com/assets/1520407/21454747/14f22818-c902-11e6-8b99-5c26df410140.jpg)
![adminer](https://cloud.githubusercontent.com/assets/1520407/21454738/00b1e5e6-c902-11e6-9ce9-01d937463e83.png)

**Comment by joubertredrat** [comment]
@Ocramius I have an idea for solve this.

On documentation saw that is possible to configure specific configuration for specific database https://doctrine-dbal.readthedocs.io/en/latest/reference/schema-representation.html#vendor-specific-options

With this I think that we can create one config named `onupdate` into `customSchemaOptions` and create validaiton to work only with `datetime` and specific mysql reserved keys.

What you think?

**Comment by Ocramius** [comment]
@joubertredrat I can't really help without @deeky666 looking into this first, sorry (he's the DBAL "gatekeeper")

In my opinion, this doesn't really fit DBAL: would rather have a custom migration written down instead.

**Comment by deeky666** [comment]
@joubertredrat `ON UPDATE CURRENT_TIMESTAMP` clause is unsupported atm. It is not abstractable so yes it could be implemented via `customSchemaOptions` for `Column` if  the schema comparator is capable of comparing it. I would accept it.

**Comment by abdgad** [comment]
@deeky666 @Ocramius I am having a similar issue.
I created a TIMESTAMP type for mysql. The default value can be `CURRENT_TIMESTAMP`. However, in the query it gets quoted `'CURRENT_TIMESTAMP'`. This is the DBAL code responsible. It's only checking for `DateTime, DateTimeTz`.

What solution do you suggest, in order to avoid quoting the keywork?

```php
public function getDefaultValueDeclarationSQL($field)
    {
        $default = empty($field['notnull']) ? ' DEFAULT NULL' : '';

        if (isset($field['default'])) {
            $default = " DEFAULT '".$field['default']."'";
            if (isset($field['type'])) {
                if (in_array((string) $field['type'], array("Integer", "BigInt", "SmallInt"))) {
                    $default = " DEFAULT ".$field['default'];
                } elseif (in_array((string) $field['type'], array('DateTime', 'DateTimeTz')) && $field['default'] == $this->getCurrentTimestampSQL()) {
                    $default = " DEFAULT ".$this->getCurrentTimestampSQL();
                } elseif ((string) $field['type'] == 'Time' && $field['default'] == $this->getCurrentTimeSQL()) {
                    $default = " DEFAULT ".$this->getCurrentTimeSQL();
                } elseif ((string) $field['type'] == 'Date' && $field['default'] == $this->getCurrentDateSQL()) {
                    $default = " DEFAULT ".$this->getCurrentDateSQL();
                } elseif ((string) $field['type'] == 'Boolean') {
                    $default = " DEFAULT '" . $this->convertBooleans($field['default']) . "'";
                }
            }
        }

        return $default;
    }
```

**Comment by joubertredrat** [comment]
Hi @abdgad 

I'm working on this issue in this exactly moment, I think that I will open PR today or tomorrow, you can test for me too?

Thanks

**Comment by abdgad** [comment]
@joubertredrat sure

**Comment by joubertredrat** [comment]
@abdgad PR opened
