### ISSUE TITLE
Context of SQLLogger::stopQuery()

### ISSUE THREAD

**Issue by MatthewVita** [doctrine/dbal#2589]
Hi,

I'm trying to determine what the context of the `stopQuery` method in the `\Doctrine\DBAL\Logging\SQLLogger` interface is.

Obviously, it's called when the last query is finished, but does it only get called when a query is successful? I'm looking into `\Doctrine\DBAL\Connection\`'s `executeQuery` method and it appears that `stopQuery` is called unless the SQL throws an exception.

Is it possible that something bad can happen with the query execution without throwing an exception, leading to `stopQuery` getting called?

Thanks,
Matthew

**Comment by Ocramius** [comment]
> Is it possible that something bad can happen with the query execution without throwing an exception, leading to `stopQuery` getting called?

A query failing silently would be a bug. That should never happen.

**Comment by MatthewVita** [comment]
@Ocramius okay so `stopQuery` is only called if the query succeeds?

Also, great project. Thanks.

Thanks,
Matthew

**Comment by Ocramius** [comment]
Correct 👍
