### ISSUE TITLE
assertValidIdentifier not valid with Oracle Schema Object Naming Rules 

### ISSUE THREAD

**Issue by IMP3ter** [doctrine/dbal#2595]
assertValidIdentifier in OraclePlatform is not valid with Oracle Schema Object Naming Rules.

It is not possible to use a dot in sequence names.

Schema Object Names and Qualifiers :
http://docs.oracle.com/cd/B19306_01/server.102/b14200/sql_elements008.htm

Pierre

**Comment by Ocramius** [comment]
Are we talking about [`OraclePlatform::assertValidIdentifier()`](https://github.com/doctrine/dbal/blob/b9b6714494c646946a0cd3d2be57a239aff977a3/lib/Doctrine/DBAL/Platforms/OraclePlatform.php#L50) ?

**Comment by IMP3ter** [comment]
Hi Ocramius,

Yes on preg_match in [OraclePlatform::assertValidIdentifier() ](https://github.com/doctrine/dbal/blob/b9b6714494c646946a0cd3d2be57a239aff977a3/lib/Doctrine/DBAL/Platforms/OraclePlatform.php#L50)

**Comment by deeky666** [comment]
@IMP3ter what exactly is the issue here? I don't see that the regex accepts dots.

**Comment by IMP3ter** [comment]
@deeky666 the regex must accept dots but she don't.

Oracle naming rules : "schema"."table" or "schema"."sequence"

**Comment by Ocramius** [comment]
`"schema"` is an identifier, `"table"` is an identifier. `"schema"."table"` is a combination of two identifiers.

Where is this failing for you?

**Comment by IMP3ter** [comment]
@Ocramius I'm agree but in [OraclePlatform:: lastInsertId($name = null) ](https://github.com/doctrine/dbal/blob/b9b6714494c646946a0cd3d2be57a239aff977a3/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php#L154) OraclePlatform::assertValidIdentifier() not autorize dot in $name.

I can't ask a sequence with name is "schema"."sequence".

**Comment by Ocramius** [comment]
That makes it more clear. Do you have an example snippet that could be added to the [`OraclePlatformTest`](https://github.com/doctrine/dbal/blob/475097dda26216a8641eac6df89e171f4c3c8323/tests/Doctrine/Tests/DBAL/Platforms/OraclePlatformTest.php)?

**Comment by IMP3ter** [comment]
I have add the bold value.

`static public function dataValidIdentifiers()
    {
        return array(
            array('a'),
            array('foo'),
            array('Foo'),
            array('Foo123'),
            array('Foo#bar_baz$'),
            **array('foo.bar'),**
            array('"a"'),
            array('"1"'),
            array('"foo_bar"'),
            array('"@$%&!"'),
        );
    }`

**Comment by IMP3ter** [comment]
I have add `array('foo.bar')`.

       static public function dataValidIdentifiers()
       {
          return array(
              array('a'),
              array('foo'),
              array('Foo'),
              array('Foo123'),
              array('Foo#bar_baz$'),
              array('foo.bar'),
              array('"a"'),
              array('"1"'),
              array('"foo_bar"'),
              array('"@$%&!"'),
          );
       }

**Comment by deeky666** [comment]
Maybe we'll have to split FQNs in the lastInsertId() method and then check each identifier individually...

**Comment by deeky666** [comment]
PR created: #2604

**Comment by IMP3ter** [comment]
@deeky666 thank you for your PR

**Comment by Ocramius** [comment]
@IMP3ter can you try latest `master`? #2604 was merged.

**Comment by deeky666** [comment]
Closing this as fixed. Feel free to reopen if you still have problems with current `master`.
