### ISSUE TITLE
PostgreSQL unable to auto increment. n/b Using doctrine/migrations to create schema.

### ISSUE THREAD

**Issue by pitsolu** [doctrine/dbal#2601]
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "id" violates not-null constraint

```php
$conn = $em->getConnection();

$conn->insert("table", array(

	"status"=>"testStatus",
	"code"=>"testCode",
	"alias"=>"testAlias",
	"name"=>"testName",
	"type"=>"testType",
	"descr"=>"testDescr"
));
```

**Comment by Ocramius** [comment]
Seems about right/expected.

Closing as `invalid`

**Comment by pitsolu** [comment]
Please elaborate ...  am in the dark here..

**Comment by Ocramius** [comment]
@pitsolu you didn't define a value for the `id` column, and the DB didn't generate a default value either, since there is no default in the DDL for that table.

**Comment by pitsolu** [comment]
@Ocramius Thanks for your speed response. I appreciate it .  I created the schema like this:
```php

        $coa = $schema->createTable('table');
        $coa->addColumn('id', 'integer', array('autoincrement' => true));
        $coa->addColumn('status', 'string');
        $coa->addColumn('code', 'string');
        $coa->addColumn('alias', 'string');
        $coa->addColumn('name', 'string');
        $coa->addColumn('type', 'string');
        $coa->addColumn('descr', 'text', array('notnull' => false));

        $coa->addUniqueIndex(array("name"));
        $coa->addUniqueIndex(array("code"));
        $coa->addUniqueIndex(array("alias"));
        $coa->setPrimaryKey(array('id'));
```
Shouldn't this enable postgres to auto increment ?

**Comment by Ocramius** [comment]
And what was the DDL generated from that schema creation snippet? The issue may be there.

**Comment by pitsolu** [comment]
/**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="coa_id_seq", allocationSize=1, initialValue=1)
     */
    private $id;

Seems to be okay. But still no auto increment.

**Comment by deeky666** [comment]
@pitsolu can you please show the generated SQL that was used to create the table as @Ocramius suggested?

**Comment by pitsolu** [comment]
```sql
     -> CREATE TABLE coa (id SERIAL NOT NULL, coa_id INT DEFAULT NULL, status VARCHAR(255) NOT NULL, code VARCHAR(255) NOT NULL, alias VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, descr TEXT DEFAULT NULL, PRIMARY KEY(id))
     -> CREATE INDEX IDX_6D008ACD3E5AB08F ON coa (coa_id)
     -> CREATE UNIQUE INDEX UNIQ_6D008ACD5E237E06 ON coa (name)
     -> CREATE UNIQUE INDEX UNIQ_6D008ACD77153098 ON coa (code)
     -> CREATE UNIQUE INDEX UNIQ_6D008ACDE16C6B94 ON coa (alias)
```

**Comment by Ocramius** [comment]
Seems about right: serial field and insert failing on it. Is the DB in sync with this definition? Can you dump the DDL from the DB, rather than from the tool?

**Comment by deeky666** [comment]
@pitsolu I think you are using the wrong identity generator strategy in your mapping. It should be `IDENTITY` I think.

**Comment by pitsolu** [comment]
This what I got
```
                                 Table "public.coa"
 Column |          Type          |                    Modifiers                     
--------+------------------------+--------------------------------------------------
 id     | integer                | not null default nextval('coa_id_seq'::regclass)
 coa_id | integer                | 
 status | character varying(255) | not null
 code   | character varying(255) | not null
 alias  | character varying(255) | not null
 name   | character varying(255) | not null
 type   | character varying(255) | not null
 descr  | text                   | 
Indexes:
    "coa_pkey" PRIMARY KEY, btree (id)
    "uniq_6d008acd5e237e06" UNIQUE, btree (name)
    "uniq_6d008acd77153098" UNIQUE, btree (code)
    "uniq_6d008acde16c6b94" UNIQUE, btree (alias)
    "idx_6d008acd3e5ab08f" btree (coa_id)
Foreign-key constraints:
    "fk_6d008acd3e5ab08f" FOREIGN KEY (coa_id) REFERENCES coa(id) ON UPDATE CASCADE
Referenced by:
    TABLE "coa" CONSTRAINT "fk_6d008acd3e5ab08f" FOREIGN KEY (coa_id) REFERENCES coa(id) ON UPDATE CASCADE
    TABLE "transx_config" CONSTRAINT "fk_e57250741cc16efe" FOREIGN KEY (credit) REFERENCES coa(id) ON UPDATE CASCADE
    TABLE "transx_config" CONSTRAINT "fk_e5725074e6c5b24" FOREIGN KEY (debit) REFERENCES coa(id) ON UPDATE CASCADE

```

**Comment by pitsolu** [comment]
@deeky666 Everything is generate, migrations to schema, schema to entities, i never coded anything manually

**Comment by pitsolu** [comment]
@deeky666 @Ocramius am back. Thanks for your help and patience. You can find the code on [books](https://github.com/pitsolu/books)

to setup:
composer update
sudo -u postgres createdb accounting
./bin/db/recreate
./bin/seeder/setup

here to find:
- [migrations](https://github.com/pitsolu/books/tree/master/database/schema/Schema/Migration)
- [models](https://github.com/pitsolu/books/tree/master/app/src/Accounts/AccountsModule/Model)

**Comment by pitsolu** [comment]
@Ocramius @deeky666 Sorry to waste your time, issue solved.

**Comment by Ocramius** [comment]
@pitsolu what's the resolution? What was wrong? Can you please clarify it here for reference (and future readers), please?

**Comment by pitsolu** [comment]
I was recreating the database through obsolete entities rather than migration was confusing the scripts .. sorry .. burnout.

```
Burnout is nature's way of telling you, you've been going through the motions your soul has departed; you're a zombie, a member of the walking dead, a sleepwalker. False optimism is like administrating stimulants to an exhausted nervous system -- Sam Keen
```

**Comment by Ocramius** [comment]
@pitsolu that's not a problem, as long as it's fixed and it is clear :-)
