### ISSUE TITLE
Weird createQueryBuilder behavior on UPDATE on SQL Server 2014

### ISSUE THREAD

**Issue by Norcoen** [doctrine/dbal#2610]
I had this code running for some years with a mysql database.
Recently we had to switch to SQL Server 2014, now I'm getting weird errors because somehow it does not like the UPDATE-Syntax doctrine is using.

It seems like sqlsrv does not like the table alias, while in the [documentation](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/query-builder.html#set-clause) this seems to be fine
 ```php
$afrmol = $db->createQueryBuilder()
	->update('tbl_priv_user', 'u')
	//->set('u.lastlogin', 'CURRENT_TIMESTAMP()')
	->set('u.logincount', 'u.logincount + 1')
	//->where('u.userid = :usermail')
	//->setParameter('usermail', $_SESSION['user'])
	->execute()
;
echo "affected rows:" . $afrmol;
exit;
```

```
Internal Server Error

An exception occurred while executing 'UPDATE tbl_priv_user u SET u.logincount = u.logincount + 1': SQLSTATE[42000]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near 'u'.

[D:/wwwroot_test/includes/doctrine/doctrine-2.4.5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:864] Doctrine\DBAL\DBALException::driverExceptionDuringQuery(PDOException::__set_state(array('errorInfo'=>array('42000',102,'[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near 'u'.'))),'UPDATE tbl_priv_user u SET u.logincount = u.logincount + 1',array())
[D:/wwwroot_test/includes/doctrine/doctrine-2.4.5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php:206] Doctrine\DBAL\Connection->executeUpdate('UPDATE tbl_priv_user u SET u.logincount = u.logincount + 1',array(),array())
[D:/wwwroot_test/configuration/legacy_configuration.php:78] Doctrine\DBAL\Query\QueryBuilder->execute()
[D:/wwwroot_test/configuration/extended_configuration.php:37] require_once('D:\wwwroot_test\configuration\legacy_configuration.php')
[D:/wwwroot_test/index.php:36] require('D:\wwwroot_test\configuration\extended_configuration.php')
```

**Comment by Ocramius** [comment]
Can't do much about this: the query builder simply [smashes your query components together by design](https://github.com/doctrine/dbal/blob/292a65169120d01b5d83067577c784e2f088339d/lib/Doctrine/DBAL/Query/QueryBuilder.php#L1198-L1203)

If SQL server does not support aliases, then they should probably not be used there.

**Comment by Norcoen** [comment]
But whats the point of using doctrine/dbal? 
If this is not handled by the DBAL wheres the difference to just using PDO?

**Comment by Ocramius** [comment]
The current DBAL query builder is really not sophisticated. We're thinking of SQL AST for 3.*, but we're far from any clear plan on how to implement it correctly
