### ISSUE TITLE
Outdated VERSION constant value in 2.5 branch

### ISSUE THREAD

**Issue by mondrake** [doctrine/dbal#2613]
Hi, the value of the VERSION constant in the 2.5 branch is still at 2.5.5-DEV while 2.5.10 is out.

```
    /**
     * Current Doctrine Version.
     */
    const VERSION = '2.5.5-DEV';

```

**Comment by Ocramius** [comment]
Yarp, will try remembering it in the next release, sorry.

Closing here, can't do anything about past releases.
