### ISSUE TITLE
Automatic array type detection

### ISSUE THREAD

**Issue by jnvsor** [doctrine/dbal#2621]
It's not too hard to make automatic array type detection so that you don't have to fill in the types array when passing an array for an `IN()`.

Is there a reason this isn't in DBAL by default?

**Comment by deeky666** [comment]
@jnvsor I don't get what you mean. Can you please clarify your issue? Maybe give an example.

**Comment by jnvsor** [comment]
Right now if you want to use something like `PARAM_STR_ARRAY` you're required to supply the type:

```php
$dbal->fetchAll(
  'SELECT * FROM users WHERE username = ? AND id IN(?)',
  ['jnvsor', [1, 2, 3]],
  [null, \Doctrine\DBAL\Connection::PARAM_STR_ARRAY]
);
```

I can implement this by extending the connection class but I was wondering if there was a reason for not handling this automatically?

```php
$dbal->fetchAll(
  'SELECT * FROM users WHERE username = ? AND id IN(?)',
  ['jnvsor', [1, 2, 3]]
);
```

**Comment by deeky666** [comment]
That's a good point. I will have a look at it as soon as I have time.

**Comment by jnvsor** [comment]
A potential reason not to implement this is that it also applies to `\Doctrine\DBAL\Types`. If making `PARAM_STR_ARRAY`/`PARAM_INT_ARRAY` have priority over eg `SIMPLE_ARRAY` isn't a an issue (Makes sense to me) then perhaps automatic types could be implemented for `DateTime` and the like too - but now we're talking about a big feature not a quick change.

**Comment by morozov** [comment]
The binding type should be defined by the program logic, not the input.
