### ISSUE TITLE
Question about TableDiff renamed columns and indexes

### ISSUE THREAD

**Issue by abdgad** [doctrine/dbal#2624]
I am working on a database update tool. I want to use **alterTable($tableDiff)** to execute the update.
The problem is that if both the name and properties of an existing column were changed, it will not be included  in TableDiff renamedColumns, it will be removed and added as a new column.
So I created a method to detect renamed columns.
**$this->getRenamedColumns()** returns the columns that were renamed.

```php
    protected function fixRenamedColumnsDiff(TableDiff $tableDiff)
    {
        foreach ($this->getRenamedColumns() as $oldName => $newName) {
            if (!isset($tableDiff->renamedColumns[$oldName])) {
                $tableDiff->renamedColumns[$oldName] = $tableDiff->addedColumns[$newName];

                unset($tableDiff->removedColumns[$oldName]);
                unset($tableDiff->addedColumns[$newName]);
            }
        }
    }
```
- Is this approach enough/valid to rename and update the columns?
- Can I use the same approach for renamedIndexes?
- What other details should I account for to avoid unwanted errors?

**Comment by abdgad** [comment]
It seems that the behavior of different platforms is different when it comes to renamedColumns.
On Mysql, the full column is updated, including the name and the properties. On Sql Server however, only the name is updated... So this approach doesn't work for all platforms...

I am thinking to make 2 separate table updates:
1. First, rename the columns and indexes.
2. After that, TableDiff will result in changedColumns and changedIndexes. So issue a second update and everything should be fine...

What do you guys think?

**Comment by Ocramius** [comment]
@abdgad what's the resolution for this issue? Is it supposed to be closed?
