### ISSUE TITLE
[RFC] testing Oracle DB on travis ci

### ISSUE THREAD

**Issue by photodude** [doctrine/dbal#2626]
Apparently, someone has a workaround for testing Oracle DB on travis ci as well https://github.com/cbandy/travis-oracle

an Oracle account is required and the Oracle username and password has to be in the build environment variables either as hidden repository settings or encrypted variables

**Comment by Ocramius** [comment]
Talked at PHPBenelux with @continuousphp: they can provide CI for OracleDB too (can be integrated here)

**Comment by DeepDiver1975** [comment]
I've been chatting with @deeky666 these days - owncloud is willing to support the doctrine project here as well.

**Comment by Ocramius** [comment]
I'm fine with any approach, but it needs to be directly integrated with the PR feedback and commit CI status

**Comment by deeky666** [comment]
@DeepDiver1975 did you have time to investigate integration possibilities already? @Ocramius can you tell something about the approach you guys discussed?

**Comment by Ocramius** [comment]
@deeky666 @continuousphp is pretty much similar to travis-ci, but custom containers are provided. The deal is simple: building with continuousphp provides some visibility for them, but they also have to provide a patch with the oracledb testing (multiple versions).

**Comment by DeepDiver1975** [comment]
What I can offer: run PR testing on jenkins - similar to what is done already today: https://jenkins.owncloud.org/view/doctrine/

As of today we are only testing against oracle xe 11g

**Comment by deeky666** [comment]
@Ocramius I tried out @continuousphp. See [here](https://continuousphp.com/git-hub/deeky666/dbal/build/c42f3663-5fbe-4a44-8b48-a10e424367f9/output)

Seems to be pretty straight forward. Should we add such a setup for now to at least be able to test one Oracle environment? I could PR that damn thing.

**Comment by Ocramius** [comment]
@DeepDiver1975 your offer is very kind, but let's try the @continuousphp setup first, mostly because that reduces the amount of customization and internal knowledge (CI PaaS is preferrable). @deeky666 I'd say that we can proceed there, and then fallback to custom jenkins ( @DeepDiver1975's ) if that fails.

**Comment by deeky666** [comment]
PR created: #2630

**Comment by Ocramius** [comment]
This is an improvement, therefore moved to `2.6`

**Comment by deeky666** [comment]
@Ocramius while I agree that we don't backport improvements, I doubt this policy is useful here. The change is not really related to production code and helps identifying Oracle related bugs in the code. Why shouldn't we want to know if our backports also succeed on Oracle in `2.5`?

**Comment by Ocramius** [comment]
> I doubt this policy is useful here.

It may not be useful, but we're really just complicating our setup here, and doing so for the gazillion versions supported in 2.5.* is not gonna make our lives easier. Keeping this on `master` is a decent tradeoff, IMO
