### ISSUE TITLE
Change QueryBuilder numerical parameters to start from 1

### ISSUE THREAD

**Issue by jnvsor** [doctrine/dbal#2627]
According to the [querybuilder docs](http://doctrine-orm.readthedocs.io/projects/doctrine-dbal/en/latest/reference/query-builder.html#security-safely-preventing-sql-injection):

> Due to an API design error the numerical parameters in the QueryBuilder API start with the needle 0, not with 1 as in the PDO API. This is very unfortunate, but we have found no BC way to fix this.

The 3.0 milestone seems like a nice place to fix this - could you add this to the 3.0 milestone?

**Comment by Ocramius** [comment]
The BC break is still excessive and hard to spot

**Comment by jnvsor** [comment]
Couldn't you add a property to the querybuilder specifying whether keys should be decremented or not before passing to `executeQuery`/`executeUpdate` and set it to legacy (along with an `E_USER_DEPRECATED`) whenever `setParameter(0, ...)` is called? (Since new code will be 1-indexed)

**Comment by Ocramius** [comment]
No, it's just not worth doing that. Additionally, I'd suggest that following PDO's API is a bad idea in most scenarios, given its exotic/weird design decisions (and also: nobody really wants to fix those in php core, since the extension is quite messy)

**Comment by jnvsor** [comment]
Ok, thanks for the response!
