### ISSUE TITLE
ORA-01002: fetch out of sequence

### ISSUE THREAD

**Issue by bertrandgauthier** [doctrine/dbal#2637]
Hi,

Since v2.5.11 and rework on closeCursor for OCI8, i get this PHP warning :
`Warning: oci_fetch(): ORA-01002: fetch out of sequence in /home/[...]/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php on line 195`.

No such problem in v2.5.10.

If i put back `return oci_free_statement($this->_sth);` in OCI8Statement::closeCursor(), everything's ok.

Thanks.

**Comment by deeky666** [comment]
@bertrandgauthier can you please provide at least a sample script using DBAL that reproduces the error?

**Comment by kutyakinma** [comment]
I has this problem

For example, log of error stack when I try to login in site:

> in vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\OCI8\OCI8Statement.php at line 196   + 
> at OCI8Statement ->closeCursor () 
> in vendor\doctrine\orm\lib\Doctrine\ORM\Internal\Hydration\AbstractHydrator.php at line 207   + 
> at AbstractHydrator ->cleanup () 
> in vendor\doctrine\orm\lib\Doctrine\ORM\Internal\Hydration\SimpleObjectHydrator.php at line 55   + 
> at SimpleObjectHydrator ->cleanup () 
> in vendor\doctrine\orm\lib\Doctrine\ORM\Internal\Hydration\AbstractHydrator.php at line 149   + 
> at AbstractHydrator ->hydrateAll (object(OCI8Statement), object(ResultSetMapping), array()) 
> in vendor\doctrine\orm\lib\Doctrine\ORM\Persisters\Entity\BasicEntityPersister.php at line 720   + 
> at BasicEntityPersister ->load (array('username' => 'user'), null, null, array(), null, 1, null) 
> in vendor\doctrine\orm\lib\Doctrine\ORM\EntityRepository.php at line 196   + 
> at EntityRepository ->findOneBy (array('username' => 'user')) 
> in vendor\symfony\symfony\src\Symfony\Bridge\Doctrine\Security\User\EntityUserProvider.php at line 51   + 
> at EntityUserProvider ->loadUserByUsername ('user') 
> in vendor\symfony\symfony\src\Symfony\Component\Security\Core\User\ChainUserProvider.php at line 49   + 
> at ChainUserProvider ->loadUserByUsername ('user') 
> in vendor\repos\app-bundle\src\Security\ChainAuthenticator.php at line 44   +

**Comment by morozov** [comment]
I don't use the ORM or symfony/security so I cannot reproduce the example above. Could anyone please put together a code example which I could run to reproduce this?

**Comment by deeky666** [comment]
I cannot reproduce this. The only improvement I see here is to use `oci_cancel()` instead of `while (oci_fetch($this->_sth));` which seems more appropriate and efficient.

**Comment by deeky666** [comment]
@bertrandgauthier can you try to use `oci_cancel($this->_sth)` and see if it works? Then I will send a PR.

**Comment by bertrandgauthier** [comment]
With `oci_cancel($this->_sth)`, it's ok, no more warning.

I use in my app the doctrine/doctrine-orm-module for ZF2. I did try to reproduce the warning in a new project with only doctrine/dbal package but i didn't succeed, sorry.

**Comment by fayouz** [comment]
Hello, 

:+1: 

I have the issue with the same module for ZF2. I reproduce the problem on line 195 of OCIStatement.php

Maybe a solution is to write @oci_fetch instead of oci_fetch. My work around is to downgrade dbal version in composer by adding this line : 
"doctrine/dbal": "2.5.10 as 2.5.11",

**Comment by Ocramius** [comment]
> `@oci_fetch` 

Urgh, no, let's not use the silencing operator, like, EVER.

As stated above, @deeky666 can't reproduce this, so please try providing a failing test scenario in order to ease working on the issue (we'll hopefully find a good workaround)

**Comment by fayouz** [comment]
Here is my stacktrace : 

![image](https://cloud.githubusercontent.com/assets/12844647/22685860/3bc5bdd0-ed22-11e6-8c2e-e2126952b8d6.png)

The issue occurs when i call the queryBuilder et using getArrayResult() . The query generated is this one:
SELECT f0_.CONFIG_ID AS CONFIG_ID_0, f0_.CONFIG_NAME AS CONFIG_NAME_1, f0_.CONFIG_PROPERTY AS CONFIG_PROPERTY_2, f0_.CONFIG_VALUE AS CONFIG_VALUE_3, f0_.CONFIG_DEFAULT_VALUE AS CONFIG_DEFAULT_VALUE_4, f0_.CONFIG_MODIF_DATE AS CONFIG_MODIF_DATE_5, f0_.CONFIG_MODIF_USER AS CONFIG_MODIF_USER_6 FROM FO_ADMIN_CONFIG f0_ WHERE (f0_.CONFIG_NAME = ? AND f0_.CONFIG_PROPERTY = ?) OR (f0_.CONFIG_NAME = ? AND f0_.CONFIG_PROPERTY = ?)

thank u in advance.

**Comment by Ocramius** [comment]
Yes, but that still needs to be reproduced in our test suite, and it needs to fail against CI in order for us to see what is causing it.

**Comment by deeky666** [comment]
@fayouz thank you for the information. I will try to reproduce this again but it would be awesome if you guys can try to figure out how the statement calls are done in which order. That might help

@Ocramius we will go with `oci_close()` which is much cleaner and the preferred way to do this as soon as we can reproduce it.

**Comment by fayouz** [comment]
I'm trying to do this request : 

` /**
     * @return array
     */
    public function findAllDeskMessages()
    {
        /** @var EntityRepository $entityRepo */
        $entityRepo = $this->getEntityRepository();

        $query = $entityRepo->createQueryBuilder('fc')
            ->where('fc.configName = :configName AND fc.configProperty = :configProperty1')
            ->orWhere('fc.configName = :configName AND fc.configProperty = :configProperty2')
            ->setParameters(array(
                    ':configName' => 'ADMIN_DESK',
                    ':configProperty1' => 'MESSAGE_1',
                    ':configProperty2' => 'MESSAGE_2',
                )
            );

        return $query->getQuery()->getArrayResult();
    }`

**Comment by deeky666** [comment]
@fayouz that doesn't help. I need to know how calls are made on the DBAL driver statement object. Still cannot reproduce it. Which PHP version are you using?

**Comment by fayouz** [comment]
Using PHP 5.6.6.
I don't how to get theses calls.

**Comment by bertrandgauthier** [comment]
I'm using PHP 5.6.29.

**Comment by deeky666** [comment]
Tried Tag `2.5.11` with PHP 5.6.6 / 7.0 / 7.1 and following test:

```php
$this->_conn->insert('stmt_test', array('id' => 1));
$this->_conn->insert('stmt_test', array('id' => 2));

$stmt = $this->_conn->executeQuery('SELECT * FROM stmt_test WHERE id = ?', array(1), array(\PDO::PARAM_INT));

while ($row = $stmt->fetch(\PDO::FETCH_ASSOC)) {

}

$stmt->closeCursor();
```

Still not able to reproduce.

**Comment by deeky666** [comment]
The call stack seems nothing different:
- [$stmt = $this->conn->executeQuery($sql, $params, $types);](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php#L714)
- [while ($row = $this->_stmt->fetch(PDO::FETCH_ASSOC))](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Internal/Hydration/SimpleObjectHydrator.php#L67-L69)
- [$this->_stmt->closeCursor();](https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Internal/Hydration/AbstractHydrator.php#L208)

**Comment by fayouz** [comment]
I'm linked to Oracle 8 Database, so I'm not using PDO Driver but OCI8 Driver

**Comment by deeky666** [comment]
Sure, I ran my tests against `oci8` too. Still I cannot get `oci_fetch()` to produce a warning.

**Comment by fayouz** [comment]
Do you have a sequence on your Id ?

**Comment by tserofcj** [comment]
We got the same issue with php 7.08, oracle 11g and v2.5.10.

**Comment by eisberg** [comment]
Same problem.

I insert a bookmark in OCI8Statment:

function   prepare in OCI8Connection  var_dump($prepareString):
string(225) "ALTER SESSION SET NLS_TIME_FORMAT = 'HH24:MI:SS' NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT = 'YYYY-MM-DD HH24:MI:SS TZH:TZM' NLS_NUMERIC_CHARACTERS = '.,'" 

In OCI8Statment:
__construct line:108Resource id #496
execute line:248Resource id #496

function   prepare in OCI8Connection  var_dump($prepareString):
string(515) "SELECT a.* FROM (SELECT t0.USER_ID AS USER_ID_1, t0.ULOGIN AS ULOGIN_2, t0.PASSWORD AS PASSWORD_3, t0.EMAIL AS EMAIL_4, t0.NAME AS NAME_5, t0.LASTNAME AS LASTNAME_6, t0.MIDDLE AS MIDDLE_7, t0.POSITION AS POSITION_8, t0.BLOCK AS BLOCK_9, t0.REGISTERDATE AS REGISTERDATE_10, t0.LASTVISITDATE AS LASTVISITDATE_11, t0.PARAMS AS PARAMS_12, t0.LANG AS LANG_13, t0.STRONG_PASSWORD AS STRONG_PASSWORD_14, t0.UTYPE AS UTYPE_15, t0.AUTH_PROVIDER AS AUTH_PROVIDER_16 FROM AUTH_USERS t0 WHERE t0.ULOGIN = ?) a WHERE ROWNUM <= 1" 

In OCI8Statment:
__construct line:108Resource id #498
execute line:248Resource id #498

fetch line:294Resource id #498
fetch line:294Resource id #498

closeCursor line:192Resource id #498
closeCursor2 line:201Resource id #498

After closeCursor2 - exception
   ```
 public function closeCursor()
    {
        echo 'closeCursor line:'.__LINE__.$this->_sth;


        // not having the result means there's nothing to close
        if (!$this->result) {
            return true;
        }


        echo 'closeCursor2 line:'.__LINE__.$this->_sth;

        // emulate it by fetching and discarding rows, similarly to what PDO does in this case
        // @link http://php.net/manual/en/pdostatement.closecursor.php
        // @link https://github.com/php/php-src/blob/php-7.0.11/ext/pdo/pdo_stmt.c#L2075
        // deliberately do not consider multiple result sets, since doctrine/dbal doesn't support them
        while (oci_fetch($this->_sth));

        $this->result = false;

        return true;
    }
```

**Comment by eisberg** [comment]
Here [in this topic](http://www.dba-oracle.com/t_ora_01002_fetch_out_of_sequence.htm) intelligent man writes:


ORA-01002 can have multiple causes including:
Cause: This error means that a fetch has been attempted from a cursor which is no longer valid. Note that a PL/SQL cursor loop implicitly does fetches, and thus may also cause this error. There are a number of possible causes for this error, including: 

1. Fetching from a cursor after the last row has been retrieved and the ORA-1403 error returned.
2.  If the cursor has been opened with the FOR UPDATE clause, fetching after a COMMIT has been issued will return the error.
3. Rebinding any placeholders in the SQL statement, then issuing a fetch before re-executing the statement.

### Action: 

You may want to try using cursor attributes to dodge ORA-01002 in the future. To resolve a current ORA-01002, there are three actions you can perform:

1. After the last record is received, do not issue a fetch
2. Inside a fetch loop on a SELECT FOR UPDATE, do not use a COMMIT
3. Try fetching again after re-executing the statement (after rebinding)

**Comment by morozov** [comment]
@eisberg the first two do not seem to be applicable here. The 1st requires ORA-1403 to happen which in turn is only applicable to the statements written in PL/SQL. The 2nd is applicable to `FOR UPDATE` which is not the case.

#_3 happens in the case of rebinding variables after execution which also doesn't look applicable.

Could you try narrowing down the reproduction steps for your scenario when you see the error? Ideally, it could be a standalone PHP script like [this](https://github.com/doctrine/dbal/issues/2637#issuecomment-277998244) which would only `require 'vendor/autoload.php'`, optionally create the table and other relevant DB objects and then call the DBAL methods in the required order.

**Comment by eisberg** [comment]
This code reproduce error:
```
//        $conn->prepare("CREATE TABLE TEST_A2 (A CLOB)")->execute(); // 	Сauser - CLOB!!!!
//        $conn->insert('TEST_A2', array('A' => 'test string'));
//        $conn->insert('TEST_A2', array('A' => 'test string2'));

        $sql =  "SELECT * from test_a2";
        $s2 = $conn->prepare($sql);
         $s2->execute();
        while ($res = $s2->fetch())
        {
               var_dump( $res );
        }
 
        $s2->closeCursor(); // <<< Here throw exception

```

Out this script:

oci_fetch(): ORA-01002: ������� �� ������������������
 /[....]/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php:195
 /[....]/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:197
 /[....]/MyTest.php:58
  
array(1) {
  ["A"]=>
  string(11) "test string"
}
array(1) {
  ["A"]=>
  string(12) "test string2"
}

**Comment by deeky666** [comment]
@eisberg thank you very much, I was able to reproduce the error with you test case.

Patch provided in #2645

**Comment by morozov** [comment]
Thank you @deeky666 for taking care of this.

**Comment by bertrandgauthier** [comment]
Weird... LOB may not be the only cause of the problem.

Given that...
```SQL
--drop table test;
CREATE TABLE test (
  code varchar2(50),
  str varchar2(50)
);
--truncate table test;
BEGIN
  FOR i in 1..99 LOOP
    INSERT INTO test(code, str) VALUES (i, i);
  END LOOP;
END;
/
commit;
```

And that...
```PHP
$sql = "SELECT * FROM test";
$stmt = $conn->query($sql);
$stmt->setFetchMode(PDO::FETCH_ASSOC);
while ($row = $stmt->fetch()) {
    var_dump($row);
}
$stmt->closeCursor();
```

I managed to reproduce the warning if i put `1..100` instead of `1..99` !!
Hard to believe!

**Comment by Ocramius** [comment]
@bertrandgauthier I was going to make a release with this patched. Can you please try latest `2.5` branch and see if the warning arises also there?

**Comment by bertrandgauthier** [comment]
@Ocramius With latest `2.5` branch, no more warning !

**Comment by Ocramius** [comment]
@bertrandgauthier thanks! Preparing a release then :-)

**Comment by bertrandgauthier** [comment]
Thanks to you, guys!
