### ISSUE TITLE
SQL Anywhere driver PHP7 compatibility

### ISSUE THREAD

**Issue by deeky666** [doctrine/dbal#2652]
Because of bumping the PHP requirements for DBAL 2.6 to PHP7+, our SQL Anywhere support is currently broken because SAP did not port their `sqlanywhere` to PHP7 (yet) and there currently is no statement about whether they are planning to do so.
We need to figure out how to deal with this situation. Please blame SAP at: https://archive.sap.com/documents/docs/DOC-40537

**Comment by heiglandreas** [comment]
The sourcecode is available @ http://d5d4ifzqzkhwt.cloudfront.net/drivers/php/sasql_php.zip …

**Comment by deeky666** [comment]
@heiglandreas this is not compatible with PHP7 unfortunately. Is the driver still maintained by SAP? The latest version of the driver is compatible with PHP 5.6 which is already EOL!

**Comment by heiglandreas** [comment]
PHP 5.6 is not EOL! There's no active support anymore, but EOL for PHP 5.6 starts 1st January 2019! http://php.net/supported-versions.php

And I didn't mean that the source is OOTB compilable with PHP 7.x. But the basic info is available to adapt and then make it run on PHP 7.x (If no support by SAP is available and one definitely needs it.)

**Comment by Ocramius** [comment]
@heiglandreas yep, but we're not doing that (conversion), and next stable is gonna require PHP 7, so either an upgrade is coming soon, or we have to drop support ;-)

**Comment by heiglandreas** [comment]
Set SAP a date until they should react. No reaction => drop official support.

For those that want to roll their own dice: put relevant Doctrine files in separate repo so they can fetch and adapt them on a best effort base.

**Comment by Ocramius** [comment]
We're not dropping any files, just not testing any SAP support anymore (which is ~= no support)

**Comment by efarrar** [comment]
I am sorry for the frustration for the current lack of support for PHP7. The migration of the driver to PHP7 has involved significantly more work than previous upgrades due to internal changes to PHP's data structures. This upgrade is being actively worked on right now.

The link in the opening post to the PHP downloads is the old, archived link from the SAP Developer Network. We are not able to update that content any more, so new files are being posted in the SQL Anywhere Wiki on the SAP Community Network (https://wiki.scn.sap.com/wiki/display/SQLANY/The+SAP+SQL+Anywhere+PHP+Module)

I will update this thread once the new module is posted.

**Comment by deeky666** [comment]
@efarrar thank you very much for this statement. I am glad to hear, that this has not been forgotten. This information is enough for us at the moment, we will simply stall testing on SQL Anywhere until the PHP7 driver version is ready. Maybe you should put a note on the wiki, that you are working on it because I have seen several comments in the old article asking about PHP7 support. That might help keeping users informed. Anyways, thanks again!

**Comment by efarrar** [comment]
The PHP 7.0 and PHP 7.1 libraries are now available for SQL Anywhere (https://wiki.scn.sap.com/wiki/display/SQLANY/The+SAP+SQL+Anywhere+PHP+Module)

**Comment by cfreear** [comment]
@efarrar you saint, been waiting a long time for this!

**Comment by andipohl** [comment]
@efarrar: great to see the sasql driver. But the source code seems to be the old one? Please upload the current one. thank you

**Comment by blabtonic** [comment]
@efarrar thanks so much for the updated version

**Comment by andipohl** [comment]
@efarrar May you please compile the SQL Anywhere-module for PHP 7.2?
Are the sources somewhere available to compile it myself?
Thank you

**Comment by andipohl** [comment]
Thanks to @efarrar: He uploaded the current sourcecode to [SAP-Wiki](https://wiki.scn.sap.com/wiki/display/SQLANY/The+SAP+SQL+Anywhere+PHP+Module)

**Comment by Ocramius** [comment]
How are the sources being developed? Isn't there a repo for contributions
to be suggested by the community?

**Comment by efarrar** [comment]
Currently the sources are being developed internally to the SQL Anywhere team (SAP). However, we now provide most of our other dynamic language drivers (Python, Ruby, etc) on our github pages (https://github.com/sqlanywhere). I think we should do the same for the SQL Anywhere PHP driver and will take this as an action item.

**Comment by cfreear** [comment]
Thanks for the update @efarrar, any chance of an official PHP 7.2 binary release?

**Comment by Majkl578** [comment]
> I think we should do the same for the SQL Anywhere PHP driver and will take this as an action item.

That would be great, less proprietary binaries is always better especially in Linux land. 👍 
We can then try to resurrect #852 somehow to have a Travis stage for SASQL and see if there is any better way how to handle the developer key (maybe something changed during the 2 years since that PR).

**Comment by Majkl578** [comment]
SAP Wiki still doesn't provide binaries for PHP 7.2 at the end of April 2018 (5 months after PHP 7.2.0 release).
Since DBAL 3.0 will be PHP 7.2+ only, this would mean there is no compatible combination of SQL Anywhere driver and DBAL.

**Comment by morozov** [comment]
There's extension [source code](https://s3.amazonaws.com/sqlanywhere/drivers/php/sasql_php.zip) available at the [SAP Wiki](https://wiki.scn.sap.com/wiki/display/SQLANY/The+SAP+SQL+Anywhere+PHP+Module).

I was able to build it against PHP 7.2 without any issues. Not that I'm advocating for keeping it supported, just the fact.

**Comment by deeky666** [comment]
@efarrar the PHP driver sources are incompatible with PHP 7.3 it seems. Do you plan to add support for it and if so is there any ETA? Thank you.

**Comment by cfreear** [comment]
We are experiencing issues building the module for PHP 7.3 too but managed fine for 7.2

@efarrar are you the guy to talk to regarding this or has someone else taken over the PHP module project?

**Comment by cfreear** [comment]
Update:

I've had a reply from a staff member at the sqlany_interfaces@sap.com address found [here](https://github.com/sqlanywhere) informing me that they are working on a PHP 7.3 compatible version of the extension but they can't give an ETA on it's availability.

**Comment by efarrar** [comment]
The PHP driver has been updated, and new binaries have been created. You can find the source and binaries here: https://wiki.scn.sap.com/wiki/display/SQLANY/The+SAP+SQL+Anywhere+PHP+Module

Sorry for the delay in getting these uploaded.

**Comment by efarrar** [comment]
I have had to temporarily pull the Linux 7.2 and Linux 7.3 binaries as they had not yet been fully verified by QA. I hope to enable them again soon. 

The Windows binaries and the updated source are still available.

Sorry for any inconvenience.

**Comment by efarrar** [comment]
All of the Linux drivers are now available: https://wiki.scn.sap.com/wiki/display/SQLANY/The+SAP+SQL+Anywhere+PHP+Module

**Comment by rgfpy** [comment]
Thanks @efarrar
