### ISSUE TITLE
Sqlsrv does not properly rebind values

### ISSUE THREAD

**Issue by fischerman** [doctrine/dbal#2656]
If the same statement is used with different parameters, the sqlsrv driver always inserts the first set of values. An attempt to bind a new value using `bindValue()` has no effect.

```php
$em->getConnection()->beginTransaction();
$stmt = $em->getConnection()->prepare('INSERT INTO ... VALUES (?)');

$first = 'first';
$stmt->bindValue(1, $first, 'string');
$stmt->execute();

$second= 'second';
$stmt->bindValue(1, $second, 'string');
$stmt->execute();

$stmt->closeCursor();
$em->getConnection()->commit();
```
After the transaction completes, it contains two times `first` but no `second`. This also affects the ORM, if two entities of the same type are inserted.

Tested with 
- PHP 7.1.1, sqlsrv ext 4.1.4, DBAL 2.5.11
- PHP 7.0, SQLSRV40, DBAL 2.5.11

**Comment by Ocramius** [comment]
@fischerman did you try with DBAL 2.5.12? See https://github.com/doctrine/dbal/pull/2646

**Comment by fischerman** [comment]
Works. Thanks!
