### ISSUE TITLE
Detect basic PDO types based on parameter values

### ISSUE THREAD

**Issue by lemon-juice** [doctrine/dbal#2661]
I'd like to suggest an improvement to DBAL's methods, like fetchAll(), that accept $params and $types arguments. When $types is not provided then DBAL assumes PDO::PARAM_STR, which is not always the best guess, although in the majority of cases it works. In order for the params to be passed correctly we need to provide the $types argument - while it works I think it would be more convenient if DBAL inferred the types automatically from PHP types instead of assuming PDO::PARAM_STR.

Actually, I've been using this solution for more than a year now via a connection wrapper class (with Postgres but I think this would work equally well for other databases) and I have found no issues. I'm actually surprised this is not a built-in feature in DBAL.

To illustrate what I mean let me show a portion of my wrapper class with fetchAll() method that overrides DBAL's native one and a simple method for inferring the types from param values:

```
class MyConnection extends \Doctrine\DBAL\Connection {
    
    public function fetchAll($sql, array $params = array(), $types = array()) {
        if ($params && !$types) {
            $types = $this->getTypesFromValues($params);
        }
        return parent::fetchAll($sql, $params, $types);
    }
    
    /**
     * Infer database types based on PHP types of given values.
     * 
     * @param array $values
     * @return array Types
     */
    protected function getTypesFromValues(array $values) {
        $types = [];
        
        foreach ($values as $key => $v) {
            if (is_int($v)) {
                $types[$key] = \PDO::PARAM_INT;
                
            } elseif (is_bool($v)) {
                $types[$key] = \PDO::PARAM_BOOL;
                
            } else {
                $types[$key] = \PDO::PARAM_STR;
            }
        }
        
        return $types;
    }
}
```
This allows me to use fetchAll() like this:

```
$rows = $connection->fetchAll("SELECT * FROM mytable
    WHERE id=?
     AND country=?
     AND suspended=?",
    [1, 'Greece', false]);
```
and I don't have to provide the third argument with $types, which is very convenient. There are certain cases (like the above) where passing everything as string will cause problems. Of course, the $types argument can still be supplied for more specific cases but this covers most, if not all, cases where we don't use any custom types apart from the standard PDO::PARAM_ ones. And I'm proposing to implement this only for the standard PDO::PARAM_ types since this appears to be an easy implementation.

These are the methods that would be affected by this change:

executeCacheQuery
executeQuery
executeUpdate
fetchAll
fetchArray
fetchAssoc
fetchColumn
insert
update

I don't see this would cause any backward compatibility issues - this can only improve current code, I don't see any detrimental effects. It would be great to have this feature built-in. What do you think?

**Comment by morozov** [comment]
It doesn't look like a valid addition. On the contrary, it will help input take over control of the application behavior.
