### ISSUE TITLE
Driver is a wrong term - Provider must be used instead

### ISSUE THREAD

**Issue by Yousha** [doctrine/dbal#2672]
DBAL wiki: https://en.wikipedia.org/wiki/Database_abstraction_layer
> A **database abstraction layer** is an application programming interface which unifies the communication between a **computer application and databases** such as SQL Server, DB2, MySQL, PostgreSQL, Oracle or SQLite. 

Actually, **driver** is a piece of software(**binary**) installed on a system, and lets other applications [directly] communicate with a hardware/destination(like Keyboard or DBMS). 
So it's **NOT** a text-based component or library...

While **provider** is a library, which is used to communicate with **data sources** like MySQL, Oracle, XML etc...

So in this case, I think the term **Driver** should be changed to **Provider**:
https://github.com/doctrine/dbal/tree/master/lib/Doctrine/DBAL/Driver

**Comment by Ocramius** [comment]
Closing as `invalid`.

A Driver is a piece of glue that helps your OS talk to a vendor device.
Same here, a Driver helps our connection talk to underlying vendor databases.

In addition to that, even if the naming could be improved, this has already become part of the ubiquitous language of DB abstraction layers.

**Comment by deeky666** [comment]
Also the term driver is widely used for the native PHP extensions, even officially. DBAL's driver component in fact is just a wrapper around the native PHP extensions. So it would make it harder for users to make a connection between those two things.
