### ISSUE TITLE
Optimize Oracle SchemaManager

### ISSUE THREAD

**Issue by mathieubouchard** [doctrine/dbal#2676]
On my system, building the list of tables on a schema with 61 tables result on a timeout after 480 seconds on an Oracle 12c database. The problem is that each call to get the list of foreign keys or indexes result in requests that take several seconds each.

The problem lies with requests on tables user_constraints and/or all_constraints. As an example, getting the list of foreign keys on a database that has no foreign key takes 5 seconds for each call (305 seconds total only for that part).

**Comment by mathieubouchard** [comment]
This patch optimize the creation of a Schema from an Oracle database by overriding the OracleSchemaManager->listTables method to get the list of columns, foreign keys and indexes one time for all the tables in the current database. That information is then used to create the table schemas.

After the patch, the schema of the database is detected in 5 seconds instead of more than 8 minutes.

It has been tested on Doctrine DBAL version 2.5.5-DEV, as shipped with TYPO3 8.6.0.

[Doctrine-optimize-OracleSchemaManager.txt](https://github.com/doctrine/dbal/files/840225/Doctrine-optimize-OracleSchemaManager.txt)

**Comment by Ocramius** [comment]
Could you please send it as a PR, so it can be reviewed? Also, what is the
bottleneck, exactly?

**Comment by mondrake** [comment]
I am also seeing this, developing a db driver for Drupal (https://github.com/mondrake/drudbal). More than 3 minutes to introspect a schema of about 50 tables, without any FK. Will try to open a PR with @mathieubouchard patch.

**Comment by morozov** [comment]
Closing as stale. Please send the above as a PR if still relevant.

**Comment by greg0ire** [comment]
A PR has been sent, reopening.
