### ISSUE TITLE
Table has no primary key while it actually has

### ISSUE THREAD

**Issue by podorozhny** [doctrine/dbal#2680]
Hello.

I tried to reverse engineer already existing table that is not managed by doctrine and got this exception:

```
➜  test-project git:(master) ✗ bin/console doctrine:mapping:convert annotation \
    ./src/ \
    --from-database \
    --namespace="TestBundle\\Entity\\" \
    --filter="test_table_name"


  [Doctrine\ORM\Mapping\MappingException]
  Table test_table_name has no primary key. Doctrine does not support reverse engineering from tables that don't have a
  primary key.
```

But it actually has primary key. The reason why I got this stupid error is here: https://github.com/doctrine/dbal/blob/ec8fc16604915110eea8046e3ea594c133aee880/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php#L70

My table primary key name is not `PRIMARY`, but its type is.

I think it's wrong to check key name instead of [its constraint type](http://stackoverflow.com/questions/2341278/php-get-primary-key-of-table).

```
Mysql: 5.7.17
doctrine/dbal: 2.5.8
```

**Comment by Ocramius** [comment]
What is the index information at that code location? Could you dump it?

**Comment by podorozhny** [comment]
@Ocramius Could you clarify what you mean please?

**Comment by Ocramius** [comment]
At https://github.com/doctrine/dbal/blob/ec8fc16604915110eea8046e3ea594c133aee880/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php#L70, what is a dump of `$tableIndexes`?

**Comment by podorozhny** [comment]
@Ocramius http://pastebin.com/J7WdgC2E

**Comment by podorozhny** [comment]
If I rename primary key index name (`Key_name`) to `PRIMARY` - everything works.

**Comment by Ocramius** [comment]
Copying dump here for reference:
```
/application/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php:68:
array(8) {
  [0] =>
  array(12) {
    'Table' =>
    string(10) "test_table_name"
    'Non_Unique' =>
    string(1) "0"
    'Key_name' =>
    string(7) "id"
    'Seq_in_index' =>
    string(1) "1"
    'Column_Name' =>
    string(17) "id"
    'Collation' =>
    string(1) "A"
    'Cardinality' =>
    string(4) "9117"
    'Sub_Part' =>
    NULL
    'Packed' =>
    NULL
    'Null' =>
    string(0) ""
    'Index_Type' =>
    string(5) "BTREE"
    'Comment' =>
    string(0) ""
  }
  [1] =>
  array(12) {
    'Table' =>
    string(10) "test_table_name"
    'Non_Unique' =>
    string(1) "1"
    'Key_name' =>
    string(8) "name"
    'Seq_in_index' =>
    string(1) "1"
    'Column_Name' =>
    string(8) "name"
    'Collation' =>
    string(1) "A"
    'Cardinality' =>
    string(4) "8770"
    'Sub_Part' =>
    NULL
    'Packed' =>
    NULL
    'Null' =>
    string(0) ""
    'Index_Type' =>
    string(5) "BTREE"
    'Comment' =>
    string(0) ""
  }

    }

```

**Comment by Ocramius** [comment]
Seems like the information above is not sufficient to determine whether a column is a PK or not. Would need a bigger scope (not so easy to fix)

**Comment by podorozhny** [comment]
I think its obvious: schema manager improperly checks name of the index instead of its constraint type. [This logic](https://github.com/doctrine/dbal/blob/ec8fc16604915110eea8046e3ea594c133aee880/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php#L70) and [this query](https://github.com/doctrine/dbal/blob/ec8fc16604915110eea8046e3ea594c133aee880/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L165) is wrong.

**Comment by Ocramius** [comment]
@podorozhny thanks for looking it up. Indeed, patching the query would be sufficient.

**Comment by lcobucci** [comment]
@podorozhny could you also paste here the result of that query? I think that would help us to solve it as well.

**Comment by lcobucci** [comment]
@podorozhny I'm running the same MySQL version (5.7.17) here and I've created a random table and `Key_name` ALWAYS returns "PRIMARY" for the PK.

Could you please send us the output of "SHOW CREATE TABLE test_table_name"?

**Comment by lcobucci** [comment]
What I think you have is an `UNIQUE INDEX id (id)` instead of `PRIMARY KEY (id)` but I might be wrong.

**Comment by podorozhny** [comment]
> What I think you have is an UNIQUE INDEX id (id) instead of PRIMARY KEY (id) but I might be wrong.

For fuck sake! You are totally right. I missed something during debugging this place. I had unique key instead or primary.

**Comment by podorozhny** [comment]
I think we can close it due to this mysql feature:
> Key_name ALWAYS returns "PRIMARY" for the PK

**Comment by Ocramius** [comment]
@podorozhny so, to clarify and set this clear: your table currently doesn't have a PK?

**Comment by podorozhny** [comment]
@Ocramius yep, shame on me :)

**Comment by Ocramius** [comment]
Happens. Closing as `invalid`
