### ISSUE TITLE
Unknown Access violation error

### ISSUE THREAD

**Issue by JefferyHus** [doctrine/dbal#2682]
Hi, I have been using DBAL for 2 months now and everything was good and fine untill today when I have tried to insert a value in one of my tables `Customer`, the issue is that I recieve an Access Violation exception even if none of the columns are reserved keywords.
I use Mysql 5.7, PHP 7.0.10 and the lates `doctrine\dbal` library.

```mysql
An exception occurred while executing 'INSERT INTO customer (?, ?, ?, ?, ?, ?) VALUES(ddddd, gbp, ddddd, ddddd, 15a0f34d-eb5c-477b-81b6-428cea294e21, ddd)' with params [":id", ":currency", ":description", ":email", ":package", ":sources"]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '':id', ':currency', ':description', ':email', ':package', ':sources') VALUES(ddd' at line 1
```

**Comment by Ocramius** [comment]
That query looks wrong. The first part of the `INSERT` should be the column names, the second the parameters. You don't seem to have the column names there, but rather the parameters.

**Comment by JefferyHus** [comment]
@Ocramius because I am using SQL BUILDER with '->setParameters(array)'

**Comment by JefferyHus** [comment]
```php
// list of data to insert
$customerValues = array(
	":id"          => $response["id"],
	":currency"    => $response["currency"] ?: "gbp",
	":description" => $response["description"],
	":email" 	   => $response["email"],
	":package"     => "15a0f34d-eb5c-477b-81b6-428cea294e21",
	":sources"     => serialize($response["sources"])
);

$customerParams = array(
	"id"          => ":id",
	"currency"    => ":currency",
	"description" => ":description",
	"email"       => ":email",
	"package"     => ":package",
	"sources"     => ":sources"
);
DB::build()->insert('customer')->values( $customerValues )->setParameters( $customerParams )->execute();
```
this is my code

**Comment by Ocramius** [comment]
Closing as `invalid`.

See the example at https://github.com/doctrine/dbal/blob/e0169b2afc0fcbe047484b852699b095aee12b4f/lib/Doctrine/DBAL/Query/QueryBuilder.php#L930-L952 - your `$customerValues` should be an array of placeholders, with keys being column names.

**Comment by JefferyHus** [comment]
The code above is what I have been using in ALL my queries with DBAL. So I believe the issue may be related to something else and not my params

**Comment by Ocramius** [comment]
Even at first glance, the code above is wrong and doesn't respect the API signature. If this is a regression, then a test is needed first.

**Comment by JefferyHus** [comment]
```php
		$customerValues = array(
			"id"          => $response["id"],
			"currency"    => $response["currency"] ?: "gbp",
			"description" => $response["description"],
			"email" 	   => $response["email"],
			"package"     => "15a0f34d-eb5c-477b-81b6-428cea294e21",
			"sources"     => serialize($response["sources"])
		);
               DB::build()->insert('customer')->values( $customerValues )->execute();
```
I have changed the code to this and still getting the same error but when I take the SQL string generated by `->getSQL()` and execute directly it works just fine.

**Comment by JefferyHus** [comment]
```php
// list of data to insert
$customerValues = array(
	":id"          => $response["id"],
	":currency"    => $response["currency"] ?: "gbp",
	":description" => $response["description"],
	":email" 	   => $response["email"],
	":package"     => "15a0f34d-eb5c-477b-81b6-428cea294e21",
	":sources"     => serialize($response["sources"])
);

$customerParams = array(
	"id"          => ":id",
	"currency"    => ":currency",
	"description" => ":description",
	"email"       => ":email",
	"package"     => ":package",
	"sources"     => ":sources"
);
DB::build()->insert('customer')->values($customerParams)->setParameters($customerValues)->execute();
```
The issue is solved I was messing things, just switched `$customerValues` with `customerParams` and things works just fine again, sorry
