### ISSUE TITLE
PDOSqlsrv Connection not compatible with PHP 5.3 - 5.4

### ISSUE THREAD

**Issue by nirix** [doctrine/dbal#2683]
The DBAL versions 2.5.11 and 2.5.12 can be installed with PHP 5.3 and 5.4, however the PDOSqlsrv [Connection](https://github.com/doctrine/dbal/blob/v2.5.11/lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php#L37) class uses [`::class` to resolve a class name](http://php.net/manual/en/language.oop5.basic.php#language.oop5.basic.class.class) which is only available to PHP >=5.5

We've had to fix our DBAL package version to [2.5.10](https://github.com/doctrine/dbal/blob/v2.5.10/lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php) until we're ready to move off PHP 5.4.

**Comment by Ocramius** [comment]
Hi Jack,

Can you simply send a PR against master so we can merge/release a
compatible version?

**Comment by IMSoP** [comment]
I believe master is now the 3.x release, so doesn't support old PHPs anyway. I have raised a PR against 2.5 here: https://github.com/doctrine/dbal/pull/3073

Will it also need applying to 2.6?

**Comment by Ocramius** [comment]
Closing here: we no longer support PHP 5.3 and PHP 5.4.

**Comment by IMSoP** [comment]
@Ocramius Can you clarify regarding support?

Reading more carefully, I see that 2.6, not 3.0, is the first release to require PHP 7.1, so this fix is definitely not needed there.

However, is the 2.5 branch completely unsupported, or should bugs be raised differently, or do new minimum PHP requirements apply?

**Comment by Ocramius** [comment]
@IMSoP https://github.com/doctrine/dbal/pull/3073 will likely be merged and fixed, since the screw-up is on our side, but otherwise `2.5.x` will only receive security fixes.

**Comment by IMSoP** [comment]
OK, that makes sense.

**Comment by Majkl578** [comment]
> I believe master is now the 3.x release

Not just yet.

Master represents upcoming 2.7 and requires PHP 7.1.
Develop is currently upcoming 3.0 and requires PHP 7.2, will be merged into master once 2.7 is released.

**Comment by IMSoP** [comment]
@Majkl578 Yeah, I misread something when I was flicking through branches.
