### ISSUE TITLE
Add Ability to Prepend SQL Statements in SchemaCreate* Listeners 

### ISSUE THREAD

**Issue by pharasyte** [doctrine/dbal#2687]
It might be useful to have a prependSql method exposed on some of the EventArgs classes. Specifically, the SchemaCreateTableEventArgs and/or SchemaCreateTableColumnEventArgs should be able to inject SQL that will be run before the table itself is created.

One particular use case for this is supporting ENUM types for PostgreSQL. In my case, I used the method described at "http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/mysql-enums.html" to implement MySQL ENUMs. Extending that to support PostgreSQL involved creating an onSchemaCreateTable listener as shown below.

The lock variable and the recursive call to getCreateTableSQL kind of bother me, and the ability to prepend SQL would avoid that.

Of course, I could be doing it all wrong. If not, and others think this might be useful, I'd be happy to do a PR.

```
class PostgreSQLEnumListener implements EventSubscriber
{
	/**
	 * Meant to Allow us to Call PostgreSqlPlatform::getCreateTableSQL
	 * recursively.
	 * 
	 * @var boolean
	 */
	private $lock = false;
	
	/**
	 * {@inheritDoc}
	 * @see \Doctrine\Common\EventSubscriber::getSubscribedEvents()
	 */
	public function getSubscribedEvents()
	{
		return array(
			'onSchemaCreateTable'	
		);
	}
	
	/**
	 * @param SchemaCreateTableEventArgs $event
	 */
	public function onSchemaCreateTable(SchemaCreateTableEventArgs $event)
	{
		$platform = $event->getPlatform();
		
		/** Either we've gone recursive or we're not using PostgreSQL */
		if ($this->lock || !($platform instanceof PostgreSqlPlatform))
		{
			return;
		}
		
		$sql = array();
		
		foreach ($event->getTable()->getColumns() as $column)
		{
			$type = $column->getType();
			
			if (!($type instanceof EnumType)) 
			{ 
				continue; 
			}
			
			$name   = $type->getName();
			$values = array_map(function ($val) { return "'" . $val . "'"; }, $type->getValues());
			
			$sql[] = "CREATE TYPE {$name} AS ENUM (" . implode(", ", $values) . ")";
		}
		
		/**
		 * Big Hack. Have the Platform generate the table SQL for us, but recursively.
		 */
		if (sizeof($sql) > 0)
		{
			$event->addSql($sql);
			
			$event->preventDefault();
			
			$this->lock = true;
			$event->addSql($event->getPlatform()->getCreateTableSQL($event->getTable()));
			$this->lock = false;
		}
	}
}
```

**Comment by Ocramius** [comment]
To me, this seems like a huge complication for adding something platform-specific that should probably live inside a DB migration instead...

**Comment by morozov** [comment]
Listeners is a horrible API for this type of extension. I don't believe we will accept any improvements based on it.
