### ISSUE TITLE
JsonType missing from releases

### ISSUE THREAD

**Issue by brettmc** [doctrine/dbal#2689]
I thought I was going crazy, because I can see JsonType in the `master` branch, but if you look at the releases for DBAL, it's not there, eg:
https://github.com/doctrine/dbal/tree/v2.5.12/lib/Doctrine/DBAL/Types

I've had a look at a few other tagged releases in the 2.5.x and 2.4.x lines, also can't see it in any.
It looks like DateIntervalType is also missing from releases.

**Comment by brettmc** [comment]
...the files also look to be missing from the 2.5 branch itself:
https://github.com/doctrine/dbal/tree/2.5/lib/Doctrine/DBAL/Types

**Comment by lcobucci** [comment]
@brettmc new features are available on minor releases not patches, for more info take a look on http://semver.org. 

Closing as invalid for that reason.

**Comment by brettmc** [comment]
@lcobucci thanks, I understand. I've misunderstood the documentation.
Since the documentation talks about using json in preference to json_array (http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#json-array) I assumed that it would be in the latest released version. I'll watch out for v2.6 to be released :)
