### ISSUE TITLE
MasterSlaveConnection: Allow changing transaction isolation level on slave

### ISSUE THREAD

**Issue by jnvsor** [doctrine/dbal#2693]
It would be nice to be able to change the transaction isolation level without automatically connecting to master. `connectTo` should automatically set the transaction isolation level after changing connection to prevent unexpected issues due to this.

**Comment by Ocramius** [comment]
That's already feasible via events?

**Comment by jnvsor** [comment]
`setTransactionIsolation` calls `executeUpdate` which in the case of `MasterSlaveConnection` forces a connection to master. As far as I know the only way around this is to run the transaction isolation query from pdo directly with `getWrappedConnection` or run the transaction isolation query through `executeQuery`, neither of which are very nice.

`connectTo` automatically setting the isolevel when changing connection is just an afterthought to stop bugs when someone sets the iso level on the slave and then wonders why it's not working after switching to master

**Comment by morozov** [comment]
The primary/replica connection feature hasn't received any maintenance in the past years. This feature is unlikely to be implemented.
