### ISSUE TITLE
PostgreSQL\Connection\Params\ How we set Default Search Path for custom-schema namespace?

### ISSUE THREAD

**Issue by vafrcor** [doctrine/dbal#2697]
If we use `PostgreSQL database`, `Doctrine\DBAL:2.5.x` already set to use default `public` namespace (see https://github.com/doctrine/dbal/pull/2490) .

How we can set `custom-schema` from configuration code without modify `Doctrine\DBAL\DriverManager` for `$_driverMap` property?
There is sample gist used for custom driver (https://gist.github.com/jkuchar/13c640fb2ac071da14f4)

**Comment by Ocramius** [comment]
This wouldn't be done via configuration, but probably via a post-connect listener.
