### ISSUE TITLE
[Question] PostgreSQL's pgcrypto uuid generator

### ISSUE THREAD

**Issue by Simperfit** [doctrine/dbal#2706]
The postgreSQL Driver does not support [pgcrypto](https://www.postgresql.org/docs/9.6/static/pgcrypto.html)'s function to generate uuid (`gen_random_uuid() returns uuid`, it does support uuid-ossp but it is currently unavailable in some provider like Google Cloud SQL (postgres).

Should dbal supports pgcrypto too ? 

I'm willing to help contributing to this if it's the case

**Comment by Ocramius** [comment]
> Should dbal supports pgcrypto too ?

Depends on whether it's provided OOTB, and if so, which version implemented it

**Comment by Simperfit** [comment]
@Ocramius It is, just like uuid-ossp, I think it exist since a long time ago (maybe pgsql  8.2)

**Comment by Ocramius** [comment]
@Simperfit so I suppose you just want to change https://github.com/doctrine/dbal/blob/fbed76eb8395d9a8c159cfaeceb775dfc6be7d9f/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L999 ?

**Comment by Simperfit** [comment]
@Ocramius I think we should add a new platform and detect if it's either one or either the other in order to not do a BC Break with existing apps that use uuid-ossp.

WDYT ?

**Comment by Ocramius** [comment]
@Simperfit if we're moving to something that is more widely supported, and the output is the same, then it's fine to just change it as-is

**Comment by morozov** [comment]
The UUID functionality is deprecated in DBAL by https://github.com/doctrine/dbal/pull/3212.
