### ISSUE TITLE
ETA for DBAL 2.6

### ISSUE THREAD

**Issue by stof** [doctrine/dbal#2712]
The master branch of DBAL contains a bunch of unreleased features, including the new JsonType merged nearly 1 year ago.
What is the ETA for release DBAL 2.6.0 ?

**Comment by Ocramius** [comment]
I think it's mostly https://github.com/doctrine/dbal/pulls?q=is%3Aopen+is%3Apr+milestone%3A2.6

Important bits are MySQL 5.7 support (because MySQL has awesome BC policies, sigh), which wasn't yet evaluated, and things that are marked as "feature/improvement". Fixes can be applied also later, but I think these will be the last "features" for the 2.x branch.

**Comment by deeky666** [comment]
:+1: I will try to work through these open issues in the next few days if I find time.

**Comment by Tobion** [comment]
I'd say it's important to reconsider the JSON type naming before releasing 2.6. See #2723

**Comment by RinkAttendant6** [comment]
2.6 doesn't seem to be backwards-compatible with 2.5 considering that the minimum requirement is PHP 7 so perhaps a major release (3.0.0) is more appropriate according to semver?

Is there going to be a migration guide for 2.5.x to the new release, or are the changes not significant enough for that to be considered?

I am in the middle of migrating an application from PHP 5.3 to PHP 7.0 so compatibility will be a very useful thing to know.

**Comment by Ocramius** [comment]
> 2.6 doesn't seem to be backwards-compatible with 2.5 considering that the minimum requirement is PHP 7 so perhaps a major release (3.0.0) is more appropriate according to semver?

@RinkAttendant6 bumping dependency requirements does not count as a BC break, and that is even [specified in semver](https://github.com/mojombo/semver/blob/df7bd79bda7d7fe6da20d0724fe0111678cbaa8f/semver.md#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api) (https://github.com/mojombo/semver/issues/148)

 > Is there going to be a migration guide for 2.5.x to the new release, or are the changes not significant enough for that to be considered?

See [UPGRADE.md](https://github.com/doctrine/dbal/blob/9d696ac2ff9391c0dc5328170667248de10e0606/UPGRADE.md#upgrade-to-26)

 > I am in the middle of migrating an application from PHP 5.3 to PHP 7.0 so compatibility will be a very useful thing to know.

You'll need 7.1 ;-)

**Comment by RinkAttendant6** [comment]
> You'll need 7.1 ;-)

According to https://github.com/doctrine/dbal/blob/master/composer.json#L15, it still says 7.0 but I assume this will be bumped to 7.1 upon release?

In that case I guess I'll have to stick with 2.5.x, can you tell me if there's any issues with using 2.5.x on PHP 7.0?

**Comment by Ocramius** [comment]
None at all

**Comment by schodemeiss** [comment]
Any idea how far away we are from a 2.6? I'm in need of some of the goodness merged in a while back?

**Comment by Tobion** [comment]
DBAL 2.6 is released so this issue can be closed. @Ocramius please merge https://github.com/doctrine/doctrine2/pull/6580 and make a patch release so we can actually use DBAL 2.6

**Comment by Ocramius** [comment]
Release of ORM 2.6 is probably happening next week anyway.
