### ISSUE TITLE
Unclear exception message

### ISSUE THREAD

**Issue by aaleksu** [doctrine/dbal#2713]
Guys, there is unclear exception message in AbstractPlatform: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L429

It doesn't say which table contains unsupported (or possible unsupported) type.
It just says: "Unknown database type ".$dbType." requested, " . get_class($this) . " may not support it."
Would be great to have more details.
What about passing table name to check-columns methods?

**Comment by Ocramius** [comment]
@aaleksu want to send a patch? :-)

**Comment by aaleksu** [comment]
I'd like to but I am not sure about solution.
I don't think it's a good idea to pass table name to the method where this exception is being thrown - because then it will be necessary to change every *SchemaManager implementation. (But this solution is much easier and more stupid.)

Probably the better way is not to throw an exception there but return null and to check type mapping in AbstractSchemaManager when all the info about tables is parsed and collected. There might be, for example, special method to validate tables' schemas.

I think the table name which cases the exception might be found exception stack. But anyway it'd be better to make the message more clear.

**Comment by morozov** [comment]
Closing as stale.
