### ISSUE TITLE
destructor and oci_close ?

### ISSUE THREAD

**Issue by mhetru** [doctrine/dbal#2728]
Hello,

I have asked myself why the https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/OCI8/OCI8Connection.php class has not a destructor with the function oci_close ?

Can you explain me?

Thanks!

Mathieu

**Comment by Ocramius** [comment]
@mhetru most likely a bug, and it should be handled.

Related: https://github.com/doctrine/dbal/pull/2708

**Comment by mhetru** [comment]
hello, is it possible to do this?

**Comment by morozov** [comment]
This is likely unnecessary.
