### ISSUE TITLE
mysqli missing driver options

### ISSUE THREAD

**Issue by leadboots5** [doctrine/dbal#2735]
According to the documentation(http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html) the mysqli driver will allow any of the real_connect options(http://php.net/manual/en/mysqli.real-connect.php). However if you specify MYSQLI_CLIENT_SSL it doesn't get passed to the real connect call(https://github.com/doctrine/dbal/blob/476c2f9746f964dbb7b645b6c941936aa71a8d7a/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php#L71) it would appear. If I var_dump $flags right before it is called then I get NULL.

If by chance I'm doing something wrong my my driverOptions please let me know. I've tried driver options with and quotes. I've also tried giving it a value of T or TRUE, but DBAL says that is an unsupported option

`$connectionParams = [
    'driver' => 'mysqli',
    'host' => 'remotehostname',
    'dbname' => 'targetdb',
    'user' => 'username',
    'password' => 'password',
    'driverOptions' => [MYSQLI_CLIENT_SSL]
];`

**Comment by antoinedeschenes** [comment]
https://github.com/doctrine/dbal/pull/2570

**Comment by Ocramius** [comment]
Closing as per @antoinedeschenes' comment: this is already in `master` (`2.6`)

**Comment by jasongill** [comment]
For anyone else who is coming across this old comment while trying to Google and figure out how you make dbal connect to MySQL with SSL without having to supply an SSL CA / cert / key, there is a logical error in the original comment which mirrors what you are probably trying - you (like me, and the original person) are following the dbal docs which aren't real clear as to how the driverOptions setting works, and are probably doing something like `'driverOptions' => [ MYSQLI_CLIENT_SSL ]` which isn't working.

The real solution (at least for dbal 3.0) is to do:
```
\Doctrine\DBAL\DriverManager::getConnection([
      'driver' => 'mysqli',
      'driverOptions' => [ 'flags' => MYSQLI_CLIENT_SSL ],
......
```

It's not readily apparent in the dbal docs (at least not as of 3.0) what format you should use for the driverOptions, and most references to mysqli SSL connections simply point to using CA / cert / key files which aren't necessary in all environments, so hopefully this comment helps someone else who's been beating their head against this for a while.

**Comment by kylehqcom** [comment]
Thank you @jasongill 🙏  - I have an app running the normal Doctrine mysql setup on AWS. But now we have an additional client wanting us to connect on there own AWS/RDS db. Getting the correct token from `use Aws\Rds\AuthTokenGenerator` was ok, but getting doctrine to play ball was a PITA. Added this driver option and success!
