### ISSUE TITLE
Slaves setup for sharding

### ISSUE THREAD

**Issue by matteomoretti** [doctrine/dbal#2737]
Hi,

at the moment (dbal 2.5.12) doesn't seem to be possible to configure slaves for a sharding configuration. With sharding the connection will use PoolingShardConnection and with slaves MasterSlaveConnection. 

Is there a way to configure slaves for each shard? 

Thanks a lot

**Comment by Ocramius** [comment]
So you'd want to have each shard connection as a `MasterSlaveConnection`?

I think one possible solution would be to deprecate the existing sharding/master-slave code, and allow passing in lazy connection instances for everything: then each connection object decides what to do.

**Comment by matteomoretti** [comment]
Yes, exactly. I would configure slaves for each shard connection. 
 
Are there any workaround to do that?

Thanks a lot for your reply and your help!

**Comment by Ocramius** [comment]
@matteomoretti not currently, no: you'd have to implement it yourself and see if it works first.

**Comment by matteomoretti** [comment]
@Ocramius thanks for your reply. If you want you can close the issue for now. If I have any updates I'll let you know.

**Comment by Ocramius** [comment]
@matteomoretti closing then.

As noted above, ideally we could just have something like:

```php
class ReadWriteSelectingConnection implements Connection
{
    public function __construct(Connection ...$selectableConnections) { ... }
}

class ShardSelectingConnection implements Connection
{
    public function __construct(Connection ...$selectableConnections) { ... }
}
```

That would remove the need for explicitly/statically coupled code between a selector class and the connection objects, as the connection objects would be "lazy" and passed in via Dependency Injection.
