### ISSUE TITLE
Add ability to change user and password to reconnect Connection

### ISSUE THREAD

**Issue by operandom** [doctrine/dbal#2744]
Hi,

Is is possible to change ~~`$_isConnected`~~ `$_params` to protected in Connection class ?

I'm on a Symfony project where each users have there own SQL user and password.
I tryed to override the Connection class and pass it to the `wrapper_class` parameter but I can't reconnect to database because I can't ~~set `$_isConnected` to false~~ change `$_params`.

Is there a architectural reason to not set `$_isConnected` protected ?

Thx

**Comment by operandom** [comment]
Arf, I missed the public `isConnected` method... -_-

**Comment by operandom** [comment]
I repoen the issue because the problem still the same as the `$_params` is private.

**Comment by Ocramius** [comment]
It will stay `private`: the class is not supposed to be extended, sorry.
