### ISSUE TITLE
Wrong param comment 

### ISSUE THREAD

**Issue by helsner** [doctrine/dbal#2745]
vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php
Line 762
The comment for the parameter is wrong in this case
$type is null or a \PDO::PARAM which is type integer

**Comment by Ocramius** [comment]
There is nothing at [line `762`](https://github.com/doctrine/dbal/blob/899c62bb579027c146b73f6b580c871eb669d310/lib/Doctrine/DBAL/Connection.php#L762)

Consider sending a patch with the changed file: you can do that directly [from the UI](https://github.com/doctrine/dbal/edit/master/lib/Doctrine/DBAL/Connection.php)

**Comment by Ocramius** [comment]
Handled in #2747
