### ISSUE TITLE
Connection ping method can trigger uncaught PDOExceptions

### ISSUE THREAD

**Issue by gregl83** [doctrine/dbal#2769]
Reading the ping method phpdoc it's not immediately clear to me if the method should allow driver exceptions to bubble up.

My expectation was that this method would always return true/false based on the success of connecting to the database and performing a dummy query.

When having a connection timeout or close it's possible to encounter PDOException instead.

**Comment by Ocramius** [comment]
@gregl83 this should be fixed rather than documented as a possible crash: a `ping` operation failing due to invalid connection information should simply return `false`

**Comment by gregl83** [comment]
@Ocramius my sentiment as well.

**Comment by morozov** [comment]
Closing per https://github.com/doctrine/dbal/pull/4128.
