### ISSUE TITLE
Call to AbstractSchemaManager->dropTable('<reserved keyword>') fails with an SQL error

### ISSUE THREAD

**Issue by ainsus** [doctrine/dbal#2779]
I am making use of [laravel-doctrine](http://www.laraveldoctrine.org/docs/1.3/migrations) integration. I (used to) have a table called 'fetch' which is a reserved keyword in MySql. Calling `php artisan doctrine:migrations:reset` (which just drops all tables in the schema one by one [using AbstractSchemaManager::dropTable](https://github.com/laravel-doctrine/migrations/blob/1.1/src/Console/ResetCommand.php#L86)) gives me this:
 
[Doctrine\DBAL\Exception\SyntaxErrorException]                                                                   
 An exception occurred while executing 'DROP TABLE fetch':                                                        
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'fetch' at line 1

The keyword should be enclosed within backticks but it is not. The reason for this is that AbstractPlatform::getDropTableSQL($table) wraps the backticks only if the argument is type Table. If it's a plain string it does not. 
If I'm not mistaken, the same kind of issue appears to be in several other functions as well.

I should also mention that the generated migration (and rollback) SQL makes use of the backticks for reserved names just fine, so `:migrate` and `:rollback` commands work just fine. The issue is with the getDropTableSQL function call if the `$table` argument is a string.

**Comment by AlessandroMinoccheri** [comment]
Doctrine doesn't quote reserved keyword automatically for table.
There is a documentation chapter on this 4.6 on this link to view how to use reserved keywords inside entity for table name

http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html

**Comment by ainsus** [comment]
Actually, it does

**Comment by Ocramius** [comment]
This cannot be fixed, since we do not know if the value passed in is already quoted or not. This is an old mistake in the design of the library: a string should never have been allowed there.
