### ISSUE TITLE
SQL Anywhere host parameter is optional

### ISSUE THREAD

**Issue by cfreear** [doctrine/dbal#2780]
Currently in [Doctrine/DBAL/Driver/SQLAnywhere/Driver.php](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/SQLAnywhere/Driver.php#L84) the host parameter is set by default to localhost:2638 which is great for servers listening on tcpip however for local development machines the ``host`` isn't needed [sap docs](http://dcx.sybase.com/index.html#sqla170/en/html/8150410e6ce21014a7e39e1c7ee1cda2.html) and because of the default values dbal actually fails to connect.

Could this parameter be made optional? Happy to submit a PR but wanted feedback first.

**Comment by Ocramius** [comment]
> the default values dbal actually fails to connect.

Could you clarify this? What are the defaults? A host name is required in order to connect somewhere, or else it must be a socket.

**Comment by cfreear** [comment]
In [Doctrine/DBAL/Driver/SQLAnywhere/Driver.php lines 84 and 85](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/SQLAnywhere/Driver.php#L84-L85) the ``HOST`` parameter in the DSN is set to ``localhost:2638`` if the ``host`` and ``port`` config items aren't set.

When running on a local machine SQL Anywhere can start listening only for shared memory connections using the [``-x none``](http://dcx.sap.com/index.html#sqla170/en/html/3bcf052b6c5f1014b9f4d7c5663fe05d.html) server option. In this mode SQL Anywhere doesn't listen on tcpip so attempting to connect via host fails, only the ``ServerName`` and ``DBN`` are needed.

**Comment by Ocramius** [comment]
Ah, I see, so the PHP and SQL Anywhere processes share some memory as I/O swap - that's interesting.

@cfreear changing the defaults is a BC break, but you can send a patch to allow using shared (local) memory

**Comment by cfreear** [comment]
To avoid BC would it be more prudent to add a ``memory`` connection parameter similar to the one in [pdo_sqlite](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/PDOSqlite/Driver.php#L82-L86)? It could default to false in which case the ``HOST=localhost:2638`` would still be prepended to the DSN and prevent BC, setting it to true would then ignore anything in ``host`` and ``port`` and skip the ``HOST=`` line. Thoughts?

**Comment by Ocramius** [comment]
Seems like a solid approach. Call it "shared_memory" or pick the
terminology from the SQLAnywhere docs

**Comment by morozov** [comment]
Closing as SQLAnywhere is no longer supported.
