### ISSUE TITLE
Postgres Json column conversion

### ISSUE THREAD

**Issue by carnage** [doctrine/dbal#2783]
When converting an existing TEXT column to JSON in postgres, the generated sql is invalid:

```
 [Doctrine\DBAL\Exception\DriverException]                                                                            
  An exception occurred while executing 'ALTER TABLE <table> ALTER <column> TYPE JSON':  
  SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "<column>" cannot be cast automatically to type json         
  HINT:  Specify a USING expression to perform the conversion.                                                         
```
Not sure how this should be fixed in the library but the correct sql would be:

`ALTER TABLE <table> ALTER <column> TYPE JSON USING to_json(<column>)`

**Comment by romaricdrigon** [comment]
I can confirm error is still there on Doctrine DBAL v2.10.1
And proposed solution works great.

**Comment by bencagri** [comment]
I also confirm this error with v2.10.2
`ALTER TABLE <table> ALTER <column> TYPE JSON USING to_json(<column>)` works great.

**Comment by ankurk91** [comment]
Still an issue with v3.3, using with Laravel and Postgresql 14

```php
 Schema::table('webhook_calls', function (Blueprint $table) {
            $table->json('payload')->change();
        });
```
```
 SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "payload" cannot be cast automatically to type json
HINT:  You might need to specify "USING payload::json". (SQL: ALTER TABLE webhook_calls ALTER payload TYPE JSON)

```

**Comment by greg0ire** [comment]
Possible next steps:
- reproducing the issue with a test case;
- finding out where a code change would occur.

**Comment by morozov** [comment]
This doesn't look like something that the DBAL should take care of. If Postgres doesn't provide a safe default for this type of conversion, it probably means that the user should make some choice.
