### ISSUE TITLE
Doctrine uses broken pipe when connection was killed

### ISSUE THREAD

**Issue by apapsch** [doctrine/dbal#2784]
doctrine/dbal v2.5.12 with PDO_mysql

When you kill a process from MySQL processlist, and the connection is still used by DBAL, Doctrine produces a PHP error. For example:

1. Start program that uses DBAL.
2. Pick and kill the process via `SHOW PROCESSLIST` and `KILL <ID>`.
3. Let the program do something via DBAL connection.

Result:

```
PHP error in /.../vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91: 8 PDOStatement::execute(): send of 278 bytes failed with errno=32 Broken pipe
```

(This message comes from a custom error handler, 8 is the PHP error level)

It would be great if this error would be thrown as exception, or shouldn't it?.

**Comment by apapsch** [comment]
I don't understand why I don't get error 2006 (MySQL server has gone away), since https://dev.mysql.com/doc/refman/5.7/en/gone-away.html tells me:

>  Some other common reasons for the MySQL server has gone away error are:
>
>    You (or the db administrator) has killed the running thread with a KILL statement or a mysqladmin kill command. 

Actually, I was trying to provoke that error, to triage an unrelated bug.

**Comment by apapsch** [comment]
I just looked in PDOStatement:91 and it seems like after call to `parent::closeCursor` errno should be checked and if it's non-zero an exception thrown. Patch like this welcome?

**Comment by Ocramius** [comment]
It is a welcome addition if approached test-first

**Comment by morozov** [comment]
Closing as stale.
