### ISSUE TITLE
PHP 7.1.7 & MariaDB 10.2.7 = Syntax error or access violation

### ISSUE THREAD

**Issue by KitsuneSolar** [doctrine/dbal#2804]
Please read this issue: https://github.com/flarum/core/issues/1211

**Comment by Ocramius** [comment]
Closing as `invalid` as per https://github.com/flarum/core/issues/1211#issuecomment-319306593

We only allow mapping string default values, and `'NULL'` is correctly interpreted in the mappings as the string `'NULL'`, not the `NULL` SQL absence value.

The correct fix is to remove the default value from the mappings overall.

Also related:

 * https://github.com/doctrine/doctrine2/issues/6383
 * https://github.com/doctrine/dbal/issues/2582
