### ISSUE TITLE
[HELP] Laravel and doctrine/dbal MySQL version not detected

### ISSUE THREAD

**Issue by MartinVandersteen** [doctrine/dbal#2805]
Hello!

I've recently updated to 2.6.1 and PHP 7.1 so that I can use the JSON data type in MySQL.
I did it because I was getting these kinds of errors when adding JSON fields in a migration (which worked previously though?) :

```
[Doctrine\DBAL\DBALException]                                                                    
  Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it. 
```
The error is still present though, even after updating. The error still mentions MySqlPlatform and not MySQL57Platform, which made me understand that the problem was in the mysql version detection.

It works when I had a return with my version just before the "return null;" that happens at the end of the getServerVersion() method in Connection.php, like so : 
```Php
private function getServerVersion()
    {
        // Automatic platform version detection.
        if ($this->_conn instanceof ServerInfoAwareConnection &&
            ! $this->_conn->requiresQueryForServerVersion()
        ) {
            return $this->_conn->getServerVersion();
        }

        return '5.7.13';
        // Unable to detect platform version.
        return null;
    }
```

So now my question is : Does anybody have an idea why my local MySQL database's version can't be detected by doctrine/dbal? Thanks in advance, this is really blocking for an important production feature and it's really surprising that it sometimes worked even in 2.5.2!

**Comment by le-martre** [comment]
Update : I've done nothing and it now works. If you guys have any idea what could cause those issues, I'm all ears! Such inconsistent development environment is really annoying :(

**Comment by Ocramius** [comment]
@MartinVandersteen did you maybe have a config caching issue?

**Comment by MartinVandersteen** [comment]
@Ocramius my collegue now has the same issue when switching on my branch, I told him to restart his development environment to see if it does the trick. If it does, I guess it could be it?

**Comment by MartinVandersteen** [comment]
Didn't do the trick.. Maybe there is a specific command to flush the config cache that you know of?

**Comment by MartinVandersteen** [comment]
Ok no my bad, it only worked because I left the "return '5.7.13';" in the private function getServerVersion. So probably not a config caching issue.

**Comment by lcobucci** [comment]
@MartinVandersteen can you provide more information on how your connection is created and what are the arguments in there? I'm really interested on what implementation of `Doctrine\DBAL\Driver\Connection` you have there.

I'm asking because as far as I could see all the MySQL related implementations would always make `$this->_conn instanceof ServerInfoAwareConnection && ! $this->_conn->requiresQueryForServerVersion()` to be `true`.

**Comment by belgattitude** [comment]
@MartinVandersteen 

What returns PDO::getAttribute(PDO::ATTR_SERVER_VERSION); in the `PDOConnection::getServerVersion()`  ? When you replaced by "return '5.7.13';" it worked... Are you using mariadb ?

(If you use mysqli, what returns `$this->_conn->server_version` and `$this->_conn->get_server_info()` in `MysqliConnection::getServerVersion()` instead)

**Comment by morozov** [comment]
Closing as stale.
