### ISSUE TITLE
Driver specific exceptions are not converted properly

### ISSUE THREAD

**Issue by natebrunette** [doctrine/dbal#2806]
PDO may not throw an exception when executing a query. In `\Doctrine\DBAL\Connection::executeQuery`, the connection `errorInfo()` and statement `errorInfo()` should be checked for a driver exception code and a driver specific exception should be created if an error occurred.

**Comment by Ocramius** [comment]
This needs a test case for the specific scenario you encountered.

**Comment by natebrunette** [comment]
@Ocramius I looked for contributor documentation, but didn't find any. Do you want me to fork the repository, write a failing test and make a pull request?

**Comment by Ocramius** [comment]
@natebrunette that would be the best scenario, but an example of failure not reflected by PDO is also sufficient.

We configure PDO so that it throws exceptions internally on its own, btw: https://github.com/doctrine/dbal/blob/399ab63ddf3db48a4befb7d4f6bcf699e7796d5f/lib/Doctrine/DBAL/Driver/PDOConnection.php#L45

**Comment by natebrunette** [comment]
What this code sample illustrates is a bug when an error handler is registered.

I noticed that using `PDOConnection`, PDO will throw an exception. However, if an error handler is registered, it will get executed first, essentially swallowing PDO's exception. This is the case in Symfony applications.

What this code sample shows is two cases. One, executing a query on the connection, and secondly, using a prepared statement. In both cases, the exception coming from the error handler is caught and a PDO exception never occurs. In each `finally` block, I show how to get the driver specific error code, depending on which kind of query is executed.

```php
<?php

require __DIR__.'/vendor/autoload.php';

use Doctrine\DBAL\Driver\PDOConnection;

set_error_handler(function ($errno, $errstr, $errfile, $errline, $errcontext) {
    throw new \Exception('This is a wrapped exception');
});

$host = '127.0.0.1';
$database = 'test';
$user = 'root';
$password = null;

$connection = new PDOConnection("mysql:host=$host;dbname=$database", $user, $password);
$connection->exec('SET SESSION wait_timeout=1');
sleep(2);

// regular connection execute
try {
    $connection->exec('DO 1');
} catch (\PDOException $exception) {
    echo 'Caught pdo exception', PHP_EOL;
} catch (\Throwable $exception) {
    echo 'Caught generic exception', PHP_EOL;
} finally {
    var_dump($connection->errorInfo());
}

$connection = new PDOConnection("mysql:host=$host;dbname=$database", $user, $password);
$connection->exec('SET SESSION wait_timeout=1');
sleep(2);

// prepared statement
$statement = $connection->prepare('DO 1');
try {
    $statement->execute();
} catch (\PDOException $exception) {
    echo 'Caught pdo exception', PHP_EOL;
} catch (\Throwable $exception) {
    echo 'Caught generic exception', PHP_EOL;
} finally {
    // connection lacks error info, use statement error info
    var_dump($connection->errorInfo());
    var_dump($statement->errorInfo());
}
```

Example output

```
Caught generic exception
/Users/natebrunette/Development/dbal-pdo-test/test.php:28:
array(3) {
  [0] =>
  string(5) "HY000"
  [1] =>
  int(2006)
  [2] =>
  string(26) "MySQL server has gone away"
}
Caught generic exception
/Users/natebrunette/Development/dbal-pdo-test/test.php:44:
array(3) {
  [0] =>
  string(5) "00000"
  [1] =>
  NULL
  [2] =>
  NULL
}
/Users/natebrunette/Development/dbal-pdo-test/test.php:45:
array(3) {
  [0] =>
  string(5) "HY000"
  [1] =>
  int(2006)
  [2] =>
  string(26) "MySQL server has gone away"
}

Process finished with exit code 0
```

**Comment by Ocramius** [comment]
That's a good enough test as a start, thanks! :+1:

**Comment by morozov** [comment]
It doesn't look like we can do anything here: PDO reports the same error in two different ways, and an external handler hijacks flow control. Relying on `errorInfo()` may have its side effects since it's a shared global state and there's no guarantee that it will be always clean.
