### ISSUE TITLE
Wrong _transactionNestingLevel decrement

### ISSUE THREAD

**Issue by RadekDvorak** [doctrine/dbal#2808]
Hi, while developing a feature that works with transaction nesting I think I encountered a bug.

The class `\Doctrine\DBAL\Connection` supports nested transactions with savepoints. Calling `rollBack` in a nested context only rolls back to the latest savepoint. Then the transaction nesting level gets [decremented](https://github.com/doctrine/dbal/blob/v2.6.1/lib/Doctrine/DBAL/Connection.php#L1359). According to [PostgreSQL docs](https://www.postgresql.org/docs/9.6/static/sql-rollback-to.html) _the savepoint remains valid and can be rolled back to again later, if needed_. I think the same should apply to the current transaction nesting level - it should remain valid. 

In fact it is the `RELEASE SAVEPOINT` SQL query that makes the savepoint vanish and transaction nesting level should be decreased consequently.

[MySQL docs](https://dev.mysql.com/doc/refman/5.6/en/savepoint.html) is not that specific. Still I have reproduced the same behaviour as documented for PostgreSQL.
```mysql
START TRANSACTION;
SAVEPOINT foo;
ROLLBACK TO SAVEPOINT foo;
ROLLBACK TO SAVEPOINT foo;
RELEASE SAVEPOINT foo;
COMMIT;
```

Can you confirm the bug or explain this behaviour? Thanks

**Comment by Ocramius** [comment]
> Can you confirm the bug or explain this behaviour?

Not really: an integration test needs to be written to check this.

**Comment by RadekDvorak** [comment]
I can not find any harm to data that would be caused by this behaviour.
