### ISSUE TITLE
Incorrect documentation example for `QueryBuilder#set()`

### ISSUE THREAD

**Issue by Dormilich** [doctrine/dbal#2814]
The affected code section (also the `update()` and `where()` examples)
```
     * <code>
     *     $qb = $conn->createQueryBuilder()
     *         ->update('users', 'u')
     *         ->set('u.password', md5('password'))
     *         ->where('u.id = ?');
     * </code>
```
When looking at the source code for `set()`, the `$value` parameter is not escaped (which makes sense) but then any unescaped string value (such as the mentioned MD5 hash) would cause an SQL syntax error due to missing string delimiters. Insofar the code example is misleading as to what can be put in as value.

Maybe a better example would be using one of the SQL functions, e.g.
```
->set('u.last_login', 'NOW()')
```

**Comment by lcobucci** [comment]
@Dormilich would you mind send us a PR with your suggestion?

**Comment by Dormilich** [comment]
not sure if I opened the PR correctly ... it's been ages since I did that last.

**Comment by Ocramius** [comment]
@Dormilich go to https://github.com/doctrine/dbal and you should see a green button that allows you to open a PR, if everything is detected correctly.

**Comment by Ocramius** [comment]
Handled in #2818
