### ISSUE TITLE
mysqli ssl_key and ssl_cert should not be mandatory

### ISSUE THREAD

**Issue by gauauu** [doctrine/dbal#2815]
In MysqliConnection.php, in setSecureConnection, there's a clause that ensures that ssl_key and ssl_cert are set.

I have a mysql connection that needs an ssl_ca to be specified, but doesn't need ssl_key or ssl_cert. I've been using this connection succefully (without this library) with this call:

`$db->ssl_set(null, null, '/etc/msqlcacert.pem', null, null);`

But with the error checking here, I can't do that.  

If I hack MysqliConnection.php to remove the "mandatory" check, and set ssl_key and ssl_cert to optional, it works on my connection:

```
		$this->_conn->ssl_set(
			$params['ssl_key'] ?? null,
			$params['ssl_cert'] ?? null,
			$params['ssl_ca']     ?? null,
			$params['ssl_capath'] ?? null,
			$params['ssl_cipher'] ?? null
		);
```

Thanks!

**Comment by gauauu** [comment]
BTW, I'm happy to make a PR with the changes unless there's a reason I'm wrong or unless dbal shouldn't support this usage for some reason.

**Comment by Ocramius** [comment]
@gauauu this is possibly a regression, so go ahead and send a patch if you can :+1:
