### ISSUE TITLE
Enable SQLite foreign key on post-connect

### ISSUE THREAD

**Issue by Ocramius** [doctrine/dbal#2833]
Apparently, SQLite has supported foreign keys for ages! All we need to do is (according to https://sqlite.org/foreignkeys.html) run a statement on post-connect:

```sql
PRAGMA foreign_keys = ON;
```

Not sure where to do it exactly, but this would be a very welcome addition.

**Comment by Federkun** [comment]
> Not sure where to do it exactly

I've an event subscriber to enable that: would you suggest to add an `SqliteSessionInit.php`?

**Comment by Ocramius** [comment]
@Federkun yup :+1:

**Comment by drhsqlite** [comment]
SQLite has a compile-time option to enable foreign_key enforcement by default.  https://www.sqlite.org/compile.html#default_foreign_keys

The default build of SQLite has foreign_key enforcement turned off by default due to backwards-compatibility concerns.

**Comment by Ocramius** [comment]
Compile-time is not in our ballpark: we are a lib sitting on top of
pre-compiled php binaries.

**Comment by DontShootMe** [comment]
Hello,
Just a little up about this functionality.

Have you found any good approach, because foreign keys are missing for ages ?

Many thanks all, for all your work
You are all amazing

**Comment by alexander-schranz** [comment]
I did stumble over https://github.com/doctrine/dbal/pull/5404 and asking myself if FK is now supported via dbal?

**Comment by derrabus** [comment]
Yes. I think, we can close this issue.
