### ISSUE TITLE
Travis failures under Trusty

### ISSUE THREAD

**Issue by Majkl578** [doctrine/dbal#2837]
[Trusty is now default](https://blog.travis-ci.com/2017-08-31-trusty-as-default-status) and some mysql-realted jobs are failing there.
Possibly check #2825, it already contains some sort of fix/hack to make it work.
While at it, we should also migrate to Build Stages.

**Comment by belgattitude** [comment]
#2825 fixes the build (no build stages though) and adds MariaDB 10.2 in the matrix.

FYI, the updated travis config: https://github.com/belgattitude/dbal/blob/fd0f8ba6ced610b8a8c159ff5da4b9aed540ed70/.travis.yml

**Comment by Majkl578** [comment]
Fixed in #2849.
