### ISSUE TITLE
doc: Host ApiGen for 2.6

### ISSUE THREAD

**Issue by lorenzleutgeb** [doctrine/dbal#2842]
Hi!

`http://www.doctrine-project.org/api/dbal/2.6.2/` and `http://www.doctrine-project.org/api/dbal/2.6.2/` are dead while `http://www.doctrine-project.org/api/dbal/2.5/` works. Could you please host the new docs as well? Or redirect to wherever they are hosted for 2.6.

Thanks!

**Comment by Majkl578** [comment]
We don't use ApiGen anymore. Current API docs for each version can be found here: https://www.doctrine-project.org/projects/dbal.html

**Comment by lorenzleutgeb** [comment]
That issue probably was not invalid 13 months ago, only now, but fine.

**Comment by Ocramius** [comment]
@lorenzleutgeb that means that it was worked on, when possible :)
