### ISSUE TITLE
MySQLi: ssl_key and ssl_cert not _really_ mandatory for ssl

### ISSUE THREAD

**Issue by nvanheuverzwijn** [doctrine/dbal#2843]
Hi,

You can do SSL with mysql and php without specifying an `ssl_key` and `ssl_cert`. The only mandatory parameter would be the `ssl_ca`. Raising an exception here is not necessary.

https://github.com/doctrine/dbal/blob/8d18a33043edd1dd0b2a996262b67523e1b83f05/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php#L286

**Comment by Ocramius** [comment]
Dupe of https://github.com/doctrine/dbal/pull/2816#issuecomment-327060259
