### ISSUE TITLE
Interface 'Throwable' not found in Laravel5.4 

### ISSUE THREAD

**Issue by ubo5** [doctrine/dbal#2852]
- When I do a bad sql query, this problem will come up.

- Here is the err message
'Interface 'Throwable' not found' in projectName/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/DriverException.php:33

**Comment by Ocramius** [comment]
`Throwable` is a PHP 7.0+ concept. If you experience bugs in pre-7.0 environments, we'll need a test case to reproduce this in isolation, with DBAL only.

**Comment by Majkl578** [comment]
Are you sure you're not using DBAL version incompatible with your PHP? DriverException extends Throwable only in 2.6 which requires PHP 7.1.

**Comment by ubo5** [comment]
Yes, I've double checked this. PHP version is PHP 7.1.8 and doctrine/dbal  is v2.6.2 in my env.
Can other configs cause this problem?

**Comment by Ocramius** [comment]
@ubo5 are php-cli and the one running the web server at the same version?

**Comment by ubo5** [comment]
yes! It seems something wrong with my php-fpm configuration, It use the old version php-fpm which php version is php5.6. 
@Ocramius Thanks!
