### ISSUE TITLE
Create an "async" API

### ISSUE THREAD

**Issue by davidbarratt** [doctrine/dbal#2860]
[Guzzle](http://docs.guzzlephp.org/en/stable/) has a really nice ["async" API](http://docs.guzzlephp.org/en/stable/quickstart.html#async-requests). I put "async" in quotes because it's not really async it's more just _concurency_. `curl` has support to execute more than one request at a time. Guzzle will group the requests and execute them together, then it will group the next level down and execute them together and so on until all of the requests and callbacks are completed. Something they don't add to the docs is that you **must** call `wait()` or the request(s) are never executed (because it's basically just a huge array of requests).

I noticed that [PDO::execute](http://php.net/manual/en/pdo.exec.php) allows more than one query to be executed (without a result set), and [PDOStatement::nextRowset](http://php.net/manual/en/pdostatement.nextrowset.php) will allow access to multiple row sets on queries that have multiple result sets.

It kind of looks like PDO will allow concurrent queries just like `curl` will allow concurrent requests.

I think it would be helpful if there was some sort of "async" API that would return a _Promises/A+_ promise. You'd still have to call `wait()` just like Guzzle, but it would make it really convenient to group and ungroup queries together so queries can be executed concurrently without making a huge mess.

**Comment by morozov** [comment]
Relating this to #2562.

**Comment by Ocramius** [comment]
This could be interesting, but won't fit the existing API.

What could be useful is an `AsyncConnection` interface returning promises
and consuming promises (specifically around transactions).

Can be done, but I doubt it will happen with PDO as underlying layer.

**Comment by Majkl578** [comment]
Some notes:
MySQL has the following async PHP API (with mysqlnd **only**):
* [`mysqli::send_query()`](http://php.net/manual/en/mysqli.send-query.php)
* [`mysqli::poll()`](http://php.net/manual/en/mysqli.poll.php)
* [`mysqli::reap_async_query()`](http://php.net/manual/en/mysqli.reap-async-query.php)

PostgreSQL has the following async PHP API:
* [`pg_connect()` with `PGSQL_CONNECT_ASYNC`](http://php.net/manual/en/function.pg-connect.php)
* [`pg_connect_poll()`](http://php.net/manual/en/function.pg-connect-poll.php)
* [`pg_send_prepare()`](http://php.net/manual/en/function.pg-send-prepare.php)
* [`pg_send_query()`](http://php.net/manual/en/function.pg-send-query.php)
* [`pg_send_query_params()`](http://php.net/manual/en/function.pg-send-query-params.php)
* [`pg_send_execute()`](http://php.net/manual/en/function.pg-send-execute.php)
* [`pg_get_result()`](http://php.net/manual/en/function.pg-get-result.php)
* [``]()

**Comment by aftabnaveed** [comment]
There is a new PHP extension swoole https://github.com/swoole/swoole-src which has mysql async support out of the box may be worth looking at.

**Comment by morozov** [comment]
Closing as it hasn't gotten any traction.
