### ISSUE TITLE
Generate migrations always delete index

### ISSUE THREAD

**Issue by cduran433** [doctrine/dbal#2866]
Hello,

I have defined in my entity this annotations:

>   @ORM\Table(name="article_ar", indexes={
>       @ORM\Index(name="idx_position", columns={"position"}),
>       @ORM\Index(name="idx_home_position", columns={"home_position"}),
>       @ORM\Index(name="select_index", columns={"publication_date", "enabled"}),
>       @ORM\Index(name="idx_list_cms", columns={"author_id", "home_position"})
>    })
>   @ORM\Entity (repositoryClass="Application\By433\NewsBundle\Entity\ArticleArabicRepository")
>   @UniqueEntity("slug")

Index are created in database except idx_list_cms, but when I executed diff to generate the new file. The migration file is deleting all index that are already created.

        $this->addSql('DROP INDEX idx_position ON article_ar');
        $this->addSql('DROP INDEX select_index ON article_ar');
        $this->addSql('DROP INDEX idx_home_position ON article_ar');

If I also try to create schema with schema:diff, index are not created. I don't know what is happening. 

I ask in migrations project, but they told me that this issue is related with dbal project, so I open this issue here.

MYSQL version:  5.5.57
Doctrine Version: 2.5.0

**Comment by lcobucci** [comment]
@cduran433 could you please send us a failing test case that reproduces that behaviour? It would help us a lot to identify and fix the issue you're describing.

You can use these tests as example: https://github.com/doctrine/dbal/blob/954ce2e82c5892dfbd51c4bf5bd154c85fc3ecf8/tests/Doctrine/Tests/DBAL/Functional/Schema/SchemaManagerFunctionalTestCase.php#L1206-L1336

**Comment by perk11** [comment]
Just want to mention that this is still happening.

**Comment by k00ni** [comment]
What is the status here?

**Comment by lyrixx** [comment]
Is it the same issue as https://github.com/doctrine/orm/issues/6218 ?

**Comment by PowerKiKi** [comment]
This is a duplicate of #3780 and should be closed (also because of inactivity)
