### ISSUE TITLE
Doctrine\DBAL\Exception\InvalidFieldNameException when working with DB schema on PostgreSQL 10

### ISSUE THREAD

**Issue by skobkin** [doctrine/dbal#2868]
Since upgrading to PostgreSQL 10 I have an error in my projects using Doctrine when I trying to generate migrations or just check the schema difference:

```
$ sf doc:sche:up --dump-sql                                                                                          
  [Doctrine\DBAL\Exception\InvalidFieldNameException]                                                        
  An exception occurred while executing 'SELECT min_value, increment_by FROM "admin"."acl_classes_id_seq"':  
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist                             
  LINE 1: SELECT min_value, increment_by FROM "admin"."acl_classes_id_...                                    
                 ^
  [Doctrine\DBAL\Driver\PDOException]                                             
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist  
  LINE 1: SELECT min_value, increment_by FROM "admin"."acl_classes_id_...         
                 ^
  [PDOException]                                                                  
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist  
  LINE 1: SELECT min_value, increment_by FROM "admin"."acl_classes_id_...         
                 ^
doctrine:schema:update [--complete] [--dump-sql] [-f|--force] [--em [EM]]
```

Seems like it's related to [nextcloud/server#5930](https://github.com/nextcloud/server/issues/5930) where @justin-sleep wrote:

> This happens specifically because of changes to how PostgreSQL 10 handles sequence metadata.

**Comment by wzator** [comment]
Suggested solution:
PostgreSqlSchemaManager.php line 292:
>         $data = $this->_conn->fetchAll('SELECT min_value, increment_by FROM ' . $this->_platform->quoteIdentifier($sequenceName));

to :

>         $version = floatval($this->_conn->getWrappedConnection()->getServerVersion());
> 
>         if ($version >= 10) {
>            $data = $this->_conn->fetchAll('SELECT min_value, increment_by FROM pg_sequences WHERE schemaname = \'public\' AND sequencename = '.$this->_conn->quote($sequenceName));
>         }
>         else
>         {
>             $data = $this->_conn->fetchAll('SELECT min_value, increment_by FROM ' . $this->_platform->quoteIdentifier($sequenceName));
>         }

**Comment by justin-sleep** [comment]
PostgreSQL 10 is out of beta now: https://www.postgresql.org/about/news/1786/

**Comment by Majkl578** [comment]
First we will need Travis CI to support it: https://github.com/travis-ci/travis-ci/issues/8537

**Comment by iquad** [comment]
when it is going to be migrated? it definently solves the problem, and because of new sequence architecture on postgresql 10 we can't define a generic method for that.

**Comment by synthead** [comment]
Just tried @wzator's changes and it works fine here 👍

**Comment by exebece** [comment]
have this problem in doctrine2 using in symfony 3.3 version. no matter which ,,auto-identity'' aproach I chose, I got this error too.

**Comment by simPod** [comment]
We are waiting for PSQL10 support in Travis I guess. Meanwhile you can use code from my PR. https://github.com/doctrine/dbal/pull/2893

**Comment by exebece** [comment]
thank you, i'll analyze your commit and use it.

**Comment by Zyqsempai** [comment]
Guys, what the status of the issue?? When we can expect fix?

**Comment by simPod** [comment]
Read the comments please 

https://github.com/doctrine/dbal/issues/2868#issuecomment-334538085
https://github.com/doctrine/dbal/issues/2868#issuecomment-346591512

**Comment by Majkl578** [comment]
#2893 has been merged and added Postgres 10 support, closing this one as duplicate.

**Comment by mca-digital** [comment]
@wzator suggestion works very fine! 
Thanks!

**Comment by srigi** [comment]
This issue should be re-opened. Fetching data for sequence definition is not working with Postgres&nbsp;10.3. Fix in #2893 in not enough.

Code from @TiFaBl actually fixes the problem. Whats the fastest way for fix to be released? Should I start PR with tests/fixed-code?

**Comment by Ocramius** [comment]
> Whats the fastest way for fix to be released? Should I start PR with tests/fixed-code?

First a failing test case

**Comment by Majkl578** [comment]
DBAL is working as expected with PostgreSQL 10+, this is very likely a configuration issue in your code where you are not specifying server_version correctly.

The code path in question is [covered by tests](https://scrutinizer-ci.com/g/doctrine/dbal/code-structure/master/code-coverage/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php) and tested against all PostgreSQL 9.x, PostgeSQL 10 and PostgreSQL 11 ([this condition](https://github.com/doctrine/dbal/blob/v2.8.0/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php#L317-L322) is not entered with PostgreSQL 10+ since these metadata are [provided by the platform ahead](https://github.com/doctrine/dbal/blob/v2.8.0/lib/Doctrine/DBAL/Platforms/PostgreSQL100Platform.php#L22-L32)).

Anyway, if you still feel this is a Doctrine issue rather than a configuration issue, please open new issue with failing test.
