### ISSUE TITLE
How to config Doctrine/Dbal "naming_strategy" config in Laravel?

### ISSUE THREAD

**Issue by hanachan1026** [doctrine/dbal#2876]
I have CamelCase columns in my DB.

When I want to change them from CamelCase to snake_case, 
In the other word I run migrations, I have this error

```
 [Doctrine\DBAL\Schema\SchemaException]
  There is no column with name 'mylowercasecolumn' on table 'my_table'.
```

Is there a way to change "naming_strategy" config value easily?

**Comment by Ocramius** [comment]
Don't understand what this is about: can you please clarify further?

The naming strategy is an ORM concept, not a DBAL one, and Laravel doesn't use the ORM.

**Comment by hanachan1026** [comment]
@Ocramius 
For example I have this column named "lowerCaseColumn",
to change the column name to "lower_case_column",

I run this

```
Schema::table('my_table', function (Blueprint $table) {
    $table->renameColumn('lowerCaseColumn', 'lower_case_colomn');
}
```

But laravel migration process doesn't read 'lowerCaseColumn', 
it reads 'lowercasecolumn'.

To change column's info, I installed
```
"doctrine/dbal": "^2.6",
```

**Comment by Ocramius** [comment]
@hanachan1026 sounds like that's a Laravel-specific issue: DBAL will not change the casing of what you pass to it.

**Comment by hanachan1026** [comment]
@Ocramius sorry about this.
I'll look into this further.

**Comment by poisa** [comment]
@hanachan1026 Did you ever find a solution to this? I've ran into the exact same problem.
