### ISSUE TITLE
"Cycles or multiple cascade paths" problem using SQL Server 2017

### ISSUE THREAD

**Issue by mwns** [doctrine/dbal#2886]
I have to migrate database from MySQL to SQL Server 2017 (new Linux version, using newest stable sqlsrv PHP driver) and there're some problems with _onDelete_ attribute:
```
[Doctrine\DBAL\DBALException]

An exception occurred while executing 'ALTER TABLE xyz ADD CONSTRAINT FK_234044AB1B89B119 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL':
                                                                                                  
SQLSTATE [42000, 1785]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Introducing FOREIGN KEY constraint 'FK_234044AB1B89B119' on table 'xyz' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY cons
SQLSTATE [42000, 1750]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Could not create constraint or index. See previous errors.
```
I wonder what's the best way to solve this problem without removing mentioned attribute from annotations? Is it possible to achieve without using triggers? Obviously this error doesn't exist using MySQL database. Thank you for any advice.

**Comment by morozov** [comment]
@mwns is it the only FK constraint in your schema? As far as I understand the error message, the FK in question may interfere with other constraints which you didn't mention.

I'm not a DBA, but if I had to solve this, I would:

1. Dump the schema into a SQL file.
2. Import it into the database.
3. Try to remove tables and constraints one by one until the problem doesn't go away.
4. By repeating 2 and 3, find the conflicting pair (or set) of constraints.

**Comment by mwns** [comment]
The problem is that I can't see any symptoms of having multiple cascade paths or cycles in my entities. So it seems that SQL Server is too sensitive in this matter, comparing to other RDBMS. However I'll try your suggestion, thanks.

**Comment by mi-hol** [comment]
@mwns was the issue solved?

**Comment by inri13666** [comment]
Excellent article that describes why it happens for MS SQL
https://www.mssqltips.com/sqlservertip/2733/solving-the-sql-server-multiple-cascade-path-issue-with-a-trigger/

**Comment by morozov** [comment]
Closing as missing reproduction steps.
