### ISSUE TITLE
v2.5.13 includes annotations v1.* which breaks PHP 5 compatibility

### ISSUE THREAD

**Issue by gwagroves** [doctrine/dbal#2888]
doctrine/dbal 2.5.13 [composer json](https://github.com/doctrine/dbal/blob/v2.5.13/composer.json)

```
"require": {
    "php": ">=5.3.2",
    "doctrine/common": ">=2.4,<2.8-dev"
 }
```

resolves to doctrine/common 2.7.3.

doctrine/common 2.7.3 [composer json](https://github.com/doctrine/common/blob/v2.7.3/composer.json)

```
"require": {
  "php": "~5.6|~7.0",
  "doctrine/inflector": "1.*",
  "doctrine/cache": "1.*",
  "doctrine/collections": "1.*",
  "doctrine/lexer": "1.*",
  "doctrine/annotations": "1.*"
}
```

resolves to [doctrine/annotations 1.5.0](https://github.com/doctrine/annotations/tree/v1.5.0) 

doctrine/annotations 1.5.0 requires PHP 7:

> This release increments the minimum supported PHP version to 7.1.0

**Comment by Ocramius** [comment]
Please see http://doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html

Closing as `invalid`

**Comment by gwagroves** [comment]
@Ocramius Yes, I see the link. It states that dbal 2.6.0 drops support for PHP 5.

But **dbal 2.5.13** has also inadvertently dropped support for PHP 5.6, because `doctrine/common@2.7.3` requires `doctrine/annotations@1.5.0`, which requires PHP 7.1.

**Comment by Ocramius** [comment]
@gwagroves no, the composer SAT system will simply exclude those dependencies when running `composer update`, since they aren't compatible with your environment.

**Comment by gwagroves** [comment]
Ah, OK. Good to know. Unfortunately we have to commit the dependencies, and `composer update` was run under `7.1`, but the server runs `5.6`.

Thanks!

**Comment by Ocramius** [comment]
@gwagroves eh, never ever ever ever ever do that: please run updates in a production-alike environment.
