### ISSUE TITLE
convertToDatabaseValue is called when value is null

### ISSUE THREAD

**Issue by kejwmen** [doctrine/dbal#2896]
Hi,
[ORM docs](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/custom-mapping-types.html) states that:
> If the value of the field is NULL the method convertToDatabaseValue() is not called.

But DBAL `Statement` [doesn't check that](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Statement.php#L114), and I encountered errors for custom type that did not handle null for conversion.

I can see that types like `DateType`, `DateTimeType`, etc. handle `null` in `convertToDatabaseValue`, so it looks like docs are wrong and contributors implementing types were aware of that.

Is it considered as a bug that should be fixed or docs are invalid?

I will prepare PR with test cases if you consider it as a bug.

**Comment by Ocramius** [comment]
This seems to be wrong in the ORM docs

**Comment by kejwmen** [comment]
Statement removed from ORM docs, closing.
