### ISSUE TITLE
How to hide password in exception/error messages

### ISSUE THREAD

**Issue by alperyazgan** [doctrine/dbal#2899]
Hi,

I am using Laravel Framework with uses doctrine/dbal  :-) and every time there is a problem with connection (like no network or db server down) in laravel log I can see the following line :

> Stack trace:
> #0 D:\hstaj\AppServer\httproot\smartinternship\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php(43): PDO->__construct('sqlsrv:Server=G...', 'someUser', 'somePassword', Array)

Here is my question; is there a way in dbal to hide the account details showing in exception ? 
Because system logs can be monitored by other users/softwares, this could lead to a security breach.

Or should I modify the code (of dbal or of what is related/responsible in laravel) ?

Your answer will be much appreciated, 
Regards,

**Comment by Ocramius** [comment]
That's unavoidable, because the parameters are somewhere in the trace. What
you want is to stop displaying exceptions to your users.

**Comment by alperyazgan** [comment]
Yes, not to show certain exception details sure ...
I see I am on my own ... Always there is a solution but I just wanted a short one ...

Thanks,
