### ISSUE TITLE
SQLite in-memory option useless without shared cache option

### ISSUE THREAD

**Issue by bitwombat** [doctrine/dbal#2901]
DBAL supports the `'memory' => true` option for SQLite database, but the way SQLite works, each new connection opening gets a new database.  This makes the feature useless because of how Doctrine opens up a new connection for every operation.

SQLite has an option that can be passed in the URI:  `sqlite::memory:?cache=shared`  This makes subsequent connection open operations share the same 'cache' - for some reason this means they share the in-memory database.

Unfortunately, PDO doesn't support this URI scheme, nor a setting via another mechanism (the docs for SQLite make it seem like the URI is the only way to get this behaviour, though there is a SQLite function called sqlite3_enable_shared_cache().  PHP's sqlite3 module supports this, but I don't think that's much help to Doctrine/DBAL).

I spent quite a few hours figuring this out, so I'd like to help document it somewhere to save the next poor sap.

Comments?

References:  
#2898 - This same issue, but I closed it because I was confused and the comments muddy everthing.
https://github.com/php/php-src/pull/2734/files (a PR that added support for an SQLite attribute - does a  similar attribute exist for the shared cache option?)
http://www.sqlite.org/sharedcache.html
http://www.sqlite.org/inmemorydb.html
https://stackoverflow.com/questions/9150319/enable-shared-pager-cache-in-sqlite-using-php-pdo
https://stackoverflow.com/questions/16487679/shared-cache-on-pdo-sqlite

**Comment by mikeryan776** [comment]
Added a pull request to support this - just a simple matter of adding "?cache=shared" to the DSN. Before attempting tests, a couple of questions:

1. I think shared cache mode is supported beyond :memory:, so this perhaps should go just before the return?
2. Are there other similar settings driver settings that could be supported?

Thanks.

**Comment by mikeryan776** [comment]
The current idea in the PR is to add 'dsn' as a possible connection param for the pdo_sqlite driver. For my own purposes, for now I'm using this solution as follows:

In my composer.json, referencing patch file [sqlite-shared-cache.patch.txt](https://github.com/doctrine/dbal/files/2912534/sqlite-shared-cache.patch.txt) (minus the .txt):

```json

    "require-dev": {
        "phpunit/phpunit" : "^8.0",
        "squizlabs/php_codesniffer": "^2.3",
        "cweagans/composer-patches": "~1.0"
    },

    "extra": {
        "patches" : {
            "doctrine/dbal": {
                "Share sqlite memory connections for testing": "patches/sqlite-shared-cache.patch"
            }
        }
    },

```
And in my code:
```php
$params = [
//    'url' => 'sqlite:///:memory:?cache=shared',
    'driver' => 'pdo_sqlite',
    'dsn' => 'sqlite::memory:?cache=shared',
];
$connection = DriverManager::getConnection($params);
```

So, now I can populate a table with sample data in my test, and validate that the tested DBAL code properly handles it.

**Comment by mikeryan776** [comment]
:headdesk:

This doesn't actually work - it's not using memory, it's creating a local database file `:memory:?cache=shared`. @bitwombat referenced that in #2898, which I conveniently forgot once I thought I had this working. Back to the drawing board.

**Comment by mikeryan776** [comment]
Note there is a PDO request for this functionality (referencing this issue): https://bugs.php.net/bug.php?id=76868

**Comment by lukepass** [comment]
Hello, any news on this subject? It would be really useful!

**Comment by gravataLonga** [comment]
Not related directly of dbal but, this is sad we don't have `shared` option that we can use on PHP. It's impossivel! :(

**Comment by morozov** [comment]
Closing as `pdo_sqlite` doesn't support using shared memory.
