### ISSUE TITLE
Issue getAlterTableSql not keeping the column order

### ISSUE THREAD

**Issue by XavierVILAIN** [doctrine/dbal#2904]
Hi,

in the file dbal/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php method getAlterTableSQL could you replace :
$queryParts[] = 'ADD ' . $this->getColumnDeclarationSQL($column->getQuotedName($this), $columnArray);
By 
  $queryPart = 'ADD ' . $this->getColumnDeclarationSQL($column->getQuotedName($this), $columnArray);
            if(isset($columnArray['previousColumnName']) && !empty($columnArray['previousColumnName'])) {
            	$queryPart .= ' AFTER '.$columnArray['previousColumnName'];
            }
            $queryParts[] = $queryPart;
To keep column order

**Comment by Ocramius** [comment]
@XavierVILAIN such a change request requires a failing test justifying it.

**Comment by morozov** [comment]
Closing as stale.
