### ISSUE TITLE
Whoops when accessing Admin Settings "/admin" after Upgrade

### ISSUE THREAD

**Issue by S0QR2** [doctrine/dbal#2910]
Hello,

i am running snipeit in a subfolder. Which was working great until i upgraded from 3.X to 4.X and now to 4.1.3. I cant access the /admin Settings via the "Gears"-Icon in the top right. I always get a red bar with "whoops ....".

Everything else seems to work. I can see, edit, create assets and people. All Data is available and working.

Anyone got an idea where i could start to look. I can really figure it out.

**Comment by Ocramius** [comment]
Closing here - while the exception may be raised by DBAL, this needs to be verified to be a DBAL issue before reporting it, sorry.
