### ISSUE TITLE
Question about database URL

### ISSUE THREAD

**Issue by Gregwar** [doctrine/dbal#2938]
Hello,

I observed a strange behaviour using `pdo_sqlsrv`. The following won't work:

```
pdo_sqlsrv://127.0.0.1/?dbname=Database&user=USR&password=PWD
```

When the following works:

```
:///?host=127.0.0.1&dbname=Database&user=USR&password=PWD&driver=pdo_sqlsrv
```

Looks like the "protocol driver" and the host are not processed correctly?

**Comment by Majkl578** [comment]
The scheme should be `sqlsrv`, not `pdo_sqlsrv`, underscore is not a valid character for protocol scheme (it's parsed by `parse_url()` internally). See https://3v4l.org/9fK7Q vs. https://3v4l.org/OYQF8.
