### ISSUE TITLE
How do i resolve this issue

### ISSUE THREAD

**Issue by Prabhareg2** [doctrine/dbal#2970]
I'm getting this error, when trying to run a select query: " Doctrine\DBAL\Exception\DriverException: An exception occurred while 
executing 'SELECT t0.id AS id1, t0.ended_at AS ended_at2, 
t0.enter_action_id AS"

MySQL server has gone away 
1 File "/var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php" 
line 115 in convertException 
2 File "/var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php" 
line 116 in driverExceptionDuringQuery 
3 File "/var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php" line 
836 in executeQuery 
4 File "/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/BasicEntityPersister.php" 
line 748 in load 
5 File "/var/www/vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php" 
line 172 in Doctrine\ORM\Proxy\{closure} 
6 File "/var/www/app/cache/prod/doctrine/orm/Proxies/__CG__BKCoreBundleEntityContactProgress.php" 
line 274 in __invoke

**Comment by Ocramius** [comment]
This is generally due to long running processes. If you have a long running process, you want to use `Doctrine\DBAL\Connection#ping()` and check if the connection is still alive before resuming operations. If not, you will need a new connection and `EntityManager`.
