### ISSUE TITLE
Platform-specific querybuilder classes

### ISSUE THREAD

**Issue by jnvsor** [doctrine/dbal#2972]
Certain platform-produced sql such as upsert is best made in the abstractplatform with a query builder, allowing it to be changed afterwards. But said platform-specific sql can't be implemented with a generic query builder.

For example, the only way to produce this valid mysql query in the `QueryBuilder` class would be to tack the last half onto the `orderBy` part. That's pretty bad.

```
INSERT INTO t1 (a,b,c) VALUES (1,2,3)
ON DUPLICATE KEY UPDATE c=c+1;
```

Can we add platform-specific query builder subclasses with extra parts? That would allow for a proper solution to the upsert problem.

**Comment by Ocramius** [comment]
No, this is not going to happen:

 1. Inheritance is not the correct approach for that
 2. We only maintain code that is cross-platform compliant. Anything else is outside the scope of this project.
