### ISSUE TITLE
[3.0 proposal] Let BigInt be integer in PHP, not string

### ISSUE THREAD

**Issue by Majkl578** [doctrine/dbal#2976]
BigInt has size of 8 bytes, same as PHP integer on 64-bit platfoms. It doesn't feel right to see and use an integer as string these days.
This would require 64-bit PHP architecture (x64, x32) for BigIntType, which shouldn't be an issue nowadays, but for 32-bit compatibility there could be _fallback type_ (or a switch in BigIntType) available which would mimic current behavior.
Another possible issue are unsigned types, but these are currently currently supported out-of-box afaik: 32-bit IntegerType on 32-bit arch would have same issues as 64-bit BigIntType on 64-bit arch - becoming signed number in PHP.

**Comment by Ocramius** [comment]
This is not a BC Break worth pursuing, in my opinion. Most folks just need `INT` (no `BIGINT`), while those that do in fact need a `BIGINT` may have already very customized code that uses strings and GMP to operate.
