### ISSUE TITLE
DATE_ADD does not work with intervals from columns in SQLite

### ISSUE THREAD

**Issue by fogs** [doctrine/dbal#2983]
Hi there!

We using DATE_ADD() with a dynamic interval parameter from a table column, such as 
`->andWhere($qb->expr()->gt("DATE_ADD(p.beginsOn, p.duration, 'month')", ':timestamp'))`

This works well in MySQL but not in SQLite; the latter produces
`AND DATE(b0_.c_beginsOn,'+b0_.c_duration MONTH') > ?)`

It seems to me like the only static intervals were anticipated; however SQLite can also handle dynamic ones.

**Comment by morozov** [comment]
Fixed by https://github.com/doctrine/dbal/pull/3019.
