### ISSUE TITLE
How to remove realCacheKey when I use my custom cache engine?

### ISSUE THREAD

**Issue by pjyong** [doctrine/dbal#2987]
I find DBAL library always connects sqlquery and connection info as realCacheKey in ResultCacheStatement class file.
But actually, I have my own cahceKey, I do not want to waste extra space on realCacheKey.
Can someone tell me how to remove that?
Thanks very much

**Comment by Ocramius** [comment]
@pjyong can you clarify the question? Adding connection info to the cache key is required because different backends may respond differently to the same query.

If you are applying higher level caching, then the `ResultCacheStatement` is not the right abstraction for tweaking the cache.

**Comment by pjyong** [comment]
![screenshot from 2018 01 23 08 49 10](https://user-images.githubusercontent.com/3728556/35252970-e2b0867a-001d-11e8-87b9-82460664fc1d.png)
Thanks for your explanation.
I attached the pic to clarify the question. Is there better way to remove the real cache key? I think my project will always use MySQL.

**Comment by pjyong** [comment]
@Ocramius

**Comment by pjyong** [comment]
Hi
I solved it. I overwrite QueryCacheProfile and CacheProvider, then use the same real key now.
Thanks very much.

**Comment by Ocramius** [comment]
That is indeed a workable solution. Closing here, no work needed.
