### ISSUE TITLE
Doctrine doesn't truncate sequences name to 63 characters

### ISSUE THREAD

**Issue by MisterGrouik** [doctrine/dbal#2993]
Hi everyone,

"doctrine:schema:update --dump-sql" generates this SQL

CREATE SEQUENCE myst_survey_instances_payroll_item_id_myst_survey_instances_payroll_item_seq INCREMENT BY 1 MINVALUE 1 START 1;

Why isn't the sequence name truncated to 63 characters ? It should truncate beforehand to detect that this sequence already exists in my database.
Now I can't use "doctrine:schema:update --force" because Postgre truncate to "myst_survey_inst  
  ances_payroll_item_id_myst_survey_instances_pay" and of course, this sequence already exists.

**Comment by Ocramius** [comment]
> Why isn't the sequence name truncated to 63 characters

Why should it be? The schema definition is clear: it should rather throw an exception upfront if the platform can't handle such long names.

**Comment by MisterGrouik** [comment]
The problem is that at the first "doctrine:schema:update",  the sequence is created with no problem because Postgre will truncate the name to 63 characters. But then when you'll do "doctrine:schema:update" again, Doctrine will generate the SQL for the sequence again because it doesn't detect the sequence in the database.
Indeed, Doctrine tries to detect the sequence will the full name and not the truncated name. In consequences, the SQL is generated again but it will fail because Postgre will truncate again the name and the sequence already exists with this truncated name.

Strange behaviour.

**Comment by MisterGrouik** [comment]
I didn't have any exception at the first "doctrine:schema:update". Doctrine never told me that the sequence name was too long.

**Comment by Ocramius** [comment]
I mean that the exception should be added to the codebase :-)

**Comment by MisterGrouik** [comment]
How do you do that ? How can you specify the max length of a sequence ?

**Comment by Ocramius** [comment]
We can't. We'd simply make sure that when such a sequence is passed anywhere to the platform, the platform throws an exception instead of silently continuing execution.

**Comment by morozov** [comment]
Should be fixed by https://github.com/doctrine/dbal/pull/4106.
