### ISSUE TITLE
Unable to connect to DB Oracle  v 11.2

### ISSUE THREAD

**Issue by jkamler** [doctrine/dbal#2997]
This issue was reported on https://github.com/symfony/symfony/issues/25935 but problem is on Doctrine side so this is reported here.

I am using Symfony 4.0.3 and I need connect to Oracle DB. I follow this instructions:

https://symfony.com/doc/current/doctrine.html

my .env file contains this

`DATABASE_URL=oci8://user:pwd@xxx.xxx.xxx.xxx:1521/something`
host address is from tnsnames.ora -> HOST, something is from tnsnames.ora -> SERVICE_NAME

And after running command:

`php bin/console doctrine:database:create`
I get this error:

```
C:\Apache24\htdocs\myapp>
2018-01-25T12:58:47+00:00 [error] Error thrown while running command 
"doctrine:database:create". Message: "Notice: Undefined index: dbname"

In AbstractOracleDriver.php line 125:

  Notice: Undefined index: dbname
```

I am able to connect to DB by plain PHP, but through Symfony not. dbname is something from my connect url at .env file. This is set from tnsnames.ora.

After this I tryed modify doctrine.yaml like this:

```
parameters:
# Adds a fallback DATABASE_URL if the env var is not set.
# This allows you to run cache:warmup even if your
# environment variables are not available yet.
# You should not need to change this value.
#env(DATABASE_URL): ''

doctrine:
    dbal:
      default_connection:   default
      connections:
        default:
          driver:    'oci8' # ... or 'pdo_oci'
          dbname:    'dbname'
          host:      'xxx.xxx.xxx.xxx'
          port:      '1521'
          user:      'user'
          password:  'pwd'

# With Symfony 3.3, remove the `resolve:` prefix
#         url: '%env(resolve:DATABASE_URL)%' 
orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
        App:
            is_bundle: false
            type: annotation
            dir: '%kernel.project_dir%/src/Entity'
            prefix: 'App\Entity'
            alias: App
```
after command `php bin/console doctrine:database:create`

I have same error.

My dbname is same as I have in SQL Developer in SID item.

**Comment by andreasschacht** [comment]
Same Problem, did you resolve it somehow @jkamler ?

**Comment by jkamler** [comment]
No. :-(

2018-06-18 21:39 GMT+02:00 Andreas Schacht <notifications@github.com>:

**Comment by Majkl578** [comment]
I went through the driver and CLI command code. The command removes database name which doesn't yet exist at that point (thanks @xabbuh for the culprit) and tries to establish connection without the database name. Unfortunately Oracle doesn't support connections without database name, this is also covered by a test:
https://github.com/doctrine/dbal/blob/11037b4352c008373561dc6fc836834eed80c3b5/tests/Doctrine/Tests/DBAL/Functional/Driver/AbstractDriverTest.php#L24-L38
https://github.com/doctrine/dbal/blob/11037b4352c008373561dc6fc836834eed80c3b5/tests/Doctrine/Tests/DBAL/Functional/Driver/PDOOracle/DriverTest.php#L24-L30

Added in f229b8a7074986ae844f0a89b83f420ee0f08c29.

So unfortunately this command won't work with Oracle.

It should throw some meaningful error though, not _undefined index_. cc @morozov

**Comment by morozov** [comment]
This should have been fixed by https://github.com/doctrine/dbal/pull/3297.
