### ISSUE TITLE
Rename protected and private class members starting with an underscore

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3004]
According to [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md), protected and private property and method names should not be prefixed with an underscore. Currently, we have some of them in the code base:
```
↪ git grep -P '(protected|private) (function |\$)_(?!_)' v2.8.0 | wc -l
284
```

In order to fix the coding standard violations, they should be renamed which would be backward incompatible. A major release could be used to make such a change.

**Comment by morozov** [comment]
Partially fixed in https://github.com/doctrine/dbal/pull/3303 and https://github.com/doctrine/dbal/pull/3306.

**Comment by Majkl578** [comment]
For the rest of protected underscored members, imho the best approach would be to make them private and expose protected constructor instead(https://github.com/doctrine/dbal/pull/3007#issuecomment-362605345). Should this be too annoying, there could be a __get() polyfill of some sort.
@Ocramius @morozov Thoughts?
