### ISSUE TITLE
Statement objects should throw exception in exceptional cases

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3005]
As it was pointed out in https://github.com/doctrine/dbal/pull/2546#discussion_r96259485, the current API contract doesn't allow some methods to throw exceptions even in exceptional situations.

For instance:

1. `ResultStatement::fetch()`, `::fetchColumn()` will return `false` (or empty array in case of `fetchAll()`) if there's no more data to fetch or the statement hasn't been executed yet. In the latter, it should throw an exception instead.
2. `ResultStatement::closeCursor()` should not return anything. Some underlying implementations (e.g. `mysqli`) have a `void` return type, for others (e.g. `ibm_db2` and `oci8`) it's just a formality (they both return false if the `$stmt` is not passed).
3. `Statement::bindParam()`, `::bindValue()` and `::execute()` return a boolean or throw exceptions depending on the driver (see `DB2Statement` or `MysqliStatement`) for example. These methods shouldn't return any value and should throw an exception in case of failure.
4. In `ResultCacheStatement` and `ArrayStatement`, calling `::fetchColumn()` with an invalid column index should throw an exception.
5. `ResultStatement::setFetchMode()` shouldn't return any value.

**Comment by morozov** [comment]
@Ocramius is fixing this one worth breaking BC in your opinion?

**Comment by Majkl578** [comment]
> is fixing this one worth breaking BC in your opinion?

I'd say it is. Returning false on error is PHP relic.
It can be implemented in backward- & forward-compatible way, i.e. by a temporary switch (2.x only) to enable exceptions in 2.x. Or even as Configuration option which will won't be possible to disable in 3.0.

**Comment by Ocramius** [comment]
Yes, returning `false` on error is just problematic. If the exception type is specific enough, adding `try-catch` around it is trivial.

**Comment by Majkl578** [comment]
What's the resolution here @morozov?

**Comment by morozov** [comment]
It's partially resolved by the rework of the types. None of the methods return `false` to indicate the error but the exceptions are only thrown when the underlying indicates an error.
