### ISSUE TITLE
Diff is not working if options are set directly in Type::getSQLDeclaration()

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#3021]
I created a custom BooleanType with the following method:

    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform) {
        return $platform->getBooleanTypeDeclarationSQL($fieldDeclaration) . ' UNSIGNED';
    }

The issue is that the diff keeps altering the table as it thinks no unsigned type option should be presented.

I think there are two solutions:
a) Parse the options from Type::getSQLDeclaration() method as from the standard table definition
b) The type will implement method like "makeDefaultColumnOptions" which can every custom type override and add all options this way

mikeSimonson commented 5 hours ago
What is an unsigned boolean ?

mvorisek commented 5 hours ago
MySQL has no boolean data type. It has only TINYINT data type. So I wanted to restrict this data type to UNSIGNED one to prevent at least negative values.

note: the example is simplified, I removed all other unnecessary code, I leaved only the code which return the implicit/forced column option and it should be honored by the diff engine.

from https://github.com/doctrine/migrations/issues/601 - see this thread for more comments

**Comment by UBERPHP** [comment]
what about custom type mediumint?
    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform): string
    {
        return 'MEDIUMINT UNSIGNED';
    }

**Comment by mvorisek** [comment]
The issue is with DOctrine diff, run:
.\doctrine.bat orm:schema-tool:update --dump-sql --force

Run it twice and based on my past testing the command was producing SQL queries to update the schema again and again, but it should update the DB and then produce no SQL queries on the 2nd run.

**Comment by UBERPHP** [comment]
my whole class:
`<?php declare(strict_types=1);

namespace App\Extensions\Doctrine\Types;

use Doctrine\DBAL\ParameterType;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\Type;

/**
 * Type that maps a database MEDIUMINT to a PHP integer.
 */
class MediumIntType extends Type implements PhpIntegerMappingType
{

    /**
     * @const string
     */
    const MEDIUMINT = 'mediumint';

    /**
     * {@inheritdoc}
     */
    public function getName(): string
    {
        return self::MEDIUMINT;
    }

    /**
     * {@inheritdoc}
     */
    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform): string
    {
        return 'MEDIUMINT UNSIGNED';
    }

    /**
     * {@inheritdoc}
     */
    public function convertToPHPValue($value, AbstractPlatform $platform): ?int
    {
        return $value === null ? null : (int)$value;
    }

    /**
     * {@inheritdoc}
     */
    public function getBindingType(): int
    {
        return ParameterType::INTEGER;
    }
}
`
with schema create - everything is ok, but when I'm trying to update or generate diff - it always doing alter for no reason.
Additionally - is I'm changing existing text type field in the database to longtext - diff/update wont detect it and do correction.

**Comment by jurgenbosch** [comment]
@mvorisek @UBERPHP Is there any update on the issue mentioned above? I have a custom type and on each diff the diff is altering the table on the custom type.

**Comment by greg0ire** [comment]
Are you up-to-date? I think https://www.doctrine-project.org/2021/11/26/dbal-3.2.0.html might fix that kind of issues

**Comment by mvorisek** [comment]
closing because of Platform-aware schema comparison (#4746)
