### ISSUE TITLE
What should be done before 2.6.4?

### ISSUE THREAD

**Issue by Nyholm** [doctrine/dbal#3022]
I see the [milestone](https://github.com/doctrine/dbal/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.6.4) is currently empty. 

Is there anything stopping us from releasing 2.6.4 now?

**Comment by Majkl578** [comment]
2.7.0 has been released today.

**Comment by Nyholm** [comment]
Excellent news. Thank you.
