### ISSUE TITLE
Drop Drizzle support for v3.0?

### ISSUE THREAD

**Issue by BenMorel** [doctrine/dbal#3039]
According to [Wikipedia](https://en.wikipedia.org/wiki/Drizzle_(database_server)), Drizzle is an abandoned project.

The latest commit on the [GitHub repo](https://github.com/stewartsmith/drizzle) dates back to 2013, while the [latest version](https://github.com/stewartsmith/drizzle/releases) dates back to 2012.

**Should we drop support for Drizzle in v3?** Now would be a good time to do so.

**Comment by Ocramius** [comment]
👍

**Comment by BenMorel** [comment]
PR opened as #3040
