### ISSUE TITLE
How to query on doctrine `json_array` type

### ISSUE THREAD

**Issue by zion03** [doctrine/dbal#3043]
I'm trying to perform `where` clause on `json_array` in Doctrine which mapped to PostgresSQL 9.6 `jsonb`. 

I'm usning `@>` operator:

    $em->createQuery(
    'SELECT p
    FROM App\Entity\Node p
    WHERE p.categoriesId @> :id'
    )->setParameter('id', 1)->execute();

But to my surprise, I got an error: `Error: Expected =, <, <=, <>, >, >=, !=, got '@'.`

I'm right understand that Doctrine don't support it yet and I need to use some third-party like https://github.com/opsway/doctrine-dbal-postgresql

Even custom function from thus lib looks like strange `CONTAINS(n.categoriesId, :id) = true` and part `= true` is required but not make sense

**Comment by Ocramius** [comment]
You seem to be attempting an ORM DQL query rather than a DBAL  SQL query (start with a `Doctrine\DBAL\Connection` instance)

Try with just DBAL and it should work.

Closing as `invalid` here :-)
