### ISSUE TITLE
Drop support for SQL Server older than 2008

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3052]
The reasons are:
1. SQL Server 2008 is [the oldest officially supported](https://en.wikipedia.org/wiki/Microsoft_SQL_Server#Currently) by Microsoft version.
2. Same is about [AppVeyor](https://www.appveyor.com/docs/services-databases/).
3. Fixing some issues on the older versions (e.g. #3020) requires additional effort if at all possible.

**Comment by Ocramius** [comment]
Handled in #3055
