### ISSUE TITLE
Improve asset caching on AppVeyor

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3057]
According to the [console output](https://ci.appveyor.com/project/doctrine/dbal/build/1.0.10/job/q04lgt5nj66fvoa7), Chocolatey and Composer packages are downloaded for every build:
```
Chocolatey v0.10.8
Installing the following packages:
php
By installing you accept licenses for the packages.
Progress: Downloading vcredist140 14.12.25810... 7%
Progress: Downloading vcredist140 14.12.25810... 22%
Progress: Downloading vcredist140 14.12.25810... 37%
Progress: Downloading vcredist140 14.12.25810... 52%
Progress: Downloading vcredist140 14.12.25810... 67%
Progress: Downloading vcredist140 14.12.25810... 82%
Progress: Downloading vcredist140 14.12.25810... 98%
Progress: Downloading vcredist140 14.12.25810... 100%

---------

[6.6MB/0.00s] Loading composer repositories with package information
[6.8MB/0.25s] Updating dependencies (including require-dev)
[171.5MB/96.48s] Package operations: 43 installs, 0 updates, 0 removals
[171.6MB/96.50s]   - Installing squizlabs/php_codesniffer (3.2.3):
[171.7MB/96.51s] Downloading[171.7MB/97.85s]  (100%)
```
Unless the PR being built changes dependencies, they should be taken from cache.

**Comment by morozov** [comment]
@photodude please take a look if you have time.

**Comment by photodude** [comment]
@morozov cache invalidation on appveyor is an odd thing. See this issue
https://help.appveyor.com/discussions/problems/6049-build-cache-does-nothing

**Comment by morozov** [comment]
It [worked for me](https://ci.appveyor.com/project/morozov/diff-sniffer-core/build/job/360ajpecsv6v75r7) at least for Composer packages and most likely for the Chocolatey as well.

**Comment by photodude** [comment]
@morozov I get the following issue
```sh
Error uploading cache entry to the cache storage: The maximum account cache size of 1,000 MB will be exceeded.
```
https://ci.appveyor.com/project/photodude/dbal/build/job/orai5hqa5v1jq8fs#L1714

So we have too a big of a cache?

**Comment by Majkl578** [comment]
Cache limit for free accounts is 1GB across all projects (whole account): https://www.appveyor.com/docs/build-cache/#cache-size-beta

**Comment by morozov** [comment]
Hm… we can replay the steps from AppVeyor on a Windows VM and see what takes that much. It's unlikely that every build we download a gigabyte of data. Maybe there's something stale in the cache which we don't need.

Besides that, maybe caching C:\PHP72 is not the best idea (even if it's in my example) since this way it'll be never updated once installed.

If we do have that much in the cache, we'll have to decide what we should get rid of (e.g. PHP).
