### ISSUE TITLE
Fate of PDOIbm driver

### ISSUE THREAD

**Issue by Majkl578** [doctrine/dbal#3058]
While working on adding DB2 to our CI stage, I found there are two drivers for DB2: IBMDB2 (ibm_db2 extension) and PDOIbm (pdo_ibm extension).
While the former works and seems to be supported, the latter is not supported by DriverManager, not documented and seems to be completely unused.

Decision should be made about this lonely driver.

**Comment by Ocramius** [comment]
I've never seen this thing being used in the wild: let's kill it for 3.0.0.

Can you integrate it in https://github.com/doctrine/dbal/pull/3055?

**Comment by Majkl578** [comment]
Will do.

Found this in UPGRADE for 2.5:
> The ``pdo_ibm`` driver is buggy and does not work well with Doctrine. Therefore it will no
longer be supported and has been removed from the ``Doctrine\DBAL\DriverManager`` drivers map. It is highly encouraged to to use `ibm_db2` driver instead if you want to connect to an IBM DB2 database as it is much more stable and secure.

So it shouldn't even be a surprising BC break, only remnant from 2.5.

**Comment by Ocramius** [comment]
Handled in #3055
