### ISSUE TITLE
Missing parameter fetchArgument for fetch and fetchAll methods

### ISSUE THREAD

**Issue by akrz** [doctrine/dbal#3066]
If I want to fetch a record and I want to use PDO::FETCH_CLASS, I can't do

```php
$example = $qb->execute()->fetch(\PDO::FETCH_CLASS, Example::class);
```

because the method signature only has one parameter:
```php
# Doctrine\DBAL\Statement
public function fetch($fetchMode = null) {...}
```

The fetchAll method actually has a second parameter in the signature to assign an argument
```php
# Doctrine\DBAL\Statement
public function fetchAll($fetchMode = null, $fetchArgument = 0) {...}
```
But the Interface only has one parameter:
```php
# Doctrine\DBAL\Driver\ResultStatement
public function fetchAll($fetchMode = null);
```
So it throws an annoying warning when I want to use
```php
$example = $qb->execute()->fetchAll(\PDO::FETCH_CLASS, Example::class);
```

The workaround is setting the fetch mode and then do a fetch/fetchAll but it should be possible to pass an argument directly to those methods.
```php
$stmt = $qb->execute();
$stmt->setFetchMode(\PDO::FETCH_CLASS, Example::class);
$example = $stmt->fetch();
```

**Comment by Ocramius** [comment]
@morozov @deeky666 we should really really really disallow the `\PDO::FETCH_CLASS` abomination.

**Comment by akrz** [comment]
@Ocramius Can I ask why?

**Comment by Ocramius** [comment]
@akrz it sets property fields with something inconsistent with reflection behavior, and creates instances by skipping ctor calls as well. If you really want to go in that direction, then you want to use a standard hydrator and avoid the bugs/quirks of PDO, by using something built in userland: even if slower, it is not worth the pain to go with the PDO internals here.

**Comment by morozov** [comment]
Please see https://github.com/doctrine/dbal/pull/2958#issuecomment-355372897 for more details.

**Comment by morozov** [comment]
I'd remove it together with `$columnIndex` for `FETCH_COLUMN` and drop `...$args` entirely.

**Comment by deeky666** [comment]
Not to mention all of those non-PDO drivers not/rarely supporting Class/Object hydration natively. We are currently doing basic "userland" hydration for those drivers just to keep compatibility with our driver API. This is something that should be done outside of DBAL. I wish we could get rid of fetch modes completely and simply provide associative arrays as results and leave everything else for other libraries/userland...

**Comment by mihas2** [comment]
And $cursorOrientation not support, and the "prepare" method does not support the settings of the scrollable cursor


```
    /**
     * {@inheritdoc}
     */
    public function fetch($fetchMode = null, $cursorOrientation = \PDO::FETCH_ORI_NEXT, $cursorOffset = 0)
    {
        return $this->stmt->fetch($fetchMode);
    }
```

**Comment by morozov** [comment]
Closing as the API is no longer supported. See https://github.com/doctrine/dbal/pull/3070.
