### ISSUE TITLE
SchemaException when mssql table has set schema

### ISSUE THREAD

**Issue by Hessuss** [doctrine/dbal#3067]
Hi.
I have a trouble.

I use Symfony 2.8.20, php7.2
in php.ini:
extension=php_pdo_sqlsrv_72_ts
extension=php_sqlsrv_72_ts

config.yml:
```
doctrine:
    dbal:    
        #driver: pdo_mysql
        driver:     pdo_sqlsrv
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

```
when i set entity like this :

```
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="tbl_admin_parameters")
 */
```
Everything is fine. 
The system  creates table "dbo.tbl administrator parameters" I can modify the entity and use them.

but i must set different table schema than DBO.

when i set it like this :
```
/**
 * @ORM\Entity
 * @ORM\Table(name="tbl_admin_parameters", schema="B2B")
 */
```
nothing happens, table still in dbo schema.

but when i set entity like this :
```
/**
 * @ORM\Entity
 * @ORM\Table(name="B2B.tbl_admin_parameters", schema="B2B")
 */
```
and run "php ./app/console doctrine:schema:update --force"
system create table in B2B schema :) but when i run the comman again system show me an error:

> [Doctrine\DBAL\Schema\SchemaException]
>   The table with name 'bi_demo2.tbl_admin_parameters' already exists.

bi_demo2 is the name of database. Doctrine should do "ALTER" command if need but i think it try do "CREATE TABLE"

What i do wrong? or it is doctrine bug?

**Comment by Ocramius** [comment]
@Hessuss what version of ORM/DBAL is this running on?

**Comment by Hessuss** [comment]
doctrine/annotations                 v1.2.7        Docblock Annotations Parser
doctrine/cache                       v1.5.4        Caching library offering an object-oriented API for man...
doctrine/collections                 v1.3.0        Collections Abstraction library
doctrine/common                      v2.5.3        Common Library for Doctrine projects
doctrine/dbal                        v2.4.5        Database Abstraction Layer
doctrine/doctrine-bundle             1.6.4         Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.2         Symfony Bundle for Doctrine Cache
doctrine/inflector                   v1.1.0        Common String Manipulations with regard to casing and s...
doctrine/lexer                       v1.0.1        Base library for a lexer that can be used in Top-Down, ...
doctrine/orm                         v2.4.8        Object-Relational-Mapper for PHP

**Comment by Ocramius** [comment]
That's running on some extremely old dependencies: please do upgrade to ORM and DBAL 2.6.x first.

**Comment by Hessuss** [comment]
I am sorry, I thought that symfony after updating the "composer update" command updates everything to the newest version. I made an update to version 2.6.3.

Still error :/
composer show -i

```
doctrine/annotations                 v1.6.0  Docblock Annotations Parser
doctrine/cache                       v1.7.1  Caching library offering an object-oriented API for many cach...
doctrine/collections                 v1.5.0  Collections Abstraction library
doctrine/common                      v2.8.1  Common Library for Doctrine projects
doctrine/dbal                        v2.6.3  Database Abstraction Layer
doctrine/doctrine-bundle             1.8.1   Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.2   Symfony Bundle for Doctrine Cache
doctrine/inflector                   v1.3.0  Common String Manipulations with regard to casing and singula...
doctrine/lexer                       v1.0.1  Base library for a lexer that can be used in Top-Down, Recurs...
doctrine/orm                         v2.4.8  Object-Relational-Mapper for PHP
incenteev/composer-parameter-handler v2.1.3  Composer script handling your ignored parameter file
ircmaxell/password-compat            v1.0.4  A compatibility library for the proposed simplified password ...
jdorn/sql-formatter                  v1.2.17 a PHP SQL highlighting library
monolog/monolog                      1.23.0  Sends your logs to files, sockets, inboxes, databases and var...
paragonie/random_compat              v2.0.11 PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
psr/log                              1.0.2   Common interface for logging libraries
sensio/distribution-bundle           v4.0.39 Base bundle for Symfony Distributions
sensio/framework-extra-bundle        v3.0.29 This bundle provides a way to configure your controllers with...
sensio/generator-bundle              v3.1.7  This bundle generates code for you
sensiolabs/security-checker          v3.0.7  A security checker for your composer.lock
swiftmailer/swiftmailer              v5.4.9  Swiftmailer, free feature-rich PHP mailer
symfony/monolog-bundle               v3.2.0  Symfony MonologBundle
symfony/phpunit-bridge               v2.8.36 Symfony PHPUnit Bridge
symfony/polyfill-apcu                v1.7.0  Symfony polyfill backporting apcu_* functions to lower PHP ve...
symfony/polyfill-intl-icu            v1.7.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring            v1.7.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54               v1.7.0  Symfony polyfill backporting some PHP 5.4+ features to lower ...
symfony/polyfill-php55               v1.7.0  Symfony polyfill backporting some PHP 5.5+ features to lower ...
symfony/polyfill-php56               v1.7.0  Symfony polyfill backporting some PHP 5.6+ features to lower ...
symfony/polyfill-php70               v1.7.0  Symfony polyfill backporting some PHP 7.0+ features to lower ...
symfony/polyfill-util                v1.7.0  Symfony utilities for portability of PHP codes
symfony/security-acl                 v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle           v2.6.7  Symfony SwiftmailerBundle
symfony/symfony                      v2.8.36 The Symfony PHP framework
twig/twig                            v2.4.7  Twig, the flexible, fast, and secure template language for PHP
```
when entity set : 
```
/**
 * @ORM\Entity
 * @ORM\Table(name="tbl_admin_parameters", schema="B2B")
 */
```

still generate "dbo.tbl_admin_parameters"

when entity set like this : 
```
/**
 * @ORM\Entity
 * @ORM\Table(name="B2B.tbl_admin_parameters", schema="B2B")
 */
```

i see this errors:

> Updating database schema...
>
>
> [Doctrine\DBAL\DBALException]
>  An exception occurred while executing 'CREATE TABLE B2B.tbl_admin_parameters (id INT IDENTITY NOT NULL, name
> NVARCHAR(255) NOT NULL, parameter NVARCHAR(255), description NVARCHAR(255), PRIMARY KEY (id))':
>
> SQLSTATE[42S01]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]There is already an object named 'tbl_ admin_parameters' in the database.
>
>
>
>  [Doctrine\DBAL\Driver\PDOException]
>  SQLSTATE[42S01]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]There is already an object named 'tbl_admin_parameters' in the database.
>
>
>
>  [PDOException]
>  SQLSTATE[42S01]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]There is already an object named 'tbl_admin_parameters' in the database.

**Comment by Ocramius** [comment]
Ah, at least it's creating things in the correct DB now. This is normal behavior though, as the ORM will only introspect the default schema for the DB you are connected to, while all other schema are ignored.

**Comment by Hessuss** [comment]
Earlier he also created tables in the proper database.

You say it's work fine, ok, but for what is "schema='schema_name'" : 
[http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#annref-table](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/annotations-reference.html#annref-table)

```<?php
/**
 * @Entity
 * @Table(name="user",
 *      uniqueConstraints={@UniqueConstraint(name="user_unique",columns={"username"})},
 *      indexes={@Index(name="user_idx", columns={"email"})}
 *      schema="schema_name"
 * )
 */
class User { }
```
it doesn't work

What if I have two or more schema in one database? How can I work with them?

Please help :)

**Comment by morozov** [comment]
Closing as stale.
