### ISSUE TITLE
testSettingUnknownOptionIsStillSupported() is reported as risky.

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3075]
In some cases, [`testSettingUnknownOptionIsStillSupported()` is reported as risky](https://ci.appveyor.com/project/doctrine/dbal/build/1.0.81/job/utt2h7bq2p2b5jj7#L239):

> There was 1 risky test:
> 1) Doctrine\Tests\DBAL\Schema\ColumnTest::testSettingUnknownOptionIsStillSupported
> This test did not perform any assertions
> ...
> Legacy deprecation notices (1)

**Comment by morozov** [comment]
@greg0ire, mind taking a look?

**Comment by greg0ire** [comment]
AFK this we, but I can try it from my phone :P

**Comment by Majkl578** [comment]
Should be fixed by #3090 + #3095.
