### ISSUE TITLE
collate gets suffix '_unicode_ci' which is bad for latin1

### ISSUE THREAD

**Issue by dominikzogg** [doctrine/dbal#3081]
If there is not 'collate' defined the suffix '_unicode_ci' gets added which breaks everything which is not utf8 related.

https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L513

**Comment by morozov** [comment]
Fixed in https://github.com/doctrine/dbal/pull/4644.
