### ISSUE TITLE
2.7 breaks renaming columns in mysql 5.7

### ISSUE THREAD

**Issue by ashgibson** [doctrine/dbal#3091]
I am using this package with latest version of Laravel (5.6.15) and my migrations have started breaking when using $table->renameColumn().

It looks like when I try and rename a nullable column the sql that is generated adds not null. It is also not including UNSIGNED for unsigned integers.

**Comment by ashgibson** [comment]
2.7.0

**Comment by ajoy39** [comment]
+1 on this issue, running Laravel migrations that rename columns with doctrine/dbal 2.7 generates the following error:

``
  SQLSTATE[0A000]: Feature not supported: 1846 ALGORITHM=COPY is not supported. Reason: Columns participating in a fore
  ign key are renamed. Try ALGORITHM=INPLACE. (SQL: ALTER TABLE watchlist CHANGE user_id watchlist_id INT NOT NULL)
``

Downgrading to 2.6.3 allows me to run migrations again

**Comment by morozov** [comment]
@ajoy39 please try reducing the test to DBAL-only. You can debug the Laravel app and see what calls it makes to Doctrine. AFAIK, no one of the maintainers uses Laravel.

**Comment by jarnovanleeuwen** [comment]
+1

Since 2.7 `unsigned` is dropped when renaming an integer column, causing failure due to mismatching foreign key columns.

**Comment by ajoy39** [comment]
2.7.1 also fixed this for me

**Comment by Majkl578** [comment]
Ok, thanks for the info. This was likely fixed by #3089 (assuming you are using the `unsigned=true` option).
Closing it here then. :+1:
