### ISSUE TITLE
When updating to version v2.7 type DateInterval throws errors

### ISSUE THREAD

**Issue by fnagel** [doctrine/dbal#3093]
When using doctrine/dbal with Symfony, the following error is thrown after updating from 2.6.3 to 2.7.0:

```
Could not convert database value "P00Y00M07DT00H00M00S" to Doctrine Type dateinterval. Expected format: %RP%YY%MM%DDT%HH%IM%SS
```

Using `"doctrine/dbal": "2.6.*"` fixes this. Is this a usage issue or a bug?

**Comment by morozov** [comment]
@fnagel what database does this happen on? Could you provide an isolated reproduction scenario? On its own, the error message may not be really helpful.

**Comment by fnagel** [comment]
Wow! That's a lightning fast response time :-D

I'm using MySQL 5.7.19 with Symfony 3.3.16. I will try to come up with a isolated test case asap. Is there something I could build upon? Or is a minimal Symfony project suitable?

**Comment by morozov** [comment]
Ideally, it should be built w/o any external dependencies. Just DBAL. Something like https://github.com/doctrine/dbal/issues/2848#issuecomment-379109082.

**Comment by Majkl578** [comment]
Hmm, this is because after #2579 DateIntervalType always expects a sign, which is not there for pre-2.7 records.

**Comment by Majkl578** [comment]
@fnagel Could you please try with #3097?

**Comment by fnagel** [comment]
Just tested 2.71 -- everything works again as expected. Thanks a lot for your fast response! <3
