### ISSUE TITLE
SQLServer [ PDO_STR | PDO_INPUT_OUTPUT ] -> Invalid parameter type: 2147483650

### ISSUE THREAD

**Issue by jstolp** [doctrine/dbal#3101]
Hello Doctrine / DBAL team,

First of all GREAT WORK! I Love this piece of software.

But i'm facing a challenge in the following piece of code:

`
        // Create query from the declared parameter arrays
        $allParameters = array_merge($inputParameters, $outputParameters);
        $placeholders = ':' . join(',:', array_keys($allParameters));
        $query = "EXEC {$storedProcedure} {$placeholders}";
        $pdo = $connection->getPdo();
        $stmt = $pdo->prepare($query);

        // Bind all input parameters to the prepared query
        foreach ($inputParameters as $name => $value) {
            $stmt->bindValue($name, $value);
        }

        // Bind all output parameters to the prepared query
        $returnedOutputParameters = [];
        foreach ($outputParameters as $name => $record) {
            // Get type of parameter
            $stmt->bindParam($name, $returnedOutputParameters[$name], PDO::PARAM_STR | PDO::PARAM_INPUT_OUTPUT, 2048);
            // InvalidArgumentException: Invalid parameter type: 2147483650         }

        // Execute stored procedure and fetch all records
        try {
            $stmt->execute();
        } catch (Exception $ex) {
            return ['message' => $ex->getMessage()];
        }
`
This cause an exception in my code.
Although the PDO docs say you can use the bitwise or ("|") to add PDO_STR | PDO_INPUT_OUTPUT
// via  http://php.net/manual/en/pdo.constants.php
`
There was 1 error:

1) App\Tests\ServiceLayerGetAbilitiesTest::testGetInvalidAbility
InvalidArgumentException: Invalid parameter type: 2147483650

/var/www/projectX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:216
/var/www/projectX/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:109
/var/www/projectX/app/Connectors/projectXEndpoint/projectXEndpointClient.php:146
`

I'm curious why this doesn't work.

What i did is upgrade all dependencies using composer. 

We went from Laravel 5.4 to Laravel 5.6
PHP Version is 7.1.x
Database is MSSQL Server ( 2012 / 2016 )
Doctrine/DBAL version 2.7.1

Composer JSON (snip):

```
....
	"require": {
		"php": "^7.1.3",
		"ext-mbstring": "*",
		"ext-openssl": "*",
		"doctrine/dbal": "2.7.0",
		"fideloper/proxy": "~4.0",
		"guzzlehttp/guzzle": "^6.3",
		"kmelia/monolog-stdout-handler": "^1.2",
		"laravel-doctrine/orm": "~1.4",
		"laravel/envoy": "~1.0",
		"laravel/framework": "5.6.*",
		"laravel/tinker": "^1.0",
		"predis/predis": "^1.1",
		"symfony/console": "~4.0",
		"sentry/sentry-laravel": "^0.7.0"
	},
	"require-dev": {
		"flow/jsonpath": "^0.3.4",
		"fzaninotto/faker": "^1.4",
		"jakub-onderka/php-parallel-lint": "^0.9.2",
		"mayflower/php-codebrowser": "^1.1",
		"mockery/mockery": "^1.0",
		"nikic/php-parser": "^3.1",
		"pdepend/pdepend": "~2.0",
		"phploc/phploc": "~4.0",
		"phpmd/phpmd": "^2.6",
		"phpro/grumphp": "~0.14",
		"phpunit/php-timer": "*",
		"phpunit/phpunit": "^7.0",
		"pyrech/composer-changelogs": "^1.6",
		"sebastian/phpcpd": "~4.0",
		"sebastian/version": "^2.0",
		"sensiolabs/security-checker": "^4.1",
		"squizlabs/php_codesniffer": "2.*",
		"symfony/css-selector": "~4.0",
		"symfony/dom-crawler": "~4.0"
	}
 ....
```

If you need more info just shout. any help is appreciated.

**Comment by Majkl578** [comment]
You composer.json shows fixed dependency on 2.7.0 `"doctrine/dbal": "2.7.0"` although you are mentioning 2.7.1.
The bug you are facing was present in 2.7.0 and was fixed in 2.7.1. Please make sure you are really using 2.7.1 (and set dependency in composer.json to `^2.7.1`), the exception has been changed to deprecation only.

**Comment by jstolp** [comment]
Thanks Michael, I'll try it out in a bit and let you know if this fixes my
issue.
We'll close it for future reference for developers.

**Comment by jstolp** [comment]
For all developers in the future.
This fixed the issue... **https://github.com/doctrine/dbal/releases/tag/v2.7.1**

Composer.json

```
	"doctrine/dbal": "~2.7"
```

Update, and done!

Thanks Michael
