### ISSUE TITLE
Don't use the server_version option to define the vendor name

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/dbal#3110]
In this comment: https://github.com/doctrine/dbal/issues/2985#issuecomment-378595588 you can see that when using MariaDB, the `server_version` option must include not only the version number but also the vendor name: `server_version: 'mariadb-10.2.12'` instead of `server_version: '10.2.12'`.

I wonder if this could be solved differently to keep the vendor name out of the `server_version` value. Thanks for your time and consideration!

**Comment by javiereguiluz** [comment]
I don't use MariaDB (maybe @tristanbes, the original issue reporter, can help us here) but it looks like the version returned by MariaDB follows a different format. According to their official docs (https://mariadb.com/kb/en/library/version/) it would be something like this: `10.0.3-MariaDB-1~precise-log`

**Comment by tristanbes** [comment]
I confirm that the format is different:
Connecting to the database via the cli gives something like:  
`Server version: 10.2.14-MariaDB-10.2.14+maria~stretch-log mariadb.org binary distribution`

**Comment by belgattitude** [comment]
For the full story: read the first paragraph in #2825 about the mariadb version detection.

MariaDB server returns the version with their vendor name (+ some prefixes or suffixes are added per distributions to handle some replications issues). Their clients 'libmariadb-client', connector/j'... will trip the vendors and prefixes transparently... In other words if you're using jdbc or php compiled with libmariadb-client, you won't see the 'mariadb' vendor. 

Some tentatives have been done to strip it in the php src too (like https://github.com/php/php-src/pull/1767... or others I cannot find anymore). But till now we need to strip the prefix in userland.

In DBAL, it's done here:

https://github.com/doctrine/dbal/blob/8392c26573c0a3eb0ff0bb421053b7b7249bc90c/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php#L167
And the corresponding test file:
https://github.com/doctrine/dbal/blob/8392c26573c0a3eb0ff0bb421053b7b7249bc90c/tests/Doctrine/Tests/DBAL/Driver/AbstractMySQLDriverTest.php#L67

**Comment by belgattitude** [comment]
I like the idea of @ocramius

> What can be done is allowing selection of the platform via class name (I think that might already be possible, jus didn't check).

@javiereguiluz do you think it would be ok ?

**Comment by morozov** [comment]
> What can be done is allowing selection of the platform via class name (I think that might already be possible, jus didn't check).

Passing a platform is already possible:
https://github.com/doctrine/dbal/blob/d3c708102614d556b4db38d1cae84441772d55f1/src/Connection.php#L175-L181
