### ISSUE TITLE
MasterSlaveConnection::ping() does't work, it throws PDOException

### ISSUE THREAD

**Issue by fredeastside** [doctrine/dbal#3118]
Hi,

When I use ```MasterSlaveConnection::ping()``` it doesn't work correctly. The problem's in custom ```MasterSlaveConnection::query()``` method. Now there don't exist block try-catch and line ```$statement->setFetchMode($this->defaultFetchMode);```. A script falls down with PDOException when execute ```SELECT 1``` query. Actually, this method has one different line ```$this->connect('master');``` and it could be work with these lines of code. But it seems like copy-paste

Doctrine\DBAL\Connection:
```php
/**
 * Executes an SQL statement, returning a result set as a Statement object.
 *
 * @return \Doctrine\DBAL\Driver\Statement
 *
 * @throws \Doctrine\DBAL\DBALException
 */
public function query()
{
    $this->connect();

    $args = func_get_args();

    $logger = $this->_config->getSQLLogger();
    if ($logger) {
        $logger->startQuery($args[0]);
    }

    try {
        $statement = $this->_conn->query(...$args);
    } catch (Exception $ex) {
        throw DBALException::driverExceptionDuringQuery($this->_driver, $ex, $args[0]);
    }

    $statement->setFetchMode($this->defaultFetchMode);

    if ($logger) {
        $logger->stopQuery();
    }

    return $statement;
}
```

Doctrine\DBAL\Connections\MasterSlaveConnection:
```php
/**
 * {@inheritDoc}
 */
public function query()
{
    $this->connect('master');

    $args = func_get_args();

    $logger = $this->getConfiguration()->getSQLLogger();
    if ($logger) {
        $logger->startQuery($args[0]);
    }

    $statement = $this->_conn->query(...$args);

    if ($logger) {
        $logger->stopQuery();
    }

    return $statement;
}
```

**Comment by morozov** [comment]
@fredeastside please feel free to provide a pull request with a fix and a test for it.

**Comment by greg0ire** [comment]
> But it seems like copy-paste

That's a bit weird indeed… it's like that since e7d6fc2cf6b1393b1a8095465f5909c3ccaf3a7e , but I cannot find an explanation with that commit.

**Comment by greg0ire** [comment]
Also, duplicates #2769 ?

**Comment by morozov** [comment]
Irrelevant as of https://github.com/doctrine/dbal/pull/4128.
