### ISSUE TITLE
The semantics of the GUID expression is inconsistent across platforms

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3167]
|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.7.1

#### Summary

As a developer, I expect the GUID expression generated by `AbstractPlatform::getGuidExpression()` to have the same semantic (namely, [UUIDv1](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_(date-time_and_MAC_address))) across supported platforms.

#### Current behavior

1. On MySQL platform, it's implemented as `UUID()` which generates UUIDv1 and is therefore correct.
2. On PostgreSQL platform, it's implemented it as `UUID_GENERATE_V4()` which generates UUIDv4. For some reason, `UUID_GENERATE_V1()` is [unavailable](https://travis-ci.org/doctrine/dbal/jobs/384203956#L663) on Travis CI:
   > SQLSTATE[42883]: Undefined function: 7 ERROR:  function uuid_generate_v1() does not exist
3. On Oracle platform, it's implemented as `SYS_GUID()` which returns `RAW(16)` which is not a UUID [according to Stackoverflow](https://stackoverflow.com/a/3037511/146187).
4. On SQL Server and SQLAnywhere, it's implemented as `NEWID()`. From the [documentation](https://docs.microsoft.com/en-us/sql/t-sql/functions/newid-transact-sql?view=sql-server-2017), it's not clear which UUID version it generates, but according to the [test output](https://travis-ci.org/doctrine/dbal/jobs/384203968#L1035), it's not UUIDv1:
   > Failed asserting that 'DBB4D428-2338-4D4F-823F-4AA2ECEC985A' is greater than 'F4959EE5-02EC-4136-A21F-211813F67B63'
5. On SQLite, it's implemented using purely `RANDOMBLOB()` which makes it not compliant with the the UUIDv1 definition.

There's also a [summary](https://en.wikipedia.org/wiki/Universally_unique_identifier#As_database_keys) of the above on Wikipedia.

#### How to reproduce

Below is the pseudo-code. See a real example in [#3162](https://github.com/doctrine/dbal/pull/3162/files#diff-fe3cbd6e714521d88bd0e81b269c7863R26).

```php
$previous = generateGuid();

for ($i = 0; $i < 99; $i++) {
    $value = generateGuid();
    self::assertGreaterThan($previous, $value);
    $previous = $value;
}
```

#### Expected behavior

All implementations generate UUIDv1 which looks impossible. Given the current state of the feature, would it make sense to deprecate it and encourage users to use application-generated UUIDs?

**Comment by Majkl578** [comment]
Handled in #3211 and #3212.
