### ISSUE TITLE
PostgreSQL check constraint requires redundant "CHECK" in the statement

### ISSUE THREAD

**Issue by msheakoski** [doctrine/dbal#3168]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.7.1

#### Summary

When adding a check constraint for PostgreSQL, the insertion of the "CHECK" SQL keyword should be automatically handled by PostgreSqlPlatform. [SQLServerPlatform](https://github.com/doctrine/dbal/blob/f4f987d72549dfa43bd2d129a2e274d8e4196686/lib/Doctrine/DBAL/Platforms/SQLServerPlatform.php#L301) and [SQLAnywherePlatform](https://github.com/doctrine/dbal/blob/f4f987d72549dfa43bd2d129a2e274d8e4196686/lib/Doctrine/DBAL/Platforms/SQLAnywherePlatform.php#L1275) do this in a similar way.

#### Current behavior

In order to add a check constraint that generates valid SQL, it needs to include the CHECK keyword:
```php
$table->addColumn("username", "text", ["check" => "CHECK (username != 'example')"]);
```
Having to include CHECK is not only redundant, it can result in difficult to diagnose errors because it is not obvious that you need to include it.

#### Expected behavior

You should be able to specify the check constraint with both the CHECK keyword and parentheses being optional:
```php
$table->addColumn("username", "text", ["check" => "username != 'example'"]);
```
This can be done in a way that preserves backwards compatibility:
```php
if (!preg_match('/\Acheck\b/i', $sql)) {
    $sql = "CHECK ($sql)";
}
```
This will handle the constraint being specified as:
* `CHECK (username != 'example')`
* `(username != 'example')`
* `username != 'example'`

If parentheses were already present, wrapping them in another set of parentheses won't hurt anything.

**Comment by morozov** [comment]
It's not really a bug but rather a poorly designed API. Fixing it at this point would be a BC break. Feel free to PR, if interested.
