### ISSUE TITLE
DBAL type "date" gets saved as "datetime" in database

### ISSUE THREAD

**Issue by MichaelBelgium** [doctrine/dbal#3171]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | Probably
| Version     | 2.5.13

#### Summary

(from https://github.com/doctrine/migrations/issues/708)

I don't think this is the purpose?
The point is, when making a migration and you add a column with type "date" (`Doctrine\DBAL\Types\Type::DATE`) the type in the database is **datetime**

The MySQL version i use is 5.7 and as far as i know it [does](https://dev.mysql.com/doc/refman/5.7/en/datetime.html) support the date type. 
PHP version I use is 7.0

#### Current behavior

When creating a table with a column that has the type date, in the database it will be a datetime

#### How to reproduce

* Generate a migration
* Create a table
* Add a column to the table with type date
```PHP
    public function up(Schema $schema)
    {
        // example i used
        $table = $schema->createTable(self::TABLE);

        $table->addColumn('id',Type::INTEGER)->setAutoincrement(true);
        $table->addColumn('datum', Type::DATE);

        $table->setPrimaryKey(['id']);
    }
```
* Execute migration
* Check on the mysql server the columns of the table and realize it's a datetime field instead of a date field
```
+-------+----------+------+-----+---------+----------------+
| Field | Type     | Null | Key | Default | Extra          |
+-------+----------+------+-----+---------+----------------+
| id    | int(11)  | NO   | PRI | NULL    | auto_increment |
| datum | datetime | NO   |     | NULL    |                |
+-------+----------+------+-----+---------+----------------+
```

#### Expected behavior

This table:
```
+-------+---------+------+-----+---------+----------------+
| Field | Type    | Null | Key | Default | Extra          |
+-------+---------+------+-----+---------+----------------+
| id    | int(11) | NO   | PRI | NULL    | auto_increment |
| datum | date    | NO   |     | NULL    |                |
+-------+---------+------+-----+---------+----------------+
```

**Comment by Majkl578** [comment]
This is strange:

https://github.com/doctrine/dbal/blob/11037b4352c008373561dc6fc836834eed80c3b5/lib/Doctrine/DBAL/Types/DateType.php#L39-L45

https://github.com/doctrine/dbal/blob/11037b4352c008373561dc6fc836834eed80c3b5/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L304-L310

It hasn't been changed for ages.

Can you dump `Type::getType('date')` in your migration and check whether the type is correct (DateType) and not i.e. overriden?

**Comment by MichaelBelgium** [comment]
> Can you dump Type::getType('date') in your migration and check whether the type is correct (DateType) and not i.e. overriden?

Yeah alright. Its our mistake, it indeed gets overriden somewhere deep in our code which I didn't realize.
Sorry to bother 😛
