### ISSUE TITLE
Doctrine migrations keeps doing the same database change over and over again

### ISSUE THREAD

**Issue by hackzilla** [doctrine/dbal#3177]
|    Q        |   A
|------------ | -----
| DBAL Version     | 2.7.1
| Migration Version     | 1.7.2

### Support Question

every time I do a migration diff I get the same change, regardless of how many times I apply it.

originally raised at https://github.com/doctrine/migrations/issues/728

an example migration that is failing:

```SQL
ALTER TABLE project CHANGE id id CHAR(36) NOT NULL COMMENT '(DC2Type:uuid)'
```

After have a look around, the issue appears to be that the information_schema.STATISTICS doesn't include any comments.

```
TABLE_CATALOG	TABLE_SCHEMA	TABLE_NAME	NON_UNIQUE	INDEX_SCHEMA	INDEX_NAME	SEQ_IN_INDEX	COLUMN_NAME	COLLATION	CARDINALITY	SUB_PART	PACKED	NULLABLE	INDEX_TYPE	COMMENT	INDEX_COMMENT
def	my-table	project	0	my-table	PRIMARY	1	id	A	1	NULL	NULL		BTREE		
```

But when I do a describe, they do.

```
SHOW FULL COLUMNS FROM  `project`;

Field	Type	Collation	Null	Key	Default	Extra	Privileges	Comment
id	char(36)	utf8mb4_unicode_ci	NO	PRI	NULL		select,insert,update,references	(DC2Type:uuid)
```

 I am using Mysql 5.7.22 and I'm hoping you can point me in the right direction.

**Comment by hackzilla** [comment]
I tracked the code down to ```/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php``` and ```public function getListTableIndexesSQL($table, $currentDatabase = null)```

However, I can see it hasn't changed in the last 7 years.
So the issue must be with MySQL, and something they've changed in last few months.

**Comment by morozov** [comment]
@hackzilla could you provide more details of the schema you're trying to manage? Specifically,
1. Where does the `uuid` type come from?
2. How is the issue related to indices?
3. How is the `my-table` table related to the `project`?

**Comment by morozov** [comment]
Closing as stale.
