### ISSUE TITLE
Auto-convert DateTime to DateTimeImmutable in DateTimeImmutableType::convertToDatabaseValue

### ISSUE THREAD

**Issue by alterphp** [doctrine/dbal#3185]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I am slowly migrating to the use of DateTimeImmutable insteadof DateTime (more reliable as returning a new instance when modified). My backoffice legacy DateTimeType form handles DateTime... So the basic mapping between form and entities (Symfony magic way of coding) tries to set a DateTime in the datetime_immutable DBAL field...

`Could not convert PHP value of type 'DateTime' to type 'datetime_immutable'. Expected one of the following types: null, DateTimeImmutable`

I think that converting automatically DateTime to DateTimeImmutable in that case would be a great help to the migration. Do you see any drawback ?

PHP ensures the conversion with DateTimeImmutable::createFromMutable (http://php.net/manual/fr/datetimeimmutable.createfrommutable.php).

**Comment by Ocramius** [comment]
> I think that converting automatically DateTime to DateTimeImmutable in that case would be a great help to the migration. Do you see any drawback ?

Yes: lack of strictness. If a `DateTime` unexpectedly makes it into a system, we want to know about it, and it needs to be loud. If you want something more graceful that helps you during the migration, I strongly encourage you to write a custom type that is active until you are through with the change.

**Comment by alterphp** [comment]
Ok, I expected this relevant answer :-)

I will convert on my side..
