### ISSUE TITLE
PDO exception on version 2.7.1

### ISSUE THREAD

**Issue by evannamonpinion** [doctrine/dbal#3186]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.7.1

#### Summary

getting the error SQLSTATE[HY000]: General error: PDO::ATTR_STATEMENT_CLASS requires format array(classname, ... even tho ive already updated my php to 7.2 and php7.2-fpm, im using laravel 5.5.*, i can't roll back to dbal 2.6.3 , because some of my dependecies were using the doctrine/dbal 2.7.1

#### Current behavior

Im getting  a PDO error when trying to call my API

#### How to reproduce

It was working on my local mac, with php 7.1, mysql 5.7 but on my live server, ubuntu 16.04, php 7.2 , mysql 5.7(AWS RDS), so i can't really tell how to reproduce this.

**Comment by morozov** [comment]
@evannamonpinion according to the source code, the statement class is always passed in correct format:
```
↪ git grep 'PDO::ATTR_STATEMENT_CLASS'
lib/Doctrine/DBAL/Driver/PDOConnection.php:        $this->setAttribute(PDO::ATTR_STATEMENT_CLASS, ['Doctrine\DBAL\Driver\PDOStatement', []]);
lib/Doctrine/DBAL/Driver/PDOSqlsrv/Connection.php: $this->setAttribute(\PDO::ATTR_STATEMENT_CLASS, [Statement::class, []]);
```

Without the code the steps to reproduce thie issue, I'm afraid we won't be able to fix it.

Could you provide the full error message and if possible the stack trace?

**Comment by morozov** [comment]
@evannamonpinion a "syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)" at
https://github.com/doctrine/dbal/blob/11037b4352c008373561dc6fc836834eed80c3b5/lib/Doctrine/DBAL/Driver/PDOStatement.php#L40
means you're using an incompatible PHP version (presumably PHP 5).

**Comment by evannamonpinion** [comment]
thats weird, im already using php7.2, there is 7.0 and php 7.2, and when i type php -v, this is what i getPHP 7.2.6-1+ubuntu16.04.1+deb.sury.org+1 (cli)

**Comment by morozov** [comment]
@evannamonpinion are you getting the reported errors in CLI or via the web API? The versions of PHP used by CLI and a web server may be different. Please check the version used where you see the error.

**Comment by evannamonpinion** [comment]
on the web api and since im using laravel , i looked upon laravel logs, and this is what the stacktrace is, i checked the server's version and its using 7.2, i haven't solve this yet but thank you for answering my questions. Ill get back on this once i've solved this.

**Comment by evannamonpinion** [comment]
@morozov you where right my apache2 was using a different version of php, here is the fix we've found, 
https://websiteforstudents.com/how-to-run-apache2-with-php7-2-fpm-on-ubuntu-16-04-17-10-18-04/
,THANK YOU
