### ISSUE TITLE
Simpler & shorter syntax for positional parameters

### ISSUE THREAD

**Issue by jkufner** [doctrine/dbal#3191]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

### Summary

Current syntax for simple positional parameters is way too verbose and unplesant. Let's make it shorter and more readable.

#### Current syntax

`````php
$queryBuilder = $dbal->createQueryBuilder();
$result = $queryBuilder
    ->select('id', 'name')
    ->from('users')
    ->where('email = ' .  $queryBuilder->createPositionalParameter($userInputEmail))
    ->where('lastLogin BETWEEN ' .  $queryBuilder->createPositionalParameter($minLastLoginDate) . ' AND ' . $queryBuilder->createPositionalParameter($maxLastLoginDate))
    ->execute();
`````

It is very verbose and SQL query is getting lost between parameters.

#### Another current syntax

`````php
$result = $dbal->createQueryBuilder()
    ->select('id', 'name')
    ->from('users')
    ->where('email = ?')
    ->setParameter(0, $userInputEmail)
    ->where('lastLogin BETWEEN ? AND ?')
    ->setParameter(1, $minLastLoginDate)
    ->setParameter(2, $maxLastLoginDate)
    ->execute();
`````

This syntax is easier to read as the parameters are not mixed with SQL, but we need the `$queryBuilder` variable and keep track of parameter positions/names.

#### New syntax

`````php
$result = $dbal->createQueryBuilder()
    ->select('id', 'name')
    ->from('users')
    ->where('email = ?')->addParameter($userInputEmail)
    ->where('lastLogin BETWEEN ? AND ?')->addParameters($minLastLoginDate, $maxLastLoginDate)
    ->execute();
`````

- There is no need to store the query builder in the variable, as the `addParameter()` method is chained like any other builder method.
- No need to know the placeholder number/name.
- No conflict with existing API.
- Only two new methods `addParameters($values...)` and `addParameter($value, $type = null)`. The plural form is equivalent to multiple calls of the the singular form with no `$type` argument.
- The logic is exactly the same as of `createPositionalParameter()`.

**Comment by morozov** [comment]
The new syntax doesn't look much different from the another current syntax. If tracking parameter numbers is a problem, it could be worked around as:
```php
$i = 0;

$result = $dbal->createQueryBuilder()
    ->select('id', 'name')
    ->from('users')
    ->where('email = ?')
        ->setParameter($i++, $userInputEmail)
    ->where('lastLogin BETWEEN ? AND ?')
        ->setParameter($i++, $minLastLoginDate)
        ->setParameter($i++, $maxLastLoginDate)
    ->execute();
```
The greater problem which I'd like to get solved is that the parameters get bound to the query at the build time but the actual order is determined in the SQL compile time. For instance:
```php
$builder = $conn->createQueryBuilder();
$builder
    ->from('table')
    ->where('bar = ' . $builder->createPositionalParameter('bar'))
    ->select($builder->createPositionalParameter('foo') . ' foo');
```
Instead of the expected:
```sql
SELECT 'foo' AS foo FROM table WHERE bar = 'bar '
```
You'll get:
```sql
SELECT 'bar' AS foo FROM table WHERE bar = 'foo'
```
How does the new API guarantee that the `addParameter()` gets applied to the preceeding part which declares them? If not, it still allows shooting in the foot by confusing the number of declared and bound parameters for a given part.

**Comment by jkufner** [comment]
> How does the new API guarantee that the addParameter() gets applied to the preceeding part which declares them?

It does not. It behaves exactly the same as `createPositionalParameter()`. No change here.

**Comment by morozov** [comment]
> To solve the issue, it is necessary to keep track of which positional parameter belongs to which expression, and then concatenate them in the same order.

Yes. The proper syntax should declare the SQL part with placeholders and the variables bound to them as a single whole to let the parameters be bound to the underlying statement in the correct order.

**Comment by morozov** [comment]
Closing as stale.
