### ISSUE TITLE
Ability to call setFilterSchemaAssetsExpression multiple times (or create an array of FilterSchema expressions)

### ISSUE THREAD

**Issue by mmucklo** [doctrine/dbal#3196]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

First thanks for all the hard work on this core library.  It's been fantastic to have something like this to use.

I'm presently maintaining a symfony bundle that allows people to use either Doctrine ORM or ODM as their datastore, as well as other options [(DtcQueueBundle)](https://github.com/mmucklo/DtcQueueBundle).  One of the requests has been if people don't use ORM, then the Doctrine Migrator shouldn't generate the tables for it [See this issue](https://github.com/mmucklo/DtcQueueBundle/issues/77).

This traces back to setFilterSchemaAssetsExpression which of course I could call in my compiler pass if ORM is not used, however it only allows a single filter at a time, so if someone sets a filter in their schema_filter symfony configuration, I can't add an additional filter on top of that to filter out the DtcQueueBundle tables without overwriting that filter.

I could write code to parse any existing filter's regular expression and then add additional regular criteria to the same original one, but that seems tricky and prone to error.

I'd rather just have the ability to "addFilterSchemaAssetsExpression" and the filter expressions be treated like an array.

Nevertheless if there's a better way to do this, I'm all ears.

**Comment by morozov** [comment]
Given that currently assets are filtered by a regular expression, it's indeed hard to extend. A trick with [combining multiple regular expressions in one using positive lookaheads](http://www.ocpsoft.org/tutorials/regular-expressions/and-in-regex/) requires the pieces to not contain the delimiters and flags which is not the case here.

The ability to `addFilterSchemaAssetsExpression()` is also not really extensible. This way, the `AND` logic would be implemented in `filterAssetNames()` which won't allow any more complex extension (e.g. the `OR` logic). It would also require adding `removeFilterSchemaAssetsExpression()` and other related methods.

Instead, `getSchemaAssetsFilter() : ?callable` and `setSchemaAssetsFilter(?callable $filter)` could be added. This way, any component can wrap an existing filter using any logic and set it back.

@Majkl578, @Ocramius, do you have an opinion? I haven't used this API myself.

**Comment by mmucklo** [comment]
@morozov A callback implementation could work with as proposed.  The only question is how to preserve backward compatibility with the existing regex filter.

Maybe the default callable stored could be the existing regex function (while the old method is marked as "@deprecated") .  That way someone could do a getSchemaAssetsFilter() and wrap even any present regex...

**Comment by morozov** [comment]
@mmucklo yes, we need a backward-compatible solution. To summarize your suggestion above:

1. Setting a regex filter should make it available as a callback via the callback getter.
2. Setting a callback filter resets the regex one.
3. The regex approach is deprecated.

This way, if the caller doesn't set the callback filter, the regex will work. If a regex filter is set, it will work via both callback and regex APIs.

**Comment by morozov** [comment]
Fixed by https://github.com/doctrine/dbal/pull/3308.
