### ISSUE TITLE
driver_class not working when using url connection parameter

### ISSUE THREAD

**Issue by thomas-hiron** [doctrine/dbal#3209]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.7.1

#### Summary

While using complete url parameter to connect to database, I can't use a custom driver class.  
I need to use all parameters (host, port, dbname, user, password).

#### Current behavior

`driver_class` only works if all connection parameters are defined.

#### How to reproduce

Clone `symfony/demo` project, use [this workaround](https://coderwall.com/p/staybw/workaround-for-1701-cannot-truncate-a-table-referenced-in-a-foreign-key-constraint-using-doctrine-fixtures-load-purge-with-truncate) to create a custom driver.

Add something like this to the driver:

```php
public function getDatabasePlatform()
{
    echo "Should be displayed";
    exit;

    return new Platform();
}
```
Then run `bin/console doctrine:fixtures:load --purge-with-truncate` --> The text should not appear.
Remove `DATABASE_URL` and use every parameters separately:

```text
doctrine:
    dbal:
       host: 127.0.0.1
       port: 3306
       dbname: symfony
       user: root
       password: 123456
```

Then the text should appear.

#### Expected behavior

A custom `driver_class` must be working when using `url` parameter.

I'll have a look if I can find something, but I lost a lot of time on this strange behavior.

**Comment by thomas-hiron** [comment]
I found the cause: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/DriverManager.php#L403

But why? Is there no way to use a custom driver with `url` parameter?

**Comment by morozov** [comment]
@thomas-hiron I'm not sure why it's implemented this way. From what I understand, the `driver` is only used to determine the `driver_class`. If that's the case, they should be mutually exclusive.

In the meanwhile, could you try using a URI without the scheme? Like the following:
```php
$url = '//user:password@example.com/path?param=value';
var_dump(parse_url($url));

/*
array(5) {
  'host' =>
  string(11) "example.com"
  'user' =>
  string(4) "user"
  'pass' =>
  string(8) "password"
  'path' =>
  string(5) "/path"
  'query' =>
  string(11) "param=value"
}
*/

**Comment by morozov** [comment]
I think this behavior is too confusing to be just documented. Unless there are some reasons I'm not aware of, the correct behavior should either of:

1. `driver_class` overrides `driver` as the former is more specific.
2. One and only one of `driver_class` and `driver` is allowed to be specified since otherwise, they can be controversial.

@Ocramius any idea why the current behavior is implemented this way?

**Comment by chucky2305** [comment]
Any updates on this

**Comment by stefanbraspenning** [comment]
After a long period of time, mysql server can go away. This packages is a wrapper around the doctrine driver to reconnect if it went away. I've been looking for solutions to overwrite driver class (override mapping of pdo_mysql, add driver to $_driverMap, specify driver_class, ... but none of them worked/is possible).

**Comment by NavyCoat** [comment]
any update?

**Comment by bvcmxy** [comment]
For using custom DBAL Driver for Symfony 4/6 set the driver_class: App\DBAL\Driver in doctrine.yaml and very important, set in .env if you are using it DATABASE_URL=App\DBAL\Driver://user:password@host:3306/database

**Comment by morozov** [comment]
Although this behavior is confusing, it's intentional:

https://github.com/doctrine/dbal/blob/9f3188ab3d56db6f6fc76c2ddf6b0b4aae06192f/lib/Doctrine/DBAL/DriverManager.php#L401-L403

Changing it would be a minor BC break. Closing for now. Please feel free to file a PR and change it in the next major release.
