### ISSUE TITLE
Execute method does not contain return statement in SQLSrvStatement

### ISSUE THREAD

**Issue by ekarajbic-mydays** [doctrine/dbal#3213]
Shouldn't there be a return statement in execute method, since documentation states that method returns boolen?

**Comment by Ocramius** [comment]
Could you link the specific bit of code please?

**Comment by ekarajbic-mydays** [comment]
In class https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php 

method execute on line 249.

The documentation section is: [https://www.doctrine-project.org/api/dbal/2.7/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.html#method_execute](url)

**Comment by Ocramius** [comment]
Ref:

https://github.com/doctrine/dbal/blob/d475ade698bf00c84d20946350f24f0cbd07f164/lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php#L249

**Comment by morozov** [comment]
As part of https://github.com/doctrine/dbal/pull/3154, I'm trying to change the return type of `Statement::execute()` from `bool` to `void`. Besides the documentation mismatch, is there a practical reason for changing the code?

**Comment by ekarajbic-mydays** [comment]
Nobody is relying only on return, of course try-catch blocks must be there.

But, it was nice to know if it was executed or not with true/false as return.

All other Statements still have it except SQLSrvStatement, so in these terms it should be taken as a BUG.

In #3154 , is it guaranteed then when void was returned, the statement was executed successfully if no exception has been thrown ?

If that is the case, then no other reason beside mismatch in documentation is problem.

**Comment by morozov** [comment]
> But, it was nice to know if it was executed or not with true/false as return.

Currently, the fact that the method doesn't throw an exception is the indicator of success:

https://github.com/doctrine/dbal/blob/d475ade698bf00c84d20946350f24f0cbd07f164/lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php#L263-L265

> In #3154, is it guaranteed then when void was returned, the statement was executed successfully if no exception has been thrown?

Yes, this is the goal.

**Comment by morozov** [comment]
I believe this is irrelevant as of https://github.com/doctrine/dbal/pull/4045.
