### ISSUE TITLE
Can we get #2825 backported to version 2.6?

### ISSUE THREAD

**Issue by ocelotsloth** [doctrine/dbal#3216]
Hello, I'm running some other software projects in my environment who's development communities are really tied due to #2825 included only as part of a major feature release rather than a minor revision.

Both fixing that issue and also moving to require PHP7 is problematic for any projects that are reliant on this project but have not yet finished their move to PHP5. All I'd like is for #2825 to be cherry-picked into the 2.6.3 release and a minor revision for version 2.6 to be released to accommodate these projects.

**Comment by Ocramius** [comment]
New features => new minor/major releases: that's not open for discussion, sorry.
