### ISSUE TITLE
Sqlite defaults & DC2Type comments

### ISSUE THREAD

**Issue by GwendolenLynch** [doctrine/dbal#3220]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.7.0+

#### Summary

The array returned from a table's `PRAGMA` query contains the `DC2Type` comment as the `dflt_value` key's value. This is no longer getting removed and causing the table diff to always want to (re)set the default column value.

#### Current behavior

Incorrect `CREATE TABLE` SQL is built, as the default still contains the `DC2Type` comment

#### How to reproduce

Create a `JsonType` field with a `NULL` default.

#### Expected behaviour

The default value for Sqlite fields with a `DC2Type` commented type will remove the comment when building the table's schema.

**Comment by morozov** [comment]
Cannot reproduce this on 2.13.x:
```php
$desiredTable = new Table('t');
$desiredTable->addColumn('c', 'json', ['default' => null]);

$sm = $connection->getSchemaManager();
$sm->createTable($desiredTable);

$actualTable = $sm->listTableDetails('t');
var_dump($actualTable->getColumn('c')->getDefault());
// NULL
```
