### ISSUE TITLE
Code in DriverException will never be reached due to typehinting

### ISSUE THREAD

**Issue by ChangePlaces** [doctrine/dbal#3227]
### Bug Report

The constructor for DriverException is typehinted with `\Doctrine\DBAL\Driver\DriverException` however, inside the constructor is a check for `\Exception`. This will never be true. Either this code or the typehint is an error.

https://github.com/doctrine/dbal/blob/54054275689c9b9759bd607f6d0cf63c77d52375/lib/Doctrine/DBAL/Exception/DriverException.php#L50

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     |  master downwards

**Comment by Ocramius** [comment]
Seems incorrect: implementations of the exception have to extend `Exception` anyway.

**Comment by Majkl578** [comment]
> This will never be true. 

Actually the condition will always be true since DriverException extends Exception - the condition could be removed.
