### ISSUE TITLE
New Logger interface

### ISSUE THREAD

**Issue by jcchavezs** [doctrine/dbal#3228]
### Feature Request

Existing logger interface is not so useful with modern logging patterns. The problems I encountered are:
1. Hard to extend: Every single time we need to introduce a new feature require changes in the interface and it ends up in a breaking change.
2. Structured logging requires keep an state between `startQuery` and `stopQuery`.
3. Output information can not enrich log records.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

The proposed interface is:

```php
namespace Doctrine\DBAL\Logging;

interface Logger
{
    /**
     * @param array $fields
     * @param int|null $timestamp if null, current timestamp is being used
     * @return void
     */
    public function log(array $fields = [], $timestamp = null);
}
```

And it can be used in the methods as follows:

```php
public function executeQuery($query, array $params = [], $types = [], QueryCacheProfile $qcp = null)
{
    ...
    $logger = $this->_config->getSQLLogger();
    if ($logger instanceof SQLLogger) {
        $logger->startQuery($query, $params, $types);
    }

    $startTime = time();

    try {
        ...
    } catch (Exception $ex) {
        throw DBALException::driverExceptionDuringQuery($this->_driver, $ex, $query, $this->resolveParams($params, $types));
    } finally {
        if ($logger instanceof Logger) {
            $this->logger->log([
                'start_time' => $startTime,
                'query' => $query,
                'statement' => $stmt,
                'error' => $ex
            ]);
        }
    }

    $stmt->setFetchMode($this->defaultFetchMode);

    if ($logger instanceof SQLLogger) {
        $logger->stopQuery();
    }
    
    return $stmt;
}
```

This allows developers to receive all the information about the query: `start_time`, `query`, `statement` (return value) and `error` and it can be translated into different signals collectors:
1. Logging: structured logging can be obtained directly.
2. Metrics: can be aggregated as low cardinality values like `query` or `error` can be used.
3. Tracing: `query`, `start_time` and `error` are essential for tracing and this can be obtained from the provided output values.

Finally, adding more information is a matter of adding a new field to the array.

Ping @morozov @Ocramius @beberlei

**Comment by morozov** [comment]
>```php
>public function log(array $fields = [], $timestamp = null);`
>```

The absence of a contract doesn't make an interface extensible.  It makes it undefined. With this approach, how do you know if the logger implementation X is compatible with DBAL of version Y?

>```php
>$this->logger->log([
>    'start_time' => $startTime,
>    'query' => $query,
>    'statement' => $stmt,
>    'error' => $ex
>]);
>```
Passing `$stmt` to the logger is too much. The logger shouldn't be able to fetch data from the statement.

The only decent approch I can think of is the middleware-like one (see https://github.com/doctrine/dbal/pull/3174#issuecomment-394861216).

**Comment by ragboyjr** [comment]
While smaller interfaces around the executeQuery/update methods would provide benefit, i don't think it removes any value from having a better defined logging interface.

I think we could tighten up this new logging api since there isn't much needed for logging other than the query, params, timestamp, the result.

I'd propose something more along the lines of:

```php
<?php

// ROUGH PSUEDO CODE

namespace Doctrine\DBAL\Logging;

final class LogRecord
{
    private function __construct(string $query, array $params, array $types, float $executionTimeInSecs, $result, \Throwable $exception = null) {}

    // simple getters for the properties
    // ...

    public function hasException(): bool {
        return $this->exception !== null;
    }


    /** @return mixed */
    public static function logAndQuery(?RecordSqlLogger $logger, string $query, $params, array $types, callable $execQuery) {
        if (!$logger) {
            return $execQuery($query, $params, $types);
        }

        $startTime = microtime(true);
        try {
            $result = $execQuery($query, $params, $types);
        } catch (\Throwable $e) {}

        $logRecord = new self($query, $params, $types, microtime(true) - $startTime, $result ?? null, $e ?? null);
        $logger->logRecord($logRecord);

        if (isset($e)) {
            throw $e;
        }

        return $result;
    }
}
```

Obviously, the `logAndQuery` isn't necessary, but could make the code easier to understand and simplify the logic in the executeQuery to not worry about having to deal with weird code flow introduced from the logging.

The more important piece is that we are using a well defined schema instead of an array to pass through. Also, if we really wanted to, we could also pass an array of `attributes` for any unstructured data that might get passed in.

**Comment by morozov** [comment]
Closing in favor of https://github.com/doctrine/dbal/issues/4941.
