### ISSUE TITLE
Better error message when index keys surpass the 767 limit

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/dbal#3230]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

If the following conditions met:

* You are using `utf8mb4`
* You set `unique=true` in a column
* That column is a string with more than 190 character length (which happens when you don't define the length and 255 is used by default)

You'll see this cryptic error message:

```
[PDOException] SQLSTATE[42000]: Syntax error or access violation:
1071 Specified key was too long; max key length is 767 bytes
```

This is [a well-known MySQL restriction](https://dev.mysql.com/doc/refman/5.6/en/innodb-restrictions.html) but maybe we could display a better error message to help users? Example:

```
When using utf8mb4, the length of the unique columns must be 190 or
less but the %s property of the %s entity has a length of %d.
```

**Comment by morozov** [comment]
No need to replace a well-known error message with a DBAL-specific one. The internal MySQL limitations may change from version to versions and vary depending on the storage engine. The same error message also can be seen with other charsets as well.

**Comment by javiereguiluz** [comment]
This is disappointing ... but at least Symfony Documentation now explains this error message and its solution: https://symfony.com/doc/current/doctrine.html

**Comment by Ocramius** [comment]
Well, it's an engine exception, as @morozov explained.

MySQL has always been very tedious to work with ("SHOW ENGINE InnoDB
STATUS" anybody?), but indeed,

if we start the rabbit hole of translating (improving?) MySQL errors we
will likely never make it out of there, so it's probably better if left
alone, as the BC breaks would be massive every time MySQL or MariaDB change
any of the strings.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/
