### ISSUE TITLE
Postgres 10 dont work

### ISSUE THREAD

**Issue by MattCzerner** [doctrine/dbal#3234]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.8.0

#### Summary
(#2868) - still does not work, even after upgrade to newer veresion of doctrine/dbal package, I still have same problem with nonexisting `min_value` column.

#### Current behavior

```
In PDOConnection.php line 107:
                                                                               
  [PDOException (42703)]                                                       
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not ex  
  ist                                                                          
  LINE 1: SELECT min_value, increment_by FROM "administrator_activitie...  
```

#### How to reproduce
Im using default query.

#### Expected behaviour
I would like what am I doing wrong, since the issue was solved and this problem does not seem to be happening for others.

**Comment by Besedin86** [comment]
@MattCzerner did you configure `server_version=10` in your DBAL config or param `serverVersion=10` in DATABASE_URL env variable?

**Comment by MattCzerner** [comment]
@Besedin86 . Oh, thats it, thank you very much :)
