### ISSUE TITLE
DBAL Query Builder Aliasing issue

### ISSUE THREAD

**Issue by CheeseBites** [doctrine/dbal#3242]
|    Q        |   A
|------------ | -----
| Version     | 2.8.0

### Support Question

If the column name starts with a number the querybuilder doesn't wrap the alias in quotes,

Error returns:
`An exception occurred while executing 'SELECT t0_.AA AS AA_0, t0_.BB AS BB_1, t0_.[12AA] AS 12AA_2 FROM [foo]'`
`SQLSTATE [42000, 102]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Incorrect syntax near '12'.
SQLSTATE [42000, 8180]: [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Statement(s) could not be prepared.'`

What the query should look like
`An exception occurred while executing 'SELECT t0_.AA AS AA_0, t0_.BB AS BB_1, t0_.[12AA] AS "12AA_2" FROM [foo]'`

The code looks like this
```
$queryBuilder = $this->entityManager->createQueryBuilder();
$queryBuilder->select('a')->from(foo::class, 'a');
$list = $queryBuilder->getQuery()->getResult();
```

Is there any workaround for this?

**Comment by morozov** [comment]
Linking a related issue: https://github.com/doctrine/dbal/issues/3152.

**Comment by morozov** [comment]
@CheeseBites given that the example uses ORM's entity manager, are you sure it's a DBAL issue? AFAIK, ORM doesn't use DBAL to build SELECT queries.

**Comment by Ocramius** [comment]
Closing: this is for the ORM
