### ISSUE TITLE
MySQL 8 - The server requested authentication method unknown to the client: [caching_sha2_password]

### ISSUE THREAD

**Issue by Destroy666x** [doctrine/dbal#3249]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.8.0

#### Summary

When connecting to MySQL 8, you get that error unless you change to the old authentication method - `mysql_native_password`.

#### Current behavior

You can't connect to MySQL 8 with its default configuration.

#### How to reproduce

Simple installation - Docker with MySQL 8, PHP 7.2 and Symfony 3.4 with latest Doctrine. Configured with `server_version: '8.0'`. Attempt to connect.

#### Expected behaviour

Default MySQL 8 authentication configuration should be supported.

**Comment by gustawdaniel** [comment]
I have this problem with PHP 7.3.14
