### ISSUE TITLE
Annotation with terms in indexes

### ISSUE THREAD

**Issue by tasselchof** [doctrine/dbal#3261]
#### Summary

If you use cases in indexes, command

orm:schema-tool:update --dump-sql

will always generate this statements:

DROP INDEX u_email_unique_idx;
CREATE UNIQUE INDEX u_email_unique_idx ON core_users (email) WHERE state <> 'deleted';

#### How to reproduce

/**
 * User
 *
 * @ORM\Entity(repositoryClass="Users\Repository\Users")
 * @ORM\Table(name="core_users", uniqueConstraints={
 *          @ORM\UniqueConstraint(name="u_email_unique_idx", columns={"email"}, options={"where": "state <> 'deleted'"}),
 *     },
 *     indexes={
 *          @ORM\Index(name="cu_search_idx", columns={"state","discr"})
 *     })
 * @ORM\HasLifecycleCallbacks
 *
 * @Gedmo\Loggable(logEntryClass="Users\Entity\Log\UserLogEntry")
 */

#### Expected behaviour

It should not generate them.

**Comment by morozov** [comment]
@tasselchof please provide a DBAL case.

**Comment by tasselchof** [comment]
I suppose I duplicated my old issue #2913.

**Comment by morozov** [comment]
Closing as a duplicate.
