### ISSUE TITLE
Add support for MariaDB 10.3

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/dbal#3278]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

[MariaDB 10.3](https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-103/) is the current major stable version. It will be supported until May 2023.

We already have support for MariaDB 10.2 thanks to #2825. We also have some feature requests for 10.3 already (see #3202).

Recently, in Symfony's Slack there's been some discussion about the lack of support of 10.3 in DBAL. Some Doctrine maintainers agreed to help bring support for MariaDB 10.3 if the community provided the needed pull request.

So **this is a public call for help** for those people who need MariaDB 10.3 support in DBAL (and therefore, in Doctrine ORM, ZendFramework apps, Symfony apps, etc.) If you think you are up for this task, please volunteer to create the pull request.

Thanks!

**Comment by morozov** [comment]
@javiereguiluz, besides the first step — adding MariaDB 10.3 to the build matrix, are you aware of any other issues with it? If we had more fine-grained tasks, it'd give a better understanding of what needs to be done to potential contributors.

**Comment by morozov** [comment]
MariaDB 10.3 was added to the build matrix in https://github.com/doctrine/dbal/pull/3283. Closing the ticket. Please feel free to file a new one if our tests don't cover some case.
