### ISSUE TITLE
Support SQLite attached databases by getSchemaManager

### ISSUE THREAD

**Issue by pc-explore** [doctrine/dbal#3282]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | no

#### Summary

At this moment, the getschemaManager only retrieves information on the initially opened SQLIte database. When you attach a second SQLite database (by using the 'Attach'-command), then getSchemamanager only queries the first database although the second is also connected and available to the program.

I think that is because the queries which are excecuted do not include a _schema-name_ (as is it called on the page https://www.sqlite.org/lang_attach.html) and therefore they are always executed in the scope of the current database.

Example : in the program attached here 
[test.zip](https://github.com/doctrine/dbal/files/2367919/test.zip)
, the listTables() will always show the table from the first database (test.db) and will not show tables from the attached database (attached.db).
There is also no way to explicitly point the getSchemaManager towards the attached database.
The program is to be run with _php bin/console test:test_

It would be a nice extension to somehow being able to address the attached database.

**Comment by Ocramius** [comment]
This is normal and applies to all other supported RDBMSs as well: the schema manager only operates on the active/current schema.
