### ISSUE TITLE
DB2 does not support streams for the LARGE_OBJECT parameter type

### ISSUE THREAD

**Issue by mpdude** [doctrine/dbal#3288]
While fixing #3217, added tests showed that `DB2Statement` is unable to correctly process streams passed in with the `ParameterType::LARGE_OBJECT`.

Such streams will be cast to strings by the DB2 driver in PHP and finally end up in the database as strings like `Resource id #126`.

#3217 fixes this for MySQLi.

A quick scan through https://github.com/php/pecl-database-ibm_db2/blob/master/ibm_db2.c does not show any attempt to support stream handling in DB2.

One solution might be to detect streams in userland (i. e. DBAL), use `stream_get_contents` or similar and pass the whole data on to DB2. The other approach is to write stream data out to a file and make use of the `DB2_PARAM_FILE` parameter type ([docs](http://php.net/manual/de/function.db2-bind-param.php)) to avoid the memory overhead.

When this issue is fixed, the `testInsertProcessesStream` and `testUpdateProcessesStream` tests in `\Doctrine\Tests\DBAL\Functional\BlobTest` need no longer be skipped.

**Comment by morozov** [comment]
Fixed via https://github.com/doctrine/dbal/pull/3309.
