### ISSUE TITLE
MySqlSchemaManager doesn't handle longtext type in _getPortableTableColumnDefinition method

### ISSUE THREAD

**Issue by rygilles** [doctrine/dbal#3292]
### Bug Report

MySqlChemaManager should handle `longtext` field type lenght

|    Q        |   A
|------------ | ------
| Version     | 2.8.0

#### Summary

MySqlChemaManager should handle `longtext` field type lenght.

`case 'longtext:`' is missing Here : 
https://github.com/doctrine/dbal/blob/3979efeedfda1eda12d30781344583b0ece0a644/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php#L118-L220

#### Current behaviour

$length = 0
Should be 4294967295

#### How to reproduce

Append when calling MySqlSchemaManager->listTableColumns method on table with longtext field.

#### Expected behaviour

$length should be 4294967295

#### Workaround

Add this code at line 168 in https://github.com/doctrine/dbal/blob/3979efeedfda1eda12d30781344583b0ece0a644/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php#L165-L170

```php
	        case 'longtext':
		        $length = MySqlPlatform::LENGTH_LIMIT_LONGTEXT;
		        break;
```

And add this code at line 60 in https://github.com/doctrine/dbal/blob/3e2bee77fc9da506e3549115fa65e1648aee8368/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L55-L63

```php
	const LENGTH_LIMIT_LONGTEXT   = 4294967295;
```

**Comment by morozov** [comment]
@rygilles please provide a pull request with the patch and tests. Also, some changes may be required in the part of DDL generation from the schema definition. If the length of the text field is greater than `LENGTH_LIMIT_MEDIUMTEXT`, the field should be declared as `LONGTEXT`.

**Comment by sidz** [comment]
this fix won't change anything. Without this case `$length` contains NULL and `getClobTypeDeclarationSQL` returns `LONGTEXT` by default which looks logically.

proof: https://github.com/doctrine/dbal/blob/3979efeedfda1eda12d30781344583b0ece0a644/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php#L266

**Comment by morozov** [comment]
@sidz you're right, it's already covered.

**Comment by rygilles** [comment]
I don't get it, why the length value should be NULL with `longtext` and 16777215 with `mediumtext` in the portable definition ?
But, ok, in my case (I'm trying to fix this lib : https://github.com/Xethron/migrations-generator/issues/105) the script should use `getClobTypeDeclarationSQL` method to set the correct field type.

**Comment by sidz** [comment]
> why the length value should be NULL 

It shouldn't but it won't change anything :) DBAL Platforms decide how to work with different types.

If it's annoying you I'm pretty sure that @morozov will approve RP with this change or I may prepare a quick fix if we agree to apply it.
