### ISSUE TITLE
Migrating a TEXT field to JSON incorrectly sets COLLATE and MySQL throws an error

### ISSUE THREAD

**Issue by poisa** [doctrine/dbal#3295]
- Laravel Version: 5.6.29
- PHP Version: 7.1.20
- Database Driver & Version: MySQL 5.7.23
- doctrine/dbal Version: 2.8.0

### Description:
I expect the generated SQL to change a column to json to include a valid collation for a JSON field (such as `binary`) or no collation at all:

```SQL
ALTER TABLE mytable CHANGE mycolumn mycolumn JSON DEFAULT NULL
```

The actual SQL generated is:

```SQL
ALTER TABLE mytable CHANGE mycolumn mycolumn JSON DEFAULT NULL COLLATE utf8mb4_unicode_ci
```
This results in the following error:

> SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_unicode_ci' is not valid for CHARACTER SET 'binary'

### Steps To Reproduce:
While creating a table set a field to TEXT:

```php
$table->text('mycolumn')->nullable();
```

Then create a migration that attempts to change the field type to JSON:

```php
$table->json('mycolumn')->nullable()->change();
```

### Referred from:

https://github.com/laravel/framework/issues/25735#issuecomment-423643346

**Comment by morozov** [comment]
@poisa could you please provide the steps to reproduce the issue in terms of DBAL? Without that, it's not clear if the issue on the DBAL side or in Laravel.

**Comment by Majkl578** [comment]
@poisa Unless you can provide a failing test case to prove this is a bug in DBAL\Schema, this appears to be a Laravel issue. The code under _Steps to Reproduce_ isn't Doctrine DBAL's API, but Laravel's API: https://github.com/laravel/framework/blob/v5.7.5/src/Illuminate/Database/Schema/ColumnDefinition.php#L7-L22

**Comment by poisa** [comment]
@morozov @Majkl578 I've managed to reproduce this bug outside of Laravel (using only DBAL as a dependency). Take a look at the last `print_r`; it includes an invalid collation. Looks like it's keeping the previous one.

```php
<?php

use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\DriverManager;
use Doctrine\DBAL\Schema\Comparator;
use Doctrine\DBAL\Types\Type;

require 'vendor/autoload.php';

$config = new Configuration();

$connectionParams = array(
    'dbname'   => 'test',
    'user'     => 'root',
    'password' => 'root',
    'host'     => 'localhost',
    'charset'  => 'utf8mb4',
    'driver'   => 'pdo_mysql',
);

$conn = DriverManager::getConnection($connectionParams, $config);
$comparator = new Comparator();
$platform = $conn->getDatabasePlatform();
$schemaManager = $conn->getSchemaManager();

// 1. Create a TEXT column
$fromSchema = $schemaManager->createSchema();
$fromTable = $fromSchema->createTable('test');
$fromTable->addColumn('my_column', 'text',
    [
        'notnull' => false,
        'length' => 65535,
        'customSchemaOptions' => [
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci'
        ]
    ]
);

print_r($fromSchema->toSql($platform));
/*
Array
(
    [0] => CREATE TABLE test (my_column TEXT  DEFAULT NULL COLLATE utf8mb4_unicode_ci) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
)
*/

// 1. Change the column from TEXT to JSON
$toSchema = clone $fromSchema;
$toTable = $toSchema->getTable('test');
$toTable->changeColumn('my_column', ['type' => Type::getType('json')]);


$schemaDiff = $comparator->compare($fromSchema, $toSchema);
$queries = $schemaDiff->toSql($platform);

print_r($queries);
/*
Array
(
    [0] => ALTER TABLE test CHANGE my_column my_column JSON  DEFAULT NULL COLLATE utf8mb4_unicode_ci
)
*/
```

**Comment by kimhemsoe** [comment]
I am with @jwage here, we can not start to guess here. Dbal do not and can not know about single column type and its feature set out there. Some databases even allow you to define new types on the fly.

**Comment by poisa** [comment]
OK, I see. When I saw DBAL generating invalid SQL I expected there would be validations in place to catch this but since I'm not familiar with the project I guess I was wrong.

I have opened up a pull request on Laravel to solve this on their end.

Having said that, I do have a question about this. When I set `customSchemaOptions` on a database engine that does not support them. Are they silently dropped or do the end up in the generated SQL string? [The docs](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.8/reference/schema-representation.html#vendor-specific-options) say that they are "Supported by MySQL, PostgreSQL, Sqlite, SQL Server and Drizzle" but they don't mention wether an error is thrown on other engines or are silently ignored.

**Comment by kimhemsoe** [comment]
@poisa Without having tested, i believe customSchemaOptions which is not supported by the platform will silently get ignored.

Look in AbstractPlatform::getColumnDeclarationSQL() for more info

**Comment by poisa** [comment]
@kimhemsoe thanks for the nudge in the right direction. I was having trouble navigating the code base.

Indeed, the collation is ignored: https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L2642-L2654

Thank you all for your help. I'm going to go ahead and close this and continue over on the Laravel side.
