### ISSUE TITLE
Allow entering a comma into a `simple_array`

### ISSUE THREAD

**Issue by ThomasLandauer** [doctrine/dbal#3300]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | maybe

#### Summary

Provide a way to literally enter a `,` (comma) into a `simple_array`, so it's possible to get these two values:
* foo,bar
* second entry

Ideas:
* Define some escape character, like e.g. `\,`. This would (probably) be a BC break.
* Let the user choose the delimiter in the column's definition. This would not be a BC break.

In the meantime, I posted a workaround: https://stackoverflow.com/a/52502920/1668200

**Comment by morozov** [comment]
Why not use something like `JsonType` instead of inventing yet another serialization format?

**Comment by ThomasLandauer** [comment]
Because with `simple_array` it's easy to enter data manually into the database (i.e. not via PHP), whereas with `array` or `json` it isn't.

**Comment by morozov** [comment]
Given the breaking nature of the requested changes and very little likelihood of having it implemented in the next major release, I'm closing this issue. Please use a custom type if needed.
