### ISSUE TITLE
Feature request: select() on connection (similar to delete/update/insert)

### ISSUE THREAD

**Issue by andrisi** [doctrine/dbal#3329]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

DBAL connections have insert/update/delete convinience functions with an $identifier parameter which for all of them is "An associative array containing column-value pairs." according to the docs. There shall be a select() method too in the same spirit, so that all four basic operations are supported this easy way.

**Comment by bmack** [comment]
we implemented this in our Doctrine DBAL Connection facade in TYPO3

https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Database/Connection.php#L226-L273

Let me see if I can come up with a PR in the next days.

**Comment by morozov** [comment]
Closing as stale. There is already a query builder component.
