### ISSUE TITLE
MsSQL Windows Authentication 

### ISSUE THREAD

**Issue by odinsey** [doctrine/dbal#3332]
In dbal/lib/Doctrine/DBAL/Driver/SQLSrv/Driver.php:34

For sqlsrv_connect, if any UID nor PWD are provided in $driverOptions array, it will use Windows Authentication
BUT there are always those keys even if $username and $password are null.

Please add those keys to $driverOptions only if values are not null.

**Comment by odinsey** [comment]
is doctrine dead ?

**Comment by AlessandroMinoccheri** [comment]
Hi @odinsey, it could be amazing if you create a pull request about it because you know the problem and the solution. After discuss it with the community!
Try to create the pull request please

**Comment by odinsey** [comment]
Ok it's done ;) please be gentle, it's my first public pull request.

**Comment by Majkl578** [comment]
#3333 has been merged.
