### ISSUE TITLE
mssql 2016 SQLServer2012Platform::getConcatExpression() missing/wrong

### ISSUE THREAD

**Issue by Lacoi** [doctrine/dbal#3346]
### Bug Report
Since SQL Server 2012 it is possible to use CONCAT() https://docs.microsoft.com/de-de/sql/t-sql/functions/concat-transact-sql?view=sql-server-2016
When i use `CONCAT(column1. '-', column2) LIKE :search)` it converts to `(f0_.column1 + '-' + f0_.column2)` which is not working in the where clauses.

|    Q        |   A
|------------ | ------
| Version     | 2.8.0

#### Solution
Add to Doctrine\DBAL\Platforms\SQLServer2012Platform
```php
   /**
     * {@inheritDoc}
     */
    public function getConcatExpression()
    {
        $args = func_get_args();

        return 'CONCAT(' . join(', ', (array) $args) . ')';
    }
```

**Comment by Ocramius** [comment]
This requires a test case showing the wanted/valid SQL syntax being produced for SQL Server 2012+.

**Comment by rogeriolino** [comment]
I'm trying to use `CONCAT` via DQL to show a period of years in my report page, but the result is the sum of fields.

Statement:

    CONCAT(fieldYear1, ' - ', fieldYear2)

Expected: 

    2010 - 2019

Got:

    4029

To fix it, I'd created a custom DQL `CONCAT` function that translate to SQL Server `CONCAT`.
