### ISSUE TITLE
#3306 introduced at least one bug

### ISSUE THREAD

**Issue by svycka** [doctrine/dbal#3349]
### Bug Report

replacing all `==` to `===` and `!==` to `!==` should not be made with cs fixer as this can cause bugs for example here: https://github.com/doctrine/dbal/blob/72b4e777543e19a67c9b94edb3f23d7b3e523be5/lib/Doctrine/DBAL/Schema/Comparator.php#L435  

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.9.x-dev

#### Summary

Becouse of #3306 change `!=` to `!==` now Schema comparator return false changes

#### Current behaviour

incorrectly treats default value because from database it returns string `'1'` but  schema retun integer `1` and counts as changed default value

#### How to reproduce

doctrine/dbal:2.9.x-dev
maraidb:10.2.14 and mariadb:10.3.10
```
/**
 * @ORM\Column(type="integer", options={"default" = 1})
 */
protected $fuelType;
```
```
doctrine-module orm:schema-tool:update --dump-sql
ALTER TABLE purchase CHANGE fuelType fuelType INT DEFAULT 1 NOT NULL;
```
#### Expected behaviour

```
doctrine-module orm:schema-tool:update --dump-sql
[OK] Nothing to update - your database is already in sync with the current entity metadata
```

**Comment by morozov** [comment]
@svycka it looks similar to https://github.com/doctrine/dbal/issues/3336.

**Comment by svycka** [comment]
yep looks like it, sorry :)
