### ISSUE TITLE
OCI8Statement::execute() ignores binding errors

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3366]
|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.8.0

`Statement::bind*()` methods return a boolean value to indicate whether the binding was successful:
https://github.com/doctrine/dbal/blob/df4343721d9981e58afd15eeaf18c885a2399766/lib/Doctrine/DBAL/Driver/Statement.php#L51-L53

This value is ignored in other DBAL components. For instance:
https://github.com/doctrine/dbal/blob/2ec1743e8876c20ba371e80fea17a0cd8e1ac919/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php#L391-L394

It leads to the issues like:
```php

use Doctrine\DBAL\DriverManager;

$conn = DriverManager::getConnection([
    'driver' => 'oci8',
    'host' => 'localhost',
    'user' => 'system',
    'password' => 'oracle',
    'dbname' => 'XE',
]);

$data = $conn->fetchAll('SELECT 1 FROM DUAL', [123]);

var_dump($data);

/*
Warning: oci_bind_by_name(): ORA-01036: illegal variable name/number in lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php on line 316

array(1) {
  [0] =>
  array(1) {
    [1] =>
    string(1) "1"
  }
}
*/
```
`Statement::execute()` should throw an exception in the case of a binding error instead of trying to execute an incorrectly constructed query.

**Comment by Ocramius** [comment]
Handled in #3369
