### ISSUE TITLE
SQL Server datetime format is still wrong after all these years

### ISSUE THREAD

**Issue by ianef** [doctrine/dbal#3373]
### Bug Report

BC Break: no
Version: DBAL 2.8

#### Summary

When using SQL Server 2008 or above, updating a DATETIME column in the database fails on commit.

#### Current behaviour

When performing an UPDATE with a datetime field, the following exception is generated:
`The server returned: " An exception occurred while executing 'UPDATE MyTable SET MyDate= ? WHERE ID = ?' with params ["2018-12-26 00:00:00.000000", 138869]: SQLSTATE[22007]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string."`

#### How to reproduce

Update any datetime field in a SQL Server database 2008 or above.

#### Expected behaviour

No exception should occur.

In the above exception message, note the milliseconds format is a 6 characters, SQL Server only accepts 3. Please see [SQL Server CAST and CONVERT](https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-2017#date-and-time-styles).

This problem was partly resolved in [DBAL-860](https://github.com/doctrine/dbal/issues/2098) which fixes the milleseconds to '000', i.e. ignores them, but the 2008 platform class still uses a datetime format string of 'Y-m-d H:i:s.u', this causes 6 digits to be produced for the milliseconds and therefore will always fail.

Just using standard format characters for creating datetime strings will never work as the PHP internal functions will always create a milliseconds section with 6 characters, see [date function](http://php.net/manual/en/function.date.php). Also note that you are using the 'u' format character which is for microseconds, 'v' is for milliseconds in PHP 7.0.0 onward.

As a workaround I have implemented a custom DateTimeType class but this should not be required:
```
class DateTimeType extends \Doctrine\DBAL\Types\DateTimeType
{
    protected $dateTimeFormatString = 'Y-m-d H:i:s.v';

    /**
     * {@inheritdoc}
     */
    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        $fmtValue = ($value === null ? null : $value->format($this->dateTimeFormatString));
        if($fmtValue !== null and strlen($fmtValue) === 26) {
            $fmtValue = substr($fmtValue, 0, 23);
        }
        return $fmtValue;
    }
}
```

**Comment by VincentChataignier** [comment]
You have to use DATETIME2(6) instead of DATETIME in your db

**Comment by morozov** [comment]
> You have to use DATETIME2(6) instead of DATETIME in your db

Closing.

**Comment by ianef** [comment]
I'd forgotten this was still open, it's been there since 2018!

I'll check the documentation, if it doesn't state that I'll raise a bug request there. My guess is that it doesn't otherwise we would not be here. Mind you a lot can change in 3 years!

**Comment by ianef** [comment]
@morozov I can't find any reference to DATETIME2 in the Doctrine documentation. I am aware that using DATETIME2 works but surely it would be sensible to actually mention this somewhere rather than relying in third party sites to do so.

At https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/cookbook/working-with-datetime.html#default-timezone-gotcha it states
"Before 2.5 this type always required a specific format, defined in $platform->getDateTimeFormatString(), which could cause quite some troubles on platforms that had various microtime precision formats. Starting with 2.5 whenever the parsing of a date fails with the predefined platform format, the date_create() function will be used to parse the date.

This could cause some troubles when your date format is weird and not parsed correctly by date_create(), however since databases are rather strict on dates there should be no problem."

This would imply that the error should be trapped and date_create() called. I've not looked at the code here so I can't comment on that. However stating that '**_there should be no problems_**' is not very helpful when it clearly does not work with a pretty standard database type.

What about dealing with legacy databases? Changing the type here is quite likely not an option.

I really don't think closing this is the right approach.

**Comment by morozov** [comment]
@ianef if you believe this issue should be fixed, please reproduce it using the DBAL APIs and provide a fix.

**Comment by ianef** [comment]
OK, great. I really do think it would make life a lot simpler for people using SQL Server.

If you can re-open this I'll try and schedule some time next week to look at it.

**Comment by Adi-18** [comment]
I have the same problem and I don't understand the solution.
Doctrine tries to store "2022-03-10T12:01:00+00:00" and I get the error. I except format like "2022-03-10T10:01:00.000".
                                                                          ------
I cannot change db on sql server and symfony don't now about datetime2.
I would expect to set annotation options for the field:
```
    /**
     * @var DateTime|null
     *
     * @ORM\Column(name="Verbrauchsdatum", type="datetime", nullable=true)
     */
    private ?DateTime $workDateTime = null;
```
