### ISSUE TITLE
ResultCacheStatement fetchAll() method does not save $data nor sets $emptied

### ISSUE THREAD

**Issue by roger-codina** [doctrine/dbal#3383]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.0

#### Summary

ResultCacheStatement is intended to save results to a persistence layer, and in the documentation it is recommended tu call fetchAll() method. To ensure that, when calling its self method closeCursor() the data will be saved.

However, since version 2.9.0, after this commit: https://github.com/doctrine/dbal/commit/e35d5e12eadf567d61e0e8295991d0d8b71deba9

This behavior is broken because ResultCacheStatement fetchAll() does not call its self fetch() method so neither $this->data nor $this->emptied are set.

#### Current behaviour

ResultCacheStatement is not caching data when calling fetchAll() method.

#### How to reproduce

Implement the following unit test:
https://github.com/doctrine/dbal/pull/3381/files#diff-ced6552e75bf27cb3e7130f38a40a63c

On branch master, tests/Doctrine/Tests/DBAL/Functional/ResultCacheTest.php 

And check is failing.

#### Expected behaviour

ResultCacheStatement should set $this->data and $this->emptied fields as it does fetch() method, to ensure that when calling closeCursor() method will overpass the following stopper validation:
```
if (! $this->emptied || $this->data === null) {
    return true;
}
```
and then reach the save() method.

My proposal is to change ResultCacheStatement fetchAll() method to this:

```
$this->data = $this->statement->fetchAll($fetchMode, $fetchArgument, $ctorArgs);
$this->emptied = true;

return $this->data;
```

This is the PR with the changes unit tested: https://github.com/doctrine/dbal/pull/3381

You can check in the following image that there is no code coverage on fetchAll() before my unit test.
You can also implement only the unit test on branch master to check cache layer is failing.

<img width="671" alt="fetchall" src="https://user-images.githubusercontent.com/7250893/49460956-df948900-f7f2-11e8-976e-11eba83b21f4.png">

**Comment by morozov** [comment]
Fixed by #3381.
