### ISSUE TITLE
Error During the Database Seeding in Laravel

### ISSUE THREAD

**Issue by AManojKiran** [doctrine/dbal#3397]
PHP Fatal error:  Maximum execution time of 900 seconds exceeded in C:\xampp\htdocs\adminlte\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php on line 117

   Symfony\Component\Debug\Exception\FatalErrorException  : Maximum execution time of 900 seconds exceeded

  at C:\xampp\htdocs\adminlte\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:117
    113|      */
    114|     public function execute($params = null)
    115|     {
    116|         try {
  > 117|             return parent::execute($params);
    118|         } catch (\PDOException $exception) {
    119|             throw new PDOException($exception);
    120|         }
    121|     }

   Whoops\Exception\ErrorException  : Maximum execution time of 900 seconds exceeded

  at C:\xampp\htdocs\adminlte\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php:117
    113|      */
    114|     public function execute($params = null)
    115|     {
    116|         try {
  > 117|             return parent::execute($params);
    118|         } catch (\PDOException $exception) {
    119|             throw new PDOException($exception);
    120|         }
    121|     }

**Comment by Ocramius** [comment]
Closing: this isn't a bug in DBAL, but just how you configured your system.
