### ISSUE TITLE
BC Break in 2.9.0 for MySQL Tables containing partitions

### ISSUE THREAD

**Issue by bcremer** [doctrine/dbal#3398]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.0

#### Summary

Commit https://github.com/doctrine/dbal/commit/a7cffda89e6154cf75502f250d0120523e73fac0#r31615323 introduces a regression for MySQL Tables that are Partitioned.

May be related to https://github.com/doctrine/dbal/issues/3389.

#### Previous behaviour

`\Doctrine\DBAL\Schema\AbstractSchemaManager::listTableDetails` emits no PHP Notice for MySQL Tables that are Partitioned.

#### Current behavior

`\Doctrine\DBAL\Schema\AbstractSchemaManager::listTableDetails` emits PHP Notice for MySQL Tables that are Partitioned.

#### How to reproduce

Add the following testcase to `tests/Doctrine/Tests/DBAL/Functional/Schema/MySqlSchemaManagerTest.php`:

```php
    public function testEnsureTableOptionsSupportPartitionedTables() : void
    {
        $this->connection->query('DROP TABLE IF EXISTS test_table_partitioned');

        $sql = <<<'SQL'
CREATE TABLE test_table_partitioned (
  col1 INT NOT NULL AUTO_INCREMENT PRIMARY KEY
) 
COLLATE=utf8mb4_unicode_ci
ENGINE=InnoDB 
PARTITION BY RANGE (col1) (
 PARTITION p1 VALUES LESS THAN (2) ENGINE = InnoDB,
 PARTITION pMax VALUES LESS THAN MAXVALUE
)
SQL;

        $this->connection->query($sql);
        $onlineTable = $this->schemaManager->listTableDetails('test_table_partitioned');

        self::assertEquals(['partitioned' => true], $onlineTable->getOption('create_options'));
    }
```

```
 MySQL> SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'redacted';
+--------+----------------+--------------------+---------------+----------------+
| ENGINE | AUTO_INCREMENT | TABLE_COLLATION    | TABLE_COMMENT | CREATE_OPTIONS |
+--------+----------------+--------------------+---------------+----------------+
| InnoDB |           NULL | utf8mb4_unicode_ci |               | partitioned    |
+--------+----------------+--------------------+---------------+----------------+
1 row in set (0.00 sec)
```

This will emit a PHP Notice:

```
PHP Notice: Undefined offset: 1 in /home/apidev/current/vendor/doctrine  
  /dbal/lib/Doctrine/DBAL/Schema/MySqlSchemaManager.php on line 319
```

**Comment by Ocramius** [comment]
Not a BC break: partitioned tables were never really supported by the schema tooling.

**Comment by bcremer** [comment]
Fair enough. Still the schemamanager was perfectly usable for partitioned tables before.
This bug may also effect other `CREATE_OPTIONS` that are not formatted as `key=value`.

Would you accept a patch that fixes CREATE_OPTIONS parsing for non key/value pairs?

**Comment by Ocramius** [comment]
Sure thing: send in the test that you're mentioning in the OP first, then add commits with a fix if you think you already have one

**Comment by bcremer** [comment]
@Ocramius Nevermind. This was already fixed in the 2.9 Branch by @morozov. See: https://github.com/doctrine/dbal/commit/6e1bb8027b8da05fee207bd58a95d4a90ed70e7e

**Comment by Ocramius** [comment]
@bcremer is the test still relevant though?

**Comment by bcremer** [comment]
The relevant testcase is already included in https://github.com/doctrine/dbal/commit/6e1bb8027b8da05fee207bd58a95d4a90ed70e7e#diff-921db63349be598a376afb1584ccc8b5.

**Comment by Ocramius** [comment]
Marking as duplicate of #3393 then :+1:
