### ISSUE TITLE
Problem with mixed parameters - SQLAnywhere

### ISSUE THREAD

**Issue by cbsan** [doctrine/dbal#3402]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.0

#### Summary

Query issues passing several mixed parameter types to the setParameter. When executing the query I am having type conversion problems, having as output "Cannot convert 'param string' into a numeric".
I am currently using php 7.1.24 and sqlanywhere 16

#### Current behaviour

Cannot convert 'param string' to a numeric.

#### How to reproduce
```
<?php
$query = $conn->createQueryBuilder();

$query->select('*')
    ->from('sampleTable')
    ->where('fieldInteger = ?')
    ->andWhere('fieldString = ?');

$query->setParameter(0, 1)
     ->setParameter(1, 'param string');

$query->execute()->fetchAll();
```

#### Expected behaviour

Return of query records

**Comment by Ocramius** [comment]
@cbsan are those supposed to be `?0` and `?1` (in your code sample)?

**Comment by cbsan** [comment]
@Ocramius , was referring to use the placeholder? syntax, sorry for my mistake. (:

Sample:
```
<?php
$query = $conn->createQueryBuilder();

$query->select('*')
    ->from('sampleTable')
    ->where('fieldInteger = ?')
    ->andWhere('fieldString = ?');

$query->setParameter(0, 1)
     ->setParameter(1, 'param string');

$query->execute()->fetchAll();

```

**Comment by SenseException** [comment]
@cbsan What is the resulting SQL query from the builder when you get the output of `$query->getSQL()`?

**Comment by cbsan** [comment]
@SenseException, this returns me the select before the bind of the parameters occurs.
In case it would have:
```SELECT * FROM sampleTable WHERE fieldInteger = ? AND fieldString = ?```
The bind occurs at the time of the $ query-> execute (), at that moment I'm having problems: /

**Comment by morozov** [comment]
Closing as SQLAnywhere is no longer supported.
