### ISSUE TITLE
The changes from #3392 break indexes with a fixed length

### ISSUE THREAD

**Issue by leofeyer** [doctrine/dbal#3409]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.9.1

#### Summary

The changes from #3392 break indexes with a fixed length.

#### Previous behaviour

```php
$table = new Table('test');
$table->addColumn('path', 'text');
$table->addIndex(['path' => 'path(768)'], 'path', [], ['lengths' => [768]]);
```

This added the following index:

<img width="411" alt="" src="https://user-images.githubusercontent.com/1192057/50007823-70692280-ffb2-11e8-872d-ae39fc67fb11.png">

#### Current behavior

```
Doctrine\DBAL\Schema\SchemaException:
There is no column with name 'path(768)' on table 'test'.
```

The exception seems to occur due to the removal of the following lines in the `Table::_createIndex()` method:

```php
        if (is_numeric($columnName) && is_string($indexColOptions)) {
            $columnName = $indexColOptions;
        }
```

**Comment by leofeyer** [comment]
We have been using it since Doctrine DBAL 2.6, however, you are right about the `lengths` option, which we have only added very recently. Before that the code looked like this:

```php
$table = new Table('test');
$table->addColumn('path', 'text');
$table->addIndex(['path' => 'path(768)'], 'path');
```

**Comment by morozov** [comment]
@leofeyer it doesn't look like valid usage to me. The first argument of `Table::addIndex()` has always been `array $columnNames`.

**Comment by leofeyer** [comment]
> it doesn't look like valid usage to me

Ok, then please tell me how to achieve the following data structure:

<img width="411" alt="" src="https://user-images.githubusercontent.com/1192057/50058315-b53db680-0176-11e9-9b3d-f16b80504716.png">

Because this is exactly what `$connection->getSchemaManager()->createSchema()` returns and also what phpMyAdmin creates:

<img width="616" alt="" src="https://user-images.githubusercontent.com/1192057/50058345-2c734a80-0177-11e9-96b6-c17a9e8f63a0.png">

And it cannot be created like this

```php
$table->addIndex(['path'], 'path(768)', [], ['lengths' => [768]]);
```

because it will end in an `Invalid index-name path(768) given, has to be [a-zA-Z0-9_]` exception.

So how do I accomplish it?

**Comment by morozov** [comment]
@leofeyer does the approach covered in https://github.com/doctrine/dbal/issues/3409#issuecomment-447411653 work for you?

**Comment by leofeyer** [comment]
No, it does not, because it does not set the correct column name. The column name needs to be `path(768)` to match the return value of `$schemaManager->createSchema()`.

### Create schema from database

```sql
CREATE TABLE test (path text NULL);
CREATE INDEX path ON test (path(768));
```

```php
$connection = $this->get('database_connection'); // Symfony DI container
dump($connection->getSchemaManager()->createSchema()->getTable('test'));
```

<img width="428" alt="" src="https://user-images.githubusercontent.com/1192057/50073360-ab4c9f80-01d8-11e9-8fc5-e7d1a35ac1ea.png">

### Create schema manually

```php
$table = new Table('test');
$table->addColumn('path', 'text');
$table->addIndex(['path'], 'path', [], ['lengths' => [768]]);
dump($table);
```

<img width="431" alt="" src="https://user-images.githubusercontent.com/1192057/50073545-35950380-01d9-11e9-8b26-279767684f53.png">

And because of this difference, `Schema::getMigrateToSql()` no longer handles the index correctly.

### Another possible solution

Maybe `$table->addIndex(['path'], 'path', [], ['lengths' => [768]]);` should just add the index length to the column name? Then the manual schema would match the created schema again.

**Comment by morozov** [comment]
The column name needs to be `path(768)` to match the return value of `$schemaManager->createSchema()`.

It should be the opposite. `path(768)` is not a column name. It's an SQL expression representing an index column (by name) and its length.

> ```sql
> CREATE TABLE test (path text NULL);
> CREATE INDEX path ON test (path(768));
> ```

When a table is created from its definition by the DBAL, the SQL looks like:
```sql
CREATE TABLE index_length (
    path TEXT NULL,
    INDEX IDX_18E36143B548B0F (path(768))
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
```
and the introspection works correctly (the following test passes):
```php
public function testIndexLength()
{
    $table = new Table('index_length');
    $table->addColumn('path', 'text');
    $table->addIndex(['path'], null, [], ['lengths' => [768]]);

    $this->schemaManager->dropAndCreateTable($table);

    $indexes = $this->schemaManager->listTableIndexes('index_length');
    self::assertCount(1, $indexes);

    $index = array_shift($indexes);
    self::assertEquals(['path'], $index->getColumns());
    self::assertEquals([768], $index->getOption('lengths'));
}
```

It also passes with your syntax:
```php
public function testIndexLength()
{
    $this->schemaManager->tryMethod('dropTable', 'index_length');
    $this->connection->exec('CREATE TABLE index_length (path text NULL)');
    $this->connection->exec('CREATE INDEX path ON index_length (path(768))');

    $indexes = $this->schemaManager->listTableIndexes('index_length');
    self::assertCount(1, $indexes);

    $index = array_shift($indexes);
    self::assertEquals(['path'], $index->getColumns());
    self::assertEquals([768], $index->getOption('lengths'));
}
```
In both cases, the index is introspected correctly as having one column `path` and its indexed length `768`. Could you please provide a failing case similar to the above? Right now I don't see where the problem is.

**Comment by leofeyer** [comment]
> It should be the opposite. `path(768)` is not a column name. It's an SQL expression representing an index column (by name) and its length.

Either way, `Schema::getMigrateToSql()` is broken now in version 2.9.1 due to the column name being different from the one returned by `$schemaManager->createSchema()`.

@beberlei @Ocramius Maybe you can take a look at this issue as well? I have already provided code samples and screenshots in https://github.com/doctrine/dbal/issues/3409#issuecomment-447753599 and I don't know how to elaborate even more on the issue. It seems we are stuck here. 🙈

**Comment by Ocramius** [comment]
@leofeyer I haven't got the slightest clue: @morozov already provided a test scenario, it is up to you to provide a failing test case now.

**Comment by leofeyer** [comment]
Ok, will do tomorrow.

**Comment by leofeyer** [comment]
So here is the failing test:

```php
public function testUpdatesIndexLength()
{
    $this->connection->exec('CREATE TABLE index_length (path text NULL)');
    $this->connection->exec('CREATE INDEX path ON index_length (path(333))');

    $table = new Table('index_length');
    $table->addColumn('path', 'text', ['notnull' => false]);
    $table->addIndex(['path'], 'path', [], ['lengths' => [768]]);

    $fromSchema = $this->connection->getSchemaManager()->createSchema();
    $toSchema = new Schema([$table]);

    $diff = $fromSchema->getMigrateToSql($toSchema, $this->connection->getDatabasePlatform());

    self::assertContains('ALTER TABLE index_length DROP INDEX path, ADD INDEX path (path(768))', $diff);
}
```

**Comment by Ocramius** [comment]
Can you please send that in a PR? That would basically restart the issue from a fresh/solid ground 👍

**Comment by leofeyer** [comment]
Sure, if you tell me in which class the test belongs.

**Comment by morozov** [comment]
@leofeyer thank you for the test. I'll figure out first what exactly is broken and then we'll see where the test belongs.
