### ISSUE TITLE
Bind Array to Statement

### ISSUE THREAD

**Issue by kutchbhi** [doctrine/dbal#3431]
Version     : 2.9

### Question

Binding Arrays is clearly supported. As its written in the docs. But only with the executeQuery() . Afaik this means query is prepare() every time executeQuery is run. such a waste..

Any suggestion?  There  can easily be a $stmt->bindArray($arr) . _bindTypedValues is an internal function 

Docs: https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/data-retrieval-and-manipulation.html#binding-types

**Comment by Ocramius** [comment]
Not possible, since DBAL has to rewrite the SQL query whenever an `array` parameter is met. A prepared statement does not allow changing the SQL anymore, since it was already "prepared".
