### ISSUE TITLE
Composite unique index for field + relation id field?

### ISSUE THREAD

**Issue by BonBonSlick** [doctrine/dbal#3434]
doctrine/annotations                           v1.6.0             Docblock Annotations Parser
doctrine/cache                                 v1.8.0             Caching library offering an object-oriented API for many cache backends
doctrine/collections                           v1.5.0             Collections Abstraction library
doctrine/common                                v2.9.0             Common Library for Doctrine projects
doctrine/data-fixtures                         v1.3.1             Data Fixtures for all Doctrine Object Managers
doctrine/dbal                                  v2.8.0             Database Abstraction Layer
doctrine/doctrine-bundle                       1.9.1              Symfony DoctrineBundle
doctrine/doctrine-cache-bundle                 1.3.3              Symfony Bundle for Doctrine Cache
doctrine/doctrine-fixtures-bundle              3.0.2              Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle            v1.3.1             Symfony DoctrineMigrationsBundle
doctrine/event-manager                         v1.0.0             Doctrine Event Manager component
doctrine/inflector                             v1.3.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/instantiator                          1.1.0              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                                 v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/migrations                            v1.8.1             Database Schema migrations using Doctrine DBAL
doctrine/orm                                   v2.6.2             Object-Relational-Mapper for PHP
doctrine/persistence                           v1.0.1             Doctrine Persistence abstractions.
doctrine/reflection                            v1.0.0             Doctrine Reflection component

### Support Question

Is there composite unique constraints on field + relational field?

<?xml version="1.0" encoding="UTF-8"?>

```
<doctrine-mapping>
....
    <!-- Composite unique fields -->
    <unique-constraints>
      <unique-constraint columns="sequence,season" name="unique_sequence_season_episode_details" />
    </unique-constraints>
....
    <embedded name="sequence" class="App\ValueObject\Sequence"
              use-column-prefix="false" />
....
    <!-- One To One-->
    <one-to-one target-entity="App\Entity\Episode" field="episode" inversed-by="details">
      <join-column name="episode_uuid" referenced-column-name="id.uuid" />
    </one-to-one>

</doctrine-mapping>
```

[There is ](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/xml-mapping.html#defining-indexes-or-unique-constraints) no word about relationю Or this vague description means that is no possible to do so?

> and not the entity-class field names

If so maybe call it or add also relation entity and give and example like in question?

**Comment by Ocramius** [comment]
Composite constraints are defined on columns, not fields. You'd need to use the actual column name instead of the field name.

In your case, assuming sequence has a single field, you'd write something like following:

```xml
    <unique-constraints>
      <unique-constraint
        columns="sequence_seuence,episode_uuid"
        name="unique_sequence_season_episode_details"
      />
    </unique-constraints>
```

**Comment by Ocramius** [comment]
Moving this to ORM, since it's only related to mappings there.
