### ISSUE TITLE
CreateSavepoint method does not connect automatically to the database

### ISSUE THREAD

**Issue by tezvi** [doctrine/dbal#3437]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.9.1

#### Summary

When executing createSavepoint method on Connection instance PHP halts with null reference exception. The connection was not previously established.

#### Current behaviour

When executing Doctrine\DBAL\Connection::createSavepoint without previously issued queries or opened transaction an error occurs: "Call to a member function exec() on null".
https://github.com/doctrine/dbal/blob/9b88bf3711b8472e75cae98e947a20f0df202d77/lib/Doctrine/DBAL/Connection.php#L1386

#### How to reproduce

Make sure to call Doctrine\DBAL\Connection::createSavepoint when no connection was previously established.

#### Expected behaviour

The method should explicitly call Doctrine\DBAL\Connection::connect to create connection before issuing a SAVEPOINT query to the database.
The same behavior is already implemented for Doctrine\DBAL\Connection::beginTransaction and Doctrine\DBAL\Connection::rollBack methods.
The same approach could be also applied to Doctrine\DBAL\Connection::releaseSavepoint and Doctrine\DBAL\Connection::rollbackSavepoint.

**Comment by Ocramius** [comment]
Would you be able to send in a test and a fix? Adding a `$this->connect()` call seems trivial, but we need a test case to prevent a regression.

**Comment by tezvi** [comment]
Sure, I'll give it a go.

What do you think should we also log SAVEPOINT related queries like here:
https://github.com/doctrine/dbal/blob/9b88bf3711b8472e75cae98e947a20f0df202d77/lib/Doctrine/DBAL/Connection.php#L1249-L1251

**Comment by Ocramius** [comment]
That would make a lot of sense, yes

**Comment by tezvi** [comment]
@Ocramius it seems it has already been fixed thx to @morozov https://github.com/doctrine/dbal/pull/3443

**Comment by morozov** [comment]
@tezvi yes. It was detected by PHPStan as calling a method on a potentially null value.

**Comment by tezvi** [comment]
Nice, case closed then :)
The only thing that might be missing is proper SQL logging. It is provided by rollback and commit methods (hardcoded), but could be reused from platform instance createSavePoint and releaseSavepoints. What do you think?

Example: https://github.com/doctrine/dbal/blob/29c7ba6ae625c03e9a36515e67e791c746f8ed83/lib/Doctrine/DBAL/Connection.php#L1350

**Comment by morozov** [comment]
@tezvi not sure what this is about. Is something not logged when it's supposed to be? Please feel free to file a new issue.
