### ISSUE TITLE
No Support for Postgres 'interval' data type

### ISSUE THREAD

**Issue by mattdillon100** [doctrine/dbal#3448]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.9.2

#### Summary

There is currently no support for setting and/or getting field data for a Postgres `interval` data type field when using PHP's `DateInterval` object.

#### Current behavior

When saving a DateInterval object as a Postgres interval, Postgres throws an error due to doctrine applying a `+` or `-` before the formatted string.

When trying to retrieve a value, Postgres returns a string such as `3 years 10 mons 1 day 02:18:00`. Doctrine has no built in functionality to handle this.

#### How to reproduce

1. Create a table in a Postgres DB with a field that has an interval data type
```
CREATE TABLE sample(
 start_time TIMESTAMP,
 end_time TIMESTAMP,
 duration INTERVAL
);
```

2. Create an entity for the table

```
...
/**
 * @ORM\Column(type="datetime")
 * @var \DateTime
 */
private $startTime;

/**
 * @ORM\Column(type="datetime")
 * @var \DateTime
 */
private $endTime;

/**
* @ORM\Column(type="dateinterval")
* @var \DateInterval
*/
 private $duration;

/**
 * @return \DateTimeInterface
 */
public function getStartTime(): \DateTimeInterface
{
    return $this->startTime;
}

/**
 * @param \DateTimeInterface $startTime
 *
 * @return $this
 */
public function setStartTime(\DateTimeInterface $startTime): self
{
    $this->startTime = $startTime;
    return $this;
}

/**
 * @return \DateTimeInterface
 */
public function getEndTime(): \DateTimeInterface
{
    return $this->endTime;
}

/**
 * @param \DateTimeInterface $endTime
 *
 * @return $this
 */
public function setEndTime(\DateTimeInterface $endTime): self
{
    $this->endTime = $endTime;
    return $this;
}

/**
 * @return \DateInterval
 */
public function getDuration(): \DateInterval
{
    return $this->duration;
}

/**
 * @ORM\PrePersist()
 *
 * @return $this
 */
public function setDuration(): self
{
    $interval = $this->startTime->diff($this->endTime);
    $this->duration = $interval;

    return $this;
}
```

3. Try to set a start and end time. This will then save the difference between the 2 times in a DateInterval object.

Dbal converts the DateInterval to a string using `DateInterval::format('%RP%YY%MM%DDT%HH%IM%SS')`. This will cause Postgres (tested on 9.5 & 10) to throw an "invalid format" error. This is due to the `%R` at the beginning. Removing this allows the value to be saved. This is performed in `doctrine/dbal/lib/Doctrine/DBAL/Types/DateIntervalType.php`.

Upon calling `getDuration()`, Postgres spits out the interval as a string, such as `3 years 10 mons 1 day 02:18:00`. Dbal then tries to directly convert this string into a DateInterval object and, of course, falls over with an \Exception because the string format is not recognised by PHP's DateInterval class.

#### Expected behavior

We should be able to feed the ORM/Dbal a DateInterval object that will be saved as an `interval` in Postgres. We should also receive a `DateInterval` object back from getting an interval Postgres field value.

**Comment by loripolve** [comment]
I propose a solution: 

Since PHP does not support mixed-signs interval, it's possible to convert positive intervals as before but without the sign at the beginning of the string. Instead for negative intervals is possible to add "-" before each number (e.g. P-00Y-00M-00DT-01D-30M-00S).

I think this strategy works for Postgres but I don't know for others DBMSs.

**Comment by rela589n** [comment]
Will this issue proceed any further? Seems there's not that much activity here.

**Comment by morozov** [comment]
We will not add support for this type since it's not portable.
