### ISSUE TITLE
MySQL limit parameter must not be a string

### ISSUE THREAD

**Issue by andig** [doctrine/dbal#3459]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    |no
| Version     | 2.9.2

#### Summary

Cannot pass an integer limit in this query with pdo_mysql driver:

    $stmt = $conn->executeQuery('SELECT 1 FROM data LIMIT ?', [1]);

#### Current behaviour

    PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''1''at line 16 in /Users/andig/htdocs/influx/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117

#### How to reproduce

Run above query on MySQL version: 8.0.15 Homebrew

#### Expected behaviour

No exception

**Comment by Ocramius** [comment]
Parameter binding does not work within the `LIMIT` clause: this is a PDO limitation.
