### ISSUE TITLE
Q: is it possible to allow Doctrine Schema Manager to list db schema elements without trying to alter them with Migrations?

### ISSUE THREAD

**Issue by gggeek** [doctrine/dbal#3460]
|    Q        |   A
|------------ | -----
| Version     | 2.5.4

Usecase: a table in the db is not managed via Doctrine ORM.
The app uses Doctrine DBAL to access the data in the table. It also has code to manage the table definition in the DB, including creating it and updating it if needed, and uses the Doctrine Schema Manager solely to find out if the table exists and how it is currently defined.

Problem:
- running `bin/console doctrine:migrations:diff`, Doctrine generates a Drop Table sql, as it assumes it has to manage the table. That statement is not welcome
- but if I list the table in the dbal configuration `schema_filter`, then my code will not be capable any more of inspecting the table using the SchemaManager. Which leaves me with the ugly option of having to write custom ddl for each database (yuk!)

Is it possible to configure Doctrine (or Symfony) in a way that the database table is not "managed" by Doctrine (so not touched by migrations commands) but it is still "inspectable" by it?

**Comment by Ocramius** [comment]
I'd say that you need a custom `Doctrine\DBAL\Schema\Comparator` implementation: if you have that, you can either re-add the tables to the schema diff, or you can add the tables in the source schema before diffing.

The implementation would probably be a decorator to the existing `Comparator`.
