### ISSUE TITLE
I am trying to addColumn but it is not working

### ISSUE THREAD

**Issue by satalways** [doctrine/dbal#3462]
|    Q        |   A
|------------ | -----
| Version     | 2.9

I am trying to add column using these codes but column is not added in table.

$sm = $dbconn->getSchemaManager();
$table = $sm->listTableDetails( 'admins');
$table->addColumn('newint', 'integer')->setDefault( 0);

Can anyone help me?

**Comment by Majkl578** [comment]
> it is not working

Please expand on what's not working, i.e. provide at least an error message, stack trace or similar.
