### ISSUE TITLE
listTableIndexes() isn't work  in lumen framework

### ISSUE THREAD

**Issue by Tyraan** [doctrine/dbal#3464]
### listTableIndexes() isn't work  in lumen framework 

I use the code like below  with lumen & doctrine/dbal  in  migration files 
```
Schema::table('persons', function (Blueprint $table) {
    $sm = Schema::getConnection()->getDoctrineSchemaManager();
    $indexesFound = $sm->listTableIndexes('persons');

    if(array_key_exists("persons_body_unique", $indexesFound))
        $table->dropUnique("persons_body_unique");
})
```
which I find that  listTableIndexes method is totally not work  even the table has many indexes

**Comment by SenseException** [comment]
Can you please be more specific what does not work and can you create an example without Lumen? For the DBAL project, this has to be recreated without the framework.

**Comment by Ocramius** [comment]
Closing here: requires a test case next time.

Also, please make the issue framework-agnostic first.
