### ISSUE TITLE
DriverTest::testDatabaseParameters() is unstable

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3471]
|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.0-dev

In the last couple of weeks, I've seen this test failing a few times for no reason.

When running against PostgreSQL, it may [fail](https://travis-ci.org/doctrine/dbal/jobs/498266025) like this:
```
1) Warning
The data provider specified for Doctrine\Tests\DBAL\Functional\Driver\PDOPgSql\DriverTest::testDatabaseParameters is invalid.
An exception occurred in driver: SQLSTATE[08006] [7] server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

When running against MySQL (yes), it may [fail](https://travis-ci.org/doctrine/dbal/jobs/496130765) like this:
```
1) Warning
The data provider specified for Doctrine\Tests\DBAL\Functional\Driver\PDOPgSql\DriverTest::testDatabaseParameters is invalid.
An exception occurred in driver: SQLSTATE[HY000] [2006] MySQL server has gone away
```

In its data provider, the test tries to detect the database name specified in the connection parameters and by that triggers the database connection while the database seems to be not yet ready.

**Comment by Majkl578** [comment]
Relevant PR:  #3426
