### ISSUE TITLE
PostgreSQL: Not null violation: 7 ERROR: null value in column “id” violates not-null constraint

### ISSUE THREAD

**Issue by videni** [doctrine/dbal#3493]
hi, I have this strange problem, please check this link [postgresql-not-null-violation-7-error-null-value-in-column-id-violates-not](https://stackoverflow.com/questions/55222800/postgresql-not-null-violation-7-error-null-value-in-column-id-violates-not)

**Comment by Ocramius** [comment]
Closing here: this is already asked in the right place (Stackoverflow).
