### ISSUE TITLE
Incorrect phpDoc

### ISSUE THREAD

**Issue by SunMar** [doctrine/dbal#3496]
### Bug Report

DBAL: 2.9.2
B/c break: no

#### Summary

Hi,

While dealing with #3490 I discovered that Doctrine is using an incorrect phpDoc syntax. Throughout the code Doctrine I see the follow docblocks:

```
    /**
     * {@inheritDoc}
     */
```

However that is [invalid phpDoc usage](http://docs.phpdoc.org/guides/inheritance.html#the-inheritdoc-tag). The `{@inheritDoc}` is to be able to in-line import specifically the _description_ of the parent method. If it is used standalone, it basically has no meaning and is redundant. The description is [already inherited from the parent](http://docs.phpdoc.org/guides/inheritance.html#methods), as well as several others. But everything that is inherited is done so automatically and not via `{@inheritDoc}`. `{@inheritDoc}` also does not cause anything except the description to be inherited.

#### Current behaviour

The issue where I ran into this specifically is with `@deprecated`. In `Type` the method `getDefaultLength()` is marked as `@deprecated`. However in `StringType` it is not marked as `@deprecated`. This means that both the phpDocumentor and IDEs such as PhpStorm will not flag `StringType->getDefaultLength()` as being a deprecated method, since `{@inheritDoc}` only redundantly inherits the description, not the `@deprecated` tag. Which makes sense, just because `Type` has deprecated `getDefaultLength()`, doesn't mean `StringType` also has it deprecated. Then you would have to add some kind of `@not-deprecated` tag, which would be weird.

Due to this I actually implemented `getDefaultLength()` because I didn't get a warning that it was deprecated.

#### How to reproduce

You can even see it in the Doctrine API documentation. If you go to [`Type->getDefaultLength()`](https://www.doctrine-project.org/api/dbal/2.9/Doctrine/DBAL/Types/Type.html#method_getDefaultLength) you see that the method is marked as deprecated. However there is no deprecation notice for [`StringType->getDefaultLength()`](https://www.doctrine-project.org/api/dbal/2.9/Doctrine/DBAL/Types/StringType.html#method_getDefaultLength).

#### Expected behaviour

Docblocks containing only `{@inheritDoc}` should be re-evaluated. They should perhaps be completely removed, or at the very least any tags that are meant to be inherited but [are not done so by default](http://docs.phpdoc.org/guides/inheritance.html) like `@deprecated` should be copied over to the child docblocks, so that the phpDoc behavior becomes consistent with what was intended.

**Comment by Ocramius** [comment]
This has been this way for a decade now: it actually got as far as making phpDocumentor change its behavior for `{@inheritDoc}`.

Closing as `won't fix` here.

**Comment by SunMar** [comment]
@Ocramius I don't understand why this is closed as a won't fix when Doctrine's own API documentation that I linked in the "How to reproduce" section shows that just using `{@inheritDoc}` does not produce correct results. At the very least you can fix the `@deprecated` tag for `StringType` since phpDocumentor does not adhere to the behavior you are mentioning. Or are you not using phpDocumentor?

**Comment by Ocramius** [comment]
We have a build generating those API docs, but mostly because there's still a couple users that browse them: otherwise unused and not worth pursuing further.
