### ISSUE TITLE
Connection and Driver API should only use same-level exceptions

### ISSUE THREAD

**Issue by Majkl578** [doctrine/dbal#3506]
Driver API should only throw DriverException and descendants, not DBALException directly.
Connection API should hide driver-specific exceptions (DriverException and descendants), only attach those in `$previous` and throw DBALException (or rather some new ConnectionException).

**Comment by morozov** [comment]
I'm going to close this since this has been primarily addressed in 3.0.0. There may be some leftovers (e.g. platform detection is a driver-level concern implemented using the DBAL level API) but those are better reported and addressed individually.
