### ISSUE TITLE
Construct connection from existing mysqli resource

### ISSUE THREAD

**Issue by JeroenDeDauw** [doctrine/dbal#3510]
DBAL allows constructing a DBAL Connection object from an existing PDO object as follows:

```php
$connection = DriverManager::getConnection( [ 'pdo' => $pdo ] )
```

Is there a way to do the same for a mysqli resource?

At the moment I am [creating my own DBAL\Driver and Driver\Connection](https://github.com/wmde/mediawiki-doctrine-connection/tree/cdc44e37845b0cefed2329d9442ddd948a19a484/src/PackagePrivate). That allows me to construct a DBAL\Connection with my mysqli resource. I'd prefer having a cleaner way, as is possible with PDO.

**Comment by morozov** [comment]
There's no plan to support constructing connections from existing resources.

**Comment by JeroenDeDauw** [comment]
So a PR to add this feature is not welcome?

**Comment by morozov** [comment]
No. If we implement it, we'll have to support all use cases and  like "I'm using my own connection and…" which is impossible. I can imagine a use case for what you're asking but it's not common and as long as it's possible to implement it by extending the existing components, it's good enough.

**Comment by JeroenDeDauw** [comment]
Ok, fair enough. Thanks for the quick replies.
