### ISSUE TITLE
Schema always add CREATE SEQUANCE

### ISSUE THREAD

**Issue by Pizgu** [doctrine/dbal#3522]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | PostgreSQL 10.7 (Ubuntu 10.7-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0, 64-bit

#### Summary

Why Doctrine didn't update sequences as it should done? It didn't remove it but try to update on already existing sequences.
Please explain me how to fix it or repair this.

#### How to reproduce

     CREATE SEQUENCE vehicle_external_copy_external_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE worksteps_workstep_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE depot_types_depot_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE park_lines_park_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE workshop_companies_workshop_company_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE ecu_parameter_sets_ecu_parameter_set_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE config_parameters_parameter_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE responsibility_ecus_fev_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE vupdate_vid_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE depot_tmp_depot_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE country_codes_country_code_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE options_groups_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE qs_fault_categories_qs_fcat_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE processed_teo_status_diagnostic_session_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE temp_teo_status_diagnostic_session_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE delivery_plan_variant_values_delivery_plan_variant_values_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE service_status_name_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE thirdparty_orders_order_num_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE c2c_unassigned_c2cbox_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE vehicle_eol_status_vehicle_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE c2c_configuration_c2cbox_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE vehicles_failed_vins_c2cbox_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE workstations_workstation_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE error_recipients_error_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE migration_versions_version_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE SEQUENCE user_role_company_structure_fev_id_seq INCREMENT BY 1 MINVALUE 1 START 1;
     CREATE TABLE migration_versions (version VARCHAR(14) NOT NULL, executed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(version));

#### Expected behaviour

Run once and it fix schema.

**Comment by jwage** [comment]
Hi, thanks for the issue. We would need more information like a reproducible test in order to help. I am going to go ahead and close this issue but if you feel there is a bug and you can provide more information to help us triage the problem, please feel free to reopen.
