### ISSUE TITLE
problem extending MariaDb1027Platform

### ISSUE THREAD

**Issue by poolerMF** [doctrine/dbal#3537]
there is no way to extend MariaDb1027Platform, becouse in MySqlSchemaManager there is hardcoded condition "$this->_platform instanceof MariaDb1027Platform"

solution 1:
- remove final from class MariaDb1027Platform

solution 2:
- update condition, make it general ... (for example create MariaDbInterface)

same problem:
https://github.com/doctrine/dbal/issues/3273 [Make MariaDb1027Platform non-final?](https://github.com/doctrine/dbal/issues/3273)
https://github.com/doctrine/dbal/issues/3126 [Allow extending MariaDb1027Platform class](https://github.com/doctrine/dbal/issues/3126)

**Comment by morozov** [comment]
Closing based on https://github.com/doctrine/dbal/issues/3126#issuecomment-385955760.
