### ISSUE TITLE
Generation of unnecessary foreign keys in Postgresql

### ISSUE THREAD

**Issue by tasselchof** [doctrine/dbal#3551]
When you use partitioning for table in PostgreSQL it's not possible to make foreign key. But doctrine generating this instruction on schema update:

`ALTER TABLE linker_refund_items ADD CONSTRAINT FK_A4DF5D5E126F525E FOREIGN KEY (item_id) REFERENCES storage_items (id) NOT DEFERRABLE INITIALLY IMMEDIATE;`

Which is leading to errors:

> [2019-05-22 20:24:34] [42809] ERROR: cannot reference partitioned table "storage_items"

Partitioning is made on DB level (by function), so practically doctrine working well with such a table except this issue.

**Comment by Ocramius** [comment]
The ORM assumes that the DB has FKs for PostgreSQL (in general): the fact that some scenarios require disabling FKs, especially with something as complex as partitioning, you really want to manage schema changes via migrations, and use the schema tool only for getting you a stub of how to migrate (to be edited by a developer).
