### ISSUE TITLE
Incorrect behaviour Doctrine\DBAL\Schema\Table::dropPrimaryKey().

### ISSUE THREAD

**Issue by nmuntyanov** [doctrine/dbal#3567]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.5.0 - 2.9.3

#### Summary
I'm using doctrine migrations in symfony project and I found that there is an issue when I'm trying to delete table's primary key and add another index. 

#### Current behaviour

```
 $financialRawData = $schema->getTable("tableName");
 if ($financialRawData->hasPrimaryKey()) {
    $financialRawData->dropPrimaryKey();
 }
$indexName = "some_unique_index_name";
if (!$table->hasIndex($indexName)) {
   $table->addUniqueIndex(["column_1", "column_2"], $indexName);
}
```
This piece of code produces such query:
```'ALTER TABLE tableName DROP INDEX PRIMARY, ADD UNIQUE INDEX some_unique_index_name (column_1, column_2)'```
 and MYSQL fails with:
```SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'PRIMARY, ADD UNIQUE INDEX some_unique_index_name (column_1' at line 1```

#### Expected behaviour

There 2 ways to solve this issue:
- Add quotes around `PRIMARY` keyword: 
```'ALTER TABLE tableName DROP INDEX `PRIMARY`, ADD UNIQUE INDEX some_unique_index_name (column_1, column_2)'```
- Change `DROP INDEX PRIMARY` to `DROP PRIMARY KEY`:
```'ALTER TABLE tableName DROP PRIMARY KEY, ADD UNIQUE INDEX some_unique_index_name (column_1, column_2)'```

**Comment by SenseException** [comment]
`DROP INDEX PRIMARY` sounds like an index that was named "primary". Can you please create a pull request with a failing test to recreate your described issue?

**Comment by morozov** [comment]
This is not reproducible with the following test on `3.3.8`, `3.5.x` and `4.0.x` (all slightly different implementations):
```php
$schema = new Schema();

$table = $schema->createTable('test');
$table->addColumn('id', 'integer');
$table->setPrimaryKey(['id']);

$schemaManager = $this->connection->createSchemaManager();
$schemaManager->migrateSchema($schema);

$table->dropPrimaryKey();
$schemaManager->migrateSchema($schema);
```
Must have been fixed earlier.
