### ISSUE TITLE
Mark eligible classes final

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3585]
The issue was originally raised in https://github.com/doctrine/dbal/pull/3007#issuecomment-362630921.

A quick check with [Ocramius/Finalizer](https://github.com/Ocramius/Finalizer) shows:
```
$ finalizer finalizer:check-final-classes lib/
Following classes need to be made final:
+-----------------------------------------------------------------+
| Doctrine\DBAL\Sharding\ShardChoser\MultiTenantShardChoser       |
| Doctrine\DBAL\Sharding\SQLAzure\Schema\MultiTenantVisitor       |
| Doctrine\DBAL\Sharding\SQLAzure\SQLAzureFederationsSynchronizer |
| Doctrine\DBAL\Sharding\PoolingShardManager                      |
| Doctrine\DBAL\Id\TableGeneratorSchemaVisitor                    |
| Doctrine\DBAL\Driver\OCI8\Driver                                |
| Doctrine\DBAL\Driver\Mysqli\Driver                              |
| Doctrine\DBAL\Driver\Mysqli\MysqliStatement                     |
| Doctrine\DBAL\Driver\PDOSqlsrv\Driver                           |
| Doctrine\DBAL\Driver\PDOSqlsrv\Statement                        |
| Doctrine\DBAL\Driver\PDOMySql\Driver                            |
| Doctrine\DBAL\Driver\IBMDB2\DB2Connection                       |
| Doctrine\DBAL\Driver\IBMDB2\DB2Statement                        |
| Doctrine\DBAL\Driver\IBMDB2\DB2Driver                           |
| Doctrine\DBAL\Driver\SQLSrv\SQLSrvStatement                     |
| Doctrine\DBAL\Driver\SQLSrv\Driver                              |
| Doctrine\DBAL\Driver\SQLSrv\SQLSrvConnection                    |
| Doctrine\DBAL\Driver\SQLAnywhere\SQLAnywhereConnection          |
| Doctrine\DBAL\Driver\SQLAnywhere\Driver                         |
| Doctrine\DBAL\Driver\SQLAnywhere\SQLAnywhereStatement           |
| Doctrine\DBAL\Driver\PDOPgSql\Driver                            |
| Doctrine\DBAL\Driver\PDOOracle\Driver                           |
| Doctrine\DBAL\Driver\PDOSqlite\Driver                           |
| Doctrine\DBAL\Driver\StatementIterator                          |
| Doctrine\DBAL\Cache\ResultCacheStatement                        |
| Doctrine\DBAL\Cache\ArrayStatement                              |
| Doctrine\DBAL\Schema\Synchronizer\SingleDatabaseSynchronizer    |
| Doctrine\DBAL\Schema\Visitor\RemoveNamespacedAssets             |
| Doctrine\DBAL\Portability\Statement                             |
+-----------------------------------------------------------------+
```
For all finalized classes, all their properties and protected methods should be declard private and renamed if they violate the [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#42-properties) naming conventions.

**Comment by mvorisek** [comment]
The world is not perfect nor bug free.

Currently, in the atk4/data project, I fixed a lot of issues by extending the specific DB platform. It works well. Most of the issues, I reported here or even proposed a PR.

Such fixing is impossible when the classes are declared final. Would it be possible to remove the `final` from the driver classes so the oppurtunity to fixing the impl. from the target project side is still possible?

**Comment by derrabus** [comment]
> I fixed a lot of issues by extending the specific DB platform.

The platform classes are not final, so you can continue to do this.

> Would it be possible to remove the `final` from the driver classes so the oppurtunity to fixing the impl. from the target project side is still possible?

I don't believe that this is really necessary. The DBAL has a well defined driver and middleware architecture that should allow you to easily implement your own driver or hook into whatever the bundled drivers are doing.

If you feel like you need to patch the driver classes, these are your options:

* Contribute a fix upstream, if there's really something broken.
* Implement a driver middleware. It should give you the same level of control as overriding public driver methods directly.
* Fork the driver class you need to patch.

**Comment by mvorisek** [comment]
One example are driver `ExceptionConverter` classes. They should not be final.

**Comment by derrabus** [comment]
`ExceptionConverter` implementations can be decorated. You gain nothing by extending them.
