### ISSUE TITLE
Wrong "from" statement if delete query with query builder

### ISSUE THREAD

**Issue by NikitaKharkov** [doctrine/dbal#3601]
### Bug Report

Invalid forming delete SQL part when I set table name in the from SQL part.

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | v2.9.2

#### Summary

So, easy example:
```
$qb->delete()
    ->from($tableName)
    ->where('uuid IN (:uuids)')
    ->setParameter('uuids', $uuids)
    ->execute();
```

#### Current behaviour

I got next structure (dump of `$sqlParts`)
```
...
  "from" => array:1 [
    0 => array:2 [
      "table" => "some_table_name"
      "alias" => null
    ]
  ]
...
```

#### How to reproduce

Just write a query with any table

#### Expected behaviour

instead of this (this is correctly formed if I put `$tablename` in delete SQL part )
```
...
  "from" => array:2 [
    "table" => "some_table_name"
    "alias" => null
  ]
...
```

**Comment by Ocramius** [comment]
Could you write a test case showing a broken usage of this? I don't get where the bug actually is, nor what it leads to.

**Comment by nreynis** [comment]
This is a blocking issue for us, we've got to empty a table. We can't use `connection->delete` without identifiers, and we can't use the query builder neither. Which means we've got to opt out of DBAL and use a raw query.

**Comment by greg0ire** [comment]
@nreynis I might be wrong, but I think OP pointed out that this would work:

> this is correctly formed if I put $tablename in delete SQL part

```php
$qb->delete($tableName)
    ->from()
    ->where('uuid IN (:uuids)')
    ->setParameter('uuids', $uuids)
    ->execute();
```

**Comment by nreynis** [comment]
@greg0ire Indeed using
```php
$qb->delete($tableName)->execute();
```
Works for me. I just saw this syntax when I wrote the test.

> I'm not sure this is the intended use of this API. Can you point us to documentation that would say otherwise? I do concede that it results in a poor user experience

I did not found any example, it just felt natural because that mimic the target SQL query (`DELETE FROM 'table_name'`).  
  
> I also think an acceptable solution would be to trigger a deprecation error when somebody calls delete and then from, and to throw an exception in the next major version of the DBAL.

👍  you could throw a `QueryException` when you access/resolve an uninitialized (empty array) `from` property.

**Comment by nreynis** [comment]
I'm not sure deprecating is even needed. It don't work at all, you won't broke anyone code.

**Comment by greg0ire** [comment]
Good point! Would you like to contribute that?

**Comment by morozov** [comment]
This will be fixed by https://github.com/doctrine/dbal/pull/3833.
