### ISSUE TITLE
sequence not generated in migration with default strategy

### ISSUE THREAD

**Issue by modiniks** [doctrine/dbal#3605]
Symfony upgraded from 4.3.0 to 4.3.1 and with it, doctrine-migrations-bundle got upgraded from version 2.0.2 to 2.1.0. Not sure if it is expected functionality or an issue.

When we try to generate a migration with the default strategy for primary key id, a sequence is not generated for the same. e.g.
`/**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
private $id;
`
When we specify strategy explicitly, sequence is generated and works as earlier.
`
/**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @ORM\Column(type="integer")
     */
private $id;
`

**Comment by Ocramius** [comment]
When using `GeneratedValue(strategy="AUTO")` (which is the default), a serial column is used for postgresql: this is expected.
