### ISSUE TITLE
Allow to set database for schemaManager functions

### ISSUE THREAD

**Issue by sofiiakulish** [doctrine/dbal#3611]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Hello!
I have unusual type of connection. My connection class works with one database for some tables, and another database - for other tables. And when I need to use listTableDetails function ($connection->getSchemaManager()->listTableDetails($tableName)) I should set some parameters for database before using this function, and return them back after. 

Is it possible to add second optional parameter for listTableDetails function as $database? And the same to the listTableIndexes function as a result (lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php) ?

**Comment by morozov** [comment]
That would make sense. Other schema introspection methods like `listTableColumns()` and `listTableForeignKeys()` already accept an optional `$database` argument.

**Comment by lewa** [comment]
There's a 5-year-old pull request _"parameter $database for listTableIndexes, listTableDetails"_:
https://github.com/doctrine/dbal/pull/885

**Comment by morozov** [comment]
Closing in favor of https://github.com/doctrine/dbal/pull/5289.
