### ISSUE TITLE
Default table options: engine: ndbcluster

### ISSUE THREAD

**Issue by timrasche** [doctrine/dbal#3612]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | newest

#### Summary

The setting "doctrine -> dbal -> default_table_options -> engine: ndbcluster" not working...

MySQL: 5.7
PHP: 7.2

and before anyone says foreign keys are not supported by ndbcluster, that's simply wrong!

**Comment by SenseException** [comment]
"The setting ... is not working" isn't really a helpful message. Please add a path how to reproduce this issue in a minimal example and error message and/or, which is much appreciated, create a PR with a failing test for this issue.
