### ISSUE TITLE
Symfony 4 Doctrine DBAL 

### ISSUE THREAD

**Issue by nasrithamer** [doctrine/dbal#3613]
Hello,
when making **php bin/console make:entity** i have this error 
  ```
 Attempted to load class "MySQL57Platform" from namespace "Doctrine\DBAL\Platforms".  
   Did you forget a "use" statement for another namespace?
```

and here also  **php bin/console make:migration**

```
  Attempted to load class "MySqlSchemaManager" from namespace "Doctrine\DBAL\Schema".  
  Did you forget a "use" statement for another namespace? 
```

Any help plz ?

**Comment by Ocramius** [comment]
Hey there, that is very likely to be asked in https://github.com/symfony/maker-bundle, since it isn't related with DBAL directly.

Closing here.
