### ISSUE TITLE
DATETIME not returned as DateTime object.

### ISSUE THREAD

**Issue by abirtles** [doctrine/dbal#3617]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | not sure what this is
| Version     | 2.9.2

#### Summary

The documentation for retrieving an SQL DATETIME column says all values will be converted to a PHP DateTime object, however it is returning a string for me.

SQL info:
Server: 127.0.0.1 via TCP/IP
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.1.37-MariaDB - mariadb.org binary distribution
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

#### Current behaviour

I have a model the returns session token from my database. The session token table contains a column for the expiry date (of type DATETIME).
According to the documentation this column's value should be returned as a DateTime object, but it is instead returning a string.

#### How to reproduce

```
$query = $db->createQueryBuilder()
	->select('*')
	->from(self::$dbTable)
	->where(self::$dbTable.'.Token = :token')
	->setParameter('token', $token);

$stmt = $query->execute();
$stmt->setFetchMode(FetchMode::CUSTOM_OBJECT, self::$model);

$result = $stmt->fetch();
```
That query above returns a class like this:
```
{
    "ID":"1",
    "Expires":"2019-08-02 00:00:00",
    "Token":"xxxxx"
}
```
Using `gettype($result->Expires)` returns `string`

#### Expected behaviour

The returned class should look like this:
```
{
    "ID":"1",
    "Expires":{
        "date":"2019-08-02 00:00:00.000000",
        "timezone_type":3,
        "timezone":"Country\Region"
    },
    "Token":"xxxxx"
}
```
Using `gettype($result->Expires)` should return `object`

**Comment by abirtles** [comment]
As an update to this, I also tested using a `prepare` instead of the query builder, but the issue is still present.

`prepare` version:
```php
$stmt = $db->prepare('SELECT * FROM UserSession WHERE Token = :token');
$stmt->execute(['token' => $token]);

$stmt->setFetchMode(FetchMode::CUSTOM_OBJECT, self::$model);

$result = $stmt->fetch();
```

I then also tried just returning it as an array, instead of getting DBAL to create a new object for me.
This also just resulted in a string being returned for the Expires column.

As far as I can tell I'm not doing anything wrong here, if someone else could please confirm this behaviour it would be greatly appreciated.

Also, this is the table schema in case that's the problem:
```sql
CREATE TABLE `UserSession` (
  `ID` int(11) NOT NULL,
  `User_Username` varchar(64) NOT NULL,
  `Token` varchar(255) NOT NULL,
  `Expires` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by abirtles** [comment]
So after some more testing I realised it's actually not doing any type conversion at all.

The documentation clearly says that type conversion is *always* done: https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/types.html#types

> Values retrieved from the database are always converted to PHP's integer type or null if no data is present.

> Values retrieved from the database are always converted to PHP's \DateTime object or null if no data is present.

Using PDO, or even using DBAL with a PDO object passed to the connection constructor results in the desired behaviour for integers at least:

DBAL constructed using driver = pdo_mysql
```
  ["Username"]=>
  string(5) "test1"
  ["Name"]=>
  string(7) "Testing"
  ["Email"]=>
  string(22) "xxx"
  ["Password"]=>
  string(60) "xxx"
  ["DayLimit"]=>
  string(3) "100"
  ["HourLimit"]=>
  string(2) "20"
```

DBAL constructed with a PDO instance
```
  ["Username"]=>
  string(5) "test1"
  ["Name"]=>
  string(7) "Testing"
  ["Email"]=>
  string(22) "xxx"
  ["Password"]=>
  string(60) "xxx"
  ["DayLimit"]=>
  int(100)
  ["HourLimit"]=>
  int(20)
```

I don't understand why PDO converts the values as expected, but DBAL does not.

**Comment by predakanga** [comment]
After reviewing the code and the issue tracker, I believe this to be the intended behaviour.

The Type system is only used for query parameters (and quoting), and the SchemaManager. `convertToPHPValue` is never actually used within DBAL.

This should probably be better documented; I came across this issue while trying to figure out the same problem.

That said, support for converting to PHP values would be a great addition in my books.

**Comment by kdambekalns** [comment]
Then someone needs to fix the documentation? It clearly states "values retrieved" are converted. If that is indeed not even intended, it should be removed/corrected in the documentation.

Unless… that is supposed to say

> if using this type and calling `convertToPhpValue()` on it, values retrieved will always be…

in the sense of "you'll never get an integer back from a `datetime` type". If it is intended in that meaning, I find it at least confusing…

**Comment by morozov** [comment]
The quotes to the documentation in https://github.com/doctrine/dbal/issues/3617#issuecomment-508302337 are taken out of context (maybe the documentation could be improved).

The values will be converted to `DateTime` if they are passed through `Type::convertToPHPValue()`. The query builder doesn't do that.
