### ISSUE TITLE
Travic CI tests are failing because ibmcom/db2express-c docker is gone

### ISSUE THREAD

**Issue by shemgp** [doctrine/dbal#3618]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | master

#### Summary

Travis-CI tests are failing due to docker ibmcom/db2express-c being removed.

#### Current behaviour

```
sudo docker pull ibmcom/db2express-c:10.5.0.5-3.10.0
Error response from daemon: pull access denied for ibmcom/db2express-c, repository does not exist or may require 'docker login'
The command "bash ./tests/travis/install-db2.sh" failed and exited with 1 during .
```

#### How to reproduce

Just commit and that commit or PR will have a Travis CI failure.

#### Expected behaviour

Tests for db2 should probably use https://hub.docker.com/r/ibmcom/db2 instead.

**Comment by morozov** [comment]
@shemgp thanks for jumping on this. I see that the DB2 build still cannot start. Let me know if get stuck with something. I tried switching to this image a week ago and I couldn't make it work.

**Comment by shemgp** [comment]
I'm stuck actually. Still figuring out why it's crashing with 137.
