### ISSUE TITLE
Error handling fails with memory meltdown when manipulating large data structures (like blob/binary)

### ISSUE THREAD

**Issue by shavounet** [doctrine/dbal#3625]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | reproduced in v2.5.13, but most likely in all version

#### Summary

This bug is an issue about the management of exceptions by `\Doctrine\DBAL\DBALException`. 

#### Current behaviour

When creating the message for an exception during a query, if the query has too big parameters (like it would be for a blob), the process memory will explode (resulting in a out of memory exception, or similar).

The original exception won't be displayed.

#### How to reproduce

Note that this is how I discovered the bug, but I believe any DBALException might fail if it concern large binary data.

- create an entity with a blob attribute, symfony example :
```php
    /**
     * @ORM\Column(type="blob", nullable=true)
     */
    protected $content;
```
- use a low mysql `max_allowed_packet` configuration
```ini
[mysqld]
max_allowed_packet	= 1M
```
- try to insert a value bigger than 1M in this entity ; I reproduced this with a zip file of 66Mo, it might be important to access into some of the problematic code. Symfony example below.
```php
                    $stream = fopen($zipFilename, 'rb');
                    $entity->setContent(stream_get_contents($stream));
                    fclose($stream);

                    $em->persist($entity);
                    $em->flush();
```

While testing this I had PHP `memory_limit` set to -1. My used RAM memory did explode to more than 12Go, before being killed by the OS.

#### Expected behaviour

Memory usage should have stayed quite stable (around the size of the zip file), and internal MySQL error should have been displayed. In this case : `SQLSTATE[HY000]: General error: 2006 MySQL server has gone away`.

While debugging, I narrowed it down to `\Doctrine\DBAL\DBALException::formatParameters`. Binary parameters are passed to `bin2hex`, which will produce way too big values for 66Mo of data, and is totally useless in an error message. A possible correction is to skip the value or truncate it after a defined length.

**Comment by Ocramius** [comment]
> A possible correction is to skip the value or truncate it after a defined length.

Truncating at something like 1023 chars or such would be a sensible solution

**Comment by morozov** [comment]
Fixed in https://github.com/doctrine/dbal/pull/4387.
