### ISSUE TITLE
Since Oracle 12.2 - getMaxIdentifierLength from 30 to 128

### ISSUE THREAD

**Issue by gherardobertini** [doctrine/dbal#3632]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

I have a project (Symfony and Doctrine) using MySQL.  
My Boss asked me to migrate from MySQL to Oracle.  

The problem is that I have field names longer than 30 chars.  
It would take too much time to edit field names.  

I found that since Oracle version 12.2 that limit has been increased from 30 to 128 [Database Object Naming Rules](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/sqlrf/Database-Object-Names-and-Qualifiers.html#GUID-75337742-67FD-4EC0-985F-741C93D918DA).  
Wonderful!!!  

BUT DBAL let only 30 chars for Oracle  

I found the code in `DBAL/Platforms/OraclePlatform.php`

- public function **fixSchemaElementName**
- public function **getmaxIdentifierLength**

How is now:
```php
    /**
     * {@inheritDoc}
     */
    public function fixSchemaElementName($schemaElementName)
    {
        if (strlen($schemaElementName) > 30) {
            // Trim it
            return substr($schemaElementName, 0, 30);
        }

        return $schemaElementName;
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxIdentifierLength()
    {
        return 30;
    }
```

How could work for 128 max length:
```php
    /**
     * {@inheritDoc}
     */
    public function fixSchemaElementName($schemaElementName)
    {
        if (strlen($schemaElementName) > 128) {
            // Trim it
            return substr($schemaElementName, 0, 128);
        }

        return $schemaElementName;
    }

    /**
     * {@inheritDoc}
     */
    public function getMaxIdentifierLength()
    {
        return 128;
    }
```

### Question
Which could be the best way to implement this feature?

**Comment by morozov** [comment]
You can implement `class Oracle122Platform extends OraclePlatform`. But mind that:
> The maximum length of identifier names depends on the value of the `COMPATIBLE` initialization parameter.

**Comment by morozov** [comment]
Closing as stale.
