### ISSUE TITLE
Bug in UDF function - udfSqrt.

### ISSUE THREAD

**Issue by r0hack** [doctrine/dbal#3637]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 2.9.2

#### Summary

Using UDF function udfSQRT (only SQlite), an error occurs if the mode is on debug. Example, if parameterized queries were not used and there is SQL-injection or otherwise, if the developer mistakenly passes.

#### Current behaviour
And as you can see below, you can, for example, get a password right away, due to an error in the UDF function or if the function gets values that can cause an error.

`/dbal/lib/Doctrine/DBAL/Platforms/SqlitePlatform.php`

![image](https://user-images.githubusercontent.com/10026540/61947005-b8badb00-afac-11e9-9f51-e270e1490990.png)

#### How to reproduce
Enabled debug-mode.

![image](https://user-images.githubusercontent.com/10026540/61946944-87daa600-afac-11e9-8b82-1c5c018afc88.png)
![image](https://user-images.githubusercontent.com/10026540/61946982-ab9dec00-afac-11e9-81f1-7a9df66aac50.png)

Also, due to an error in the function, we will get directly into the request.
![image](https://user-images.githubusercontent.com/10026540/61947224-5910ff80-afad-11e9-8be3-6ed49dffa0d7.png)

**Comment by Ocramius** [comment]
Seems about right: you tried running a sqrt of a string, and the DB is correctly reporting that it cannot do that.

**Comment by r0hack** [comment]
There is no wrong, more precisely, DQL skips such a request, and an error has already arisen in SQLite, which will help to display the password directly. In other databases, there is no UDF. Therefore, there is no such injection. And in the SQLITEthere is, because there YOU incorrectly process the values.

**Comment by Ocramius** [comment]
Nothing wrong here: `SQRT(s1_.password)` was correctly generated SQL (from the DQL string).

**Comment by r0hack** [comment]
This is Error-based Injection and this only happens in SQLite. If this is done using. Because there is no UDF function. and when using the mysql, everything works correctly, this is the correct work.
![image](https://user-images.githubusercontent.com/10026540/61949363-56190d80-afb3-11e9-996b-152ea4e5eda0.png)

**Comment by Ocramius** [comment]
I'd rather say that [MySQL retrieving `0` for `SQRT('potato')`](http://sqlfiddle.com/#!9/9eecb/99398/0) is wrong.

SQLite is correct here.

**Comment by r0hack** [comment]
OK.) To display the user password is very correct)). And error in Doctrine function.)

**Comment by Ocramius** [comment]
> To display the user password is very correct)

No, that's mis-configuration of your environment: do not display trace information, because it will always contain sensitive data.

 >  And error in Doctrine function

The ORM correctly takes a `SimpleArithmeticExpression` and converts it to the resulting `SQRT(<expression>)` in SQL:

https://github.com/doctrine/orm/blob/376c5e1628b642381aa94559d595b7b5be18e990/lib/Doctrine/ORM/Query/AST/Functions/SqrtFunction.php#L27

Locking here - this is going nowhere.
