### ISSUE TITLE
parseDatabaseUrl function needs to urlencode URL before calling parse_url

### ISSUE THREAD

**Issue by shaswa** [doctrine/dbal#3638]
### Bug Report

Version     | 2.5.4

#### Current behaviour
 In the file /doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php,
function: parseDatabaseUrl
The url is parsed to return an associative array

The parse_url function breaks if the password contains any special characters like #
Reference: https://bugs.php.net/bug.php?id=73500

#### How to reproduce
Use a password with a special character like # 

#### Expected behaviour

The URL should be encoded before calling parse_url function. 
I temporarily fixed mine by using %23 in the password instead of # character

**Comment by morozov** [comment]
> I temporarily fixed mine by using %23 in the password instead of # character

This is the right approach. According to [RFC 3986](http://www.faqs.org/rfcs/rfc3986.html), `#` is not an unreserved character and therefore must be percent-encoded.
