### ISSUE TITLE
[2.9.2] The columnDefinition does not trigger table schema updating.

### ISSUE THREAD

**Issue by zacharyzh** [doctrine/dbal#3647]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.9.2

I add the `columnDefinition` to `some_column` after the table was created:

    some_column:
        type: simple_array
        nullable: false
        columnDefinition: "VARCHAR(256) NOT NULL"

But the `columnDefinition` never trigger the table scheme updating:

    $ console doctrine:schema:validate --env=dev
    Mapping
    -------
    [OK] The mapping files are correct. 
    
    Database
    --------
    [OK] The database schema is in sync with the mapping files.

(The `columnDefinition` take effect when table creating)

EDIT:
Doctrine does not add the `DC2Type:simple_array` comment automatic if use the `columnDefinition` for `some_column`.

**Comment by Ocramius** [comment]
`columnDefinition` is generally "you are on your own" land: it pretty much will always fail during schema diffing

**Comment by zacharyzh** [comment]
Is it necessary to add a new option that it allowed to customize the column type (instead LONGTEXT) of `simple_array` ?

**Comment by zacharyzh** [comment]
Maybe just give a `length` option here to define the column type as `VARCHAR(1024)` instead, to avoid using `columnDefinition`:

    some_column:
        type: simple_array
        nullable: false
        length: 1024

**Comment by morozov** [comment]
> `columnDefinition` is generally "you are on your own" land: it pretty much will always fail during schema diffing

Closing based on this.
