### ISSUE TITLE
Too generic DBALException when using existing PDO 

### ISSUE THREAD

**Issue by Erikvv** [doctrine/dbal#3648]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.9.2

#### Summary

Instead of a specific exception like `Doctrine\DBAL\Exception\InvalidFieldNameException` or `Doctrine\DBAL\Exception\UniqueConstraintViolationException` there is a `Doctrine\DBAL\DBALException` when using an existing PDO instance.

#### How to reproduce

Check out https://github.com/Erikvv/doctrine-vs-pdo/tree/unique-exception 
-> use the correct branch
-> xdebug is provided for your convenience

This compares 2 databases using existing PDO vs letting Doctrine create it.

Run:

    $ docker-compose run php

Expected:

    Doctrine\DBAL\Exception\UniqueConstraintViolationException
    Doctrine\DBAL\Exception\UniqueConstraintViolationException

Actual:

    Doctrine\DBAL\DBALException
    Doctrine\DBAL\Exception\UniqueConstraintViolationException

#### Notes

On develop branch reusing PDO fails entirely with a nonsensical exception

> Fatal error: Uncaught Doctrine\DBAL\Exception\DriverRequired: The options "driver" or "driverClass" are mandatory if no PDO instance is given to DriverManager::getConnection(). in /usr/src/doctrine-vs-pdo/vendor/doctril/lib/Doctrine/DBAL/Exception/DriverRequired.php on line 27

**Comment by Erikvv** [comment]
I just saw in previous discussions that this is no longer a scenario the maintainers want to support.

**Comment by matriphe** [comment]
@Erikvv could you point me the link of the discussion? I had similar problem and came across to this issue. thanks!

**Comment by Erikvv** [comment]
@matriphe  https://github.com/doctrine/dbal/pull/3548

I guess I'll close this issue then.
