### ISSUE TITLE
Platform-related events don't work if you specify a custom platform

### ISSUE THREAD

**Issue by zerocrates** [doctrine/dbal#3649]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.9/master

The event manager is only injected into the platform [in the `detectDatabasePlatform` method of Doctrine\DBAL\Connection](https://github.com/doctrine/dbal/blob/d6a1237/lib/Doctrine/DBAL/Connection.php#L388). If you specify a platform, then the detection method is never called and the event manager is not injected.

You can, after creating the Connection, get its event manager and set it on the platform yourself... I don't know if there are any events that might fire in the meantime that could be missed if done this way, but it seems not since `detectDatabasePlatform` is already only called "just-in-time."

If that's in fact sufficient it would still probably be an issue with the [documentation](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/platforms.html) which indicates merely creating and passing the platform should be sufficient.

**Comment by SenseException** [comment]
If your documentation proposal is about extending the docs for the event manager, we would appreciate a PR.
