### ISSUE TITLE
flaky builds with MySQL and MySQLi due to ConnectionException not properly detected

### ISSUE THREAD

**Issue by mmucklo** [doctrine/dbal#3655]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | master

#### Summary

Occasionally travis builds are failing on MySQL for a DriverException that should be interpreted as a ConnectionException.

```sh
There was 1 failure:
752
7531) Doctrine\Tests\DBAL\Functional\ExceptionTest::testConnectionException with data set #0 (array('not_existing'))
754Failed asserting that exception of type "Doctrine\DBAL\Exception\DriverException" matches expected exception "Doctrine\DBAL\Exception\ConnectionException". Message was: "An exception occurred in driver: The server requested authentication method unknown to the client" at
755/home/travis/build/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php:71
756/home/travis/build/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/Driver.php:16
757/home/travis/build/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:354
758/home/travis/build/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:418
759/home/travis/build/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:378
760/home/travis/build/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:322
761/home/travis/build/doctrine/dbal/tests/Doctrine/Tests/DBAL/Functional/ExceptionTest.php:369
```

This is happening because the test is expecting a ConnectionException, but instead a DriverConnection is incorrectly happening.

*MySQLi driver flaky failed builds:*
[doctrine/dbal/jobs/565778380](https://travis-ci.org/doctrine/dbal/jobs/565778380)
[doctrine/dbal/jobs/569139933](https://travis-ci.org/doctrine/dbal/jobs/569139933)
[doctrine/dbal/jobs/569146693](https://travis-ci.org/doctrine/dbal/jobs/569146693)

*MySQL PDO driver flaky failed builds:*
[doctrine/dbal/jobs/569146680](https://travis-ci.org/doctrine/dbal/jobs/569146680)
[doctrine/dbal/jobs/569146690](https://travis-ci.org/doctrine/dbal/jobs/569146690)

#### How to reproduce

Submit a PR.

#### Expected behaviour

ConnectionExceptions are properly detected during builds, even in these edge cases

I have a PR to fix this.

**Comment by Ocramius** [comment]
Handled in https://github.com/doctrine/dbal/pull/3656 - please open a new issue if this still applies.
