### ISSUE TITLE
Appveyor builds are broken

### ISSUE THREAD

**Issue by mmucklo** [doctrine/dbal#3657]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | master

#### Summary

Appveyor builds are broken now as it can no longer install PHP 7.2.

This is because Chocolatey (the Windows package manager used to install PHP) appears to have removed PHP 7.2, and now only seems to have PHP 7.3

#### Current behaviour

Appveyor builds break.

#### How to reproduce

Submit a PR

#### Expected behaviour

Appveyor builds work.

I have a PR to fix this.

**Comment by Ocramius** [comment]
Handled in #3654. Thanks @mmucklo!
