### ISSUE TITLE
Missing MySQL 8.0 keywords lead to unquoted identifiers

### ISSUE THREAD

**Issue by loilo** [doctrine/dbal#3673]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.9.2

#### Summary

This repo's [list of MySQL 8.0 keywords](https://github.com/doctrine/dbal/blob/v2.9.2/lib/Doctrine/DBAL/Platforms/Keywords/MySQL80Keywords.php#L30-L57) seems to [be incomplete](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-M).

This leads to keywords not being quoted when they should. The example I ran into is  the `MEMBER` keyword, as described in contao/contao#727.

That keyword is relatively new (MySQL 8.0.17, released in July). However, as far as I can tell, the list is missing quite a number of keywords. Not sure whether that is intentended.

#### Current behaviour

The `MEMBER` keyword is not recognized as a keyword by DBAL which leads to incorrect generated SQL syntax if a `member` field is present.

#### How to reproduce

I'm not at all proficient in DBAL usage, therefore the only reproduce steps I've got are the non-minimal ones I outlined in contao/contao#727

#### Expected behaviour
Identifier names should be correctly quoted.

**Comment by fritzmg** [comment]
> ... if a `member` _table_ is present.

and (or rather) field name, presumably?  :)

**Comment by loilo** [comment]
> > ... if a `member` _table_ is present.
> 
> and (or rather) field name, presumably? :)

Absolutely, a whoopsie on my side, going to correct it.

**Comment by AireAyquaza** [comment]
Hello ! I have same issue with OPTION keyword from mysql 5.7.19 :)

**Comment by SenseException** [comment]
PRs for extending the list of keywords are welcome.

**Comment by loilo** [comment]
Alright, I'll give it a shot.

**Comment by loilo** [comment]
Question: There are word that are [no longer keywords/reserved words](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-removed-in-current-series) in MySQL 8. Should the `MySQL80Keywords` class reflect that or does this expose us to any form of risk? (Current behavior is to exclusively add to MySQL 5.7 reserved words.)

**Comment by loilo** [comment]
Also @AireAyquaza, the `OPTION` keyword [is in the list](https://github.com/doctrine/dbal/blob/v2.9.2/lib/Doctrine/DBAL/Platforms/Keywords/MySQL57Keywords.php#L172), and it has been [for 6 years](https://github.com/doctrine/dbal/blame/22800bd651c1d8d2a9719e2a3dc46d5108ebfcc9/lib/Doctrine/DBAL/Platforms/Keywords/MySQL57Keywords.php#L172). Your problem probably lies somewhere else. 🙂

**Comment by loilo** [comment]
Fixed in b0726e7.
