### ISSUE TITLE
Types convertToPHPValueSQL declaration ko

### ISSUE THREAD

**Issue by aureldunet** [doctrine/dbal#3676]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.9

#### Summary

The declaration of the $platform arg is invalid into Doctrine\DBAL\Types\Type::convertToPHPValueSQL
https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/Types/Type.php

#### Current behaviour

Declaration should be compatible with Type->convertToPHPValueSQL(sqlExpr : string, platform : \Doctrine\DBAL\Platforms\AbstractPlatform)

#### Current 

```
public function convertToPHPValueSQL($sqlExpr, $platform)
{
    return $sqlExpr;
}
```

#### Fix

```
public function convertToPHPValueSQL($sqlExpr, AbstractPlatform $platform)
{
    return $sqlExpr;
}
```

**Comment by morozov** [comment]
What should the declaration of `Type::convertToPHPValueSQL()` be compatible with?

**Comment by aureldunet** [comment]
2nd arg $platform use AbstractPlatform class, if
