### ISSUE TITLE
Remove PHP 7.4 from `allow_failures`

### ISSUE THREAD

**Issue by carusogabriel** [doctrine/dbal#3683]
PHP 7.4 will be released [soon](https://wiki.php.net/todo/php74) and we need to ensure that `Doctrine` is compatible with it.

All we need to do is to remove these following lines

https://github.com/doctrine/dbal/blob/b0726e7aab01080fc385599a88491a0ccdbd9417/.travis.yml#L40-L41

 and verify that everything is working.

This is a very good issue for those who want to participate in https://hacktoberfest.digitalocean.com.

**Comment by morozov** [comment]
Fixed by https://github.com/doctrine/dbal/pull/3702.
