### ISSUE TITLE
PHPUnit tests fail on PHPUnit 8.4

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3687]
|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.0-dev

#### Summary
There are [test failures](https://travis-ci.org/doctrine/dbal/jobs/593782293) on Travis seemingly caused by the changes in PHPUnit 8.4.

**Comment by Ocramius** [comment]
Likely needs fixing upstream first

**Comment by kejwmen** [comment]
Related issue in phpunit repo: https://github.com/sebastianbergmann/phpunit/issues/3879
