### ISSUE TITLE
doctrine is fetching bigints as string - how to prevent this

### ISSUE THREAD

**Issue by elzozo13** [doctrine/dbal#3690]
Hello,

I have the following issue:

Doctrine is supposed to update entities that were changed. The problem is that for some reason (maybe legacy 32 bit systems?) the bigint data type is treated as string (as you can see below - this is the bigint type class in doctrine, there are also multiple other conversions to string in doctrine code).

    <?php
    
    namespace Doctrine\DBAL\Types;
    
    use Doctrine\DBAL\ParameterType;
    use Doctrine\DBAL\Platforms\AbstractPlatform;
    
    /**
     * Type that maps a database BIGINT to a PHP string.
     */
    class BigIntType extends Type implements PhpIntegerMappingType
    {
        /**
         * {@inheritdoc}
         */
        public function getName()
        {
            return Type::BIGINT;
        }
    
        /**
         * {@inheritdoc}
         */
        public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
        {
            return $platform->getBigIntTypeDeclarationSQL($fieldDeclaration);
        }
    
        /**
         * {@inheritdoc}
         */
        public function getBindingType()
        {
            return ParameterType::STRING;
        }
    
        /**
         * {@inheritdoc}
         */
        public function convertToPHPValue($value, AbstractPlatform $platform)
        {
            return $value === null ? null : (string) $value;
        }
    }

This results in updating data that should not be updated because the unit of work checker compares data as strict (as it should) resulting in differences (code below).

    // skip if value haven't changed
    if ($orgValue === $actualValue) { // $orgValue = "3829784117300", $actualValue = 3829784117300
        continue;
    }

The end result for this is that the following code:

    $product = $productRepo->find($id);
    $product->setOwnerId($ownerId); // $ownerId = 3829784117300
    $this->em->flush();

Is generating a query that does... nothing basically except stressing db (in my case I have a few tens of millions of those per day). The solution for the particular case above...

    $product = $productRepo->find($id);
    if ((int)$product->getOwnerId() !== $ownerId) {
        $product->setOwnerId($ownerId); // $ownerId = 3829784117300
    }
    $this->em->flush();

Simple right? But... what do you do when you have 2 bigints? Ok... 2 conditions... not a big deal. But what if they are... 90? Ok... we can use reflection go through entity properties and check all. 

But... what if somewhere in the relation chain there is another entity that needs to be checked? And the complete solution is that we have to recursively check every attribute of the entity and its children and check for bigints.

But... isn't that what the doctrine unit of work is for? Why do I need to reparse the whole entity and check for something that is already checked for just because bigint is treated as string (resulting in basically duplicating a huge chunk of doctrine code)?

And now the question... how to go around this (bare in mind that I'm not asking for a particular solution for a simple case, I'm asking for a general solution that can be applied to a big code base that is supposed to be mentained for years to come - as you can see above I have solutions but I'm not ok with half jobs and fragile code unless there is really no other way)? I'm looking for maybe a setting that I missed that makes doctrine treat integers like integers and not as strings... stuff like that.

Have a greay day,
Victor

**Comment by alcaeus** [comment]
> Can we migrate the question on the right place pls? I would like not to double post.

I've transferred the issue to the DBAL project.

FWIW, while I'd like to agree that we should just kick 32-bit systems to the curb and ignore them, we've seen a couple of bug reports in the doctrine/migrations library after making some changes that broke migration ordering on 32-bit systems. People still use them, so just because most systems over the past 5 years have been 64-bit, we're (unfortunately) not yet at the point where we can ignore 32-bit limitations entirely.

**Comment by elzozo13** [comment]
> 
> 
> > Can we migrate the question on the right place pls? I would like not to double post.
> 
> I've transferred the issue to the DBAL project.
> 
> FWIW, while I'd like to agree that we should just kick 32-bit systems to the curb and ignore them, we've seen a couple of bug reports in the doctrine/migrations library after making some changes that broke migration ordering on 32-bit systems. People still use them, so just because most systems over the past 5 years have been 64-bit, we're (unfortunately) not yet at the point where we can ignore 32-bit limitations entirely.

Tyvm for migrating.

About 32-bit, I never said ignore them (I actually said "I agree that backwards compatibility must be maintained"). I was suggesting to add a setting with the current behavior being the default, that can be changed by devs (people who actually know what systems they have - or at least they should). This way you keep everyone happy (if I find a couple of hours this weekend I may even provide the code). I basically a pre-pre-step towards deprecation (pre-pre-step -> add setting with default serving "older" systems, after a few years: pre-step change the setting default to fit "newer" systems and, after a few more years deprecate the setting and support while still maintaining it, and finally drop support -> is a lengthy process, years long but at some point it has to begin imo).

**Comment by svinohod** [comment]
doctrine/orm v2.7.2 ALWAYS executes UPDATE statement for entities with BIGINT fields with value !== NULL. Independently of you have changed you entity values or not. So it's enough to load you entity from database and run flush() after that.

Example:
```
$myEntity = new MyEntity()
$myEntity->setMyBigintField(12345);
$entityManager->persist($myEntity);
$entityManager->flush(); // here make  doctrine an INSERT statement for $myEntity. As expected

$entityManager->refresh($myEntity); // here make  doctrine an SELECT statement  for $myEntity. As expected
$entityManager->flush(); // here make  doctrine an UPDATE statement for $myEntity. That is unexpected and not good
```

@Doctrine-developers: please fix that problem.

**Comment by es-cologne** [comment]
doctrine/orm v2.7.2 ALWAYS executes UPDATE statement for entities with BIGINT fields with value !== NULL. Independently of you have changed your entity values or not. So it's enough to load your entity from database and run flush() after that.

Example:
```
$myEntity = new MyEntity()
$myEntity->setMyBigintField(12345);
$entityManager->persist($myEntity);
$entityManager->flush(); // here make  doctrine an INSERT statement for $myEntity. As expected

$entityManager->refresh($myEntity); // here make  doctrine an SELECT statement  for $myEntity. As expected
$entityManager->flush(); // here make  doctrine an UPDATE statement for $myEntity. That is unexpected and not good
```

@Doctrine-developers: please fix that problem.

**Comment by alcaeus** [comment]
@es-cologne is this something that was introduced in a recent version or does the problem occur in older releases as well?

**Comment by es-cologne** [comment]
@alcaeus I don't know if doctrine have same behavior in other versions.

**Comment by elzozo13** [comment]
So... I ended up going with @andrew-demb suggestion. @stof solution was also good but in my particular case (and I think in most cases) would generate more harm then good since you would need either to cast the value each time you want to use it in a mathematical operation either to create a secondary getter for it.

My full type class looks like this (in case someone needs a starting point) and combined with a cast on the entities fully solved the issues (only the last function is changed compared to the original one).

Note: This WILL result in issues on 32 bit architectures, so be sure you are on 64 (and even there it will fail on numbers over 
9,223,372,036,854,775,807 -> 1 bit for sign). For me that is not a problem since I don't get close to that, but if someone copy paste it... disclaimer :).

I do still think that it should be a setting for this. It can end up by doing thousands of queries per second for nothing. And most devs will probably not dig deep enough to find the source of the issue (but if they are presented with a config they'll probably use it).

P.S. Sorry for late resolution. Covid and stuff :).

```
<?php

namespace App\Doctrine\Types;

use Doctrine\DBAL\ParameterType;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\Type;
use Doctrine\DBAL\Types\Types;

/**
 * Type that maps a database BIGINT to a PHP int.
 */
class BigIntType extends Type
{
    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return Types::BIGINT;
    }

    /**
     * {@inheritdoc}
     */
    public function getSQLDeclaration(array $fieldDeclaration, AbstractPlatform $platform)
    {
        return $platform->getBigIntTypeDeclarationSQL($fieldDeclaration);
    }

    /**
     * {@inheritdoc}
     */
    public function getBindingType()
    {
        return ParameterType::STRING;
    }

    /**
     * {@inheritdoc}
     */
    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        return null === $value ? null : (int) $value;
    }
}

```

**Comment by morozov** [comment]
It shouldn't be prevented. Not all integers fit into the PHP's `int` type on all platforms.
