### ISSUE TITLE
behavior of setParameters()

### ISSUE THREAD

**Issue by ahmedali5530** [doctrine/dbal#3698]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.5.13

#### Summary

`setParameters` replaces all parameters set by `setParameter`

#### Current behaviour

when i use both `setParameter` and `setParameters` in single query `setParameters` replace all parameters set by `setParameter`

#### How to reproduce

Use both `setParameter` and `setParameters` in single query

#### Expected behaviour

`setParameters` should append the new parameters

**Comment by greg0ire** [comment]
> setParameters should append the new parameters

This is what I would expect from a method called `addParameters`, but not from a `setParameters` method. But maybe it should be renamed to `resetParametersTo` for clarity?

**Comment by Ocramius** [comment]
Closing as per @greg0ire's comment: the API behaves as expected.
