### ISSUE TITLE
creating indexes, does doctrine ignore length option ?

### ISSUE THREAD

**Issue by lamb0tiana** [doctrine/dbal#3707]
Hi,
facing to limited length for indexing mysql column , I try out add option like  {options:{"length":x}}, apparently it seems ignore length option ?

**Comment by Ocramius** [comment]
I don't remember if index lengths are supported out of the box, but we do indeed have index lengths in the schema namespace: https://github.com/doctrine/dbal/blob/d82b6aa2b1b0b0a2f7e7454fa59085c4d7ac7e10/tests/Doctrine/Tests/DBAL/Schema/IndexTest.php#L114-L142

Maybe dump your DBAL schema symbols, and see if the index has a length?
