### ISSUE TITLE
Release 2.10.0 drops support for PHP 7.1

### ISSUE THREAD

**Issue by phil-davis** [doctrine/dbal#3721]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.0

#### Current behaviour

```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/dbal ^2.10 -> satisfiable by doctrine/dbal[v2.10.0].
    - doctrine/dbal v2.10.0 requires php ^7.2 -> your PHP version (7.1.33-1+ubuntu18.04.1+deb.sury.org+1) overridden by "config.platform.php" version (7.1) does not satisfy that requirement.
```

#### How to reproduce

In `composer.json` specify:
```
        "doctrine/dbal": "^2.10",
```
And have PHP 7.1

#### Expected behaviour

I expected that the release notes at https://github.com/doctrine/dbal/releases/tag/v2.10.0 would mention that PHP V7.1 support is dropped with dbal 2.10

But I don't see that mentioned.

Should  the release notes be updated to mention that PHP V7.1 is no longer supported?

**Comment by Ocramius** [comment]
Not sure if dependency upgrades should be mentioned anymore: as you saw from the above, composer explicitly prevented you from installing the package.

I've added it to the release notes nonetheless, thanks!
