### ISSUE TITLE
How to run in-memory migrations from tests?

### ISSUE THREAD

**Issue by jlwalkerlg** [doctrine/dbal#3725]
|    Q        |   A
|------------ | -----
| Version     | 2.10.0

### Support Question

I'm using an in-memory sqlite database for my PHPUnit tests, so I need to run the doctrine migrations from my test cases.

In Laravel you can simply use the `RefreshDatabase` trait in your tests. With the Doctrine ORM I managed to setup an in-memory database from my tests as follows:

```php
self::$entityManager = EntityManagerFactory::getEntityManager();

$metadatas = self::$entityManager->getMetadataFactory()->getAllMetadata();
$schemaTool = new SchemaTool(self::$entityManager);
$schemaTool->updateSchema($metadatas);
```

I've found no such way to do this with the DBAL.

I've tried running `exec(__DIR__ . '/../../../vendor/bin/doctrine-migrations migrate --no-interaction');` and it appears to run the migrations successfully since I get a message in the console `++ 1 sql queries`, however all my subsequent tests still fail, complaining that there is `no such table...`.

If I switch to a `.sqlite` file the tests run fine. My guess is that the connection through which the migrations run is different from the connection in my tests, and since they are in-memory, they are in effect different databases.

So the question is, how can I run in-memory migrations from my PHPUnit tests?

**Comment by lcobucci** [comment]
@jlwalkerlg you can create an in-memory connection by using the sqlite driver and passing the option `memory` as `true`. More info https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/configuration.html#pdo-sqlite

It's also important to note that, although handy and easy to configure, this is generally not recommended since your tests won't run in a similar environment as production.

**Comment by jlwalkerlg** [comment]
@lcobucci I understand that by how can I use that connection to run migrations? As far as I'm aware, there's nothing like `$connection->migrate()`. There's only a command-line tool, which doesn't work for test purposes.

**Comment by Ocramius** [comment]
You have to create your own migrator: see https://github.com/doctrine/migrations/blob/v2.1.0/lib/Doctrine/Migrations/Tools/Console/Command/MigrateCommand.php#L138
