### ISSUE TITLE
2.10.0 requires PHP ^7.2 but doctrine/cache won't pass PHP ^7.2 syntax validation

### ISSUE THREAD

**Issue by reedy** [doctrine/dbal#3727]
Making a task here for cross referencing and making it visible...

But due to a usage of "object: in RiakCache in doctrine/cache, any version of doctrine/cache that includes RiakCache won't pass `php -l`, so while 2.10.0 of doctrine/dbal actually says PHP ^7.2, it's not actually fully supporting it...

See https://github.com/doctrine/cache/issues/323 and https://github.com/doctrine/cache/issues/324 as a suggestion to drop the code which seems to be unmaintained upstream (due to various issues), and also forked numerous times but the PR to use those have not been finished or merged

**Comment by reedy** [comment]
https://github.com/doctrine/cache/pull/324 has been merged, to go into 1.10

When that's tagged for release, I'll make a PR to bump https://github.com/doctrine/dbal/blob/master/composer.json#L36 from `^1.0` to `^1.10` and then backport for 2.10 too

**Comment by Ocramius** [comment]
Closing here: unrelated to this repository.
