### ISSUE TITLE
Schema data structures should have a parent pointer

### ISSUE THREAD

**Issue by guilhermeblanco** [doctrine/dbal#3732]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Schema elements, such as Table, Column, ForeignKey, Constraint, Index, etc should have a property to corresponding parent in the case it make sense logically. Example:

```
$column->getTable();
```

This would allow us to rely on DBAL data structure in ORM (already provisioned) instead of building our own data structures there.

**Comment by morozov** [comment]
If a table has references to its inner elements (columns, indices, etc) and they have a reference back to their parent, won't it create circular dependencies and potential memory leaks? Or modern PHP GC can detect them? Or we need some more sophisticated approach to that?

**Comment by morozov** [comment]
Closing in light of #4742.
