### ISSUE TITLE
QueryBuilder binds type to a wrong param when using positional parameters

### ISSUE THREAD

**Issue by vdmorozov** [doctrine/dbal#3740]
### Bug Report

QueryBuilder tries to bind a type to a wrong param if you use positional parameters, and the type of the first one is not explicit.

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.0

#### Summary

The problem is that the numerical parameters in the QueryBuilder API start with the needle `0`, not with `1` as in the PDO API. That's why we need to use offset in `Doctrine\DBAL\Connection::_bindTypedValues`:
```
if (is_int(key($params))) {
    // Positional parameters
    $typeOffset = array_key_exists(0, $types) ? -1 : 0;
    ...
```

But if you don't specify a type in the first call of `setParameter` method, `$types` doesn't contain key `0`, while you still need to use offset `-1`.

Checking for a `0` key in the `$params` instead of `$types` may be a solution.

#### Current behaviour

Let's say you have a code looking like this:
```
$connection->createQueryBuilder()
    ->insert('contacts')
    ->values(
        [
            'name' => '?',
            'birthday' => '?',
        ]
    )
    ->setParameter(0, (string)$name)
    ->setParameter(1, $birthday, Types::DATE_MUTABLE)
    ->execute();
```

In this example, the `DATE_MUTABLE` type will be bound to the `name` value causing `ConversionException`.

#### Expected behavior

The type `DATE_MUTABLE` should be bound to the second param `birthday`.

**Comment by SenseException** [comment]
This is surely some strange behaviour you found there. Can you please provide a pull request with a failing test that helps to implement a fix?

**Comment by vdmorozov** [comment]
Sure, here it is:
https://github.com/doctrine/dbal/pull/3751

**Comment by morozov** [comment]
Closing as the test in https://github.com/doctrine/dbal/pull/3751 doesn't perform any assertions and works as expected otherwise.
