### ISSUE TITLE
MasterSlave Connection host null

### ISSUE THREAD

**Issue by mayro** [doctrine/dbal#3741]
Hello,
I'm using MasterSlave connection with symfony. I want to know if my query was executed in Master or Slave connection, when i debug  my connection i have host = null and port = null every time... 
I'm using $this->getDoctrine()->getConnection()->getHost()  and i have null result.

Thanks

**Comment by Ocramius** [comment]
You can check `isConnectedToMaster()`: https://github.com/doctrine/dbal/blob/ab888962987575f26530f974c057c42903a50169/lib/Doctrine/DBAL/Connections/MasterSlaveConnection.php#L123

**Comment by mayro** [comment]
i know this function but i need the exact host thanks any way :)

**Comment by Ocramius** [comment]
You'd need a debugger for that: no API is exposed to show that, sorry.
