### ISSUE TITLE
 Default to real-utf8 when no charset is provided

### ISSUE THREAD

**Issue by greg0ire** [doctrine/dbal#3749]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Configuring charset in a portable way is a real pain for the community.
See e.g. symfony/recipes#674, which triggered symfony/recipes#689, then https://github.com/symfony/recipes/pull/691/files

This should be fixed by https://github.com/doctrine/DoctrineBundle/pull/1070, but it would be great to have that default benefit to other consuming frameworks by contributing it directly here. When this is done, the code introduced in the bundle maybe be removed provided the composer constraint is adjusted.

**Comment by ostrolucky** [comment]
We should perhaps start with checking which databases don't already default to utf-8. MySQL was famous for defaulting to `latin1_swedish_ci`, but that's no longer true since MySQL 8.

**Comment by morozov** [comment]
Will be fixed by https://github.com/doctrine/dbal/pull/4644.
