### ISSUE TITLE
Cannot get string representation of booleans in pgsql

### ISSUE THREAD

**Issue by ostrolucky** [doctrine/dbal#3763]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.9.3

#### Summary

I've run into this when checking https://github.com/doctrine/DoctrineBundle/issues/627. Sorry if there already is issue for this.

#### Current behaviour

Alternative A: `\Doctrine\DBAL\Platforms\PostgreSqlPlatform::$useBooleanTrueFalseStrings` set to `false`:

Bundle calls [BooleanType::convertToDatabaseValue](https://github.com/doctrine/dbal/blob/0382f44f91ca1fe8df6aded507eff6b1ee4df85c/lib/Doctrine/DBAL/Types/BooleanType.php#L26), then chain of calls is [PostgreSqlPlatform::convertBooleansToDatabaseValue](https://github.com/doctrine/dbal/blob/355d242f4cbc40f5d475c13a5bdbf85a44f35b89/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L880) -> [PostgreSqlPlatform::convertBooleans](https://github.com/doctrine/dbal/blob/355d242f4cbc40f5d475c13a5bdbf85a44f35b89/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L859) -> [\Doctrine\DBAL\Platforms\AbstractPlatform::convertBooleans](https://github.com/doctrine/dbal/blob/436f2f6c943937abe8544505630e76be4c468ae1/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L2348). 

Result (int) $value.

Alternative B: `\Doctrine\DBAL\Platforms\PostgreSqlPlatform::$useBooleanTrueFalseStrings` set to `true`:

Bundle calls [BooleanType::convertToDatabaseValue](https://github.com/doctrine/dbal/blob/0382f44f91ca1fe8df6aded507eff6b1ee4df85c/lib/Doctrine/DBAL/Types/BooleanType.php#L26), then chain of calls is [PostgreSqlPlatform::convertBooleansToDatabaseValue](https://github.com/doctrine/dbal/blob/355d242f4cbc40f5d475c13a5bdbf85a44f35b89/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L880) ->[PostgreSqlPlatform::doConvertBooleans](https://github.com/doctrine/dbal/blob/355d242f4cbc40f5d475c13a5bdbf85a44f35b89/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L851) -> [PostgreSqlPlatform::convertSingleBooleanValue](https://github.com/doctrine/dbal/blob/355d242f4cbc40f5d475c13a5bdbf85a44f35b89/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L805) -> callback at [PostgreSqlPlatform::convertBooleansToDatabaseValue](https://github.com/doctrine/dbal/blob/355d242f4cbc40f5d475c13a5bdbf85a44f35b89/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L889). 

Result (int) $value.

#### Expected behaviour

I expect following code would be executed in some situations https://github.com/doctrine/dbal/blob/355d242f4cbc40f5d475c13a5bdbf85a44f35b89/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php#L865-L874 Instead, some weird call hierarchy is being used which always arrives to same result.

**Comment by stof** [comment]
To me, there is no issue on the DBAL side. DBAL exposes 2 boolean conversion APIs: `AbstractPlatform::convertBooleansToDatabaseValue` and `AbstractPlatform::convertBooleans`. The bundle was trying to use the wrong API for its use case.

`BooleanType::convertToDatabaseValue` is expected to perform the necessary conversion for code using parameter binding. And PDO expects parameters bound with `PDO::PARAM_BOOL` to be integers. So the behavior of the API is the right one.

The use case of DoctrineBundle of interpolating parameters to a SQL representation of their value is solved in DBAL with `AbstractPlatform::convertBooleans`, which already produces `true` or `false` strings in PostgresqlPlatform (when using `PostgreSqlPlatform::$useBooleanTrueFalseStrings = true` which is the default).

**Comment by ostrolucky** [comment]
I agree. Let's close.
