### ISSUE TITLE
Document SQL comment hint functionality for custom types

### ISSUE THREAD

**Issue by alcaeus** [doctrine/dbal#3764]
The [custom mapping type documentation](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/types.html#custom-mapping-types) does not mention the [`Type::requiresSQLCommentHint`](https://github.com/doctrine/dbal/blob/299ef4f06645b747fbef7876f87516012eb990ba/lib/Doctrine/DBAL/Types/Type.php#L315) method. A recent change in DoctrineBundle 2.0 removes implicitly marking custom types as commented, instead deferring to the logic that is built into the type itself. However, since this isn't documented in the custom mapping types documentation, many people don't know about this and wonder why their custom types don't work.

For users that rely on implicit commenting in DoctrineBundle we introduced a deprecation layer in 1.11 that tells them to update their type, but users creating new types won't know about this. (see also https://github.com/doctrine/DoctrineBundle/issues/1074 and https://github.com/doctrine/DoctrineBundle/issues/977).

**Comment by morozov** [comment]
Irrelevant as of https://github.com/doctrine/dbal/pull/5512.
