### ISSUE TITLE
Known minor BC break causing problems with sqlsrv driver and escaped backslash

### ISSUE THREAD

**Issue by YetiCGN** [doctrine/dbal#3767]
### BC Break Report

`driver: 'pdo_sqlsrv'`

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.10

#### Summary

Updating from doctrine/dbal 2.9.3 to 2.10.0 introduced a "MINOR BC BREAK": "Default values are no longer handled as SQL expressions". Unfortunately we are now unable to produce a correct query, because the backslash in the query is always escaped:

`SELECT KST FROM vwUsers WHERE Login = 'DOMAIN\\username'`

This does not return a result, only a where argument with just one backslash. We are setting just one backslash in the query string, but it is now escaped, returning a query that will not get any result. 

Could this BC break behavior be made switchable or could a special treatment for PDOSqlsrv be developed, because apparently the SQL server does not recognize backslash as an escape character?

#### Previous behaviour

The above query was generated correctly as `SELECT * FROM vwUsers WHERE Login = 'DOMAIN\username'`

#### Current behavior

The above query has an escaped backslash that is not recognized as an escape character in SQL Server, apparently and returns no result.

#### How to reproduce

In a repository class that's tied to a view on the SQL Server:

```
$qb = new QueryBuilder($this->connection);
$qb->select('KST')->from('vwUsers');
$qb->where("Login = :username");
$qb->setParameter('username', 'DOMAIN\\' . $username);
$result = $qb->execute()->fetchAll();
```

The parameter "username" contains only one backslash, but generating the SQL query generates two backslashes.

I will try to create a minimal working (failing) example.

**Comment by Ocramius** [comment]
`$qb->setParameter('username', 'DOMAIN\\' . $username);`

This should generate a prepared statement, not an SQL snippet like `Login = 'DOMAIN\\username'`

**Comment by morozov** [comment]
@YetiCGN if you're referring to #2960, then this is unlikely since this change was about handling default values in columns and affected only the code that generates DDL. The problem you're experiencing is about SQL.

**Comment by YetiCGN** [comment]
@Ocramius The prepared statement correctly has just the one backslash, but the resulting query has two and it fails:

![image](https://user-images.githubusercontent.com/447119/70070744-66419900-15f4-11ea-9036-c4ab93bcb466.png)

@morozov Yeah, I'm not so sure now it's dbal, doctrine/orm did also change from 2.6.6 to 2.7.0 between the two app releases where the issue occured. I will keep digging...

**Comment by YetiCGN** [comment]
Never mind, I found the error. As suggested by @morozov, it didn't have anything to do with the referred change. I was misled by my database query tool which did not return a result if I just copy the query above, but when executed it works.

Sorry, guys!
