### ISSUE TITLE
MySQL | Change varchar to boolean results in syntax error

### ISSUE THREAD

**Issue by JaZo** [doctrine/dbal#3773]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.10.0

#### Summary

When I change a varchar column to a boolean, it results in a syntax error and the change fails. I'm not sure, but it looks like #3418 introduced this issue. This issue is not present in 2.9.3.

N.B. I'm using Laravel migrations so i'm not directly interacting with this package.

#### Current behaviour

It adds a charset to the alter query, but as far as I know that should not be added for an integer.

Create statement taken from database manager:
```
CREATE TABLE `categories` (
  `is_default` VARCHAR(255) NOT NULL DEFAULT '' COLLATE 'utf8_unicode_ci'
)
COLLATE='utf8_unicode_ci' ENGINE=InnoDB
```

Incorrect alter statement produced by this package:
```
ALTER TABLE categories
CHANGE is_default is_default TINYINT(1) CHARACTER SET utf8 DEFAULT '0' NOT NULL COLLATE `utf8_unicode_ci`
```

#### How to reproduce

I'm using Laravel migrations so I'm not familiar with this package. Below are my Laravel migrations. I'll try to create a failing test to make it easier to reproduce.

Create migration:
```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCategoriesTable extends Migration
{
    /**
     * Run the migrations.
     */
    public function up()
    {
        Schema::create('categories', function (Blueprint $table) {
            $table->string('is_default')->default('');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down()
    {
        Schema::dropIfExists('categories');
    }
}
```

Alter migration:
```php
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AlterCategoriesTableUpdateIsDefault extends Migration
{
    /**
     * Run the migrations.
     */
    public function up()
    {
        Schema::table('categories', function (Blueprint $table) {
            $table->boolean('is_default')->default(0)->change();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down()
    {
        Schema::table('categories', function (Blueprint $table) {
            $table->string('is_default')->default('')->change();
        });
    }
}
```

#### Expected behaviour

I would expect an alter statement without charset i.e.
```
ALTER TABLE categories
CHANGE is_default is_default TINYINT(1) DEFAULT '0' NOT NULL COLLATE `utf8_unicode_ci`
```

**Comment by JaZo** [comment]
Sorry, duplicate of #3714

**Comment by Niko9911** [comment]
Still, unresolved. Would open this, as this seems only related.
