### ISSUE TITLE
Command to Query Database Structure

### ISSUE THREAD

**Issue by beberlei** [doctrine/dbal#3775]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Add a Console command that allows querying the structure of the "online" Schema similar to how php provides --ri Reflection flags on the command line.

Examples:

```
php app/console dbal:query-schema --table=foobar
php app/console dbal:query-schema --index=baz
php app/console dbal:query-schema ; lists all tables, indexes, foreign keys, ...
```

**Comment by morozov** [comment]
It doesn't have to be implemented in the DBAL. The existing APIs should allow implementing this command outside.
