### ISSUE TITLE
PHP 8 Fatal Error because of incompatible signatures

### ISSUE THREAD

**Issue by orklah** [doctrine/dbal#3791]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10

#### Summary

I tried to install CI with PHP 8 in my project and I get a Fatal Error because of incompatible signatures

#### Current behaviour

``` 
PHP Fatal error:  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $statement) in /home/runner/work/inspar/inspar/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 70
```

Is this a known issue? Maybe it's a little early to worry about PHP 8?

**Comment by morozov** [comment]
Yes, it's a known issue (#3770). Closing as duplicate.
