### ISSUE TITLE
Postgres-Doctrine-Symfony -> TIMESTAMP :: Bad insertion default value

### ISSUE THREAD

**Issue by natarska** [doctrine/dbal#3796]
ORM > Query builded result in migrations file:
$this->addSql('ALTER TABLE component ADD datecreate DATE DEFAULT \'CURRENT_TIMESTAMP\' NOT NULL');

I think the Insertion Query might be: ALTER TABLE component ADD datecreate DATE DEFAULT  'CURRENT_TIMESTAMP' NOT NULL

CMD error : An exception occurred while executing 'ALTER TABLE component ADD datecreate DATE DEFAULT 'CURRENT_TIMESTAMP'
   NOT NULL':

  SQLSTATE[0A000]: Feature not supported: 7 ERROR:  date/time value "current" is no longer supported

**Comment by Ocramius** [comment]
Seems correct/expected behaviour: default value expressions aren't supported in ORM
