### ISSUE TITLE
Make QueryBuilder Doctrine-agnostic

### ISSUE THREAD

**Issue by Bilge** [doctrine/dbal#3805]
### Feature Request

The comment at the head of the `QueryBuilder` states:

> Important: Verify that every feature you use will work with your database vendor.
> SQL Query Builder does not attempt to validate the generated SQL at all.

If this is the case, it should not be necessary to depend on a Doctrine `Connection`, as it currently does. This dependency means the query builder cannot be used with other database connectivity libraries, such as async implementations offered by Amp or React. Clearly, the query builder would be a lot more useful if it were not tied directly to Doctrine.

**Comment by morozov** [comment]
Please feel free to implement one outside of the DBAL.
