### ISSUE TITLE
Flush on MariaDB 10.4.11 fails to Syntax error

### ISSUE THREAD

**Issue by NikoGrano** [doctrine/dbal#3815]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 2.10.1
| PHP | 7.4.1
| Database | MariaDB 10.4.11
| Framework | Symfony 4.4

#### Summary

I am trying to persist entity with to the database. It fails.

#### Current behaviour

```
  [PDOException (42000)]                                                                                
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check   
  the manual that corresponds to your MariaDB server version for the right syntax to use near 'index,   
  recorded, type) VALUES (0, '2020-01-09 22:27:32.066694', 'App.Stock.Domai' at line 1 
```

#### How to reproduce

I have [Entity](https://github.com/HouseHold/HouseHold/tree/dev/src/Stock/Domain) extending [abstract entity](https://github.com/HouseHold/HouseHold/blob/dev/src/Core/Infrastructure/Share/Event/Repository/ORM/AbstractEventStoreEntity.php).
When trying to do following, I will get mentioned failure.

```php
$this->em = EntityManagerInterface::class;
$entity = new Entity(...)

$this->em->persist($entity);
$this->em->flush();
```

I do not expect you to fix this, if this is bug with my code, but as I have this code publicly available, it might help you. Repository is available [here](https://github.com/HouseHold/HouseHold)

#### Expected behaviour

Entity gets persisted.

### Next Steps in debugging

~I will be trying to run this under MariaDB 10.3. However, it should not affect this at all and do not wait me while I do it.~
Same error under 10.3.21

**Comment by morozov** [comment]
@NikoGrano if you believe the problem is in DBAL, you'll have to reproduce it using DBAL.

**Comment by NikoGrano** [comment]
@morozov Should I open this issue in ORM repo?

**Comment by NikoGrano** [comment]
Posted into wrong tracker. Closing and moving to orm repo.
