### ISSUE TITLE
Deprecate the usage of arrays in QueryBuilder methods

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3837]
The usage of array arguments in `QueryBuilder::select()`, `::addSelect()`, `::groupBy()` and `::addGroupBy()` methods needs to be deprecated.

Their support was removed in https://github.com/doctrine/dbal/pull/3831.

**Comment by morozov** [comment]
@BenMorel do you want to address this one as well before the up-merge? I'll do the merge later today regardless of the status of this issue.

**Comment by BenMorel** [comment]
Do you just want to mark them as deprecated? Or raise a deprecation notice?

**Comment by morozov** [comment]
Just document the usage of array arguments as deprecated in the method descriptions. Not using the `@deprecated` annotation since it would deprecate the methods, not using `trigger_error()`.

**Comment by morozov** [comment]
Fixed by #3853.
