### ISSUE TITLE
CompositeExpression is mutable

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#3844]
|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.1

If a composite expression is used in different parts of the same query or in different queries, its implicit mutation by the `QueryBuilder::(and|or)(Where|Having)()` methods in one place will affect the other places as well.

**Comment by BenMorel** [comment]
Fixed in #3858.

**Comment by BenMorel** [comment]
@morozov Is there anything preventing this issue from being closed?

**Comment by morozov** [comment]
I usually rely on GitHub to close issues automatically.
