### ISSUE TITLE
Generate NOT NULL columns as a sequence of two queries

### ISSUE THREAD

**Issue by finwe** [doctrine/dbal#3856]
### Feature Request

Generate new `NOT NULL` columns in schema diff as two separate queries to make specifying default column values easier.

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes?
| BC Break    | no

#### Summary

Reference: https://github.com/doctrine/migrations/issues/603

Currently, new not null columns in schema diff are generated as a single query: 

```sql
ALTER TABLE curriculum ADD help BOOLEAN NOT NULL;
```

This would almost always fail on a database being in use as the column would have `NULL` values for existing rows.

I propose generating the diff as two queries which will make easier to insert an `UPDATE` query between them that would fill the new column with values.

```sql
ALTER TABLE curriculum ADD help BOOLEAN;
ALTER TABLE curriculum ALTER COLUMN help SET NOT NULL;
```

**Comment by damienalexandre** [comment]
That would be really great for Migration DX indeed :+1:

**Comment by morozov** [comment]
> I propose generating the diff as two queries which will make easier to insert an UPDATE query between them that would fill the new column with values.

~~What prevents adding the `UPDATE` before the single `ALTER TABLE`?~~ I see, it's a new column. This is quite a specific case that needs to be addressed on the application side anyways. At this point, it's possible to just find and replace the DDL with what's needed.
