### ISSUE TITLE
MysqliStatement, method errorInfo,  annoatation type return is wrong

### ISSUE THREAD

**Issue by athos99** [doctrine/dbal#3873]
PHPstan detect a real problem for the class class MysqliStatement

For file lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php

In reality the method errorInfo return a string for driver mysqli. 
But in the anotation (phpdoc)  inherits from interface Statement where errorInfo return a mixed.

**Comment by beberlei** [comment]
This is valid by php 7.4s contravarianve rules, because string is a subtype of mixed
