### ISSUE TITLE
OracleSchemaManager listTableDetails use index COMMENTS non-existent

### ISSUE THREAD

**Issue by Hectorfdv88** [doctrine/dbal#3877]
In  Doctrine\DBAL\Schema\OracleSchemaManager.php  line 402

```
public function listTableDetails($tableName) : Table
    {
        $table = parent::listTableDetails($tableName);

        /** @var OraclePlatform $platform */
        $platform = $this->_platform;
        $sql      = $platform->getListTableCommentsSQL($tableName);

        $tableOptions = $this->_conn->fetchAssoc($sql);
        $table->addOption('comment', $tableOptions['COMMENTS']);

        return $table;
    }

```
Please change to

```
public function listTableDetails($tableName) : Table
    {
        $table = parent::listTableDetails($tableName);

        /** @var OraclePlatform $platform */
        $platform = $this->_platform;
        $sql      = $platform->getListTableCommentsSQL($tableName);

        $tableOptions = $this->_conn->fetchAssoc($sql);
        $table->addOption('comment', $tableOptions['comments']);

        return $table;
    }
```

because index COMMENTS is case sensitive, and Oracle return lower case comments.

This is tested un Oracle 18c.

Thanks!

**Comment by SenseException** [comment]
Thank you for opening this issue. Please show what the current result is and what the expected result is supposed to be. As far as I understand you'll get an Notice for an undefined index. Is that correct?
Is this something that differs between Oracle versions?

**Comment by cesarhein** [comment]
I have the same issue. When i run the "php artisan migrate" command in a Laravel project i get this Exception:

   ErrorException  : Undefined index: COMMENTS

  at C:\xampp\htdocs\voyager_oracle_4\vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\OracleSchemaManager.php:402
    398|         $platform = $this->_platform;
    399|         $sql      = $platform->getListTableCommentsSQL($tableName);
    400| 
    401|         $tableOptions = $this->_conn->fetchAssoc($sql);
  > 402|         $table->addOption('comment', $tableOptions['COMMENTS']);
    403| 
    404|         return $table;
    405|     }
    406| }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined index: COMMENTS", "C:\xampp\htdocs\voyager_oracle_4\vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\OracleSchemaManager.php", ["v_permissions", Object(Doctrine\DBAL\Schema\Table), Object(Doctrine\DBAL\Platforms\OraclePlatform), "SELECT comments FROM user_tab_comments WHERE table_name = 'V_PERMISSIONS'"])
      C:\xampp\htdocs\voyager_oracle_4\vendor\doctrine\dbal\lib\Doctrine\DBAL\Schema\OracleSchemaManager.php:402

  2   Doctrine\DBAL\Schema\OracleSchemaManager::listTableDetails("v_permissions")
      C:\xampp\htdocs\voyager_oracle_4\vendor\laravel\framework\src\Illuminate\Database\Schema\Grammars\ChangeColumn.php:57

  Please use the argument -v to see more details.

**Comment by chepew23** [comment]
I have the same issue. i'm using Laravel 7.x with Oracle 12c. This pull request have a solution:
https://github.com/doctrine/dbal/pull/3907

**Comment by morozov** [comment]
Fixed by https://github.com/doctrine/dbal/pull/5226.
