### ISSUE TITLE
Support APP name for pdo_sqlsrv connections

### ISSUE THREAD

**Issue by gjdanis** [doctrine/dbal#3895]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Please allow the ability to specify ["APP"](https://docs.microsoft.com/en-us/sql/connect/php/example-application-pdo-sqlsrv-driver?view=sql-server-ver15) in the connection string. I believe something similar is done for [PG SQL connections](https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/configuration.html#pdo-pgsql).

This metadata is leveraged by monitoring platforms and is helpful for identifying connections.

**Comment by morozov** [comment]
It's currently supported via the `driverOptions` configuration parameter. See https://github.com/doctrine/dbal/pull/3033.
