### ISSUE TITLE
Support for Amazons Aurora Serverless Data Api

### ISSUE THREAD

**Issue by Nemo64** [doctrine/dbal#3910]
### Feature Request

Amazon has a new way of interacting with their Aurora Serverless Sql Database called the [rds-data api](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html).

It uses http requests instead of a persistent connection. The advantages aren't immediately obvious but there are some like not needing a VPC, having automatic connection pool management, not needing a database password, being able to do multiple queries in parallel, having multiple transactions at the same time (if you are mad).

I already implemented a surprisingly well working dbal driver: https://github.com/Nemo64/dbal-rds-data

Before I put a lot more work into it I'm curious if there is interest to implement this directly into dbal.
I'd be happy to try porting it.

**Comment by morozov** [comment]
Unlikely to happen since it's a proprietary API. Keeping the support for it in a separate package looks like the right approch.
