### ISSUE TITLE
Malformed UTF-8 characters, possibly incorrectly encoded

### ISSUE THREAD

**Issue by BaHeK1994** [doctrine/dbal#3913]
https://github.com/doctrine/dbal/blob/01143c9cd4fc360a6e42017902fd9b591ca706bb/lib/Doctrine/DBAL/Types/JsonType.php#L40

this code fixed error "Malformed UTF-8 characters, possibly incorrectly encoded" in php 7.2 or newer
> $encoded = json_encode($value, DEFINED('JSON_INVALID_UTF8_IGNORE') ? JSON_INVALID_UTF8_IGNORE : 0);

PS: sorry for my bad English

**Comment by PReimers** [comment]
Hello @BaHeK1994 

Could you explain why this is needed?
I don't understand the necessity of this change.

**Comment by BaHeK1994** [comment]
> Hello @BaHeK1994
> 
> Could you explain why this is needed?
> I don't understand the necessity of this change.

I get information from the game server and store this information in json type. Some players have incorrect characters in their nickname, and when I save an array of data with such players, I get an error.

**Comment by greg0ire** [comment]
I think the string should be cleaned before being passed to the DBAL. How to clean it (remove it, or try something better) should be your decision IMO, not the DBAL's

**Comment by PReimers** [comment]
@greg0ire Thanks for providing the SO link.

@BaHeK1994 
Like @greg0ire said, I would recommend handling this behavior in your application instead of handling it in the library.
