### ISSUE TITLE
SQLSrv wrong Exception on unique constraint violation

### ISSUE THREAD

**Issue by lampi87** [doctrine/dbal#3922]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | v2.10.1

#### Summary

On inserting duplicate data into SQLSrv a wrong exception is throw. A common DBALException is thrown instead of UniqueConstraintViolationException

#### Current behaviour

Doctrine\DBAL\DBALException: An exception occurred while executing....

Returned message is: An exception occurred while executing 'INSERT INTO ...'
SQLSTATE [23000, 2601]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot insert duplicate key row in object 'dbo....' with unique index 'UNIQ_...'. The duplicate key value is (...).

Stack trace:
``
0 /vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(146): Doctrine\DBAL\DBALException::wrapException(Object(Doctrine\DBAL\Driver\SQLSrv\Driver), Object(Doctrine\DBAL\Driver\SQLSrv\SQLSrvException), 'An exception oc...')
1 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(162): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\SQLSrv\Driver), Object(Doctrine\DBAL\Driver\SQLSrv\SQLSrvException), 'INSERT INTO pat...', Array)
2 /vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(287): Doctrine\DBAL\Statement->execute()
3 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1087): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
4 /vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(400): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
5 /vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(368): Doctrine\ORM\UnitOfWork->commit(NULL)
``

#### How to reproduce

Create a table with a unique key, e.g. 3 columns together for one constraint. Insert same data two times.

#### Expected behaviour

UniqueConstraintViolationException should be returned instead common Doctrine\DBAL\DBALException

**Comment by morozov** [comment]
Should be fixed by https://github.com/doctrine/dbal/pull/4928.
