### ISSUE TITLE
Problem with installation of doctrine/dbal with doctrine/orm 3.0.x-dev

### ISSUE THREAD

**Issue by Musiksammler** [doctrine/dbal#3929]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | dev-master#0ef7d47bc5055e45c5dd3c57d2121b5807ae0917

#### Summary

I make "composer install" with 

> "doctrine/dbal": "dev-master#0ef7d47bc5055e45c5dd3c57d2121b5807ae0917 as 3.x-dev"
> "doctrine/orm": "3.0.x-dev" 

and after that I get the error "Class 'Doctrine\DBAL\Configuration' not found"

#### Current behaviour

Error "Class 'Doctrine\DBAL\Configuration' not found"

#### How to reproduce

> composer require doctrine/dbal:dev-master#0ef7d47bc5055e45c5dd3c57d2121b5807ae0917

is enough. The package gets installed. The files are then stored in 
> vendor/doctrine/dbal/lib/Doctrine/DBAL

but in the vendor/composer directory the files "installed.json", "autoload_psr4.php" and "autoload_static.php" have "vendor/doctrine/dbal/src" as root directory for the package. Somehow the psr-4 configuration in the composer.json of the package gets overwritten by a newer value.

I made a temporary fix by inserting this as "post-install-cmd" and "post-update-cmd" but this is no final solution.

> "post-install-cmd": [
>            "cDir=\"$PWD\" && ln -s $cDir/vendor/doctrine/dbal/lib/Doctrine/DBAL vendor/doctrine/dbal/src"
> ],

**Comment by morozov** [comment]
This doesn't seem to be a DBAL issue.
