### ISSUE TITLE
setAutoCommit not working properly with MasterSlaveConnection

### ISSUE THREAD

**Issue by marcod85** [doctrine/dbal#3938]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | ?
| Version     | 2.10.1

#### Summary

When setAutoCommit was disabled, and later on gets enabled again, the current transaction is not commited.

#### Current behaviour

When calling `setAutoCommit(true)` the method checks for `isConnected`, which is always false in case of MasterSlaveConnections.
Hence the call to `commitAll` is not executed.

```
// Connection.php #520
        if ($this->isConnected !== true || $this->transactionNestingLevel === 0) {
            return;
        }

        $this->commitAll();
```

#### How to reproduce

1. `$conn->setAutoCommit(false);`
2. Perform queries, etc.
3. `$conn->setAutoCommit(true);`
4. Perform more queries. These ones won't be executed, because the transaction is still open.

#### Expected behaviour

`commitAll()` is properly called.

A suggestion would be to change `$this->isConnected` to `$this->isConnected()` and override `isConnected()` method in `MasterSlaveConnection`.

**Comment by morozov** [comment]
The primary/replica connection feature hasn't received any maintenance in the past years. This feature is unlikely to be implemented.
