### ISSUE TITLE
xorX() : support XOR operator in ExpressionBuilder

### ISSUE THREAD

**Issue by sylbru** [doctrine/dbal#3962]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | no

(sorry I’m not sure if I should check yes or no for RFC)

#### Summary

Why doesn’t DBAL support the XOR operator in ExpressionBuilder? Is there a specific reason for that, or just nobody needs it? It seems very easy to implement, I could probably do it myself.

**Comment by SenseException** [comment]
I don't know if there's a reason why xor wasn't added in the past years, but it seems like there wasn't a huge demand for it. I currently don't see the need to implement and maintain it.
