### ISSUE TITLE
v2.10.2 - SQLSTATE[HY000]: General error: Extraneous additional parameters

### ISSUE THREAD

**Issue by oojacoboo** [doctrine/dbal#3975]
### Bug Report

When using the Doctrine PDO connection object to bind params to a prepared statement, the following error is being caused.

`SQLSTATE[HY000]: General error: Extraneous additional parameters`

This issue did not exist with 2.10.1.  I also believe it's related to `$stmt->fetchAll(\PDO::FETCH_ASSOC)`.

|    Q        |   A
|------------ | ------
| Version     | 2.10.2

**Comment by greg0ire** [comment]
Here is the list of changes between the 2 versions: https://github.com/doctrine/dbal/compare/v2.10.1...2.10.2

Do you think it might have to do with https://github.com/doctrine/dbal/commit/24cefe5d83a8e0ccc49b18fe774b11105a7fbcd9 ?

Is there a stack trace you could share?

**Comment by oojacoboo** [comment]
Here is the trace:

```
[
  ...
  {
      "file": "/srv/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php",
      "line": 252,
      "function": "fetchAll",
      "class": "PDOStatement",
      "type": "->",
      "args": [
        2,
        null,
        null
      ]
    }
  ],
  "message": "SQLSTATE[HY000]: General error: Extraneous additional parameters",
  "file": "/srv/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php",
  "line": 252,
  "class": "PDOException",
  "user": [],
  "tags": [],
  "extra": [],
  "timestamp": "2020-04-22 18:28:31 UTC",
  "level": "critical",
  "environment": "dev",
  "app_version": "4.0.0-stage+20200419180027"
}
```

And yes, that could certainly be related.  It looks like Propel dealt with an issue related to this years ago- found some issues on github.

**Comment by greg0ire** [comment]
Possible next steps:

1. Confirming that by editing the code and just removing the 3rd argument
2. Checking the `fetchAll` docs to see if there is anything about this
3. Contributing a PR that passes the third argument only when necessary, depending on the first one

**Comment by Carpenter0100** [comment]
i am running into the same issue and can confirm that this PR is the cause: 24cefe5

**Comment by greg0ire** [comment]
@duncan3dc please have a look at this

**Comment by DanielSchwiperich** [comment]
Can also confirm and set a conflict for 2.10.2 in composer.json which fixed our pipeline so far

**Comment by grzegorztomasiak** [comment]
+1

**Comment by DanielSchwiperich** [comment]
Problem still existis in 2.10.3 released today. 

So far this helps
```yml
"conflict": {
    "doctrine/dbal": "2.10.2|2.10.3"
  },
```

**Comment by bytehead** [comment]
The problem still exists in 2.10.4.

```yaml
"conflict": {
    "doctrine/dbal": "2.10.2|2.10.3|2.10.4"
  },
```

**Comment by bytehead** [comment]
thank you @morozov and @BenMorel! 🎉
