### ISSUE TITLE
[BC Break] 2.10.1 to v2.10.2: PDOStatement::convertParamType() must be of the type int, null given

### ISSUE THREAD

**Issue by noniagriconomie** [doctrine/dbal#3976]
### BC Break Report

Hello, here is my bug report, after upgrading locally `doctrine/dbal` from `v2.10.1` to `v2.10.2` (`patch upgrade`)

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.10.2

#### Summary

```sql
$countryCode = $conn->executeQuery(
    'SELECT country_code FROM core_town WHERE id = ?;',
    [$townId]
)->fetchColumn(0);

info:
int $townId
$conn is $conn = $this->_em->getConnection();
code lives inside a class extending Doctrine\ORM\EntityRepository
```

- ✅ works on 2.10.1
- ❌ fatal on 2.10.2

#### Previous behaviour

Working (yes i know not the best way to write prepared query with `?` param, but not the point here :s ))

#### Current behavior

```
An exception occurred while executing 'SELECT country_code FROM core_town WHERE id = ?;' with params [36548]:

Argument 1 passed to Doctrine\DBAL\Driver\PDOStatement::convertParamType() must be of the type int, null given, called in /Users/antoine/Sites/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 78
```

#### How to reproduce

<details>
<summary>More info</summary

`Symfony 4.3.latest`
`PHP 7.3.17`

while doing:

`composer upgrade doctrine/dbal`

other doctrine component updated are

```

  - Updating doctrine/annotations (v1.8.0 => 1.10.2): Loading from cache
  - Updating doctrine/reflection (v1.1.0 => 1.2.1): Loading from cache
  - Updating doctrine/persistence (1.3.6 => 1.3.7): Loading from cache
  - Updating doctrine/orm (v2.7.0 => v2.7.2): Loading from cache

```

I've checked the doc, this part https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/data-retrieval-and-manipulation.html#doctrine-dbal-types-conversion
but my issue is more on the `bc breack` more than the doc and code rewrite

</detaisl>

**Comment by wuchen90** [comment]
I think it's caused by this line https://github.com/doctrine/dbal/commit/21512f9ef5ee1b4acccb553f4b474cd0715ae628#diff-e7dd540cfb86c74ce7361e2bd00053cfR138

**Comment by noniagriconomie** [comment]
@wuchen90 it seems yes, but as of a patch release, IMO it should not break

Waiting maintainers review/comment, thank you

**Comment by greg0ire** [comment]
A stack trace would help I think.

**Comment by marcingy** [comment]
I have a similar issue and can confirm that the patch linked here breaks BC.

**Comment by greg0ire** [comment]
Thanks for confirming that. @marcingy @noniagriconomie @wuchen90 , can you please provide a stack trace?

**Comment by marcingy** [comment]
`Doctrine\DBAL\DBALException: An exception occurred while executing 'UPDATE site SET vcs_path = '?' WHERE sitegroup = '?'' with params ["VCS_CHANGED_TO_PATH_UNKNOWN", "stargatesg1"]:

mysqli_stmt::bind_param() expects parameter 1 to be string, array given

/Users/marc.ingram/checkouts/hosting-api/docroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:172
/Users/marc.ingram/checkouts/hosting-api/docroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:149
/Users/marc.ingram/checkouts/hosting-api/docroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:914`

This of help?

**Comment by greg0ire** [comment]
> This of help?

Not so much, I think a big part is missing… are you sure there are only 3 lines in your stack trace? How did you obtain it?

**Comment by marcingy** [comment]
This is from phpunit test the rest of the stack is code that is part of my companies application, hence not very useful to you this is the entry point where we call executeQuery.

**Comment by greg0ire** [comment]
Ah I guess we are more interested in the stack trace of `$ex` here. 

https://github.com/doctrine/dbal/blob/aab745e7b6b2de3b47019da81e7225e14dcfdac8/lib/Doctrine/DBAL/Connection.php#L914

Does phpunit only show the top exception? Or are there several of them?

**Comment by greg0ire** [comment]
Ah I think I have found what the stack trace should look like
1. https://github.com/doctrine/dbal/blob/4c03ed81471c62f178581eb325339a3c34f3b71a/lib/Doctrine/DBAL/Connection.php#L905
2. Either https://github.com/doctrine/dbal/blob/4c03ed81471c62f178581eb325339a3c34f3b71a/lib/Doctrine/DBAL/Connection.php#L1563 or https://github.com/doctrine/dbal/blob/4c03ed81471c62f178581eb325339a3c34f3b71a/lib/Doctrine/DBAL/Connection.php#L1576
3. See message above

**Comment by greg0ire** [comment]
And of course, the `null` comes from https://github.com/doctrine/dbal/blob/4c03ed81471c62f178581eb325339a3c34f3b71a/lib/Doctrine/DBAL/Connection.php#L901 in `executeQuery`

**Comment by greg0ire** [comment]
Because of this check: https://github.com/doctrine/dbal/blob/4c03ed81471c62f178581eb325339a3c34f3b71a/lib/Doctrine/DBAL/Connection.php#L1560

So this method must be at fault I think: https://github.com/doctrine/dbal/blob/4c03ed81471c62f178581eb325339a3c34f3b71a/lib/Doctrine/DBAL/Connection.php#L1562

**Comment by marcingy** [comment]
It looks like we go down this path

#1 /Users/marc.ingram/checkouts/hosting-api/docroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php(241): mysqli_stmt->bind_param(Array, 'VCS_CHANGED_TO_...', 'stargatesg1')
#2 /Users/marc.ingram/checkouts/hosting-api/docroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php(147): Doctrine\DBAL\Driver\Mysqli\MysqliStatement->bindTypedParameters()
#3 /Users/marc.ingram/checkouts/hosting-api/docroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(906): Doctrine\DBAL\Driver\Mysqli\MysqliStatement->execute()

**Comment by greg0ire** [comment]
Looks like I was completely wrong :sweat_smile: 

What's also odd, it looks like the line numbers you have do not match perfectly: https://github.com/doctrine/dbal/blob/aab745e7b6b2de3b47019da81e7225e14dcfdac8/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php#L146-L147

**Comment by marcingy** [comment]
Yes I have modified the source as part of my debuging exercise :(

**Comment by greg0ire** [comment]
Makes sense… also, I just noticed that you don't have the same error as OP :sweat:

**Comment by greg0ire** [comment]
Can you try 

```
- $types += array_fill_keys(array_keys($params), null);
+ $types += array_fill_keys(array_keys($params), \Doctrine\DBAL\ParameterType\ParameterType::STRING);
```

in SQLParserUtils and report back?

**Comment by marcingy** [comment]
That didn't make a difference

**Comment by greg0ire** [comment]
This method has a really weird API: https://www.php.net/manual/en/mysqli-stmt.bind-param.php

You should dump `$types` just before the crash to see what it looks like.

**Comment by marcingy** [comment]
It is an array when we get into this method, will trace further back

`
/Users/marc.ingram/checkouts/hosting-api/docroot/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php:215:
array(2) {
  [0] =>
  string(1) "s"
  [1] =>
  string(1) "s"
}
`

**Comment by marcingy** [comment]
K so it happens in because we loop around the types in _bindTypedValues in connection.php

public function bindValue($param, $value, $type = ParameterType::STRING)

**Comment by marcingy** [comment]
After some digging it turns out it was actually a bug in our code which was hidden.

`
-                $sql = "UPDATE site SET vcs_path = '?' WHERE sitegroup = '?'";
+                $sql = "UPDATE site SET vcs_path = ? WHERE sitegroup = ?";
`

So extra quotes, sorry about that but I wonder if that might be underlying issue for the original bug

**Comment by noniagriconomie** [comment]
hi @greg0ire sorry i was mainly AFK this month

what kind of stacktrace do you need, if i dump you the sf log is it usefull? I can reproduce it if you want

**Comment by greg0ire** [comment]
> if i dump you the sf log is it usefull?

I don't need the full log of the request, just the stack trace that corresponds to the innermost exception you are getting. See what a stack trace is exactly on this page: https://symfony.com/blog/new-in-symfony-3-3-redesigned-exception-pages

**Comment by greg0ire** [comment]
@marcingy the patch above made your issue more visible I think, I'm not sure how. Anyway, I marked your messages as resolved so that we can more easily focus on OP's issue.

**Comment by noniagriconomie** [comment]
@greg0ire here you are (from the command line while running `bin/console doc:m:m --no-interaction --allow-no-migration --em=front`)

```
  ++ migrating 20200202232806

     -> ALTER TABLE front_slider ADD path VARCHAR(255) DEFAULT NULL
     -> UPDATE front_slider SET path = ? WHERE src = ? with parameters ([5a/50/48879ffc0348a4589476d5a1ea7d.jpeg], [slider_5c49eeeee418a.jpeg])
Migration 20200202232806 failed during Execution. Error An exception occurred while executing 'UPDATE front_slider SET path = ? WHERE src = ?' with params ["5a\/50\/48879ffc0348a4589476d5a1ea7d.jpeg", "slider_5c49eeeee418a.jpeg"]:

Argument 1 passed to Doctrine\DBAL\Driver\PDOStatement::convertParamType() must be of the type int, null given, called in /Users/antoine/Sites/front/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 78
15:59:25 CRITICAL  [app] Uncaught console command exception ["class" => "Doctrine\DBAL\DBALException","message" => """  An exception occurred while executing 'UPDATE front_slider SET path = ? WHERE src = ?' with params ["5a\/50\/48879ffc0348a4589476d5a1ea7d.jpeg", "slider_5c49eeeee418a.jpeg"]:\n  \n  Argument 1 passed to Doctrine\DBAL\Driver\PDOStatement::convertParamType() must be of the type int, null given, called in /Users/antoine/Sites/front/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 78  ""","file" => "/Users/antoine/Sites/front/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line" => 172,"command" => "doctrine:migrations:migrate","input" => "'doc:m:m' --no-interaction --allow-no-migration --em=front"] ["uid" => "f4159b5338"]

In DBALException.php line 172:
                                                                                                                  
  An exception occurred while executing 'UPDATE front_slider SET path = ? WHERE src = ?' with params ["5a\/50\/4  
  8879ffc0348a4589476d5a1ea7d.jpeg", "slider_5c49eeeee418a.jpeg"]:                                                
                                                                                                                  
  Argument 1 passed to Doctrine\DBAL\Driver\PDOStatement::convertParamType() must be of the type int, null given  
  , called in /Users/antoine/Sites/front/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line   
  78                                                                                                              
                                                                                                                  

In PDOStatement.php line 199:
                                                                                                                  
  Argument 1 passed to Doctrine\DBAL\Driver\PDOStatement::convertParamType() must be of the type int, null given  
  , called in /Users/antoine/Sites/front/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line   
  78                                                                                                              
                                                                                                                  

doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]

exit status 1
```

I am reproducing on the web context, will post here as well

**Comment by noniagriconomie** [comment]
here from the web

```


[2/2] DBALException
--
Doctrine\DBAL\DBALException: An exception occurred while executing 'SELECT country_code FROM core_town WHERE id = ?;' with params [12312]:  Argument 1 passed to Doctrine\DBAL\Driver\PDOStatement::convertParamType() must be of the type int, null given, called in /Users/antoine/Sites/admin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 78    at /Users/antoine/Sites/admin/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:172   at Doctrine\DBAL\DBALException::wrapException(object(Driver), object(TypeError), 'An exception occurred while executing \'SELECT country_code FROM core_town WHERE id = ?;\' with params [12312]:Argument 1 passed to Doctrine\\DBAL\\Driver\\PDOStatement::convertParamType() must be of the type int, null given, called in /Users/antoine/Sites/admin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 78')      (/Users/antoine/Sites/admin/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:149)   at Doctrine\DBAL\DBALException::driverExceptionDuringQuery(object(Driver), object(TypeError), 'SELECT country_code FROM core_town WHERE id = ?;', array(12312))      (/Users/antoine/Sites/admin/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:914)   at Doctrine\DBAL\Connection->executeQuery('SELECT country_code FROM core_town WHERE id = ?;', array(12312))      (AdminBundle/Controller/ContactController.php:40)   at AdminBundle\Controller\ContactController->indexAction(object(Request), 1)      (/Users/antoine/Sites/admin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (/Users/antoine/Sites/admin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)      (/Users/antoine/Sites/admin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:200)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request), 1, true)      (/Users/antoine/Sites/admin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/SubRequestHandler.php:102)   at Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle(object(Kernel), object(Request), 1, true)      (/Users/antoine/Sites/admin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php:453)   at Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(object(Request), true, null)      (/Users/antoine/Sites/admin/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/HttpCache/HttpCache.php:64)   at Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache->forward(object(Request), true)      (/Users/antoine/Sites/admin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php:426)   at Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(object(Request), true)      (/Users/antoine/Sites/admin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php:317)   at Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(object(Request), true)      (/Users/antoine/Sites/admin/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpCache/HttpCache.php:192)   at Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(object(Request))      (/Users/antoine/Sites/admin/web/index.php:41)



```

**Comment by greg0ire** [comment]
Your first message contains 2 exceptions, but not the stack trace, so it doesn't really help. When in cli, use `bin/console -vvv` and then you will have stack trace. The second message (http context) contains just 1 out of 2 exception (see the `[2/2]` ?). I think exception `[1/2]` might be more interesting, please include it.

**Comment by greg0ire** [comment]
Will have a look later, but it looks helpful, thanks!

**Comment by greg0ire** [comment]
I noticed that there are calls to `auxmoney/opentracing-bundle-doctrine-dbal` right in the middle of the stack trace. You could try disabling it to see if maybe that's causing the bug?

**Comment by noniagriconomie** [comment]
Ok sure i will try on monday and report here

**Comment by greg0ire** [comment]
Also, you motivated me to contribute this: https://github.com/symfony/symfony-docs/pull/13699

**Comment by noniagriconomie** [comment]
I will review it carefuly :)

**Comment by noniagriconomie** [comment]
Closing in favor of the issue mentioned above, thanks
