### ISSUE TITLE
fetchAll with FetchMode::COLUMN and mysqli driver always return values from the first column for any value of the fetchArgument

### ISSUE THREAD

**Issue by artemmolotov** [doctrine/dbal#3982]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.1

#### Summary
`PDOStatement::fetchAll(FetchMode::COLUMN, 1)` return values from the **second** column.
`MysqliStatement::fetchAll(FetchMode::COLUMN, 1)` return values from the **first** column. 

`fetchAll(FetchMode::COLUMN, $columnIndex)` with the `mysqli` driver **always return values from the first column** for any value of the `$columnIndex` variable.

https://github.com/doctrine/dbal/blob/v2.10.1/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php#L363

Other non-pdo drivers might have the same problem.

#### How to reproduce

1. Create new database
2. Exec: `CREATE TABLE test (first int, second int)`
3. Exec: `INSERT INTO test VALUES (1, 2), (3, 4)`. We get the following table:

    |    first        |   second
    |------------ | ------
    | 1    | 2
    | 3     | 4

4. Configure DBAL Connection with the `mysqli` driver
5. Run:
```php
$stmt = $connection->prepare("SELECT * FROM test");
$stmt->execute();

$columnIndex = 1;
$valuesOfSecondColumn = $stmt->fetchAll(FetchMode::COLUMN, $columnIndex);

echo $valuesOfSecondColumn[0], " ", $valuesOfSecondColumn[1];
```

#### Expected behaviour
`2 4`

#### Current behaviour

`1 3`

**Comment by morozov** [comment]
Closing as this API is no longer supported.
