### ISSUE TITLE
Pretty print sql

### ISSUE THREAD

**Issue by reedy** [doctrine/dbal#4003]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary
While it doesn't matter for a computer, for humans it's easier to read things with whitespace etc.

Is there any chance of being able to get a "pretty print" mode, or some sort of SQL formatter to add newlines, whitespace etc for readability purposes?

**Comment by andrew-demb** [comment]
https://github.com/doctrine/sql-formatter

**Comment by reedy** [comment]
> https://github.com/doctrine/sql-formatter

Aha, thanks. Any chance of maybe getting that documented somewhere? :) Or is it, and I've just managed to completely miss it?

**Comment by greg0ire** [comment]
> Aha, thanks. Any chance of maybe getting that documented somewhere? :) Or is it, and I've just managed to completely miss it?

Well it comes with a fairly complete README IMO.

**Comment by greg0ire** [comment]
> Or even in suggest in composer.json? 

:thinking: I'm not sure… in what circumstances do you get SQL from the DBAL?

**Comment by reedy** [comment]
> > Aha, thanks. Any chance of maybe getting that documented somewhere? :) Or is it, and I've just managed to completely miss it?
> 
> Well it comes with a fairly complete README IMO.

"it" being what exactly? https://github.com/doctrine/dbal/blob/2.10.x/README.md is pretty limited ;)

The problem is discoverability

> > Or even in suggest in composer.json?
> 
> 🤔 I'm not sure… in what circumstances do you get SQL from the DBAL?

Isn't that the whole point of the library? To build SQL?

**Comment by greg0ire** [comment]
I was referring to the README of https://github.com/doctrine/sql-formatter so, so very obviously ;)

> Isn't that the whole point of the library? To build SQL?

The whole point to me would be executing it. Rarely do I get SQL from the DBAL (but it is still possible)

**Comment by reedy** [comment]
> I was referring to the README of https://github.com/doctrine/sql-formatter so, so very obviously 😉

I think we crossed wires a little. I was meaning documenting it somewhere in here/the docs for DBAL - "Hey, if you want to pretty print your SQL use https://github.com/doctrine/sql-formatter"

Not going into the extent of how to use it etc. Mostly discoverability. If you know the right keywords you can probably find the sql formatter repo.. If you don't, you might not

Hence the 'suggest' suggestion:

`"doctrine/sql-formatter": "SQL statement formatter. Can be used for syntax highlighting too"`

> > Isn't that the whole point of the library? To build SQL?
> 
> The whole point to me would be executing it. Rarely do I get SQL from the DBAL (but it is still possible)

We're using it to try and abstract our schema generation in MediaWiki, but it's a big change for us, so we want to know (at least in the mean time) that the SQL is what we expect, which is meaning we're putting them in files and committing for review etc.

And hence, we want it formatted with whitespace, so people can read it. I don't know if we'll do this forever, but for now, we are.

**Comment by greg0ire** [comment]
I think that kind of PR would be accepted, you can go ahead and do it :slightly_smiling_face:
