### ISSUE TITLE
Incorrect Azure MySQL version detected

### ISSUE THREAD

**Issue by eddedre** [doctrine/dbal#4032]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.10.2

#### Summary

I get this error when using a Azure MySQL database 5.7.x

"Unknown database type json requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it."

#### Current behaviour

It appears that the package is not reporting the right version

#### How to reproduce

docker@api:/var/www/html$ php artisan tinker
Psy Shell v0.10.4 (PHP 7.2.30-1+ubuntu18.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> DB::connection()->getPdo();
=> Doctrine\DBAL\Driver\PDOConnection {#3298
     inTransaction: false,
     attributes: {
       CASE: NATURAL,
       ERRMODE: EXCEPTION,
       AUTOCOMMIT: 1,
       PERSISTENT: false,
       DRIVER_NAME: "mysql",
       SERVER_INFO: "Uptime: 605054  Threads: 9  Questions: 1117139  Slow queries: 0  Opens: 580  Flush tables: 1  Open tables: 103  Queries per second avg: 1.846",
       ORACLE_NULLS: NATURAL,
       CLIENT_VERSION: "mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $",
       **SERVER_VERSION: "5.6.42.0",**
       STATEMENT_CLASS: [
         "Doctrine\DBAL\Driver\PDOStatement",
         [],
       ],
       EMULATE_PREPARES: 0,
       CONNECTION_STATUS: "************.database.azure.com via TCP/IP",
       DEFAULT_FETCH_MODE: BOTH,
     },
   }

#### Expected behaviour

It should return 5.7.29 as report when I manually run SELECT @@version

![image](https://user-images.githubusercontent.com/1719526/83072033-104a2d00-a03c-11ea-98b8-91eefe11abdd.png)

**Comment by SenseException** [comment]
Have you set a server-version in the DBAL configuration?

**Comment by morozov** [comment]
> Have you set a server-version in the DBAL configuration?

I believe this is irrelevant. The bug is about _detecting_ the version. Azure MySQL is not currently supported. Although, setting the version manually may work as a workaround.

> I get this error when using a Azure MySQL database 5.7.x
> SERVER_VERSION: "5.6.42.0"

This looks coming from PDO, DBAL has nothing to do with that. In the recent past (#3595) we dropped the support for Azure Federations because it's a commercial product that cannot be used by the library maintainers. Unless there's a way to continuously test with this platform, it's not going to be supported.

**Comment by SenseException** [comment]
Having a workaround was my intention in case no version was set for this use case.
