### ISSUE TITLE
Heads up about upcoming PHP 8 signature changes

### ISSUE THREAD

**Issue by GrahamCampbell** [doctrine/dbal#4042]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | ???
| Version     | 2.10.2

#### Summary

PHP 8 will be adding scalar types to some of its internal signatures in favour of internal type checking.

#### Current behaviour

`
PHP Fatal error:  Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $statement) in /data/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 73
`

**Comment by andrew-demb** [comment]
See #3803

**Comment by GrahamCampbell** [comment]
Right, thanks.
