### ISSUE TITLE
Native JSON Support for MSSQL/Azure DB

### ISSUE THREAD

**Issue by jangaehler** [doctrine/dbal#4102]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

The type json is unfortunately only created as nvarchar on MSSQL databases. Would it be possible to implement native JSON support for MSSQL?

**Comment by morozov** [comment]
According to the [SQL Server 2019 documentation](https://docs.microsoft.com/en-us/sql/relational-databases/json/store-json-documents-in-sql-tables?view=sql-server-ver15),
> JSON documents can be stored as-is in `NVARCHAR` columns.

There doesn't seem to be any other column type for JSON.
