### ISSUE TITLE
Invalid queries are generated

### ISSUE THREAD

**Issue by 4c0n** [doctrine/dbal#4104]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.10.x

#### Summary

When changing a column type the platform options are not considered, in version 2.9 for MySQL/MariaDB the charset key was not passed as platform option in a column object. Since 2.10 the charset key is passed and it is causing generation of invalid queries.

#### Current behaviour

In this scenario the query generated to alter the table is:
'ALTER TABLE to_be_altered CHANGE some_column_name some_column_name INT CHARACTER SET utf8 DEFAULT NULL COLLATE utf8_unicode_ci'

Obviously the charset should not be provided/processed for integer type columns.

#### How to reproduce

I opened a PR containing the failing case: https://github.com/doctrine/dbal/pull/4103
See the builds for more information.

#### Expected behaviour

At least for the MySQL dialect the query should be generated without 'CHARACTER SET utf8` when changing to integer type.

**Comment by morozov** [comment]
Closing based on https://github.com/doctrine/dbal/pull/4103#issuecomment-658021097.
