### ISSUE TITLE
Add support for MYSQLI_OPT_READ_TIMEOUT option

### ISSUE THREAD

**Issue by siimsoni** [doctrine/dbal#4141]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Add support for undocumented `MYSQLI_OPT_READ_TIMEOUT` option. Comparable to `MYSQL_OPT_READ_TIMEOUT` in [MySQL C API](https://dev.mysql.com/doc/refman/8.0/en/mysql-options.html).

> Add support to specify timeout in seconds for each attempt to read from the server.

The currently supported `MYSQLI_OPT_CONNECT_TIMEOUT` specifies timeout in seconds for establishing the connection, but not for the time it takes to read the data. There doesn't appear to be support for write timeouts.

There is an open [PHP bug report](https://bugs.php.net/bug.php?id=76497) to add documentation for this option.

**Comment by siimsoni** [comment]
Closed with df465cc

**Comment by Sunil4imr** [comment]
Hello,
In symfony, I've been trying to add MYSQLI_OPT_READ_TIMEOUT in cofig.yml. it's not giving any error. but it didn't work for me.
i used it like this. is it a right way to use it in cofig.yml file?

> 
    doctrine:
            dbal:
                driver: pdo_mysql
                host: "%database_host%"
                dbname: "%database_name%"
                user: "%database_user%"
                password: "%database_password%"
                options:    
                    MYSQLI_OPT_READ_TIMEOUT : 1

**Comment by siimsoni** [comment]
This is an option for `mysqli` driver.
https://www.doctrine-project.org/projects/doctrine-dbal/en/2.10/reference/configuration.html#mysqli

**Comment by Sunil4imr** [comment]
I added mysqli driver but still  it's not working

        doctrine:
            dbal:
                driver: mysqli
                host: "%database_host%"
                port: "%database_port%"
                dbname: "%database_name%"
                user: "%database_user%"
                password: "%database_password%"
                server_version: '15.1'
                options:    
                      MYSQLI_OPT_READ_TIMEOUT : 1    
it's showing this error.....
`{"error":{"code":500,"message":"Internal Server Error","exception":[{"message":"An exception occurred in driver: Failed to set option 0 with value \"1\"","class":"Doctrine\\DBAL\\Exception\\DriverException","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"C:\\xampp\\htdocs\\pandora\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php","line":128,"args":[]},`

**Comment by siimsoni** [comment]
What is your PHP version and output of `var_dump(MYSQLI_OPT_READ_TIMEOUT)`?

**Comment by Sunil4imr** [comment]
php version is 7.4.8

**Comment by siimsoni** [comment]
You are most likely missing `mysqli` PHP extension.

**Comment by Sunil4imr** [comment]
i checked mysqli PHP extension in php.ini . it's uncommented there.

**Comment by siimsoni** [comment]
You will have to check the extension is actually loaded. If the extension is not installed, but enabled in `php.ini`, that would only emit a warning, and not stop program execution.

**Comment by Sunil4imr** [comment]
![image](https://user-images.githubusercontent.com/39276533/88784388-9bb37c00-d1ad-11ea-93fa-abb434ff0dc1.png)

**Comment by siimsoni** [comment]
Ok, that is interesting. So either you are missing `MYSQLI_OPT_READ_TIMEOUT` constant, or there is a problem with YAML.

This option is not documented, so it is unclear if there can be some environments where this is not defined (e.g. Windows). If it is not defined, `define ('MYSQLI_OPT_READ_TIMEOUT', 11);` should function as a workaround.

**Comment by Sunil4imr** [comment]
MYSQLI_OPT_READ_TIMEOUT attribute is in MysqliConnection.php.
![image](https://user-images.githubusercontent.com/39276533/88804671-e04e1000-d1cb-11ea-9cb4-ee081dd7ae32.png)

but i did not find where `define ('MYSQLI_OPT_READ_TIMEOUT', 11);` should be there??

**Comment by siimsoni** [comment]
This should probably be defined in some sort of a bootstrap file (e.g. index.php), before executing other code.

**Comment by Sunil4imr** [comment]
yes, now i'm sending this attribute from config as a constant, so now it's not giving any error
![image](https://user-images.githubusercontent.com/39276533/88808172-260cd780-d1d0-11ea-8b1b-ab13bf93cd6c.png)

but i put read_timout 1 sec and my request is taking more than 4 sec. so it should give some timeout warning or error. but it's not giving.

**Comment by siimsoni** [comment]
> my request is taking more than 4 sec

You mean a single MySQL query is taking more than 4 seconds, right? Then it sounds like this option is not supported on your platform. This is an issue beyond Doctrine, and it is hard to provide any further feedback here.

**Comment by Sunil4imr** [comment]
> > my request is taking more than 4 sec
> 
> You mean a single MySQL query is taking more than 4 seconds, right? Then it sounds like this option is not supported on your platform. These options are handled in mysqli extension and that's beyond DBAL, so it is hard to provide any further feedback here. I tested a PHP 7.4.8 Docker image with Mysqli extension, and there it worked fine.

ok, thanks
