### ISSUE TITLE
Unknown database type geometry requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

### ISSUE THREAD

**Issue by CoderForBestWorld** [doctrine/dbal#4183]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | x.y.z

**Comment by SenseException** [comment]
I have no clue what this PR is about. Please fill in the Summary, Current behaviour, how it can be reproduced and what the expected behaviour is.
