### ISSUE TITLE
Added the column/table names in the error message related to unknown column types

### ISSUE THREAD

**Issue by javiereguiluz** [doctrine/dbal#4194]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I was working on an existing application which had a database with many tables already created. One of those tables has a column of type `uuid` and my PostgreSQL version doesn't have support for that. So, I saw this error message when running some Doctrine commands:

```
[Doctrine\DBAL\DBALException]
Unknown column type "uuid" requested. Any Doctrine type that you use has to be registered
with  \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with
\Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection 
then you might have forgotten to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement 
Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with
the cache or forgot some mapping information.
```

If it's technically possible, could we please add the name of the column (and table) which had that unsupported type? It took me some time to find the table with this issue (because in this app there are no entities for all tables, so I can't look for in my code for this `uuid` type column). Example:

```
[Doctrine\DBAL\DBALException]
The "foo" column of the "bar" table uses the unknown column type "uuid".
Any Doctrine type that you use has to be registered with [...]
```

Thanks!

**Comment by greg0ire** [comment]
A stack trace would help a lot, consider providing wat? You can get it by following the steps described at https://github.com/symfony/symfony-docs/pull/13699, which I would love you to review :wink:

**Comment by javiereguiluz** [comment]
I'm closing this issue because sadly I won't have time to provide the requested details. Sorry!
