### ISSUE TITLE
SchemaManager dropDatabase failing

### ISSUE THREAD

**Issue by stuba** [doctrine/dbal#4198]
### Bug Report

It seems that dropDatabase is not quoting dbname. If there is some "special" characters dropDatabase will fail if string is not quoted before entering.

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.2

#### Summary

->dropDatabase('my-dbname') fails when there is for example '-' in the dbname. If dbname is quoted database will be dropped. ->dropDatabase('`my-dbname`')

#### Current behaviour

dropDatabase fails

#### How to reproduce

Create database having a dash and try to drop it.

#### Expected behaviour

database should end up gone.

**Comment by morozov** [comment]
Currently, DBAL doesn't automatically quote the names that need quoting and most likely it never will. On the contrary, it will require the consumer to quote all names including the keywords.
