### ISSUE TITLE
FetchMode::GROUP, FetchMode::UNIQUE are missing

### ISSUE THREAD

**Issue by ZaneCEO** [doctrine/dbal#4206]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.7

#### Summary

My code spits this: `PHP Deprecated: Using a PDO fetch mode or their combination (196610 given) is deprecated and will cause an error in Doctrine DBAL 3.0`, so I'm trying to [upgrade](https://github.com/doctrine/dbal/blob/v2.7.0/UPGRADE.md#deprecation-direct-usage-of-the-pdo-apis-in-the-dbal-api)

This should be the part where my code is unfit:

`$stmt->fetchAll(\PDO::FETCH_GROUP|\PDO::FETCH_UNIQUE|\PDO::FETCH_ASSOC)`

As suggested in the upgrade.MD, I tried to replace it with this:

`$stmt->fetchAll(FetchMode::GROUP|FetchMode::UNIQUE|FetchMode::ASSOCIATIVE)`

But it doesn't work, because the `FetchMode` class doesn't define neither FetchMode::GROUP nor FetchMode::UNIQUE 

What am I missing here?

Thanks!

**Comment by morozov** [comment]
Only the modes declared in the `FetchMode` class are available in DBAL 3.0. The `PDO` modes you're able to use with DBAL 2 are not supported consistently across drivers.

What's the intended behavior of the combination of `\PDO::FETCH_GROUP|\PDO::FETCH_UNIQUE|\PDO::FETCH_ASSOC`?

**Comment by ZaneCEO** [comment]
hi @morozov , sorry for the delay.

FETCH_ASSOC gets fields as column_name => value, GROUP takes 1st column and makes it the main key for the result array, however it will still be an array of single-item-arrays (assuming you have only 1 item per main key in the result set) - UNIQUE removes the unwanted level, basically saying "Hey dude, there is only 1 item per main key - so tidy up! :)"

See here: https://stackoverflow.com/a/29850792/1204976

**Comment by morozov** [comment]
I see. What's the use case for this way of presenting the result? Do you want to be able to reference a specific element of the array by its key?

**Comment by ZaneCEO** [comment]
Exactly! The whole point of `\PDO::FETCH_GROUP|\PDO::FETCH_UNIQUE|\PDO::FETCH_ASSOC` is to reference a specific element of the array by its key and remove some array nesting. Basically the result is

```
[
	5 => [
		"name" => "Peter",
		"last"    => "Parker",
		...
	],
	
	7 => [
		...
	]
]
```

**Comment by morozov** [comment]
I see but what's the use case for when you want to reference a specific element? How is it different from having the data presented as:
```php
[
    [
        "id" => 5,
        "name" => "Peter",
        "last"    => "Parker",
        // ...
    ],
    [
        "id" => 7,
        // ...
    ]
]
```

**Comment by ZaneCEO** [comment]
Whan you need to mix and match data from different datasource (some from a DB, some from API response), having the array indexed by a specific field is the faster and better way

**Comment by morozov** [comment]
Makes sense. I don't think DBAL should be in charge of grouping specifically, but having a method that behaves as you described might be handy. My only question for now is the method name.

**Comment by ZaneCEO** [comment]
I agree,  DBAL must not be in charge of grouping. But this is not something to be added to DBAL: it is already provided by PDO, so it's already handled by the layer below the DBAL.

One possible solution is to just add the missing constants `FetchMode::GROUP`, `FetchMode::UNIQUE` and `FetchMode::ASSOCIATIVE` to https://github.com/doctrine/dbal/blob/2.11.x/lib/Doctrine/DBAL/FetchMode.php, exactly like the other constants currently available have the corresponding `PDO::` value:

````
public const GROUP = \PDO::FETCH_GROUP;
public const UNIQUE= \PDO::FETCH_UNIQUE;
````

It would be AMAZING if we can also add this directly:

````
public const INDEX =\PDO::FETCH_GROUP|\PDO::FETCH_UNIQUE|\PDO::FETCH_ASSOC;
````

😛

**Comment by ZaneCEO** [comment]
Uh, I now see that [FetchMode.php is deprecated in Doctrine 3.x](https://github.com/doctrine/dbal/blob/3.0.x/UPGRADE.md#removed-fetchmode-and-the-corresponding-methods). I now see what you meant by "method name".

Well, a `fetchIndexed()` for the whole `\PDO::FETCH_GROUP|\PDO::FETCH_UNIQUE|\PDO::FETCH_ASSOC` sound appropriate to me 👍

**Comment by morozov** [comment]
@ZaneCEO please see https://github.com/doctrine/dbal/pull/4341.

**Comment by ZaneCEO** [comment]
Wow man, thank you very much! Great naming BTW, I fully agree it's better than mine 😄

**Comment by Evgeny1973** [comment]
If FetchMode.php is deprecated, how i can map data to class??
Like this 
` $qb->setFetchMode(FetchMode::CUSTOM_OBJECT, MyOwnDto::class)
return $qb->fetch();`

**Comment by morozov** [comment]
@Evgeny1973 you can't. See the details in https://github.com/doctrine/dbal/pull/3070.

**Comment by Evgeny1973** [comment]
A very strange decision.
Now what to do with a bunch of dto's in the project, how can I fill them in?

**Comment by morozov** [comment]
You can fill them in using the code that would previously fill them in the DBAL.

**Comment by uncaught** [comment]
In case someone needs this or this could be incorporated, too, these are replacements for more PDO modes:

```php
  /**
   * Replacement for fetchAll(\PDO::FETCH_GROUP)
   */
  public function fetchAllGrouped(string $query, array $params = [], array $types = []): array {
    $stmt = $this->executeQuery($query, $params, $types);

    $data = [];

    foreach ($stmt->fetchAllAssociative() as $row) {
      $data[array_shift($row)][] = $row;
    }

    return $data;
  }

  /**
   * Replacement for fetchAll(\PDO::FETCH_GROUP | \PDO::FETCH_COLUMN)
   */
  public function fetchAllGroupedColumn(string $query, array $params = [], array $types = []): array {
    $stmt = $this->executeQuery($query, $params, $types);

    $this->ensureHasKeyValue($stmt);

    $data = [];

    foreach ($stmt->fetchAllNumeric() as [$key, $value]) {
      $data[$key][] = $value;
    }

    return $data;
  }
```

**Comment by Evgeny1973** [comment]
Anyway, I think this is a stupid decision. If you don't want to support, leave it, don't touch it. And then people used it and suddenly everything was deleted.

**Comment by jove4015** [comment]
I agree - PDO is a fairly solid system already and offers this.  Why block it unnecessarily just because it may not work for everyone?  With no workaround or better offering?  It's just making your software less functional.
