### ISSUE TITLE
Documentation on DBAL\Driver\Statement.php is incorrect

### ISSUE THREAD

**Issue by gjdanis** [doctrine/dbal#4210]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

The documentation for [DBAL/Driver/Statement::bindValue](https://github.com/doctrine/dbal/blob/2.10.x/lib/Doctrine/DBAL/Driver/Statement.php#L26) is incorrect.

Per the [implementation](https://github.com/doctrine/dbal/blob/2.10.x/lib/Doctrine/DBAL/Statement.php#L87) this function can take a string, int, or type instance.

We should change this so that static analyzers like phpstan don't complain about this mismatch:

```
 ------ -----------------------------------------------------------------------------------------------------
  34     Parameter #3 $type of method Doctrine\DBAL\Driver\Statement::bindValue() expects int, string given.
 ------ -----------------------------------------------------------------------------------------------------

```

**Comment by SenseException** [comment]
The description of the docblock for the argument `$type` is referring to the constants of `ParameterType` class, which are all integer. But I agree that the implementing classes and the interface should be on one term. Do you propose to adapt the docblock in the interface? If you do, you're welcome to create a pull request.

**Comment by gjdanis** [comment]
Thanks @SenseException, @andrew-demb -- opened up a PR for this.

I don't think this will be a problem with future versions of the library since the [user facing query interface](https://github.com/doctrine/dbal/blob/master/src/Statement.php#L100) is different from the driver interface. It would be great if the team could consider this patch as it would save our applications from having to upgrade.

**Comment by morozov** [comment]
Fixed in https://github.com/doctrine/dbal/commit/15d9be0b3c87e05f428f8c2beb1fb9555e7b75bf.
