### ISSUE TITLE
Sporadic test failure on PDO_OCI

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#4225]
```
There was 1 error:

1) Doctrine\DBAL\Tests\Functional\Schema\OracleSchemaManagerTest::testDropsDatabaseWithActiveConnections
Exception: [Doctrine\DBAL\Exception\DriverException] An exception occurred while executing 'DROP USER test_drop_database CASCADE':

SQLSTATE[HY000]: General error: 1940 OCIStmtExecute: ORA-01940: cannot drop a user that is currently connected
 (/opt/oracle/php-src-php-7.4.9/ext/pdo_oci/oci_driver.c:348)
```

According to the test name, it is meant to drop a database with active connections but under certain circumstances, it fails to do so.

At the same time, it's not clear why this functionality is needed in the first place.

**Comment by greg0ire** [comment]
That functionality was introduced in https://github.com/doctrine/dbal/pull/849 
@deeky666 , maybe you remember why this was needed?

**Comment by morozov** [comment]
> This PR closes all active connections before dropping the database if dropping the database failed before.

IMO this is a fundamentally wrong approach, even from the DBAL's own perspective. If DBAL loses its connection, it will attempt to recreate it again before the next query. If a service that uses the database being dropped gets its connection closed, it will attempt to restore it and proceed thereby interfering with the process of dropping the database.

A proper approach is to either have a maintenance window during the database is inaccessible to its clients or perform a rolling migration.

**Comment by greg0ire** [comment]
Should we drop the flaky test? It's annoying to have to restart the builds every time.

**Comment by morozov** [comment]
I can mark it as incomplete for Oracle in https://github.com/doctrine/dbal/pull/4230 based on your earlier findings.
