### ISSUE TITLE
Schema Manager : listTableDetails() does not handle custom SQLServer schema

### ISSUE THREAD

**Issue by mvachette** [doctrine/dbal#4249]
### Bug Report

\Doctrine\DBAL\Schema\SQLServerSchemaManager::listTableDetails() does not work when default db schema is not "dbo" => there is not table listed.

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.10.0

#### Summary

I'm trying to call \Doctrine\DBAL\Schema\SQLServerSchemaManager::listTableDetails() on a database with a default schema name that is not "dbo", but its seems unsupported

#### Current behaviour

No table is listed at all.

In the code of  \Doctrine\DBAL\Platforms\SQLServerPlatform::getListTableMetadataSQL(), we can see that is there an harcoded "dbo" schema used.

#### Expected behaviour

Either table listing use the current database default schema (like any other operation, prefered option), or provide a way to specify the schema to be used.

**Comment by morozov** [comment]
@mvachette mind adding a simple reproducer?
