### ISSUE TITLE
New assertion breaks QueryBuilder with dummy driver

### ISSUE THREAD

**Issue by Bilge** [doctrine/dbal#4250]
I use the Doctrine QueryBuilder with a foreign database library. Since the QueryBuilder does not work without a driver, I create a dummy driver so I can just use the QueryBuilder. This worked until a BC break in a minor revision that added an assertion that disagrees with the type hint on the backing field.

### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.10.3

#### Summary

When upgrading from 2.10.2. to 2.10.3 my code breaks due to this change: https://github.com/doctrine/dbal/commit/e48861ecca29fb44b450e36230452a40125f64bf

https://github.com/doctrine/dbal/blob/e48861ecca29fb44b450e36230452a40125f64bf/lib/Doctrine/DBAL/Connection.php#L1459

#### Previous behaviour

Previously `$this->_conn` was allowed to be `null`. The type hint for `$_conn` still reads as nullable, but for some reason this assertion was added that disagrees with this.

https://github.com/doctrine/dbal/blob/e48861ecca29fb44b450e36230452a40125f64bf/lib/Doctrine/DBAL/Connection.php#L82-L87

#### Current behavior

Since the assertions forces `$_conn` to be non-null, it breaks cases where `$_conn` is null.

#### How to reproduce
```php
<?php
declare(strict_types=1);

use Doctrine\DBAL\Driver\AbstractPostgreSQLDriver;

final class DummyPostgresDriver extends AbstractPostgreSQLDriver
{
    public function connect(array $params, $username = null, $password = null, array $driverOptions = []): void
    {
        // Intentionally empty.
    }

    public function getName(): string
    {
        return __CLASS__;
    }
}

$qb = (new Doctrine\DBAL\Connection([], new DummyPostgresDriver))->createQueryBuilder();
$qb->setMaxResults(50); // Only occurs when max results is defined.
$qb->getSql(); // This eventually calls Connection::getWrappedConnection(), triggering the assertion to fail.
```

**Comment by greg0ire** [comment]
Before the assertion was added, there was a contract for implementations though:

https://github.com/doctrine/dbal/blob/e48861ecca29fb44b450e36230452a40125f64bf/lib/Doctrine/DBAL/Connection.php#L1453

The contract is enforced now, any implementation should already be compliant. You can work this around by disabling assertions, or you could implement the contract by returning a dummy implementation of `DriverConnection`.

**Comment by Bilge** [comment]
The class itself is already a `DriverConnection`. I could inject it into itself but that seems silly.

**Comment by greg0ire** [comment]
Doesn't having a dummy driver feel silly already? Anyway, I don't think we are going to revert this to humor this use case, sorry. Feels a bit too much like xkcd 1172

**Comment by Bilge** [comment]
Doesn't having a QueryBuilder tied to an active connection feel silly? I'm trying to work around these artificial constraints.

**Comment by greg0ire** [comment]
It sure does. Good luck with your issue.

**Comment by greg0ire** [comment]
Closing as per https://github.com/doctrine/dbal/pull/4094#issuecomment-686750995
