### ISSUE TITLE
PHPStan error: "Unable to resolve the template type T" in DriverManager

### ISSUE THREAD

**Issue by pkruithof** [doctrine/dbal#4264]
Continued from https://github.com/doctrine/dbal/pull/3977#issuecomment-689606532

|    Q        |   A
|------------ | -----
| Version     | 2.10.x

### Support Question

As discussed in #3977, the annotations for the `DriverManager` class now result in a PHPStan error.

https://github.com/doctrine/dbal/blob/f97ee9445186e2f5edd519579405df53521cdae4/lib/Doctrine/DBAL/DriverManager.php#L116-L130

 This error is currently ignored by this repo: https://github.com/doctrine/dbal/blob/f97ee9445186e2f5edd519579405df53521cdae4/phpstan.neon.dist#L101-L106

However the same error is reported in projects that use dbal (when they use the `DriverManager` of course), which I think should not happen. Here is the trimmed down version of the error case: https://phpstan.org/r/6ffb80b4-bb00-419d-bc98-887488e1c36b

The PHPStan author [suggested](https://github.com/phpstan/phpstan/issues/3849#issuecomment-689517922) a possible solution, which does not work unfortunately. So there is more investigation needed as to why this happens, and how to resolve it.

**Comment by muglug** [comment]
In my opinion this sort of error should not be shown to users of a static analysis tool — it’s rarely ever the users’ fault.

**Comment by ondrejmirtes** [comment]
FYI the annoying message about "unable to resolve template type" will no longer show up in these cases (because the template type is not present in the return type used by PHPStan): https://phpstan.org/r/3273047f-31d7-42bb-8763-357e10553eb5

Thanks to commit: https://github.com/phpstan/phpstan-src/commit/a5f9f0c26d9112e5add6d74758b0f7388a141da0

**Comment by greg0ire** [comment]
@pkruithof can you please try updating and report back?

**Comment by greg0ire** [comment]
Thanks @ondrejmirtes BTW :)

**Comment by pkruithof** [comment]
> @pkruithof can you please try updating and report back?

Unfortunately I cannot remember where I encountered this, and I can't find any references in our repositories to it anymore. 😅

I'll close the issue for now as I believe it should be resolved. Should I encounter it again I can always open a new ticket.

**Comment by pkruithof** [comment]
@greg0ire last night phpstan was updated by Dependabot in the project that had this issue, and where we ignored the error to fix it. The ignore is no longer needed so I can confirm that the issue is indeed fixed.

**Comment by greg0ire** [comment]
Great, thanks a lot!
