### ISSUE TITLE
Cockroach Compatibility / dbal

### ISSUE THREAD

**Issue by tdashton** [doctrine/dbal#4265]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

I am wondering if there is / will be an effort to support the rest of the CockroachDB internals with Doctrine? The wire protocol for Cockroach is supported by `pdo_pgsql` however many of the internals of the driver are broken, including

* differently named functions for generating `uuid` s
* internal schema differences in things like the sequences:

```
In AbstractPostgreSQLDriver.php line 60:

  An exception occurred while executing 'SELECT min_value, increment_by FROM "ledger_entries_id_seq"':

  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
```

actual structure is similar in Cockroach:

```
SELECT * FROM "whatever_id_seq";
 last_value | log_cnt | is_called
------------+---------+-----------
          0 |       0 | t
(1 Zeile)
```

* different internal column types: https://github.com/cockroachdb/cockroach/issues/19337

and probably more.

In my (amateur) estimation this could be covered by adding a logic in  a new `\Doctrine\DBAL\Driver\PDOPgSql\Connection` class which detects the difference between an underlying Cockroach DB and a PostgresSQL db and returns an appropriate platform.

Is anyone aware of any forks or similar attempts to bridge this compatibility gap? I would also be willing to help!

Many thanks in advance!

Tyler

**Comment by morozov** [comment]
> In my (amateur) estimation this could be covered by adding a logic in a new `\Doctrine\DBAL\Driver\PDOPgSql\Connection` class which detects the difference between an underlying Cockroach DB and a PostgresSQL db and returns an appropriate platform.

You can pass the Cockroach DB platform as a connection parameter to DBAL connection w/o having to implement any auto-detection logic in the connection.

**Comment by beberlei** [comment]
I agree with @morozov here, you can provide a Cockroach DB platform in the factory of DBAL and provide it as a third party package. Doctrine itself is not going to support this in the near or mid-term future.

**Comment by y4roc** [comment]
I'm looking for some people who like to create a third party package to connect doctrine/dbal with cockroachdb. I found a package [doctrine-cockroachdb](https://github.com/lapaygroup/doctrine-cockroachdb), but this isn't working currently with the doctrine-migrations commands.

So we need to fix it and can use it soon. My problem is, that the error message makes no sense. I know the connection is the problem. I hope someone can help me to understand this error-message.
