### ISSUE TITLE
Doctrine fails to declare Extended Property on SQL-Server array column (when table name is quoted) 

### ISSUE THREAD

**Issue by metaturso** [doctrine/dbal#4283]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | possibly
| Version     | ORM v2.6.3, DBAL v2.9.2
| Database Server | Microsoft SQL-Server 2017
| Doctrine Driver | `pdo_sqlsrv`

#### Summary

The following error happens when using Doctrine's `SchemaTool` to construct an entity requiring Extended Properties which also has a quoted table name:

```
'An exception occurred while executing 'EXEC sp_addextendedproperty N'MS_Description', N'(DC2Type:array)', N'SCHEMA', 'dbo', N'TABLE', '[the-table]', N'COLUMN', chairs':
                                                                                                                                 
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server] Object is invalid. Extended properties are not permitted on 'dbo.[the-table].chairs', or the object does not exist.'
```

The user has sufficient permissions to add Extended Properties to the database metadata. If I understand this right, this problem is happening because of the quoted table name being passed to the stored procedure as a string (i.e. the databases recognises `[the-table] !== "[the-table]"`.)

Stopping Doctrine from quoting the table name **fixes the problem**, alas I can't afford to rename the table.

#### Current behavior

The database server refuses to execute the query because it does not recognise the referenced object.

#### How to reproduce

1. Declare an entity whose name is a quoted symbol, e.g. 
```php
/**
 *@Table(name="`the-table`")
 */
class TheTable 
{
}
```
2. Add a column requiring the use of Extended Properties by Doctrine

```php
class TheTable
{
 /**
  * @ORM\Column(type="array", name="chairs")
  */
 private $chairs;
}
```

3. Use the Schema Tool to create the tables

```php
$schemaTool = new SchemaTool($entityManager);
$schemaTool->createSchema([
 $entityManager->getMetadataForClass(TheTable::class)
]); 
```

#### Expected behavior

Doctrine can successfully attach the Extended Properties that it needs to the column.

**Comment by SenseException** [comment]
Depending on the test this seems to be a DBAL issue.
