### ISSUE TITLE
Add a fetch mode methods for "PDO::FETCH_KEY_PAIR"

### ISSUE THREAD

**Issue by tswcode** [doctrine/dbal#4289]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Let's assume a sql, summarizing entity ids and a special count. Then I need the workflow like the default PDO does:

<pre lang=php>
public function countOrders()
{
    $sql = 'SELECT `e`.`id`, COUNT(`o`.`id`) 
        FROM `event` AS `e` 
        LEFT JOIN `order` AS `o` ON `o`.`event_id` = `e`.`id`
        WHERE `o`.`deleted` = 0
        GROUP BY `e`.`id` ';

    $dbConnection = $this->getEntityManager()->getConnection();
    $sqlStatement = $dbConnection->prepare($sql);
    $sqlStatement->execute();

    $counts = $sqlStatement->fetchAll(PDO::FETCH_KEY_PAIR); 
    $sqlStatement->free();

    return $counts;
}
</pre>

The result was an array with the ids as keys and counts as values, like:
<pre lang=php>
array (2) [
    11 => integer 10
    22 => integer 5
]
</pre>

Since the old fetch methods are deprecated, it would be great to implement 
an adequate method to the PDO feature to reduce boilerplate code.

Here is an quote from @morozov of #4019 
<pre lang=php>
$conn = new PDO('sqlite::memory:');
$stmt = $conn->query('SELECT 1');

$stmt->fetchAll(PDO::FETCH_KEY_PAIR);

// PDOStatement::fetchAll(): SQLSTATE[HY000]: General error: PDO::FETCH_KEY_PAIR fetch mode requires the result set to contain extactly 2 columns
</pre>

As @morozov mentioned:
> Looks like PDO is strict enough about the number of columns. I think we can implement this in DBAL at the wrapper level which will automatically cover all supported drivers.

**Comment by morozov** [comment]
```php
$sqlStatement->fetchAll(PDO::FETCH_KEY_PAIR, 0);
```
@tswcode what does the second argument in this call mean? I cannot find any documentation for it.

**Comment by tswcode** [comment]
Oh sorry, that was copy and paste. I guess it previously was an PDO::FETCH_COLUMN. I'll edit the first post.

**Comment by Gamesh** [comment]
here is a good documentation of this and all the other modes that are now not accessible from DBAL https://phpdelusions.net/pdo/fetch_modes

**Comment by morozov** [comment]
Closed via https://github.com/doctrine/dbal/pull/4338.

**Comment by uncaught** [comment]
@morozov I am a bit confused about the interfaces returned by `executeQuery()` and I am not getting code completion for `fetchAllKeyValue()`. Is the method missing somewhere? I am not seeing it in `Doctrine\DBAL\Driver\PDOStatement` nor in `Doctrine\DBAL\Driver\Result` where I find the other mapping fetches like `fetchAllAssociative()`.

(I'm still on 2.12.x, but not seeing it in the 2.13 branch, either)


Edit: Sorry, never mind, didn't realize they are all on the connection now directly!
