### ISSUE TITLE
Don't ignore empty strings in QueryBuilder

### ISSUE THREAD

**Issue by BenMorel** [doctrine/dbal#4290]
The following methods ignore an empty string as a parameter:

- `QueryBuilder::andWhere()`
- `QueryBuilder::orWhere()`
- `QueryBuilder::andHaving()`
- `QueryBuilder::orHaving()`

This behaviour was kept in 2.x for BC reasons, but makes no sense in 3.0, where no validation of the expression should be made.

---

For 3.0, just revert commit 0325f424ae9d85d5085b6ebe13bae13c84bea9cb.

**Comment by BenMorel** [comment]
@morozov Please mark as a blocker and assign to the 3.0.0 milestone!

**Comment by morozov** [comment]
Done. Thanks, @BenMorel.

**Comment by morozov** [comment]
Closed via #4300.
