### ISSUE TITLE
Using setAutoincrement in a migration fails schema validation on postgres

### ISSUE THREAD

**Issue by Rainrider** [doctrine/dbal#4328]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.11.1

#### Summary

Using `$table->addColumn('id', 'integer')->setAutoincrement(true);` in a migration leads to database schema validation failure on PostgreSQL (versions 13, 12 and 11 tested).

#### Current behaviour

We want to use the Doctrine DBAL API in migrations to keep them platform independent as far as possible. The current workflow is something like that:

1. Create an entity
2. Create the migration `php bin/console doctrine:migrations:diff`
3. Re-write the migration using the DBAL API instead of SQL
4. Run the migration `php bin/console doctrine:migrations:migrate`
5. Validate the schema `php bin/console doctrine:schema:validate`

This is successful for mariadb but fails in the last step for postgres. All other steps are fine.

```
# output of php bin/console doctrine:schema:update --dump-sql
ALTER TABLE book ALTER id DROP DEFAULT;
```

It obviously wants to drop the default value which is correctly set to `nextval('book_id_seq'::regclass)` by the migration.

#### How to reproduce

Please see https://github.com/Rainrider/doctrine-schema-validate for a minimal repro.

0. `git clone https://github.com/Rainrider/doctrine-schema-validate && cd doctrine-schema-validate`
1. `composer install`
2. `docker-compose up -d`
3. `php bin/console doctrine:migrations:migrate`
4. `php bin/console doctrine:schema:validate`

There is also a mariadb configuration in the repo for a comparison - please checkout the `mariadb` tag if interested.

#### Expected behaviour

I would expect the schema validation to pass with my entity configuration:
```php
/**
 * @ORM\Id
 * @ORM\GeneratedValue
 * @ORM\Column(type="integer")
 */
private $id;
```

**Comment by Rainrider** [comment]
A short feedback in this would be much appreciated.

Is the expected behaviour unreasonable? Is the use case irrelevant?

**Comment by morozov** [comment]
> Please see https://github.com/Rainrider/doctrine-schema-validate for a minimal repro.

@Rainrider a minimal repro should not contain any dependencies besides the DBAL itself. Please try to provide a minimal self-contained scenario.

**Comment by Rainrider** [comment]
@morozov I created a new simple repo for reproduction unter https://github.com/Rainrider/doctrine-schema-validate2 using only doctrine/orm, doctrine/dbal and doctrine/migrations (I can't tell which one is to blame for this very issue and hope you guys might figure this out)

0. `git clone https://github.com/Rainrider/doctrine-schema-validate2.git && cd doctrine-schema-validate2`
1. `composer install`
2. `docker compose up -d`
3. `php bin/migrations migrate -n`
4. `php bin/doctrine orm:validate-schema`

```console
Mapping
-------

                                                                                                                        
 [OK] The mapping files are correct.                                                                                    
                                                                                                                        

Database
--------

                                                                                                                        
 [ERROR] The database schema is not in sync with the current mapping file.  
```

I would expect the schema validation to pass as it is the case with mariadb (you can check the `mariadb` branch for this).

**Comment by morozov** [comment]
@Rainrider, the repro should not contain any dependencies besides the DBAL itself.

> I can't tell which one is to blame for this very issue and hope you guys might figure this out.

Then why are you filing a bug in the DBAL?

**Comment by Rainrider** [comment]
> Then why are you filing a bug in the DBAL?

Because if I generate the migration by using the doctrine-migrations cli (`diff`), it produces platform specific sql:
```php
public function up(Schema $schema): void
{
    // this up() migration is auto-generated, please modify it to your needs
    $this->addSql('CREATE SEQUENCE Book_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
    $this->addSql('CREATE TABLE Book (id INT NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
}

public function down(Schema $schema): void
{
    // this down() migration is auto-generated, please modify it to your needs
    $this->addSql('CREATE SCHEMA public');
    $this->addSql('DROP SEQUENCE Book_id_seq CASCADE');
    $this->addSql('DROP TABLE Book');
}
```
which leads to a valid schema. But when I use `Doctrine\DBAL\Schema\Schema` [like in the repro](https://github.com/Rainrider/doctrine-schema-validate2/blob/main/migrations/Version20220212203455.php), then I have a platform independent migration which fails validation.

> the repro should not contain any dependencies besides the DBAL itself

I know very little about doctrine internals. I did provide an example to you which describes my use case the way I experience it. I cannot reproduce it without doctrine/migrations because this is where I use `Doctrine\DBAL\Schema\Schema`. I cannot strip away doctrine/orm because it provides the cli command I use for verification. If this is not good enough, then I don't know any better and I can't provide anything simpler than that which still reproduces my problem.

**Comment by greg0ire** [comment]
@Rainrider this is where `doctrine/migrations` uses `doctrine/dbal`: https://github.com/doctrine/migrations/blob/e7df670aa9565b435ffec636cebdb4d0a1987f10/lib/Doctrine/Migrations/Generator/DiffGenerator.php#L93-L123

Maybe you can debug until that point, and then try to reproduce the issue by copy/pasting those lines and creating `$fromSchema` and `$toSchema` manually (maybe you can do so thanks to `var_export`), in a custom Symfony command that would be able to retrieve the schema manager?

**Comment by morozov** [comment]
Closing due to the lack of feedback.
