### ISSUE TITLE
PDOException: SQLSTATE[HY000]: General error: 20003 Adaptive Server connection timed out [20003] (severity 6)

### ISSUE THREAD

**Issue by Dbaldeveloper** [doctrine/dbal#4331]
Tried to update the php 7.0 to php 7.2 and using the Doctrine/DBAL 2.10.* version to connect to SQL Server(Remote server).
DBAL + SQL server communication works fine in PHP 7.0 Whereas in new environment, this error occurring "PDOException: SQLSTATE[HY000]: General error: 20003 Adaptive Server connection timed out [20003] (severity 6)" for long running queries > 30 seconds. Increased the php max execution time, Remote sql server and Environment variables are also changed but it does not resolve this issue.

This is happening in AWS linux. 

Could you please provide your insight on this and help me.

**Comment by morozov** [comment]
A timeout issue is unlikely related to the DBAL.
