### ISSUE TITLE
Removal of getSQLResultCasing without alternative breaks ORM assumptions

### ISSUE THREAD

**Issue by beberlei** [doctrine/dbal#4335]
### BC Break Report

The ORM currently does not quote any identifier. This means the default case for unquoted columns of each database is used, which is a.) depends on server config for MySQL, but by default its case used at creation b.) lowercase for postgresql c.) uppercase for Oracle.

To allow the ORM to support arbitrary databases, the platform must need to know what this behavior is of each platform, so that when it fetches the result of an SQL query without quoted identifiers it can access the values correctly.

When you declare a field in the ORM with for example `<field name="name" />` then the quoting strategy uses `AbstractPlatform::getSQLResultCasing` to determine if the column for this field is `name` or `NAME`.

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.0

#### Summary

`AbstractPlatform::getSQLResultCasing` was removed, is platform specific behavior needed in ORM. ORM can't offer this abstraction itself as it depends on Platform.

**Comment by morozov** [comment]
As discussed offline, instead of mimicking the behavior of a specific database platform by using the API above, consumers may use the portability layer and normalize the behavior instead. @beberlei please let me know if you expect more work to be done on this issue.

**Comment by morozov** [comment]
As discussed offline, using the portability layer is the proper way to address this issue in consumers.

**Comment by greg0ire** [comment]
@morozov to be clear, this means calls to `getSQLResultCasing` should be removed from the ORM, and people should be advised to use https://github.com/doctrine/dbal/blob/3.1.x/docs/en/reference/portability.rst ?

**Comment by morozov** [comment]
In my understanding, the ORM itself currently relies on the column casing, so it should be using the portability middleware instead.

**Comment by greg0ire** [comment]
Ok, so in `Doctrine\ORM\Configuration::__construct()`, there should be the following call: `$this->setMiddlewares([new \Doctrine\DBAL\PortabilityMiddleware(NOT_SURE_WHAT_TO_PASS_HERE, NOT_SURE_WHAT_TO_PASS_HERE_EITHER)])`?

**Comment by beberlei** [comment]
Referencing https://github.com/doctrine/orm/issues/8887 here as the first step in the 2.x branches.

**Comment by morozov** [comment]
The arguments should be `(Connection::PORTABILITY_FIX_CASE, ColumnCase::LOWER)`.
