### ISSUE TITLE
executeQuery() relies on deprecated setFetchMode()

### ISSUE THREAD

**Issue by antonmakarenko** [doctrine/dbal#4345]
### Bug Report

`\Doctrine\DBAL\Connection::executeQuery()` invokes `$stmt->setFetchMode()` - but it is deprecated.
https://github.com/doctrine/dbal/blob/2.11.x/lib/Doctrine/DBAL/Connection.php#L1222

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.11.1

#### Summary

I am implementing a custom driver that DBAL does not have out of the box. I noticed many methods of `\Doctrine\DBAL\Driver\ResultStatement` are deprecated, referring to `\Doctrine\DBAL\Driver\Result` as an alternative. So in my custom Statement implementation, I decided to throw an exception preventing use of any deprecated functionality and see what happens.

#### Current behaviour

In many places in `\Doctrine\DBAL\Connection` you have something like this:
```php
if ($stmt instanceof Result) {
    return $stmt->fetchAssociative();
}
```

But not in `executeQuery()`

#### How to reproduce

My implementation of the statement:
```php
public function setFetchMode($fetchMode, $arg2 = null, $arg3 = null)
{
    throw new Exception('setFetchMode() is deprecated in DBAL. Use one of the fetch- or iterate-related methods.');
}
```

```php
$dbal->executeQuery('... any SQL');
```

Throws an exception.

#### Expected behaviour

Should avoid using deprecated `setFetchMode()` or add a similar logic `if ($stmt instanceof Result)`

**Comment by morozov** [comment]
This is by design. Calling a method on a class that can be extended is part of the contract. Not calling it might cause a BC break,
