### ISSUE TITLE
Bug with PostgreSQL schema manager after update on 2.11.2

### ISSUE THREAD

**Issue by andreybolonin** [doctrine/dbal#4359]
<img width="361" alt="Screen Shot 2020-10-19 at 10 39 12 AM" src="https://user-images.githubusercontent.com/2576509/96415484-5a07ff80-11f7-11eb-9b11-78bcc69bd318.png">

**Comment by sasule** [comment]
I have the same problem.
My configuration: Postgre13 and php 7.4.11.

**Comment by digitv** [comment]
I confirm the same behaior on our app (Laravel 6) deploy with bitbucket pipepines.
PHP 7.4.5
PostgreSQL10

**Comment by shEtendard** [comment]
```
assert(preg_match(
            '/FOREIGN KEY \((.+)\) REFERENCES (.+)\((.+)\)/',
            $tableForeignKey['condef'],
            $values
        ) !== 0);
```
https://www.php.net/manual/en/function.preg-match.php
preg_match() returns 1 if the pattern matches given subject, 0 if it does not, or FALSE if an error occurred.

**Comment by agustingomes** [comment]
I can confirm the same error in the [PostgreSqlSchemaManager.php](https://github.com/doctrine/dbal/blob/b88a45cbc395e850b2d958dcd7b9d49d09ff23e0/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php#L165).

In my case it was with php 7.4.11 and Postgres 10.6

**Comment by SindlaXYZ** [comment]
Same error after 2.11.2 update (from 2.11.1).

PHP 7.4.11 & PostgreSQL 12.4

**Comment by pelikan7** [comment]
The code inside assert() does not run at all, leaving $values as undefined variable

**Comment by bensquire** [comment]
Can also confirm the problem, 2.4.12 from 2.4.11, PostgresSQL, PHP 7.4.11.

**Comment by jarofgreen** [comment]
Confirmed, downgrading to 2.11.1 fixes it fine.

In my case I got it in Symfony 5.1 when running:

    ./bin/console doctrine:schema:drop --force --quiet

**Comment by morozov** [comment]
The issue is reproducible via the existing test suite with disabled assertions (`zend.assertions=-1`):
```
$ phpunit -c pdo-pgsql.phpunit.xml tests/Doctrine/Tests/DBAL/Functional/Schema/PostgreSqlSchemaManagerTest.php

PHPUnit 9.4.0 by Sebastian Bergmann and contributors.

......EE.E...EEE...............E.......EEE....EE.....E.E.S...........S........... 81 / 85 ( 95%)
..S.                                                                              85 / 85 (100%)

Time: 00:07.376, Memory: 18.00 MB

There were 14 errors:

1) Doctrine\Tests\DBAL\Functional\Schema\PostgreSqlSchemaManagerTest::testTableWithSchema
Exception: [PHPUnit\Framework\Error\Notice] Undefined variable: values
...
```

**Comment by EdgarSedov** [comment]
Holy shit, i've spent so many hours trying to find this thread via google, but found only after i've looked into blame for file)
