### ISSUE TITLE
ibm_db2: OUT parameter

### ISSUE THREAD

**Issue by tdutrion** [doctrine/dbal#4369]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Currently, the IBM DB2 [uses the constant DB2_PARAM_IN](https://github.com/doctrine/dbal/blob/3.0.x/src/Driver/IBMDB2/Statement.php#L96) in the Statement class, not letting the user choose the parameter direction.

I can't find a way to change this parameter (the bind method being private), hence not letting me call a stored procedure with outgoing parameters.

I think it should be doable without breaking compatibility, if anyone can confirm that I haven't missed a way, then I can work on this feature.

**Comment by morozov** [comment]
DBAL currently doesn't support out parameters with any drivers since stored procedures cannot be ported across the platform.

**Comment by tdutrion** [comment]
Ok then. I'll therefore close this issue unless that's something you'd like to be worked on, but as it's not fully cross platform I guess that's not interesting for the project.

Thanks
