### ISSUE TITLE
Migration diff always produce "Undefined variable: values" on PostgreSQL

### ISSUE THREAD

**Issue by seticzech** [doctrine/dbal#4375]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.11.2

After update to the last version `migrations diff` stops working and always breaks on **[ErrorException]
 Notice: Undefined variable: values**.

Exception trace ends at:
/*/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php:165

Problem lays in next code:

_current version:_
```
assert(preg_match(
    '/FOREIGN KEY \((.+)\) REFERENCES (.+)\((.+)\)/',
    $tableForeignKey['condef'],
    $values
) !== 0);
```

_previous functional version:_
```
$result = preg_match('/FOREIGN KEY \((.+)\) REFERENCES (.+)\((.+)\)/', $tableForeignKey['condef'], $values);
assert($result === 1);
```

It's really **bad idea** to close code to assertions which are ignored in production environment: https://www.php.net/manual/en/function.assert.php

**Comment by greg0ire** [comment]
Please, perform a search for similar issues before opening one. This is reporting bugs 101.
