### ISSUE TITLE
Quote all identifiers in SQL implicitly

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#4385]
see https://github.com/doctrine/dbal/pull/4360/files#diff-260f15d92dacb5c7db10faacb895b841a9b843c53b7b46455ae4e0a442a655a9R41

wdyt about to quote all identifiers in SQL implicitly (instead of explicitly), ie.
- set `quoted` by default to `true`
- **forbid use of quoted name as string**
- allow unquoted names (for BC) by setting `quoted` = false
- maybe renamed `quoted` to `unquoted` - but this will be breaking because of changed names

I very strongly support this idea as it will prevent all issues with dangerously left unquoted/unsupported names and still allow to use unquoted names.

I propose this for 3.x

**Comment by greg0ire** [comment]
Does it relate to #4357 ?

**Comment by mvorisek** [comment]
> 
> 
> Does it relate to #4357 ?

Yes, #4357 is statement about a problem, this issue is how to solve it.

**Comment by greg0ire** [comment]
You may try to find more information in existing issues, I think #4357 is rooted in previous experiences, and I have a vague memory of quoting everything not being an option. Otherwise, let's just wait for the promised information in #4357

**Comment by morozov** [comment]
We can't quote identifiers automatically because a lot of APIs already accept a string that may be a quoted or a non-quoted identifier. At this point, we don't know if it needs to be quoted or not. This issue is tracked in https://github.com/doctrine/dbal/issues/4772.
