### ISSUE TITLE
dbal/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php should override getLengthExpression() and use CHAR_LENGTH()

### ISSUE THREAD

**Issue by cmanley** [doctrine/dbal#4388]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | x.y.z

#### Summary

For multibyte character encodings in MySQL, the CHAR_LENGTH() function returns the character length.
So it seems to me that dbal/lib/Doctrine/DBAL/Platforms/MySqlPlatform.php should override getLengthExpression() and use CHAR_LENGTH() instead of LENGTH() as inherited from the parent class.

#### Current behaviour

Incorrect calculation of string lengths for strings containing multibyte characters.

#### How to reproduce

Place a single multibyte character in a mysql field with utf8mb4 encoding and then calculate it's length with getLengthExpression().

#### Expected behaviour

1

**Comment by morozov** [comment]
Should be fixed by https://github.com/doctrine/dbal/pull/4855.
