### ISSUE TITLE
Exception type error

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#4389]
v 2.11.3

![image](https://user-images.githubusercontent.com/2228672/97298734-2874e100-1854-11eb-8c50-89767b8b58ce.png)

**Comment by morozov** [comment]
@mvorisek what do you expect to be done with this report?

**Comment by mvorisek** [comment]
check the stack trace against the 2.11.3 dbal code and fix it, as some unexpected error is thrown or too strict type is declared

**Comment by greg0ire** [comment]
I think this is what they call a [shrug report](https://blog.codinghorror.com/new-programming-jargon/)

**Comment by morozov** [comment]
I checked the stack trace and decided to not fix it.

**Comment by mvorisek** [comment]
so there is an issue and it wont't be fixed?
