### ISSUE TITLE
OracleSessionInit bug when there is also another DB in use

### ISSUE THREAD

**Issue by vuras** [doctrine/dbal#4392]
Hi everyone,

I am using Symfony 5.1.7 together with doctrine/dbal 2.12.0 on my project.
Project has two databases in use: primary Sqlite and secondary Oracle.
I needed to alter my session date environment variables then I registered OracleSessionInit as an event listener and then the error occured:

> An exception occurred while executing 'ALTER SESSION SET NLS_TIME_FORMAT = 'HH24:MI:SS' NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS' NLS_TIMESTAMP_TZ_FORMAT = 'YYYY-MM-DD HH24:MI:SS TZH:TZM' NLS_NUMERIC_CHARACTERS = '.,'':

> SQLSTATE[HY000]: General error: 1 near "SESSION": syntax error

I solved it by extending the class and adding this if clause in postConnect method:

> public function postConnect(ConnectionEventArgs $args): void
>     {
>         if (!$args->getConnection()->getDatabasePlatform() instanceof OraclePlatform) {
>             return;
>         }
>         parent::postConnect($args);
>     }

The problem is that event listener is called after connection to every registered database and these session variables do not exist in Sqlite therefore I had to add a check on which database platform a listener is being executed.

After extending it I can use it successfully but I thought you should know about it and fix it.

Thank you :)

**Comment by morozov** [comment]
@vuras did you register `OracleSessionInit` for the SQLite connection as well? Otherwise, how can I reproduce it?
