### ISSUE TITLE
Allow MySQL tables to be created using the database default character set and collation

### ISSUE THREAD

**Issue by gggeek** [doctrine/dbal#4404]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | yes/no

#### Summary

The current implementation of `MySqlPlatform::buildTableOptions` makes it unnecessarily hard to create "generic" php code that would be useful for creating tables that do not specify the character set and/or collation in their creation SQL statement.

As mysql allows to specify charset and collation defaults for a database, it seems a useful solution for many scenarios to allow to specify the charset/collection once, as db defaults, and then omit them from all/most table definitions.

Example usecase: bundle A creates tables, using a different charset/collation in its versions 1 and 2; bundle B creates tables that need to be joined to the tables of A, and tries to be compatible with both A.1 and A.2.

At the moment the developer is forced to specify the charset if she wants not to have 'utf8', and for older version of Doctrine this leads in cascade to having to specify collation as well (otherwise DBAL might attempt to set an invalid collation).
The default character set / collation of the database seem almost impossible to be retrieved and taken into account.

What about accepting NULL as valid options for 'charset' and 'collate', which would result in the table-creation SQL statement omitting the DEFAULT CHARACTER SET and COLLATE clauses?

**Comment by gggeek** [comment]
Seems related yo old issue #1529

**Comment by gggeek** [comment]
Not unrelated to #2441, either

**Comment by gggeek** [comment]
> What about accepting NULL as valid options for 'charset' and 'collate', which would result in the table-creation SQL statement omitting the DEFAULT CHARACTER SET and COLLATE clauses?

If giving a different meaning to NULL is considered a BC, we might introduce a string value of eg. 'default' with the meaning of 'use the db default'.

Btw, the same logic can also be applied to the ENGINE specification.

**Comment by morozov** [comment]
This looks like the right concern to me. The DBAL shouldn't enforce such defaults. Please feel free to initiate a PR.

> If giving a different meaning to NULL is considered a BC

I believe it would be a BC break because right now these options are checked via `isset()` and default to some non-empty values.

> we might introduce a string value of eg. 'default' with the meaning of 'use the db default'.

What if we introduce temporary boolean options instead, e.g. `use_default_{charset,collate,engine}` that could be dropped in the next major version? It would be better than having magic values of the existing options.

**Comment by morozov** [comment]
This will be fixed in 4.0.0 by https://github.com/doctrine/dbal/pull/4644.
