### ISSUE TITLE
ResultCacheStatement::fetchAllAssociative does not store results in cache

### ISSUE THREAD

**Issue by dFayet** [doctrine/dbal#4406]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 2.12.0

#### Summary

Using `fetchAllAssociative` to fetch query results on a Symfony project using `doctrine/dbal` (no ORM) with a Redis cache seems to not use the cache. But `fetchAll` does.  

#### Current behaviour

The query is executed at each run.

#### How to reproduce

```php
$sql = <<<SQL
    SELECT
        *
    FROM my_table
    WHERE id = :id
SQL;

$connection = ;// instance of Doctrine\DBAL\Connection
$stmt = $connection->executeCacheQuery(
    $sql,
    ['id' => 1],
    ['id' => PDO::PARAM_INT],
    new QueryCacheProfile(
        360,
        'my_key'
    )
);
$results = $stmt->fetchAllAssociative(); // This will always execute a query
```

This problem also shows up when using `fetchAllNumeric`, `fetchAssociative`, and `fetchNumeric`, but not when using `fetchAll`

#### Expected behaviour

The query should be executed at the same occurence with `fetchAllAssociative|fetchAllNumeric|fetchAssociative|fetchNumeric` as with `fetchAll`

I've tried to dig a bit in the code, I saw 2 things:
- `fetchAllAssociative` and `fetchAllNumeric`:
  I am a bit less confident there as it seems to have "nested statement calls" (I do not know how it is called, look for example at lines [256](https://github.com/doctrine/dbal/blob/cad295a6b777b759fe3dc0be0cc2a3d7e87aa8e1/lib/Doctrine/DBAL/Cache/ResultCacheStatement.php#L256) and [258](https://github.com/doctrine/dbal/blob/cad295a6b777b759fe3dc0be0cc2a3d7e87aa8e1/lib/Doctrine/DBAL/Cache/ResultCacheStatement.php#L258]), but they both calls a method [store()](https://github.com/doctrine/dbal/blob/cad295a6b777b759fe3dc0be0cc2a3d7e87aa8e1/lib/Doctrine/DBAL/Cache/ResultCacheStatement.php#L328) that will also not save data in cache.

-  `fetchAssociative` and `fetchNumeric`:
   They both call method `doFetch`, but this methods will not store the result if it differs from `false`
https://github.com/doctrine/dbal/blob/cad295a6b777b759fe3dc0be0cc2a3d7e87aa8e1/lib/Doctrine/DBAL/Cache/ResultCacheStatement.php#L314-L320

**Update**: `fetchAssociative` and `fetchNumeric` are probably not an issue, according to the doc

**Comment by greg0ire** [comment]
@morozov I think this issue might have been introduced with at least this change: https://github.com/doctrine/dbal/pull/4048/files#diff-4e21b732b0eb382f16d2407b468f9d2a0ecba40e654f7972fc816bc9099afeacR313

**Comment by dFayet** [comment]
@greg0ire Maybe, from what I have seen today I've never entered in the `saveToCache` method. 
I'll take a deeper look asap (tomorrow morning).

**Comment by greg0ire** [comment]
Yes, that seems to be the issue, only `store` seems to be called in `fetchAll*`, never `saveToCache`…

**Comment by dFayet** [comment]
As @greg0ire said when doing `fetchAll*` we never enter in `saveToCache` [$this->statement](https://github.com/doctrine/dbal/blob/cad295a6b777b759fe3dc0be0cc2a3d7e87aa8e1/lib/Doctrine/DBAL/Cache/ResultCacheStatement.php#L256) is an instance of `lib/Doctrine/DBAL/Driver/PDOStatement.php` there is no recursivity or something like that, we then directly go to `store()` thats all.

For `fetchAssociative` it runs only 1 time `doFetch()`, `$row` contains the fetched result (is not `false`), so we leave the method without entering `saveToCache`.
