### ISSUE TITLE
Regression:: Connection::executeCacheQuery array_key_exists error when $data is null

### ISSUE THREAD

**Issue by tomdulin** [doctrine/dbal#4427]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.1.2.0

#### Summary

This line should check for null as well as false
https://github.com/doctrine/dbal/blob/5f94000488373d45445fd6fcd495cb9a4bdbe09c/lib/Doctrine/DBAL/Connection.php#L1307
 _-- should be --_
`if ($data && $data !== false) {` <-- fix

#### Current behaviour

This used to check for null, now checks for false.  When `$resultCache->fetch($cacheKey)` returns null, error thrown when checking `array_key_exists($realKey, $data)` (when $data is null);

Warning: array_key_exists() expects parameter 2 to be array, null given in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php on line 1315

#### How to reproduce

—————————————————————— QueryCacheProfile

class Doctrine\DBAL\Cache\QueryCacheProfile#323 (3) {
  private $resultCacheDriver =>
  NULL
  private $lifetime =>
  int(86400)
  private $cacheKey =>
  string(32) "29d5790c21339c114ffe88e8c99997e0"
}

—————————————————————— $this->_config->getResultCacheImpl()
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1294:
class Doctrine\Common\Cache\MemcachedCache#364 (3) {
  private $memcached =>
  class enotescom\Memcached#383 (1) {
    protected $enabled =>
    bool(false)
  }
  private $namespace =>
  string(0) ""
  private $namespaceVersion =>
  NULL
}

—————————————————————— dofetch $id 
/vendor/doctrine/cache/lib/Doctrine/Common/Cache/MemcachedCache.php:54:
string(41) "sadf[29d5790c21339c114ffe88e8c99997e0][1]"
—————————————————————— dofetch $this->memcached->get($id)
/vendor/doctrine/cache/lib/Doctrine/Common/Cache/MemcachedCache.php:57:
NULL
—————————————————————— resultcache
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1311:
class Doctrine\Common\Cache\MemcachedCache#364 (3) {
  private $memcached =>
  class enotescom\Memcached#383 (1) {
    protected $enabled =>
    bool(false)
  }
  private $namespace =>
  string(0) ""
  private $namespaceVersion =>
  int(1)
}
—————————————————————— Data
/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:1315:
NULL

#### Expected behaviour

should not throw exception when in this state.

**Comment by morozov** [comment]
@tomdulin could you be more specific on how to reproduce the issue? I don't understand what's going on from the dumps above.
