### ISSUE TITLE
Target PHP 7.4 for 4.0.x

### ISSUE THREAD

**Issue by BenMorel** [doctrine/dbal#4434]
I can see that `3.0.x` currently targets PHP 7.3+; could we make 7.4 the minimum requirement?

Reasons:

- PHP 7.3's active support [ends in 20 days](https://www.php.net/supported-versions.php) (6 December)
- Targeting 7.4 would allow us to:
  - harden the codebase a bit using typed properties
  - make it a bit cleaner by using short closures in a few places.

**Comment by morozov** [comment]
Some people express concerns about libraries artificially bumping PHP version constraints. I don't fully share this concern but we may want that into account. Another consideration is that typed properties make more sense with strictly typed scalar arguments which are only implemented in `4.0-dev`, so I'd consider implementing them there first.

**Comment by BenMorel** [comment]
> I don't fully share this concern but we may want to take that into account.

I wouldn't pay too much attention to these concerns TBH, major versions are here to break things, and even formerly conservative libraries like PHPUnit now closely follow PHP's release schedule, quickly stopping supporting PHP versions that are past EOL.

> (...) with strictly typed scalar arguments which are only implemented in 4.0-dev, so I'd consider implementing typed properties there first.

Do you want me to backport these to 3.0.x then? Won't this be a pain to merge back into 4.0-dev later?

Also, could you please tell me what else is currently in 4.0, that's not in 3.0? I fail to understand the difference between the two, at the moment.

**Comment by morozov** [comment]
> Do you want me to backport these to 3.0.x then?

No.

> Also, could you please tell me what else is currently in 4.0, that's not in 3.0?

You can look at the [4.0.0](https://github.com/doctrine/dbal/milestone/3) milestone and compare https://github.com/doctrine/dbal/compare/3.0.x...master. If I were to put together a summary, I would use those as a source.
