### ISSUE TITLE
Non resolvable Exception reference in multiple driver exceptions classes

### ISSUE THREAD

**Issue by nreynis** [doctrine/dbal#4443]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.12

#### Summary

Those links to `Exception` are ambiguous and cannot be resolved:  

- [Doctrine\DBAL\Driver\Mysqli\MysqliException](https://github.com/doctrine/dbal/blob/2.12.1/lib/Doctrine/DBAL/Driver/Mysqli/MysqliException.php#L8)
- [Doctrine\DBAL\Driver\IBMDB2\DB2Exception](https://github.com/doctrine/dbal/blob/2.12.1/lib/Doctrine/DBAL/Driver/IBMDB2/DB2Exception.php#L8)
- [Doctrine\DBAL\Driver\OCI8\OCI8Exception](https://github.com/doctrine/dbal/blob/2.12.1/lib/Doctrine/DBAL/Driver/OCI8/OCI8Exception.php#L8)
- [Doctrine\DBAL\Driver\SQLSrv\SQLSrvException](https://github.com/doctrine/dbal/blob/2.12.1/lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvException.php#L9)

#### Current behaviour

I don't know what implementation of `Exception` I need to use

#### Expected behaviour

I should be able to tell what `Exception` I must use

**Comment by greg0ire** [comment]
I think you are supposed to use `Driver\Exception`: https://github.com/doctrine/dbal/commit/a7374a24d7d51500e2567499f53509666ee36247

Can you please make a PR that fixes it by adding the missing use statements?
