### ISSUE TITLE
Deprecated Doctrine\DBAL\Driver\PDOException suggests to use a class marked as internal

### ISSUE THREAD

**Issue by nreynis** [doctrine/dbal#4444]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.12

#### Summary

This class:  
https://github.com/doctrine/dbal/blob/79cba0bc0e653005fc9ab5a23624828a803f41fb/lib/Doctrine/DBAL/Driver/PDOException.php#L8-L12
Suggests to use this replacement:  https://github.com/doctrine/dbal/blob/79cba0bc0e653005fc9ab5a23624828a803f41fb/lib/Doctrine/DBAL/Driver/PDO/Exception.php#L10-L14

#### Current behaviour

The replacement is marked as internal.

#### Expected behaviour

The replacement should not be internal

**Comment by morozov** [comment]
Driver-level exceptions are meant only for internal usage. Consumers of the DBAL API should only catch the wrapper-level exceptions.

**Comment by nreynis** [comment]
Then PdoException should also be flagged as internal.

It's not so much about how third party use the code, but more about codebase consistency.

**Comment by morozov** [comment]
It's already `@deprecaed` in favor of  `Doctrine\DBAL\Driver\PDO\Exception` which is `@internal`.

**Comment by beberlei** [comment]
In what kind of scenario are you getting a `PDOException` as a user anyways? This should not happen in many places in 2.x

**Comment by nreynis** [comment]
Essentially I wrap the PDOConnection as a workaround for https://github.com/doctrine/dbal/issues/4441  
This may be unecessary, since you say it should be catched and rethrown.  
  
Let's close that.

**Comment by beberlei** [comment]
Its an honest question, if you find where you get this hint please let us know

**Comment by Synchro** [comment]
I'm seeing this in Laravel 8.29 when I get a duplicate key clash:
```
[2021-03-02 07:44:54] testing.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-3' for key ... at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678)
[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-3' for key ... at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)
[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-3' for key ... at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115)
```

So to trap that I want to catch the error:

```php
        try {
            $thing = Thing::create(
                ...;
        } catch (PDOException $e) {
```
My IDE (PHPStorm) marks that `PDOException` as deprecated. If I switch it to using the higher-level `PDO\Exception`, it also marks that as bad because that class is marked as `@internal`, exactly as reported.

It seems that I perhaps shouldn't be catching these particular exceptions at all – doing so doesn't actually seem to work in Laravel; catching `\Illuminate\Database\QueryException` however does, even though that Exception class doesn't appear in the uncaught stack.

**Comment by nreynis** [comment]
@beberlei 
> In what kind of scenario are you getting a PDOException as a user anyways? This should not happen in many places in 2.x

When you [use a fetch method](https://github.com/doctrine/dbal/issues/4441#issuecomment-852152447)

**Comment by morozov** [comment]
The only driver-level exception that is meant to be caught is `Doctrine\DBAL\Driver\Exception` but it's meant to be caught by the wrapper and handled (wrapped into a `Doctrine\DBAL\Exception` which is meant to be caught by the user code). If it doesn't happen, then it's a bug. Note that there are quite some bugs like this in `2.x` and fewer of them in `3.x`.
