### ISSUE TITLE
Delete SQL statement is wrong when using alias MySQL

### ISSUE THREAD

**Issue by ustmaestro** [doctrine/dbal#4448]
### Bug Report

Invalid forming delete query when I use alias for table. Query produces a syntax error.

My `MySQL` version is `5.7.25`.

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.12.x

#### Summary

I'm using the delete like described in example `https://github.com/doctrine/dbal/blob/79cba0bc0e653005fc9ab5a23624828a803f41fb/lib/Doctrine/DBAL/Query/QueryBuilder.php#L545`

    $qb = $conn->createQueryBuilder()
        ->delete('users_groups', 'ug')
        ->where('ug.groupId = :groupId')
        ->setParameter(':groupId', 1);
   
This creates a query like this: `DELETE FROM users_groups ug WHERE ug.groupId = 1` that produces an MySQL error

`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ug WHERE ug.groupId = 1' at line 1`

I do not know if this is a specific MySQL issue or for some MySQL versions, my current MySQL version is 5.7.25.

I've searched MySQL error related answers and i found this https://stackoverflow.com/a/26935749/2624626

    delete <alias> from <table> <alias> where <alias>.<field>...

For me `DELETE ug FROM users_groups ug WHERE ug.groupId = 1` worked as expected and without errors.

#### Current behaviour

    DELETE FROM <table_name> <alias> WHERE <alias>.<field> ...

#### How to reproduce

`CREATE TABLE test_delete (userId int, groupId int);`

`INSERT INTO test_delete (userId, groupId) VALUES (1,1), (1,2), (1,3), (2,1), (2,3);`

`DELETE FROM test_delete td WHERE td.groupId = 1;`

https://www.db-fiddle.com/f/uPFmoWKGyQngD97AVMBV8Y/1

`DELETE td FROM test_delete td WHERE td.groupId = 1;`

    $qb = $conn->createQueryBuilder()
        ->delete('test_delete', 'td')
        ->where('td.groupId = :groupId')
        ->setParameter(':groupId', 1);

   $qb->execute();   

#### Expected behaviour

    DELETE <alias> FROM <table_name> <alias> WHERE <alias>.<field> ...

**Comment by ustmaestro** [comment]
https://www.db-fiddle.com/f/uPFmoWKGyQngD97AVMBV8Y/2

**Comment by simonberger** [comment]
It looks like the platforms have the following syntax:

In front of the table name:
- mysql
- mssql

Behind the table name:
- PostgreSql

No alias / found no info:
- others

The query builder seems not intended to know or handle the platforms differently. With my limited knowledge of this package I don't see a way to fix it satisfactorily.
