### ISSUE TITLE
ConnectionException should extend RuntimeException

### ISSUE THREAD

**Issue by noahboegli** [doctrine/dbal#4454]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | I think not

#### Summary

I have used a bit of less automatic operations with Doctrine to simplify data import, considering the following code sample (where `$entityManager` refers to an instance of the Entity Manager):

```php
$entityManager->getConnection()->beginTransaction();

// Some code with batch processing goes in here, that code can call $entityManager->getConnection()->setRollbackOnly()

if (!$entityManager->getConnection()->isRollbackOnly()) {
    $entityManager->getConnection()->commit();
} else {
    $entityManager->getConnection()->rollBack();
}
```

Up until there, everything is fine. However, the IDE (correctly) indicates for the following methods calls

- commit()
- rollBack()
- setRollbackOnly()
- isRollbackOnly()

 that a `ConnectionException` is not being wrapped in a try/catch. Looking at the documentation for these 4 methods, they all say something in the lines of
> ConnectionException thrown if there was no active transaction

Since I started the transaction myself, there is no other reason than a runtime error for no transaction being active.

While this does not really matter in the end, it is a bit heavy to deal with in IDEs and code coverage testing because there is technically an exception that does not extend RuntimeException not being handled properly.

Looking at other usages of this particular exception, I don't see any sign that it could not extend RuntimeException (from a usage standpoint).

However from a technical standpoint, the fact that it does not directly extends the base Exception type might complicate the thing.

I am willing to provide some time and try to make a PR if this is a reasonable request.

**Comment by beberlei** [comment]
Does PHPStorm not show this error when you extend from `RuntimeException`? that is new knowledge to me and intriguing.

**Comment by noahboegli** [comment]
Yep, you can configure [unchecked exception](https://blog.jetbrains.com/phpstorm/2018/04/configurable-unchecked-exceptions/) as they call it, by default `RuntimeException`, `LogicException` and  `Error` are not checked for . 

Although I could go for the easy solution to not check for `ConnectionException`, I feel like it would be kind of "abusing" this feature. It makes sense to not check for RuntimeException as you can't plan for every case that will go wrong based on X parameters. But it would not make sense to not check for something that you can actually plan for
