### ISSUE TITLE
pdo_sqlsrv doctrine is incorrectly changing a datetime column to datetime2

### ISSUE THREAD

**Issue by senyahnoj** [doctrine/dbal#4460]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | ?
| Version     | 2.12.1

#### Summary

I am using the laravel framework for running database migrations https://laravel.com/docs/6.x/migrations#modifying-columns

Under the hood, laravel uses doctrine/dbal to modify columns but not to create them.

The bug is that I am creating a non-nullable **datetime** column but when I modify it to be nullable the data type changes to become **datetime2**. It is the modification to this column which I believe is performed by doctrine/dbal.

I originally raised this bug with the laravel/framework (see https://github.com/laravel/framework/issues/35566) but, as you can see from the ticket, they advised me that it was an issue with dbal and to raise it with yourselves instead.

#### Current behaviour

Using 2 laravel database migration scripts (as per https://laravel.com/docs/6.x/migrations). First one creates the datetime column (not null). Second one modifies it to be nullable.

#### How to reproduce

* Laravel Version: 6.0.4 LTS
* PHP Version: 7.4.12
* Database Driver & Version: pdo_sqlsrv 5.8.1

I'm afraid I only have the laravel framework methods for doing this as I am not using dbal directly.

My first migration has the following method

```
/**
 * Migration one create the column
 *
 * @return void
 */
public function up(): void
{
    Schema::table('my_table', function (Blueprint $table) {
        $table->dateTime('my_field');
        // Result is a newly created datetime column
    });
}
```

My subsequent migration attempts to make the column nullable as below

```
/**
 * Migration two modify the column
 *
 * @return void
 */
public function up(): void
{
    Schema::table('my_table', function (Blueprint $table) {
        $table->dateTime('my_field')->nullable()->change();
        // Result is a nullable column but it's changed to a datetime2!
    });
}
```

#### Expected behaviour

I would expect the datatype to remain **datetime** - not change to **datetime2**

**Comment by morozov** [comment]
@senyahnoj please reproduce the issue using only the DBAL APIs.
