### ISSUE TITLE
Remove PHPStorm stubs from dependencies

### ISSUE THREAD

**Issue by DaanBiesterbos** [doctrine/dbal#4468]
### Feature Request

**Please consider removing the (dev) dependency jetbrains/phpstorm-stubs.** 

IntelliejIDEA  and PHPStorm are producing a lot of duplicate class warnings. I don't see any functional benefits of having (outdated!) stubs in my vendor folder. I would say that this is the responsibility of my IDE. I can switch back and forth PHP version and get accurate information in any project, all the time.
Sure, I can mark the directories as excluded to get rid of the warnings  but still.... 

I don't understand why this dependency is here. Assuming most devs use a decent IDE there is no point in installing stubs right?  And even if we'd all be using notepad++ it still would not be Doctrine's responsbility. The current version is v2020.2. . What if another bundle decides to require the stubs from ^2020? There would be a version conflict. And for what? For interfaces of standard PHP classes I neither use or need.

1.  The stubs are in conflict with IDE
2.  Stubs are subject to change, other tools are more suitable to provide this functionality.
3.  There may be version conflicts for some people (the dependency is already outdated)
4.  No functional benefits

I would purpose to suggest this package instead. I don't think it is a bad thing to expect developers to take care of this themselves. If someone needs stubs they can easily install the dependency themselves I would say.

**Comment by morozov** [comment]
> IntelliejIDEA and PHPStorm are producing a lot of duplicate class warnings.

What is the setup? Do you develop the DBAL or you use it as a dependency? In the latter case, Composer shouldn't install any stubs since they are a development dependency.
