### ISSUE TITLE
Replacement for PingableConnection

### ISSUE THREAD

**Issue by gjuric** [doctrine/dbal#4469]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.0.0

#### Summary

Is there a recommended solution on how to replace the functionality that was provided by a PingableConnection?

#### Previous behaviour

PingableConnection existed and allowed a connection to be pinged/checked. This was especially useful when working with long running processes.

#### Current behavior

PingableConnection has been deprecated and then removed.

Since this has been removed I believe issues #3118 and #2769 can be closed.

**Comment by acataluddi** [comment]
Hi @gjuric,

I'm trying to figure out why [`Doctrine\DBAL\Connection#ping()`](https://github.com/doctrine/dbal/blob/b551fcb26a81e230085c0dca88174573b6c36609/lib/Doctrine/DBAL/Connection.php#L1575) is now deprecated but I cannot find any explanation neither in the PhpDoc comment nor in the GitHub issues. Could you help me, please?

Thanks,  
Adriano C.

**Comment by gjuric** [comment]
HI @acataluddi,

this is what I am trying to figure out as well, hence this issue.

**Comment by lcobucci** [comment]
Folks, did you read the [upgrade guide](https://github.com/doctrine/dbal/blob/2.12.x/UPGRADE.md#the-pingableconnection-interface-is-deprecated)?

**Comment by gjuric** [comment]
To be honest, I read the title that it's being deprecated but somehow missed the sentence below it:

> The wrapper connection will automatically handle the lost connection if the driver supports reporting it.

Now that I read it, I am not sure what that means. Handling the lost connection is I suppose reconnecting if the driver is able to report that the connection is lost?

**Comment by lcobucci** [comment]
> To be honest, I read the title that it's being deprecated but somehow missed the sentence below it:
> 
> > The wrapper connection will automatically handle the lost connection if the driver supports reporting it.
> 
> Now that I read it, I am not sure what that means. Handling the lost connection is I suppose reconnecting if the driver is able to report that the connection is lost?

@gjuric you can see how that's handled in https://github.com/doctrine/dbal/pull/4119 but TL;DR: DBAL will mark the connection as closed when the driver is able to identify a lost connection. A `LostConnection` exception will still be throw so that users can handle that and perform the necessary calls to recover the operation.

**Comment by gjuric** [comment]
Thank you!

I don't really think removal of this feature was the best idea since it was an elegant way to check a connection in long running processes, but I see that there are other factors at play here (other platforms).

Since `getDummySelectSQL()` is still there, ping() can be easily reimplemented if needed.
