### ISSUE TITLE
Enabling foreign key constraints in sqlite database breaks `doctrine:schema:drop`

### ISSUE THREAD

**Issue by elfin-sbreuers** [doctrine/dbal#4479]
Hello,

apparently `doctrine:schema:drop` fails in sqlite database if foreign key constraints are enabled. In sqlite databases they are disabled by default. We enable it via a subscriber on the `DBAL\Events::postConnect` events with 

```
$args->getConnection()->exec('PRAGMA foreign_keys = ON;');
```
For databases that have foreign key constraints between tables this does not allow to execute a

```
DROP TABLE foo;
```
If foo is linked with a foreign key constraint to another table `bar`.

Unfortunately, the command 

```
./bin/console doctrine:schema:drop --env test --force
```

returns a success message, although it did not delete anything from the database and should have encountered errors.

```
 Dropping database schema...
                                                                                                                        
 [OK] Database schema dropped successfully!                                                                             
                                                                                                                     
```
For once it would be nice if the return statement states that the drops for the tables could not be executed, which they couldn't.

It would be also nice the command could execute despite foreign key constraints. Either bei disabling the foreign key constraints or by just deleting and recreating an empty file.

I will delete the file for now.

Thanks in advance.

**Comment by ostrolucky** [comment]
Doesn't look like doctrine-bundle related, moving to dbal.

**Comment by morozov** [comment]
@elfin-sbreuers please provide steps to reproduce the issue.
