### ISSUE TITLE
Sequence is in the migrations diff although it should be filtered

### ISSUE THREAD

**Issue by einenlum** [doctrine/dbal#4486]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.11.3

#### Summary

I suspect the schema_filter does not filter out correctly sequences.

#### Current behaviour

I have a custom bundle installed containing an Entity.

```php
<?php

namespace SomeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="account_list",indexes={@ORM\Index(name="search_account", columns={"email", "customer_id", "group_name", "contract_id", "pod"})})
 */
class Account
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    // …
}
```

Now if I generate a migration with DoctrineMigrationsBundle 3.0.2 (with doctrine:migrations:diff) it wants to create the table for this entity:

```php
$this->addSql('CREATE SEQUENCE account_list_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
$this->addSql('CREATE TABLE account_list (id INT NOT NULL, email VARCHAR(255) NOT NULL, customer_id VARCHAR(255) NOT NULL, contract_id VARCHAR(255) DEFAULT NULL, pod VARCHAR(255) DEFAULT NULL, group_name VARCHAR(255) DEFAULT NULL, active BOOLEAN DEFAULT \'false\', orderby INT DEFAULT NULL, PRIMARY KEY(id))');
```

But I don't want this.
So I added a schema_filter option in dbal:

```yaml
doctrine:
    dbal:
        # …
        schema_filter: ~^(?!account_list)~
```

The table creation disappeared from the migration, but I still have the sequence in my diff (?!) :

```php
        $this->addSql('CREATE SEQUENCE account_list_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
```

Same result if I use `schema_filter: ~^(?!account_list|account_list_id_seq)~`

It's said in the doctrine migrations bundle documentation that [sequences are also filtered](https://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html#manual-tables).

I thought it could be because the sequence name is autogenerated and not explicit, so:

```php
<?php

namespace SomeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="account_list",indexes={@ORM\Index(name="search_account", columns={"email", "customer_id", "group_name", "contract_id", "pod"})})
 */
class Account
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @ORM\SequenceGenerator(sequenceName="account_list_id_seq")
     */
    private $id;
    // …
}
```
But same story.

I tried to change the name of the sequence to be sure:
`     * @ORM\SequenceGenerator(sequenceName="foobar")`

And this is indeed the one added: `$this->addSql('CREATE SEQUENCE foobar INCREMENT BY 1 MINVALUE 1 START 1');`.

Adding `schema_filter: ~^(?!account_list|foobar)~` does not change this result.

#### How to reproduce

Not sure yet.
Versions used: Postgres: 12.3, DoctrineMigrationsBundle: 3.0.2

#### Expected behaviour

The sequence creation should not appear in the diff generated by Doctrine.

#### Related issues

I found [this issue](https://github.com/doctrine/dbal/issues/3986) but it seems different to me, cause the sequence was filtered correctly and the user thought it was only filtering tables.

**Comment by morozov** [comment]
@Einenlum since the issue is reported in the DBAL repository, please reproduce it using only the DBAL.

**Comment by BigC** [comment]
i have the same issue. any update?

**Comment by morozov** [comment]
@BigC all updates are above your comment.
