### ISSUE TITLE
Comparison Problem with Default 'NULL' in MariaDB

### ISSUE THREAD

**Issue by tmachyshyn** [doctrine/dbal#4496]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.0.0
| MariaDB    | 10.4.17

#### Summary

The same issue for DBAL v3.0.0 in MariaDB 10.4.17 as faced before: https://github.com/doctrine/dbal/issues/2817

The default values are indicated as changed while schema comparison:
|    Normal value        |   Value in MariaDB
|------------ | ------
`null` | `'NULL'` (string)
| `1` | `'1'`

**Comment by tmachyshyn** [comment]
Found the problem. It was related to my customizations. I have created a custom `MariaDb1027Platform` class and this condition (https://github.com/doctrine/dbal/blob/3.0.x/src/Schema/MySQLSchemaManager.php#L200) is not working for me. 
Why just not remove the `final` declaration in the class  https://github.com/doctrine/dbal/blob/3.0.x/src/Platforms/MariaDb1027Platform.php#L12. It will help to extend the `MariaDb1027Platform` class without having to create an own `Driver` class?
What is the reason of creating the `final` class? All other Platforms can be extended.

**Comment by morozov** [comment]
> Found the problem. It was related to my customizations.

Is the issue in subject solved?

> Why just not remove the `final` declaration in the class [...]

Keeping classes `final` makes it possible to make changes to the non-public class APIs without them being breaking changes.

> It will help to extend the `MariaDb1027Platform` class without having to create an own `Driver` class?

Why is creating a custom driver a problem?

**Comment by tmachyshyn** [comment]
Sorry for the late answer.

1. Yes, the issue is solved. 
2. This is quite important if you need to extend class functionality especially for `MariaDb1027Platform`. The main problem is checking the instance:
```
if ($this->_platform instanceof MariaDb1027Platform) {
``` 
So, if you want to extend functionality of `MariaDb1027Platform` you have to create own custom class instead of extending existing. And thus, this condition will not work at all, because the instance will be different.

3. No problem to create a custom driver at all. However, it requires to create an additional driver, additional MySQLSchemaManager and extend a few methods.

**Comment by morozov** [comment]
Why do you need to extend the functionality of a platform except for that being a temporary solution? If this platform is supported by the DBAL, then if it's missing some standard functionality, it should be implemented in the DBAL, not in your project. We accept pull requests! If it's not a standard functionality, it could be implemented anywhere else, not in the platform class.

**Comment by tmachyshyn** [comment]
We are using the DBAL for an open-source CRM system named EspoCRM. We had to extend the functionality for a few reasons:
- no one data should be removed from database. For example if some column is deleted or renamed from metadata, we do not need to delete this column from database.
- fix this bug, https://github.com/doctrine/dbal/issues/4459.

**Comment by morozov** [comment]
> no one data should be removed from database

This is a reasonable requirement from the business logic PoV but it doesn't really belong to a platform. I assume EspoCRM only supports MariaDB. What it if supported other platforms? At a glance, the Comparator might be the right extension point (not sure if it exists at the moment).

> fix this bug, #4459 

Do you want to contribute the fix? Once it's released, you'll have one customization fewer to maintain.

**Comment by tmachyshyn** [comment]
1. It's implemented via Comparator and Platform. We had to use the Platform to solve issues with the autoincrement column. Actually, there are a few issues:
- https://github.com/doctrine/dbal/issues/4459
- handle renaming autoincrement column to avoid column deletion.
- make utf8mb4 as default charset
- make the MEDIUMTEXT as default type for text columns

All extended code is here: https://github.com/espocrm/espocrm/tree/master/application/Espo/Core/Utils/Database/DBAL. If you have any recommendations, please let me know.

2. I do not think, that this code can be contributed. But you are welcome to get some part of the code, see `Espo: Unable to create autoindex column in existing table fix` mark.

**Comment by morozov** [comment]
@tmachyshyn thanks for the details. I'll keep them in mind.

I'm going to close this issue since the primary problem is resolved.
