### ISSUE TITLE
Signature of wrapper Connection constructor is not enforced

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#4511]
Psalm on level 2:

```
ERROR: UnsafeInstantiation - lib/Doctrine/DBAL/DriverManager.php:236:16 - Cannot safely instantiate class Doctrine\DBAL\Connection with "new $class_name" as its constructor might change in child classes (see https://psalm.dev/229)
        return new $wrapperClass($params, $driver, $config, $eventManager);
```

**Comment by greg0ire** [comment]
A solution might be to have a static method for this, that way the LSP is enforced

**Comment by morozov** [comment]
Ideally, I'd like to turn it into a composition similar to what we did with the portability layer. Each wrapper connector class by definition may have different dependencies injected via the constructor and the only way to do that now is to pass them via `$params` which isn't really type-safe.

**Comment by orklah** [comment]
Note that Psalm has an annotation `@psalm-consistent-constructor` that will silent this Issue while making sure every child respects the original signature

**Comment by morozov** [comment]
Thanks, @orklah. That's definitely a good way to document the shortcomings of the existing API.
