### ISSUE TITLE
Why is Type constructor final ?

### ISSUE THREAD

**Issue by yann-eugone** [doctrine/dbal#4528]
|    Q        |   A
|------------ | -----
| Version     | ^2.9.3

### Support Question

Hello !

I was working on [yokai/doctrine-value-object](https://github.com/yokai-php/doctrine-value-object) (a library to simplify usage of value objects)
And one of the challenges I had was to find a way to create new doctrine type without asking the developper to do so.
My idea was simple : add arguments to constructor. But the [Type constructor](https://github.com/doctrine/dbal/blob/3.1.x/src/Types/Type.php#L56) is final...
I ended up with a static constructor on my types, to be able to fill the required properties.

Is there any reason that the `Type::__construct` is final ?
Is the chosen implementation a problem, regarding DBAL philosophy ?

Thank you for your time (working on these amazing libraries and reading this issue).

**Comment by morozov** [comment]
See:
1. https://github.com/doctrine/dbal/blob/70ab8407498d78c5a5fc61d578eb146e30b4b9ce/lib/Doctrine/DBAL/Types/Type.php#L132-L134
2. https://github.com/doctrine/dbal/blob/70ab8407498d78c5a5fc61d578eb146e30b4b9ce/lib/Doctrine/DBAL/Types/Type.php#L243-L245

Types are identified by their class name and cannot have constructor arguments. This is the limitation of the current type system design.

What are you trying to achieve by implementing your own constructor? If it's meant to accept arguments, then it's is against the current design. If it initializes the internal state of the object, then it would be a valid use case (currently not supported).

**Comment by yann-eugone** [comment]
Thank you for the answer @morozov :)

Yeah, I saw these piece of code at the time I decided to work on this lib.

But I don't understand why a type cannot have constructor arguments.
A type is identified by a name, which is an arbitrary string (which is never the Type FQCN, AFAIK).

Thus it is safe to register 2 instances of the same type, with 2 different name. No ?

The Types on this library are converting values to objects, and identified as "storing values like X".
For instance, the [StringValueObjectType](https://github.com/yokai-php/doctrine-value-object/blob/main/src/Doctrine/Types/StringValueObjectType.php) will store the value as string, but will convert value to object of certain type.
This certain type, has to be set on the type, so it can work as expected.

I'm not sure if you consider this as against the design or not ^^

**Comment by morozov** [comment]
> I'm not sure if you consider this as against the design or not

This is not _against_ the design but it's not _supported_ by this design. The current API of mapping type names to classes should change to the mapping of type names to objects in order to support your use case.

> But I don't understand why a type cannot have constructor arguments.

When asking "why", are you asking why it was designed this way or why a type _currently_ cannot have constructor arguments? The answer to the first version is "I don't know". The answer to the second one is obvious. There's no way to pass arguments to the constructor: https://github.com/doctrine/dbal/blob/70ab8407498d78c5a5fc61d578eb146e30b4b9ce/lib/Doctrine/DBAL/Types/Type.php#L243-L245

**Comment by jvasseur** [comment]
@morozov that's not totally true, since `getTypeRegistry` is public you could do `Type::getTypeRegistry()->register($name, new MyClass($arguments));`
