### ISSUE TITLE
Running 'SET ANSI_WARNINGS ON' as query results in AssertionError

### ISSUE THREAD

**Issue by stefantalen** [doctrine/dbal#4531]
### Bug Report

MSSQL server: 12.00.6164
PHP: 7.4.12

|    Q        |   A
|------------ | ------
| BC Break    | no?
| Version     | 2.12.1 

#### Summary

Running `Doctrine/DBAL/Driver/PDOConnection->exec('SET ANSI_WARNINGS ON');` results in a false assertion. When checking the errorInfo the code is `00000` (Success)

```
 try {
            $result = parent::exec($sql);
            var_dump($this->errorInfo());

            assert($result !== false);

            return $result;
        } catch (PDOException $exception) {
            throw Exception::new($exception);
        }
```
Result:
```
vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:53:
array (size=3)
  0 => string '00000' (length=5)
  1 => null
  2 => null
```

#### Current behaviour

An AssertionError is thrown

#### How to reproduce

`Doctrine/DBAL/Driver/PDOConnection->exec('SET ANSI_WARNINGS ON');`

#### Expected behaviour

No AssertionError is thrown

**Comment by morozov** [comment]
I cannot reproduce it locally using PHP 7.4 or PHP 8.0 using [microsoft/mssql-server-linux](https://hub.docker.com/r/microsoft/mssql-server-linux/) (Microsoft SQL Server 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64)).
```php
$conn = DriverManager::getConnection([
    'driver'   => 'pdo_sqlsrv',
    'user'     => 'sa',
    'password' => 'Passw0rd',
    'dbname'   => 'master',
]);
var_dump($conn->exec('SET ANSI_WARNINGS OFF'));
// int(0)
```
Could you check if this behavior is specific to a specific SQL Server version and/or OS? You can also create a pull request with a failing test, it will be run on AppVeyor against SQL Server 2012 Service Pack 1.

**Comment by stefantalen** [comment]
Looks like I failed to mention my driver. I'm using this Symfony bundle: https://github.com/mediamonks/symfony-mssql-bundle/

Running it in `php:7.4-apache-buster` with `pdo_dblib` (and freetds) installed.

**Comment by morozov** [comment]
Why do you have to use DBLIB/FreeTDS if there are `sqlsrv` and `pdo_sqlsrv` [drivers](https://github.com/microsoft/msphpsql) officially supported by Microsoft? Looks like the bundle you're using was last updated 5 years ago when the official driver might not support Linux.

The PHP [documentation](https://www.php.net/manual/en/pdo.exec.php) is as always vague about the return types:
> ```
> public PDO::exec ( string $statement ) : int
> ```
> **Warning** This function may return Boolean false

So far it looks like a driver problem to me.

**Comment by stefantalen** [comment]
You are right, I've installed the `sqlsrv` and  `pdo_sqlsrv` and am not getting the error anymore.

I will be phasing out usage of `pdo_dblib` on our environment :)
