### ISSUE TITLE
Schema\Index::isFullfilledBy() fails to return true for a larger index and both are non-unique

### ISSUE THREAD

**Issue by rgrellmann** [doctrine/dbal#4541]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | all versions

#### Summary

The method Index::isFullfilledBy() should return true if an "$other" index exists which fulfills the needs of "$this" index.
This is the case when:
- either both indexes have exactly the same properties
- or if an "$other" index exists which has the columns of "$this" index in the same order as its first columns, but has additional columns, and "$this" is not unique or primary.

The first 2 lines of Index::isFullfilledBy() contain the following comment:
```
// allow the other index to be equally large only. It being larger is an option
// but it creates a problem with scenarios of the kind PRIMARY KEY(foo,bar) UNIQUE(foo)
```
That is correct, but as I wrote above, this only applies if "$this" index is unique or primary.
I assume beberlei was a little bit lazy in 2010 when he wrote this code ;-)

Why is this important? To save system resources and to gain performance, redundant indexes should be avoided. When doctrine/dbal checks if there is an index on the referencing column in a foreign key constraint (which is not necessary in PostgreSQL and MSSQL and maybe other DBMS, but that is another bug), it should accept any index which has that column in first place, no matter if there are additional columns in the index.

#### Current behaviour

Index::isFullfilledBy() returns false when "this" is a non-unique index with less columns than the "other" index, which shares the same first columns in the same order.

#### How to reproduce

```
CREATE TABLE test (a integer, b integer, PRIMARY KEY (a, b));
```
When Index::isFullfilledBy() is called with "this" being an index only on "a" and "$other" being the primary key, the method should return true.

#### Expected behaviour

Index::isFullfilledBy() returns **true** when "$this" is a non-unique index with less columns than the "$other" index, which shares the same first columns in the same order.

This could be achieved by changing the third line of isFullfilledBy to this:
```if (($this->isUnique() || $this->isPrimary()) && count($other->getColumns()) !== count($this->getColumns())) {```

**Comment by morozov** [comment]
@rgrellmann please feel free to send a PR with the fix and a test.

**Comment by morozov** [comment]
After double-checking the description: 

> ```sql
> CREATE TABLE test (a integer, b integer, PRIMARY KEY (a, b));
> ```
> 
> When Index::isFullfilledBy() is called with "this" being an index only on "a" and "$other" being the primary key, the method should return true.

The expectation is wrong since the primary key is unique, so having a different set of columns, it cannot fulfill another constraint.
