### ISSUE TITLE
"Address not available" - issue while trying to create new connection under stress testing application

### ISSUE THREAD

**Issue by siabuba121** [doctrine/dbal#4545]
I'm stress testing application which priority is to take a log of request per second, typical request does insert row to database.
at some point of test php-fpm cannot establish new connection to database, inside db logs there is nothing wrong. 
But for some reason after some time connections can be again established
The only error which is returned is under php-fpm and it is:
`[2021-03-12T14:15:33.989070+00:00] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occurred in driver: SQLSTATE[HY000] [2002] Address not available" at /opt/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 112 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] Address not available at /opt/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] Address not available at /opt/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] Address not available at /opt/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)"} []`

I'm using dbal version
`         "name": "doctrine/dbal",
            "version": "2.12.1"`
            
Whole app is dockerized but also performed tests with db on host .
Db version is mariadb 10.5.9 
Php-fpm is 7.4.11

**Comment by morozov** [comment]
Why do you think it's a DBAL issue?

**Comment by siabuba121** [comment]
Luck of logged error elsewhere in system, i've checked many scenarios hosting db outside docker checking logs for evry service system logs even docker service logs and i cannot find anything the only place this error is showing is php-fpm docker logs i'm not sure it's issue inside doctrine/dbal but i thought it could be.

**Comment by greg0ire** [comment]
The logs show that this exception actually comes from the driver: `An exception occurred in driver: SQLSTATE[HY000] [2002] Address not available"`. `doctrine/dbal` is just passing the message on
