### ISSUE TITLE
RunSqlCommand uses an unsupported default argument value type

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#4557]
see test commit: https://github.com/doctrine/dbal/commit/2f5d8e15e2ccdecf1c2a41661d6f820b56e57dc0

```
ERROR: InvalidScalarArgument - lib/Doctrine/DBAL/Tools/Console/Command/RunSqlCommand.php:56:105 - Argument 5 of Symfony\Component\Console\Input\InputOption::__construct expects array<array-key, string>|bool|null|string, 7 provided (see https://psalm.dev/012)
            new InputOption('depth', null, InputOption::VALUE_REQUIRED, 'Dumping depth of result set.', 7),
```

**Comment by morozov** [comment]
Seems related to https://github.com/symfony/symfony/pull/40428.

**Comment by morozov** [comment]
@mvorisek please make sure you provide a detailed enough description of the problem.

**Comment by mvorisek** [comment]
> 
> 
> Seems related to [symfony/symfony#40428](https://github.com/symfony/symfony/pull/40428).

If so, this is how it is fixed in another tools like phpstan: https://github.com/contao/core-bundle/commit/d7f7c27369a6fb441851f4580a8ae9d7ba435d3e

**Comment by chalasr** [comment]
I can confirm it is, and the fix made on contao is the right one.

**Comment by chalasr** [comment]
See #4559.
