### ISSUE TITLE
Error: Class "Doctrine\Deprecations\Deprecation" not found

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#4561]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 2.12.0

#### Summary

see failing CI: https://github.com/atk4/data/runs/2225696919?check_suite_focus=true#step:7:136
the latest passing CI: https://github.com/atk4/data/runs/2217433793?check_suite_focus=true#step:7:181

It seems like a dependency issue, there was no code change on the atk4/data repo side. Please note, the CI is failing when `--prefer-lowest` composer option is used.

**Comment by beberlei** [comment]
Please investigate more, you mention 3.0.0 but this also installs 2.12 at some point. Both don't use Deprecation, without more information this makes no sense to me and we probably won't investigate further ourselves.

**Comment by mvorisek** [comment]
You are right, I have updated the CI link and also added a link to the latest passing CI.

**Comment by greg0ire** [comment]
The version mention in the Q/A table is still 2.12.0, which still doesn't mention `Doctrine\Deprecations\Deprecation`, and never will.

**Comment by mvorisek** [comment]
But why the CI shows:
```
Error: Class "Doctrine\Deprecations\Deprecation" not found

/__w/data/data/vendor/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php:221
```

this line: https://github.com/doctrine/dbal/blob/2.12.0/lib/Doctrine/DBAL/DriverManager.php#L221

**Comment by andrew-demb** [comment]
@mvorisek just check the same line in v2.13.0 - https://github.com/doctrine/dbal/blob/2.13.0/lib/Doctrine/DBAL/DriverManager.php#L221

Your CI uses a different version of DBAL than you expect.

**Comment by mvorisek** [comment]
That is correct, I just checked the issue come from patch branch which is rebased lately onto 2.13.0.
