### ISSUE TITLE
 After the DBAL 2.13 update PHPStorm will no longer show those methods as deprecated.

### ISSUE THREAD

**Issue by bcremer** [doctrine/dbal#4570]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.13

#### Summary

After the DBAL 2.13 update PHPStorm will no longer show some methods as deprecated.

#### How to reproduce

* Create a new directory and open as Project in PHPStorm.

* Create repro.php:

```php
<?php

assert($connection instanceof \Doctrine\DBAL\Connection);
$clusterIds =  $connection->executeQuery('SELECT 1')->fetchAll(\PDO::FETCH_COLUMN);
```

* Install doctrine/dbal:2.12.1

```
composer require doctrine/dbal:2.12.1
```

PHPStorm will show `fetchAll` as deprectated

![image](https://user-images.githubusercontent.com/55820/113256099-fe26c400-92c8-11eb-9909-ca338b3014d6.png)

* Update to doctrine/dbal:2.13.0

```
composer require doctrine/dbal:2.13.0
```

PHPStorm will not show `fetchAll` as deprectated

![image](https://user-images.githubusercontent.com/55820/113256192-21517380-92c9-11eb-9ca7-6896b435d7af.png)

#### Expected behaviour

PHPStorm should be able to detect usage of deprecated dbal methods.

I suspect that the `{@inheritDoc}` does not work like intended in this situation
https://github.com/doctrine/dbal/blob/2.13.x/lib/Doctrine/DBAL/ForwardCompatibility/Result.php#L71

**Comment by bcremer** [comment]
A simple fix would be to copy the `@deprecated` annotation line explicitly in https://github.com/doctrine/dbal/blob/2.13.x/lib/Doctrine/DBAL/ForwardCompatibility/Result.php.

```php
    /***
     * {@inheritDoc}
     * @deprecated Use fetchAllNumeric(), fetchAllAssociative() or fetchFirstColumn() instead.
     */
    public function fetchAll($fetchMode = null, $fetchArgument = null, $ctorArgs = null)
    {
        return $this->stmt->fetchAll($fetchMode, $fetchArgument, $ctorArgs);
    }
```

Would you be open for a PR adding those lines?

**Comment by NetworkDevHead** [comment]
Why is Doctrine deprecating fetch, fetchAll, fetchColumn?  This will break millions of lines of code.  The new methods are not any more clear.  WHY? WHY? OH WHY?

**Comment by beberlei** [comment]
Fixed.
