### ISSUE TITLE
SQLLogger does not log actual params used in query

### ISSUE THREAD

**Issue by Wirone** [doctrine/dbal#4602]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.12.1

#### Summary

There are scenarios when params logged by `SQLLogger` are not the same as params actually used in query. It's because query, params and types are logged before preparing statement, in which params are bound (and while binding they can be typecasted which ends with different value than the one which was logged).

Initially reported in [Symfony](https://github.com/symfony/symfony/issues/40566), after discussion in [DoctrineBundle](https://github.com/doctrine/DoctrineBundle/issues/1312), then here after @ostrolucky's request.

#### Current behaviour

When using query builder with something like:
```
$qb->andWhere("foo.value IN (:foo_values)");
$qb->setParameter("foo_values", ['bar'], Connection::PARAM_INT_ARRAY);
```
Doctrine data collector in Symfony profiler shows "runnable query" with `foo.values IN ('bar')` but actually database query contains `foo.values IN (0)` because of `Connection::PARAM_INT_ARRAY` param type. It is very misleading, because looking at the profiler you may think the query is correct (even though the result is not). Profiler displays data from collector, which works on top of `SQLLogger`, so DBAL is the source of query, params and types available later in the profiler.

More context can be found in [`doctrine/DoctrineBundle#1312`](https://github.com/doctrine/DoctrineBundle/issues/1312#issuecomment-809225933) 

#### How to reproduce

Here's reproducer created by @Nyholm → https://github.com/Nyholm/sf-issue-40566

#### Expected behaviour

In the end user should know what params were actually used in query because it would allow to find bugs faster. Personally I've lost lot of time because I've seen in profiler wrong "runnable query", which was returning different set of values than actual query in the app. I had to enable and watch general log in MySQL to see what's actually executed and then was able to find source of the problem.

**Comment by beberlei** [comment]
My opinion is this is a DoctrineBundle issue, because it wants to make sure the query is runnable and does something with the params. Yes it would reduce redudandcy to to it in DBAL, but it also causes overhead of converting when maybe the logger is not interested in this. As such i am :-1: here.

It would also be a BC break. Yes we don't change the signature, but we would change the expected behavior, maybe other loggers are already converting `$params` based on `$types`? This is a bug in DoctrineBundle.

**Comment by ostrolucky** [comment]
@beberlei Have you like me actually digged into code to check what's the problem, or what's your opinion based on? DoctrineBundle doesn't do "something with params", DoctrineBridge does. Also, this issue wasn't about params but query. 

~Also, we don't seem to have working reproducer, I don't see any `foo.values IN (0)` in output of https://github.com/Nyholm/sf-issue-40566~

edit: Reproducer actually works - it shows `WHERE u0_.name IN ('bar');` while actual query is `WHERE u0_.name IN (0);`

**Comment by beberlei** [comment]
@ostrolucky i haven't dug into the code, but I know this is not a DBAL issue, because DBAL is not going to proactively convert the params based on the types. So it must be fixed inside the logger, which I assume from your comment is in doctrine-bridge.

**Comment by ostrolucky** [comment]
No, logger is in DBAL

**Comment by morozov** [comment]
If it's claimed to be a DBAL issue, can anybody reproduce it in the DBAL?

**Comment by ostrolucky** [comment]
I have added failing test at https://github.com/doctrine/dbal/pull/4618

I mentioned this in https://github.com/symfony/symfony/issues/40566#issuecomment-821851299, but actual issue with DBAL is that it binds string to `PDOStatement:bindValue`, then what happens next is undefined, because it depends on php driver extension.

Solution might be to either throw exception here because this was clearly user error (passing in string value for integer binding) and it doesn't need to be passed over to php extension. 
Or DBAL should have built in map of driver behaviour and should know it's going to be casted to 0 for mysql, so it should do it preemptively so at least correct value will end up in logger.

With a stretch, this could also be considered a security issue.

**Comment by morozov** [comment]
At least in the `mysqli` case, it looks like the DBAL loses the binding metadata somewhere. If used directly, the driver seems to work as expected:
```php
$conn = mysqli_connect('127.0.0.1', 'root', '', 'mysql');
$stmt = mysqli_prepare($conn, 'SELECT ?');
$variable = 'FOO';
$stmt->bind_param('i', $variable);
$stmt->execute();
$stmt->bind_result($result);
$stmt->fetch();
var_dump($result);
// int(0)
```

**Comment by morozov** [comment]
It's actually MySQL itself to blame:
```
mysql> select * from ddc1372_foobar where foo = 0;
+----+-----+-----+
| id | foo | bar |
+----+-----+-----+
|  7 | foo | baz |
+----+-----+-----+
1 row in set, 1 warning (0.01 sec)
```

**Comment by greg0ire** [comment]
:thinking: what the hell? :scream: 

`1 warning` : will that be about a loose comparison?

**Comment by ostrolucky** [comment]
Folks, this issue isn't about mysql returning non-empty results, but about difficulty of debugging such problem in DBAL. I have created test case with result assertion only to demonstrate this WTF. Now imagine this happening accidentally - DBAL logger shows values you passed but they aren't the values passed to mysql server. This is very tricky for user and I have posted some proposal to improve it in https://github.com/doctrine/dbal/issues/4602#issuecomment-825931120

**Comment by morozov** [comment]
> `1 warning` : will that be about a loose comparison?

Yes:
```
mysql> show warnings;
+---------+------+-----------------------------------------+
| Level   | Code | Message                                 |
+---------+------+-----------------------------------------+
| Warning | 1292 | Truncated incorrect DOUBLE value: 'foo' |
+---------+------+-----------------------------------------+
1 row in set (0.00 sec)
```

**Comment by morozov** [comment]
> Now imagine this happening accidentally - DBAL logger shows values you passed but they aren't the values passed to mysql server.

These are the values that are passed to the underlying driver (see https://github.com/doctrine/dbal/issues/4602#issuecomment-825952148). How do you propose to log what the driver sends to the server?

**Comment by ostrolucky** [comment]
I've proposed one idea before - we know how mysql is going to cast it, so dbal can cast it itself before passing it to driver, result would be same - except correct values would be logged. Or throw exception, it doesn't make sense to bind non-numeric string as integer type.

**Comment by morozov** [comment]
Definitely not the logger's (nor the DBAL's in general) responsibility. I'd try digging into the underlying DBs configuration and see if it's possible to disable such insane behavior in the first place. Alternatively, enable query logging on the server side, that would be the real source of truth.

**Comment by morozov** [comment]
A more adequate solution would be to enforce parameter types _during_ binding. E.g.:
```php
// before
$stmt->bindValue(1, 'foo', ParameterType::INTEGER);

// after
function bindInteger($position, int $value);

$stmt->bindInteger(1, 'foo'); // would cause a type error
```
This would also solve a ton of other API-related issues.

**Comment by ostrolucky** [comment]
Yeah that's second solution. But new API wouldn't help here when passing an array of types and values.

**Comment by morozov** [comment]
Why not?
```php
function bindIntegerArray($position, int ...$value);
```

**Comment by ostrolucky** [comment]
I'm talking about cases where you bind multiple placeholders in one call. ::bindSomething always binds only one parameter
```php
return $connection->fetchAllAssociative($query, $_POST['you_dont_know_values_inside'], $_POST['you_dont_know_types_inside']);
```

**Comment by morozov** [comment]
> `$_POST['you_dont_know_types_inside']`

Really? Is it the user input that should define the binding type? The types should be defined by the code. In this case, it will get passed to `bindIntegerArray()` internally and fail.

**Comment by ostrolucky** [comment]
I guess I'm not explaining the problem clearly, but at the same time I don't quite get why you don't see the problem. So let's see concrete case. How would you replace this line in your test case so it works with your new proposed API? https://github.com/doctrine/dbal/blob/cfd53c97231fab078bc52c5814660e6ca4366c81/tests/Functional/NamedParametersTest.php#L237? Input can be
 ```php
[
    'bar' => Connection::PARAM_INT_ARRAY,
    'foo' => ParameterType::INTEGER,
]
```
as well as
```php
[
    'baz' => Connection::PARAM_INT_ARRAY,
    'quix' => ParameterType::INTEGER,
    'fox' => ParameterType::STRING,
    'dog' => Connection::PARAM_STR_ARRAY,
]
```

Place where fetching is done doesn't know which. It's whatever you define in dataprovider. And it's not a single parameter, it's array of parameters. `bindIntegerArray` binds single parameter only.

**Comment by morozov** [comment]
`fetchAllAssociative()` will internally call the typed methods, so it shouldn't be a problem.
