### ISSUE TITLE
Support for postgres 10 in version v2.5.13

### ISSUE THREAD

**Issue by bakiro** [doctrine/dbal#4627]
Hello!  in the file lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php replace line 292 with 

### Feature Request

$version = floatval($this->_conn->getWrappedConnection()->getServerVersion());
        if ($version >= 10) {
            $data = $this->_conn->fetchAll('SELECT min_value, increment_by FROM pg_sequences WHERE schemaname = \'public\' AND sequencename = ' . $this->_conn->quote($sequenceName));
        } else {
            $data = $this->_conn->fetchAll('SELECT min_value, increment_by FROM ' . $this->_platform->quoteIdentifier($sequenceName));
        }

**Comment by greg0ire** [comment]
@bakiro this is best done with a pull request, please open one so that we can discuss this properly.
