### ISSUE TITLE
utf8mb4_0900_ai_ci should be the default collation for server_version: '8.0'

### ISSUE THREAD

**Issue by fmonts** [doctrine/dbal#4631]
The default collation for MySQL is `utf8mb4_0900_ai_ci` since MySQL 8.0.1.

Doctrine is still using the older `utf8mb4_unicode_ci` to create new tables, when the server_version settings is set to 8.0

### Feature Request

Update the default collate to the newest version, to guarantee the best out-of-the-box configuration.

**Comment by morozov** [comment]
I don't think the DBAL should be responsible for setting any platform- or even version-specific defaults. We should remove them instead which might be a breaking change.
