### ISSUE TITLE
Possible memory leak in postgres connection

### ISSUE THREAD

**Issue by flaushi** [doctrine/dbal#4636]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.12.0

#### Summary

I found a memleak in ORM https://github.com/doctrine/orm/issues/7649, but this leak **only happens with postgres** so I wanted to forward this problem to the  DBAL project.

I guess https://github.com/doctrine/orm/issues/7748 is the same problem.

#### Current behaviour
When issuing `$query->getSingleScalarResult()` many times in one session, I am leaking memory.
If I use `$query->getResult()`, the leak does not occur.

#### How to reproduce
See the test case https://github.com/doctrine/orm/issues/7649

#### Expected behaviour

The leak should not occur if I use `getSingleScalarResult`

**Comment by morozov** [comment]
@flaushi diagnosing this issue will require a reproducer using only the DBAL API.

**Comment by flaushi** [comment]
I was expecting that.

To realize that I will have to really step into ORM's internals to find the crucial code lines. Will take some time

**Comment by morozov** [comment]
Closing giving the lack of details.
