### ISSUE TITLE
SQLServer platform quoteIdentifier wrong escaping

### ISSUE THREAD

**Issue by zajca** [doctrine/dbal#4643]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | all

#### Summary

It looks like that escaping identifier for sql platform is broken since day one.

#### Current behaviour

This is in tests:
https://github.com/doctrine/dbal/blob/6611e6d24560944e0a299cfd619013597833efc2/tests/Platforms/AbstractSQLServerPlatformTestCase.php#L576
But if I try for example create table
```SQL
CREATE TABLE [test_escaping].[fo][o] ([col1] INT);
-- Failed to execute query. Error: Parse error at line: 1, column: 34: Incorrect syntax near '[o]'.
```

#### Expected behaviour

Expected output should be `[fo]]o]`

```SQL
CREATE TABLE [test_escaping].[fo]]o] ([col1] INT);
-- Query succeeded: Affected rows: 0
```

So the function should be:
```PHP
    public function quoteSingleIdentifier($str)
    {
        return '[' . str_replace(']', ']]', $str) . ']';
    }
```
Output is than same as from
```SQL
SELECT QUOTENAME('fo]o');
-- [fo]]o]
```
https://docs.microsoft.com/en-us/sql/t-sql/functions/quotename-transact-sql?view=sql-server-ver15

**Comment by morozov** [comment]
Closed via #4648.
