### ISSUE TITLE
OCI8Statement not executing toString

### ISSUE THREAD

**Issue by mbolka** [doctrine/dbal#4649]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.12.1

#### Summary

Deleting objects by id, where id is an value object it not working.

#### Current behaviour
If you pass to bindParam method in OCI8Statement class  value that is an value object, method __toString() is not executed prior to calling  oci_bind_by_name on the line 311.
This causes a $variable on the line 314 to be an object and thus empty value when query was performed.
If you compare the execution to the PDOStatement method bindParam on the line 87 implicitly calls toString on $variable.

#### How to reproduce
Perform deletion of an entity that has id value object.

#### Expected behaviour
OCI8Statement performs __toString on any object variable and binds its value to the query.

#### Naive solution
```
--- doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php
+++ doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php
@@ -306,6 +306,10 @@ class OCI8Statement implements IteratorAggregate, StatementInterface, Result
             $variable =& $lob;
         }
 
+        if (is_object($variable)) {
+            $variable = (string) $variable;
+        }
+
         $this->boundValues[$param] =& $variable;
 
         return oci_bind_by_name(

```

**Comment by morozov** [comment]
What prevents the caller from converting the object to a string? The DBAL shouldn't be in the business of figuring out the implementation details of the client code.

**Comment by morozov** [comment]
The proposed fix would break the reference to the originally passed variable, and in general, implicit type casting at the library level isn't a good idea.

**Comment by fcamp** [comment]
Hi @morozov, I'm in the case of saving some simple fixtures with `doctrine/orm` and i got `oci_bind_by_name(): Invalid variable used for bind`.

The UserSettings entity

```php
class UserSettings {
  
    /**
     * @ORM\ManyToOne(targetEntity="Owner")
     */
    private $owner;
}
```

The owner entity

```php
class Owner  {

    /**
     * @ORM\Id
     */
    private $id;

    public function __toString() {
        return (string)$this->id;
    }
}
```

I'm just saving the fixtures on the db for testing

```php
class AppFixtures extends Fixture {

    public function load(ObjectManager $manager): void {
        $owner = new Owner();
        $manager->persist($owner);

        $pref = new UserSettings();
        $pref
            ->setOwner($owner)
        $manager->persist($pref);

        $manager->flush();
    }

```

Before using oracle, I used postgres and had no problems because the `__toString` method of my `Owner` entity gets called, but with oracle i get `oci_bind_by_name(): Invalid variable used for bind`

Why do you think casting object variables to string when calling `\Doctrine\DBAL\Driver\OCI8\Statement::bindParam` is a bad idea? Or what can be an alternative solution for this?

```php
//just before calling the extention function
$variable = method_exists($variable,'__toString') ? (string)$variable : $variable;

return oci_bind_by_name(
    $this->statement,
    $param,
    $variable,
    $length ?? -1,
    $this->convertParameterType($type)
);

```

**Comment by morozov** [comment]
@fcamp the DBAL doesn't support objects as parameters, it's the job of the ORM to map objects to the values understood by the database. If you believe that this is a bug, please file it in the ORM project.

**Comment by fcamp** [comment]
@morozov As I see, the main difference using postgres(pdo) vs oci8 drivers is that in the oci8 Statement, the `bindValue` method calls the `bindParam` (which takes variable by reference causing the problem), while in the pdo one the native pdo `bindValue` is used, which requires the parameter by value, thus triggering `__toString` entity method.

This is the `\Doctrine\DBAL\Driver\OCI8\Statement`

```php
public function bindValue($param, $value, $type = ParameterType::STRING): bool
{
    return $this->bindParam($param, $value, $type);
}

//variable by reference
public function bindParam($param, &$variable, $type = ParameterType::STRING, $length = null): bool
{
...
```

And this is `\Doctrine\DBAL\Driver\PDO\Statement`

```php
/**
 * {@inheritdoc}
 */
public function bindValue($param, $value, $type = ParameterType::STRING)
{
    $type = $this->convertParamType($type);

    try {
        //calls \PDOStatement::bindValue which doesn't take $value by reference
        return $this->stmt->bindValue($param, $value, $type);
    } catch (PDOException $exception) {
        throw Exception::new($exception);
    }
}
```
