### ISSUE TITLE
IN operator limitation in ORACLE database queries 

### ISSUE THREAD

**Issue by mezcaspider** [doctrine/dbal#4651]
Hello,

Let me take this point back to you:

The ORM engine does not take into account the limitation of the ORACLES databases concerning the use of the IN operator.
Queries are generated with an IN operator containing more than 1000 elements. This generates an error message from the database.

ORA-01795: maximum number of expressions in a list is 1000

This type of request should be generated with for example:
SELECT * FROM TABLE WHERE ID in (el1, el2, el3 ..., el1000) OR ID IN (el1001, el1002, el1003 ... el2000) OR ID in (el2001, el1002, el1003 ... el3000) ...

Or by using combined ORs for all elements

Thank you in advance for your support.

Edouard Monnier

**Comment by morozov** [comment]
I believe Oracle does that for a reason: it might be more efficient to use a join in the case of so many values. Additionally, databases usually have a limit on the number of prepared statement parameters (I believe the default for [Oracle](https://docs.oracle.com/cd/E57185_01/SQRLG/apas02s02.html) is 4096), so even if this limit is bypassed, another one may kick in.

I don't believe this workaround should be implemented at the library level. It can be implemented with much less effort in the userland code.
