### ISSUE TITLE
ResultStatement::fetchAllClass() and fetchClass() missing?

### ISSUE THREAD

**Issue by fmonts** [doctrine/dbal#4670]
Let's say I have a snippet like this:

    $result = $db->executeQuery('SELECT * FROM users WHERE ...;');
    $users = $result->fetchAll(\PDO::FETCH_CLASS, User::class);

fetchAll() is deprecated and "one of the fetch- methods" should be used instead.

But isn't there a way to replicate \PDO::FETCH_CLASS? 

Same for ResultStatement::fetchClass() if I want to retrieve only one record

**Comment by morozov** [comment]
This fetch mode isn't supported starting DBAL 3.0 (see https://github.com/doctrine/dbal/pull/3070), so there's no upgrade path provided.
