### ISSUE TITLE
sqlite doesn't compare dates properly

### ISSUE THREAD

**Issue by bitwombat** [doctrine/dbal#4700]
[sql_datetime_query_bug.zip](https://github.com/doctrine/dbal/files/6759300/sql_datetime_query_bug.zip)
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | ??
| Version     | doctrine/orm 2.9, Ubuntu's sqlite3_7.4.3

#### Summary

When I run a >= query comparing a DateTime, it only works if I set the year to be one less than the actual year.

#### Current behaviour
Here's my test code. Also attached, but short enough to show here.
```php
<?php

require_once "bootstrap.php";

$sub = new Subscription();
$sub->setStart(new DateTime('2021-04-25'));

$entityManager->persist($sub);
$entityManager->flush();

function executeQuery($entityManager, $dql) {
    $query = $entityManager->createQuery($dql);

    echo($query->getSQL() . "\n");

    $results = $query->execute();
    if ($results) {
        echo($results[0]->getStart()->format('c') . "\n");
    } else {
        echo("No records\n");
    }
}

executeQuery($entityManager, "SELECT e FROM Subscription e WHERE e.start > '2021/04/20'");
executeQuery($entityManager, "SELECT e FROM Subscription e WHERE e.start > '2020/04/20'"); // Year before works for some reason


```
#### How to reproduce

Run the attached `showbug.php`.

#### Expected behaviour

Both queries should return the entity, as the entity's "start" date is on after both search dates.
This code works fine in MySQL.

**Comment by greg0ire** [comment]
> `2021/04/20`
 
This date format does not seem valid, does it?

For reference: 
![xkcd about iso 8601](https://imgs.xkcd.com/comics/iso_8601.png)

Also, have you tried reproducing the bug via sqlitemanager ?

**Comment by bitwombat** [comment]
Thanks for the quick response.

The format was my first suspicion. I got it from looking at the DQL that was being produced by another piece of code that works - turns out that code was using MySQL, which happily takes the YYYY/MM/DD format.

Trying the YYYY-MM-DD format in my testcase makes the testcase work, but trying it in my original code, and it doesn't work.  Back to the drawing board maybe... will try to cobble a new testcase.

> Also, have you tried reproducing the bug via sqlitemanager ?

Can reproduce it in `sqlitebrowser`, yep. `SELECT * from Subscription s WHERE s.start >= '2019/01/01'` needed to pick up dates in 2020. `2020-01-01` works as expected.

Shouldn't something have thrown an exception somewhere instead of just mysteriously assuming YYYY+1 (apparently)?

**Comment by greg0ire** [comment]
> Shouldn't something have thrown an exception somewhere instead of just mysteriously assuming YYYY+1 (apparently)?

Maybe, but it's not the responsibility of the DBAL to validate what formats underlying platforms support or don't support. Since you have reproduced the issue without the DBAL, it means this bug (if it really is one) should not be reported here, but to SQLite directly
