### ISSUE TITLE
Is there an API way to get underlying connection (PDO)?

### ISSUE THREAD

**Issue by simPod** [doctrine/dbal#4705]
|    Q        |   A
|------------ | -----
| Version     | 2.x/3.x

### Support Question

I have started my issue here https://github.com/getsentry/sentry-symfony/issues/522. I was using `getWrappedConnection()` in a while loop to get the most lower level connection so I could get to PDO instance.

Now https://github.com/getsentry/sentry-symfony introduced wrapping connection that no longer has a way to access the connection it decorates and therefore prevents me to reach PDO.

Is there a way to access PDO with dbal? I'm using it for pg notify feature but I'd like to keep dbal managing it.

**Comment by morozov** [comment]
> Now https://github.com/getsentry/sentry-symfony introduced wrapping connection that no longer has a way to access the connection it decorates and therefore prevents me to reach PDO.

It doesn't seem to be a DBAL issue in this case. The wrapper-level connection provides access to the driver connection: https://github.com/doctrine/dbal/blob/e6add2943187cdf01599e198a77bb6d3672703ab/src/Connection.php#L1518-L1525

And the PDO driver connection provides access to the underlying PDO connection: https://github.com/doctrine/dbal/blob/60fe440a762109c216db94612334bbae8e51f613/src/Driver/PDO/Connection.php#L147-L150

**Comment by simPod** [comment]
@morozov hmm, guys from sentry sent me here 🤔 . Based on that I thought, the issue is that there's no dbal API, that would tell 3rd party wrapping connections to keep the door open to PDO.

So it's easy to access underlying PDO in dbal connections but it is not guaranteed by any other 3rd party wrapper because that wrapper does not allow you to go to the connection it actually wraps. Or am I missing something? Thank you!

------------

Here it implements `DriverConnectionInterface`

`final class TracingDriverConnection implements DriverConnectionInterface`

https://github.com/getsentry/sentry-symfony/blob/c5caac2ad539963b1e8224e4d2961553c0060821/src/Tracing/Doctrine/DBAL/TracingDriverConnection.php#L19

but there's nothing that would tell them to expose `private $decoratedConnection`

**Comment by morozov** [comment]
> Based on that I thought, the issue is that there's no dbal API, that would tell 3rd party wrapping connections to keep the door open to PDO.

> So it's easy to access underlying PDO in dbal connections but it is not guaranteed by any other 3rd party wrapper because that wrapper does not allow you to go to the connection it actually wraps. Or am I missing something?

No, you're right. Those methods are not enforced by any interfaces and aren't even supported by all drivers.

> but there's nothing that would tell them to expose `private $decoratedConnection`

Only you can tell them to do that or use reflection. The underlying connection is an implementation detail that is different for every implementation. There's no interface possible that would force each implementation to expose its implementation details. For instance, I want to implement a primary/replica wrapper. Which of the 1-2...N connections should it expose via the method defined by the interface?

I remember we had a similar discussion some time ago in https://github.com/doctrine/dbal/issues/3534. Also, there was a similar feature request long ago: https://github.com/doctrine/dbal/issues/987. Just linking for reference.

**Comment by simPod** [comment]
Thank you!
