### ISSUE TITLE
VERSION is out-of-date in 2.13.* release series

### ISSUE THREAD

**Issue by phil-davis** [doctrine/dbal#4711]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.13.2

#### Summary
`lib/Doctrine/DBAL/Version.php` has out-of-date version.

#### Current behaviour
`public const VERSION = '2.12.2-DEV';`

#### How to reproduce

Look at the source code.

#### Expected behaviour
Should have been released as:
`public const VERSION = '2.13.2';`

And maybe in the branch it should now be:
`public const VERSION = '2.13.3-DEV';`

**Comment by greg0ire** [comment]
That class was deprecated in https://github.com/doctrine/dbal/pull/3861

It was not stated, but I think one of the goals was to stop bumping it on every release. Also, since it's removed in 3.x, merging this will mean a conflict when merging up 2.x into 3.x.

**Comment by phil-davis** [comment]
OK - feel free to close this, and PR #4712 if the decision is that the value of VERSION will no longer be incremented.

That will mean that consumers of this in 2.13.* will see changed behavior - the VERSION will not be reliably up-to-date. They will "see" more than just a deprecation annotation. (Whoever the consumers are that care - I don't ;) )

**Comment by greg0ire** [comment]
Let's close then, and let's reopen if a consumer that cares pops up :)

**Comment by morozov** [comment]
FWIW, the version of 2.x releases is increased manually by commits like adce7a954a1c2f14f85e94aed90c8489af204086 which is easy to forget (the process is described in https://github.com/doctrine/dbal/issues/3406).

The fact that this API is deprecated and bumping the release version will produce merge conflicts doesn't prevent us from maintaining the proper version for the next 2.x releases but there's nothing we can do about the already released ones.

**Comment by phil-davis** [comment]
Someone please decide - do I reopen PR #4712 ?

By applying the change there, then even if nothing else happens, the next release will have `VERSION` `2.13.3-DEV`, which will be closer to reality.

**Comment by greg0ire** [comment]
This has been labeled with "Can't fix", so to me, the decision is pretty clear :stuck_out_tongue:
