### ISSUE TITLE
OraclePlatform::getCreateAutoincrementSql forces sequence value in autoincrement column

### ISSUE THREAD

**Issue by mondrake** [doctrine/dbal#4725]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.0

#### Summary

The trigger that OraclePlatform::getCreateAutoincrementSql() adds to the database when an autoincrement column is defined does not take into account values passed in directly in the INSERT statements and always overwrites them with the next value of the sequence. 

#### Current behaviour

Look at the trigger code:

https://github.com/doctrine/dbal/blob/a602f2baf74df3d9b17ea8b29fca5fc33786d68d/src/Platforms/OraclePlatform.php#L532-L536

In the very first statement, `sequence.nextval` always forces the next value sequence to the autoincrement column, no matter if there's a value defined already. Other databases allow forcing a value to the autoincrement column, with this code Oracle behaves differently. Weirdly, the rest of the trigger code seems to deal with the case of a value higher that the sequence value to get it up to match an higher value inserted directly; but that can not run, actually, because the first statement has already forced the sequence.nextval to the column to be inserted.

I think just removing that first statement will do.

#### How to reproduce

Create a table with an autoincrement column, try to INSERT a record with a value = 1000 in that column, select back => the value inserted has a value == 1.

#### Expected behaviour

Create a table with an autoincrement column, try to INSERT a record with a value = 1000 in that column, select back => the value inserted has a value == 1000; next insert operation with no value defined will determine a record with value == 1001.

**Comment by mondrake** [comment]
So, MySql and SQLite behave as per expected behavior.

DB2 and PostgresSQL allow to force an arbitrary value on the autoincrement column on INSERT, but are not updating the sequence, i.e. a further INSERT without passing a value to the autoincrement column will get a value == 2.

Oracle ignores the arbitrary value, and forces the sequence's next value, silently.

MSSQL cannot insert explicit value for identity column.

What a mess.

**Comment by morozov** [comment]
@mondrake a PR is welcome.

**Comment by mondrake** [comment]
@morozov filed PR #4733
