### ISSUE TITLE
Doctrine DBAL picks wrong DateTime format when using multiple EntityManagers

### ISSUE THREAD

**Issue by vkost** [doctrine/dbal#4737]
|    Q        |   A
|------------ | -----
| Version     | 2.12

### Support Question

Hi,

I have an API project with two entity managers, one connecting to MySQL (5.7) and another connecting to MSSQL (2019-CU6). Everything seems to be working fine, but I noticed that datetime values in MySQL lack the time portion (the date is set OK, but the time is always 00:00:00). Checking the logs, I found that doctrine sends the value for the datetime column WITH THE TIME ZONE, and MySQL reports a warning and ignores the time part.
Digging through Doctrine, I found the function getDateTimeFormatString() in AbstractPlatform.php, which defaults to proper format for MySQL. However, it seems like DBAL is picking up the function from SQLServer2012Platform.php, which includes the timezone part (actually defined in SQLServer2008Platform.php but inherited). So it's talking to the right server, but picking the wrong platform class. 
I presume this is a configuration issue, but I can't find the error in my config - everything else is working as it should. I'd appreciate some help, if possible. 

Thanks,
Vic

**Comment by morozov** [comment]
> However, it seems like DBAL is picking up the function from SQLServer2012Platform.php, which includes the timezone part (actually defined in SQLServer2008Platform.php but inherited). So it's talking to the right server, but picking the wrong platform class.

Please provide a way to reproduce this.
