### ISSUE TITLE
Default value not changed for Text Type on MariaDB 10.2 platform

### ISSUE THREAD

**Issue by gregor-tb** [doctrine/dbal#4747]
### Bug Report

Caused by `MysqlPlatform`: https://github.com/doctrine/dbal/blob/96990667d5373ad651e05adb03116f1009cf1ef4/src/Platforms/MySQLPlatform.php#L571-L579

Try to set (new) default value here, but run into the condition with a (long)text field.
Doing it manually works fine, cannot see any missing support?

> ALTER TABLE `mytable` CHANGE `field1` `field1` LONGTEXT CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL DEFAULT '';

Version: mysql  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Second place to check: https://github.com/doctrine/dbal/blob/96990667d5373ad651e05adb03116f1009cf1ef4/src/Platforms/MySQLPlatform.php#L453-L461

#### Expected behaviour

Should migrate default values on MariaDB 10.3 on text fields and not skipping them.

**Comment by morozov** [comment]
~~This should be addressed by the work being done in https://github.com/doctrine/dbal/pull/4659. As long as two types produce different SQL (except for some edge cases like character set and collation matching the table defaults), they should be considered different.~~

Not really. The issue needs to be fixed individually.

**Comment by morozov** [comment]
@gregor-tb do you think you could submit a patch to fix this issue?

**Comment by gregor-tb** [comment]
Sorry, not in the near future. I force to upgrade to PHP8 and switch to DBAL3, then I'm going to come back to this (and some other issues I found recently).

Meanwhile we figured out, that this text default value support was introduced in MariaDB 10.2, so it should be overloaded in `MariaDb1027Platform` I guess.
