### ISSUE TITLE
change column type from string to json not works

### ISSUE THREAD

**Issue by karabash22** [doctrine/dbal#4748]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.1

#### Summary

After update from version 2.* to 3.1.1 laravel migrations that change field type to Json stopped working with QueryException 'Datatype mismatch: 7 ERROR:  column "field" cannot be cast automatically to type json
HINT:  You might need to specify "USING field::json". (SQL: ALTER TABLE table ALTER field TYPE JSON)'

#### Current behaviour

migrations that change field type to Json stopped working with QueryException 'Datatype mismatch: 7 ERROR:  column "field" cannot be cast automatically to type json
HINT:  You might need to specify "USING field::json". (SQL: ALTER TABLE table ALTER field TYPE JSON)'

#### How to reproduce

run migration with changing column type to json

#### Expected behaviour

column type changed successfull

**Comment by morozov** [comment]
Please provide the steps to reproduce the issue.

**Comment by morozov** [comment]
The same issue is reproducible on `2.13.x`:
```php
$table1 = new Table('table');
$table1->addColumn('field', 'string');

$table2 = new Table('table');
$table2->addColumn('field', 'json');

$sm = $connection->getSchemaManager();
$sm->dropAndCreateTable($table1);

$comparator = new Comparator();
$diff = $comparator->diffTable($table1, $table2);
$sm->alterTable($diff);

// SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "field" cannot be cast automatically to type json
// HINT:  You might need to specify "USING field::json"
```

**Comment by morozov** [comment]
Related issue: https://github.com/doctrine/dbal/pull/3615.

**Comment by morozov** [comment]
This doesn't look like something that the DBAL should take care of. If Postgres doesn't provide a safe default for this type of conversion, it probably means that the user should make some choice.

**Comment by morozov** [comment]
Also related to https://github.com/doctrine/dbal/issues/2783.
