### ISSUE TITLE
Class 'Doctrine\DBAL\Driver\PDOPgSql\Driver' not found

### ISSUE THREAD

**Issue by masadi** [doctrine/dbal#4757]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.1.1

#### Summary
![image](https://user-images.githubusercontent.com/5530849/130727575-bbf8665d-fd16-4458-980e-b092b2123b66.png)

**Comment by greg0ire** [comment]
Seems related to 99c1b213fef5b23c5c0a1c2087a16d158a09b5e2 . What version of the DBAL are you using?

**Comment by masadi** [comment]
> 
> 
> Seems related to [99c1b21](https://github.com/doctrine/dbal/commit/99c1b213fef5b23c5c0a1c2087a16d158a09b5e2) . What version of the DBAL are you using?

3.1.1

**Comment by greg0ire** [comment]
Duplicate of #4439
