### ISSUE TITLE
Opposed to adding new types?

### ISSUE THREAD

**Issue by grantholle** [doctrine/dbal#4809]
### Feature Request

I was curious if we were open to adding new type classes, such as one for Postgres' `citext` column type?

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

I wish to add a type class definition for the `citext` column type, but from searching for `citext` in issues, I don't see anyone recommending it or even if it's allowed.

**Comment by morozov** [comment]
It looks like `citext` is a Postgres-specific type. You should be able to add it to your application as a custom type. As a platform-specific type, it doesn't really belong to a database abstraction.

**Comment by grantholle** [comment]
Thanks
