### ISSUE TITLE
Columns are not found with 3.1.2

### ISSUE THREAD

**Issue by eschricker** [doctrine/dbal#4832]
### Bug Report

Columns are not found. They are named in camelCase. 

|    Q        |   A
|------------ | ------
| BC Break    | yes/no
| Version     | 3.1.2

#### Summary

I am using doctrine/dbal in a lumen project. I recently upgraded dbal to 3.1.2 and now my tests with sqlite and mysql fail with the message that columns cannot be found when renamed or their type is changed. 

With version 2.13.3 and 3.1.1 it works. 

#### Current behaviour

-

#### How to reproduce

-

#### Expected behaviour

The columns should be found and renamed or their type should get altered.

**Comment by derrabus** [comment]
Please provide steps to reproduce your problem.

**Comment by eschricker** [comment]
I can create a lumen sample project that causes this error if that is helpful. 

I have compared the code of version 3.1.1 and 3.1.2 and created a pull request that fixes the error. The use of lower case columns in sqlite has been dropped there.

**Comment by derrabus** [comment]
Thanks, the PR should be enough then.
