### ISSUE TITLE
DBALException constructor should be made private

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#4847]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | yes

#### Summary

Exception handling is a critical part of software. With change https://github.com/doctrine/dbal/commit/ad1e48238b38a8ec10a7f461e7426c7f3985b603 present since v2.11, a lot of software started to use `Exception` instead of `DBALException` which is dangerous when this change is made in `catch` phrases which newly misses all `DBALException` instances.

To mitigate this issue, I propose to make `DBALException` constructor private and `Exception` constructor public.

**Comment by derrabus** [comment]
Well, `DBALException` is gone since 3.0 and we won't introduce breaking changes to the 2.13 branch. I'd say, there's nothing to do here.
