### ISSUE TITLE
`Table::getPrimaryKeyColumns()` must return `Column[]` not `string[]`

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#4850]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | bugfix
| Version     | 3.1.3

#### Summary

`Table::getPrimaryKeyColumns()` must return `Column[]` not `string[]`

#### Current behaviour

Currently, it returns wrong type because in https://github.com/doctrine/dbal/blob/96b0053775a544b4a6ab47654dac0621be8b4cf8/src/Schema/Table.php#L806
`$primaryKey->getColumns()` returns `string[]` as implemented in https://github.com/doctrine/dbal/blob/96b0053775a544b4a6ab47654dac0621be8b4cf8/src/Schema/Index.php#L93

#### Expected behaviour

`Table::getPrimaryKeyColumns()` must return `Column[]`

**Comment by mvorisek** [comment]
Also all phpdocs are mismatched with the impl. Should be probably solved as part of https://github.com/doctrine/dbal/issues/4772

**Comment by morozov** [comment]
I plan to implement https://github.com/doctrine/dbal/issues/4772 primarily in `4.0.x` since it may require quite some breaking changes, and it's still just a plan. If there is something that could be improved in the supported branches, it can be done there.
