### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#4853]
Doctrine DBAL participates in [Hacktoberfest 2021](https://hacktoberfest.digitalocean.com/) and welcomes pull requests from regular contributors and newcomers alike. Please make sure, you have read the [contribution guidelines](https://www.doctrine-project.org/contribute/index.html).

### Improve the documentation!

* A great way to make a first contribution.
* The documentation is written in reStructuredText (RST) and located in the docs directory
* A rendered version can be found at https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/index.html
* Target the `3.1.x` branch.

### If you want to provide a new feature:

* Make sure it applies to all or at least the majority of the supported database platforms.
* If a new API needs to be introduced, please make sure it's type-safe.
* Target the `3.2.x` branch.

### If you want to contribute a bugfix:

* Target the `3.1.x` branch. We will take care of merging it up to higher branches.
* Always provide a test that fails without your changes. See the [testing guidelines](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/testing.html#testing-guidelines) for more details.

**Comment by greg0ire** [comment]
Cool feature to implement: https://github.com/doctrine/dbal/issues/1320
