### ISSUE TITLE
Optimize build pipeline by taking affected paths into account 

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#4854]
Currently, the build pipeline runs for any changes, even though some changes are known as not affecting the build results. For instance,

1. A change in documentation won't affect the build results of PHPUnit tests, static analysis or coding standards check.
2. A change in the configuration of a certain tool (e.g. PHPUnit) won't affect other build tools (e.g. PHPStan).
3. A change driver- or platform-specific code won't affect the build results in other drivers or platforms.

With that in mind, we can annotate the build jobs with `paths` and `paths-ignore` ([documentation](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths)).

**Comment by marulitua** [comment]
Please assign this to me

**Comment by marulitua** [comment]
I haven't figured out how to achieve the third requirement. `path` and `path-ignore` only available on workflow level, 
so I have to split `continuous-integration` workflow into each platform specific workflow, but then the coverage only for that particular specific platform. How to keep all the overall coverage but only run specific platform ?

**Comment by morozov** [comment]
@marulitua thanks for the research. I believe we can start simple and implement at least some basic improvements first.

As for the platform/driver specific optimization, we'll need to think first about how exactly we want to divide the builds: the platforms and the drivers are related as many-to-many (see `mysqli`/`pdo_mysql` and MySQL/MariaDB for example). If we divide them too specifically, there will be too many workflows.
