### ISSUE TITLE
Field with default value cannot be null

### ISSUE THREAD

**Issue by SaaberDev** [doctrine/dbal#4862]
Why this is happing ? Could not find a solution with proper description.

Note That: I used "0" with quotation, used boolean (true, false) but no good luck.

![image](https://user-images.githubusercontent.com/60372951/136765963-6fa806a7-2925-4719-a779-2791e28c8bb4.png)

**Comment by stof** [comment]
doctrine/common is not the issue tracker for all of Doctrine. Please report it to the right project.

**Comment by derrabus** [comment]
The code looks like Illuminate Database rather than Doctrine. Please use Laravel's trackers for support.

**Comment by SaaberDev** [comment]
I posted it in laravel repo. How did it came here ?🤔

**Comment by derrabus** [comment]
No, you did not.

**Comment by SaaberDev** [comment]
Sorry about that may be i need to take a break from my work.
