### ISSUE TITLE
PHP 8.1: MySQLi: Default error mode set to exceptions

### ISSUE THREAD

**Issue by mondrake** [doctrine/dbal#4870]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1

#### Summary

In PHP 8.1, MySQLi default error mode is set to exceptions. Prior to PHP 8.1, the default error reporting mode in MySQLi was to silent the errors.

If I understand correctly, now `mysqli_sql_exception` is not captured and standardized into DBAL exceptions, and rather bubble up in consuming code.

https://php.watch/versions/8.1/mysqli-error-mode

**Comment by morozov** [comment]
In https://github.com/doctrine/dbal/pull/4685, the `mysqli` driver sets the error mode to `MYSQLI_REPORT_OFF`. A patch that implements handling of the new default is welcome.

**Comment by derrabus** [comment]
I'm trying to fix this in #4875.
