### ISSUE TITLE
OracleSchemaManager::_getPortableTableColumnDefinition throws deprecations on PHP 8.1

### ISSUE THREAD

**Issue by mondrake** [doctrine/dbal#4871]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1

#### Summary

In PHP 8.1 you can get a deprecation when introspecting an Oracle schema on a null default column:

```
Deprecated function: trim(): Passing null to parameter #1 ($string) of type string is deprecated
Doctrine\DBAL\Schema\OracleSchemaManager->_getPortableTableColumnDefinition()() (Line: 111)
```

**Comment by morozov** [comment]
This will be fixed in `3.2.0` by https://github.com/doctrine/dbal/pull/4685.
