### ISSUE TITLE
A call to the non-deprecated AbstractPlatform::getAdvancedForeignKeyOptionsSQL() triggers a deprecation

### ISSUE THREAD

**Issue by simonberger** [doctrine/dbal#4886]
Dbal 2.13.4 still uses `AbstractPlatform::supportsForeignKeyOnUpdate` in `AbstractPlatform::supportsForeignKeyOnUpdate`
The library should never use a method it deprecated itself.

**Comment by morozov** [comment]
> The library should never use a method it deprecated itself.

Why?

See https://github.com/doctrine/dbal/pull/4278.

**Comment by simonberger** [comment]
@morozov because it triggers deprecation methods in 2.13 also when other projects use this library normally. I saw that problems like this seem to be normally solved by using `triggerIfCalledFromOutside` instead of `trigger`.

**Comment by morozov** [comment]
I see, yes. `AbstractPlatform::supportsForeignKeyOnUpdate()` should call `triggerIfCalledFromOutside()`, not `trigger()`.
