### ISSUE TITLE
?? syntax not working anymore?

### ISSUE THREAD

**Issue by lugosium** [doctrine/dbal#4889]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.1.3

#### Summary

The ?? syntax seems to not work anymore after upgrading dbal from 2.* to 3.*.

`$connection->fetchFirstColumn("SELECT marking ?? 'published' from some_table")` => OK

But

`$connection->fetchFirstColumn("SELECT marking ?? 'published' from some_table where foo = :bar", ['bar' => true])`

gives:

`Positional parameter at index 0 does not have a bound value.`

Linked to #3078.

**Comment by morozov** [comment]
Besides the linked question, it doesn't look like DBAL ever supported this syntax: no tests, no documentation. But I assume it's a convention defined in `pdo_pgsql`.

**Comment by morozov** [comment]
So, to reproduce this issue, we need the query to be parameterized and the named parameters used:
```php
$connection->fetchOne('SELECT \'{"a":null}\'::jsonb ?? :key', ['key' => 'a']);
```

**Comment by lugosium** [comment]
Thank you 🎉
