### ISSUE TITLE
Attempted to call an undefined method named "pgsqlGetNotify" of class "Doctrine\DBAL\Driver\PDO\Connection"

### ISSUE THREAD

**Issue by 99hops** [doctrine/dbal#4893]
### BC Break Report
|    Q        |   A
|------------ | ------
BC Break    | yes
Version     | 3.1.3

#### Summary

With composer set to 
```
"prefer-stable": true
"doctrine/orm": "^2.9" 
```

after update to doctrine/orm 2.10.1 I get Attempted to call an undefined method named "pgsqlGetNotify" of class "Doctrine\DBAL\Driver\PDO\Connection"

I am using Symfony 5.3 consumers to pull messages with PostgreSQL 13.4

#### Previous behaviour

No error message

#### Current behavior

Attempted to call an undefined method named "pgsqlGetNotify" of class "Doctrine\DBAL\Driver\PDO\Connection"

#### How to reproduce

Change "doctrine/orm": "2.9", to "doctrine/orm": "^2.9"

```
composer update
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "^5.3"
Updating dependencies
Lock file operations: 0 installs, 2 updates, 0 removals
  - Upgrading doctrine/dbal (2.13.4 => 3.1.3) <--- this is what causes the error
  - Upgrading doctrine/orm (2.9.0 => 2.10.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Downloading doctrine/dbal (3.1.3)
  - Downloading doctrine/orm (2.10.1)
  - Upgrading doctrine/dbal (2.13.4 => 3.1.3): Extracting archive 
  - Upgrading doctrine/orm (2.9.0 => 2.10.1): Extracting archive 
```

**Comment by derrabus** [comment]
This BC break was introduced with DBAL 3.0 and is documented. The driver connection does not extend the PDO connection anymore. There's a `getWrappedConnection()` method in case you need to access it.

**Comment by 99hops** [comment]
Isn't it supposed that "doctrine/orm": "^2.9" should not introduce such BC changes and stick dependencies to the 2. versioning? 
Looking at the composer [manual](https://getcomposer.org/doc/articles/versions.md#caret-version-range-) I read "The ^ operator behaves very similarly, but it sticks closer to semantic versioning, and will always allow non-breaking updates."

**Comment by derrabus** [comment]
But as you noted yourself, it was DBAL that introduced the BC break, not ORM. If you used DBAL only through the ORM, everything would be fine. This issue however has nothing to do with the ORM.

Your project interacts with DBAL classes directly which makes DBAL a direct dependency of your project. You performed a major version update of a direct dependency of your project, so I'm sorry, you need to read the upgrade notes of that library and test thoroughly.
