### ISSUE TITLE
PHP 8.1 - default value for type is wrong in ExpressionBuilder::literal

### ISSUE THREAD

**Issue by come-nc** [doctrine/dbal#4906]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.1.2

#### Summary

This PHP error happens with PHP 8.1:
`PHP Deprecated:  PDO::quote(): Passing null to parameter #2 ($type) of type int is deprecated in /home/mcmic/dev/doctrine/dbal/src/Driver/PDO/Connection.php on line 96`

You changed the default value in Connection::quote, but not in ExpressionBuilder::literal, which is:
```
    /**
     * Quotes a given input parameter.
     *
     * @param mixed    $input The parameter to be quoted.
     * @param int|null $type  The type of the parameter.
     *
     * @return string
     */
    public function literal($input, $type = null)
    {
        return $this->connection->quote($input, $type);
    }
```

But null is not a valid value anymore in PHP 8.1 as passing it to PDO::quote triggers the warning.

**Comment by derrabus** [comment]
Confirmed, on it.
