### ISSUE TITLE
[3.1.3] SQL Parser: Assertion error on long query string, caused by JIT stack limit exhaustion

### ISSUE THREAD

**Issue by j-schumann** [doctrine/dbal#4907]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.1.3
|PHP Version | 8.0.8
|php.ini pcre.jit | 1
|php.ini pcre.recursion_limit| 100000
|php.ini memory_limit| 300M

#### Summary

I upgraded from 2.13.4 to 3.1.3 in an API Platform / Symfony project and got this regression in executability,
caused by: ```Fatal error: Uncaught AssertionError: assert($offset === strlen($sql)) in .../vendor/doctrine/dbal/src/SQL/Parser.php:105```

#### Previous behaviour

All DQL was correctly converted to SQL and parsed+executed.

#### Current behavior

SQL parsing fails.

#### How to reproduce

Minimal reproduction repository: https://github.com/j-schumann/dbal-test

Steps:
* create a long SQL query, no parameters needed
* create a Parser instance and try to parse the long SQL -> fatal error
* reduce the SQL string length, e.g. by reducing selected fields until it works again
* set $mySQLStringEscaping = true in the Parser constructor to fail again with a shorter string, see example

It seems to be a combination of string length & used patterns, when debugging preg_match() on https://github.com/doctrine/dbal/blob/3.1.3/src/SQL/Parser.php#L95 fails when matching the following pattern:
```
('[^']*'|"[^"]*"|`[^`]*`|(?<!\b(?i:ARRAY))\[(?:[^\]])*\]|:{2,}|--[^\r\n]*|/\*([^*]+|\*+[^/*])*\**\*/|((?![:\?'"`\[\-\/]).)+)+
```

preg_last_error_msg() returns `JIT stack limit exhausted`

I want to emphasize that executing the DQL that caused this query worked with the same PHP version & settings in DBAL 2.13.4, that's why I filed this as BC break.

**Comment by pedrocasado** [comment]
Same here after upgrading from 2.13.3 with a quite long query (9 joins).

I'm using PHP 7.4.

**Comment by morozov** [comment]
It should be possible to simplify the regex by matching the next fragment of the query against each of the `$patterns` individually instead of smashing them together.

**Comment by morozov** [comment]
@j-schumann, @pedrocasado please see the linked PR. It works with the query in the issue description but it would be nice if you could test it with other queries that make the current implementation fail.

**Comment by j-schumann** [comment]
@morozov after quickly applying the patch and running a first test I have to say it does'nt fix the 3 queries  in my unit tests that cause this problem. I will do some more in-depth testing and come back with new query examples.

Edit: reproduction repo updated with a new query. I currently don't have more test cases, my 3 failing unit tests all fail with the same query.
While looking for solutions for this issue yesterday I found https://stackoverflow.com/a/40923765/1341762 which is about the same stack exhaustion, so I tested the new pattern from #4916 and it still shows up quite inefficient with 34k steps on regex101.com: https://i.imgur.com/T2JvMJs.png

**Comment by morozov** [comment]
@j-schumann could you share those 3 queries so that we could run the parser against them? And thanks for sharing the tips.

**Comment by j-schumann** [comment]
@morozov see https://github.com/j-schumann/dbal-test/blob/master/dbal-test.php#L21, don't want to paste it here because >9KiB

**Comment by morozov** [comment]
So it's the same query? For me, parsing this query repeated 1000 times (8,027,257 bytes in total) works with the new implementation. The old one fails with the same error as in your case.

**Comment by morozov** [comment]
I tried using regex101 and seeing if there's a specific portion of the complex regex that makes the engine perform this many steps. It looks like the number of steps primarily depends on the length of the test string rather than the regex. [Here](https://regex101.com/r/1dYusm/1), there's just a small portion of the regex, and it still takes ~52K steps to parse your query. Although, this part may be the root cause of the complexity.

**Comment by j-schumann** [comment]
Did you use the "new" query from line 21? This is the longer version of the "old" query in line 12. And this new query fails for me with the patch from #4916 applied, with the settings/PHP version from the OP. I don't have different queries at the moment.

Does executing `php dbal-test.php` fail for you when you clone the repo (and `composer install`, maybe after adjusting the required PHP version) in your environment?

Probably not, I just tested it now: Some of my environments (ubuntu + php7,  debian docker container + php7) work, even without the patch, with pcre.jit enabled. Only the Docker container with Alpine (php:8-fpm-alpine) fails.

Do you know how to view the stack size that is used? I read it can be set as compile time option, but the configure command in the alpine container looks unsuspecting:
```
Configure Command =>  './configure'  '--build=x86_64-linux-musl' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--with-pic' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-pdo-sqlite=/usr' '--with-sqlite3=/usr' '--with-curl' '--with-libedit' '--with-openssl' '--with-zlib' '--with-pear' '--enable-fpm' '--with-fpm-user=www-data' '--with-fpm-group=www-data' '--disable-cgi' 'build_alias=x86_64-linux-musl'
```

**Comment by morozov** [comment]
Sorry, I didn't notice there was a new query. Yes, the new one still fails.

**Comment by morozov** [comment]
It's indeed the "other" token regular expression that is causing the trouble:
```regex
~\G((?![:\?'"`\[\-\/]).)+~s
```
Even if it's applied alone to the 9KB query, it causes the JIT stack exhaustion.

**Comment by morozov** [comment]
@j-schumann please check the implementation in https://github.com/doctrine/dbal/pull/4927.

**Comment by j-schumann** [comment]
I can confirm that the assertion error is gone with #4927 (for this query, in my environment).

**Comment by pedrocasado** [comment]
My query also works with this patch.

**Comment by makm** [comment]
I known, it's looks crazy, but however:

`SELECT CASE WHEN p0_.id = 96990 THEN 0 WHEN p0_.id = 98840 THEN 1 WHEN p0_.id = 99257 THEN 2 WHEN p0_.id = 97437 THEN 3 WHEN p0_.id = 98872 THEN 4 WHEN p0_.id = 98570 THEN 5 WHEN p0_.id = 98635 THEN 6 WHEN p0_.id = 98657 THEN 7 WHEN p0_.id = 98925 THEN 8 WHEN p0_.id = 98661 THEN 9 WHEN p0_.id = 96495 THEN 10 WHEN p0_.id = 98841 THEN 11 WHEN p0_.id = 98622 THEN 12 WHEN p0_.id = 48010 THEN 13 WHEN p0_.id = 97531 THEN 14 WHEN p0_.id = 98677 THEN 15 WHEN p0_.id = 98302 THEN 16 WHEN p0_.id = 98458 THEN 17 WHEN p0_.id = 48553 THEN 18 WHEN p0_.id = 98690 THEN 19 WHEN p0_.id = 99093 THEN 20 WHEN p0_.id = 98658 THEN 21 WHEN p0_.id = 96539 THEN 22 WHEN p0_.id = 85661 THEN 23 WHEN p0_.id = 85789 THEN 24 WHEN p0_.id = 98734 THEN 25 WHEN p0_.id = 98783 THEN 26 WHEN p0_.id = 98572 THEN 27 WHEN p0_.id = 98769 THEN 28 WHEN p0_.id = 98778 THEN 29 WHEN p0_.id = 93133 THEN 30 WHEN p0_.id = 94853 THEN 31 WHEN p0_.id = 98664 THEN 32 WHEN p0_.id = 98573 THEN 33 WHEN p0_.id = 98575 THEN 34 WHEN p0_.id = 98576 THEN 35 WHEN p0_.id = 96924 THEN 36 WHEN p0_.id = 96540 THEN 37 WHEN p0_.id = 82894 THEN 38 WHEN p0_.id = 97154 THEN 39 WHEN p0_.id = 97436 THEN 40 WHEN p0_.id = 98957 THEN 41 WHEN p0_.id = 98958 THEN 42 WHEN p0_.id = 98959 THEN 43 WHEN p0_.id = 50192 THEN 44 WHEN p0_.id = 61341 THEN 45 WHEN p0_.id = 92061 THEN 46 WHEN p0_.id = 97387 THEN 47 WHEN p0_.id = 98918 THEN 48 WHEN p0_.id = 99103 THEN 49 WHEN p0_.id = 88536 THEN 50 WHEN p0_.id = 98707 THEN 51 WHEN p0_.id = 98781 THEN 52 WHEN p0_.id = 50193 THEN 53 WHEN p0_.id = 87514 THEN 54 WHEN p0_.id = 87515 THEN 55 WHEN p0_.id = 96968 THEN 56 WHEN p0_.id = 97614 THEN 57 WHEN p0_.id = 48549 THEN 58 WHEN p0_.id = 73030 THEN 59 WHEN p0_.id = 97130 THEN 60 WHEN p0_.id = 98812 THEN 61 WHEN p0_.id = 99046 THEN 62 WHEN p0_.id = 98656 THEN 63 WHEN p0_.id = 98633 THEN 64 WHEN p0_.id = 98944 THEN 65 WHEN p0_.id = 98945 THEN 66 WHEN p0_.id = 98946 THEN 67 WHEN p0_.id = 97518 THEN 68 WHEN p0_.id = 4205 THEN 69 WHEN p0_.id = 842 THEN 70 WHEN p0_.id = 163 THEN 71 WHEN p0_.id = 10422 THEN 72 WHEN p0_.id = 41750 THEN 73 WHEN p0_.id = 41820 THEN 74 WHEN p0_.id = 45887 THEN 75 WHEN p0_.id = 45889 THEN 76 WHEN p0_.id = 45891 THEN 77 WHEN p0_.id = 45921 THEN 78 WHEN p0_.id = 46001 THEN 79 WHEN p0_.id = 46002 THEN 80 WHEN p0_.id = 46003 THEN 81 WHEN p0_.id = 46008 THEN 82 WHEN p0_.id = 46010 THEN 83 WHEN p0_.id = 46013 THEN 84 WHEN p0_.id = 46087 THEN 85 WHEN p0_.id = 46090 THEN 86 WHEN p0_.id = 46188 THEN 87 WHEN p0_.id = 46204 THEN 88 WHEN p0_.id = 46205 THEN 89 WHEN p0_.id = 46387 THEN 90 WHEN p0_.id = 46436 THEN 91 WHEN p0_.id = 46612 THEN 92 WHEN p0_.id = 46644 THEN 93 WHEN p0_.id = 46691 THEN 94 WHEN p0_.id = 46739 THEN 95 WHEN p0_.id = 46741 THEN 96 WHEN p0_.id = 46769 THEN 97 WHEN p0_.id = 46770 THEN 98 WHEN p0_.id = 46771 THEN 99 WHEN p0_.id = 46772 THEN 100 WHEN p0_.id = 46773 THEN 101 WHEN p0_.id = 46792 THEN 102 WHEN p0_.id = 46882 THEN 103 WHEN p0_.id = 46883 THEN 104 WHEN p0_.id = 47316 THEN 105 WHEN p0_.id = 47811 THEN 106 WHEN p0_.id = 47812 THEN 107 WHEN p0_.id = 47815 THEN 108 WHEN p0_.id = 47819 THEN 109 WHEN p0_.id = 47821 THEN 110 WHEN p0_.id = 47822 THEN 111 WHEN p0_.id = 47825 THEN 112 WHEN p0_.id = 47826 THEN 113 WHEN p0_.id = 47829 THEN 114 WHEN p0_.id = 47830 THEN 115 WHEN p0_.id = 47831 THEN 116 WHEN p0_.id = 47832 THEN 117 WHEN p0_.id = 47833 THEN 118 WHEN p0_.id = 47834 THEN 119 WHEN p0_.id = 47836 THEN 120 WHEN p0_.id = 47840 THEN 121 WHEN p0_.id = 47842 THEN 122 WHEN p0_.id = 47844 THEN 123 WHEN p0_.id = 47845 THEN 124 WHEN p0_.id = 47848 THEN 125 WHEN p0_.id = 47849 THEN 126 WHEN p0_.id = 47852 THEN 127 WHEN p0_.id = 47854 THEN 128 WHEN p0_.id = 47858 THEN 129 WHEN p0_.id = 47862 THEN 130 WHEN p0_.id = 47864 THEN 131 WHEN p0_.id = 47929 THEN 132 WHEN p0_.id = 47930 THEN 133 WHEN p0_.id = 47931 THEN 134 WHEN p0_.id = 47932 THEN 135 WHEN p0_.id = 47936 THEN 136 WHEN p0_.id = 47939 THEN 137 WHEN p0_.id = 47941 THEN 138 WHEN p0_.id = 47942 THEN 139 WHEN p0_.id = 47943 THEN 140 WHEN p0_.id = 47944 THEN 141 WHEN p0_.id = 47945 THEN 142 WHEN p0_.id = 47947 THEN 143 WHEN p0_.id = 47950 THEN 144 WHEN p0_.id = 47952 THEN 145 WHEN p0_.id = 47954 THEN 146 WHEN p0_.id = 47956 THEN 147 WHEN p0_.id = 47959 THEN 148 WHEN p0_.id = 47960 THEN 149 WHEN p0_.id = 47961 THEN 150 WHEN p0_.id = 47962 THEN 151 WHEN p0_.id = 47963 THEN 152 WHEN p0_.id = 47964 THEN 153 WHEN p0_.id = 47965 THEN 154 WHEN p0_.id = 47973 THEN 155 WHEN p0_.id = 47975 THEN 156 WHEN p0_.id = 47976 THEN 157 WHEN p0_.id = 47978 THEN 158 WHEN p0_.id = 47979 THEN 159 WHEN p0_.id = 47980 THEN 160 WHEN p0_.id = 47981 THEN 161 WHEN p0_.id = 47983 THEN 162 WHEN p0_.id = 47984 THEN 163 WHEN p0_.id = 47986 THEN 164 WHEN p0_.id = 47987 THEN 165 WHEN p0_.id = 47989 THEN 166 WHEN p0_.id = 47990 THEN 167 WHEN p0_.id = 47991 THEN 168 WHEN p0_.id = 47992 THEN 169 WHEN p0_.id = 47993 THEN 170 WHEN p0_.id = 47995 THEN 171 WHEN p0_.id = 47997 THEN 172 WHEN p0_.id = 47998 THEN 173 WHEN p0_.id = 47999 THEN 174 WHEN p0_.id = 48003 THEN 175 WHEN p0_.id = 48004 THEN 176 WHEN p0_.id = 48005 THEN 177 WHEN p0_.id = 48008 THEN 178 WHEN p0_.id = 48009 THEN 179 WHEN p0_.id = 48011 THEN 180 WHEN p0_.id = 48018 THEN 181 WHEN p0_.id = 48019 THEN 182 WHEN p0_.id = 48021 THEN 183 WHEN p0_.id = 48104 THEN 184 WHEN p0_.id = 48124 THEN 185 WHEN p0_.id = 48126 THEN 186 WHEN p0_.id = 48139 THEN 187 WHEN p0_.id = 48143 THEN 188 WHEN p0_.id = 48203 THEN 189 WHEN p0_.id = 48205 THEN 190 WHEN p0_.id = 48344 THEN 191 WHEN p0_.id = 48350 THEN 192 WHEN p0_.id = 48351 THEN 193 WHEN p0_.id = 48352 THEN 194 WHEN p0_.id = 48354 THEN 195 WHEN p0_.id = 48355 THEN 196 WHEN p0_.id = 48358 THEN 197 WHEN p0_.id = 48361 THEN 198 WHEN p0_.id = 48366 THEN 199 WHEN p0_.id = 48368 THEN 200 WHEN p0_.id = 48372 THEN 201 WHEN p0_.id = 48376 THEN 202 WHEN p0_.id = 48377 THEN 203 WHEN p0_.id = 48383 THEN 204 WHEN p0_.id = 48387 THEN 205 WHEN p0_.id = 48390 THEN 206 WHEN p0_.id = 48393 THEN 207 WHEN p0_.id = 48395 THEN 208 WHEN p0_.id = 48396 THEN 209 WHEN p0_.id = 48397 THEN 210 WHEN p0_.id = 48398 THEN 211 WHEN p0_.id = 48558 THEN 212 WHEN p0_.id = 48593 THEN 213 WHEN p0_.id = 48598 THEN 214 WHEN p0_.id = 48618 THEN 215 WHEN p0_.id = 48619 THEN 216 WHEN p0_.id = 48621 THEN 217 WHEN p0_.id = 48624 THEN 218 WHEN p0_.id = 48626 THEN 219 WHEN p0_.id = 48627 THEN 220 WHEN p0_.id = 48632 THEN 221 WHEN p0_.id = 48633 THEN 222 WHEN p0_.id = 48930 THEN 223 WHEN p0_.id = 49014 THEN 224 WHEN p0_.id = 49146 THEN 225 WHEN p0_.id = 49147 THEN 226 WHEN p0_.id = 49148 THEN 227 WHEN p0_.id = 49151 THEN 228 WHEN p0_.id = 49238 THEN 229 WHEN p0_.id = 49248 THEN 230 WHEN p0_.id = 49249 THEN 231 WHEN p0_.id = 49256 THEN 232 WHEN p0_.id = 49258 THEN 233 WHEN p0_.id = 49261 THEN 234 WHEN p0_.id = 49327 THEN 235 WHEN p0_.id = 49329 THEN 236 WHEN p0_.id = 49369 THEN 237 WHEN p0_.id = 49371 THEN 238 WHEN p0_.id = 49487 THEN 239 WHEN p0_.id = 49511 THEN 240 WHEN p0_.id = 49514 THEN 241 WHEN p0_.id = 49552 THEN 242 WHEN p0_.id = 49553 THEN 243 WHEN p0_.id = 49591 THEN 244 WHEN p0_.id = 49627 THEN 245 WHEN p0_.id = 49647 THEN 246 WHEN p0_.id = 49648 THEN 247 WHEN p0_.id = 49700 THEN 248 WHEN p0_.id = 49702 THEN 249 ELSE 249 END AS sclr_0, p0_.id AS id_1, p0_.barcode_type AS barcode_type_2, p0_.barcode AS barcode_3, p0_.art AS art_4, p0_.created_at AS created_at_5, p0_.updated_at AS updated_at_6, p0_.deleted_at AS deleted_at_7, p0_.gross AS gross_8, p1_.id AS id_9, p1_.slug AS slug_10, p1_.caption AS caption_11, p1_.head_title AS head_title_12, p1_.meta_keywords AS meta_keywords_13, p1_.meta_description AS meta_description_14, p1_.description AS description_15, p1_.video_tag AS video_tag_16, p1_.desc_values AS desc_values_17, p1_.alternative AS alternative_18, p1_.related AS related_19, p1_.created_at AS created_at_20, p1_.updated_at AS updated_at_21, p1_.deleted_at AS deleted_at_22, p1_.viewed_count AS viewed_count_23, p1_.priority AS priority_24, p1_.hidden AS hidden_25, p0_.product_set_id AS product_set_id_26, p0_.created_by_id AS created_by_id_27, p1_.brand_id AS brand_id_28, p1_.created_by_id AS created_by_id_29 FROM products p0_ LEFT JOIN product_sets p1_ ON p0_.product_set_id = p1_.id AND (p1_.deleted_at IS NULL) WHERE (p0_.id IN (?)) AND (p0_.deleted_at IS NULL) ORDER BY sclr_0 ASC`
