### ISSUE TITLE
mysqli driver support undocumented arguments for driverOptions

### ISSUE THREAD

**Issue by divinity76** [doctrine/dbal#4908]
### Bug Report

according to the mysqli driver documentation at https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html , the mysqli driverOptions argument only support mysqli::real_connect flags, but it also supports MYSQLI_OPT_CONNECT_TIMEOUT , which is not a real_connect flag, it is an argument for mysqli::options(), it works but it's not documented on that url.

(i was looking for how to set connection timeout when using the mysqli driver, couldn't really find any documentation on how to do it, but i just tried setting it in the driverOptions arugment, and to my surprise, it actually worked! would be nice if it was documented)

**Comment by morozov** [comment]
@divinity76, a patch to the documentation is welcome.

**Comment by morozov** [comment]
Closing due to the lack of interest in addressing the issue.
