### ISSUE TITLE
simple_array text length is not recognized/updated

### ISSUE THREAD

**Issue by ecwio** [doctrine/dbal#4946]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 2.7

using MariaDB

#### Summary

using `simple_array`; text length is not recognized/updated by `php bin/console make:migration` when property `length` is removed from entity property.

`php bin/console make:migration`  sees no change

#### How to reproduce

Create simple_array with length of 128
database object is mapped to tinytext
`videoLinkPreview tinytext COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '(DC2Type:simple_array)',`

remove length in the property
database migration sees no change

fix is to remove property; migrate, then recreate the entity property without length to get longtext
`videoLinkPreview longtext COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '(DC2Type:simple_array)',`

**Comment by morozov** [comment]
@signmeuptwice please see if your issue is reproducible on `3.2.x-dev`. It may have been fixed by https://github.com/doctrine/dbal/pull/4746. If it still is, please provide more details. Ideally, a failing test.

**Comment by morozov** [comment]
Closing due to the lack of feedback.
