### ISSUE TITLE
Prevent iterating `Result` -- or make it work

### ISSUE THREAD

**Issue by UlrichThomasGabor** [doctrine/dbal#5025]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature |
| RFC         | 
| BC Break    | 

#### Summary

From what I see in [documentation](https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/data-retrieval-and-manipulation.html#data-retrieval) and [code](https://github.com/doctrine/dbal/blob/3.1.x/src/Result.php) a `Result`-object cannot be used like in the following snippet
```php
$resultSet = $conn->executeQuery('SELECT * FROM user WHERE username = ?', array('jwage'));
foreach ($resultSet as $user) {
  echo $user['id']; // Variant 1
  echo $user[0]; // Variant 2
}
```

Nevertheless, **this code runs through** without signaling that it is using the object in a non-planned way (iterating over all public properties, but there is none, so this just does nothing). Given that such code is working with PDO, such faulty usage of the interface is expected and at the same time hard to find without signaling any odd usage. (It was also working in previous versions of DBAL.)

I propose to change that behavior in one of the following two ways:
1. Throw an Exception
2. Return an actual iterator

Variant 1 can be implemented as
```php
class Result implements \IteratorAggregate
{
    ...

    public function getIterator(): Traversable
    {
        throw new \LogicException('not implemented');
    }
}
```

Variant 2 can be implemented as
```php
class Result implements \IteratorAggregate
{
    ...

    public function getIterator(): Traversable
    {
        return $this->iterateAssociativeIndexed();
    }
}
```

**Comment by derrabus** [comment]
Okay, the main problem here is that something like this works in PHP:

```php
class Foo {
    public $bar = 'baz';
}

foreach (new Foo as $key => $value) {
    var_dump($key);
    var_dump($value);
}
```

https://3v4l.org/pImFj

Should we really compensate for one of PHP's… unfortunate design decisions?

I'm almost certain that your variant 1 is a bad idea. We would prevent iteration all right, but at the same time we would actively indicate that the result object _is_ `iterable`. It would suddenly pass `iterable`  and `Traversable` type checks and we would fool static analysis tools this way.

Variant 2 is kind-of back to the roots. The possibility to iterate over the result statement directly had been removed because there's more than one way how a developer would want to iterate over a result: rows as arrays keyed by field name, as numeric arrays, as objects, … Directly iterating the result is either ambiguous or has to depend on a setting which again makes the code hard to analyse for a tool.

Right now, my favorite variant would be leaving everything as it is. 😕

**Comment by UlrichThomasGabor** [comment]
Since this is a library for PHP, it has to live with what the language brings in. This includes that objects are iterable by default and that PDO statements are iterable as well, which leads to certain assumptions using this DBAL.

Regarding Variant 1: I share your concerns regarding implementing `Traversable`, fulfilling corresponding checks with `instanceof`, but then not implementing it.

Regarding Variant 2: I do not see how "present the user of an interface with a reasonable default" is worse than "present the user with unexpected behavior causing harm". Using the object as listed in my first post is also not highlighted by any static analysis tool, because "iterate the object" and "iterate the result set" are both valid usages. No tool can decide, what a programmer wanted to actually do. But, iterating an empty object is likely never what one wants to do with a `Result` object. (Actually, I think that throwing an exception as in Variant 1 could at least be found by analyzers at all.)

Therefore, I would vote for variant 2. It prevents nothing, i.e. every developer can still choose to use one of the `iterate*` methods if he prefers. It just fixes mistakes, which are otherwise invisible. And be it that we are trying to access array keys inside the loop, which are not there because we expected a numerical row and were given an associative row per default (or vice versa).

**Comment by morozov** [comment]
I agree with what @derrabus said. Closing.

**Comment by derrabus** [comment]
> present the user with unexpected behavior causing harm

Well, if you try to iterate over a non-traversable object without public properties, you will basically iterate over an empty set. That does not sound harmful to me.

> Using the object as listed in my first post is also not highlighted by any static analysis tool

Well: https://psalm.dev/r/113c1de22f

> Therefore, I would vote for variant 2. It prevents nothing

You're basically asking us to take back a deliberate design descision that we've made when decoupling DBAL from PDO.

I'm really not convinced that we should do that. I'm really sorry that the behavior of the new result class surprised you, but I'm sure you'll be able to work with it just fine.

**Comment by UlrichThomasGabor** [comment]
> > present the user with unexpected behavior causing harm
> 
> Well, if you try to iterate over a non-traversable object without public properties, you will basically iterate over an empty set. That does not sound harmful to me.

I would say that this is undesirable at all for "normal" objects, but that is something to discuss/change on language level not here.

In the context of PHP and PDO we have a language which allows to iterate over variables, and we have a similar official library, which allows to iterate over the result set. As I said, this wakes assumptions, which one might try and which are silently ignored here. To me, this is a non-robust interface. It is surprising that it does not work, and it is surprising a second time that it will not complain if it's used wrongly.

I don't think "surprising behavior" is in any way a desirable goal for software.


> > Using the object as listed in my first post is also not highlighted by any static analysis tool
> 
> Well: https://psalm.dev/r/113c1de22f

Well, it is doing exactly what I said: It cannot determine if this was desirable or not.

[There are papers](https://ieeexplore.ieee.org/document/6606613) telling us that unclear messages from static analyzers are often just ignored by its users. Highlighting just everything which _may_ be wrong can be not helpful at all, e.g. in a project using raw-object iteration regularly for whatever.


> > Therefore, I would vote for variant 2. It prevents nothing
> 
> You're basically asking us to take back a deliberate design descision that we've made when decoupling DBAL from PDO.
> 
> I'm really not convinced that we should do that.

I have not read any technical argument against variant 2.

The only argument against it until now is:
> The possibility to iterate over the result statement directly had been removed because there's more than one way how a developer would want to iterate over a result:

That is no technical argument, but an ... educational?

Like I said, I do not see any harm caused by just returning any iterator explicitly, being associative, numeric or whatever. But I see harm in deciding for breaking with the context the language brings with: iterable objects per language design, an existing related official library providing exactly that, and an object one will want to iterate in most cases.

What good does the best and cleanest interface bring, if it does not fit the context?

> I'm really sorry that the behavior of the new result class surprised you, but I'm sure you'll be able to work with it just fine.

Obviously, I have seen the problem. I want to make it go away for others.


By the way, there is a third solution: Just add any public property:
```php
public $unsupportedRawObjectIteration = 'This object does not support raw object iteration.';
```

By doing that, the `foreach` will actually loop and do something, likely causing an error further down, see https://3v4l.org/128CI throwing an error in comparison to https://3v4l.org/AgMc8.

I think this is less appealing than my proposed variants, but maybe you think this is better.

**Comment by derrabus** [comment]
> In the context of PHP and PDO we have a language which allows to iterate over variables, and we have a similar official library, which allows to iterate over the result set.

We don't agree with several design decisions of PDO which is one of the reasons why DBAL has been decoupled from the PDO interfaces in 3.0.

> > Well: https://psalm.dev/r/113c1de22f
> 
> Well, it is doing exactly what I said: It cannot determine if this was desirable or not.

I'm not sure if I'm seeing a different output than you, but Psalm clearly reports an error. A project that uses Psalm would actively need to suppress that error. Your interpretation of the output might be… different than mine, but we agree that static analysis tools are able to detect this case, don't we?

> That is no technical argument, but an ... educational?

And because of that the argument is invalid?

> unclear messages from static analyzers are often just ignored by its users

Talking about "educational arguments": This is cercainly one.

Sorry, I don't think that this discussion is leading us anywhere.

**Comment by UlrichThomasGabor** [comment]
> > In the context of PHP and PDO we have a language which allows to iterate over variables, and we have a similar official library, which allows to iterate over the result set.
> 
> We don't agree with several design decisions of PDO which is one of the reasons why DBAL has been decoupled from the PDO interfaces in 3.0.

I understand this goal and I think the separation is good, but it is only part of what came up here.

The main question I still have is: Why is a class, whose main purpose is to provide a collection of data, not iterable? This has only to do with PDO as far as it is one example of a library, which provides a default for an iterator.

Being iterable or returning directly an array is [just](https://www.php.net/manual/en/function.imap-fetch-overview.php) [how](https://github.com/laravel/framework/blob/78637dcc784e8c85e08490d47098cd7531dcaa81/src/Illuminate/Collections/Collection.php#L12) [this](https://3v4l.org/dmRlp) [ecosystem](https://3v4l.org/crPeD) [works](https://www.php.net/manual/en/class.pdostatement.php) ([and](https://www.php.net/manual/en/function.ftp-mlsd.php) [works](https://www.php.net/manual/en/memcached.getserverlist.php) ([an](https://github.com/thephpleague/csv/blob/b6ac1da668bd74f0748061476ebfffa53def181f/src/ResultSet.php)[d](https://github.com/thephpleague/csv/blob/b6ac1da668bd74f0748061476ebfffa53def181f/src/TabularDataReader.php) [works](https://github.com/thephpleague/flysystem/blob/b12570ef64e4d35b9f29d71d7b4b3859b41ef0f9/src/DirectoryListing.php#L15))) ([at](https://3v4l.org/bWMUQ) [least](https://www.php.net/manual/en/class.ziparchive.php) [part](https://www.php.net/manual/en/class.directory.php) of it). Please share with me, what makes this Symfony class so special, that you feel it is wrong to implement `IteratorAggregate` and just return one of the existing iterators?

This is deterministic, prevents nobody from using another iterator, is more in line with expectations for users coming from `PDO`, Laravel or DBAL 2.0, and makes "faulty" usage of the interface either visible (by throwing an error) or just working. I do not see any harm here?

> > > Well: https://psalm.dev/r/113c1de22f
> > 
> > 
> > Well, it is doing exactly what I said: It cannot determine if this was desirable or not.
> 
> I'm not sure if I'm seeing a different output than you, but Psalm clearly reports an error. A project that uses Psalm would actively need to suppress that error. Your interpretation of the output might be… different than mine, but we agree that static analysis tools are able to detect this case, don't we?

It reports a "**Possibly** undesired iteration over regular object Foo". To me this is something else than an error.

> > That is no technical argument, but an ... educational?
> 
> And because of that the argument is invalid?

No, I would not have a problem with that, if PHP would not allow object iteration per default (or at least gave the ability to prevent it). But it does not.

**Comment by derrabus** [comment]
> The main question I still have is: Why is a class, whose main purpose is to provide a collection of data, not iterable? This has only to do with PDO as far as it is one example of a library, which provides a default for an iterator.

I have answered that question already. Besides, you're free to use PDO or Illuminate Database if that suits you better.

> what makes this Symfony class so special

Symfony is not involved here, as far as I can tell.

> > I'm not sure if I'm seeing a different output than you, but Psalm clearly reports an error. A project that uses Psalm would actively need to suppress that error. Your interpretation of the output might be… different than mine, but we agree that static analysis tools are able to detect this case, don't we?
> 
> It reports a "**Possibly** undesired iteration over regular object Foo". To me this is something else than an error.

Fine, but to Psalm it is exactly that: an error. Let me give you a hand here.

<img width="999" alt="Bildschirmfoto 2021-11-28 um 12 17 37" src="https://user-images.githubusercontent.com/1506493/143765691-b2393352-93fe-41cc-b614-1667d879244f.png">

> No, I would not have a problem with that, if PHP would not allow object iteration per default (or at least gave the ability to prevent it). But it does not.

Please file an RFC at PHP for changing that. You'll have my full support.
