### ISSUE TITLE
Sqlite does support schemas, current schema is always `'main'`

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5046]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.2.0

#### Summary

Sqlite does support schemas. The main schema is named `'main'`.

demo: http://sqlfiddle.com/#!5/2174f5/3

#### Current behaviour

`SqlitePlatform::getCurrentDatabaseExpression` return an empty SQL literal (`''`).

empty schema is not even valid http://sqlfiddle.com/#!5/2174f5/8

#### How to reproduce

1. the following assertion must be satisfied
```
$this->assertSame('\'main\'', $sqlitePlatform->getCurrentDatabaseExpression())
```
2. all functional tests that work with schemas must pass

#### Expected behaviour

`SqlitePlatform::getCurrentDatabaseExpression` must return `'main'`

**Comment by morozov** [comment]
There is nothing wrong with the current behavior.

**Comment by mvorisek** [comment]
Please reopen and see https://dbfiddle.uk/?rdbms=sqlite_3.27&fiddle=54b55ddd69d79f20ee2f86c0228e272b

I would like to work on SqlitePlatform support.
