### ISSUE TITLE
PDOStatement::bindParam: Passing null to parameter $maxLength is deprecated

### ISSUE THREAD

**Issue by Jeroeny** [doctrine/dbal#5134]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.2.0

#### Summary

When running `doctrine/dbal` `3.2.0` in **PHP 8.1**, a deprecation warning is thrown:

> `PDOStatement::bindParam()`: Passing null to parameter # 4 (`$maxLength`) of type `int` is deprecated in [/app/vendor/doctrine/dbal/src/Driver/PDO/Statement.php](https://github.com/doctrine/dbal/blob/3.2.x/src/Driver/PDO/Statement.php#L83) on line 84

#### Current behaviour

A deprecation warning is thrown. 

#### How to reproduce

By using the `Doctrine\DBAL\Driver\PDO\Statement::bindParam()` method.

#### Expected behaviour

I don't know if it's known that this deprecation isn't fixed yet, it's intended to not have been fixed or that an issue already exists. But I couldn't find anything about it yet.

**Comment by morozov** [comment]
> By using the Doctrine\DBAL\Driver\PDO\Statement::bindParam() method.

I assume you're explicitly passing `NULL` to `bindParam()`, aren't you? For instance,
```php
$value = 1;
$stmt = $connection->prepare('SELECT ?');
$stmt->bindParam(1, $value, ParameterType::INTEGER, null);
$stmt->executeQuery();

// Deprecated: PDOStatement::bindParam(): Passing null to parameter #4 ($maxLength) of type int is deprecated in /src/Driver/PDO/Statement.php
```

**Comment by Jeroeny** [comment]
That's indeed what is happening. It occurred in `getsentry/sentry-symfony`, fixing it there: https://github.com/getsentry/sentry-symfony/pull/586

**Comment by morozov** [comment]
Reopening since this is still a bug.
