### ISSUE TITLE
Question: Add additional SQL to default create SQLs

### ISSUE THREAD

**Issue by delorie** [doctrine/dbal#5135]
Hello :)

I have a question, we use a Postgres with the TimescaleDB extension.

Here, the "HyperTables" are created separately by the SQL command `create_hypertable`.
We wanted to do this with the help of onSchemaCreateTable.

```php
public function onSchemaCreateTable(SchemaCreateTableEventArgs $event): void {

        $table = $event->getTable();

        if ($this->isTableAHyperTable($table) === false) {
           return;
        }
        
        $resolver   = $this->createHyperTableOptionsResolver($table);
        $options    = $this->getHyperTableOptions($table, $resolver);
        
        $event->addSql($this->getCreateHyperTableSQL($table, $options));
}
```

Result: SELECT create_hypertable('timescale_energy_counter', 'time')

But this SQL does not come with the DIFF-File.
Only when "$event->preventDefault()" is called but then the Create-SQL for the table is missing.

This is the part in the code that adds the SQLs for the Tables:
https://github.com/doctrine/dbal/blob/701ebbc69951e6656e8841c59fdf8b886290ce57/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php#L1635
But this has no ELSE-Case, is there a special reason here?
Are we using this wrong?

The columns were solved differently, so that the SQLs are added additionally.

Many thanks in advance :)

**Comment by morozov** [comment]
> But this has no ELSE-Case, is there a special reason here?

I believe the idea here is that either you rely on the DBAL to build the schema or take over and do it yourself.

In my personal opinion, the event-based platform extension API was a poor design choice and should be avoided (more details in https://github.com/doctrine/dbal/pull/5126#discussion_r771009371).

In this specific case, it may work if you use a custom platform class and override the behavior of `getCreateTableSQL()` or other relevant methods.

**Comment by delorie** [comment]
Thank you :) 

We have opted for the platform-variant.

like:
```php
class PostgreSQLTimescalePlatform extends PostgreSQL100Platform {

    private OptionsResolver $hyperTableOptionsResolver;

    //......

    /**
     * @param Table $table
     * @param int $createFlags
     * @return string[]
     * @throws \Doctrine\DBAL\Exception
     */
    public function getCreateTableSQL(Table $table, $createFlags = self::CREATE_INDEXES): array {

        $generatedSQLs = parent::getCreateTableSQL($table, $createFlags);

        if ($this->isTableAHyperTable($table) === false) {
            return $generatedSQLs;
        }

        $options = $this->getHyperTableOptions($table, $this->hyperTableOptionsResolver);

        return array_merge($generatedSQLs, [$this->getCreateHyperTableSQL($table, $options)]);
    }

   //....
}
```
