### ISSUE TITLE
Error "JIT stack limit exhausted" in big queries

### ISSUE THREAD

**Issue by eisberg** [doctrine/dbal#5137]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.2.0 

#### Summary

When executing big DDL/SQL queries, the error "JIT stacklimit exhausted" occurs

Same problem reporting also here: 
Issue: #4980 
PR: #4927

Error trace: 

```
JIT stack limit exhausted
#0 vendor/doctrine/dbal/src/SQL/Parser.php(109): Doctrine\DBAL\SQL\Parser\Exception\RegularExpressionError::new()
#1 vendor/doctrine/dbal/src/Driver/OCI8/Connection.php(71): Doctrine\DBAL\SQL\Parser->parse('DELETE FROM DEV...', Object(Doctrine\DBAL\Driver\OCI8\ConvertPositionalToNamedPlaceholders))
#2 vendor/doctrine/dbal/src/Driver/OCI8/Connection.php(108): Doctrine\DBAL\Driver\OCI8\Connection->prepare('DELETE FROM DEV...')
#3 vendor/doctrine/dbal/src/Connection.php(1145): Doctrine\DBAL\Driver\OCI8\Connection->exec('DELETE FROM DEV...')
#4 vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleTableDeleteUpdateExecutor.php(45): Doctrine\DBAL\Connection->executeStatement('DELETE FROM DEV...', Array, Array)
#5 vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(322): Doctrine\ORM\Query\Exec\SingleTableDeleteUpdateExecutor->execute(Object(Doctrine\DBAL\Connection), Array, Array)
#6 vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1160): Doctrine\ORM\Query->_doExecute()
...
```
  
#### How to reproduce

Example DQL:  [dql.txt](https://github.com/doctrine/dbal/files/7755677/dql.txt)

pseudo code:

```
$this->createFilteredQueryBuilder($filter) //   << Doctrine\ORM\QueryBuilder, with filter ( many OR conditions, see dql.txt)
            ->delete($entityClassName, 'a')
            ->getQuery()
            ->execute();

```

#### Expected behaviour

Large SQL runs without errors (as in DBAL2)

**Comment by morozov** [comment]
I can reproduce the issue locally. It looks like the current version of the regular expressions used by the parser still can take too many steps on queries like the one in the description ([ref](https://regex101.com/r/mALfF3/1)).

**Comment by morozov** [comment]
@eisberg please see if https://github.com/doctrine/dbal/pull/5138 works for you. It works for me with your query.

**Comment by eisberg** [comment]
> @eisberg please see if #5138 works for you. It works for me with your query.

Yes, it works fine with this fix!
