### ISSUE TITLE
Add support for CyberArk credentials lookup

### ISSUE THREAD

**Issue by c-schinzer** [doctrine/dbal#5146]
In my work context am facing a security constraint that requires to lookup the database connectivity and credentials from a CyberArk safe; passwords are rotated by an automated policy. I thought, the best was to implement a custom driver that does the lookup through HTTPClient from the CyberArk REST API and then injects the retrieved connection details (host, port, dbname) and credentials (user. password) into the original Driver.

My current solution implements this through driverOptions (to hand in the CyberArk URI and lookup parameters) and through a custom class inheriting from the MysqliDriver class.

I am wondering whether such a solution could possibly be of general interest and should be added to the project.
Let me know, I am happy to contribute and esp. the to learn how to avoid to go through driverOptions with the CyberArk parameters as these are meant for something different I am pretty sure.

**Comment by derrabus** [comment]
> I thought, the best was to implement a custom driver that does the lookup through HTTPClient from the CyberArk REST API

Maybe I'm underestimating the complexity of your problem, but DBAL allows you to set the password in `DriverManager::getConnection()` and does not care much about how you retrieve the password. You should not need to implement a custom driver for that.

> I am wondering whether such a solution could possibly be of general interest

I highly doubt it. I don't think that we will be able to maintain that solution of yours.

**Comment by morozov** [comment]
As far as I understand, CyberArk can be used to store database configuration and credentials which the DBAL already accepts via the driver configuration. Why does integration with a specific configuration provider should be part of the DBAL?

Since configuration is part of a stable public API of the DBAL, if the goal is to have such integration to be publicly available, it can be implemented as a separate library.

**Comment by c-schinzer** [comment]
Hello both,


first of all, thanks for getting back.
I do agree, CyberArk is a configuration provider, however if used properly,
the configuration information, esp. credentials, are to be configured to be
changes dynamically. So it is not a config store only, rather AT CONNECT
time credentials needs to be checked and updated if required (provided a
cache is configured to avoid plenty requests).

Scope-wise it might not be the right thing to place it into DBAL (and I
think I got a similar reply some time ago when posting a similar
suggestion), but data-flow-wise it is related to the pickup of credentials
at connect-time; therefore I placed it into a custom provider.

Are you aware of dynamic configuration for doctrine in a different way? Is
anybody already doing credentials lookup around Kernel initialization time
in order to pipe them into the DBAL configuration? if so, thanks for a
hint. If not so: How would you solve the issue of looking up a remote
config store before initializing the Doctrine DBAL?

Thanks upfront and warm regards


Carsten

---


Dr. Carsten Schinzer

*Inhaber*



Am Mi., 29. Dez. 2021 um 16:56 Uhr schrieb Sergei Morozov <
***@***.***>:

**Comment by c-schinzer** [comment]
Sorry, custom driver of course.


Am Mi., 29. Dez. 2021 um 17:33 Uhr schrieb Carsten Schinzer <
***@***.***>:

**Comment by morozov** [comment]
> data-flow-wise it is related to the pickup of credentials at connect-time

Then a custom driver is a way to go. See the logging driver for example: https://github.com/doctrine/dbal/blob/843483d1c7655c6ed12d12ea8063328461d94f45/src/Logging/Driver.php#L31-L42

This is where you can exchange the CyberArk credentials for the connection parameters.

**Comment by c-schinzer** [comment]
Thanks, I'll check it out.

---


Dr. Carsten Schinzer

*Inhaber*


t +49 89 88569642 | f +49 89 99964059 | m +49 159 05269462

DCS Verkaufssysteme

Gerner Str. 27 | 80638 München | Germany


Am Mi., 29. Dez. 2021 um 17:53 Uhr schrieb Sergei Morozov <
***@***.***>:
