### ISSUE TITLE
SQLite strict mode support

### ISSUE THREAD

**Issue by sanderdlm** [doctrine/dbal#5149]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

SQLite recently added support for [STRICT mode typing](https://www.sqlite.org/stricttables.html) in version 3.37.0. It would be nice to support the syntax in Doctrine. I could work on this myself but I'm not familiar with the codebase and would need some pointers on what changes to make and where.

Initial idea:
* Add configuration option to set strict_typing to true
* Add a version check before parsing/allowing the option
* If the version check and the setting allow it, add the STRICT keyword to the SQLite create table syntax.

**Comment by morozov** [comment]
> I could work on this myself but I'm not familiar with the codebase and would need some pointers on what changes to make and where.

@dreadnip you'll have to be more specific on the pointers you need.

**Comment by sanderdlm** [comment]
I didn't have any free time to follow up on this, but I have been using the strict mode in personal projects. I've simply been generating migrations and then altering the generated SQL syntax.

Example of the regular syntax:
```sql
CREATE TABLE item (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
  title VARCHAR(255) NOT NULL, 
  visible BOOLEAN NOT NULL,
  created_on DATETIME DEFAULT NULL
)
```
and the STRICT table:
```sql
CREATE TABLE item (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  title TEXT NOT NULL,
  visible INTEGER NOT NULL,
  created_on TEXT DEFAULT NULL
) STRICT
```

If I wanted to add support for this to the DBAL/ORM, the STRICT keyword at the end could be added to the [createTableSQL method in the SqlitePlatform](https://github.com/doctrine/dbal/blob/3.3.x/src/Platforms/SqlitePlatform.php#L374):
```php
        $strictKeyword = '';
        if (isset($options['strict'])) {
            $strictKeyword = ' STRICT';
        }

        $query = ['CREATE TABLE ' . $name . ' ' . $tableComment . '(' . $queryFields . ')' . $strictKeyword];
```

but I'm lost on how the option would be passed down to this method. Should I add an `#[ORM\Strict]` attribute, or add an option to the existing Entity attribute `#[ORM\Entity(strict: true)]`? Is it ok if this ORM attribute would be the only use-case for this option in the DBAL? How would I pass down this attribute to the DBAL (correctly)?

The most drastic change would be the required data types for the Sqlite columns. Strict table mode only allows the following types:
* INTEGER
* REAL
* TEXT
* BLOB
* ANY 

which means that most of the current dbal-level types for Sqlite, like [boolean](https://github.com/doctrine/dbal/blob/3.3.x/src/Platforms/SqlitePlatform.php#L227) or [datetime](https://github.com/doctrine/dbal/blob/3.3.x/src/Platforms/SqlitePlatform.php#L299) throw an error when trying to create a table with them. 

I'm not sure how to approach this problem. As far as I know, types like VARCHAR(255) means absolutely nothing to Sqlite and are implicitly converted to TEXT. Does that mean that we could update the SQL type methods in SqlitePlatform to their strictest syntax? Or is the current implementation written this way to ensure maximal compatibility with other platforms? If everything is stored as INT/TEXT, it would probably be harder to migrate your schema to MySQL or Postgres.

Another option would be to keep both the regular data types and a strict alternative. Either in separate methods or by passing a flag to each of the `get<type>TypeDeclarationSQL` methods to set strict to true or false.

**Comment by morozov** [comment]
This looks like a huge project without a goal. As a DBAL user, what would be the benefits of the SQLite strict mode being supported by the DBAL? In my understanding, people use SQLite primarily for development and use a different database platform in production. What's the point in having a stricter development platform if the application still has to be tested against a production database?

I didn't dig deep into the reasoning behind the introduction of the strict mode but not the allowing columns like `DATETIME` makes it less compatible with other database platforms. Since one of the goals of the DBAL is portability, I don't see much point in supporting the configuration that makes a database platform less compatible with others.

**Comment by sanderdlm** [comment]
Alright, I understand. Regarding the usage of SQLite as a development database: It has actually gained quite a bit of traction as a production solution as well. As long as your project runs on a single server and is not write-heavy, it works very well. It's fast, back-ups are easy and deploying is simple as well. There is also more tooling like [Litestream](https://litestream.io/) that is making production-usage viable.

But I agree that the restrictive column types would increase incompatibility with other platforms in the DBAL and the cost of maintaining this code would outweigh the benefit of the feature.

**Comment by derrabus** [comment]
If that strict mode is enabled, how would DBAL handle boolean or datetime fields? How would it declare such a field and how would type conversions look like? I wonder if that strict more should be implemented as a separate platform in DBAL, as it would generate too many edge cases when handled by `SqlitePlatform`.

**Comment by morozov** [comment]
Closing as this is unlikely to happen.
