### ISSUE TITLE
`Driver\Mysqli\Connection::getServerVersion()` returns wrong version for MariaDB 10.x

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5170]
|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 3.2.1

#### Current behaviour

Version starting with `5.` is returned for MariaDB.

The fix mentioned in https://github.com/doctrine/dbal/blob/3.2.1/src/Driver/Mysqli/Connection.php#L49 seems to be not working.

#### How to reproduce

Start `mariadb:latest` Docker image (or other MariaDB 10 instance) and test the version returned by DBAL.

Reproduced in CI:

https://github.com/atk4/data/blob/275b9f4243136eea05625d6d3595063001ba4fe2/tests/WithTest.php#L53 (the condition is satisfied even with MariaDB 10.x)

#### Expected behaviour

For the latest `mariadb:latest` Docker image version starting with `10.` should be returned.

**Comment by morozov** [comment]
@mvorisek could you be more specific about what's not working for you?

If I query the version in `mariadb:latest`, I get:
```
mysql> SELECT VERSION();
+---------------------------------------+
| VERSION()                             |
+---------------------------------------+
| 10.5.10-MariaDB-1:10.5.10+maria~focal |
+---------------------------------------+
1 row in set (0.01 sec)
```
There's a test case that covers a similar version pattern: https://github.com/doctrine/dbal/blob/4caf37acf14b513a91dd4f087f7eda424fa25542/tests/Driver/AbstractMySQLDriverTest.php#L67

**Comment by mvorisek** [comment]
Here is a repro https://github.com/atk4/data/runs/4771743049?check_suite_focus=true with version dump:

```
var_dump(...->expr('select version()')->getOne()); // raw version from SQL
var_dump(...->getWrappedConnection()->getServerVersion()); // version from DBAL
```

```
string(35) "10.6.5-MariaDB-1:10.6.5+maria~focal"
string(41) "5.5.5-10.6.5-MariaDB-1:10.6.5+maria~focal"
```

instead of `5.5.5-10.6.5-MariaDB-1:10.6.5+maria~focal` I expect `10.6.5` or `10.6.5-MariaDB`, or at least the `5.5.5-` prefix must be stripped (it is there for replication compatibility, see https://jira.mariadb.org/browse/MDEV-4088)

**Comment by morozov** [comment]
This prefix comes from [mysqlnd](https://github.com/php/php-src/blob/72cdb0af5500b57e4a83c6eeb64faf5bb3a917e7/ext/mysqlnd/mysqlnd_connection.c#L1281), not the DBAL:
```c
#define MARIA_DB_VERSION_HACK_PREFIX "5.5.5-"
```
I'm not sure why the driver connections perform any parsing of the version string. It should be up to the API consumer to parse it and extract the details according to the use case. This applies to the driver which instantiates the corresponding platform.

I'd prefer to get rid of parsing the version in the driver connections at all.

**Comment by mvorisek** [comment]
> This prefix comes from [mysqlnd](https://github.com/php/php-src/blob/72cdb0af5500b57e4a83c6eeb64faf5bb3a917e7/ext/mysqlnd/mysqlnd_connection.c#L1281), not the DBAL:
> 
> ```c
> #define MARIA_DB_VERSION_HACK_PREFIX "5.5.5-"
> ```

this code should actually fix it, it seems the `mysqlnd_conn_data::get_server_version` C function is not used for `mysqli::get_server_info`

opened https://github.com/php/php-src/issues/7932

**Comment by derrabus** [comment]
This `5.5.5` prefix is a hack for legacy clients that were built at a time when you would use ext-mysqli and PDO_mysql exclusively to connect to a MySQL server. Returning a version 10.x would mislead those clients to think that they're connected to a future MySQL server when they're in fact talking to a MariaDB.

Since DBAL is aware of MariaDB and implements dedicated drivers for it, I think it would be okay to revert that hack and return the actual version number of the MariaDB server.

**Comment by mvorisek** [comment]
> This `5.5.5` prefix is a hack for legacy clients that were built at a time when you would use ext-mysqli and PDO_mysql exclusively to connect to a MySQL server.

It is a hack from MariaDB server side to fix replication (https://jira.mariadb.org/browse/MDEV-4088).

I agree with @morozov, it should be fixed in php-src directly.

**Comment by derrabus** [comment]
> It is a hack from MariaDB server side to fix replication (https://jira.mariadb.org/browse/MDEV-4088).

Right, thanks for the clarification.

> I agree with @morozov, it should be fixed in php-src directly.

No argument from me, this is where the fix belongs. However, a workaround in the DBAL driver for PHP versions without that fix (if we get one) would still be reasonable and not hard to maintain, imho.

**Comment by morozov** [comment]
> However, a workaround in the DBAL driver for PHP versions without that fix (if we get one) would still be reasonable and not hard to maintain, imho.

Just to clarify, my proposal in https://github.com/doctrine/dbal/issues/5170#issuecomment-1010130282 was the opposite:
> I'd prefer to get rid of parsing the version in the driver connections at all.

I don't believe the DBAL should be in the business of massaging the versions returned by the server. We should just remove this parsing entirely instead of trying to satisfy all possible cases.
