### ISSUE TITLE
Global error handling/interception at the DBAL layer

### ISSUE THREAD

**Issue by RinkAttendant6** [doctrine/dbal#5171]
|    Q        |   A
|------------ | -----
| Version     | 2.x (specifically 2.9.3-2.13.x)

### Support Question

Is there a way to do something "globally" (e.g. logging) whenever a query error occurs (e.g. by catching `\Doctrine\DBAL\Exception`) while allowing the exception to propagate to be handled in the application code (either in the specific method that called the database or higher up at the front controller level)?

Currently using version 2.9 I am using the wrapperClass to provide a decorated connection like this:

```php
use Doctrine\DBAL\Connection;
use Doctrine\DBALException;
use Psr\Log\LoggerAwareTrait;

class DecoratedConnection extends Connection
{
    use LoggerAwareTrait;

    public function executeUpdate($query, array $params = [], array $types = []): int
    {
        try {
            return parent::executeUpdate($query, $params, $types);
        } catch (DBALException $e) {
            $this->handleErrors($e, $query, $params, $types);
            throw $e;
        }
    }

    // ...other wrapped methods...

    private function handleErrors(DBALException $e, string $query = '', ?array $params = null, ?array $types = null): void
    {
        $this->logger->critical(/* ...implementation... */);
    }
}
```

It has been working ok for years (assuming I wrapped all the necessary methods), but as I understand, wrapped Connection classes are deprecated in 2.13 and removed in 3.x. 

I looked into implementing SQLLogger but it looks like that is for debug logging and instrumentation (in 2.x) rather than catching errors?

Is there an error event that I can listen for or some other way to acheive this?

**Comment by derrabus** [comment]
If a custom wrapper class works for you on 2.13, you can continue to use it. On DBAL 3, I recommend implenting a driver middleware instead.

**Comment by RinkAttendant6** [comment]
Would you mind pointing me to the documentation for implementing and integrating a driver middleware? I can't seem to find anything on the site (at least not within the DBAL project)

**Comment by derrabus** [comment]
The documentation is indeed lacking a chapter on middlewares. I can give you some code pointers though. DBAL 3 is shipping with a logger middleware that raplaces the old SQLLogger. That middleware is probably a good source of inspiration:

* https://github.com/doctrine/dbal/blob/3.3.x/src/Logging/Middleware.php
* https://github.com/doctrine/dbal/blob/3.3.x/src/Logging/Driver.php
* https://github.com/doctrine/dbal/blob/3.3.x/src/Logging/Connection.php
* https://github.com/doctrine/dbal/blob/3.3.x/src/Logging/Statement.php

You can add a middleware to your DBAL configuration like this:

```PHP
/** @var \Doctrine\DBAL\Configuration $config */
$config->setMiddlewares([
    new \Doctrine\DBAL\Logging\Middleware(),
    new \Your\Own\Custom\Middleware(),
]);
```

**Comment by morozov** [comment]
I assume the original question has been answered, so the issue can be closed. Documenting the Middleware API is a separate issue.
