### ISSUE TITLE
MYSQL Server has gone away

### ISSUE THREAD

**Issue by Nizari** [doctrine/dbal#5193]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.3.0

#### Summary

When we run https://github.com/barryvdh/laravel-ide-helper the command `DB_DATABASE=our_db_name php artisan ide-helper:models -W -R -vvv` the generation was immensely slower than in `3.2.1`. Afterwards inconsistently it would break either on the 1 or other commands which required a DB connection. When restarting the mac or mysql5.7 service (installed on mac via brew).

#### Previous behaviour

It would quickly generate docblocs based on above command and all would work accordingly.

#### Current behavior

When we run `DB_DATABASE=our_db_name php artisan ide-helper:models -W -R -vvv` (and only this command) all other commands which require DB connection will (randomly) fail like below 

![image](https://user-images.githubusercontent.com/8299892/150501143-87b77913-36c6-41b1-8566-627e49b5a297.png)

#### How to reproduce
Below a piece of our `composer.json` we run Laravel8 with php8 and mysql5.7 on a mac installed with homebrew. 

```console
 "done": [
            "@clean",
            "@check"
        ],
        "check": [
            "@analyze",
            "@test"
        ],
        "clean": [
            "@model-docblocs",
            "@fix",
            "@sniff-fix"
        ],
        "model-docblocs": "DB_DATABASE=boilerplate_local_atabix php artisan ide-helper:models -W -R -vvv",
        "test": "./vendor/bin/phpunit",
        "fix": [
            "php-cs-fixer fix --config ~/Development/.php-cs-fixer.dist.php --cache-file=./vendor/.php-cs-fixer.cache ./app",
            "php-cs-fixer fix --config ~/Development/.php-cs-fixer.dist.php --cache-file=./vendor/.php-cs-fixer.cache ./database",
            "php-cs-fixer fix --config ~/Development/.php-cs-fixer.dist.php --cache-file=./vendor/.php-cs-fixer.cache ./tests"
        ],
        "analyze": "vendor/bin/phpcpd --min-lines=10 --fuzzy ./app && ./vendor/bin/phpstan analyse -c ./phpstan.neon --memory-limit=2G",
        "sniff-fix": "./vendor/bin/phpcbf --standard=slevomat_ruleset.xml --extensions=php --tab-width=4 --report-file=./sniff_report.log -sp app",
```

**Comment by derrabus** [comment]
I'm not familiar with the tool you're using. Can you reproduce the problem using DBAL standalone?

**Comment by greg0ire** [comment]
Sounds related to https://github.com/doctrine/dbal/issues/5195

**Comment by Nizari** [comment]
It's indeed duplicate of #5195 I guess you can close this then :)
