### ISSUE TITLE
Provide Connection::createSchemaManager() in 2.13.x

### ISSUE THREAD

**Issue by trompette** [doctrine/dbal#5198]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Dear maintainers,

It would be nice if all supported versions could provide `Connection::createSchemaManager()`, which means at the moment adding the method in 2.13.x branch.

Doing so would enable projects supporting both 2.13.x and 3.3.x branches by using `Connection::getSchemaManager()` to remove easily a deprecation notice without relying on `method_exists()`.

What do you think?

**Comment by greg0ire** [comment]
We discussed that internally in the last few days, and are planning to publish something about the sunset of DBAL 2, but one of the things that were said is that 

> We accept only the following types of patches for DBAL 2:
>   1. Development dependency updates
>   2. Security fixes
>   3. Improvements to compatibility with PHP 8.1
>   4. Improvements in the upgrade path to DBAL 3
> 
>   Except for dependency updates, there are no known issues of any other kind.

I think your proposal falls under 4. I'm not saying we will do it, but I think we would accept a PR doing so.

**Comment by morozov** [comment]
To me, it's a stretch. `Connection::getSchemaManager()`, although deprecated, will be removed only in `4.0.x` (https://github.com/doctrine/dbal/pull/4518), so in order to support both `2.x` and `3.x`, it is sufficient to use `Connection::getSchemaManager()`.

Otherwise, we may end up migrating all new APIs introduced in `3.x` to `2.x` (e.g. the middlewares).

**Comment by greg0ire** [comment]
Ok, let's not do it then.

**Comment by trompette** [comment]
> in order to support both `2.x` and `3.x`, it is sufficient to use `Connection::getSchemaManager()`

And it is precisely what I use in my library's code.

Now I know where you stand on this kind of issues, and your answer is consistent with mine on https://github.com/trompette/php-feature-toggles/pull/37.
