### ISSUE TITLE
`Connection::getWrappedConnection()` is legit method to get the Driver connection

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5199]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 3.3.0

#### Summary

Thank you for introducing the unified `getNativeConnection()` method.

However the `Doctrine\DBAL\Connection::getWrappedConnection()` is legit method to get the `Doctrine\DBAL\Driver\Connection`.

#### Previous behaviour

returns child/Driver connection

#### Current behavior

`Doctrine\DBAL\Connection::getWrappedConnection()` method must be not deprecated.

the deprecations of `getWrappedConnection()` on Driver connections is IMO good.

#### How to reproduce

see https://github.com/atk4/data/blob/09f141fbecf254df7f4ca6f568637f3d48fc3ea2/src/Persistence/Sql/Connection.php#L239

the usecase requires to return the child/Driver connection, not the lowest/native driver

**Comment by derrabus** [comment]
Can you elaborate why you need access to the driver connection?

**Comment by mvorisek** [comment]
see the atk4/data project I linked

We support creating `Connection` based on string DSN or existing `Connection` or `Driver\Connection`. When `Connection` is passed, we need to extract the wrapped `Driver\Connection`/middleware as we always create own wrapping `Connection`.

**Comment by derrabus** [comment]
And specifying the wrapper class in the configuration would not help you?

https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#wrapper-class

**Comment by morozov** [comment]
The driver connection is an implementation detail of the DBAL. Exposing it via the API will make evolving the API more challenging.
