### ISSUE TITLE
what is causing the requirement for composer-runtime-api ^2 in dbal 3.3.0?

### ISSUE THREAD

**Issue by jonnott** [doctrine/dbal#5207]
Would be good to know, as many server environments (e.g. cPanel/WHM) don't have composer v2+ yet, so this makes things a bit tricky when it comes to deployment.

**Comment by greg0ire** [comment]
How to find out:
![Peek 2022-01-25 23-31](https://user-images.githubusercontent.com/657779/151070721-5258e988-ace5-439a-aeec-ad7ce7a98a04.gif)

So it's #5078
