### ISSUE TITLE
One-To-One relationships with missing unique index causes invalid drop index on database diff

### ISSUE THREAD

**Issue by jackbentley** [doctrine/dbal#5210]
#### Summary

Bug was experienced while using PostgreSQL.

One-to-one relationships are expected to have a unique index.
https://github.com/doctrine/orm/blob/2.11.x/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php#L1893

When running `doctrine:schema:update`, ORM will create an expected table schema with a unique index named `UNIQ_`.
https://github.com/doctrine/orm/blob/2.11.x/lib/Doctrine/ORM/Tools/SchemaTool.php#L745

When generating a table object from current schema, an index is always added for all FKs which is non-unique and with the prefix `IDX_`. This isn't correct for One-To-One relations which will have a unique index prefixed with `UNIQ_`.
https://github.com/doctrine/dbal/blob/3.3.x/src/Schema/Table.php#L578-L592

In my particular case, the table existed, a FK was present for the relation, but an index was not.

#### Current behaviour

This causes a "phantom" drop index. The code thinks the index exists in the database when it does not. The index is not present in the expected schema and is told to be dropped.

```sql
     DROP INDEX IDX_A0BF0B2B40C46575;
     CREATE UNIQUE INDEX UNIQ_A0BF0B2B40C46575 ON foo (bar_id);
```

#### Expected behaviour

The drop index shouldn't be outputted

```sql
     CREATE UNIQUE INDEX UNIQ_A0BF0B2B40C46575 ON foo (bar_id);
```

**Comment by morozov** [comment]
@jackbentley please provide the steps to reproduce the issue.

**Comment by jackbentley** [comment]
@morozov I can only provide steps via Doctrine ORM/Symfony:

1. Create an two entities with a One-To-One relationship between each other
2. Create both tables / Run `doctrine:schema:create`
3. Remove the unique index on the owning side of the relationship. Keep the FK.
4. Run `doctrine:schema:update`

Let me know if you need specific code example or a reproducer repo

**Comment by morozov** [comment]
If you consider it a DBAL bug, it should be reproduced by using only the DBAL API. Otherwise, the bug may be anywhere else.

**Comment by jackbentley** [comment]
@morozov As mentioned in the description, DBAL is making an assumption which is incorrect according to how ORM works:

> When generating a table object from current schema, an index is always added for all FKs which is non-unique and with the prefix IDX_. This isn't correct for One-To-One relations which will have a unique index prefixed with UNIQ_.
> https://github.com/doctrine/dbal/blob/3.3.x/src/Schema/Table.php#L578-L592

Clearly this is an issue in how the two libraries handle FKs. I'll open a bug in ORM and also see if I can get you reproducer code which only uses DBAL...
