### ISSUE TITLE
`Connection::getParams()` is `@internal` now: how to access params?

### ISSUE THREAD

**Issue by dmaicher** [doctrine/dbal#5213]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

Related to https://github.com/doctrine/dbal/issues/3593

#### Summary

I'm currently trying to [fix an issue](https://github.com/dmaicher/doctrine-test-bundle/pull/197#discussion_r792752944) where I need access to the connection params inside an event listener for `postConnect`.

Since `Connection::getParams()` [was marked](https://github.com/doctrine/dbal/pull/4086) `@internal` I currently don't see any other way of accessing data added by the Driver into the connection params.

Would you consider reverting the `@internal` change?

Or maybe as a new feature would it be possible to get access to the params inside the dispatched `postConnect` event `ConnectionEventArgs`?

**Comment by morozov** [comment]
The connection parameters are an implementation detail which we don't want to be part of the public API. See the details in #3593. If there is a logic that depends on connection parameters, they should be explicitly provided to this logic similarly to how they are provided to the connection.

> Would you consider reverting the `@internal` change?

No.

**Comment by dmaicher** [comment]
For now I will try to work around this.
