### ISSUE TITLE
Integer db columns in mysql return as integers instead of string when using php 8.1

### ISSUE THREAD

**Issue by aszenz** [doctrine/dbal#5228]
I'm seeing integer columns in database come out as integers on the php side when using php8.1, using php 8.0 they used to be represented as strings. (using `fetchAllAssociative`, `fetchFirstColumn`)

Seems like pdo mysql made this change
https://www.php.net/manual/en/migration81.incompatible.php#migration81.incompatible.pdo.mysql

> MySQL Driver

> Integers and floats in result sets will now be returned using native PHP types instead of strings when using emulated prepared statements. This matches the behavior of native prepared statements. The previous behaviour can be restored by enabling the PDO::ATTR_STRINGIFY_FETCHES option.

Should dbal restore previous behaviour or not?

**Comment by derrabus** [comment]
It shouldn't.

**Comment by aszenz** [comment]
Okay, should it be considered a backwards compatibility breakage then

**Comment by derrabus** [comment]
Very well, but the page you've linked documents the BC break already, doesn't it. So what is it you suggest we should do here?

**Comment by aszenz** [comment]
The page is about pdo mysql, dbal is an abstraction layer over it, so people using dbal may not know about breaking changes in it.

I think we can document it clearly, and have a way to restore the old behavior somehow if not make it the default

**Comment by derrabus** [comment]
Understood. Let's make this a documentation issue then. Do you want to submit a PR?

**Comment by aszenz** [comment]
Yes, where should we document it

**Comment by derrabus** [comment]
The documentation has a section "Data Retrieval And Manipulation". I think, this is the place where we should explain that DBAL does not perform type conversion on retrieved data and that the result types might differ when switching the database driver or PHP version.

**Comment by aszenz** [comment]
While I added the documentation, it feels really strange to say that an abstraction (dbal) is affected by the underlying implementation (db driver) in a non transparent way.
 
Doesn't this make DBAL a leaky abstraction, where you still need to worry about underlying database and drivers even though the interface doesn't show it explicitly.

Is speed the main reason dbal doesn't type cast the data?

**Comment by derrabus** [comment]
The main reason is probably that we don't feel the DBAL should be responsible for guessing the type of a result column. If any component in the whole chain has access to the necessary information to determine the type of the column, it's the native driver. This is where type cast should happen. If that information is not handed down to us, we can only guess and that will get messy.

That leaves us two options: Either we trust that the driver casts the types properly or we cast everything to string.

Relying on the driver seems like the best option to me. And to be honest: I think it's an improvement that PDO_mysql started to cast integers. Why should we undo this?

**Comment by aszenz** [comment]
I think that's right, the driver is indeed the right layer to cast the data.


> And to be honest: I think it's an improvement that PDO_mysql started to cast integers. Why should we undo this?

It is an improvement indeed, but it also breaks code that assumed string was returned. 
Nevertheless it is good enough to say dbal doesn't try to solve this problem and column types must be considered mixed

**Comment by aszenz** [comment]
Note:

To revert to previous behavior one can set the option in config file

```php
$dbal->option((string) \PDO::ATTR_STRINGIFY_FETCHES, true)
```
