### ISSUE TITLE
Diff command with PostgreSQLPlatform fails when there is a sequence

### ISSUE THREAD

**Issue by maxm86545** [doctrine/dbal#5244]
### Bug Report

|    Q        |   A
|------------ | ------
| Version dbal | 3.3.1
| Version postgres | 13.5

#### Summary

Diff command with **PostgreSQLPlatform** fails when there is a sequence. Note: There is no problem with deprecated **PostgreSQL100Platform** .

#### Current behaviour

When using diff command with actual **PostgreSQLPlatform**, fatal error: An exception occurred while executing a query: `SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "test_id_seq"`

#### How to reproduce

1. Use PostgreSQLPlatform.
2. Have the `test_id_seq` sequence.
3. Run the diff command.

#### Expected behaviour

The diff command with **PostgreSQLPlatform** has the same behavior as with **PostgreSQL100Platform**. This is correct behavior.

#### Possible solution
The fix is here https://github.com/doctrine/dbal/pull/5233

**Comment by morozov** [comment]
@maxm86545 please be more specific about your scenario. The scenario of introspecting schema that includes a sequence is covered at least by the following test: https://github.com/doctrine/dbal/blob/0edd213bd01a4cf79d4ddc5f63622fa6e2149fe0/tests/Functional/Schema/SchemaManagerFunctionalTestCase.php#L127-L151

**Comment by maxm86545** [comment]
Maybe the tests don't show the issue because **PostgreSQL100Platform** is used for Postgres 13.X? Deprecated **PostgreSQL100Platform** don't have a problem. The problem is with actual **PostgreSQLPlatform**.

**Comment by derrabus** [comment]
> Maybe the tests don't show the issue because **PostgreSQL100Platform** is used for Postgres 13.X? Deprecated **PostgreSQL100Platform** don't have a problem. The problem is with actual **PostgreSQLPlatform**.

`PostgreSQL100Platform` is the correct platform class for your version of Postgres. Does DBAL create a `PostgreSQLPlatform` instance in your case? If so, we should rather find out why that happens.

**Comment by maxm86545** [comment]
I am using a custom class extends from **PostgreSQLPlatform**. **PostgreSQL100Platform** is deprecated. In https://github.com/doctrine/dbal/pull/5233 I have moved **getListSequencesSQL** from **PostgreSQL100Platform** to **PostgreSQLPlatform**. This version of getListSequencesSQL is compatible with Postgres 9.4+.

**Comment by morozov** [comment]
You should extend the class from `PostgreSQL100Platform`. The fact the class is deprecated means that it will be removed in the next major release but doesn't mean that you must stop using it now. Unfortunately, it's not always possible to provide a smooth upgrade path.

**Comment by maxm86545** [comment]
I suggest moving **PostgreSQL100Platform::getListSequencesSQL** to **PostgreSQLPlatform::getListSequencesSQL**. It does not break compatibility: https://github.com/doctrine/dbal/pull/5233

**Comment by derrabus** [comment]
If the query works on Postgres 9 already, I agree that we should move it to simplify our code here. But since that won't be a bugfix anymore, let's target 3.4.
