### ISSUE TITLE
unable to change double type of laravel 

### ISSUE THREAD

**Issue by srijanlama** [doctrine/dbal#5258]
### Bug Report

|    Q        |   A
|------------ | ------
| doctrine/dbal |^3.3
| laravel/framework |^8.75

#### Summary
Unable to change the double column type of laravel to nullable() value

#### Current behaviour
```
  $table->unsignedDouble('salary')->nullable()->change()
```

 Unknown column type "double" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType().

**Comment by derrabus** [comment]
Please report this issue to Laravel or try to reproduce it by using the DBAL API only.
