### ISSUE TITLE
DB change detection for enum types in combination with dbal 2.11.1

### ISSUE THREAD

**Issue by bobvandevijver** [doctrine/dbal#5260]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 2.13.7 / 3.2.2 / 3.3.0

#### Summary

Crosspost from doctrine/orm, as I think the issue might actually be here. See https://github.com/doctrine/orm/issues/9494. 

With orm 2.11.1 the database is reported as out of sync for enum based properties, while this does not happen with orm 2.11.0. This happens in combination with dbal 2.13.7, 3.2.2 & 3.3.0. dbal 3.3.1 seems to have fixed this, so this is only valid for the older supported 2.13 release.

#### Current behaviour

The database schema is being reported as not being in sync.

#### How to reproduce

See https://github.com/doctrine/orm/issues/9494. 

#### Expected behaviour

The behaviour as in 3.3.1 and higher, so no changes detected :)

**Comment by greg0ire** [comment]
Bugfixes are no longer supported for DBAL 2, sorry. See https://www.doctrine-project.org/2022/01/22/sunsetting-dbal-2.html for more details.

**Comment by bobvandevijver** [comment]
Hmm, did not know that. I was actually looking for what the maintenance state of 2.13 was, and my conclusion was that it was still supported (looking at the readme and the [website](https://www.doctrine-project.org/projects/dbal.html)). 

Anyways, good reason to make the switch to 3.3 then.
