### ISSUE TITLE
Mysql comparator breaks with table options `collate`

### ISSUE THREAD

**Issue by Matth--** [doctrine/dbal#5265]
### Bug Report/Support Question

|    Q        |   A
|------------ | ------
| Version     | 3.2.0
| MySQL Version | 5.7

#### Summary

The `Doctrine\DBAL\Platforms\MySQ\Comparator` uses the $fromTable tableOptions. When running a Symfony project with the DoctrineBundle with [suggested](https://www.doctrine-project.org/projects/doctrine-bundle/en/2.4/configuration.html) `default_table_options` where we use `collate` instead of `collation` the downCommand will create alter statements for every StringType column because only charset is taken into consideration and not collation (because of the used `collate` option).

#### Current behaviour

Using an ORM generated Schema (as $fromTable) and a MySQL generated Schema (as $toTable) we get a lot of diffs because the `collation` property is not taken into account.

#### How to reproduce

I created [a project](https://github.com/Matth--/dbal-mysql-comparator-bug) with the issue. The `collate` setting has been set in the `config/packages/doctrine.yaml` config file.

The second Migration class in the /migrations folder contains the alter statement that is incorrect.

#### Expected behaviour

This is more of a question/suggestion. The `Doctrine\DBAL\Platforms\AbstractMySQLPlatform::buildTableOptions` method fixes a similar issue by checking if the `collate` options is set and then populates the `collation` option. Should we implement something similar when trying to compare 

##### Suggestion 1

We could change the documentation and prefer collation. 

##### Suggestion 2

In the Mysql/Comparator, check if the `collate` option exists and add it as collation in tableOptions.

```php
public function diffTable(Table $fromTable, Table $toTable)
{
    $tableOptions = $fromTable->getOptions();

    if (array_key_exists('collate', $tableOptions)) {
        $tableOptions['collation'] = $tableOptions['collate'];
    }

    $defaults = array_intersect_key($tableOptions, [
        'charset'   => null,
        'collation' => null,
    ]);

    if ($defaults !== []) {
        $fromTable = clone $fromTable;
        $toTable   = clone $toTable;

        $this->normalizeColumns($fromTable, $defaults);
        $this->normalizeColumns($toTable, $defaults);
    }

    return parent::diffTable($fromTable, $toTable);
}
```

When opting for this solutions, please let me know and I will open a PR 😄  . I already have an implementation with added tests

**Comment by svnldwg** [comment]
We just ran into the same issue today, which breaks backwards compatibility. Affected versions are 3.3.1 and 3.3.2. In 3.3.0 everything works fine. We don't have the `collate` nor the `charset` option set. Our config is very minimal:

```
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
```

**Comment by morozov** [comment]
Have you tried reproducing this same issue with [3.2.2](https://github.com/doctrine/dbal/releases/tag/3.3.2)? There were some relevant changes around schema comparison and the `collate`/`collation` options specifically.

**Comment by Matth--** [comment]
@morozov .The linked project in this issue actually uses dbal 3.3.2. still need to reproduce it with earlier versions.

**Comment by morozov** [comment]
> where we use `collate` instead of `collation`

As of https://github.com/doctrine/dbal/pull/5246, the MySQL platform supports both the `collation` and `collate` options. The latter will be deprecated in `3.4.0` (https://github.com/doctrine/dbal/pull/5249) since it causes schema comparison issues.

Please make sure your code uses the `collation` option consistently.

**Comment by greg0ire** [comment]
See also: https://github.com/doctrine/DoctrineBundle/pull/1471

Prior to that PR, you might end up with both options specified

**Comment by Matth--** [comment]
@morozov @greg0ire should we do the collate to collation mapping then and make sure it here removed in the 4.x release to guarantee BC?

**Comment by greg0ire** [comment]
@Matth-- not sure what you want to do that isn't already done in one package, but feel free to send a PR with what you have in mind, it will make things clearer.

**Comment by morozov** [comment]
> free to send a PR with what you have in mind

Please make sure the issue is reproduced first without additional dependencies. A PR implies that something needs to be fixed but there's no understanding of what's broken.

**Comment by Matth--** [comment]
@greg0ire you're right! The issue is a combo between DoctrineBundle and dbal. I'll close this issue as it is resolved in DoctrineBundle.

**Comment by svnldwg** [comment]
here is the related issue at DoctrineBundle: https://github.com/doctrine/DoctrineBundle/issues/1468
