### ISSUE TITLE
unable to change enum type

### ISSUE THREAD

**Issue by nguyendai0409** [doctrine/dbal#5267]
### Feature Request
  Unknown column type "enum" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to regi
ster all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information.

**Comment by greg0ire** [comment]
Do you mean to use PHP enums? Or MySQL enums?

- https://www.php.net/manual/en/language.types.enumerations.php
- https://www.doctrine-project.org/projects/doctrine-orm/en/2.9/cookbook/mysql-enums.html
