### ISSUE TITLE
Explicit server version in database URL is ignored when using replicas

### ISSUE THREAD

**Issue by mburtscher** [doctrine/dbal#5285]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.0

#### Summary

When using a database URL to configure the connection, an explicit server version is not correctly handled as soon as replicas are used. The explicit server version will be ignored and a database connection is always established to detect the server's version.

#### Current behaviour

A database connection is established to detect the server version although there is an explicit server version configured. Since this is done on application bootstrap in Symfony context, there is no chance to execute any Symfony console commands without having a database connection available.

#### How to reproduce

Tested in the context of a Symfony application with an environment variable `DATABASE_URL` with the value `postgresql://ci:ci@ci:5432/ci?serverVersion=13.4`.

**Symfony configuration (working as expected)**

```php
$config->dbal([
    'connections' => [
        'default' => [
            'url' => '%env(resolve:DATABASE_URL)%',
            'charset' => 'UTF8',
            'driver' => 'pdo_pgsql',
            //'replicas' => ['reader' => ['url' => '%env(resolve:DATABASE_URL)%', 'charset' => 'UTF8']],
        ],
    ],
]);
```

**Symfony configuration (explicit server version ignored)**

```php
$config->dbal([
    'connections' => [
        'default' => [
            'url' => '%env(resolve:DATABASE_URL)%',
            'charset' => 'UTF8',
            'driver' => 'pdo_pgsql',
            'replicas' => ['reader' => ['url' => '%env(resolve:DATABASE_URL)%', 'charset' => 'UTF8']],
        ],
    ],
]);
```

#### Further information

When adding a `dump($this->params);` to [`Connection::getDatabasePlatformVersion()`](https://github.com/doctrine/dbal/blob/3.3.x/src/Connection.php#L389) one can see the problem:

**Working as expected**

```
array:11 [
  "url" => "postgresql://ci:ci@ci:5432/ci?serverVersion=13.4"
  "charset" => "UTF8"
  "driver" => "pdo_pgsql"
  "host" => "ci"
  "port" => 5432
  "user" => "ci"
  "password" => "ci"
  "driverOptions" => []
  "defaultTableOptions" => []
  "dbname" => "ci"
  "serverVersion" => "13.4"
]
```

**Explicit server version ignored**

```
array:8 [
  "driver" => "pdo_pgsql"
  "slaves" => []
  "driverOptions" => []
  "replica" => array:1 [
    "reader" => array:9 [
      "url" => "postgresql://ci:ci@ci:5432/ci?serverVersion=13.4"
      "charset" => "UTF8"
      "host" => "ci"
      "port" => 5432
      "user" => "ci"
      "password" => "ci"
      "driver" => "pdo_pgsql"
      "dbname" => "ci"
      "serverVersion" => "13.4"
    ]
  ]
  "defaultTableOptions" => []
  "primary" => array:9 [
    "url" => "postgresql://ci:ci@ci:5432/ci?serverVersion=13.4"
    "charset" => "UTF8"
    "host" => "ci"
    "port" => 5432
    "user" => "ci"
    "password" => "ci"
    "driver" => "pdo_pgsql"
    "dbname" => "ci"
    "serverVersion" => "13.4"
  ]
  "wrapperClass" => "Doctrine\DBAL\Connections\PrimaryReadReplicaConnection"
  "charset" => "utf8"
]
```

The code on [line 387](https://github.com/doctrine/dbal/blob/3.3.x/src/Connection.php#L397) expects a `serverVersion` key being available in the parameter root but it isn't for the example using replicas.

**I'll try to provide a sample repository / test case / fix!**

#### Expected behaviour

It is expected that no database connection is established to detect the server version when the app is bootstrapped.

**Comment by derrabus** [comment]
Related to #4900?

**Comment by mburtscher** [comment]
Yes, you're right @derrabus. Thanks for pointing me there.
