### ISSUE TITLE
OFFSET is not listed as a keyword for MariaDB 

### ISSUE THREAD

**Issue by yurikuzn** [doctrine/dbal#5291]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.2

#### Summary

`OFFSET` is a reserved word as of MariaDB 10.6 https://mariadb.com/kb/en/reserved-words/.

We run into this issue being on the version 3.1.5. After checking [the source code](https://github.com/doctrine/dbal/blob/3.3.2/src/Platforms/Keywords/MariaDBKeywords.php) I found out that it's not fixed yet.

#### Current behaviour

`offset` column identifier is not quoted in a generated SQL.

#### How to reproduce

Create a table with a column named `offset`.

#### Expected behaviour

`offset` should be quoted.

**Comment by derrabus** [comment]
Do you want to work on a PR?
