### ISSUE TITLE
Custom Driver Options in DSN URL

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5293]
This is a question.

Based on https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/configuration.html#custom-driver-options `driverOptions` can be used to specify driver specific options.

For MSSQL I need to specify `TrustServerCertificate=1`. How can I specify such option in DSN URL so it is parsed correctly to `driverOptions` array?

**Comment by morozov** [comment]
Something like this may work according to `DriverManagerTest::testDatabaseUrl()`:
```php
'Driver Options' => [
    [
        'url' => 'sqlsrv://localhost/foo?driverOptions[TrustServerCertificate]=1',
    ],
    [
        'driverOptions' => [
            'TrustServerCertificate' => 1,
        ],
    ],
],
```

**Comment by mvorisek** [comment]
Works like a charm, thank you!
