### ISSUE TITLE
Alter comment in custom type

### ISSUE THREAD

**Issue by cyril-barragan** [doctrine/dbal#5309]
|    Q        |   A
|------------ | -----
| Version     | 3.3.2

### Support Question

Hi, I can't figure how to change the comment content generated by doctrine in a custom type.

What I am trying to achieve is to define one type "EnumType" once, then to use the "enumType" property to link a Php enum.

eg:     #[ORM\Column(type: EnumType::class, enumType: UserType::class)]

I want to use the comment section to store the enumType

I tried the following :
* Setting the comment as the result of getSQLDeclaration function ""enum('" . implode("', '", array_keys($this->values)) . "') COMMENT $comment"" => this generates a new diff each time, even if nothing has changed.
* Setting the comment into the entity field '    #[ORM\Column(type: EnumType::class, enumType: TimeslotType::class, options: ['comment' => 'test'])]' => this works but I'm trying to avoid the burden of configuring this manually every time.

Is there any way to achieve this ? Thanks

**Comment by michnovka** [comment]
Hi,

what you are trying to achieve is provided e.g. by https://github.com/Elao/PhpEnums

the way enum support is implemented natively in doctrine now is via string type extension (which checks the enumType option). So you cannot use  #[ORM\Column(type: EnumType::class, enumType: TimeslotType::class)]`

I would suggest you check out the PhpEnums repo.

Alternatively, your type class needs to have the `requiresSQLCommentHint()` function returning true. You cannot specify the comment itself, it is handled by Doctrine.

You can also check my[ StackOverflow question](https://stackoverflow.com/questions/71312186/how-to-use-actual-enum-type-in-symfony-doctrine) where I wanted to sum up how to do this kind of stuff with your own code.

I think @morozov this issue can be closed
