### ISSUE TITLE
Empty results with parameter substitution

### ISSUE THREAD

**Issue by 1ed** [doctrine/dbal#5312]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.2

PHP 8.1 and MySQL 5.7.36-1debian10 

#### Summary

If I create the following native query

```php
        $idsForDistance = $this->_em->getConnection()
            ->createQueryBuilder()
            ->select('id, ST_Distance_Sphere(point(JSON_EXTRACT(coordinates, "$.lon"), JSON_EXTRACT(coordinates, "$.lat")), point(:lon, :lat)) as distance')
            ->from('location')
            ->andWhere('type = :type')
            ->andWhere('polygon IS NOT NULL')
            ->andWhere('JSON_EXTRACT(coordinates, "$.lon") < :east')
            ->andWhere('JSON_EXTRACT(coordinates, "$.lon") > :west')
            ->andWhere('JSON_EXTRACT(coordinates, "$.lat") < :north')
            ->andWhere('JSON_EXTRACT(coordinates, "$.lat") > :south')
            ->orderBy('distance', 'ASC')
            ->setParameter('type', LocationType::CITY->value)
            ->setParameter('lon', $location->getCoordinates()->getLongitude())
            ->setParameter('lat', $location->getCoordinates()->getLatitude())
            ->setParameter('east', $bb->getEast())
            ->setParameter('west', $bb->getWest())
            ->setParameter('north', $bb->getNorth())
            ->setParameter('south', $bb->getSouth())
            ->fetchAllAssociative();
```
the same empty results with the following:
```php
       $idsForDistance = $this->_em->getConnection()->fetchFirstColumn(
            'SELECT id, ST_Distance_Sphere(point(JSON_EXTRACT(coordinates, "$.lon"), JSON_EXTRACT(coordinates, "$.lat")), point(:lon, :lat)) as distance FROM location WHERE (type = :type) AND (polygon IS NOT NULL) AND (JSON_EXTRACT(coordinates, "$.lon") < :east) AND (JSON_EXTRACT(coordinates, "$.lon") > :west) AND (JSON_EXTRACT(coordinates, "$.lat") < :north) AND (JSON_EXTRACT(coordinates, "$.lat") > :south) ORDER BY distance ASC',
            [
                'type' => LocationType::CITY->value,
                'lon' => $location->getCoordinates()->getLongitude(),
                'lat' => $location->getCoordinates()->getLatitude(),
                'east' => $bb->getEast(),
                'west' => $bb->getWest(),
                'north' => $bb->getNorth(),
                'south' => $bb->getSouth(),
            ]
        );
```
but if I run the same query like (the parameters are inlined by the symfony profiler and changed `type = 'city'` to `type = "city"` ):
```php
        $idsForDistance = $this->_em->getConnection()->fetchFirstColumn(
            'SELECT id, ST_Distance_Sphere(point(JSON_EXTRACT(coordinates, "$.lon"), JSON_EXTRACT(coordinates, "$.lat")), point(17.558728, 47.105658)) as distance FROM location WHERE (type = "city") AND (polygon IS NOT NULL) AND (JSON_EXTRACT(coordinates, "$.lon") < 17.955110571764) AND (JSON_EXTRACT(coordinates, "$.lon") > 17.162345428236) AND (JSON_EXTRACT(coordinates, "$.lat") < 47.3754540583) AND (JSON_EXTRACT(coordinates, "$.lat") > 46.8358619417) ORDER BY distance ASC;'
        );
```
I got results. And if I remove the 

```php
            ->andWhere('JSON_EXTRACT(coordinates, "$.lon") < :east')
            ->andWhere('JSON_EXTRACT(coordinates, "$.lon") > :west')
            ->andWhere('JSON_EXTRACT(coordinates, "$.lat") < :north')
            ->andWhere('JSON_EXTRACT(coordinates, "$.lat") > :south')
            ->setParameter('east', $bb->getEast())
            ->setParameter('west', $bb->getWest())
            ->setParameter('north', $bb->getNorth())
            ->setParameter('south', $bb->getSouth())
```
part there are also results. 

#### Current behaviour

There are no results returned.

#### How to reproduce

Maybe I'm doting something wrong, but if it seems a bug for you too I can provide additional information or work on a failing test.

#### Expected behaviour

There are results returned.

**Comment by morozov** [comment]
@1ed so far there's no information for us to reproduce this issue. The issue description neither contains the data being queried, nor the parameters used in the queries.

Why do you believe the bug is in the DBAL?

**Comment by 1ed** [comment]
The 3rd example contains all the parameters, that is the query the DBAL produces, if I use that query as is (except changing `type = 'city'` to `type = "city"`) I get results. I suspect bug should be somewhere near param parsing or maybe escaping, but I'm not sure, maybe I just missing something. If you could give me some pointers where should I look, maybe I could debug further, or write a failing test.

**Comment by morozov** [comment]
You should inspect the resulting query and the parameter before it hits the driver. E.g.:
1. https://github.com/doctrine/dbal/blob/7648e9a8c0cae5481c1a8edc190755d3fe103fec/src/Driver/Mysqli/Connection.php#L59
2. https://github.com/doctrine/dbal/blob/4afa4917d6bf3898ef62d49accc708a573b21c6b/src/Driver/Mysqli/Statement.php#L162

And see if the SQL and the parameters passed to the driver correspond to what you expect to be passed.

**Comment by 1ed** [comment]
Thanks! I didn't find the issue yet, but in the meantime created a reproducer in a Symfony project.

If you want to try:
```
git clone git@github.com:1ed/dbal-5312.git
docker-compose up
symfony console doc:dat:cre
symfony console doctrine:migrations:migrate
symfony serve
```
And go to `https://127.0.0.1:8000` and see the debug toolbar.
It shows an empty array, but it should be [228, 221]
If you copy the runnable query into an sql console, it shows the correct results

```
symfony console doc:que:sql 'SELECT id, ST_Distance_Sphere(point(JSON_EXTRACT(coordinates, "$.lon"), JSON_EXTRACT(coordinates, "$.lat")), point(17.558728, 47.105658)) as distance FROM location WHERE (JSON_EXTRACT(coordinates, "$.lon") < 17.955110571764) AND (JSON_EXTRACT(coordinates, "$.lon") > 17.162345428236) AND (JSON_EXTRACT(coordinates, "$.lat") < 47.3754540583) AND (JSON_EXTRACT(coordinates, "$.lat") > 46.8358619417) ORDER BY distance ASC;'
```

**Comment by 1ed** [comment]
Parameters without explicit type are treated as strings? Maybe it's related to that. If I write

```php
            ->andWhere('JSON_EXTRACT(coordinates, "$.lon") < ' . $bb['east'])
            ->andWhere('JSON_EXTRACT(coordinates, "$.lon") > ' . $bb['west'])
            ->andWhere('JSON_EXTRACT(coordinates, "$.lat") < ' . $bb['north'])
            ->andWhere('JSON_EXTRACT(coordinates, "$.lat") > ' . $bb['south'])
```
and remove the bindings it works.

**Comment by morozov** [comment]
@1ed please reproduce your issue without using dependencies like Docker, the ORM, or Symfony CLI. See https://github.com/doctrine/dbal/issues/2663#issuecomment-905763017 for example.

**Comment by morozov** [comment]
Closing as not reproducible.
