### ISSUE TITLE
executeStatement returning int|string in phpdoc but it can return only int

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [doctrine/dbal#5318]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.3

#### Summary

`Connection::exectureStatement` (https://github.com/doctrine/dbal/blob/3.3.x/src/Connection.php#L1128) declares that it can return `int|string` but 2 return statements (https://github.com/doctrine/dbal/blob/3.3.x/src/Connection.php#L1128 and https://github.com/doctrine/dbal/blob/3.3.x/src/Connection.php#L1160) return only `int`.

#### How to reproduce

n/a

#### Expected behaviour

It should return only `int`

**Comment by morozov** [comment]
A statement may have to return a string if its numeric value is greater than `PHP_INT_MAX`. All methods returning the number of affected rows should return `int|string`. See https://github.com/doctrine/dbal/pull/5317#issuecomment-1064249810.
