### ISSUE TITLE
Charset or Collation are ignored during migration

### ISSUE THREAD

**Issue by surikman** [doctrine/dbal#5322]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.*

#### Summary

After upgrade dbal from 2.x to 3.3.x doctrine migration generates `down` a lot of changes about `COLLATE` because in Comparatar charset & collation is null 
https://github.com/doctrine/dbal/blob/dfdb5fb2b2230237bf46761140ce9b2dd4edea39/src/Platforms/MySQL/Comparator.php#L34-L37

#### Current behaviour

We have a table:
```sql
CREATE TABLE IF NOT EXISTS `test` (`name` VARCHAR(255) NOT NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\';');
```

If I run `migrations:diff`:
- `up` is empty
- `down` contains changes for `name` column 

```sql
ALTER TABLE test CHANGE name name VARCHAR(255) NOT NULL COLLATE `utf8mb4_unicode_ci`
```

#### How to reproduce

```php
$connection = DriverManager::getConnection(['url' => 'mysql://root:root@127.0.0.1:3306/test?serverVersion=8.0']);
$connection->executeQuery('CREATE TABLE IF NOT EXISTS `test` (`name` VARCHAR(255) NOT NULL) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\';');
$schemaManager = $connection->createSchemaManager();
$fromSchema = $schemaManager->createSchema();

$toSchema = new Schema([], [], $schemaManager->createSchemaConfig());
$toSchema->createTable('test')->addColumn(
    'name',
    Types::STRING,
    ['length' => 255, 'notnull' => true, 'platformOptions' => ['version' => false]]
);

$up = $schemaManager->createComparator()->compareSchemas($fromSchema, $toSchema);
$diffSql = $up->toSql($connection->getDatabasePlatform());
assert(count($diffSql) === 0);


$down = $schemaManager->createComparator()->compareSchemas($toSchema, $fromSchema);
$diffSql = $down->toSql($connection->getDatabasePlatform());
assert(count($diffSql) === 0);
```

#### Expected behaviour

Diff of UP & DOWN should be empty -> nothing to migrate

I created this issue from https://github.com/doctrine/dbal/issues/5321#issuecomment-1069705080

**Comment by stefgodin** [comment]
I have the same problem with **v3.4.1** of doctrine/migrations.
The problem is resolved when forcing installation of **v3.3.2** of doctrine/migrations.

**Comment by surikman** [comment]
@Stefmachine yes, You are right. I had `doctrine/migrations:3.4.1` and I tried to install `3.3.2` and it works.

Ok It means, this is bug of `doctrine/migrations` or `doctrine/dbal` lib? 🤔 

I think this issue comes from https://github.com/doctrine/migrations/pull/1229

**Comment by stefgodin** [comment]
When I run the composer update command upon switching from 3.4.1 to 3.3.2 this shows up
![image](https://user-images.githubusercontent.com/32845418/158823624-7dad24ac-2b22-4b2c-8209-01109de09159.png)

Which seems to imply that only doctrine/migrations is updated and not doctrine/dbal.
Unless composer/package-versions-deprecated causes a problem but that is very unlikely.

**Comment by morozov** [comment]
@surikman please check the patch from https://github.com/doctrine/dbal/pull/5326. As reported in the description, your issue is not reproducible with this patch.

**Comment by surikman** [comment]
> @surikman please check the patch from #5326. As reported in the description, your issue is not reproducible with this patch.

Thanks @morozov, now on branch `3.3.x-dev` it works properly!
