### ISSUE TITLE
Incompatibility after Postgres 9 deprecation

### ISSUE THREAD

**Issue by astronom** [doctrine/dbal#5324]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.0+

#### Summary
After deprecate [Deprecate support for Postgres 9](https://github.com/doctrine/dbal/pull/5060) seems missed to change assert in https://github.com/doctrine/dbal/blob/82331b861727c15b1f457ef05a8729e508e7ead5/src/Driver/AbstractPostgreSQLDriver.php#L69
So if I extends PostgreSql100Platform I get deprecation notice, if I extends PostgreSQLPlatform I catch assert error. But PostgreSql94Platform nothing overwrites from base class

#### Expected behaviour

Change assert to PostgreSQLPlatform

**Comment by derrabus** [comment]
You should avoid extending those platform classes, really. But if you have to extend them, extending `PostgreSql100Platform` would be the right thing to do despite the deprecation if that class of yours is meant for Postgres 10 and above.

**Comment by astronom** [comment]
We extending platform class to add milliseconds to DateTime objects and db column declaration, because doctrine does not provide them out of the box. If extends PostgreSql100Platform, I should increase max indirect deprecation counter in my code since the last lib release. I try to investigate another way and find assert that can be safely changed to `assert($platform instanceof PostgreSQLPlatform);`.

**Comment by morozov** [comment]
The assertion indeed needs to be changed to `assert($platform instanceof PostgreSQLPlatform)`.
