### ISSUE TITLE
Escaping columns name in Connection.insert method

### ISSUE THREAD

**Issue by adrienpayen** [doctrine/dbal#5350]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.4

#### Summary

Using Connection.insert method I keep having the following error
`
An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'default, editable,...' at line 1
`

One my column is in fact a reserved word (`default`). 

So my question is **shouldn't we always escape column names in the insert method** or **provide a way to do so ?** 

If so I'll be happy to help.

#### How to reproduce

```php
$data = [
    'default' => 'value'
];

$this->connection->insert('my_table', $data);
```

**Comment by derrabus** [comment]
The method works as documented.

https://github.com/doctrine/dbal/blob/719663b15983278227669c8595151586a2ff3327/src/Connection.php#L729

> shouldn't we always escape column names in the insert method

Maybe, but that would be a breaking change. The method would essentially do somethings else than it does right now.

> or provide a way to do so 

There is `Connection::quoteIdentifier()` for that matter.

**Comment by adrienpayen** [comment]
I agree, that would be a breaking change, so maybe this should only be optional (?). Adding a fourth optional argument to the `insert()` method that allow escaping table and/or columns name ? Using the method you provided to do so `Connection::quoteIdentifier()`

And I am curious, what is the actual reason they are not safe for user-input ?

**Comment by derrabus** [comment]
> Adding a fourth optional argument to the `insert()` method that allow escaping table and/or columns name ?

Nah, adding a boolean flag to a method that already has so many parameters sounds smelly. *If* we wanted to do that, I'd make this a separate method instead, I guess.

> And I am curious, what is the actual reason they are not safe for user-input ?

Tables and columns don't necessarily need to be identifiers, those could also be expressions depending on the database engine you use. Escaping everything would disallow using those.

**Comment by morozov** [comment]
I wouldn't add a new method that would automatically quote identifiers since the quoting logic itself is flawed, to say the least (see the examples in https://github.com/doctrine/dbal/issues/4357 comments).

I believe until a new API for proper handling of identifiers is introduced, we should refrain from building new by-design broken APIs. Quoting identifiers in the userland before passing them to the DBAL would be trivial.
