### ISSUE TITLE
[MySQL] Deprecate automatically setting collation to `{charset}_unicode_ci` as it can produce invalid collations

### ISSUE THREAD

**Issue by ruudk** [doctrine/dbal#5353]
While working on https://github.com/doctrine/orm/pull/9636 I noticed that the AbstractMySQLPlatform does something really weird.

When you define `charset` for the Table options, without defining the `collation`, it will automatically construct the `collation` like this:
https://github.com/doctrine/dbal/blob/719663b15983278227669c8595151586a2ff3327/src/Platforms/AbstractMySQLPlatform.php#L459-L462

This is naive, as it assumes that there is always a `_unicode_ci` for every given `charset`. For exampe, If I set the `charset` to `ascii` it tries to create `ascii_unicode_ci` which doesn't exist.

I think a deprecation should be triggered when `charset` is defined without specifying the `collation`. It teaches people to define both.

I also think that this is weird:
https://github.com/doctrine/dbal/blob/719663b15983278227669c8595151586a2ff3327/src/Platforms/AbstractMySQLPlatform.php#L448-L451

It uses the default `utf8` alias which points to `utf8mb3` which is not compatible with UTF8. It should be `utf8mb4`. So maybe instead of setting this default, not do it, and or trigger a deprecation.

References:
- https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8.html

/cc @greg0ire

**Comment by morozov** [comment]
The defaults will be removed in 4.0 (https://github.com/doctrine/dbal/pull/4644).

> I think a deprecation should be triggered when charset is defined without specifying the collation. It teaches people to define both.

That's arguable. Since MySQL doesn't force specifying the collation alongside the charset, the DBAL shouldn't either.
