### ISSUE TITLE
MYSQLI_OPT_READ_TIMEOUT is not available in PHP 7.1 / breaks 2.11+

### ISSUE THREAD

**Issue by MisterDuval** [doctrine/dbal#5358]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.11 / 2.12

#### Summary

MYSQLI_OPT_READ_TIMEOUT is not available in PHP 7.1
It is used in doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliConnection.php

#### Current behavior

index not found and breaks code

#### How to reproduce

Install PHP 7.1, test a MySQL connexion

#### Expected behavior

As the 2.11/2.12 versions of Doctrine supports PHP 7.1, you shouldn't use MYSQLI_OPT_READ_TIMEOUT as it is only available on PHP 7.2 https://www.php.net/manual/en/mysqli.options.php

You can use instead :
```
<?php
if (!defined('MYSQLI_OPT_READ_TIMEOUT')) {
    define ('MYSQLI_OPT_READ_TIMEOUT', 11);
}
?>
```

**Comment by derrabus** [comment]
I'm transferring the issue because it affects the DBAL, not the ORM.

**Comment by derrabus** [comment]
You are correct. Unfortunately, you are using DBAL 2 and that version is EOL as per our announcement: https://www.doctrine-project.org/2022/01/22/sunsetting-dbal-2.html

This means, we won't fix this bug anymore. So the solution for you would be to either upgrade to PHP 7.2+ or to paste that workaround of yours into your application bootstrap.
