### ISSUE TITLE
Dropping Default Contraints with SQLServer doesn't work

### ISSUE THREAD

**Issue by Pixdigit** [doctrine/dbal#5413]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.4

#### Summary

When dropping a default constraint, DBAL generates a random name for the constaint to be dropped, which obviously doesn't work. This happens in `ChangeColumn.php`. This calls `getAlterTableSQL` in `compile`. If it is determined that the default constraint has to be removed then `getAlterTableDropDefaultConstraintClause` (In SQLServerPlatform.php) is called which calls `generateDefaultConstraintName`. This *generates* a random name for a default constraint, instead of finding it.

I stumbled upon this through laravel which ideally would use it's own [compileDropDefaultConstraint](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Database/Schema/Grammars/SqlServerGrammar.php#L234). That (SQL) code works and could also be used in DBAL as it's MIT Licensed. However as a query on the `sys.columns` table is needed, a simple `"ALTER TABLE "  . $code`  won't do the trick.

#### Current behaviour

Dropping default constraints on SQL Server fails with "Constraint does not exist".

#### How to reproduce

Create a Database/Table/User on an SQL Server. The Table should have a column with a default value. Try to remove the default constraint via `ChangeColumn`.

#### Expected behaviour

The default constraint is removed.

**Comment by Pixdigit** [comment]
See also https://github.com/laravel/framework/issues/37419

**Comment by morozov** [comment]
@Pixdigit how could one reproduce the issue? Here's what I tried:
```php
function printDefault(Connection $connection): void {
    var_dump($connection->fetchOne("SELECT COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'test' AND COLUMN_NAME = 'test'"));
}

$schema = new Schema();
$table = $schema->createTable('test');
$table->addColumn('test', 'integer', ['default' => 1]);

$sm = $connection->createSchemaManager();
$sm->migrateSchema($schema);
printDefault($connection);
// string(5) "((1))"

$table->getColumn('test')->setDefault(null);
$sm->migrateSchema($schema);
printDefault($connection);
// null
```
The first migration will execute the following statements:
```sql
ALTER TABLE test ALTER COLUMN test INT NOT NULL;
ALTER TABLE test ADD CONSTRAINT DF_D87F7E0C_D87F7E0C DEFAULT 1 FOR test;
```

The second migration will execute the following:
```sql
ALTER TABLE test DROP CONSTRAINT DF_D87F7E0C_D87F7E0C;
ALTER TABLE test ALTER COLUMN test INT NOT NULL;
```

So the constraint names match.

**Comment by Pixdigit** [comment]
Well then it appears to be a problem with how laravel used DBAL. Thank you for your effort.
