### ISSUE TITLE
MySQL / MariaDB: 1170 BLOB/TEXT column '<any_name>' used in key specification without a key length

### ISSUE THREAD

**Issue by aheissenberger** [doctrine/dbal#5421]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.6

#### Summary

If one of the columns used for the primary key have no length (e.g. TEXT) the generated SQL for MySQL / MariaDB will fail with this error message:
`SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'document_id' used in key specification without a key length`

#### Current behaviour

Columns with length greater than allowed will break the sql execution.

#### How to reproduce

```php
$sm = $this->getConnection()->getSchemaManager();
$table = new Table($this->getTableName());

$table->addColumn('collection', Types::STRING);
$table->addColumn('document_id', Types::TEXT);

$table->addColumn('document_type', Types::TEXT);
$table->addColumn('document', Types::JSON);

$table->setPrimaryKey(['collection', 'document_id']);

$sm->createTable($table);
```

```sql
CREATE TABLE ecotone_document_store (
    collection VARCHAR(255) NOT NULL,
    document_id LONGTEXT NOT NULL,
    document_type LONGTEXT NOT NULL,
    document LONGTEXT NOT NULL COMMENT '(DC2Type:json)',
    PRIMARY KEY(collection, document_id)
) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB
```

#### Expected behaviour

`document_id` needs to include a length value which is either based on a global value per platform/engine or can be provided as an option when setting the primary key.

```sql
PRIMARY KEY(collection, document_id(255))
```

**correct sql**
```sql
CREATE TABLE ecotone_document_store (
    collection VARCHAR(255) NOT NULL,
    document_id LONGTEXT NOT NULL,
    document_type LONGTEXT NOT NULL,
    document LONGTEXT NOT NULL COMMENT '(DC2Type:json)',
    PRIMARY KEY(collection, document_id(255))
) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB
```

**allow to set options when with `setPrimaryKey `**

```php
$table->setPrimaryKey(['collection', 'document_id'],null,["lengths"=>[255,255]);
```

##### temp fix

```php
$columnNames=['collection', 'document_id'];
if ($sm->getDatabasePlatform()->getName()==='mysql') {
    $table->addIndex($columnNames,null,[],["lengths"=>[255,255]]);
    foreach ($columnNames as $columnName) {
        $column = $table->getColumn($columnName);
        $column->setNotnull(true);
    }
} else {
   $table->setPrimaryKey($columnNames);
}
```

#### MySQL Docs

https://dev.mysql.com/doc/refman/5.6/en/column-indexes.html

**Comment by morozov** [comment]
What's the practical use case when a text column should be part of the primary key? While it's in theory possible, I don't see much value in adding the support for that in the DBAL. As pointed out in https://github.com/ecotoneframework/dbal/pull/1#issuecomment-1144021631, `document_id` being a blob column is a bug.

**Comment by aheissenberger** [comment]
You are right, the use case I had is closed :-) 

But there are use cases as otherwise MySQL would not offer the possibility to add TEXT and BLOB to an index.
I hope my fix will help other people with less detail know how to avoid the mysql error.

**Comment by morozov** [comment]
@aheissenberger, what is the practical use case when a text column should be part of the primary key?

As a developer, why would you _want_ to use a text column as part of the primary key? Right now, it seems like the DBAL prevents this from happening which is a good thing because most likely it's a mistake as in your case.

**Comment by aheissenberger** [comment]
### 1. Use Case - VARCHAR

The need to set the INDEX length to a "VARCHAR" on primary keys exists too:
```sql
CREATE TABLE type_varchar (
  `collection` varchar(800) COLLATE utf8mb3_unicode_ci NOT NULL,
  `document_id` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `document_type` longtext COLLATE utf8mb3_unicode_ci NOT NULL,
  `document` longtext COLLATE utf8mb3_unicode_ci NOT NULL COMMENT '(DC2Type:json)',
  PRIMARY KEY (collection,document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
```

The result on a default MariaDB instance is this error: 
`Specified key was too long; max key length is 3072 bytes`

You will need to define a length for the primary key column:
`PRIMARY KEY (collection(700),document_id)`

Here is a test to check that with a reduced index the primary key is still not allowing duplicated content:
```sql
INSERT INTO `type_varchar` (`collection`, `document_id`, `document_type`, `document`)
VALUES
	(REPEAT('1',800), '1', 't1', 'doc1');
INSERT INTO `type_varchar` (`collection`, `document_id`, `document_type`, `document`)
VALUES
	(REPEAT('1',800), '1', 't1', 'doc1');
```

the result is the expected error:
`Duplicate entry '1111111111111111111111111111111111111111111111111111111111111...' for key 'PRIMARY'`

Based on your feedback I would remove from my PR the automatic fix for TextType and BlobType but keep the extension of the `setPrimaryKey`methode to allow to optional define the individual length of the columns used for the index.

### 2. Use Case - Index BTREE Size in Memory or Disk

Datasets with many rows might opt to reduce the length of the index of column of any datatype to reduce the overall size of the final BTREE.

This table will still hold all the rules for a primary key and will work with UPSERT but the index is only a fraction:
```sql
CREATE TABLE type_varchar (
  `collection` varchar(800) COLLATE utf8mb3_unicode_ci NOT NULL,
  `document_id` varchar(255) COLLATE utf8mb3_unicode_ci NOT NULL,
  `document_type` longtext COLLATE utf8mb3_unicode_ci NOT NULL,
  `document` longtext COLLATE utf8mb3_unicode_ci NOT NULL COMMENT '(DC2Type:json)',
  PRIMARY KEY (collection(1),document_id(1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;
```

### 3. Use Case - Implementation Differences between TEXT and VARCHAR

MySQL imposes a limit of 65,535 bytes for the [max size of each row](https://dev.mysql.com/doc/refman/8.0/en/column-count-limit.html#row-size-limits). The size of a VARCHAR column is counted towards the maximum row size, while TEXT columns are assumed to be storing their data by reference so they only need 9-12 bytes. That means even if the "theoretical" max size of your VARCHAR field is 65,535 characters you won't be able to achieve that if you have more than one column in your table.

**Comment by morozov** [comment]
If you're using only a part of the column in the primary key, it means that the column contains two values: the one that identifies the row (and must be unique) and some remainder. If that's the case, the proper approach would be to create two columns.
