### ISSUE TITLE
Droptable() method should only drop table if the tables exists

### ISSUE THREAD

**Issue by sadiqk2** [doctrine/dbal#5468]
dropandcreatetable() has been depreciated,

Now droptable() and createtable() , 
Although behaviour is now bit different, 
I want droptable method To drop table only if the table exists,

So that i can make use of both methods properly.... If the table is not created and i use drop method my services breaks down

I think we should include one more method dropIfTableExists()

**Comment by morozov** [comment]
If you don't care if the table being dropped exists, you can use `dropTable()` and suppress the `DatabaseObjectNotFoundException`:

https://github.com/doctrine/dbal/blob/c0122118c54a6ea7af01c0a2c2bd9f07721e477b/tests/FunctionalTestCase.php#L85-L88

**Comment by sadiqk2** [comment]
@morozov , thanks
 I have suppressed the exception using try and catch, but we should have one method that check if the table exits, 

I can open pr for that?

**Comment by morozov** [comment]
Personally, I don't believe this would be a good addition. We already had a similar discussion in the past and decided not to implement such an API (https://github.com/doctrine/dbal/pull/3535#issuecomment-488075199).

The schema management logic in the DBAL is driven by the desired and the actual schemas and the difference between them. The "if exists" question is answered by the schema introspection, so there's no need for the "if exist" clause at the time when a table is being dropped.

If an application manages its schema using some different principles, it can suppress the exception.

**Comment by sadiqk2** [comment]
got it ,
Thanks
