### ISSUE TITLE
Issue connecting PDO Mysql primary and replica database with SSL connection

### ISSUE THREAD

**Issue by hirakch** [doctrine/dbal#5472]
When connecting primary and replica database with SSL connection, the driver options remain empty for the replica database. 

> Error: An exception occurred in driver: SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry.

- Doctrine do not allow to provide "options" in the replica but also not includes primary options while connecting
- The driver options remains empty for replica as the replica is a nested with multiple replicas the driver cannot be retrieved directly from the params
- add the following code in connectTo function in `Doctrine/DBAL/Connections/PrimaryReadReplicaConnection.php`

```
if($connectionName == 'replica') {
    $driverOptions = $params['replica'][array_rand($params['replica'])]['driverOptions'] ?? [];
}
```

Possible Solution: change the connectTo function to check if it is replica database, get the driver options form the params of replica.

```
   /**
     * Connects to a specific connection.
     *
     * @param string $connectionName
     *
     * @return DriverConnection
     */
    protected function connectTo($connectionName)
    {
        $params = $this->getParams();

        $driverOptions = $params['driverOptions'] ?? [];

        if($connectionName == 'replica') {
                $driverOptions = $params['replica'][array_rand($params['replica'])]['driverOptions'] ?? [];
        }

        $connectionParams = $this->chooseConnectionConfiguration($connectionName, $params);
        $user     = $connectionParams['user'] ?? null;
        $password = $connectionParams['password'] ?? null;
        return $this->_driver->connect($connectionParams, $user, $password, $driverOptions);
    }
```
or 

move `$driverOptions = $params['driverOptions'] ?? [];`

after `$connectionParams = $this->chooseConnectionConfiguration($connectionName, $params);`

and replace `$params` with  `$connectionParams` 

`$driverOptions = $connectionParams['driverOptions'] ?? [];`

```
   /**
     * Connects to a specific connection.
     *
     * @param string $connectionName
     *
     * @return DriverConnection
     */
    protected function connectTo($connectionName)
    {
        $params = $this->getParams();

        $connectionParams = $this->chooseConnectionConfiguration($connectionName, $params);

        $driverOptions = $connectionParams['driverOptions'] ?? [];

        $user     = $connectionParams['user'] ?? null;
        $password = $connectionParams['password'] ?? null;
        return $this->_driver->connect($connectionParams, $user, $password, $driverOptions);
    }
```

**Comment by sylfabre** [comment]
FYI, this issue exists in doctrine\dbal v2 but is solved with v3

https://github.com/doctrine/dbal/blob/3.5.x/src/Connections/PrimaryReadReplicaConnection.php#L247

**Comment by derrabus** [comment]
@hirakch Can you confirm that this problem has been solved in 3.x?

**Comment by jaikdean** [comment]
Are you using the Symfony Doctrine bundle? We've just run into this issue and suspect https://github.com/doctrine/DoctrineBundle/pull/1506 fixed this issue when used with `doctrine/dbal` 3, but broke it under `doctrine/dbal` 2.

**Comment by derrabus** [comment]
I'm closing due to the lack of feedback from @hirakch. If you can reproduce the issue with DBAL 3, please open a new issue. If it's an issue with DoctrineBundle, please open an issue there.
