### ISSUE TITLE
AbstractSchemaManager::listTableForeignKeys() should support listing for all tables at once

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5488]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no

#### Summary

This is a feture request I am willing to implement for my atk4/data framework and it would save costly loop there - currently, to obtain linking foreign keys, tables needs to be listed first and then `AbstractSchemaManager::listTableForeignKeys()` must be called for each table.

As the `ForeignKeyConstraint::getLocalTableName()` is deprecated, returning all linking foreign keys from `AbstractSchemaManager::listTableForeignKeys()` is not possible, as the local table would not available.

The solution is to add `AbstractSchemaManager::listForeignKeys()`, which will return an array of foreign keys for each table, with table name as a key.

Please let me know, if such schema manager method would be welcomed.

**Comment by morozov** [comment]
Are you looking for `AbstractSchemaManager::fetchForeignKeyColumnsByTable()`? It will be released in 3.4.0.

**Comment by mvorisek** [comment]
Yes! Thank you!
