### ISSUE TITLE
SqlitePlatform should support UNSIGNED numbers

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5499]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no

#### Summary

see https://jianjye.com/articles/24/how-to-create-or-modify-unsigned-integer-column-in-sqlite, there is no native UNSIGNED number modifier supported, but it can be emulated using CHECK constraint

The CHECK should be supported for CREATE TABLE and also when introspecting the table details.

**Comment by morozov** [comment]
In real unsigned types, the highest bit is used to store the value which allows storing the full range of values (e.g. 0...255 for a one-byte type) as opposed to the signed ones where it's used to store the sign (-128...127).

There is little point in using an emulated unsigned type that cannot store the value in the higher range.

**Comment by mvorisek** [comment]
Very good point about "above signed range support".

I did experiments - https://dbfiddle.uk/?rdbms=sqlite_3.27&fiddle=2c9cf26e789a9853a428d52e3c954bcd

The conclusion is:
- `UNSIGNED BIGINT` cannot be supported by any numeric datatype, even by `DECIMAL(30, 0)`
- there are basically two numeric datatypes in Sqlite - `signed bigint` (64 bit signed integer) and `double` (IEEE 754 double-precision float)

There are two motivations for this issue:
- table introspecion should return as much as possible the created structure, ie. return unsigned option for numerical column created as unsigned
- the supported column range should match as closely as possible the created column, ie. emit an error for negative numbers, `TINYINT` should allow `-128` - `127` values only etc.

Outside the `UNSIGNED BIGINT` case - which is currently not supported and cannot be supported /w numerical Sqlite datatype, we can use the `MATCH` restriction to achive both.

**Comment by morozov** [comment]
There's no goal in the DBAL to emulate every feature in every supported database platform. It's the opposite: it provides an API for building portable applications that could use a common subset of the features provided by the platforms that a given application supports.

On the per-application basis, a decision needs to be made: whether it will rely on certain features (e.g. unsigned integer types) or not support the platforms that don't provide those features (e.g. support only MySQL).
