### ISSUE TITLE
Add a sort call to all indexes on introspection.

### ISSUE THREAD

**Issue by velreine** [doctrine/dbal#5519]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no

#### Summary

When dealing with many-to-many relations (and possibly other types of relations) there is an owning side and an inverse side, for many-to-many relations you also need to define an owning side even though it does not totally make sense (other than change-tracking i think?) 

If the owning side is changed and the database is afterwards introspected the ORDER of the primary keys will seem wrong and therefore a TableDiff is created with a "changedIndexes" property, does any index/constraint/primary-key exist where the order of the participating columns actually matters?

My migration now contains a sql statement:
"ALTER TABLE store_catalog ADD PRIMARY KEY (catalog_id,store_id)";

because the current primary key definition is (store_id,catalog_id).

I was thinking if those columns were sorted before the TableDiff was generated it would not be necessary to see this as a "changedIndex".

What are your thoughts?

**Comment by morozov** [comment]
> If the owning side is changed and the database is afterwards introspected the ORDER of the primary keys will seem wrong and therefore a TableDiff is created with a "changedIndexes" property […]

Could you provide a reproducer for this, please?

**Comment by morozov** [comment]
Closing due to the lack of feedback.
