### ISSUE TITLE
Unknown database type enum requested

### ISSUE THREAD

**Issue by andes2912** [doctrine/dbal#5557]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3
| Laravel     | 9.19

#### Summary

I found an error Unknown database type enum requested, **`Doctrine\DBAL\Platforms\MySQL80Platform may not support it`**. when running commands **`php artisan model:show user`** on the command line.

#### How to reproduce

I had to put a few lines of code on **`app/Providers/AppServiceProvider.php`** to work around this.
like this
 ```
DB::connection()
            ->getDoctrineSchemaManager()
            ->getDatabasePlatform()
            ->registerDoctrineTypeMapping('enum', 'string');
```

**Comment by morozov** [comment]
This looks specific to Laravel and similar to https://github.com/doctrine/dbal/issues/3161.

@andes2912 please check if https://github.com/doctrine/dbal/issues/3161#issuecomment-723016526 solves your problem. Otherwise, please provide the steps to reproduce the issue using only the DBAL APIs.

**Comment by andes2912** [comment]
> This looks specific to Laravel and similar to #3161.
> 
> @andes2912 please check if [#3161 (comment)](https://github.com/doctrine/dbal/issues/3161#issuecomment-723016526) solves your problem. Otherwise, please provide the steps to reproduce the issue using only the DBAL APIs.

Oke, thanks you. Hopefully it will be fixed soon 👍
