### ISSUE TITLE
Add Options in the OracleDriver

### ISSUE THREAD

**Issue by ghost** [doctrine/dbal#5559]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no

#### Summary

Add options like TRANSPORT_CONNECT_TIMEOUT in the OracleDriver   
  
Like this:   
Driver/AbstractOracleDriver/EasyConnectString.php   

```php
return self::fromArray([
    'DESCRIPTION' => [
        'TRANSPORT_CONNECT_TIMEOUT' => $params['transport_connect_timeout'] ?? 30,
        'ADDRESS' => [
            'PROTOCOL' => 'TCP',
            'HOST' => $params['host'],
            'PORT' => $params['port'] ?? 1521,
        ],
        'CONNECT_DATA' => $connectData,
    ],
]);
```

**Comment by morozov** [comment]
There are a few issues with the proposed approach:

1. The DBAL shouldn't be responsible for any defaults.
2. We cannot support each of the many existing configuration parameters.
3. The DBAL-level parameters are meant to hold the parameters common for all drivers, e.g. host and port. The driver-specific parameters are usually put into `$params['driver_options']`.

The API already allows passing an arbitrary connect string via the `connectstring` parameter and allows building one from an array of parameters. Isn't that sufficient to be able to specify `TRANSPORT_CONNECT_TIMEOUT` or any other driver-specific parameters?

**Comment by ghost** [comment]
Thanks for the reply, I understand your posts and they make perfect sense.

Yes, $params['driverOptions'] would be an option:

```
return self::fromArray([
            'DESCRIPTION' => [
                'TRANSPORT_CONNECT_TIMEOUT' => $params['driverOptions']['transport_connect_timeout'] ?? 60,
                'ADDRESS' => [
                    'PROTOCOL' => 'TCP',
                    'HOST' => $params['host'],
                    'PORT' => $params['port'] ?? 1521,
                ],
                'CONNECT_DATA' => $connectData,
            ],
        ]);
```

But using connectstring solved the whole problem.

I hadn't thought of that before.
