### ISSUE TITLE
Generated names can produce duplicates

### ISSUE THREAD

**Issue by mvorisek** [doctrine/dbal#5562]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.3.7

#### Summary

Currently the generated names in https://github.com/doctrine/dbal/blob/3.3.7/src/Schema/AbstractAsset.php#L215-L222 have several issues:
- hash is calculated of each individual input element, but cropped to the final length after concatenation, thus the generated result may honor first few elements only
- FK constraint is a 4-tuple consisting of a local/foreign table/column names, currently, only the local names are part of the generated name - https://github.com/doctrine/dbal/blob/3.3.7/src/Schema/Table.php#L416
- (minor) the used hash function is weak (`crc32`)
- (minor) no care is taken to pass/hash an unquoted/quoted names consistenly

#### How to reproduce

https://github.com/doctrine/dbal/blob/d58bd5803623f01468db09252a8c33758e51e33c/tests/Schema/TableTest.php#L864-L905

#### Expected behaviour

Each of the described issue should be fixed to produce a hash/generated name with a minimal chance of a collision.

**Comment by morozov** [comment]
Please provide clear and concise steps to reproduce the issue.

**Comment by mvorisek** [comment]
The first 2 major issues have full code to reproduce in https://github.com/doctrine/dbal/pull/5490. I belive I cannot do more.

**Comment by mvorisek** [comment]
does your action mean all 4 (related) reasons/issues are not valid?
