### ISSUE TITLE
Invalid alter table SQL generated for SQLite

### ISSUE THREAD

**Issue by simonworkhouse** [doctrine/dbal#5572]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.4.0

#### Summary

Invalid alter table SQL is generated for SQLite when an unnamed foreign key constraint exists.

#### Current behaviour

```
SQLSTATE[HY000]: General error: 1 near "0": syntax error (SQL: CREATE TABLE orders (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER DEFAULT NULL, reference VARCHAR(255) DEFAULT NULL COLLATE BINARY, CONSTRAINT 0 FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE))
```

#### How to reproduce

Here's an example of the issue in a Laravel project https://github.com/workhouse-advertising/laravel-sqlite-bug 

#### Expected behaviour

Either the `CONSTRAINT 0` portion needs to be omitted or perhaps the key name needs to be quoted like so `CONSTRAINT '0'`, whichever is valid.

**Comment by louis-l** [comment]
Having the same issue, downgrade to v3.3.8 works.

**Comment by morozov** [comment]
It looks like the same issue as reported in https://github.com/doctrine/dbal/issues/4243.

**Comment by da-mask** [comment]
This blew up every one of my PHPUnit tests in my Laravel app, all errored with `ErrorException: Undefined array key -1`.  Downgrading to v3.3.8 resolved it. Probably not much useful info here, but its all I've got.
