### ISSUE TITLE
listTables is broken on PostgreSQL

### ISSUE THREAD

**Issue by ddeboer** [doctrine/dbal#5574]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.4.0

#### Summary

`PostgresSQLSchemaManager::listTables()` returns no tables for a database connection that does have tables.

Is this related to #5268 and other work on the introspection methods?

#### Current behaviour

An empty list of tables is returned.

#### How to reproduce

On an existing Postgres database that has at least one table:

```php
$schemaManager = PostgresSQLSchemaManager::createSchema(); 
$schemaManager->listTables();
```

#### Expected behaviour

All existing tables should be returned.

**Comment by NoiseByNorthwest** [comment]
Same issue I think #5573

**Comment by NoiseByNorthwest** [comment]
It seems to be caused by the unexpected use of `current_schemas(false)` to filter tables as mentionned in #5573

**Comment by ddeboer** [comment]
Yep, same issue (with 4 mins difference 😄), so closing this as a duplicate of #5573.
