### ISSUE TITLE
PostgreSQL schema listing doesn't include namespaces

### ISSUE THREAD

**Issue by aleho** [doctrine/dbal#5593]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.4.0

#### Summary

Schema listing (tables, indexes, …) is broken for PostgreSQL.

This causes doctrine/orm#9991.

#### Current behaviour

Since 3.4.0 listing schema information, although undocumented (?), seems to require `search_path` to be set to retrieve objects from all available schemas (see `ANY(current_schemas(false))` condition).

When multiple schemas, i.e. search paths, are used, this breaks.

Apparently when retrieving information the namespace is omitted from table names (`Table` is expecting it to be in the format of `namespace.table_name`).

#### How to reproduce

Use entities from different schemas (other than the default PostgreSQL `public`):
```php
<?php

declare(strict_types = 1);

namespace App\Entity\Schema1;

use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MyEntityRepository::class)]
#[ORM\Table(schema: 'schema1')]
class MyEntity
{
    …
}
```

Set `search_path` to multiple schemas:
```sql
ALTER DATABASE db_name SET search_path TO public,schema1;
```

#### Expected behaviour

Tables, indexes, etc are listed with the correct namespace.

**Comment by morozov** [comment]
This looks like having the same root cause as https://github.com/doctrine/dbal/issues/5575 and should have been fixed by https://github.com/doctrine/dbal/issues/5575. Could you try bumping the dependency constraint for `doctrine/dbal` to `^3.4@dev` and re-testing?

**Comment by aleho** [comment]
Yes, you are right!

Sorry, it didn't occur to me searching for index as well because here all introspection was broken, so I thought a PR would address this too.

Also, 3.4.1 was released just now fixing all problems here.

Thank you!
