### ISSUE TITLE
using logger middleware in favor of setSSqlLogger

### ISSUE THREAD

**Issue by remco-pc** [doctrine/dbal#5628]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.13.1

#### Summary

There is a possibility to log sql queries in doctrine. the old method uses DebugStack and $em->getConnection()->getConfiguration()->setSQLLogger($logger); but this got deprecated

There are mentions about a middlewares solution in combination with monolog logger.
I've tried to set it up, but the examples found on the internet doesn't show exactly howto.
 
I do:
```php
$logger = new Logger('Doctrine');
$logger->pushHandler(new StreamHandler($object->config('project.dir.log') . 'sql.log', Logger::DEBUG));
$logger->pushProcessor(new PsrLogMessageProcessor(null, true));

$logger->info('Logger initialized...');

$configuration = $em->getConnection()->getConfiguration();
$configuration->setMiddlewares([new Logging\Middleware($logger)]);
```

Now the Logger initialized gets created. but not more. what todo next to enable sql logging

**Comment by greg0ire** [comment]
Moving this to `doctrine/dbal`, which is where the connection is defined.

**Comment by greg0ire** [comment]
If you're talking about my message [here](https://github.com/doctrine/orm/issues/9562#issuecomment-1058518021) apparently it won't work, and is apparently too late. The only place where the middlewares is used is here, in DriverManager::getConnection():

https://github.com/doctrine/dbal/blob/a24b89d663d8f261199bc0a91c48016042ebda85/src/DriverManager.php#L204

**Comment by remco-pc** [comment]
it was a different one, but should the code not contain (if logger then log->info(sql query) ?

**Comment by greg0ire** [comment]
what code?

**Comment by remco-pc** [comment]
> what code?

https://github.com/doctrine/DoctrineBundle/pull/1456/commits/c416af573582fc64aeb9116d08e897b4907e1e67 and one other which i cannot find right now

**Comment by greg0ire** [comment]
It's not the responsibility of the bundle to provide a logging middleware, only to wire it. The code that logs the queries is inside the DBAL itself: https://github.com/doctrine/dbal/blob/a24b89d663d8f261199bc0a91c48016042ebda85/src/Logging/Connection.php#L41

**Comment by remco-pc** [comment]
I see, but how can the entityManager using that connection or is it already using it ? because i dont get logs in the file yet only if i add them myself

**Comment by greg0ire** [comment]
That part, the entity manager using the logging connection is what I referred to as wiring. So if you want to understand why it doesn't work, I suggest you debug the bundle code you found. This part, for instance: https://github.com/doctrine/DoctrineBundle/blob/57280cea7b1a9212fde52a3b5065b8196ed213ce/DependencyInjection/DoctrineExtension.php#L1160-L1162

**Comment by remco-pc** [comment]
i came to this, but it is still not working:
```
$config = ORMSetup::createAnnotationMetadataConfiguration($paths, false, $proxyDir, $cache);

            $logger = new Logger(Database::LOGGER_DOCTRINE);
            $logger->pushHandler(new StreamHandler($object->config('project.dir.log') . 'sql.log', Logger::DEBUG));
            $logger->pushProcessor(new PsrLogMessageProcessor(null, true));

            $object->logger($logger->getName(), $logger);
            $logger->info('Logger initialized...');
            $connection = DriverManager::getConnection($connection, $config, new EventManager());
            $connection = new Logging\Connection($connection, $logger);
            $em = EntityManager::create($connection, $config);

            $configuration = $em->getConnection()->getConfiguration();
            $configuration->setMiddlewares([new Logging\Middleware($logger)]);
```

```
TypeError: Argument 1 passed to Doctrine\DBAL\Logging\Connection::__construct() must implement interface
Doctrine\DBAL\Driver\Connection, instance of Doctrine\DBAL\Connection given
```

Why not create $em->setConnection(...)
Do you have any idea ?

**Comment by greg0ire** [comment]
Yes: as I told you above, middlewares are taken into account in `DriverManager::getConnection()`, and in your code, you are calling `setMiddlewares` after calling `DriverManager::getConnection`… that's too late. Please take a look at how it works:
https://github.com/doctrine/dbal/blob/a24b89d663d8f261199bc0a91c48016042ebda85/src/DriverManager.php#L181-L219

**Comment by morozov** [comment]
FWIW, I stumbled upon a similar problem recently: updating connection configuration after connecting may or may not work depending on what exactly is being updated. In the long term, we should make the connection and the configuration immutable to prevent this kind of frustration.

**Comment by remco-pc** [comment]
I ended up with this working code:
```php
/**
     * @throws ObjectException
     * @throws FileWriteException
     * @throws ORMException
     * @throws ORMException2
     * @throws Exception
     */
    public static function entityManager(App $object, $options=[]){
        $environment = $object->config('framework.environment');
        if(empty($environment)){
            $environment = Config::MODE_DEVELOPMENT;
        }
        if(array_key_exists('environment', $options)){
            $environment = $options['environment'];
        }
        $entityManager = $object->get(Database::NAME . '.entityManager.' . $environment);
        if(!empty($entityManager)){
            return $entityManager;
        }

        $url = $object->config('project.dir.data') . 'Config.json';
        $config  = $object->parse_read($url, sha1($url));
        if($config){
            $connection = (array) $config->get('doctrine.' . $environment);
            $paths = $config->get('doctrine.paths');
            $proxyDir = $config->get('doctrine.proxy.dir');
            $cache = null;
            $config = ORMSetup::createAnnotationMetadataConfiguration($paths, false, $proxyDir, $cache);
            $logger = new Logger(Database::LOGGER_DOCTRINE);
            $logger->pushHandler(new StreamHandler($object->config('project.dir.log') . 'sql.log', Logger::DEBUG));
            $logger->pushProcessor(new PsrLogMessageProcessor(null, true));
            $object->logger($logger->getName(), $logger);
            $logger->info('Logger initialized...');
            $config->setMiddlewares([new Logging\Middleware($logger)]);
            $connection = DriverManager::getConnection($connection, $config, new EventManager());
            $em = EntityManager::create($connection, $config);
            $object->set(Database::NAME .'.entityManager. ' . $environment, $em);
            return $em;
        }
    }
```

**Comment by morozov** [comment]
Closing then.
