### ISSUE TITLE
Using sequences in mariadb databases

### ISSUE THREAD

**Issue by br4in1** [doctrine/dbal#5653]
|    Q        |   A
|------------ | -----
| Version     | 3.4.3

### Support Question

Hello,

I'm working on a Symfony 5 project that is linked to a mariadb database with version 10.6.8.
I want to create a user-defined sequence and use it to generate IDs for a table.
According to the mariadb website, [the engine supports sequences starting with version 10.3](https://mariadb.com/kb/en/sequences/).
Though, when I add the annotation 
`* @ORM\GeneratedValue(strategy="SEQUENCE")`
`* @ORM\SequenceGenerator(sequenceName="seq_id")`
and I try to dump the SQL queries by executing `php bin/console d:s:u --dump-sql`, nothing regarding the sequence shows up.
Moreover, when I try to persist an entity that have the annotation above, I get the error `Operation 'Doctrine\DBAL\Platforms\AbstractPlatform::getSequenceNextValSQL' is not supported by platform.`

It may be important to note that the same code works as expected when I link my application to a PostgreSQL database.

This isn't weird behavior: The class at [MariadbPlatform.php](https://github.com/doctrine/dbal/blob/4cbbe6e4b9ef6c69d5f4c968c637476f47bb54f5/src/Platforms/MariaDBPlatform.php) does not overload the `getCreateSequenceSQL` method, and thus it calls the base class method that throws a `Exception::notSupported(__METHOD__)`.
The weird behavior though is that the doctrine/dbal package is not being upgraded to support the new features provided by engines.

For now, I have managed to progress by implementing a custom Id generator that simply fetches the next value of the sequence. But for that to work, the sequence must be created manually on the database which is not very practical.

Please let me know if I'm doing something wrong 😁

Thank you.

**Comment by morozov** [comment]
If an `AbstractPlatform` subclass doesn't override `getCreateSequenceSQL()`, it means that the DBAL doesn't support sequences on this platform which is what the error message says.

The DBAL uses sequences primarily to implement the `autoincrement` column property on the platforms that don't support identity columns natively (e.g. Oracle).

Given that recent Oracle versions support identity columns as well (see https://github.com/doctrine/dbal/pull/5443), I believe we will sunset the support for sequences in the DBAL at some point.

Implementing a custom generator if you need one looks like a proper solution.
