### ISSUE TITLE
ORA-00923 error at startup with Oracle 19c (oci8)

### ISSUE THREAD

**Issue by JeremyPasco** [doctrine/dbal#5659]
### Bug Report

|    Q        |   A
|------------ | ------
| DBAL Version     | 3.2.1

#### Summary

Hi, I encounter a ORA-00923 error when I try to connect a Symfony application with Oracle 19c Database

#### Current behaviour

At Symfony startup, the following error is triggered :
```
Error thrown while running command \"dbal:run-sql -q 'SELECT 1'\". 
Message: \"An exception occurred while executing a query: 
ORA-00923: mot-clé FROM absent à l'emplacement prévu\"",
"context":{"exception":{"class":"Doctrine\\DBAL\\Exception\\SyntaxErrorException","message"
:"An exception occurred while executing a query: ORA-00923: mot-clé FROM absent à l'emplacement prévu","code":923,"file":"/srv/api/vendor/doctrine/dbal/src/Driver/API/OCI/ExceptionConverter.php:47","previous":{"class":"Doctrine\\DBAL\\Driver\\OCI8\\Exception\\Error","message":"ORA-00923: mot-clé FROM absent à l
'emplacement prévu","code":923,"file":"/srv/api/vendor/doctrine/dbal/src/Driver/OCI8/Exception/Error.php:27"}
```

The SQL query `SELECT 1` makes me think that a wrong SQL dialect is picked by DBAL. Should not the oci8 mention in the url be enough to make DBAL pick Oracle dialect? Is there something I'm missing?

Btw I don't know how to specify Oracle version and if it matters for oci. I tried with different values for `?serverVersion=` : `oracle-19c`, `oracle-19`, `19c`, `19`. 

#### How to reproduce

Here is my current configuration:
```yaml
doctrine:
    dbal:
        url: 'oci8://user:password@host:port/service_name'
        service: true
```

The database is up and running at the provided url.

**Comment by morozov** [comment]
Where does `SELECT 1` come from? From your error message, it looks like something is running a console command:
```sh
dbal:run-sql -q 'SELECT 1'
```

The DBAL does not use this API internally, so the issue must be outside of the DBAL.

**Comment by JeremyPasco** [comment]
Sorry for wasting your time. I am working on a fresh API Platform distribution and missed the part where this distribution challenge the database at startup with the `SELECT 1` query to ensure it is reachable. I thought it was DBAL playing this role. I'll made a PR on the API Platform distribution to adapte this query to DBAL configuration (Oracle dialect).
