### ISSUE TITLE
Missing table option check for "foreignKeys" when creating foreign keys for multiple table creation SQL

### ISSUE THREAD

**Issue by asilgalis** [doctrine/dbal#5669]
|    Q        |   A
|------------ | -----
| Version     | 3.4.4

### Support Question

In `Doctrine\DBAL\Platforms\AbstractMySQLPlatform` method `_getCreateTableSQL` there is a check `if (isset($options['foreignKeys'])) {` to create foreign keys but in method `getCreateTablesSQL` this check is absent.

Is this a bug? I don't know.

Should this check be there? IMO - yes

**Comment by morozov** [comment]
What problem does not having this check cause for you?

**Comment by morozov** [comment]
Closing due to insufficient context and the lack of feedback.
