### ISSUE TITLE
SchemaManager::listTableColumns() does not return view columns anymore

### ISSUE THREAD

**Issue by fabacino** [doctrine/dbal#5671]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.4.4

Version 3.3.x is not affected.

#### Summary

I want to get the columns of a view in order to inspect its structure and compare it across platforms.

#### Current behaviour

Calling `SchemaManager::listTableColumns()` with the name of a view as argument returns an empty array (tested on Oracle, PostgreSQL, SQLServer and Sqlite). In version 3.3, the same call used to return the columns of the view. Since I didn't find anything in the release notes indicating that this was intentionally changed, I assume it's a bug.

#### How to reproduce

```php
$connection = \Doctrine\DBAL\DriverManager::getConnection([
    'driver' => 'pdo_sqlite',
    'memory' => true,
    'charset' => 'UTF-8',
]);

$schemaManager = $connection->createSchemaManager();
$table = $schemaManager->createSchema()->createTable('my_table');
$table->addColumn('id', 'integer');
$schemaManager->createTable($table);

$schemaManager->createView(new \Doctrine\DBAL\Schema\View(
    'my_view',
    'SELECT id FROM my_table'
));

$columns = $schemaManager->listTableColumns('my_view');
```

#### Expected behaviour

The columns of the view are returned.

**Comment by morozov** [comment]
It may have changed as a side effect of https://github.com/doctrine/dbal/pull/5268. Also, it may be the result of fixing https://github.com/doctrine/dbal/issues/5579.

In my opinion, the expectation that the method named `listTableColumns()` will return view columns is correct, even though it might previously work like this.

> Calling `SchemaManager::listTableColumns()` with the name of a view as argument returns an empty array (tested on Oracle, PostgreSQL, SQLServer and Sqlite).

Did it work as you expect on all platforms?

**Comment by fabacino** [comment]
> Did it work as you expect on all platforms?

It worked on Oracle, PostgreSQL and Sqlite platforms, but not on SQLServer (tested with version 3.3.8).

> In my opinion, the expectation that the method named `listTableColumns()` will return view columns is correct, even though it might previously work like this.

I assume you meant *not* correct and I agree. All the other table functions (I am aware of) don't work with views either, so there's no reason why `listTableColumns()` should. As this is not a bug then, I will take care of it on our end for now.

I am not sure to how many other people this would be useful but in case you are interested in adding `listViewColumns()` (and possibly `viewsExist()`) to the schema manager, I could probably help out with the implementation.

**Comment by morozov** [comment]
> I assume you meant _not_ correct and I agree.

You are right, I meant  _not_ correct.

> I am not sure to how many other people this would be useful but in case you are interested in adding `listViewColumns()` (and possibly `viewsExist()`) to the schema manager, I could probably help out with the implementation.

At this point, the support for views in the DBAL is quite limited, and I'm not really sure how much we need to improve it. In my experience, views are either owned by a DBA to offload complex query logic from the application to the database, or they replace tables in order to allow making schema changes in tables without having to change the application code. None of these scenarios are primary for the DBAL.

Why would you want to see these APIs available in the DBAL?

**Comment by fabacino** [comment]
These methods are useful for us because they allow us to assert the database structure our application expects across multiple platforms. We have a test pipeline which compares all our databases against a reference database, so whenever a migration script with DDL statements is created, the pipeline runs and checks whether the database structure is still consistent afterwards across all those platforms.
For this purpose, we need something like `listViewColumns()` in order to be able to inspect the columns of a view.

I also think these methods would be a nice addition for "symmetry reasons" (for lack of a better word). It was not clear to me why `listViews()`, `createView()`, etc. do exist, but `viewsExist()` and `listViewColumns()` do not.

**Comment by kynx** [comment]
👍 for `listViewColumns()`. 

This one recently caught me when updating dbal on a project that uses `SchemaManager` to build a model of a star-schema data warehouse. There views are used as "role playing dimensions". I need the columns from them to populate a report designer UI.
