### ISSUE TITLE
PHP 8.2 compatibility for DBAL 2.x ?

### ISSUE THREAD

**Issue by bmack** [doctrine/dbal#5723]
Dear Doctrine DBAL team,

we at TYPO3 migrated to Doctrine DBAL 3 for our next major release, however we would also give our users support for our release from last year (supported another 24 months) with the latest PHP 8 versions, where we use DBAL 2.13.x.

My question is: Would you be willing to release another Doctrine DBAL 2.13.x version with PHP 8.2 support at all? Could we also support this with code / tests or financially? Or is this a no-go from your side?

All the best,
Benni.

**Comment by derrabus** [comment]
We do not maintain version 2 anymore as announced [here](https://www.doctrine-project.org/2022/01/22/sunsetting-dbal-2.html). Even if we did create a PHP 8.2 compat release, we'd face the same question again next year when talking about PHP 8.3, wouldn't we. So I'd rather not resurrect the 2.13.x branch if that's possible.

Would it be feasible for you to let users opt-in to DBAL 3? Projects that run on 2.13.x deprecation-free should be able to use DBAL 3 right away.

**Comment by bmack** [comment]
Thanks for the quick reply. We do have some problems with that
a) we ship a tarballed version with dependencies bundled
b) on top, TYPO3 has the "extensions" concept where people might still use old APIs we don't know exactly

We might be able to pull something off as you proposed (we also have a QueryBuilder decorator already in place with most migrations in place to ease the pain), however we also might consider forking 2.13.x ourselves then with PHP 8.2 support, as this might be less pain and work for us.

**Comment by morozov** [comment]
> we ship a tarballed version with dependencies bundled

In this case, why can't you fork the DBAL and ship a patched version that will support PHP 8.2 or satisfy any other needs of the business?

**Comment by bmack** [comment]
thanks for the input and no worries @morozov - we will add PHP 8.2 to our build matrix with a patched version of DBAL 2.x, and have a look at the necessary changes. Once this is done we will let you know how much work it was.
