### ISSUE TITLE
`Doctrine\DBAL\Connection::connect` and `@internal`

### ISSUE THREAD

**Issue by dmaicher** [doctrine/dbal#5791]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.5.0

#### Summary

Recently the `Doctrine\DBAL\Connection::connect` method has been marked `@internal` on 3.x. On 4.0 this method is protected and not `@internal`.

I'm wondering: is marking it `@internal` needed and fully correct? I mean it is still an extension point on 4.0 (for classes inheriting from it) and its not purely meant for internal purposes, or?

With Symfony's phpunit bridge I now get this on 3.5

```
  1x: The "Doctrine\DBAL\Connection::connect()" method is considered internal This method will be made protected in DBAL 4.0. It may change without further notice. You should not extend it from "DAMA\DoctrineTestBundle\Doctrine\DBAL\Connection".
```

**Comment by morozov** [comment]
> I'm wondering: is marking it `@internal` needed and fully correct?

No idea. [phpDocumentor](https://docs.phpdoc.org/2.9/references/phpdoc/tags/internal.html) doesn't say anything specific in this regard.

> I mean it is still an extension point on 4.0 (for classes inheriting from it) and its not purely meant for internal purposes, or?

I don't think the DBAL provides backward compatibility for its protected API, so all protected methods are internal to a certain extent.

Another uncertainty is the BC promise for SPIs: if the DBAL calls a certain non-private method and you extend it to have your code called at a certain point, it is not guaranteed that it will always be the case (see https://github.com/doctrine/dbal/pull/5268 for example).

If you plan to use the method for extension, you can suppress this error in your static analysis configuration.

**Comment by dmaicher** [comment]
> I don't think the DBAL provides backward compatibility for its protected API, so all protected methods are internal to a certain extent.

Hm ok. This makes it really hard for me to make https://github.com/dmaicher/doctrine-test-bundle work with DBAL 4 then.

Since the removal of `Events::postConnect` the only extension point I can use is `Connection::connect()` :confused: 

> If you plan to use the method for extension, you can suppress this error in your static analysis configuration.

Unfortunately its about https://github.com/dmaicher/doctrine-test-bundle and many users would see this error message then.

**Comment by derrabus** [comment]
> Since the removal of `Events::postConnect` the only extension point I can use is `Connection::connect()` 😕

Why doesn't a driver middleware work in your case?

**Comment by dmaicher** [comment]
> Why doesn't a driver middleware work in your case?

That does not work. I basically need the `Doctrine\DBAL\Connection` internal state (`$_transactionNestingLevel`) to be in sync with the underlying driver connection that my bundle manages.

See https://github.com/dmaicher/doctrine-test-bundle/blob/master/src/DAMA/DoctrineTestBundle/Doctrine/DBAL/PostConnectEventListener.php#L19

**Comment by derrabus** [comment]
I'm afraid, I haven't fully understood why a middleware can't do that. `Connection::connect()` was never meant as an extension point and the event has been removed in an effort to consolidate extension points.

Let's think this a bit outside the box and pretend none of the current extension points existed. Can you elaborate a bit more how your extension interacts with the DBAL and what kind of extension point you need?

**Comment by dmaicher** [comment]
Sure :blush: 

So basically my bundle manages a `Doctrine\DBAL\Driver\Connection` connection via a custom Middleware and a custom Driver.

The idea is that the driver connection is kept statically in the current php process and with a PHPUnit extension we begin a transaction before all tests and roll it back afterwards.

To make this work I need to make sure that the actual driver connection `$this->_conn` used inside `Doctrine\DBAL\Connection` is the one kept statically in the process and managed by my custom Driver. So that we can roll-back all changes after the test.

So how the flow looks like for a test case:

- `Doctrine\DBAL\Driver\Connection` is created using a factory (by DoctrineBundle)
- `Doctrine\DBAL\Connection::connect` is called at some point to actually open a connection
    - `DAMA\DoctrineTestBundle\Doctrine\DBAL\Middleware` decorates the original driver 
    - `DAMA\DoctrineTestBundle\Doctrine\StaticDriver` is used to return a connection that is kept statically in the process and which already has a transaction started.
    - now since the underlying connection has a transaction started already I also need to make sure the `Doctrine\DBAL\Connection` instance is aware of this and start a transaction there too so that `$transactionNestingLevel = 1` 
    
So the last part is the tricky thing. Basically I need an extension point where I can call `Doctrine\DBAL\Connection::beginTransaction` AFTER the driver connection was created and assigned to `Doctrine\DBAL\Connection::$_conn`. Which is exactly what I used `Events::postConnect` for. 

I did some tests and I can extend `Doctrine\DBAL\Connection` and hook into `connect` to achieve the same but obviously this is far from ideal.

**Comment by derrabus** [comment]
So, we basically have an outer and an inner connection here and a custom driver on the outer connection that delegates to the inner connection?

> now since the underlying connection has a transaction started already I also need to make sure the `Doctrine\DBAL\Connection` instance is aware of this and start a transaction there too so that `$transactionNestingLevel = 1`

Okay, why do we need to do this? Can't we live with the state `$outerConnection->transactionNestingLevel = $innerConnection->transactionNestingLevel - 1` permamently?

**Comment by dmaicher** [comment]
> Okay, why do we need to do this? Can't we live with the state $outerConnection->transactionNestingLevel = $innerConnection->transactionNestingLevel - 1 permamently?

Hm no this won't work if inside the tested code (domain code of the app) we also use transactions. In this case we need to use SAVEPOINTs for example. And this only works properly if the outer connection is aware of the current nesting level.

For example this scenario 

- start transaction on inner connection
    - app persist some stuff
    - app starts a transaction on outer connection
    - some error happens on the app code
    - app does rollback (using SAVEPOINT) on outer connection
    - app does some more manipulations like INSERT/DELETE/UPDATE on outer connection
- we rollback all changes on inner connection via PHPUnit extension

In this scenario we have to make sure the transactionNestingLevel is in sync all the time. Otherwise no savepoint would be used for example.

**Comment by derrabus** [comment]
> In this scenario we have to make sure the transactionNestingLevel is in sync all the time. Otherwise no savepoint would be used for example.

Okay, that would be the case when the outer connection assumes the nesting level to be 0 while it's 1 in the inner connection. But in that case, the outer connection would call `beginTransaction()` which our custom driver could translate to a savepoint, right?

**Comment by dmaicher** [comment]
So you mean I basically replicate the SAVEPOINT logic in the inner connection?

Like https://github.com/doctrine/dbal/blob/3.5.x/src/Connection.php#L1335

**Comment by derrabus** [comment]
Something like that. Would that work?

**Comment by dmaicher** [comment]
:thinking: I will have a look and get back to you. Thanks already for your input :+1:

**Comment by derrabus** [comment]
Thank you for taking the time!

**Comment by dmaicher** [comment]
@derrabus I had a look and I believe I can indeed make this work purely on the inner connection by managing savepoints myself. Seems to be the nicer solution :blush: Thanks.

So let's close here for now.

**Comment by derrabus** [comment]
Great, thanks for getting back to us. Don't hesitate to open a new issue if this plan does not work. 🙂
