### ISSUE TITLE
Release 3.5.0 breaks metadata check in doctrine/migrations

### ISSUE THREAD

**Issue by manuelkiessling** [doctrine/dbal#5796]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.5.0

#### Summary

`doctrine/migrations:3.5.2` currently requires `doctrine/dbal:3.5.0`. It previously required `doctrine/dbal:3.4.6`.

doctrine/migrations uses doctrine/dbal to check if its metadata information is up to date. When using a MariaDB database, this check works with `doctrine/dbal:3.4.6` but fails with `doctrine/dbal:3.5.0`, and downgrading to `doctrine/dbal:3.4.6` is the only workaround.

See https://github.com/doctrine/migrations/issues/1281 for a related bug report.
Also, https://github.com/doctrine/dbal/pull/5779 seems to be related.

#### Current behaviour

Upgrading from `doctrine/dbal:3.4.6` to `doctrine/dbal:3.5.0` when using a MariaDB database fails with "The metadata storage is not up to date" as returned by https://github.com/doctrine/migrations/blob/3.5.x/lib/Doctrine/Migrations/Exception/MetadataStorageError.php#L13.

#### How to reproduce

Set up a Symfony 6.1 project, using PHP 8.1.11, running against a MariaDB 10.5.13 database. Install and set up the DoctrineMigrationsBundle as described in https://symfony.com/bundles/DoctrineMigrationsBundle/current/index.html#installation.

Make sure that the `DATABASE_URL` env var contains the `mariadb-` part for its `serverVersion=` parameter.

Try running `php bin/console make:migration` or launch the Symfony project using `symfony server:start`, and try opening one of its pages.

Both will result in a "The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue." error.

Running `php bin/console doctrine:migrations:sync-metadata-storage` does not solve the problem.

#### Expected behaviour

No error.

**Comment by derrabus** [comment]
Can you please verify that updating DBAL to `"~3.5.1@dev"` in your composer.json fixes the regression for you?

**Comment by manuelkiessling** [comment]
@derrabus I can confirm that everything works fine when upgrading DBAL from `3.4.6` to `3.5.x-dev f38ee8a`.
