### ISSUE TITLE
Visual Schema designer/builder

### ISSUE THREAD

**Issue by excitedbox** [doctrine/dbal#5809]
One of the mos useful tools for designing mysql databases is the mysql workbench and the visual db tools. I would love to see a visual db tool like that for Doctrine to make it easier to model entity relationships and generate migrations. Current options are lacking many important features and cause many headaches.

- Symfony maker bundle lacks options for editing or visualizing models, and aborting an entity leaves you with broken code that needs to be manually removed.
-Skippy is expensive and barely works.
- conversion from mysql workbench is difficult and requires knowing the ins and out of how Doctrine creates entities and relationships in order to configure tables the same way.

Even having a simple crud form to configure entities would be a massive step up from current options, in my opinion.

**Comment by derrabus** [comment]
Such a tool would be way out of scope for the DBAL (the repository where you opened this issue).

Moreover, that tool can be developed in a separate repository by anyone who feels like they need it. I'm closing the issue because we don't intend to build it.
