### ISSUE TITLE
Create an easy way to extend the schema manager

### ISSUE THREAD

**Issue by derrabus** [doctrine/dbal#5812]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no

#### Summary

In #5784, the event system of the DBAL has been deprecated. One of the current use-cases is to modify the SQL emitted by the schema manager after a schema comparison. Instead, developers should extend the schema manager directly now. However, it is not really easy to do that at the moment because it involves overriding the driver as well.

My idea would be to allow a developer to pass a callable to `DriverManager` that constructs a schema manager instance and thus overrides the schema manager created by the driver/platform.

**Comment by eugene-borovov** [comment]
Is it easy enough?
```php
DriverManager::getConnection(
    [
        'driver' => ...
        'wrapperClass' => SchemaOverriddenConnection::class,
    ]
);

class SchemaOverriddenConnection extends Connection
{
  public function createSchemaManager(): AbstractSchemaManager
  {
     return new OverriddenSchemaManager($this, $this->getDatabasePlatform());
  }
}
```

**Comment by derrabus** [comment]
Good one, but maybe we can manage to do that without providing our own wrapper class. It's possible for the driver and the platform, why shouldn't it be for the schema manager?

**Comment by eugene-borovov** [comment]
`Driver` is a factory for the `Connection` internals. Wrapper class allows override driver creational methods without exposing dependency in the constructor.

**Comment by derrabus** [comment]
So, what you're saying is, extending the wrapper class is the way to go? In that case, this would be a pure documentation issue.

**Comment by eugene-borovov** [comment]
Another way is using `\Doctrine\DBAL\Configuration` for schema manager overriding like middleware configuration.

**Comment by eugene-borovov** [comment]
```php
class \Doctrine\DBAL\Configuration
{
    
  // ....

  private ?AbstractSchemaManager $schemaManager = null;
  
  public function getSchemaManager(): ?AbstractSchemaManager
  {
    return $this->schemaManager;
  }  
  
  public function setSchemaManager(AbstractSchemaManager $schemaManager): void
  {
    $this->schemaManager = $schemaManager;
  }  
  
  // ....
	
}


class \Doctrine\DBAL\Connection
{
  // ...
  
  public function createSchemaManager(): AbstractSchemaManager
  {
    return $this->_config->getSchemaManager() ?? 
        $this->_driver->getSchemaManager($this, $this->getDatabasePlatform());
  }
  
  // ...

}
```

**Comment by eugene-borovov** [comment]
> So, what you're saying is, extending the wrapper class is the way to go? In that case, this would be a pure documentation issue.

It looks like a more correct way to override schema manager is using `\Doctrine\DBAL\Driver\Middleware`. But it's not so easy anymore. Although technically it is also a wrapper class.

**Comment by frsmoray** [comment]
Would an implementation of a custom Schema manager like as in the suggested example (of an overridden schema manager as OverriddenSchemaManager) be able to let a developer place a table prefix as it can be done with current dbal deprecated event system?

**Comment by derrabus** [comment]
I've worked on an implementation in #5876.
