### ISSUE TITLE
Doctrine batch processing and memory limit issue in Symfony dev env

### ISSUE THREAD

**Issue by fabienlem** [doctrine/dbal#5815]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 2.7.1

#### Summary

Hello there,

I stumble upon [this issue](https://github.com/symfony/symfony/issues/46158) as I encounter the same problem.

Even with the solution provided by @pmishev I got memory limit issue when processing batch import with Symfony in dev env.

Thank you for your feedback!

#### Current behaviour

Memory limit due to Doctrine middleware I'm not able to disable.

My though is: is it still possible to process batch import with Doctrine?

#### How to reproduce

Here is my import logic:

- Read data from external source
- Create or update a batch of entities (findOneBy / new Entity() / ->setX()->setY()->setZ())
- Flush and clear entity manager
- Repeat

#### Expected behaviour

Provide a way to disable logging / debuging features when processing batch operations with Doctrine.

#### Workaround

In addition to @pmishev solution, I added this code in order to avoid memory limit issue:

```
<?php

namespace App\DependencyInjection;

use App\Doctrine\Middleware\ProxyDebugDataHolder;
use App\Doctrine\Middleware\ProxyLogger;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

class OverrideDoctrineMiddlewareCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $doctrineLoggingMiddlewareDef = $container->getDefinition('doctrine.dbal.logging_middleware');
        $doctrineLoggingMiddlewareDef->replaceArgument(0, new Reference(ProxyLogger::class));

        $doctrineLoggingMiddlewareDef = $container->getDefinition('doctrine.dbal.debug_middleware');
        $doctrineLoggingMiddlewareDef->replaceArgument(0, new Reference(ProxyDebugDataHolder::class));
    }
}
```

and:

```
<?php

namespace App\Doctrine\Middleware;

use Symfony\Bridge\Doctrine\Middleware\Debug\DebugDataHolder;
use Symfony\Bridge\Doctrine\Middleware\Debug\Query;

class ProxyDebugDataHolder extends DebugDataHolder
{
    public function addQuery(string $connectionName, Query $query): void
    {
    }
}
```
Drawback: it totally disables Doctrine debugging.

**Comment by dmaicher** [comment]
Is this batch processing happening in a Symfony command? If so is disabling debug mode altogether using `--no-debug` an option when running the command?

That's usually how I run long running commands which produce loads of queries and otherwise blow up memory

**Comment by fabienlem** [comment]
@dmaicher indeed I import through `messenger:consume` command.

Using `--no-debug` solve my issue. Thank you a lot!
