### ISSUE TITLE
SQL Server issue listing table names

### ISSUE THREAD

**Issue by rotunomp** [doctrine/dbal#5816]
### Bug Report

Hello, I was trying to get database table names from an SQL Server 2019 connection, and ran into this error:

**SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens**

I attempted this on a different postgres connection just to make sure, and it could properly get table names on that connection.

|    Q        |   A
|------------ | ------
| Version     | 3.5.1

#### How to reproduce

- PHP Version 8.1.9
- SQL Server 2019

This is my code. I am using Laravel to establish the DB connection, I attempted:

```
<?php

namespace App\Console\Commands\Run;

use App\Models\Account;
use Illuminate\Support\Facades\DB;

class TestCommand extends \Illuminate\Console\Command
{
    protected $signature = 'run:test';

    public function handle()
    {
        $connection = DB::getDoctrineConnection();
        $dbal = $connection->createSchemaManager();
        $dbal->listTableNames();
    }
}
```

**Comment by derrabus** [comment]
Please reproduce your issue with DBAL APIs only or by providing a failing functional test. This makes it easier for others to pick your issue up because not everyone uses Laravel.

**Comment by ahmed-bhs** [comment]
@rotunomp hi, I'm facing the same issue did you find any solutions please ?

**Comment by derrabus** [comment]
Does #6072 fix the issue for you?
