### ISSUE TITLE
How to replace postConnect event

### ISSUE THREAD

**Issue by simPod** [doctrine/dbal#5817]
|    Q        |   A
|------------ | -----
| Version     | 3.5.1

### Support Question

_I wanted to ask in https://github.com/doctrine/dbal/issues/5784 but there was some guy that caused the issue to be locked._

I'm using

`SET application_name TO .....` query in `postConnect` event listener. What is the recommended way to replace it?

I have taken a look on middlewares but it somehow does not fit into the design. I need to call the query just right after when dbal is connected.

**Comment by eugene-borovov** [comment]
Why don't middleware work for you? I use [InitializeSession middleware](https://github.com/doctrine/dbal/blob/82483595da680180c1d360ea7fbff1ea8fb08142/src/Driver/OCI8/Middleware/InitializeSession.php) for post-connection queries.

**Comment by simPod** [comment]
Oh nice, thanks for example. Got it.
