### ISSUE TITLE
Connection with pdo_ prefix url is not working

### ISSUE THREAD

**Issue by Itach1Uchixa** [doctrine/dbal#5906]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.5.3

#### Summary

DriverManager parseDatabaseUrl method not detecting scheme of url when database connection url schem has pdo_ prefix
because php's url_parse function returns array only with 'path' key in it when pdo prefixed scheme is used
#### Current behaviour

```Fatal error: Uncaught Doctrine\DBAL\Exception: The options 'driver' or 'driverClass' are mandatory if a connection URL without scheme is given to DriverManager::getConnection(). Given URL: pdo_sqlite3:////var/www/data/db.sqlite in /var/www/vendor/doctrine/dbal/src/Exception.php:67```
#### How to reproduce

Use any connection url with pdo prefixed scheme:
```pdo_sqlite3:////var/www/data/db.sqlite```
For reference my php verion is 8.1
#### Expected behaviour

Scheme detection to work properly

**Comment by derrabus** [comment]
There is no `pdo_sqlite3` driver. The driver is called `pdo_sqlite`.

**Comment by Itach1Uchixa** [comment]
> There is no `pdo_sqlite3` driver. The driver is called `pdo_sqlite`.

It does not matter if you use pdo_ prefix pdo_sqlite, pdo_mysql, pdo_* not working

**Comment by Itach1Uchixa** [comment]
@derrabus 
please check out this:
![image](https://user-images.githubusercontent.com/6389024/217171303-ac4dafff-3781-48af-9dd5-af55742444be.png)

**Comment by derrabus** [comment]
Did you try to use a dash instead of an underscore, as documented here? https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/configuration.html#connecting-using-a-url

**Comment by Itach1Uchixa** [comment]
@derrabus 
here:
![image](https://user-images.githubusercontent.com/6389024/217174426-c3543e94-0b3e-457b-a7d6-eae9f14c80a1.png)

**Comment by Itach1Uchixa** [comment]
> @derrabus here: ![image](https://user-images.githubusercontent.com/6389024/217174426-c3543e94-0b3e-457b-a7d6-eae9f14c80a1.png)

In preg_replace there is clearly underscore. I do not understand why it's there because url standard do not allow underscore in scheme only + or - allowed. The documentation is is correct in this sense but code was changed after that I think

**Comment by Itach1Uchixa** [comment]
@derrabus any other driver without pdo prefix works perfect. The preg_replace regex must be changed to fix this issue

**Comment by derrabus** [comment]
I see. Please submit a PR that fixes the issue + a test that covers your change.
