### ISSUE TITLE
Error for uninitialized variable

### ISSUE THREAD

**Issue by aimeos** [doctrine/dbal#5927]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.6.0

#### Summary

Using `Index::getOptions()` results in an PHP error due to an uninitialized `$options` class variable.

#### Current behaviour

The `$options` class variable in the `Index` schema class isn't initialized by default. Even if it's done in the constructor afterwards, which should prevent the error, PHP 8.2 still throws an error that the class variable in uninitialized if its accessed using `getOptions()`:

https://github.com/doctrine/dbal/blob/85b98cb23c8af471a67abfe14485da696bcabc2e/src/Schema/Index.php#L46

Changing the line to `private array $options = [];` fixes the problem.

#### How to reproduce

```php
$schema = $conn->createSchemaManager()->createSchema();
$table => $schema->getTable('test');
$table->getIndex('idx_text')->getOptions();
```

#### Expected behaviour

`Index::getOptions()` should return an (empty) array

**Comment by derrabus** [comment]
Thanks. Do you want to send a PR to fix that?

**Comment by aimeos** [comment]
Done: https://github.com/doctrine/dbal/pull/5930
