### ISSUE TITLE
The pgsql driver doesn't support streams as BLOB values

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#5938]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.6.x-dev

#### Summary

The `pgsql` driver doesn't support streams as BLOB values while at least `mysqli`, `pdo_mysql` and `pdo_pgsql` do.

#### Current behaviour

An attempt to bind a PHP stream to a `ParameterType::LARGE_OBJECT` parameter of a prepared statement causes type error:

> TypeError: pg_escape_bytea(): Argument #‎​2 ($string) must be of type string, resource given in dbal/src/Driver/PgSQL/Statement.php on line 153

#### How to reproduce

```php
use Doctrine\DBAL\DriverManager;
use Doctrine\DBAL\ParameterType;

$connection = DriverManager::getConnection([
    'driver' => 'pgsql',
    'host'   => '127.0.0.1',
    'user'   => 'postgres',
    'password' => 'Passw0rd',
]);

$stream = fopen('data://text/plain,test','r');
echo $connection->fetchOne('SELECT ?', [$stream], [ParameterType::LARGE_OBJECT]), PHP_EOL;
```

#### Expected behaviour

The script outputs "test".

**Comment by derrabus** [comment]
That is correct. Reading blobs from resources is not supported yet.

But I think we should throw an exception in that case.

**Comment by morozov** [comment]
As I understand, PostgreSQL doesn't support streaming from arbitrary PHP streams to the database (see the [source](https://github.com/php/php-src/blob/fbaa2eb0593b7228d5c8cd70a3be22979afb9cfa/ext/pdo_pgsql/pgsql_statement.c#L367)). I believe the stream needs to be read into memory and then handled as a string (as well as `pdo_pgsql` does it).

**Comment by derrabus** [comment]
> As I understand, PostgreSQL doesn't support streaming from arbitrary PHP streams to the database

Well, there's `pg_lo_create()` and friends, that interface is not really easy to use.

> I believe the stream needs to be read into memory and then handled as a string (as well as `pdo_pgsql` does it).

Let's try that: #5942

**Comment by morozov** [comment]
I recently learned that BLOB and BYTEA are different types in PostgreSQL ([documentation](https://wiki.postgresql.org/wiki/BinaryFilesInDB)). The `pg_lo_*` functions work with BLOBs and allow streaming them to and from the database but BLOB is not a column type, it's a separate type of object (i.e. tables, views, blobs). DBAL maps BLOB columns to BYTEA, which can be written to via an intermediate BLOB and probably can be read from in a similar way but it won't be portable by any means.

**Comment by derrabus** [comment]
Makes sense. In that case, reading the whole resource into a string is probably the best we can do. Thank you!
