### ISSUE TITLE
Composer incompatible PHP requirement for dbal 3.6 and PHP 7.4.33

### ISSUE THREAD

**Issue by fleonardelli-xt** [doctrine/dbal#5939]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.6

#### Summary

Using PHP 7.4.33, trying to install dbal v3.6 gives an error about incompatible PHP requirement.

#### Current behaviour

Running 
`composer require doctrine/dbal:3.6`

Gives the following error:
```
  [InvalidArgumentException]
  Package doctrine/dbal at version 3.6 has a PHP requirement incompatible with your PHP version (7.4.33)

```

#### Expected behaviour

According to this comment https://github.com/doctrine/dbal/pull/5843#issuecomment-1447660290 v3.6 should work with PHP 7.4

**Comment by derrabus** [comment]
We allow PHP 7.4:

https://github.com/doctrine/dbal/blob/e4564fb046b2dc5072d7dd05049913a00974ce9c/composer.json#L34

In addition, DBALs test suite is run on PHP 7.4 on GitHub actions.

This is most certainly not a DBAL problem. Composer has a [support forum](https://github.com/composer/composer/discussions), please ask there.
