### ISSUE TITLE
MariaDB 10.5.2 supports RENAME INDEX

### ISSUE THREAD

**Issue by Khartir** [doctrine/dbal#5940]
### Feature Request

We are currently switching from MySQL 5.7 to MariaDB 10.5. In the process I came across #2583.
In MySQL 5.7 this is solved by using `RENAME INDEX` instead of `DROP INDEX`/`CREATE INDEX`.

MariaDB 10.5.2 [added support for RENAME INDEX](https://mariadb.com/kb/en/alter-table/#rename-indexkey).

Would it be possible to add this to doctrine? Would you be interested in a PR for this?

#### Summary

Add support for MariaDB's `RENAME INDEX` with version > 10.5.2.

**Comment by derrabus** [comment]
Yes, please.

**Comment by bigfoot90** [comment]
MR was merged but this issue is still open

**Comment by derrabus** [comment]
Let's close it then.
