### ISSUE TITLE
PgSQL driver corrupts BLOB values

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#5950]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.6.x

#### How to reproduce
```php
echo $connection->fetchOne('SELECT ?', ['test'], [ParameterType::LARGE_OBJECT]), PHP_EOL;
```

#### Expected output
```
test
```

#### Actual output
```
\x74657374
```

When binding binary values to the statement, the driver must not use `pg_escape_bytea()`. The purpose of this function is to convert binary values to SQL (see examples in the [documentation](https://www.php.net/manual/en/function.pg-escape-bytea.php)) similar to `mysqli_real_escape_string()`.

Note that besides corrupting data, this issue increases the memory usage overheard by 200% (instead of "just" storing the blob in memory, the driver also stores its encoded representation which is twice larger).

UPD: Actually, the behavior of storing BLOB and BINARY values in the database and fetching them is covered by `BlobTest`, and without the escaping, some tests fail. I'm still not sure if the above behavior is correct or not.

**Comment by derrabus** [comment]
> When binding binary values to the statement, the driver must not use `pg_escape_bytea()`.

The problem is that when I don't escape binary data with `pg_escape_bytea()`, the Postgres client would try to parse the string as unicode sequence which it isn't.

I believe that the current implementation is correct in general. I've tested it loacally with the following script. It creates a table `images` with a `BYTEA` field. Then I load the same image file into that table using the `pgsql` and `pdo_pgsql` drivers. For each driver, I use `Connection::insert()`, a prepared statement with the image as resource and a prepared statement with the image as binary string. And finally, I use `ext-pgsql`'s native LO interface to upload the image.

<details>

```php
use Doctrine\DBAL\DriverManager;
use Doctrine\DBAL\ParameterType;

require __DIR__ . '/vendor/autoload.php';

$connection1 = DriverManager::getConnection([
    'driver' => 'pgsql',
    'host' => 'localhost',
    'user' => 'postgres',
    'password' => 'postgres',
    'dbname' => 'doctrine_tests',
]);

$connection1->executeStatement('DROP TABLE IF EXISTS images;');
$connection1->executeStatement('CREATE TABLE images (id BIGSERIAL PRIMARY KEY, image BYTEA)');

$connection2 = DriverManager::getConnection([
    'driver' => 'pdo_pgsql',
    'host' => 'localhost',
    'user' => 'postgres',
    'password' => 'postgres',
    'dbname' => 'doctrine_tests',
]);

foreach ([$connection1, $connection2] as $connection) {
    $connection->insert(
        'images',
        ['image' => fopen(__DIR__ . '/image.png', 'rb')],
        ['image' => ParameterType::BINARY],
    );
    $connection->insert(
        'images',
        ['image' => file_get_contents(__DIR__ . '/image.png')],
        ['image' => ParameterType::BINARY],
    );
    $stmt = $connection->prepare('INSERT INTO images (image) VALUES (:image)');
    $stmt->bindValue(':image', fopen(__DIR__ . '/image.png', 'rb'), ParameterType::BINARY);
    $stmt->executeStatement();
    $stmt->bindValue(':image', file_get_contents(__DIR__ . '/image.png'), ParameterType::BINARY);
    $stmt->executeStatement();
}

$connection = $connection1->getNativeConnection();
assert($connection instanceof \PgSql\Connection);

pg_exec($connection, 'BEGIN');
$oid = pg_lo_create($connection);
$lo = pg_lo_open($connection, $oid, 'w');
pg_lo_write($lo, file_get_contents(__DIR__ . '/image.png'));
pg_lo_close($lo);
pg_exec($connection, "INSERT INTO images (image) VALUES (lo_get($oid))");
pg_lo_unlink($connection, $oid);

pg_exec($connection, 'COMMIT');
```
</details>

Inspecting the table with PHPStorm, I get 9 identical rows.

<img width="412" alt="Bildschirm­foto 2023-03-05 um 19 00 39" src="https://user-images.githubusercontent.com/1506493/222977705-7ea8c7fe-27ed-43d2-a504-ba064b743c69.png">

The file sizes displayed here match the size of the uploaded image. I can download the image from each of them and it's fully intact.

> increases the memory usage overheard by 200% (instead of "just" storing the blob in memory, the driver also stores its encoded representation which is twice larger).

Yes, but the only way around that would be to upload the image as a LO, as far as I can tell.

**Comment by derrabus** [comment]
Regarding your reproducer: ext-pgsql does not perform any type conversions, everything is a string in results fetched from the database: Integers come as numeric strings, binary comes as hex escape sequence and booleans come as `t` and `f` characters. However, I can ask ext-pgsql for the type of each result column which I use for performing primitive type conversions in the driver. PDO should more or less do the same thing.

However, in your case where you `SELECT` the value of a parameter directly, the returned type information is inaccurate. It'll always report as `text`. You'll see the same issue with integers and booleans. The reason for that is that our parameters are typed as `unknown` which means that their types are inferred from the context the parameter is used in. And in your scenario, there's just no context to infer type information from.

Using a prepared statement in a type-safe manner is possible, but I would need to know the types of the parameters already when preparing the statement, see [docs](https://www.postgresql.org/docs/15/sql-prepare.html). This unfortunately is not compatible with our workflow of specifying parameter types when executing a previously prepared statement. Also, ext-pgsql doesn't even expose an API for parameter types: I would need to bypass `pg_send_prepare()` and run a handcrafted `PREPARE` query. Fun times. 🙈

**Comment by morozov** [comment]
@derrabus thanks for the details. I filed this issue before I realized that the logic is covered with a test and it's functionally correct. Escaping the value before passing it to the prepared statement didn't look right, especially given that all code examples I could find use it with plain SQL, not prepared statements.

I'm fine if this issue is closed as "won't fix".

**Comment by derrabus** [comment]
> I'm fine if this issue is closed as "won't fix".

Let's do that. And thank you very much for testing the new driver!
