### ISSUE TITLE
How to replace getEventManager() and methods?

### ISSUE THREAD

**Issue by kevinpapst** [doctrine/dbal#5966]
The deprecation message for `getEventManager()` leads to the discussion #5784, but this does not include many hints how to replace the deprecated logic.  

I tried to find a workaround or examples on how to replace my current implementations, but wasn't lucky. Will my use-case be possible with Doctrine APIs in the future, or do I have to find an application side workaround?

### Support Question

The Event system in general is going to stay I assume, so how can I get a hold of the EventManager and registered listeners? 

My application uses some global EventListeners, some other listeners are injected through optional plugins.
I need to be able to detect and deactivate some of these listeners (identified by an interface) for certain code paths.

Currently I am using code like this:

```php
        $allListener = $connection->getEventManager()->getAllListeners();
        foreach ($allListener as $event => $listeners) {
            foreach ($listeners as $hash => $object) {
                if ($object instanceof MyMetadataSubscriber) {
                    $connection->getEventManager()->removeEventListener([$event], $object);
                }
            }
        }
```

What would be the way forward to replace such code?

**Comment by derrabus** [comment]
> The Event system in general is going to stay I assume

No, DBAL 4 doesn't have an event system. If you still need the event manager for your own events, feel free to create and configure one, but the DBAL connection won't expose an event manager anymore because it doesn't have any use for one.

**Comment by kevinpapst** [comment]
Oh right, now I get it. Your answer finally gave me the right push. 
I am an idiot... I was using `Connection::getEventManager()` for years, which actually worked totally fine (by accident?).

When I change my code to use `EntityManagerInterface::getEventManager()` instead, it still works and the deprecation is solved. My use-case is e.g. listening for `onFlush`, which, now that I think about it, is obviously part of the EntityManager and not the Connection itself 🤷 😁 

Thanks for cleaning up the codebase @morozov and thanks for your quick answer @derrabus much appreciated 👍 sometimes such a short feedback is enough to clarify things.
