### ISSUE TITLE
Date type not converted to PHP's \DateTime object or null

### ISSUE THREAD

**Issue by ovidiuenache** [doctrine/dbal#5972]
|    Q        |   A
|------------ | -----
| Version     | 3.6.1

### Support Question

The [documentation](https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/types.html#date) for the _date_ type states the following:
> Values retrieved from the database are always converted to PHP's \DateTime object or null if no data is present.

For the sake of describing this issue, I have created a view called _view_test_ with two columns:
- id (int)
- created_at (date)

If I run the following code:
```
$result = $this->entityManager->getConnection()
            ->createQueryBuilder()
            ->select('*')
            ->from('view_test')
            ->executeQuery()
            ->fetchAllAssociative();
```

the result I get is the following:
```
array(2) {
  [0]=>
  array(2) {
    ["id"]=>
    int(1)
    ["created_at"]=>
    string(10) "2023-03-23"
  }
  [1]=>
  array(2) {
    ["id"]=>
    int(2)
    ["created_at"]=>
    string(10) "2023-03-31"
  }
}
```

The value of the _created_at_ column is a string and this invalidates the statement from the documentation.

Does it need to be updated or am I missing something?

**Comment by derrabus** [comment]
The DBAL does not guess type mappings from database results. It simply doesn't know that `created_at` is supposed to be mapped to the date type.

**Comment by ovidiuenache** [comment]
Thank you for answering, @derrabus!

I believe this should also be reflected in the [documentation](https://www.doctrine-project.org/projects/doctrine-dbal/en/current/reference/types.html#date). The current wording states that _Values retrieved from the database are always converted to PHP's \DateTime object or null if no data is present._ and this is not correct given the scenario above and the behavior you described.

What is your opinion on this?

**Comment by derrabus** [comment]
The documentation is correct. It documents the `DateType` and if you use the `DateType` it behaves that way. The thing is you don't use it. If you weren't aware of that fact, I'm happy to review any change to the documentation that would've helped you understand that.

**Comment by ovidiuenache** [comment]
Pardon my confusion but would you like to provide more details about what does using the DateType mean and how am I not doing it?

The way I see things is that I am **retrieving** a value from the database (from a column with type _date_) and the documentation of the _date_ type states that values **retrieved** from the database are always converted to PHP's \DateTime object or null.

Thank you!

**Comment by greg0ire** [comment]
You're retrieving a value from the database, from a column with the _SQL_ type date. What you are quoting is the documentation of the _DBAL_ type.  DBAL types are usually used indirectly, through `doctrine/orm`.

**Comment by derrabus** [comment]
> The way I see things is that I am **retrieving** a value from the database (from a column with type _date_)

No, you are retrieving the result of an SQL query. Big difference. The DBAL does not introspect SQL and does not know from what **table column** a **result field** originates. The DBAL doesn't even know it's a date at this point because most databases transfer dates as simple strings.

**Comment by ovidiuenache** [comment]
Thank you for clarifying things for me, @derrabus @greg0ire! We can close this one!

**Comment by derrabus** [comment]
Glad we could help. 🙂
