### ISSUE TITLE
MariaDB support with the type `bit`.

### ISSUE THREAD

**Issue by soundlake** [doctrine/dbal#5979]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.6.1

#### Summary

Support for the recent MariaDB seems missing.

`Unknown database type bit requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.`

MariaDB does have the type name "bit" https://mariadb.com/kb/en/bit/

Unfortunately, it's hard to find from which version MariaDB introduced it.

#### Current behaviour

I get error with `Unknown database type bit requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.`

#### How to reproduce

I set `server_version: mariadb-10.11.2`, and executed `php bin/console doctrine:schema:update --dump-sql`.

#### Expected behaviour

Generating SQLs without an error.

**Comment by derrabus** [comment]
Note that the command that you mentioned is not part of the DBAL but belongs to the ORM.

You are correct, the `BIT` type is not supported by the DBAL. Generally speaking, the DBAL does not guarantee a successful introspection of tables that it cannot create. You probably want to exclude the table in question from the ORM's schema diff.

**Comment by soundlake** [comment]
@derrabus Thank you for the response. I got the message although it took a while to get it.
