### ISSUE TITLE
Destructor in Connection class that calls `close`

### ISSUE THREAD

**Issue by zerkms** [doctrine/dbal#6016]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | no
| RFC         | no

#### Summary

```php
function callme(array $credentials): void {
    $db = $this->createNewPDOInstance($credentials);
    $connection = new Connection(['pdo' => $db], new Driver());
}
```

If you invoke the function above in a loop 100 times - it would create and _retain_ 100 tcp connections to database. And if it's a postgresql with default settings - you would exhaust its connection pool.

It  can be fixed with calling `gc_collect_cycles();` in-between, or with `$connection->close();`.

Why it happens: `Connection` has a circular reference through `_expr` property, so GC does not collect it (and running the function 100 times is not enough to fill the root buffer). More details: https://www.php.net/manual/en/features.gc.collecting-cycles.php

Hence a suggestion: is there a reason to not have a destructor that invokes `->close()` in the `Connection` class?

UPD: okay, I tried it, and it looks like having a destructor won't help for the very same reason - the `$connection` object is not garbage collected :facepalm:

**Comment by derrabus** [comment]
This code does not look like a public DBAL API to me. And even if it was, I wouldn't know what to do with your request, tbh.

I'd like to close the issue, if you agree?

**Comment by zerkms** [comment]
Why `Doctrine\DBAL\Connection` is not a public api?

**Comment by derrabus** [comment]
> Why `Doctrine\DBAL\Connection` is not a public api?

The class is, but the constructor isn't.

https://github.com/doctrine/dbal/blob/47589fdf56929f1510fd9b394c328c31a7ce13fb/src/Connection.php#L171

Apart from that, none of our drivers accept an instantiated PDO connection via the `pdo` parameter. At least not since DBAL 3.0.

https://github.com/doctrine/dbal/blob/47589fdf56929f1510fd9b394c328c31a7ce13fb/UPGRADE.md?plain=1#L1424-L1426

**Comment by zerkms** [comment]
Oh, right, I'm still at dbal v2, and after quick _visual_ check I assumed that part of logic was kept the same. Now I see it has not.
