### ISSUE TITLE
Why did you remove the sharding support?

### ISSUE THREAD

**Issue by juaiglesias** [doctrine/dbal#6021]
Hello everyone! 

I would like to know why did you removed the sharding support for DBAL 3.0. I'm currently trying to implement this in our MySQL database and find out that is not supported for the version of the abstraction layer library we have. I also saw some forks adding this support for DBAL 3 but i would like to know if there was a reason related to the internals or any problem associated that make you drop this feature?

Thank you very much!

**Comment by greg0ire** [comment]
Hi! What are you talking about exactly? I don't know much about sharding but I might be able to help you if you give more details like maybe a link to relevant docs.

**Comment by juaiglesias** [comment]
Hi @greg0ire! Thanks for your anwser.
Yes, i'm talking [about this](https://github.com/doctrine/dbal/issues/3595). I saw [this fork](https://github.com/redantnl/doctrine-dbal-sharding), but I wanted to know why doctrine dropped the support for this. The reasons explained in the issue (which are mixed with the drop of azure federations feature) are lack of integration tests, hard to mantain, no owner, and apparently no use of the feature. Also, "The package is almost entirely decoupled from DBAL which means it can be maintained as a separate library if needed". I guess what I'm trying to find out if is you recommend any library that offers this feature. Thanks!

**Comment by greg0ire** [comment]
AFAIK we don't recommend any specific library.

**Comment by juaiglesias** [comment]
Okay, thanks for the answer btw!
