### ISSUE TITLE
Allow `doctrine/deprecations ^1`

### ISSUE THREAD

**Issue by mitelg** [doctrine/dbal#6042]
#### Summary

Hey there,

I would like to know if it would be desired to allow `doctrine/deprecations ^1.0` for the 2.x version of DBAL. If this would be no problem, I would be happy to provide a PR. As far as I notice it has no API changes, so only a change in the `composer.json` would be necessary. 

This would allow us, to update to `doctrine/orm 2.15.x`, which only allows `doctrine/lexer ^2`, which only allows `doctrine/deprecations ^1.0` :grin: 

Best regards

**Comment by greg0ire** [comment]
Hi! Have you seen https://www.doctrine-project.org/2022/01/22/sunsetting-dbal-2.html ? Let me know if anything is unclear.

**Comment by derrabus** [comment]
> I would like to know if it would be desired to allow `doctrine/deprecations ^1.0` for the 2.x version of DBAL.

We already do.

https://github.com/doctrine/dbal/blob/2.13.9/composer.json#L38

**Comment by mitelg** [comment]
ah nice! sorry, I missed the tag, as it was not on the release page :slightly_smiling_face: :see_no_evil: 

thanks for pointing out!
