### ISSUE TITLE
Add support for CockroachDB

### ISSUE THREAD

**Issue by fwolfsjaeger** [doctrine/dbal#6045]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes

#### Summary
Add support for CockroachDB

[CockroachDB](https://www.cockroachlabs.com/) is a distributed SQL database that is mostly compatible with PostgreSQL: [PostgreSQL Compatibility](https://www.cockroachlabs.com/docs/stable/postgresql-compatibility.html)
There are some incompatibilities requiring a dedicated Doctrine DBAL Driver though.

I would like to add native support for CockroachDB to enable configuring the connection parameters using a database DSN prefixed with pdo_crdb/crdb.

Are there any objections?

**Comment by derrabus** [comment]
I would advise to build that driver as a standalone package.

**Comment by fwolfsjaeger** [comment]
Fine with me, I am using it like that already.

To configure the connection using a custom DSN prefix, like "crdb", the prefix has to be added to the constant \Doctrine\DBAL\DriverManager::DRIVER_MAP though. Would you accept a modification of the DriverManager that allows adding driver mappings?

**Comment by fwolfsjaeger** [comment]
Never mind, I found a solution that doesn't require any changes to the Doctrine DBAL core functionality.

The feature request can be closed, thank you.

**Comment by derrabus** [comment]
> the prefix has to be added to the constant \Doctrine\DBAL\DriverManager::DRIVER_MAP

You should not need to do that. Adding a driver to that constant that we don't ship would be weird, wouldn't it. 🙂 

Thanks, I'm closing the issue. If you publish your package somewhere, please feel free to dump a link here, so others will find it if they're looking for a driver for that DB.

**Comment by fwolfsjaeger** [comment]
> You should not need to do that. Adding a driver to that constant that we don't ship would be weird, wouldn't it. slightly_smiling_face

Adding a mapping to an external driver would definitely be weird ;). I was considering adding mappings using some method.

> Thanks, I'm closing the issue. If you publish your package somewhere, please feel free to dump a link here, so others will find it if they're looking for a driver for that DB.

I will add some more PHPUnit tests and upload the driver to: https://github.com/fwolfsjaeger/doctrine-cockroachdb
