### ISSUE TITLE
Rollback fails with "PDOException: There is no active transaction"

### ISSUE THREAD

**Issue by mykh74** [doctrine/dbal#6049]
### Bug Report

The error is as follows:
```
PDOException: There is no active transaction in 
vendor/doctrine/dbal/src/Driver/PDO/Connection.php:130
Stack trace:
#0 vendor/doctrine/dbal/src/Driver/PDO/Connection.php(130): PDO->rollBack()
#1 vendor/doctrine/dbal/src/Connection.php(1514): Doctrine\DBAL\Driver\PDO\Connection->rollBack()
```

|    Q        |   A
|------------ | ------
| Version     | 3.6.2

#### Summary

It looks like when a commit fails or some other DB errors occur during a transaction, a rollback operation can throw PDOException. The issue is reproducible on PHP 8.1 and started occurring after an upgrade from PHP 7.4.

#### Current behaviour

Doctrine\DBAL\Driver\PDO\Connection->rollBack() throws "PDOException: There is no active transaction"

#### How to reproduce

We do not have clear steps on how to reproduce the bug.

**Assumption**:
Doctrine\DBAL\Driver\PDO\Connection->commit() throws an exception. As a result, a consequent Doctrine\DBAL\Driver\PDO\Connection->rollBack() call throws "PDOException: There is no active transaction"

#### Expected behaviour

Doctrine\DBAL\Driver\PDO\Connection->rollBack() should not throw PDOExceptions. If a transaction is not active, a rollback does nothing.

**Comment by derrabus** [comment]
Wild guess: you're on MySQL or MariaDB and perform DDL statements (like `CREATE TABLE`) within a transaction.

**Comment by greg0ire** [comment]
I'm going to close this but please don't take it the wrong way, it's just I'm fairly sure this is not an issue with the DBAL. Please read https://www.doctrine-project.org/projects/doctrine-migrations/en/stable/explanation/implicit-commits, it should help.

**Comment by mykh74** [comment]
We are on MariaDB 10.6.12. You are right -  we use DDL statements inside a transaction. Thank you for your explanation and quick resolution.
