### ISSUE TITLE
SUPPORT FOR MYSQL 8.0

### ISSUE THREAD

**Issue by marcoslp010** [doctrine/dbal#6052]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no

#### Summary

Hello to all the maintainers of the doctrine , I did not classify it as a bug , because it was after an update of msyql that the error started , some functions changed their name for example to AsBinary which now is st_AsBinary this caused me an error when searching the code to get it solve, but it would be nice to have mysql 8.0 support

**Comment by greg0ire** [comment]
MySQL is supposed to be supported: https://github.com/doctrine/dbal/blob/9a747d29e7e6b39509b8f1847e37a23a0163ea6a/.github/workflows/continuous-integration.yml#L406-L408

**Comment by derrabus** [comment]
MySQL 8.0 is supported.
