### ISSUE TITLE
`AbstractPlatform::supportsCreateDropDatabase` deprecation

### ISSUE THREAD

**Issue by dmaicher** [doctrine/dbal#6063]
|    Q        |   A
|------------ | ------
| Version     | 3.6.3

I'm seeing this deprecation when running my test suite (which uses DoctrineBundle's `DropDatabaseDoctrineCommand`):

```
1x Doctrine\DBAL\Platforms\AbstractPlatform::supportsCreateDropDatabase is deprecated. (AbstractPlatform.php:4158 called by AbstractPlatform.php:3807, https://github.com/doctrine/dbal/pull/5513, package doctrine/dbal)
``` 

Seeing that this method is called internally from within `AbstractPlatform` itself:

https://github.com/doctrine/dbal/blob/4e673be0ecad4ee4fd68c55f686edc098df6a047/src/Platforms/AbstractPlatform.php#L3807

Can we avoid this somehow? Maybe we can use `triggerIfCalledFromOutside`?

**Comment by greg0ire** [comment]
Yes, I think it makes sense in that case. Up to send a PR?
