### ISSUE TITLE
Accessing protected properties is no more possible - Alternative solution ?

### ISSUE THREAD

**Issue by drupol** [doctrine/dbal#6070]
Hi!, 

I'm opening this issue regarding the extended driver we're currently using to access Oracle databases. This extended driver incorporates a `cursor` functionality (_requested in #2572_). You can find the package for Doctrine 2 at the following URL: https://github.com/ecphp/doctrine-oci8.

<details>
  <summary>UML diagram of ecphp/doctrine-oci8 with DBAL 2</summary>

![](https://planttext.com/api/plantuml/png/ZLHDQzj04BtlhnX83Ybft4Cl8H28S5BmmQJKq4i9ORKQoqlsYzbHunBotplwi68rTbiGHfxtthpPsOTkCclYnZkbyfCDG36ZsjWA0NtYN-3HbqXPARRif6ZI9dsgec6o0I-YiPVWRKsQRGp04QfIkyzAgQ0zvgGDmeuyQo5uKG2wp4pQC1YdSuPY-7jBzYVItTPWQhiT9zxBZyEUBYnvUln-lhWSvO1Rnb0TRp_AUk0TV-8oyPZ74D1q9jOdXnu3PtYhVeGLagWMOHsBPqsu9sZF3t0YUzh05H3cs931eOXRD0tZCihwhy06blhhr7l5cZl3VUi5ezn0fAAk2MiXo0GZR-VuUD3oCVEXgf69fJmzxGxyMdmhbeBczbxheRf6DfjsygLE_V0_7aPdNEl6yPSTPJnSXoPDslUglkCeB6CJgk_QDPW5z7QBrOZ9nD9IocMChjlJwtxgkg3Efa5zcMpoQ00cWPtz8m27HN-G-YiuXu3FyuPofBFJTktN41hdFWnhxe21c0XbAtXsEhoikhqCpF5gtwUZR_ANeTwqHrBrFr8nlH5I-z7u3G00)

</details>

Today, I finally decided to upgrade this package for Doctrine 3 and noticed a few key differences.

<details>
  <summary>UML diagram of ecphp/doctrine-oci8 with DBAL 3 (work in progress)</summary>

![](https://planttext.com/api/plantuml/png/bLN1Rfmm4BtxAwpa5edj8PSeXoeeKQGzh58rKYzH51ap2rQnZSP3aghTVw-ziB0Os2G-8F2yvvbvunbk70caHbUCkT_ASBGEMAbouA1h-iCrw0pGCKQAAhyfwxB-bbj9g0maLgehhbM1WfGrd2pFCr5TCcQ41bSB2Vo0NGKB_ykuNsGBe1Am-mnB6GBS1i8Zu2lWscnj-YOGRgqn8CFnSrWI11eCpTZM_aMGnRGe40gFwp4YSuH24fULS8wdtUU3VrHmXygxxx4jv6o8uemBnnzkrrV3rftFB2O4H1zTp-btvYYjvpssVUr1ExOaspGGdZpbmfMGFoV_ldz2pDRvp3c3ax3EVMLBViqHd6rGGcI4Tv0DmSRwYtCTYj3RkzWFmOuK6CUwNB0FYDDRC2GrfiKvlPnCwiNHAQlqUddpMBeOz2FzcMuyoeKcA2Bh5aYMGREDg5lPdfud4S9MD1NT7w2Hl1sg5YXqUqhhQN9GPXkJ_n9L0yw3j7g7V8BncNfNtfnPMyrLSBYNF0dABxREZksEXy1-RAmEes0_DHOdmLxF1ft5SPL7WsGrhVaHxo99lWgFghZGO2SZ-h3LehEcKSwCbKZwLlOnw-JywcXJNqSZPhxFlgx-GFrKQlqzkG6JXp_GVm00)

</details>

In the previous version, doctrine/dbal 2, we heavily used the **inheritance** pattern. However, with the latest version, doctrine/dbal 3, a shift towards the **composition** pattern has been made. In the new version, all the classes are `final` and it no longer permits the use of inheritance. This presents a bit of a challenge as it restricts access to some members, which was not the case before.

While I am a strong supporter of the composition pattern, this change has left me a little apprehensive.

Therefore, I am raising this concern to seek confirmation that the members we used to access in DBAL 2 are now no more accessible with DBAL 3.

### Example

In [OCI8Statement, line 59](https://github.com/ecphp/doctrine-oci8/blob/2556cdffcb1fb6eeae956c4ce11f6fb2578106e7/src/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php#L59), we previously had access to `$this->_paramMap`. However, this is **no longer accessible** as we cannot extend [`Doctrine\DBAL\Driver\OCI8\Statement`](https://github.com/doctrine/dbal/blob/19f0dec95edd6a3c3c5ff1d188ea94c6b7fc903f/src/Driver/OCI8/Statement.php#L26) anymore.

I am looking forward to receiving clarification on these changes and suggestions on how we can adapt to them.

**Comment by derrabus** [comment]
The param map is indeed a structure internal to our statement class. We want to be able to change it in a future release without breaking your code. But since your `Statement` class decorates ours and thus receives all calls that would mutate the param map before ours would, you should be able to maintain your own version of the param map structure that is maybe even tailored to your use-case.

**Comment by drupol** [comment]
Thank you, this is confirming what I was doing in the meantime.
