### ISSUE TITLE
Is there a documentation for all classes and methods?

### ISSUE THREAD

**Issue by murugappanrm** [doctrine/dbal#6079]
|    Q        |   A
|------------ | -----
| Version     | x.y.z
DBAL version | 3.6.4

### Support Question
The documentation appears to be so summary level and i could not find any help in the search either. E.g. needed the documentation on the "lastInsertId()" method and could not find it anywhere. Is there a documentation on all classes and methods? I am really lost when i read the existing documentation. 

Please help!

**Comment by derrabus** [comment]
The existing documentation is the best documentation that we have. Your best alternative would be reading the source code.
