### ISSUE TITLE
Remove `PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead` notification

### ISSUE THREAD

**Issue by mvmaasakkers** [doctrine/dbal#6090]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 2.x

#### Summary

When running composer install version 2.13.x on PHP 8.2 you get the following deprecation message:

`PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead`

While it's not technically a bug I still think it's a good idea to remove those if possible. 

I've already fixed it in a [fork](https://github.com/doctrine/dbal/compare/2.13.9...mvmaasakkers:dbal:2.13.x?expand=1) but there is no branch for 2.x anymore to make a PR against. Unfortunately we're not able to upgrade to 3.0 yet. Could it be possible to release a `2.13.10` anyway?

#### Current behaviour

`composer install` outputs `PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead`

#### How to reproduce

Run composer install doctrine/dbal:2.13.9 with E_DEPRECATED messages enabled on PHP 8.2

#### Expected behaviour

`composer install` doesn't output `PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead`

**Comment by derrabus** [comment]
We don't maintain version 2 anymore.
