### ISSUE TITLE
[Feature request] Change Connection::bindParameters visibility

### ISSUE THREAD

**Issue by VincentLanglet** [doctrine/dbal#6100]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes

#### Summary

Hi,
I'm recently getting deprecations from Doctrine/DBAL
```
User Deprecated: Passing $params to Statement::executeQuery() is deprecated. Bind parameters using Statement::bindParam() or Statement::bindValue() instead. (Statement.php:212 called by *, https://github.com/doctrine/dbal/pull/5556, package doctrine/dbal)
```

This is caused by call like
```
$statement = $em->getConnection()->prepare($sql);
// do things
$statement->executeQuery($params);
```

If I understood currently, it's recommended to do 
```
$statement = $em->getConnection()->prepare($sql);
// do things
foreach ($params as $key => $value) {
    $statement->bindValue($key, $value);
}
$statement->executeQuery();
```

This is basically what does Connection::bindParameters, which also support a `types` array parameter.
Instead of asking developers to do the foreach with keys, values (and types) by themself, 
what do you think about changing the visibility of `Connection::bindParameters` ?

This way can be written:
```
$statement = $em->getConnection()->prepare($sql);
// do things
$em->getConnection()->bindParameters($statement, $params);
$statement->executeQuery();
```

**Comment by derrabus** [comment]
Can you elaborate what `// do things` is and why it has to be done after preparing the statement and before executing it?

Or in other words: Why is this the inferior solution from your perspective?

```php
// do things
$connection->executeQuery($sql, $params);
```

**Comment by VincentLanglet** [comment]
> Or in other words: Why is this the inferior solution from your perspective?
> 
> ```
> // do things
> $connection->executeQuery($sql, $params);
> ```

Didn't think about calling executeQuery method indeed.
This might be enough, it solve almost every my usages.
