### ISSUE TITLE
Mapping results from native SQL queries to DTO's

### ISSUE THREAD

**Issue by szymonmil** [doctrine/dbal#6101]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no

#### Summary

While fetching data from native SQL queries on Connection, like in example:
```php
$connection->executeQuery('SELECT user.id, user.name FROM user')->fetchAll...
```

There is no simple way to map result into DTO's. I suggest to add next `fetch` method, which will get DTO class qualified name as a parameter, and it will try to map result into that class (for example by constructor, but it's not time for implementation suggestions).

Example usage and result:
```php
/** @var array<My\Namespace\SomeDto> $result */
$result = $connection
    ->executeQuery('SELECT user.id, user.name FROM user')
    ->fetchAllObjects(My\Namespace\SomeDto::class);
```

What do you think about it?

**Comment by derrabus** [comment]
> There is no simple way to map result into DTO's.

There is. That's one of the features of the ORM.

> I suggest to add next `fetch` method,

I doubt that this is a good idea. This functionality can be implemented as a layer above the DBAL. I don't see a benefit in deeply integrating it into the result class.

> which will get DTO class qualified name as a parameter, and it will try to map result into that class

Apart from trivial cases, that might not be enough. You'll probably want to leverage the DBAL's type system for that (like the ORM does), so you'll need information on how result fields should be mapped to their DTO counterparts.

The problem that you're trying to solve here is more complicated that it might seem at first glance. Furthermore, we've always tried to keep the DBAL focussed. The functionality that you're proposing should be a separate package imho.

**Comment by greg0ire** [comment]
Agree on all counts
