### ISSUE TITLE
DBAL\Connection->insert() generates invalid SQL when inserting DateTime data for oci8 (Oracle)

### ISSUE THREAD

**Issue by wayne530** [doctrine/dbal#6128]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.6.5

#### Summary

Inserting DateTime data using `DBAL\Connection->insert()` on oci8 (Oracle) fails.

#### Current behaviour

The query fails with:
```
   Doctrine\DBAL\Exception\DriverException  An exception occurred while executing a query: ORA-01843: not a valid month.
```

According to `DateTimeType`, `DateTime` objects are converted to a database value using `$value->format('Y-m-d H:i:s')`, thus producing the following SQL:

```
insert into dbal_test (created_at) values ('2023-08-12 11:40:00');
```

Running this query manually produces the same error:
```
insert into dbal_test (created_at) values ('2023-08-12 11:40:00')
Error report -
ORA-01843: not a valid month
```

Instead, the following insert SQL is required:
```
insert into dbal_test (created_at) values (to_timestamp('2023-08-12 11:40:00', 'YYYY-MM-DD HH24:MI:SS'));
```

#### How to reproduce

Create a simple table:
```
create table dbal_test (
  created_at timestamp
);
```

then execute an insert statement from the corresponding connection:
```
$connection->insert('dbal_test', ['created_at' => new DateTime()], [Types::DATETIME_MUTABLE]);
```

#### Expected behaviour

The query inserts a row with the `created_at` set to the current DateTime.

**Comment by eugene-borovov** [comment]
You should initialize Oracle connection with appropriate NLS date format https://github.com/doctrine/dbal/blob/17d7baff12c60ebbb90420504ff63cefff8e021e/src/Driver/OCI8/Middleware/InitializeSession.php

**Comment by derrabus** [comment]
@eugene-borovov is correct. If you want to use DBAL's type system on Oracle, you should use that middleware for initializing the proper NLS settings.

**Comment by wayne530** [comment]
@eugene-borovov @derrabus Thanks for the additional information. Although it is deprecated in favor of the corresponding Middleware, my understanding is that the older pattern of using an `EventSubscriber` still works, and we are using `OracleSessionInit`, which presumably is setting these NLS_* session attributes. Should we expect that `OracleSessionInit` will still work or should we move to the middleware?

**Comment by wayne530** [comment]
~~I switched to the `wrap` middleware and it's working fine. I suspect that means `OracleSessionInit` may no longer be working as a `postConnect` listener? Happy to do some additional testing if you'd like - just let me know.~~

Never mind - I just realized the old listener was scoped for a specific connection, which was not the one being used for this particular failing example. All is good. Thanks for the help!

**Comment by wayne530** [comment]
Actually, the new middleware doesn't seem to allow additional session attributes to be set like the old `postConnect` listener did. What is the recommended way of dealing with this? Writing our own additional wrapper/listener? It would be nice if something being deprecated/replaced would have its replacement contain an identical feature set or a super set of the old thing.

**Comment by derrabus** [comment]
Yes, wire your own middleware that applies those additional settings you need.
