### ISSUE TITLE
Add ArrayParameterType binary

### ISSUE THREAD

**Issue by shyim** [doctrine/dbal#6133]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no

#### Summary

We use for our UUID the binary format in MySQL. It seems like since MySQL 8.0.34 ArrayParameterType::STRING is not working well anymore. Single ParameterType::BINARY works fine, but that does not work with `IN(:ids)`. 

So my suggestion would be to add to ArrayParameterType also Binary so we can pass arrays of binary data.

**Comment by derrabus** [comment]
See #5994
