### ISSUE TITLE
2.13.9 -> 2.13.10 - release

### ISSUE THREAD

**Issue by vrestihnat** [doctrine/dbal#6173]
Please make a small change to 2.13.9 and publish release 2.13.10
see
[https://github.com/doctrine/dbal/compare/2.13.9...dek-cz:dbal:2.13.10?expand=1](https://github.com/doctrine/dbal/compare/2.13.9...dek-cz:dbal:2.13.10?expand=1)

Thank you

**Comment by greg0ire** [comment]
Sorry, DBAL 2 is no longer maintained: https://github.com/doctrine/dbal/blob/31919d2aa03d8eab5239620298e8e7e293ac5dcb/.doctrine-project.json#L68-L71
