### ISSUE TITLE
Regression for type="array"

### ISSUE THREAD

**Issue by sdespont** [doctrine/dbal#6174]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 3.7.0

#### Summary
Tehre is a regression with a last version

#### Current behaviour

Since I have upgraded from 3.6.7 to 3.7.0, the following field

    `<field name="tags" type="array" column="tags" length="50" nullable="true"/>`

want always be updated on MariaDB 10.6 and MySQL 5.7 with 

`ALTER TABLE letter CHANGE tags tags TINYTEXT DEFAULT NULL COMMENT '(DC2Type:array)';`

![image](https://github.com/doctrine/dbal/assets/646632/855cbfbe-c3f5-4cc8-8ff8-05aba3a585e7)

Even if the instruction is executed, the dbal library still has to update the field.

#### How to reproduce

Define a field in XML file with `<field name="tags" type="array" column="tags" length="50" nullable="true"/>`

Run php bin/doctrine orm:schema-tool:update --force --env=prod  --complete -v

#### Expected behaviour

The schema must not be updated because the field is already correct

**Comment by greg0ire** [comment]
Does your screenshot show database comments?

Also, to troubleshoot this, you can take a look at this variable: https://github.com/doctrine/orm/blob/62ed63bbbe3f59dcacb7dadb574895f5cb27a257/lib/Doctrine/ORM/Tools/SchemaTool.php#L989

Hopefully it will let you know if the diff is about the type, the default value, or the SQL comment.

**Comment by sdespont** [comment]
@greg0ire Thank you for your reply. Yes, the comments are displayed. In fact, there is an existing comment added by the doctrine declaration to the "tags" fields, even if the comment is not defined in the XML field definition.

![image](https://github.com/doctrine/dbal/assets/646632/dd0dba44-318c-47f0-be92-2af51dec1b53)

Why is a comment now automatically generated by Doctrine?

**Comment by greg0ire** [comment]
> Why is a comment now automatically generated by Doctrine?

I've wondered about that in the past, and documented my findings here: https://www.doctrine-project.org/projects/doctrine-dbal/en/3.7/explanation/dc2type-comments.html

**Comment by ausi** [comment]
This looks similar to #6168 I think.

@sdespont can you check if this issue still appears in version 3.7.1

**Comment by sdespont** [comment]
@ausi @greg0ire I confirm that the problem is fixed in version 3.7.1

Thank you for your support !
