### ISSUE TITLE
Expose current transaction level in Driver\Connection

### ISSUE THREAD

**Issue by ro0NL** [doctrine/dbal#6180]
Hi,

The `onTransactionCommit` event was deprecated/removed: https://github.com/doctrine/dbal/pull/5785

I find myself lost in trying to recreate it using connection middlewares: https://github.com/doctrine/orm/discussions/10973

Using `wrapperClass` config i can get the doctrine event manager, as well as the current transaction level.

Before proceeding with this approach, i'd like to ask if it's possible to expose the current transaction level in the driver connection.

Then i could dispatch my own event using any dispatcher.

**Comment by derrabus** [comment]
The transaction nesting level is tracked on the wrapper connection. Why would we need it on the driver level?

**Comment by ro0NL** [comment]
id like to dispatch postcommit event, and tell existing listeners it's the most outer transaction yes/no. Thus when the flush is persisted to DB and we can proceed updating eg. external parties.

**Comment by ro0NL** [comment]
> The transaction nesting level is tracked on the wrapper connection

hence im considering `wrapperClass` as extension point instead, but it feels im relying on something dirty that can be deprecated any time.

I dont want to take the 'decorating EntityManagerInterface' route either :sweat_smile: 

However, since you mentioned 'tracking' im now thinking i could track the 'final flush' using `postFlush` event

**Comment by ro0NL** [comment]
:facepalm: i can track the transaction level myself at driver/connection level by overriding `beginTransaction` et al

**Comment by derrabus** [comment]
> 🤦 i can track the transaction level myself at driver/connection level by overriding `beginTransaction` et al

Note that nested transactions are emulated through savepoints, which means that the driver's `beginTransaction()` is only called for the outermost transaction.

**Comment by ro0NL** [comment]
i double checked Dbal\Connection also only commits the outer transaction :sweat_smile: it's fine

i followed the same approach done here https://github.com/symfony/symfony/blob/6ef211d04ff038cef1c711cdf2e6cdf021324d7c/src/Symfony/Bridge/Doctrine/Middleware/Debug/DBAL3/Connection.php#L28
