### ISSUE TITLE
Sqlite version

### ISSUE THREAD

**Issue by karinarastsinskagia** [doctrine/dbal#6181]
Hello,

I would like to ask a question about the SQLite database. More specifically, which version of sqlite, this package, is using? Also, is there a way to define its version through configuration or to update it to the latest one?

**doctrine/dbal : 3.7.1**

Thanks a lot

**Comment by derrabus** [comment]
DBAL uses whatever SQLite version your PHP interpreter is linked against. Run `php -i` to find out.
