### ISSUE TITLE
Decouple `doctrine_type_mappings` from database platform

### ISSUE THREAD

**Issue by boesing** [doctrine/dbal#6201]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes

#### Summary

Due to the way how the `doctrine_type_mappings` are currently configured, this always requires some kind of database connection to determine the server version as it is registered to the database platform.

I wonder if it is possible to have those type mappings passed to the connection instead, so that these will be registered once `getDatabasePlatform` is actually called rather than having to call it while registering these mappings:

https://github.com/doctrine/DoctrineORMModule/blob/7cc1cfcb855007cbaedfa86417fccb3b4477623e/src/Service/DBALConnectionFactory.php#L63-L65

This would most probably avoid database connection to be opened for whatever workflow which does not even involve the database but have a service with the entitymanager injected.

**Comment by derrabus** [comment]
You could wire a middleware that registers the type mappings once the connection has been established. That's something that can be fixed in DoctrineORMModule.
