### ISSUE TITLE
PostgreSqlPlatform deprecated

### ISSUE THREAD

**Issue by halfik** [doctrine/dbal#6206]
### Bug Report

If you try to use dbal with new postgresql (i think version does not matter) and php 8.2 you will get warnnings like this one:

"<br />
<b>Deprecated</b>:  Using ${var} in strings is deprecated, use {$var} instead in 
<b>/var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/PostgreSqlPlatform.php</b> on line 
<b>874</b>
<br />"

#### Summary

PostgreSqlPlatform is flaged as deprecated. Problem is all versions that are not 94 and 100 - are extending each other to the point where PostgreSqlPlatform is always in use:

PostgreSQL100Platform extends PostgreSQL94Platform
PostgreSQL94Platform extends PostgreSQL92Platform
PostgreSQL92Platform extends PostgreSQL91Platform (deprecated)
PostgreSQL91Platform extends PostgreSqlPlatform (deprecated)
PostgreSqlPlatform (deprecated)

So proper class is selected if u use 10+ pgs db, but it does not matter. You always inherit from multiple deprecated versions anyway.

#### Current behaviour

Usage of deprecated classes that are not updatewd to work with php 8.2

#### How to reproduce

Just use pgs10+ with php 8.2 and on some requests it will throw this notification. Didnt find when it does it throw and when does not. Since it can throw in one request and not on antother request to same endpoint.

#### Expected behaviour

If PostgreSqlPlatform is deprecated, then whole part of code there has to be cleaned up. Situation where we have 3+ layers of inheritance over deprecated classes is not welcomed.

Would be nice to have base class and probably some interface that is compatible with php 8.2 to prevent this notification. So this base class could be use for 94 and 100 versions. Also composition over inheritance.

**Comment by andrew-demb** [comment]
What version of DBAL do you use?

**Comment by halfik** [comment]
> What version of DBAL do you use?

Im using laravel-doctrine/orm with lumen in project i found this issue. So its "^2.13.3" version of dbal.
I know its very old one but can't upgrade to 3+ since laravel-doctrine/orm won't let me.

Ok i did check newer version of laravel-doctrine and it does use 3.2 version of dbal where problem seems solved (based on code i see in repo). So problem is with my project only not able to upgrade to latest version of laravel-doctrine/orm. 

Close this issue then.
