### ISSUE TITLE
Swoole Connection Pooling with Doctrine

### ISSUE THREAD

**Issue by Merchant6** [doctrine/dbal#6225]
Is it possible to use  Swoole connection pooling with Doctrine DBAL. This is my current Entity Class Constructor:

```
 public function __construct()
 {
        $config = require(__DIR__ . '/../Config/database.php');

        $pool = new \Swoole\ConnectionPool(
            function() use($config){
                return DriverManager::getConnection($config['db']);
            }, 100000
        );

        $this->entityManager =  EntityManager::create($pool->get(), Setup::createAttributeMetadataConfiguration([__DIR__ . '/../Entity']));
 }
```    

This is currently working but I don't know how to test the connection pool and also is this a right approach.

**Comment by derrabus** [comment]
I think, you should ask this kind of question through one of Swoole's support channels instead. We don't maintain any integration layer with Swoole on our side.
