### ISSUE TITLE
DB2 Statement exception occured when Schema-manager instance lists tables

### ISSUE THREAD

**Issue by horizontitph** [doctrine/dbal#6227]
### Bug Report

In PHP Symfony I used controller that should read the database structure and list the tables and columns in the database.
With PostgreSQL database controller works OK, but with DB2/ZOS it throws DBAL exception. 

- Operating System: Windows 11
- PHP Version: 8.2.10
- Symfony Version : 5.7.2
- Doctrine Version: 2.7.1-DEV
- Database: DB2 Z/OS 13.0

#### Summary
Simple controller is used to list tables and columns from the database using Doctrine and DBAL.
The controller is using Schema-manager instance and lists the tables with listTables method.
With the PostgreSQL database the code works as expected and lists all tables and their columns.
With the DB2/ZOS database the code is throwing StatementError exception.

#### Current behaviour

The controller in returning Doctrine\DBAL\Driver\IBMDB2\Exception\ StatementError 
[IBM][CLI Driver][DB2] SQL0206N "CURRENT_USER" is not valid in the context where it is used. SQLSTATE=42703
the problem occurs when SQL query SELECT CURRENT_USER FROM sysibm.sysdummy1 is executed.
In DB2/ZOS this sql query is invalid.
I found the the correct sql query for DB2/ZOS should use single quotes around keyword CURRENT_USER
So the correct sql query syntax for DB2/ZOS is SELECT 'CURRENT_USER' FROM sysibm.sysdummy1
The query SELECT CURRENT_USER FROM sysibm.sysdummy1 propably returns correct result in DB2 LUW.

#### How to reproduce

Controller code used to list the database tables and columns:

```php
namespace App\Controller;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\DBAL\Connection;

class PgtestsuiteController extends AbstractController
{
    #[Route('/pgtestsuite', name: 'app_pgtestsuite')]
    public function index(Connection $conn): Response
    {
		$schemaManager = $conn->getSchemaManager();
		$tables = $schemaManager->listTables();
		//dump($tables);
		foreach ($tables as $table) {
    echo "<b>Table name: " . $table->getName() . "</b><br>";

    // get information about the columns in the table
    $columns = $table->getColumns();

    foreach ($columns as $column) {
        echo "Column name: " . $column->getName() . "<br>";
        echo "Column type: " . $column->getType()->getName() . "<br>";
    }
}
        return $this->render('pgtestsuite/index.html.twig', [
            'controller_name' => 'PgtestsuiteController',
        ]);
    }
}
```

#### Expected behaviour
The code should print table names and columns for DB2/ZOS database.

**Comment by derrabus** [comment]
We don't support DB2 on z/OS, sorry. We can only support databases that we can test on. Unless someone donates a permanently running IBM mainframe to the Doctrine project, we can't possibly maintain such a driver.

**Comment by horizontitph** [comment]
Thank you for confirmation that the DB2/ZOS  database is not supported.
It is valuable information for our development project.
