### ISSUE TITLE
AbstractPlatform::canEmulateSchemas() deprecation exception

### ISSUE THREAD

**Issue by arsrobota** [doctrine/dbal#6228]
|    Q           |   A
|------------| -----
| Version     | 3.7.2

### Support Question

Hello,
I am upgrading a Symfony project. The target version uses `doctrine/doctrine-bundle` 2.11.1, `doctrine/orm` 2.17.1 and `doctrine/dbal` 3.7.2. At runtime I get the exception `User Deprecated: AbstractPlatform::canEmulateSchemas() is deprecated. (AbstractPlatform.php:4132 called by DefaultQuoteStrategy.php:45, https://github.com/doctrine/dbal/pull/4805, package doctrine/dbal)`.
I cannot figure out if I have anything else to configure or update to avoid calling AbstractPlatform::canEmulateSchemas() is deprecated.

Does anybody have information about that ?
Thanks a lot.

Alecz

**Comment by derrabus** [comment]
First of all, if your application turns deprecations into exceptions, this is a clear misconfiguration on your side. Your error handler may log deprecations, but it should never turn them into an exception.

The exception says that the call came from `DefaultQuoteStrategy` which is an ORM class. You probably can't do much about it on your side. If you feel like this issue should be fixed, please report it to https://github.com/doctrine/orm/ instead.
