### ISSUE TITLE
Schema's getMigrateFromSql always adds CREATE SCHEMA public [Still not fixed]

### ISSUE THREAD

**Issue by Arkemlar** [doctrine/dbal#6243]
### Bug Report

With PostgreSQL

|    Q        |   A
|------------ | ------
| Version     | 3.6.4

#### Summary

All the generated down() methods start with a "CREATE SCHEMA public" line.

⚠️ This bug exists since 2015 (!!!). Previous topic is https://github.com/doctrine/dbal/issues/1110 which is closed for no reason (no fix has been done).

#### Current behaviour

`console doctrine:migration:diff` generates:
```php
/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20231220030603 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
    }
}
```

#### How to reproduce

Just use PostgreSQL with public schema (I suppose it is sufficient).
I have this:
![изображение](https://github.com/doctrine/dbal/assets/19671202/f8a75a6e-c4f6-4cf9-8f5c-42156fa0bb8e)

#### Expected behaviour

It should not add "CREATE SCHEMA public" line.

**Comment by greg0ire** [comment]
Hey @Arkemlar , the "How to reproduce" section is supposed to be filled with code allowing to reproduce the issue without any extra software (such as `doctrine/migrations` or `doctrine/orm`). Can you maybe write a DBAL test that exhibits the issue?

**Comment by greg0ire** [comment]
Fixed by https://github.com/doctrine/migrations/pull/1463
