### ISSUE TITLE
 DBAL 4 MySQL COLLATION 'utf8_bin' is not valid for CHARACTER SET 'utf8mb4'" at

### ISSUE THREAD

**Issue by alexander-schranz** [doctrine/dbal#6281]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | ^4.0@dev

#### Summary

I'm currently test dbal 4 against jackalope doctrine dbal adapter and get the following error on mysql. As I can not find `utf8_bin` inside its code base I think its related to dbal 4 changes.

https://github.com/jackalope/jackalope-doctrine-dbal/actions/runs/7669224337/job/20902692362?pr=436

#### Current behaviour

The first error on MySql 5.7 was:

```
Message was: "Error inside the transport layer: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION
'utf8_bin' is not valid for CHARACTER SET 'latin1'" at
```

Then I upgraded to MySQL 8.0:

```
Message was: "An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION
'utf8_bin' is not valid for CHARACTER SET 'utf8mb4'" at
```

#### How to reproduce

This pull request should allow to reproduce: https://github.com/jackalope/jackalope-doctrine-dbal/pull/436

There is a `blob` field which I think is causing the problem: https://github.com/jackalope/jackalope-doctrine-dbal/blob/a0706b48d07fcedbc8c9062f59eb54ddc22b4e65/src/Jackalope/Transport/DoctrineDBAL/RepositorySchema.php#L122

#### Expected behaviour

Think the corec collation should be used.

**Comment by derrabus** [comment]
Can you try to isolate the problem a bit further? I'm not familiar with the codebase of that library.

**Comment by alexander-schranz** [comment]
Looks the error is unrelated to dbal. Atleast the utf8_bin coming from here not from dbal default definitions: https://github.com/jackalope/jackalope-doctrine-dbal/blob/607ff5d81c81b9cc0db7194e1a770d10b24203f5/src/Jackalope/Transport/DoctrineDBAL/Client.php#L381-L391

**Comment by alexander-schranz** [comment]
@derrabus the unexpected behaviour seems to be that we not longer know what encoding the database is using. before it always was `utf8` in doctrine/dbal 3, defined here as a default: https://github.com/doctrine/dbal/blob/79ea9d6eda8e8e8705f2db58439e9934d8c769da/src/Platforms/AbstractMySQLPlatform.php#L581.

And it seems doctrine/dbal 4 not longer defines a default charset, and so it uses whatever the server defined as default charset, which did end in the unexpected behaviour as our logic is build currently ontop that if now `charset` defined it is utf8.
