### ISSUE TITLE
Password authentication failed DBAL v4 and ORM v3

### ISSUE THREAD

**Issue by andreybolonin** [doctrine/dbal#6296]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 4.0

#### Summary

Just only update DBAL from v3 to v4 and ORM from v2 to v3
And getting this error in Gitlab CI

#### Current behaviour

<img width="1016" alt="Screenshot 2024-02-05 at 10 03 17" src="https://github.com/doctrine/dbal/assets/2576509/bae461b8-c8a0-46d9-8a8f-cfd5bd8a07d4">

**Comment by andreybolonin** [comment]
My DSN

<img width="602" alt="Screenshot 2024-02-05 at 10 05 22" src="https://github.com/doctrine/dbal/assets/2576509/27397892-b342-4787-9d4b-24528c5e7a7b">

Gilab CI params
<img width="325" alt="Screenshot 2024-02-05 at 10 07 13" src="https://github.com/doctrine/dbal/assets/2576509/9cc53464-89fd-4f43-84af-0c04ce9b7b72">

**Comment by derrabus** [comment]
Please try to reproduce this problem using DBAL APIs only.

**Comment by andreybolonin** [comment]
@derrabus for me no problem to stay at v3.
You can do nothing about this error :)
Thanks
