### ISSUE TITLE
Impossible to create a user

### ISSUE THREAD

**Issue by guirou62** [doctrine/dbal#6297]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 4.0.0

#### Summary

When you try to create all the security service on symfony and more specially to create the User entity thanks to make:user, we have an error message

#### Current behaviour

The error message : Undefined constant Doctrine\DBAL\Types\Types::ARRAY

#### How to reproduce

Create a symfony project (on lts/6.4 for exemple, I didn't try on 7.*).
On your console, you put "php bin/console make:user", just press "Enter" to every questions.
It creates the user entity (but partially completed) and the user repository but we have an error : Undefined constant Doctrine\DBAL\Types\Types::ARRAY

#### Expected behaviour

My Entity should correctly generated.

=> To correct this problem, I had to downgrade to 3.8.1 version

**Comment by derrabus** [comment]
Please report this issue to https://github.com/symfony/maker-bundle
