### ISSUE TITLE
Doctrine\ORM\QueryBuilder::setParameter and ArrayParameterType in 4.0.0

### ISSUE THREAD

**Issue by hanishsingla** [doctrine/dbal#6309]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 4.0.0

#### Summary

`Doctrine\ORM\QueryBuilder::setParameter()` needs an optional parameter for complex data types sometimes and in 3.x version, it expects `string|int|null` and can be linked via `Doctrine\DBAL\Connection` e.g. `Doctrine\DBAL\Connection::PARAM_STR_ARRAY`. These values used to be as int datatype and has been deprecated. Now these constants are linked to `Doctrine\DBAL\ArrayParameterType` class. In 4.0.0 class ArrayParameterType has been converted to Enums but setParameter() is still accepting old `string|int|null` resulting following error

#### Current behaviour

`Doctrine\ORM\QueryBuilder::setParameter(): Argument #3 ($type) must be of type string|int|null, Doctrine\DBAL\ArrayParameterType given`

#### How to reproduce

```
return $this->createQueryBuilder('t')
	->where('t.id IN (:Ids)')
	->setParameter('Ids', $Ids, ArrayParameterType::STRING)
	->getQuery()
	->getResult() ;
```

#### Expected behaviour

`Doctrine\ORM\QueryBuilder::setParameter()` should accept `Doctrine\DBAL\ArrayParameterType`

**Comment by derrabus** [comment]
PR welcome.
