### ISSUE TITLE
Got error on SQLite database creation stage

### ISSUE THREAD

**Issue by oleksiivelychko** [doctrine/dbal#6330]
|    Q        |   A
|------------ | -----
| doctrine/dbal     | 4.0.1
| doctrine/orm     | 3.0.2
|doctrine/doctrine-bundle | 2.11.3

### Support Question

I try to create SQLite database:
```
symfony console doc:d:create --env=test
```
...where I have the connection string in my **.env.test**:
```
DATABASE_URL="sqlite:///%kernel.project_dir%/var/data.db"
```
but I'm getting the error:
```
Could not create database MY_PROJECT_DIR/var/data.db for connection named default
Operation "Doctrine\DBAL\Platforms\SQLitePlatform::getCreateDatabaseSQL" is not supported by platform.
```
I debugged it in `vendor/doctrine/dbal/src/Platforms/SQLitePlatform.php` as well:
```php
public function getCreateDatabaseSQL(string $name): string
{
     throw NotSupported::new(__METHOD__);
}
```

What's wrong? Maybe, I missed something?
Thanks.

**Comment by derrabus** [comment]
What would you expect to happen instead?

**Comment by oleksiivelychko** [comment]
Something like that:
```
Created database "symfony" for connection named default
```
...when I'm doing **php bin/console doctrine:database:create** for Postgres

**Comment by derrabus** [comment]
So, the command should display that message although it didn't create any database?

**Comment by oleksiivelychko** [comment]
Yes, right you are. The exception **NotSupported** is raised instead. I've switched to Postgres as test database, however I wonder what happened with SQLite.

**Comment by derrabus** [comment]
Running that command on SQLite just doesn't make any sense. There is no database that could be created. That's why I asked about your expectations. I mean, you must've expected something to happen when running that command. I mean something beyond a nice message.

**Comment by oleksiivelychko** [comment]
I sorted out. Everything works. I mixed up some console commands. I expected to get the created DB schema with all my tables. I created manually db.sqlite file and ran **symfony console d:schema:create**.
