### ISSUE TITLE
Incorrect definition of table mysql.column_stats MariaDB OOM-kill

### ISSUE THREAD

**Issue by sts-ryan-holton** [doctrine/dbal#6349]
:wave: Hi,

I'm hoping to try and clear something up here. Recently, I've updated my Laravel project from Laravel 10 to Laravel 11. Laravel 11 [no longer](https://laravel.com/docs/11.x/upgrade#doctrine-dbal-removal) requires the `dbal` package.

I run MariaDB 10.11.6 in my production server. Earlier this week my database crashed due to a **oom-kill** error, first I thought it could be linked to Laravel 11 directly and so [opened this](https://github.com/laravel/framework/issues/50807) (which is worth checking out).

Essentially, ever since updating, the memory usage seems to continue to rise in MariaDB and eventually crash. It rose from around 500mb to over 6gb in 24 hours of memory usage.

A [suggestion](https://dba.stackexchange.com/questions/338180/mariadb-incorrect-definition-of-table-mysql-column-stats) was to run `mariadb-upgrade`, which I did, and everything seems to be fine. However, one thing to note here, is prior to this I was getting:

```
2024-03-29 12:51:31 5813 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
2024-03-29 12:51:31 5813 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
```

**So, my main question is...**

- Does `dbal` utlise anything described in that error above, and since removing the package, the error I'm getting is unmasked, and since upgrading the error has gone away, or is this completely unrelated?

See [the results](https://github.com/laravel/framework/issues/50807#issuecomment-2027970044) before and after...

**Comment by derrabus** [comment]
Thank you for reaching out. However, given that DBAL is clearly not involved, I don't think that you've come to the right place to ask for support.

If your issue started to appear after a Laravel upgrade, it should be tracked and discussed on a Laravel repository.

**Comment by sts-ryan-holton** [comment]
@derrabus No worries. Just thought, since Laravel used quite a lot with DBAL and now it's gone - could've been the answer.
