### ISSUE TITLE
"dbal:run-sql command does not correctly output query results, shows '0 rows affected' instead"

### ISSUE THREAD

**Issue by vkviyu** [doctrine/dbal#6356]
###Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | No
| Version     | doctrine/orm 3.1.0 php8.1.27
#### Summary

When executing a query using the `dbal:run-sql` command, the records are not correctly outputted. Instead, it displays "0 rows affected".

#### Current behavior

When I run the following command:

```bash
php doctrine.php dbal:run-sql "show databases"
```

I expect to see a list of my databases, but what I actually see is "0 rows affected".

#### How to reproduce

1. set the following parameters:

```php
$connectionParams = [
    'user' => 'root',
    'password' => 'kalisita-@',
    'host' => 'localhost',
    'driver' => 'pdo_mysql'
];
$isDevMode = true;
$paths = [ __DIR__ . '/path/to/xml-mappings'];
$config = ORMSetup::createXMLMetadataConfiguration($paths, $isDevMode);
$connection = DriverManager::getConnection($connectionParams, $config);
$entityManager = new EntityManager($connection, $config);

$commands = [
    // ...
];

ConsoleRunner::run(
    new SingleManagerProvider($entityManager),
    $commands
);
```
![image](https://github.com/doctrine/orm/assets/90970572/d3acb941-90a7-4329-8e03-fbca5b6de522)

2. Run the following command:

```bash
php doctrine.php dbal:run-sql "show databases"
```
![image](https://github.com/doctrine/orm/assets/90970572/bf070f21-6e36-4ca4-9c19-45a396035484)

#### Expected behavior

I expect to see a list of my databases, not "0 rows affected". I'm not sure if the latest version of doctrine/orm has fixed this bug, but for some reasons, I can't upgrade my PHP version.

**Comment by greg0ire** [comment]
This seems to be the cause: https://github.com/doctrine/dbal/blob/c70bae9e69e0e543044d5e282a624d9b3cbea6fb/src/Tools/Console/Command/RunSqlCommand.php#L80

I don't know if we should support `show` as it is MySQL-specific…

**Comment by greg0ire** [comment]
Ah and it seems to be already covered by `--force-fetch`. Please try it.
