### ISSUE TITLE
COLLATION_CHARACTER_SET_APPLICABILITY.COLLATION_NAME vs MariaDB FULL_COLLATION_NAME

### ISSUE THREAD

**Issue by rotdrop** [doctrine/dbal#6361]
In recent MariaDB version the following will not succeed (resp. always yields an empty result set):

https://github.com/doctrine/dbal/blob/7fb00fdf7091a3ab0a4b6d0eed12170b4c7c2aa8/src/Schema/MySQLSchemaManager.php#L463-L474

The reason is, that `CCSA.collation_name` in recent MariaDB versions (tested version: 10.11.7) only contains the short collation name without prepended character set, while `TABLES.table_collation` contains the *long* table name. For example, in the case of the newly introduced `utf8mb4_uca1400_ai_ci` the corresponding row from `COLLATION_CHARACTER_SET_APPLICABILITY` is (CSV export):

```
"COLLATION_NAME","CHARACTER_SET_NAME","FULL_COLLATION_NAME","ID","IS_DEFAULT"
"uca1400_ai_ci","utf8mb4","utf8mb4_uca1400_ai_ci","2304",
```

while the `TABLES.TABLE_COLLATION` holds the full collation name `utf8mb4_uca1400_ai_ci`.

It also seems that this is a recent change in MariaDB; one Ubuntu "Jammy" system I am using runs MariaDB 10.6.16 which only has the `COLLATION_NAME` and `CHARACTER_SET_NAME` in that table, and the collation name is the full name with the character set prepended.

**Comment by derrabus** [comment]
Is this a bug report? If yes, please start with answering the usual questions:

* What did you try to do?
* What did you expect to happen?
* What happened instead?

**Comment by rotdrop** [comment]
This is a bug report related to the most recent versions of MariaDB

### What did you try to do?

Running Doctrine/Orm migrations after upgrading to DBAL >= 3 and ORM >=2.20

### What did you expect to happen?

That -- after applying the suggested migrations -- the schema validation tools would no longer complain

### What happened instead?

Endless loop, applying the suggested migrations did not help.

One comment from my side: yes, you receive frequent bug reports, but please read and understand my explanations from the first post, IMHO they are clear and concise. Thank you.

**Comment by greg0ire** [comment]
> but please read and understand my explanations from the first post, IMHO they are clear and concise

Another comment from my side:  @derrabus 's questions are completely on point, it's not far fetched to ask you in what context you stumbled upon this, and it has nothing to do with the clarity or conciseness of your original message. I don't know why you assume your message hasn't been read.
