### ISSUE TITLE
❓ Is there a DBAL constant or similar to easily find which major version is installed?

### ISSUE THREAD

**Issue by llupa** [doctrine/dbal#6365]
|    Q        |   A
|------------ | -----
| Version     | 3 and 4

### Support Question

Because of the latest jump of a major version in a _decade_ (I am very happy it happened!), some changes are proving a bit tricky to handle. Is it possible to add a constant or similar to easily check which version of DBAL is being used? If this is already the case, would anyone from the team be so kind to show where?

Some context: 
- https://github.com/doctrine/orm/issues/11073
- https://github.com/symfony/symfony/issues/54418 
- https://github.com/symfony/symfony/pull/54694

**Comment by derrabus** [comment]
We've had such a constant and removed it, see #3861. If you _really_ need to know the version of the DBAL package at runtime, [you can ask composer](https://getcomposer.org/doc/07-runtime.md#knowing-the-version-of-package-x).
