### ISSUE TITLE
Why some places you use throw new Exception and other static method?

### ISSUE THREAD

**Issue by eerison** [doctrine/dbal#6424]
Hello guys it is just for a question that came up in our team, and the guy used this repo as example.

Do you have the initial discussion for when you decided to use `throw Exception::new();` instead of `throw new Exception();`

and I see that some places you are using `throw new` and others with static method.

e.g:

- https://github.com/doctrine/dbal/blob/cbd0e9adb46ec66f22c163e7003d0f4b2e38c8c7/src/DriverManager.php#L152
- https://github.com/doctrine/dbal/blob/cbd0e9adb46ec66f22c163e7003d0f4b2e38c8c7/src/Driver/PgSQL/Driver.php#L42

Thank you in advance.

**Comment by derrabus** [comment]
Static constructor methods help us standardize how we derive the exception message from given input, in your example an invalid class name.

**Comment by eerison** [comment]
But Couldn't you do like this too?

```php
throw new InvalidWrapperClass($wrapperClass); 
```

**Comment by derrabus** [comment]
Sure.
