### ISSUE TITLE
Unable to setup 'platform' in wrapper `Connection`, but still documented in 4.x

### ISSUE THREAD

**Issue by janedbal** [doctrine/dbal#6459]
#### Summary

Since dbal 4, `'platform'` key cannot be used in `DriverManager::getConnection($params)` ([release note](https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-removed-support-for-the-platform-parameter-of-the-wrapper-connection)), but it is [still present in documentation](https://www.doctrine-project.org/projects/doctrine-dbal/en/4.0/reference/platforms.html).

**Comment by derrabus** [comment]
You are correct, the documentation needs to be updated. PR welcome.

**Comment by janedbal** [comment]
What is the new official proper way? Implementing `Doctrine\DBAL\Driver` and returning the platform from `MyDriver::getDatabasePlatform`?

**Comment by janedbal** [comment]
Now I see this is a duplicate: https://github.com/doctrine/dbal/issues/6354#issuecomment-2051693300

**Comment by derrabus** [comment]
Closing as duplicate then. 🙂
