### ISSUE TITLE
Using connection string without `serverVersion` with postgresql?

### ISSUE THREAD

**Issue by plaes** [doctrine/dbal#6530]
### Bug Report

It seems to be not possible to connect to postgresql database without supplying `serverVersion=...` variable within the `DATABASE_URL` variable, as it crashes with following message:

> In InvalidPlatformVersion.php line 22:
>                                                                                                                                                     
>  Invalid platform version `""` specified. The platform version has to be specified in the format: `"<major_version>.<minor_version>.<patch_version>"`.  

|    Q        |   A
|------------ | ------
| Version     |4.1.1

#### Summary

When setting up an application (see https://github.com/Part-DB/Part-DB-server/issues/722) utilizing postgreSQL, one must also define serverVersion variable within the connection string. This requirement seems a bit excessive (haven't seen this requirement in other ORMs like SQLAlchemy or Diesel).

It also makes automated application deployment a bit more complicated due to the need to define extra variables. (Ie Kubernetes setup with PostgreSQL cluster deployed by CloudNativePg operator where secrets for application are generated automatically).

#### Current behaviour

DBAL seems to fail to determine PostgreSQL version unless `serverVersion=` is supplied with the connection string (`DATABASE_URL`):
https://github.com/doctrine/dbal/blob/7a8252418689feb860ea8dfeab66d64a56a64df8/src/Driver/AbstractPostgreSQLDriver.php#L26-L33

Also, ideally it shouldn't parse the string version of the version, there's also a way to return version number as integer using: `SELECT current_setting('server_version_num');`

#### How to reproduce

1. Prepare [Part-DB application](https://docs.part-db.de/installation/installation_docker.html) with following `DATABASE_URL`:
`DATABASE_URL=postgresql://partdb:partdb@partdb-cluster-rw.partdb:5432/partdb`
2. Attempt to run initial migrations using `docker exec --user=www-data partdb php bin/console doctrine:migrations:migrate
`

#### Expected behaviour

Things work without providing `serverVersion`.

**Comment by derrabus** [comment]
> #### How to reproduce
> 
> 1. Prepare [Part-DB application](https://docs.part-db.de/installation/installation_docker.html) with following `DATABASE_URL`:
> `DATABASE_URL=postgresql://partdb:partdb@partdb-cluster-rw.partdb:5432/partdb`

Please provide a reproducer that uses DBAL APIs only. We cannot provide support for 3rd party code.

**Comment by plaes** [comment]
> > #### How to reproduce
> > 
> > 1. Prepare [Part-DB application](https://docs.part-db.de/installation/installation_docker.html) with following `DATABASE_URL`:
> >    `DATABASE_URL=postgresql://partdb:partdb@partdb-cluster-rw.partdb:5432/partdb`
> 
> Please provide a reproducer that uses DBAL APIs only. We cannot provide support for 3rd party code.

Indeed, this seems to related how application sets up dbal.

When just using DsnParser I was able to run basic product example like this (using `php bin/doctrine orm:schema-tool:update --force --dump-sql`):

```php
<?php
// bootstrap.php
use Doctrine\DBAL\DriverManager;
use Doctrine\DBAL\Tools\DsnParser;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\ORMSetup;

require_once "vendor/autoload.php";

// Create a simple "default" Doctrine ORM configuration for Attributes
$config = ORMSetup::createAttributeMetadataConfiguration(
    paths: [__DIR__ . '/src'],
    isDevMode: true,
);

$dsnParser = new DsnParser();
$connectionParams = $dsnParser
    ->parse('pgsql://partdb:...@localhost:5432/partdb');
$connection = DriverManager::getConnection($connectionParams);

$entityManager = new EntityManager($connection, $config);
```
