### ISSUE TITLE
Comment link redirects to random betting website

### ISSUE THREAD

**Issue by sergiuionescu** [doctrine/dbal#6538]
### Bug Report

|    Q        |   A
|------------ | ------
| Version     | 4.1.1

#### Summary

\Doctrine\DBAL\Schema\PostgreSQLSchemaManager::_getPortableTableIndexesList doc block contains a link to a website that now redirects to a betting website:
```
/**
     * {@inheritDoc}
     *
     * @link http://ezcomponents.org/docs/api/trunk/DatabaseSchema/ezcDbSchemaPgsqlReader.html
     */
    protected function _getPortableTableIndexesList(array $tableIndexes, string $tableName): array
    {
```

#### Current behaviour

The doc bloc is redundant.

#### How to reproduce

Open the file and see the doc bloc.

#### Expected behaviour

The doc block should only link to reputable websites, only if further context is required to describe the chosed solution.

**Comment by derrabus** [comment]
Seems like somebody did not renew the domain for ez Components and some shady person took advantage of that. 🤦🏻‍♂️ 

Thank you for pointing that out to us.
