### ISSUE TITLE
Find a more reliable source of the IBM DB2 CLI driver for CI

### ISSUE THREAD

**Issue by morozov** [doctrine/dbal#6629]
Currently, the host we download the driver from in CI workflows is down, and it happens every now and then:

```
curl https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at
 you@your.address to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
</body></html>
```

It results in intermittent failures on CI.

Apparently there is a GitHub repository containing various versions of the driver: [ibmdb/db2drivers](https://github.com/ibmdb/db2drivers). Not sure how official this organization is but it's been around for about a decade, so it looks reliable.

**Comment by derrabus** [comment]
I'd prefer not to rely on unofficial sources, tbh. So far, that server has always come up again. If it does, can we maybe cache or mirror the drivers somewhere?

**Comment by morozov** [comment]
@derrabus what exactly are your concerns about using an unofficial source?

From the legal perspective, if we stand up our own public mirror, it will be as questionable as the one I proposed to use (I don't know what exactly the binary distribution license is).

From the reliability standpoint, if the source I proposed to use goes down, we can switch back to the official one in a matter of a day (which is more or less the downtime we experience regularly by using the official source).

I'm not pushing towards using that specific source and I want to do some more research to see if there are better alternatives.

**Comment by morozov** [comment]
A few data points:
1. It seems to be legal to redistribute the driver ([source](https://www.ibm.com/support/pages/db2-odbc-cli-driver-download-and-installation-information#%5B%3Ch2%3E%5DLicense%5B%3C%2Fh2%3E%5D)):
   > You can include the driver in your database application installation package, and redistribute the driver with your applications
2. There are public mirrors of the driver ([example](https://docs.guance.com/en/integrations/db2/)).
3. Datadog [references](https://docs.datadoghq.com/integrations/ibm_db2/?tab=host) the Python IBM DB2 driver from `ibmdb` in its documentation.
4. Documents within the IBM organization ([1](https://github.com/IBM/db2-samples/blob/445001528b534843c5b1d71f8676ac211d471d5e/db2_graph/README.md?plain=1#L34), [2](https://github.com/IBM/ibm-cloud-sdk-common/blob/3787346186f13b2b704e48a3aeae8557a49d702d/README.md?plain=1#L86)) reference the Python driver and various SDKs from the `ibmdb` organization.

**Comment by derrabus** [comment]
Thank you for your research! I'm fine with using that mirror then.
